BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_1099_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_ABSENCE_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_AP_INV_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_AR_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_ASSIGNMENT_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_BEN_BENFY_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_BEN_DEPEND_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_BEN_PARTIC_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_BILLING_EVENT_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_BLANKET_PO_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_CONTRACT_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_CUST_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_EXPENDITURE_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_FA_ASSET_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_GL_BAL_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_GL_BUDGET_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_GRANTS_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_MISC_RECEIPT_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_PAY_REL_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_PERF_EVAL_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_PLAN_BUDGET_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_PO_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_PRJ_BUDGET_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_PROJECT_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_SAL_BASIS_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_SALARY_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_SUP_ADDR_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_SUP_CONTACTS_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_SUP_SITE_ASSN_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_SUP_SITE_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_SUPPLIER_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_TALENT_PROF_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_TAX_CARD_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_W2_BAL_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_WORK_SCHED_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW DMT_WORKER_IMP_RPT_V'; EXCEPTION WHEN OTHERS THEN IF SQLCODE IN (-942, -4043) THEN NULL; ELSE RAISE; END IF; END;
/
-- ----------------------------------------------------------------------
-- Migration 2026-09-23: drop the 36 dead *_IMP_RPT_V legacy report views
-- (backlog #31). These views are the documented invalid-object baseline:
-- they were bound to columns that no longer exist on the current STG/TFM
-- tables, so on any database that still carries them they show up as
-- INVALID on every install. They are legacy report views from the original
-- ConversionTool report layer and are NOT part of the DMT2 git-first deploy
-- tree.
--
-- Already removed from git: the 36 create-view files were deleted from
-- db/views in commit 219de95 ("Views + infrastructure tranches"), and none
-- of the 36 names appears in db/install.sql. This migration is the missing
-- database-convergence step: it drops the views from any pre-existing
-- database (the db_full seed / ATP gold) that still carries them, so those
-- installs converge to git and the invalid-VIEW baseline goes to zero.
--
-- Unreferenced: grep-verified that none of the 36 names is referenced
-- anywhere in apex/, db/, or bip/ in the current tree (0 hits per name).
-- No APEX page, engine package, or BIP report reads any of them.
--
-- The 37 summary DMT_*_V / DMT_V_* views were usage-checked in the same
-- backlog item and are all VALID (no INTEGRATION_ID -> RUN_ID column drift
-- on the current schema), so none needed a fix or a drop here -- see the
-- PR body for the per-group audit.
--
-- Idempotent (matches the 2026-09-21 / 2026-09-22 sibling migrations): each
-- DROP is wrapped in a guarded block that swallows ORA-00942 (view does not
-- exist) and ORA-04043 (object does not exist), so a re-run on a database
-- where the views are already gone (e.g. a fresh local install) is a no-op.
--
-- Each executable block is one physical line and leads its chunk on purpose:
-- the deploy runner (scripts/dmt_deploy.py) splits a migration on ";\n" /
-- "/\n" and skips any chunk that begins with "--", so every executable
-- statement must lead and stay on a single line so the split never
-- fragments a block. This trailing comment block is skipped by the runner.
-- ----------------------------------------------------------------------
