"""One-shot generator for the PurchaseOrders gold FBDI templates.

Emits the four position-based CSV templates (no header row) with the exact
column order/counts of the proven DMT PO FBDI generator
(ConversionTool/packages/generators/fbdi/po/dmt_po_fbdi_gen_pkg.pkb):

    PoHeadersInterfaceOrder.csv        99 columns
    PoLinesInterfaceOrder.csv          98 columns
    PoLineLocationsInterfaceOrder.csv  93 columns
    PoDistributionsInterfaceOrder.csv 123 columns

Every field is double-quoted (matching the generator's append style). Only the
positions a PO import actually needs are filled; the rest are empty ("").
${PREFIX} and discovered ${TOKEN}s are left in place for the harness to stamp.

Two good POs (G1, G2) + one bad PO (BAD1). BAD1 carries an invalid supplier
site code so Import Orders rejects it into PO_INTERFACE_ERRORS while the row
still lands in PO_HEADERS_INTERFACE and never reaches PO_HEADERS_ALL.

Run once to (re)generate the templates:
    python objects/PurchaseOrders/build_templates.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ART = os.path.join(HERE, 'artifact')

# ---- exact ordered column lists (from the proven generator) ----------------
HEADERS = "INTERFACE_HEADER_KEY,ACTION,BATCH_ID,INTERFACE_SOURCE_CODE,APPROVAL_ACTION,DOCUMENT_NUM,DOCUMENT_TYPE_CODE,STYLE_DISPLAY_NAME,PRC_BU_NAME,REQ_BU_NAME,SOLDTO_LE_NAME,BILLTO_BU_NAME,AGENT_NAME,CURRENCY_CODE,RATE,RATE_TYPE,RATE_DATE,COMMENTS,BILL_TO_LOCATION,SHIP_TO_LOCATION,VENDOR_NAME,VENDOR_NUM,VENDOR_SITE_CODE,VENDOR_CONTACT,VENDOR_DOC_NUM,FOB,FREIGHT_CARRIER,FREIGHT_TERMS,PAY_ON_CODE,PAYMENT_TERMS,ORIGINATOR_ROLE,CHANGE_ORDER_DESC,ACCEPTANCE_REQUIRED_FLAG,ACCEPTANCE_WITHIN_DAYS,SUPPLIER_NOTIF_METHOD,FAX,EMAIL_ADDRESS,CONFIRMING_ORDER_FLAG,NOTE_TO_VENDOR,NOTE_TO_RECEIVER,DEFAULT_TAXATION_COUNTRY,TAX_DOCUMENT_SUBTYPE,ATTRIBUTE_CATEGORY,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,ATTRIBUTE11,ATTRIBUTE12,ATTRIBUTE13,ATTRIBUTE14,ATTRIBUTE15,ATTRIBUTE16,ATTRIBUTE17,ATTRIBUTE18,ATTRIBUTE19,ATTRIBUTE20,ATTRIBUTE_DATE1,ATTRIBUTE_DATE2,ATTRIBUTE_DATE3,ATTRIBUTE_DATE4,ATTRIBUTE_DATE5,ATTRIBUTE_DATE6,ATTRIBUTE_DATE7,ATTRIBUTE_DATE8,ATTRIBUTE_DATE9,ATTRIBUTE_DATE10,ATTRIBUTE_NUMBER1,ATTRIBUTE_NUMBER2,ATTRIBUTE_NUMBER3,ATTRIBUTE_NUMBER4,ATTRIBUTE_NUMBER5,ATTRIBUTE_NUMBER6,ATTRIBUTE_NUMBER7,ATTRIBUTE_NUMBER8,ATTRIBUTE_NUMBER9,ATTRIBUTE_NUMBER10,ATTRIBUTE_TIMESTAMP1,ATTRIBUTE_TIMESTAMP2,ATTRIBUTE_TIMESTAMP3,ATTRIBUTE_TIMESTAMP4,ATTRIBUTE_TIMESTAMP5,ATTRIBUTE_TIMESTAMP6,ATTRIBUTE_TIMESTAMP7,ATTRIBUTE_TIMESTAMP8,ATTRIBUTE_TIMESTAMP9,ATTRIBUTE_TIMESTAMP10,AGENT_EMAIL_ADDRESS,MODE_OF_TRANSPORT,SERVICE_LEVEL,FIRST_PTY_REG_NUM,THIRD_PTY_REG_NUM,BUYER_MANAGED_TRANSPORT_FLAG".split(',')

LINES = "INTERFACE_LINE_KEY,INTERFACE_HEADER_KEY,ACTION,LINE_NUM,LINE_TYPE,ITEM,ITEM_DESCRIPTION,ITEM_REVISION,CATEGORY,AMOUNT,QUANTITY,UNIT_OF_MEASURE,UNIT_PRICE,SECONDARY_QUANTITY,SECONDARY_UNIT_OF_MEASURE,VENDOR_PRODUCT_NUM,NEGOTIATED_BY_PREPARER_FLAG,HAZARD_CLASS,UN_NUMBER,NOTE_TO_VENDOR,NOTE_TO_RECEIVER,LINE_ATTRIBUTE_CATEGORY_LINES,LINE_ATTRIBUTE1,LINE_ATTRIBUTE2,LINE_ATTRIBUTE3,LINE_ATTRIBUTE4,LINE_ATTRIBUTE5,LINE_ATTRIBUTE6,LINE_ATTRIBUTE7,LINE_ATTRIBUTE8,LINE_ATTRIBUTE9,LINE_ATTRIBUTE10,LINE_ATTRIBUTE11,LINE_ATTRIBUTE12,LINE_ATTRIBUTE13,LINE_ATTRIBUTE14,LINE_ATTRIBUTE15,ATTRIBUTE16,ATTRIBUTE17,ATTRIBUTE18,ATTRIBUTE19,ATTRIBUTE20,ATTRIBUTE_DATE1,ATTRIBUTE_DATE2,ATTRIBUTE_DATE3,ATTRIBUTE_DATE4,ATTRIBUTE_DATE5,ATTRIBUTE_DATE6,ATTRIBUTE_DATE7,ATTRIBUTE_DATE8,ATTRIBUTE_DATE9,ATTRIBUTE_DATE10,ATTRIBUTE_NUMBER1,ATTRIBUTE_NUMBER2,ATTRIBUTE_NUMBER3,ATTRIBUTE_NUMBER4,ATTRIBUTE_NUMBER5,ATTRIBUTE_NUMBER6,ATTRIBUTE_NUMBER7,ATTRIBUTE_NUMBER8,ATTRIBUTE_NUMBER9,ATTRIBUTE_NUMBER10,ATTRIBUTE_TIMESTAMP1,ATTRIBUTE_TIMESTAMP2,ATTRIBUTE_TIMESTAMP3,ATTRIBUTE_TIMESTAMP4,ATTRIBUTE_TIMESTAMP5,ATTRIBUTE_TIMESTAMP6,ATTRIBUTE_TIMESTAMP7,ATTRIBUTE_TIMESTAMP8,ATTRIBUTE_TIMESTAMP9,ATTRIBUTE_TIMESTAMP10,UNIT_WEIGHT,WEIGHT_UOM_CODE,WEIGHT_UNIT_OF_MEASURE,UNIT_VOLUME,VOLUME_UOM_CODE,VOLUME_UNIT_OF_MEASURE,TEMPLATE_NAME,ITEM_ATTRIBUTE_CATEGORY,ITEM_ATTRIBUTE1,ITEM_ATTRIBUTE2,ITEM_ATTRIBUTE3,ITEM_ATTRIBUTE4,ITEM_ATTRIBUTE5,ITEM_ATTRIBUTE6,ITEM_ATTRIBUTE7,ITEM_ATTRIBUTE8,ITEM_ATTRIBUTE9,ITEM_ATTRIBUTE10,ITEM_ATTRIBUTE11,ITEM_ATTRIBUTE12,ITEM_ATTRIBUTE13,ITEM_ATTRIBUTE14,ITEM_ATTRIBUTE15,SOURCE_AGREEMENT_PRC_BU_NAME,SOURCE_AGREEMENT,SOURCE_AGREEMENT_LINE".split(',')

LOCS = "INTERFACE_LINE_LOCATION_KEY,INTERFACE_LINE_KEY,SHIPMENT_NUM,SHIP_TO_LOCATION,SHIP_TO_ORGANIZATION_CODE,AMOUNT,QUANTITY,NEED_BY_DATE,PROMISED_DATE,SECONDARY_QUANTITY,SECONDARY_UNIT_OF_MEASURE,DESTINATION_TYPE_CODE,ACCRUE_ON_RECEIPT_FLAG,ALLOW_SUBSTITUTE_RECEIPTS_FLAG,ASSESSABLE_VALUE,DAYS_EARLY_RECEIPT_ALLOWED,DAYS_LATE_RECEIPT_ALLOWED,ENFORCE_SHIP_TO_LOCATION_CODE,INSPECTION_REQUIRED_FLAG,RECEIPT_REQUIRED_FLAG,INVOICE_CLOSE_TOLERANCE,RECEIVE_CLOSE_TOLERANCE,QTY_RCV_TOLERANCE,QTY_RCV_EXCEPTION_CODE,RECEIPT_DAYS_EXCEPTION_CODE,RECEIVING_ROUTING,NOTE_TO_RECEIVER,INPUT_TAX_CLASSIFICATION_CODE,LINE_INTENDED_USE,PRODUCT_CATEGORY,PRODUCT_FISC_CLASSIFICATION,PRODUCT_TYPE,TRX_BUSINESS_CATEGORY,USER_DEFINED_FISC_CLASS,ATTRIBUTE_CATEGORY,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,ATTRIBUTE11,ATTRIBUTE12,ATTRIBUTE13,ATTRIBUTE14,ATTRIBUTE15,ATTRIBUTE16,ATTRIBUTE17,ATTRIBUTE18,ATTRIBUTE19,ATTRIBUTE20,ATTRIBUTE_DATE1,ATTRIBUTE_DATE2,ATTRIBUTE_DATE3,ATTRIBUTE_DATE4,ATTRIBUTE_DATE5,ATTRIBUTE_DATE6,ATTRIBUTE_DATE7,ATTRIBUTE_DATE8,ATTRIBUTE_DATE9,ATTRIBUTE_DATE10,ATTRIBUTE_NUMBER1,ATTRIBUTE_NUMBER2,ATTRIBUTE_NUMBER3,ATTRIBUTE_NUMBER4,ATTRIBUTE_NUMBER5,ATTRIBUTE_NUMBER6,ATTRIBUTE_NUMBER7,ATTRIBUTE_NUMBER8,ATTRIBUTE_NUMBER9,ATTRIBUTE_NUMBER10,ATTRIBUTE_TIMESTAMP1,ATTRIBUTE_TIMESTAMP2,ATTRIBUTE_TIMESTAMP3,ATTRIBUTE_TIMESTAMP4,ATTRIBUTE_TIMESTAMP5,ATTRIBUTE_TIMESTAMP6,ATTRIBUTE_TIMESTAMP7,ATTRIBUTE_TIMESTAMP8,ATTRIBUTE_TIMESTAMP9,ATTRIBUTE_TIMESTAMP10,FREIGHT_CARRIER,MODE_OF_TRANSPORT,SERVICE_LEVEL,FINAL_DISCHARGE_LOCATION_CODE,REQUESTED_SHIP_DATE,PROMISED_SHIP_DATE,REQUESTED_DELIVERY_DATE,PROMISED_DELIVERY_DATE".split(',')

DISTS = "INTERFACE_DISTRIBUTION_KEY,INTERFACE_LINE_LOCATION_KEY,DISTRIBUTION_NUM,DELIVER_TO_LOCATION,DELIVER_TO_PERSON_FULL_NAME,DESTINATION_SUBINVENTORY,AMOUNT_ORDERED,QUANTITY_ORDERED,CHARGE_ACCOUNT_SEGMENT1,CHARGE_ACCOUNT_SEGMENT2,CHARGE_ACCOUNT_SEGMENT3,CHARGE_ACCOUNT_SEGMENT4,CHARGE_ACCOUNT_SEGMENT5,CHARGE_ACCOUNT_SEGMENT6,CHARGE_ACCOUNT_SEGMENT7,CHARGE_ACCOUNT_SEGMENT8,CHARGE_ACCOUNT_SEGMENT9,CHARGE_ACCOUNT_SEGMENT10,CHARGE_ACCOUNT_SEGMENT11,CHARGE_ACCOUNT_SEGMENT12,CHARGE_ACCOUNT_SEGMENT13,CHARGE_ACCOUNT_SEGMENT14,CHARGE_ACCOUNT_SEGMENT15,CHARGE_ACCOUNT_SEGMENT16,CHARGE_ACCOUNT_SEGMENT17,CHARGE_ACCOUNT_SEGMENT18,CHARGE_ACCOUNT_SEGMENT19,CHARGE_ACCOUNT_SEGMENT20,CHARGE_ACCOUNT_SEGMENT21,CHARGE_ACCOUNT_SEGMENT22,CHARGE_ACCOUNT_SEGMENT23,CHARGE_ACCOUNT_SEGMENT24,CHARGE_ACCOUNT_SEGMENT25,CHARGE_ACCOUNT_SEGMENT26,CHARGE_ACCOUNT_SEGMENT27,CHARGE_ACCOUNT_SEGMENT28,CHARGE_ACCOUNT_SEGMENT29,CHARGE_ACCOUNT_SEGMENT30,DESTINATION_CONTEXT,PROJECT,TASK,PJC_EXPENDITURE_ITEM_DATE,EXPENDITURE,EXPENDITURE_ORGANIZATION,PJC_BILLABLE_FLAG,PJC_CAPITALIZABLE_FLAG,PJC_WORK_TYPE,PJC_RESERVED_ATTRIBUTE1,PJC_RESERVED_ATTRIBUTE2,PJC_RESERVED_ATTRIBUTE3,PJC_RESERVED_ATTRIBUTE4,PJC_RESERVED_ATTRIBUTE5,PJC_RESERVED_ATTRIBUTE6,PJC_RESERVED_ATTRIBUTE7,PJC_RESERVED_ATTRIBUTE8,PJC_RESERVED_ATTRIBUTE9,PJC_RESERVED_ATTRIBUTE10,PJC_USER_DEF_ATTRIBUTE1,PJC_USER_DEF_ATTRIBUTE2,PJC_USER_DEF_ATTRIBUTE3,PJC_USER_DEF_ATTRIBUTE4,PJC_USER_DEF_ATTRIBUTE5,PJC_USER_DEF_ATTRIBUTE6,PJC_USER_DEF_ATTRIBUTE7,PJC_USER_DEF_ATTRIBUTE8,PJC_USER_DEF_ATTRIBUTE9,PJC_USER_DEF_ATTRIBUTE10,RATE,RATE_DATE,ATTRIBUTE_CATEGORY,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,ATTRIBUTE11,ATTRIBUTE12,ATTRIBUTE13,ATTRIBUTE14,ATTRIBUTE15,ATTRIBUTE16,ATTRIBUTE17,ATTRIBUTE18,ATTRIBUTE19,ATTRIBUTE20,ATTRIBUTE_DATE1,ATTRIBUTE_DATE2,ATTRIBUTE_DATE3,ATTRIBUTE_DATE4,ATTRIBUTE_DATE5,ATTRIBUTE_DATE6,ATTRIBUTE_DATE7,ATTRIBUTE_DATE8,ATTRIBUTE_DATE9,ATTRIBUTE_DATE10,ATTRIBUTE_NUMBER1,ATTRIBUTE_NUMBER2,ATTRIBUTE_NUMBER3,ATTRIBUTE_NUMBER4,ATTRIBUTE_NUMBER5,ATTRIBUTE_NUMBER6,ATTRIBUTE_NUMBER7,ATTRIBUTE_NUMBER8,ATTRIBUTE_NUMBER9,ATTRIBUTE_NUMBER10,ATTRIBUTE_TIMESTAMP1,ATTRIBUTE_TIMESTAMP2,ATTRIBUTE_TIMESTAMP3,ATTRIBUTE_TIMESTAMP4,ATTRIBUTE_TIMESTAMP5,ATTRIBUTE_TIMESTAMP6,ATTRIBUTE_TIMESTAMP7,ATTRIBUTE_TIMESTAMP8,ATTRIBUTE_TIMESTAMP9,ATTRIBUTE_TIMESTAMP10,DELIVER_TO_PERSON_EMAIL_ADDR,BUDGET_DATE,PJC_CONTRACT_NUMBER,PJC_FUNDING_SOURCE".split(',')


def row(colnames, values):
    """Build a fully double-quoted CSV line for the given column order.
    values: dict col->str. Missing cols emit empty quoted field."""
    cells = []
    for c in colnames:
        v = values.get(c, '')
        cells.append('"' + str(v).replace('"', '""') + '"')
    return ','.join(cells)


# ---- record values ---------------------------------------------------------
# Natural keys carry ${PREFIX}. FK references carry discovered ${TOKEN}s.
NEED_BY = '2026/12/31'

def hdr(sfx, bad=False):
    v = {
        'INTERFACE_HEADER_KEY': '${PREFIX}RT-PO-' + sfx,
        'ACTION': 'ORIGINAL',
        # PO_HEADERS_INTERFACE.BATCH_ID is a NUMBER column -> must be numeric.
        # (The ParameterList arg9 batch label is separate free text.)
        'BATCH_ID': '${PREFIX}',
        'INTERFACE_SOURCE_CODE': 'RT${PREFIX}',
        'DOCUMENT_NUM': '${PREFIX}RT-PO-' + sfx,
        'DOCUMENT_TYPE_CODE': 'STANDARD',
        'STYLE_DISPLAY_NAME': 'Purchase Order',
        'PRC_BU_NAME': '${PRC_BU_NAME}',
        'SOLDTO_LE_NAME': '${SOLDTO_LE_NAME}',
        'BILLTO_BU_NAME': '${PRC_BU_NAME}',
        'AGENT_NAME': '${AGENT_NAME}',
        'CURRENCY_CODE': '${CURRENCY_CODE}',
        'VENDOR_NAME': '${VENDOR_NAME}',
        'VENDOR_NUM': '${VENDOR_NUM}',
        # BAD row: invalid supplier site -> Import Orders rejects it
        'VENDOR_SITE_CODE': ('ZZINVALIDSITE' if bad else '${VENDOR_SITE_CODE}'),
        'APPROVAL_ACTION': 'SUBMIT',
        'AGENT_EMAIL_ADDRESS': '${AGENT_EMAIL}',
    }
    return row(HEADERS, v)


def line(sfx):
    v = {
        'INTERFACE_LINE_KEY': '${PREFIX}RT-POL-' + sfx,
        'INTERFACE_HEADER_KEY': '${PREFIX}RT-PO-' + sfx,
        # PO_LINES_INTERFACE.ACTION left blank: a new-order line takes no action
        # code (header ACTION=ORIGINAL is what drives the create). A line ACTION
        # of 'ORIGINAL' is rejected as an invalid attribute value.
        'LINE_NUM': '1',
        'LINE_TYPE': '${LINE_TYPE}',
        'ITEM_DESCRIPTION': 'RT Gold PO line ' + sfx,
        'CATEGORY': '${CATEGORY_NAME}',
        'QUANTITY': '2',
        'UNIT_OF_MEASURE': 'Each',
        'UNIT_PRICE': '25',
    }
    return row(LINES, v)


def loc(sfx):
    v = {
        'INTERFACE_LINE_LOCATION_KEY': '${PREFIX}RT-POLL-' + sfx,
        'INTERFACE_LINE_KEY': '${PREFIX}RT-POL-' + sfx,
        'SHIPMENT_NUM': '1',
        'SHIP_TO_LOCATION': '${SHIP_TO_LOCATION}',
        'QUANTITY': '2',
        'NEED_BY_DATE': NEED_BY,
        'DESTINATION_TYPE_CODE': 'EXPENSE',
    }
    return row(LOCS, v)


def dist(sfx):
    v = {
        'INTERFACE_DISTRIBUTION_KEY': '${PREFIX}RT-POD-' + sfx,
        'INTERFACE_LINE_LOCATION_KEY': '${PREFIX}RT-POLL-' + sfx,
        'DISTRIBUTION_NUM': '1',
        'DELIVER_TO_LOCATION': '${DELIVER_TO_LOCATION}',
        'QUANTITY_ORDERED': '2',
        'CHARGE_ACCOUNT_SEGMENT1': '${CHG_S1}',
        'CHARGE_ACCOUNT_SEGMENT2': '${CHG_S2}',
        'CHARGE_ACCOUNT_SEGMENT3': '${CHG_S3}',
        'CHARGE_ACCOUNT_SEGMENT4': '${CHG_S4}',
        'CHARGE_ACCOUNT_SEGMENT5': '${CHG_S5}',
        'CHARGE_ACCOUNT_SEGMENT6': '${CHG_S6}',
    }
    return row(DISTS, v)


def write(name, lines):
    path = os.path.join(ART, name)
    # FBDI CSVs use CRLF line endings; keep newline='' so we control them.
    with open(path, 'w', newline='') as f:
        f.write('\r\n'.join(lines) + '\r\n')
    print('wrote', path, '(%d cols x %d rows)' % (
        lines[0].count(',') + 1, len(lines)))


SFX = ['G1', 'G2', 'BAD1']
write('PoHeadersInterfaceOrder.csv',
      [hdr('G1'), hdr('G2'), hdr('BAD1', bad=True)])
write('PoLinesInterfaceOrder.csv', [line(s) for s in SFX])
write('PoLineLocationsInterfaceOrder.csv', [loc(s) for s in SFX])
write('PoDistributionsInterfaceOrder.csv', [dist(s) for s in SFX])
print('done. header cols=%d line cols=%d loc cols=%d dist cols=%d'
      % (len(HEADERS), len(LINES), len(LOCS), len(DISTS)))
