-- DMT_RUN_METRICS_V
CREATE OR REPLACE EDITIONABLE VIEW "DMT_RUN_METRICS_V" ("RUN_DATE", "TOTAL_RUNS", "SUCCESSFUL_RUNS", "FAILED_RUNS", "RECORDS_PROCESSED", "RECORDS_LOADED", "RECORDS_FAILED", "AVG_RECORDS_PER_RUN", "AVG_SUCCESS_RATE_PCT")  AS 
  SELECT
    TRUNC(m.START_DATE) AS RUN_DATE,
    COUNT(*) AS TOTAL_RUNS,
    SUM(CASE WHEN m.STATUS = 'LOADED' THEN 1 ELSE 0 END) AS SUCCESSFUL_RUNS,
    SUM(CASE WHEN m.STATUS = 'FAILED' THEN 1 ELSE 0 END) AS FAILED_RUNS,
    SUM(m.TOTAL_RECORDS) AS RECORDS_PROCESSED,
    SUM(m.SUCCESSFUL_RECORDS) AS RECORDS_LOADED,
    SUM(m.ERRORED_RECORDS) AS RECORDS_FAILED,
    ROUND(AVG(m.TOTAL_RECORDS), 0) AS AVG_RECORDS_PER_RUN,
    ROUND(AVG(CASE
        WHEN m.TOTAL_RECORDS > 0
        THEN (m.SUCCESSFUL_RECORDS / m.TOTAL_RECORDS * 100)
    END), 2) AS AVG_SUCCESS_RATE_PCT
FROM
    DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
GROUP BY
    TRUNC(m.START_DATE)
ORDER BY
    TRUNC(m.START_DATE) DESC;
