-- DMT_V_TXN_CONTROLS_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_TXN_CONTROLS_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "PROJECT_NUMBER", "TXN_CTRL_REFERENCE", "PROJECT_NAME", "TASK_NUMBER", "TASK_NAME", "EXPENDITURE_CATEGORY_NAME", "EXPENDITURE_TYPE", "NON_LABOR_RESOURCE", "PERSON_NUMBER", "PERSON_NAME", "PERSON_EMAILID", "PERSON_TYPE", "JOB_NAME", "ORGANIZATION_NAME", "CHARGEABLE_FLAG", "BILLABLE_FLAG", "CAPITALIZABLE_FLAG", "START_DATE_ACTIVE", "END_DATE_ACTIVE", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.STATUS, stg.STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.PROJECT_NUMBER                                      AS PROJECT_NUMBER,
    stg.TXN_CTRL_REFERENCE,
    stg.PROJECT_NAME,
    stg.TASK_NUMBER,
    stg.TASK_NAME,
    stg.EXPENDITURE_CATEGORY_NAME,
    stg.EXPENDITURE_TYPE,
    stg.NON_LABOR_RESOURCE,
    stg.PERSON_NUMBER,
    stg.PERSON_NAME,
    stg.PERSON_EMAILID,
    stg.PERSON_TYPE,
    stg.JOB_NAME,
    stg.ORGANIZATION_NAME,
    stg.CHARGEABLE_FLAG,
    stg.BILLABLE_FLAG,
    stg.CAPITALIZABLE_FLAG,
    stg.START_DATE_ACTIVE,
    stg.END_DATE_ACTIVE,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    cm.PREFIX,
    CAST(NULL AS NUMBER)                                    AS SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_PJC_TXN_CONTROLS_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_PJC_TXN_CONTROLS_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
