-- DMT_OTC_RECEIPTS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_OTC_RECEIPTS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "RECEIPT_NUMBER", "RECEIPT_DATE", "SOURCE_DOCUMENT_CODE", "TRANSACTION_AMOUNT", "UNIT_OF_MEASURE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    r.STG_SEQUENCE_ID,
    rt.TFM_SEQUENCE_ID,
    r.SOURCE_ID,
    -- RECEIPT_NUMBER does not exist on RCV_TRANSACTIONS TFM; lives on RCV_HEADERS TFM as RECEIPT_NUM
    rt.DOCUMENT_NUM AS RECEIPT_NUMBER,
    rt.TRANSACTION_DATE AS RECEIPT_DATE,
    rt.SOURCE_DOCUMENT_CODE,
    rt.AMOUNT AS TRANSACTION_AMOUNT,
    rt.UNIT_OF_MEASURE,
    r.STATUS AS STG_STATUS,
    rt.STATUS AS TFM_STATUS,
    NVL(rt.STATUS, r.STATUS) AS OVERALL_STATUS,
    NVL(rt.STATUS, r.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(rt.ERROR_TEXT, r.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    r.STAGE_DATE,
    rt.RESULTS_UPDATED_DATE,
    NULL AS FUSION_LINK,
    r.SCENARIO_ID
FROM
    DMT_OWNER.DMT_RCV_TRANSACTIONS_STG_TBL r
    LEFT JOIN DMT_OWNER.DMT_RCV_TRANSACTIONS_TFM_TBL rt
        ON rt.STG_SEQUENCE_ID = r.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = rt.INTEGRATION_ID
ORDER BY
    r.STAGE_DATE DESC,
    r.STG_SEQUENCE_ID DESC;
