-- DMT_V_PROJECT_TEAM_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_PROJECT_TEAM_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "PROJECT_NAME", "TEAM_MEMBER_NUMBER", "TEAM_MEMBER_NAME", "TEAM_MEMBER_EMAIL", "PROJECT_ROLE_NAME", "START_DATE_ACTIVE", "END_DATE_ACTIVE", "TRACK_TIME_FLAG", "ALLOCATION", "EFFORT", "COST_RATE", "BILL_RATE", "ASSIGNMENT_TYPE", "BILLABLE_PERCENT", "BILLABLE_PERCENT_REASON_CODE", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.STATUS, stg.STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.PROJECT_NAME                                        AS PROJECT_NAME,
    stg.TEAM_MEMBER_NUMBER                                  AS TEAM_MEMBER_NUMBER,
    stg.TEAM_MEMBER_NAME,
    stg.TEAM_MEMBER_EMAIL,
    stg.PROJECT_ROLE_NAME,
    stg.START_DATE_ACTIVE,
    stg.END_DATE_ACTIVE,
    stg.TRACK_TIME_FLAG,
    stg.ALLOCATION,
    stg.EFFORT,
    stg.COST_RATE,
    stg.BILL_RATE,
    stg.ASSIGNMENT_TYPE,
    stg.BILLABLE_PERCENT,
    stg.BILLABLE_PERCENT_REASON_CODE,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    cm.PREFIX,
    CAST(NULL AS NUMBER)                                    AS SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_PJF_TEAM_MEMBERS_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_PJF_TEAM_MEMBERS_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
