-- DMT_CUST_IMP_RPT_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_CUST_IMP_RPT_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_STATUS", "START_DATE", "END_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "PARTY_ORIG_SYSTEM_REFERENCE", "PARTY_TYPE", "PARTY_NUMBER", "ORGANIZATION_NAME", "PERSON_FIRST_NAME", "PERSON_LAST_NAME", "STG_STATUS", "TFM_STATUS", "EFFECTIVE_STATUS", "RECONCILIATION_STATUS", "STG_ERRORS", "TFM_ERRORS", "ALL_ERRORS", "FUSION_PARTY_ID", "FUSION_PARTY_NUMBER", "RESULTS_UPDATED_DATE", "STAGE_DATE", "SOURCE_RECORD_ID", "LOCATION_COUNT", "PARTY_SITE_COUNT", "ACCOUNT_COUNT", "ACCOUNTS_LOADED", "ACCOUNTS_FAILED")  AS 
  SELECT
    t.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.STATUS                                        AS RUN_STATUS,
    m.START_DATE,
    m.END_DATE,
    m.PREFIX,
    -- Identification (from STG -- always present)
    s.STG_SEQUENCE_ID,
    t.TFM_SEQUENCE_ID,
    s.PARTY_ORIG_SYSTEM_REFERENCE,
    s.PARTY_TYPE,
    s.PARTY_NUMBER,
    s.ORGANIZATION_NAME,
    s.PERSON_FIRST_NAME,
    s.PERSON_LAST_NAME,
    -- Raw status from each layer
    s.STATUS                                        AS STG_STATUS,
    t.STATUS                                        AS TFM_STATUS,
    -- Effective status: worst wins
    CASE
        WHEN 'FAILED' IN (s.STATUS, NVL(t.STATUS, 'X'))  THEN 'FAILED'
        WHEN t.STATUS = 'GENERATED'                        THEN 'GENERATED'
        WHEN t.STATUS IS NOT NULL                          THEN t.STATUS
        ELSE s.STATUS
    END                                             AS EFFECTIVE_STATUS,
    -- Reconciliation status (badge color)
    CASE
        WHEN NVL(t.STATUS, s.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(t.STATUS, s.STATUS) = 'FAILED' AND COALESCE(t.ERROR_TEXT, s.ERROR_TEXT) IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(t.STATUS, s.STATUS) = 'FAILED' AND COALESCE(t.ERROR_TEXT, s.ERROR_TEXT) IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                             AS RECONCILIATION_STATUS,
    -- Error text from each layer
    DBMS_LOB.SUBSTR(s.ERROR_TEXT, 4000, 1)         AS STG_ERRORS,
    DBMS_LOB.SUBSTR(t.ERROR_TEXT, 4000, 1)         AS TFM_ERRORS,
    -- Combined errors
    CASE
        WHEN s.ERROR_TEXT IS NOT NULL AND t.ERROR_TEXT IS NOT NULL
        THEN DBMS_LOB.SUBSTR(s.ERROR_TEXT, 2000, 1) || ' | ' ||
             DBMS_LOB.SUBSTR(t.ERROR_TEXT, 2000, 1)
        ELSE DBMS_LOB.SUBSTR(COALESCE(s.ERROR_TEXT, t.ERROR_TEXT), 4000, 1)
    END                                             AS ALL_ERRORS,
    -- Fusion outcome (NULL until BIP reconciliation completes)
    t.FUSION_PARTY_ID,
    t.FUSION_PARTY_NUMBER,
    t.RESULTS_UPDATED_DATE,
    s.STAGE_DATE,
    s.SOURCE_ID                                     AS SOURCE_RECORD_ID,
    -- Rollup counts (NULL pre-pipeline)
    (SELECT COUNT(*)
     FROM   DMT_OWNER.DMT_HZ_LOCATIONS_TFM_TBL lt
     WHERE  lt.INTEGRATION_ID = t.INTEGRATION_ID)   AS LOCATION_COUNT,
    (SELECT COUNT(*)
     FROM   DMT_OWNER.DMT_HZ_PARTY_SITES_TFM_TBL pst
     WHERE  pst.INTEGRATION_ID = t.INTEGRATION_ID
     AND    pst.PARTY_ORIG_SYSTEM_REFERENCE = t.PARTY_ORIG_SYSTEM_REFERENCE) AS PARTY_SITE_COUNT,
    (SELECT COUNT(*)
     FROM   DMT_OWNER.DMT_HZ_ACCOUNTS_TFM_TBL at2
     WHERE  at2.INTEGRATION_ID = t.INTEGRATION_ID
     AND    at2.PARTY_ORIG_SYSTEM_REFERENCE = t.PARTY_ORIG_SYSTEM_REFERENCE) AS ACCOUNT_COUNT,
    (SELECT COUNT(*)
     FROM   DMT_OWNER.DMT_HZ_ACCOUNTS_TFM_TBL at3
     WHERE  at3.INTEGRATION_ID = t.INTEGRATION_ID
     AND    at3.PARTY_ORIG_SYSTEM_REFERENCE = t.PARTY_ORIG_SYSTEM_REFERENCE
     AND    at3.STATUS = 'LOADED')                   AS ACCOUNTS_LOADED,
    (SELECT COUNT(*)
     FROM   DMT_OWNER.DMT_HZ_ACCOUNTS_TFM_TBL at4
     WHERE  at4.INTEGRATION_ID = t.INTEGRATION_ID
     AND    at4.PARTY_ORIG_SYSTEM_REFERENCE = t.PARTY_ORIG_SYSTEM_REFERENCE
     AND    at4.STATUS = 'FAILED')                    AS ACCOUNTS_FAILED
FROM
    DMT_OWNER.DMT_HZ_PARTIES_STG_TBL            s
    LEFT JOIN DMT_OWNER.DMT_HZ_PARTIES_TFM_TBL  t
        ON  t.STG_SEQUENCE_ID  = s.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON  m.INTEGRATION_ID   = t.INTEGRATION_ID
ORDER BY
    t.INTEGRATION_ID DESC NULLS LAST,
    s.ORGANIZATION_NAME,
    s.PERSON_LAST_NAME;
