-- DMT_MST_ITEM_CATS_V
-- Repaired 2026-07-15 (Stage F / APEX port): master joined to TFM on RUN_ID
-- (was INTEGRATION_ID, renamed in the rebuild); FORCE dropped now that it compiles.
CREATE OR REPLACE EDITIONABLE VIEW "DMT_MST_ITEM_CATS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "ORGANIZATION_CODE", "ITEM_NUMBER", "CATEGORY_SET_NAME", "CATEGORY_CODE", "CATEGORY_NAME", "STAGE_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "ERROR_TEXT", "RESULTS_UPDATED_DATE", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    h.STG_SEQUENCE_ID,
    ht.TFM_SEQUENCE_ID,
    h.SOURCE_ID,
    NVL(ht.ORGANIZATION_CODE, h.ORGANIZATION_CODE) AS ORGANIZATION_CODE,
    NVL(ht.ITEM_NUMBER, h.ITEM_NUMBER) AS ITEM_NUMBER,
    NVL(ht.CATEGORY_SET_NAME, h.CATEGORY_SET_NAME) AS CATEGORY_SET_NAME,
    NVL(ht.CATEGORY_CODE, h.CATEGORY_CODE) AS CATEGORY_CODE,
    NVL(ht.CATEGORY_NAME, h.CATEGORY_NAME) AS CATEGORY_NAME,
    h.STAGE_DATE,
    h.STG_STATUS AS STG_STATUS,
    ht.TFM_STATUS,
    NVL(ht.TFM_STATUS, h.STG_STATUS) AS OVERALL_STATUS,
    DBMS_LOB.SUBSTR(NVL(ht.ERROR_TEXT, h.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ht.RESULTS_UPDATED_DATE,
    h.SCENARIO_ID
FROM
    DMT_OWNER.DMT_EGP_ITEM_CAT_STG_TBL h
    LEFT JOIN DMT_OWNER.DMT_EGP_ITEM_CAT_TFM_TBL ht
        ON ht.STG_SEQUENCE_ID = h.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ht.RUN_ID;
