-- DMT_CFG_LOOKUP_TYPES_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_CFG_LOOKUP_TYPES_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "LOOKUP_TYPE", "MEANING", "DESCRIPTION", "MODULE_TYPE", "MODULE_KEY", "STAGE_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "ERROR_TEXT", "RESULTS_UPDATED_DATE", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    h.STG_SEQUENCE_ID,
    ht.TFM_SEQUENCE_ID,
    h.SOURCE_ID,
    NVL(ht.LOOKUP_TYPE, h.LOOKUP_TYPE) AS LOOKUP_TYPE,
    NVL(ht.MEANING, h.MEANING) AS MEANING,
    NVL(ht.DESCRIPTION, h.DESCRIPTION) AS DESCRIPTION,
    NVL(ht.MODULE_TYPE, h.MODULE_TYPE) AS MODULE_TYPE,
    NVL(ht.MODULE_KEY, h.MODULE_KEY) AS MODULE_KEY,
    h.STAGE_DATE,
    h.STATUS AS STG_STATUS,
    ht.TFM_STATUS,
    NVL(ht.TFM_STATUS, h.STATUS) AS OVERALL_STATUS,
    DBMS_LOB.SUBSTR(NVL(ht.ERROR_TEXT, h.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ht.RESULTS_UPDATED_DATE,
    h.SCENARIO_ID
FROM
    DMT_OWNER.DMT_FND_LOOKUP_TYPE_STG_TBL h
    LEFT JOIN DMT_OWNER.DMT_FND_LOOKUP_TYPE_TFM_TBL ht
        ON ht.STG_SEQUENCE_ID = h.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ht.INTEGRATION_ID;
