-- DMT_CFG_PAY_TERM_LINES_V
-- Repaired 2026-07-15 (Stage F / APEX port): master joined to TFM on RUN_ID
-- (was INTEGRATION_ID, renamed in the rebuild); FORCE dropped now that it compiles.
CREATE OR REPLACE EDITIONABLE VIEW "DMT_CFG_PAY_TERM_LINES_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "SEQUENCE_NUM", "DUE_PERCENT", "DUE_DAYS", "DISCOUNT_PERCENT", "DISCOUNT_DAYS", "STAGE_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "ERROR_TEXT", "RESULTS_UPDATED_DATE", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    h.STG_SEQUENCE_ID,
    ht.TFM_SEQUENCE_ID,
    h.SOURCE_ID,
    NVL(ht.SEQUENCE_NUM, h.SEQUENCE_NUM) AS SEQUENCE_NUM,
    NVL(ht.DUE_PERCENT, h.DUE_PERCENT) AS DUE_PERCENT,
    NVL(ht.DUE_DAYS, h.DUE_DAYS) AS DUE_DAYS,
    NVL(ht.DISCOUNT_PERCENT, h.DISCOUNT_PERCENT) AS DISCOUNT_PERCENT,
    NVL(ht.DISCOUNT_DAYS, h.DISCOUNT_DAYS) AS DISCOUNT_DAYS,
    h.STAGE_DATE,
    h.STG_STATUS AS STG_STATUS,
    ht.TFM_STATUS,
    NVL(ht.TFM_STATUS, h.STG_STATUS) AS OVERALL_STATUS,
    DBMS_LOB.SUBSTR(NVL(ht.ERROR_TEXT, h.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ht.RESULTS_UPDATED_DATE,
    h.SCENARIO_ID
FROM
    DMT_OWNER.DMT_AP_PAY_TERM_LINE_STG_TBL h
    LEFT JOIN DMT_OWNER.DMT_AP_PAY_TERM_LINE_TFM_TBL ht
        ON ht.STG_SEQUENCE_ID = h.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ht.RUN_ID;
