-- DMT_CONFIG_ADMIN_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_CONFIG_ADMIN_V" ("CONFIG_KEY", "CONFIG_VALUE", "DESCRIPTION", "LAST_UPDATED_DATE", "LAST_UPDATED_BY")  AS 
  SELECT
    CONFIG_KEY,
    CONFIG_VALUE,
    -- CONFIG_CATEGORY does not exist on DMT_CONFIG_TBL
    DESCRIPTION,
    -- CREATED_DATE does not exist on DMT_CONFIG_TBL
    LAST_UPDATED_DATE,
    LAST_UPDATED_BY
FROM
    DMT_OWNER.DMT_CONFIG_TBL
ORDER BY
    CONFIG_KEY;
