-- DMT_CONVERSION_MASTER_TBL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_CONVERSION_MASTER_TBL" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "STATUS", "START_DATE", "END_DATE", "PREFIX", "SCENARIO_NAME", "TOTAL_RECORDS", "VALID_RECORDS", "INVALID_RECORDS", "SUCCESSFUL_RECORDS", "ERRORED_RECORDS", "ESS_JOB_ID", "FBDI_FILENAME", "INSTANCE_ID", "SOURCE_FILENAME", "FOLDER", "RESULT", "DEPENDENT_PREFIX", "SCENARIO_ID", "LAST_UPDATED_DATE")  AS 
  SELECT RUN_ID           AS INTEGRATION_ID,
       PIPELINE_CODES   AS ORCHESTRATION_CODE,
       RUN_STATUS       AS STATUS,
       SUBMITTED_DATE   AS START_DATE,
       COMPLETED_DATE   AS END_DATE,
       PREFIX,
       SCENARIO_NAME,
       0                AS TOTAL_RECORDS,
       0                AS VALID_RECORDS,
       0                AS INVALID_RECORDS,
       0                AS SUCCESSFUL_RECORDS,
       0                AS ERRORED_RECORDS,
       NULL             AS ESS_JOB_ID,
       NULL             AS FBDI_FILENAME,
       NULL             AS INSTANCE_ID,
       NULL             AS SOURCE_FILENAME,
       NULL             AS FOLDER,
       NULL             AS RESULT,
       NULL             AS DEPENDENT_PREFIX,
       RUN_ID           AS SCENARIO_ID,
       SUBMITTED_DATE   AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_PIPELINE_RUN_TBL;
