-- DMT_GRANTS_IMP_RPT_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_GRANTS_IMP_RPT_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_STATUS", "START_DATE", "END_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "AWARD_NAME", "AWARD_NUMBER", "BUSINESS_UNIT", "LEGAL_ENTITY", "CONTRACT_TYPE", "PRIMARY_SPONSOR", "AWARD_START_DATE", "AWARD_END_DATE", "CURRENCY_CODE", "STG_STATUS", "TFM_STATUS", "EFFECTIVE_STATUS", "RECONCILIATION_STATUS", "STG_ERRORS", "TFM_ERRORS", "ALL_ERRORS", "FUSION_AWARD_ID", "RESULTS_UPDATED_DATE", "STAGE_DATE", "SOURCE_RECORD_ID", "FUNDING_COUNT", "PROJECTS_COUNT", "PERSONNEL_COUNT", "FUND_SRC_COUNT", "PRJ_FUND_SRC_COUNT", "KEYWORDS_COUNT", "BUDGET_PERIODS_COUNT", "CERTS_COUNT", "CFDAS_COUNT", "FUND_ALLOC_COUNT", "ORG_CREDITS_COUNT", "PRJ_TASK_BURDEN_COUNT", "REFERENCES_COUNT", "TERMS_COUNT")  AS 
  SELECT
    t.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.STATUS                                        AS RUN_STATUS,
    m.START_DATE,
    m.END_DATE,
    m.PREFIX,
    -- Identification (from STG -- always present)
    s.STG_SEQUENCE_ID,
    t.TFM_SEQUENCE_ID,
    s.AWARD_NAME,
    s.AWARD_NUMBER,
    s.BUSINESS_UNIT,
    s.LEGAL_ENTITY,
    s.CONTRACT_TYPE,
    s.PRIMARY_SPONSOR,
    s.AWARD_START_DATE,
    s.AWARD_END_DATE,
    s.CURRENCY_CODE,
    -- Raw status from each layer
    s.STATUS                                        AS STG_STATUS,
    t.STATUS                                        AS TFM_STATUS,
    -- Effective status: worst wins
    CASE
        WHEN 'FAILED' IN (s.STATUS, NVL(t.STATUS, 'X'))  THEN 'FAILED'
        WHEN t.STATUS = 'GENERATED'                        THEN 'GENERATED'
        WHEN t.STATUS IS NOT NULL                          THEN t.STATUS
        ELSE s.STATUS
    END                                             AS EFFECTIVE_STATUS,
    -- Reconciliation status (badge color)
    CASE
        WHEN NVL(t.STATUS, s.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(t.STATUS, s.STATUS) = 'FAILED' AND COALESCE(t.ERROR_TEXT, s.ERROR_TEXT) IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(t.STATUS, s.STATUS) = 'FAILED' AND COALESCE(t.ERROR_TEXT, s.ERROR_TEXT) IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                             AS RECONCILIATION_STATUS,
    -- Error text from each layer
    DBMS_LOB.SUBSTR(s.ERROR_TEXT, 4000, 1)         AS STG_ERRORS,
    DBMS_LOB.SUBSTR(t.ERROR_TEXT, 4000, 1)         AS TFM_ERRORS,
    -- Combined errors
    CASE
        WHEN s.ERROR_TEXT IS NOT NULL AND t.ERROR_TEXT IS NOT NULL
        THEN DBMS_LOB.SUBSTR(s.ERROR_TEXT, 2000, 1) || ' | ' ||
             DBMS_LOB.SUBSTR(t.ERROR_TEXT, 2000, 1)
        ELSE DBMS_LOB.SUBSTR(COALESCE(s.ERROR_TEXT, t.ERROR_TEXT), 4000, 1)
    END                                             AS ALL_ERRORS,
    -- Fusion outcome (NULL until BIP reconciliation completes)
    t.FUSION_AWARD_ID,
    t.RESULTS_UPDATED_DATE,
    s.STAGE_DATE,
    s.SOURCE_ID                                     AS SOURCE_RECORD_ID,
    -- Child counts (all NULL pre-pipeline)
    (SELECT COUNT(*) FROM DMT_OWNER.DMT_GMS_AWD_FUNDING_TFM_TBL c
     WHERE c.INTEGRATION_ID = t.INTEGRATION_ID AND c.AWARD_NUMBER = t.AWARD_NUMBER)     AS FUNDING_COUNT,
    (SELECT COUNT(*) FROM DMT_OWNER.DMT_GMS_AWD_PROJECTS_TFM_TBL c
     WHERE c.INTEGRATION_ID = t.INTEGRATION_ID AND c.AWARD_NUMBER = t.AWARD_NUMBER)     AS PROJECTS_COUNT,
    (SELECT COUNT(*) FROM DMT_OWNER.DMT_GMS_AWD_PERSONNEL_TFM_TBL c
     WHERE c.INTEGRATION_ID = t.INTEGRATION_ID AND c.AWARD_NUMBER = t.AWARD_NUMBER)     AS PERSONNEL_COUNT,
    (SELECT COUNT(*) FROM DMT_OWNER.DMT_GMS_AWD_FUND_SRC_TFM_TBL c
     WHERE c.INTEGRATION_ID = t.INTEGRATION_ID AND c.AWARD_NUMBER = t.AWARD_NUMBER)     AS FUND_SRC_COUNT,
    (SELECT COUNT(*) FROM DMT_OWNER.DMT_GMS_AWD_PRJ_FUND_SRC_TFM_TBL c
     WHERE c.INTEGRATION_ID = t.INTEGRATION_ID AND c.AWARD_NUMBER = t.AWARD_NUMBER)     AS PRJ_FUND_SRC_COUNT,
    (SELECT COUNT(*) FROM DMT_OWNER.DMT_GMS_AWD_KEYWORDS_TFM_TBL c
     WHERE c.INTEGRATION_ID = t.INTEGRATION_ID AND c.AWARD_NUMBER = t.AWARD_NUMBER)     AS KEYWORDS_COUNT,
    (SELECT COUNT(*) FROM DMT_OWNER.DMT_GMS_AWD_BDGT_PRDS_TFM_TBL c
     WHERE c.INTEGRATION_ID = t.INTEGRATION_ID AND c.AWARD_NUMBER = t.AWARD_NUMBER)     AS BUDGET_PERIODS_COUNT,
    (SELECT COUNT(*) FROM DMT_OWNER.DMT_GMS_AWD_CERTS_TFM_TBL c
     WHERE c.INTEGRATION_ID = t.INTEGRATION_ID AND c.AWARD_NUMBER = t.AWARD_NUMBER)     AS CERTS_COUNT,
    (SELECT COUNT(*) FROM DMT_OWNER.DMT_GMS_AWD_CFDAS_TFM_TBL c
     WHERE c.INTEGRATION_ID = t.INTEGRATION_ID AND c.AWARD_NUMBER = t.AWARD_NUMBER)     AS CFDAS_COUNT,
    (SELECT COUNT(*) FROM DMT_OWNER.DMT_GMS_AWD_FUND_ALLOC_TFM_TBL c
     WHERE c.INTEGRATION_ID = t.INTEGRATION_ID AND c.AWARD_NUMBER = t.AWARD_NUMBER)     AS FUND_ALLOC_COUNT,
    (SELECT COUNT(*) FROM DMT_OWNER.DMT_GMS_AWD_ORG_CREDITS_TFM_TBL c
     WHERE c.INTEGRATION_ID = t.INTEGRATION_ID AND c.AWARD_NUMBER = t.AWARD_NUMBER)     AS ORG_CREDITS_COUNT,
    (SELECT COUNT(*) FROM DMT_OWNER.DMT_GMS_AWD_PRJ_TSK_BRD_TFM_TBL c
     WHERE c.INTEGRATION_ID = t.INTEGRATION_ID AND c.AWARD_NUMBER = t.AWARD_NUMBER)     AS PRJ_TASK_BURDEN_COUNT,
    (SELECT COUNT(*) FROM DMT_OWNER.DMT_GMS_AWD_REFERENCES_TFM_TBL c
     WHERE c.INTEGRATION_ID = t.INTEGRATION_ID AND c.AWARD_NUMBER = t.AWARD_NUMBER)     AS REFERENCES_COUNT,
    (SELECT COUNT(*) FROM DMT_OWNER.DMT_GMS_AWD_TERMS_TFM_TBL c
     WHERE c.INTEGRATION_ID = t.INTEGRATION_ID AND c.AWARD_NUMBER = t.AWARD_NUMBER)     AS TERMS_COUNT
FROM
    DMT_OWNER.DMT_GMS_AWD_HEADERS_STG_TBL       s
    LEFT JOIN DMT_OWNER.DMT_GMS_AWD_HEADERS_TFM_TBL t
        ON  t.STG_SEQUENCE_ID  = s.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON  m.INTEGRATION_ID   = t.INTEGRATION_ID
ORDER BY
    t.INTEGRATION_ID DESC NULLS LAST,
    s.AWARD_NUMBER;
