-- DMT_V_CEMLI_STATUS
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_CEMLI_STATUS" ("PIPELINE", "CEMLI_CODE", "SORT_ORDER", "RUN_ID", "INTEGRATION_ID", "STATUS", "ROW_COUNT", "UNRECONCILED_COUNT")  AS 
  SELECT q.PIPELINE, q.CEMLI_CODE, q.SORT_ORDER,
       q.RUN_ID, q.RUN_ID AS INTEGRATION_ID,
       q.STATUS, q.ROW_COUNT, q.UNRECONCILED_COUNT
FROM (
-- P2P Pipeline
SELECT 'P2P' AS PIPELINE, 'Suppliers' AS CEMLI_CODE, 1 AS SORT_ORDER,
       RUN_ID, STATUS, COUNT(*) AS ROW_COUNT,
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END) AS UNRECONCILED_COUNT
FROM DMT_OWNER.DMT_POZ_SUPPLIERS_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'P2P', 'SupplierAddresses', 2, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_POZ_SUP_ADDR_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'P2P', 'SupplierSites', 3, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_POZ_SUP_SITE_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'P2P', 'SupplierSiteAssignments', 4, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_POZ_SUP_SITE_ASSN_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'P2P', 'SupplierContacts', 5, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_POZ_SUP_CONTACTS_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'P2P', 'PurchaseOrders', 6, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL
WHERE STYLE_DISPLAY_NAME = 'Purchase Order' OR STYLE_DISPLAY_NAME IS NULL
GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'P2P', 'BlanketPOs', 7, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL
WHERE STYLE_DISPLAY_NAME = 'Blanket Purchase Agreement'
GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'P2P', 'Contracts', 8, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL
WHERE STYLE_DISPLAY_NAME = 'Contract Purchase Agreement'
GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'P2P', 'APInvoices', 9, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_AP_INVOICES_INT_TFM_TBL
WHERE INVOICE_TYPE_LOOKUP_CODE NOT LIKE '%1099%' OR INVOICE_TYPE_LOOKUP_CODE IS NULL
GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'P2P', '1099Invoices', 10, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_AP_INVOICES_INT_TFM_TBL
WHERE INVOICE_TYPE_LOOKUP_CODE LIKE '%1099%'
GROUP BY RUN_ID, STATUS
-- O2C Pipeline
UNION ALL
SELECT 'O2C', 'Customers', 1, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_HZ_PARTIES_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'O2C', 'ARInvoices', 2, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_RA_LINES_TFM_TBL GROUP BY RUN_ID, STATUS
-- Projects Pipeline
UNION ALL
SELECT 'Projects', 'Projects', 1, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_PJF_PROJECTS_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'Projects', 'BillingEvents', 2, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_PJB_BILL_EVENTS_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'Projects', 'Expenditures', 3, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_PJC_EXPENDITURES_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'Projects', 'Grants', 4, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_GMS_AWD_HEADERS_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'Projects', 'ProjectBudgets', 5, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_PRJ_BUDGET_TFM_TBL GROUP BY RUN_ID, STATUS
-- Financials Pipeline
UNION ALL
SELECT 'Financials', 'GLBalances', 1, RUN_ID, TFM_STATUS AS STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_GL_INTERFACE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
SELECT 'Financials', 'GLBudgetBalances', 2, RUN_ID, TFM_STATUS AS STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_GL_BUDGET_INT_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
SELECT 'Financials', 'PlanningBudgets', 3, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_PLAN_BUDGET_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'Financials', 'Assets', 4, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_FA_ASSET_HDR_TFM_TBL GROUP BY RUN_ID, STATUS
-- Standalone
UNION ALL
SELECT 'Standalone', 'Requisitions', 1, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_POR_REQ_HEADERS_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'Standalone', 'MiscReceipts', 2, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_RCV_HEADERS_TFM_TBL GROUP BY RUN_ID, STATUS
-- HCM Pipeline
UNION ALL
SELECT 'HCM', 'Workers', 1, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_WORKER_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'HCM', 'Assignments', 2, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_ASSIGNMENT_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'HCM', 'Salaries', 3, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_SALARY_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'HCM', 'SalaryBases', 4, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_SAL_BASIS_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'HCM', 'PayrollRelationships', 5, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_PAY_REL_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'HCM', 'TaxCards', 6, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_TAX_CARD_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'HCM', 'W2Balances', 7, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_W2_BAL_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'HCM', 'BenParticipant', 8, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_BEN_PARTIC_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'HCM', 'BenDependent', 9, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_BEN_DEPEND_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'HCM', 'BenBeneficiary', 10, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_BEN_BENFY_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'HCM', 'Absences', 11, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_ABSENCE_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'HCM', 'TalentProfiles', 12, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_TALENT_PROF_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'HCM', 'PerfEvaluations', 13, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_PERF_EVAL_TFM_TBL GROUP BY RUN_ID, STATUS
UNION ALL
SELECT 'HCM', 'WorkSchedules', 14, RUN_ID, STATUS, COUNT(*),
       SUM(CASE WHEN STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_WORK_SCHED_TFM_TBL GROUP BY RUN_ID, STATUS
-- Configuration Pipeline
UNION ALL
SELECT 'Configuration', 'GLCalendar', 1, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_GL_CALENDAR_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
SELECT 'Configuration', 'ValueSets', 2, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_FND_VS_SET_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
SELECT 'Configuration', 'ValueSetValues', 3, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_FND_VS_VALUE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
SELECT 'Configuration', 'LookupTypes', 4, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_FND_LOOKUP_TYPE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
SELECT 'Configuration', 'LookupValues', 5, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_FND_LOOKUP_VALUE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
SELECT 'Configuration', 'UOM', 6, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_INV_UOM_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
SELECT 'Configuration', 'PaymentTerms', 7, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_AP_PAY_TERM_HDR_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
SELECT 'Configuration', 'PaymentTermLines', 8, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_AP_PAY_TERM_LINE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
SELECT 'Configuration', 'TaxRegimes', 9, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_ZX_REGIME_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
SELECT 'Configuration', 'TaxRates', 10, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_ZX_RATE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
-- Master Data Pipeline
UNION ALL
SELECT 'MasterData', 'Items', 1, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_EGP_ITEM_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
-- Item categories are bundled into the Items FBDI ZIP, so their row counts roll up into
-- the 'Items' card (CEMLI_CODE='Items', same SORT_ORDER) rather than a separate card.
SELECT 'MasterData', 'Items', 1, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_EGP_ITEM_CAT_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
SELECT 'MasterData', 'Banks', 3, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_CE_BANK_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
SELECT 'MasterData', 'BankBranches', 4, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_CE_BRANCH_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
UNION ALL
SELECT 'MasterData', 'BankAccounts', 5, RUN_ID, TFM_STATUS, COUNT(*),
       SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
FROM DMT_OWNER.DMT_CE_BANK_ACCT_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
-- Async pipeline runs (overview card, not per-object)
UNION ALL
SELECT CASE r.PIPELINE_CODES
           WHEN 'P2P'        THEN 'P2P'
           WHEN 'O2C'        THEN 'O2C'
           WHEN 'OTC'        THEN 'O2C'
           WHEN 'HCM'        THEN 'HCM'
           WHEN 'FINANCIALS' THEN 'Financials'
           WHEN 'PROJECTS'   THEN 'Projects'
           WHEN 'STANDALONE' THEN 'Standalone'
           ELSE INITCAP(r.PIPELINE_CODES)
       END AS PIPELINE,
       '__PIPELINE__' AS CEMLI_CODE,
       -1 AS SORT_ORDER,
       r.RUN_ID,
       r.RUN_STATUS AS STATUS,
       0 AS ROW_COUNT,
       0 AS UNRECONCILED_COUNT
FROM DMT_OWNER.DMT_PIPELINE_RUN_TBL r
WHERE r.RUN_STATUS IN ('QUEUED', 'IN_PROGRESS', 'FAILED', 'COMPLETED')
) q;
