-- DMT_BIP_REPORTS_ADMIN_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_BIP_REPORTS_ADMIN_V" ("BIP_REPORT_ID", "CEMLI_CODE", "OBJECT_TYPE", "DM_CATALOG_PATH", "REPORT_CATALOG_PATH", "INTERFACE_TABLE", "NOTES", "CREATED_DATE", "RUNS_EXECUTED")  AS 
  SELECT
    br.BIP_REPORT_ID,
    br.CEMLI_CODE,
    br.OBJECT_TYPE,
    br.DM_CATALOG_PATH,
    br.REPORT_CATALOG_PATH,
    br.INTERFACE_TABLE,
    br.NOTES,
    br.CREATED_DATE,
    COUNT(m.INTEGRATION_ID) AS RUNS_EXECUTED
FROM
    DMT_OWNER.DMT_BIP_REPORT_TBL br
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.ORCHESTRATION_CODE = br.CEMLI_CODE
GROUP BY
    br.BIP_REPORT_ID,
    br.CEMLI_CODE,
    br.OBJECT_TYPE,
    br.DM_CATALOG_PATH,
    br.REPORT_CATALOG_PATH,
    br.INTERFACE_TABLE,
    br.NOTES,
    br.CREATED_DATE
ORDER BY
    br.CEMLI_CODE;
