-- DMT_AR_IMP_RPT_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_AR_IMP_RPT_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_STATUS", "START_DATE", "END_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "TRX_NUMBER", "BATCH_SOURCE_NAME", "CUST_TRX_TYPE_NAME", "LINE_TYPE", "DESCRIPTION", "CURRENCY_CODE", "AMOUNT", "BILL_CUSTOMER_ACCOUNT_NUMBER", "BU_NAME", "INTERFACE_LINE_CONTEXT", "INTERFACE_LINE_ATTRIBUTE1", "STG_STATUS", "TFM_STATUS", "EFFECTIVE_STATUS", "RECONCILIATION_STATUS", "STG_ERRORS", "TFM_ERRORS", "ALL_ERRORS", "FUSION_CUSTOMER_TRX_ID", "FUSION_TRX_NUMBER", "RESULTS_UPDATED_DATE", "STAGE_DATE", "SOURCE_RECORD_ID", "DIST_COUNT", "DISTS_LOADED", "DISTS_FAILED")  AS 
  SELECT
    t.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.STATUS                                        AS RUN_STATUS,
    m.START_DATE,
    m.END_DATE,
    m.PREFIX,
    -- Identification (from STG -- always present)
    s.STG_SEQUENCE_ID,
    t.TFM_SEQUENCE_ID,
    s.TRX_NUMBER,
    s.BATCH_SOURCE_NAME,
    s.CUST_TRX_TYPE_NAME,
    s.LINE_TYPE,
    s.DESCRIPTION,
    s.CURRENCY_CODE,
    s.AMOUNT,
    s.BILL_CUSTOMER_ACCOUNT_NUMBER,
    s.BU_NAME,
    s.INTERFACE_LINE_CONTEXT,
    s.INTERFACE_LINE_ATTRIBUTE1,
    -- Raw status from each layer
    s.STATUS                                        AS STG_STATUS,
    t.STATUS                                        AS TFM_STATUS,
    -- Effective status: worst wins
    CASE
        WHEN 'FAILED' IN (s.STATUS, NVL(t.STATUS, 'X'))  THEN 'FAILED'
        WHEN t.STATUS = 'GENERATED'                        THEN 'GENERATED'
        WHEN t.STATUS IS NOT NULL                          THEN t.STATUS
        ELSE s.STATUS
    END                                             AS EFFECTIVE_STATUS,
    -- Reconciliation status (badge color)
    CASE
        WHEN NVL(t.STATUS, s.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(t.STATUS, s.STATUS) = 'FAILED' AND COALESCE(t.ERROR_TEXT, s.ERROR_TEXT) IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(t.STATUS, s.STATUS) = 'FAILED' AND COALESCE(t.ERROR_TEXT, s.ERROR_TEXT) IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                             AS RECONCILIATION_STATUS,
    -- Error text from each layer
    DBMS_LOB.SUBSTR(s.ERROR_TEXT, 4000, 1)         AS STG_ERRORS,
    DBMS_LOB.SUBSTR(t.ERROR_TEXT, 4000, 1)         AS TFM_ERRORS,
    -- Combined errors
    CASE
        WHEN s.ERROR_TEXT IS NOT NULL AND t.ERROR_TEXT IS NOT NULL
        THEN DBMS_LOB.SUBSTR(s.ERROR_TEXT, 2000, 1) || ' | ' ||
             DBMS_LOB.SUBSTR(t.ERROR_TEXT, 2000, 1)
        ELSE DBMS_LOB.SUBSTR(COALESCE(s.ERROR_TEXT, t.ERROR_TEXT), 4000, 1)
    END                                             AS ALL_ERRORS,
    -- Fusion outcome (NULL until BIP reconciliation completes)
    t.FUSION_CUSTOMER_TRX_ID,
    t.FUSION_TRX_NUMBER,
    t.RESULTS_UPDATED_DATE,
    s.STAGE_DATE,
    s.SOURCE_ID                                     AS SOURCE_RECORD_ID,
    -- Distribution rollup counts (NULL pre-pipeline)
    (SELECT COUNT(*)
     FROM   DMT_OWNER.DMT_RA_DISTS_TFM_TBL dt
     WHERE  dt.INTEGRATION_ID          = t.INTEGRATION_ID
     AND    dt.INTERFACE_LINE_CONTEXT   = t.INTERFACE_LINE_CONTEXT
     AND    dt.INTERFACE_LINE_ATTRIBUTE1 = t.INTERFACE_LINE_ATTRIBUTE1) AS DIST_COUNT,
    (SELECT COUNT(*)
     FROM   DMT_OWNER.DMT_RA_DISTS_TFM_TBL dt
     WHERE  dt.INTEGRATION_ID          = t.INTEGRATION_ID
     AND    dt.INTERFACE_LINE_CONTEXT   = t.INTERFACE_LINE_CONTEXT
     AND    dt.INTERFACE_LINE_ATTRIBUTE1 = t.INTERFACE_LINE_ATTRIBUTE1
     AND    dt.STATUS                   = 'LOADED')             AS DISTS_LOADED,
    (SELECT COUNT(*)
     FROM   DMT_OWNER.DMT_RA_DISTS_TFM_TBL dt
     WHERE  dt.INTEGRATION_ID          = t.INTEGRATION_ID
     AND    dt.INTERFACE_LINE_CONTEXT   = t.INTERFACE_LINE_CONTEXT
     AND    dt.INTERFACE_LINE_ATTRIBUTE1 = t.INTERFACE_LINE_ATTRIBUTE1
     AND    dt.STATUS                   = 'FAILED')             AS DISTS_FAILED
FROM
    DMT_OWNER.DMT_RA_LINES_STG_TBL              s
    LEFT JOIN DMT_OWNER.DMT_RA_LINES_TFM_TBL    t
        ON  t.STG_SEQUENCE_ID  = s.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON  m.INTEGRATION_ID   = t.INTEGRATION_ID
ORDER BY
    t.INTEGRATION_ID DESC NULLS LAST,
    s.TRX_NUMBER,
    s.INTERFACE_LINE_ATTRIBUTE1;
