-- DMT_V_PERSON_ADDR_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_PERSON_ADDR_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "PERSON_NUMBER", "ADDRESS_TYPE", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "ADDRESS_LINE_1", "ADDRESS_LINE_2", "ADDRESS_LINE_3", "ADDRESS_LINE_4", "TOWN_OR_CITY", "REGION_1", "REGION_2", "REGION_3", "POSTAL_CODE", "COUNTRY", "PRIMARY_FLAG", "FROM_DATE", "TO_DATE", "ADD_INFORMATION13", "ADD_INFORMATION14", "ADD_INFORMATION15", "ADD_INFORMATION16", "ADD_INFORMATION17", "ADD_INFORMATION18", "ADD_INFORMATION19", "ADD_INFORMATION20", "ADD_INFORMATION21", "ADD_INFORMATION22", "ADD_INFORMATION23", "ADD_INFORMATION24", "ADD_INFORMATION25", "ADD_INFORMATION26", "ADD_INFORMATION27", "ADD_INFORMATION28", "ADD_INFORMATION29", "ADD_INFORMATION30", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.STATUS, stg.STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.PERSON_NUMBER                                       AS PERSON_NUMBER,
    stg.ADDRESS_TYPE                                        AS ADDRESS_TYPE,
    stg.EFFECTIVE_START_DATE,
    stg.EFFECTIVE_END_DATE,
    stg.ADDRESS_LINE_1,
    stg.ADDRESS_LINE_2,
    stg.ADDRESS_LINE_3,
    stg.ADDRESS_LINE_4,
    stg.TOWN_OR_CITY,
    stg.REGION_1,
    stg.REGION_2,
    stg.REGION_3,
    stg.POSTAL_CODE,
    stg.COUNTRY,
    stg.PRIMARY_FLAG,
    stg.FROM_DATE,
    stg.TO_DATE,
    stg.ADD_INFORMATION13,
    stg.ADD_INFORMATION14,
    stg.ADD_INFORMATION15,
    stg.ADD_INFORMATION16,
    stg.ADD_INFORMATION17,
    stg.ADD_INFORMATION18,
    stg.ADD_INFORMATION19,
    stg.ADD_INFORMATION20,
    stg.ADD_INFORMATION21,
    stg.ADD_INFORMATION22,
    stg.ADD_INFORMATION23,
    stg.ADD_INFORMATION24,
    stg.ADD_INFORMATION25,
    stg.ADD_INFORMATION26,
    stg.ADD_INFORMATION27,
    stg.ADD_INFORMATION28,
    stg.ADD_INFORMATION29,
    stg.ADD_INFORMATION30,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    cm.PREFIX,
    stg.SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_PERSON_ADDR_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_PERSON_ADDR_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
