-- DMT_MST_ITEMS_V
-- FORCE retained deliberately: this view is one of the tracked-broken
-- INTEGRATION_ID-drifted summary views (docs/tranche-reviews/2026-07-07-views.md
-- finding F1(rest): DEFER pending Stage F usage check against the f155 APEX
-- export - delete or repair then). It cannot compile until that repair, so
-- without FORCE the install would abort; every other view file has no FORCE
-- per the accepted no-FORCE rule (design section 7, accepted 2026-07-08).
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_MST_ITEMS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "ITEM_NUMBER", "DESCRIPTION", "ORGANIZATION_CODE", "PRIMARY_UOM_CODE", "ITEM_CLASS_NAME", "ITEM_STATUS", "STAGE_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "ERROR_TEXT", "RESULTS_UPDATED_DATE", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    h.STG_SEQUENCE_ID,
    ht.TFM_SEQUENCE_ID,
    h.SOURCE_ID,
    NVL(ht.ITEM_NUMBER, h.ITEM_NUMBER) AS ITEM_NUMBER,
    NVL(ht.DESCRIPTION, h.DESCRIPTION) AS DESCRIPTION,
    NVL(ht.ORGANIZATION_CODE, h.ORGANIZATION_CODE) AS ORGANIZATION_CODE,
    NVL(ht.PRIMARY_UOM_CODE, h.PRIMARY_UOM_CODE) AS PRIMARY_UOM_CODE,
    NVL(ht.ITEM_CLASS_NAME, h.ITEM_CLASS_NAME) AS ITEM_CLASS_NAME,
    NVL(ht.INVENTORY_ITEM_STATUS_CODE, h.INVENTORY_ITEM_STATUS_CODE) AS ITEM_STATUS,
    h.STAGE_DATE,
    h.STG_STATUS AS STG_STATUS,
    ht.TFM_STATUS,
    NVL(ht.TFM_STATUS, h.STG_STATUS) AS OVERALL_STATUS,
    DBMS_LOB.SUBSTR(NVL(ht.ERROR_TEXT, h.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ht.RESULTS_UPDATED_DATE,
    h.SCENARIO_ID
FROM
    DMT_OWNER.DMT_EGP_ITEM_STG_TBL h
    LEFT JOIN DMT_OWNER.DMT_EGP_ITEM_TFM_TBL ht
        ON ht.STG_SEQUENCE_ID = h.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ht.INTEGRATION_ID;
