-- DMT_V_PO_LINE_LOCS_DETAIL
CREATE OR REPLACE EDITIONABLE VIEW "DMT_V_PO_LINE_LOCS_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "INTERFACE_LINE_LOCATION_KEY", "SHIPMENT_NUM", "INTERFACE_LINE_KEY", "SHIP_TO_LOCATION", "SHIP_TO_ORGANIZATION_CODE", "AMOUNT", "QUANTITY", "NEED_BY_DATE", "PROMISED_DATE", "SECONDARY_QUANTITY", "SECONDARY_UNIT_OF_MEASURE", "DESTINATION_TYPE_CODE", "ACCRUE_ON_RECEIPT_FLAG", "ALLOW_SUBSTITUTE_RECEIPTS_FLAG", "ASSESSABLE_VALUE", "DAYS_EARLY_RECEIPT_ALLOWED", "DAYS_LATE_RECEIPT_ALLOWED", "ENFORCE_SHIP_TO_LOCATION_CODE", "INSPECTION_REQUIRED_FLAG", "RECEIPT_REQUIRED_FLAG", "INVOICE_CLOSE_TOLERANCE", "RECEIVE_CLOSE_TOLERANCE", "QTY_RCV_TOLERANCE", "QTY_RCV_EXCEPTION_CODE", "RECEIPT_DAYS_EXCEPTION_CODE", "RECEIVING_ROUTING", "NOTE_TO_RECEIVER", "INPUT_TAX_CLASSIFICATION_CODE", "LINE_INTENDED_USE", "PRODUCT_CATEGORY", "PRODUCT_FISC_CLASSIFICATION", "PRODUCT_TYPE", "TRX_BUSINESS_CATEGORY", "USER_DEFINED_FISC_CLASS", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "ATTRIBUTE16", "ATTRIBUTE17", "ATTRIBUTE18", "ATTRIBUTE19", "ATTRIBUTE20", "ATTRIBUTE_DATE1", "ATTRIBUTE_DATE2", "ATTRIBUTE_DATE3", "ATTRIBUTE_DATE4", "ATTRIBUTE_DATE5", "ATTRIBUTE_DATE6", "ATTRIBUTE_DATE7", "ATTRIBUTE_DATE8", "ATTRIBUTE_DATE9", "ATTRIBUTE_DATE10", "ATTRIBUTE_NUMBER1", "ATTRIBUTE_NUMBER2", "ATTRIBUTE_NUMBER3", "ATTRIBUTE_NUMBER4", "ATTRIBUTE_NUMBER5", "ATTRIBUTE_NUMBER6", "ATTRIBUTE_NUMBER7", "ATTRIBUTE_NUMBER8", "ATTRIBUTE_NUMBER9", "ATTRIBUTE_NUMBER10", "ATTRIBUTE_TIMESTAMP1", "ATTRIBUTE_TIMESTAMP2", "ATTRIBUTE_TIMESTAMP3", "ATTRIBUTE_TIMESTAMP4", "ATTRIBUTE_TIMESTAMP5", "ATTRIBUTE_TIMESTAMP6", "ATTRIBUTE_TIMESTAMP7", "ATTRIBUTE_TIMESTAMP8", "ATTRIBUTE_TIMESTAMP9", "ATTRIBUTE_TIMESTAMP10", "FREIGHT_CARRIER", "MODE_OF_TRANSPORT", "SERVICE_LEVEL", "FINAL_DISCHARGE_LOCATION_CODE", "REQUESTED_SHIP_DATE", "PROMISED_SHIP_DATE", "REQUESTED_DELIVERY_DATE", "PROMISED_DELIVERY_DATE", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    -- 1. Run status
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    -- 2. Error text
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    -- 3. Human identifiers
    stg.INTERFACE_LINE_LOCATION_KEY                         AS INTERFACE_LINE_LOCATION_KEY,
    stg.SHIPMENT_NUM                                        AS SHIPMENT_NUM,
    -- 4. All remaining STG business columns
    stg.INTERFACE_LINE_KEY,
    stg.SHIP_TO_LOCATION,
    stg.SHIP_TO_ORGANIZATION_CODE,
    stg.AMOUNT,
    stg.QUANTITY,
    stg.NEED_BY_DATE,
    stg.PROMISED_DATE,
    stg.SECONDARY_QUANTITY,
    stg.SECONDARY_UNIT_OF_MEASURE,
    stg.DESTINATION_TYPE_CODE,
    stg.ACCRUE_ON_RECEIPT_FLAG,
    stg.ALLOW_SUBSTITUTE_RECEIPTS_FLAG,
    stg.ASSESSABLE_VALUE,
    stg.DAYS_EARLY_RECEIPT_ALLOWED,
    stg.DAYS_LATE_RECEIPT_ALLOWED,
    stg.ENFORCE_SHIP_TO_LOCATION_CODE,
    stg.INSPECTION_REQUIRED_FLAG,
    stg.RECEIPT_REQUIRED_FLAG,
    stg.INVOICE_CLOSE_TOLERANCE,
    stg.RECEIVE_CLOSE_TOLERANCE,
    stg.QTY_RCV_TOLERANCE,
    stg.QTY_RCV_EXCEPTION_CODE,
    stg.RECEIPT_DAYS_EXCEPTION_CODE,
    stg.RECEIVING_ROUTING,
    stg.NOTE_TO_RECEIVER,
    stg.INPUT_TAX_CLASSIFICATION_CODE,
    stg.LINE_INTENDED_USE,
    stg.PRODUCT_CATEGORY,
    stg.PRODUCT_FISC_CLASSIFICATION,
    stg.PRODUCT_TYPE,
    stg.TRX_BUSINESS_CATEGORY,
    stg.USER_DEFINED_FISC_CLASS,
    stg.ATTRIBUTE_CATEGORY,
    stg.ATTRIBUTE1,
    stg.ATTRIBUTE2,
    stg.ATTRIBUTE3,
    stg.ATTRIBUTE4,
    stg.ATTRIBUTE5,
    stg.ATTRIBUTE6,
    stg.ATTRIBUTE7,
    stg.ATTRIBUTE8,
    stg.ATTRIBUTE9,
    stg.ATTRIBUTE10,
    stg.ATTRIBUTE11,
    stg.ATTRIBUTE12,
    stg.ATTRIBUTE13,
    stg.ATTRIBUTE14,
    stg.ATTRIBUTE15,
    stg.ATTRIBUTE16,
    stg.ATTRIBUTE17,
    stg.ATTRIBUTE18,
    stg.ATTRIBUTE19,
    stg.ATTRIBUTE20,
    stg.ATTRIBUTE_DATE1,
    stg.ATTRIBUTE_DATE2,
    stg.ATTRIBUTE_DATE3,
    stg.ATTRIBUTE_DATE4,
    stg.ATTRIBUTE_DATE5,
    stg.ATTRIBUTE_DATE6,
    stg.ATTRIBUTE_DATE7,
    stg.ATTRIBUTE_DATE8,
    stg.ATTRIBUTE_DATE9,
    stg.ATTRIBUTE_DATE10,
    stg.ATTRIBUTE_NUMBER1,
    stg.ATTRIBUTE_NUMBER2,
    stg.ATTRIBUTE_NUMBER3,
    stg.ATTRIBUTE_NUMBER4,
    stg.ATTRIBUTE_NUMBER5,
    stg.ATTRIBUTE_NUMBER6,
    stg.ATTRIBUTE_NUMBER7,
    stg.ATTRIBUTE_NUMBER8,
    stg.ATTRIBUTE_NUMBER9,
    stg.ATTRIBUTE_NUMBER10,
    stg.ATTRIBUTE_TIMESTAMP1,
    stg.ATTRIBUTE_TIMESTAMP2,
    stg.ATTRIBUTE_TIMESTAMP3,
    stg.ATTRIBUTE_TIMESTAMP4,
    stg.ATTRIBUTE_TIMESTAMP5,
    stg.ATTRIBUTE_TIMESTAMP6,
    stg.ATTRIBUTE_TIMESTAMP7,
    stg.ATTRIBUTE_TIMESTAMP8,
    stg.ATTRIBUTE_TIMESTAMP9,
    stg.ATTRIBUTE_TIMESTAMP10,
    stg.FREIGHT_CARRIER,
    stg.MODE_OF_TRANSPORT,
    stg.SERVICE_LEVEL,
    stg.FINAL_DISCHARGE_LOCATION_CODE,
    stg.REQUESTED_SHIP_DATE,
    stg.PROMISED_SHIP_DATE,
    stg.REQUESTED_DELIVERY_DATE,
    stg.PROMISED_DELIVERY_DATE,
    stg.SOURCE_ID,
    -- 5. STG_SEQUENCE_ID
    stg.STG_SEQUENCE_ID,
    -- 6. RUN_ID
    tfm.RUN_ID,
    -- 7. PREFIX (from PIPELINE_RUN)
    cm.PREFIX,
    -- 8. SCENARIO_ID
    stg.SCENARIO_ID,
    -- 9. STAGE_DATE
    stg.STAGE_DATE,
    -- 10. LAST_UPDATED_DATE
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_PO_LINE_LOCS_INT_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_PO_LINE_LOCS_INT_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
