-- DMT_PROJECT_EXPENDITURES_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_PROJECT_EXPENDITURES_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "EXPENDITURE_REF", "EXPENDITURE_TYPE", "TRANSACTION_DATE", "AMOUNT", "CURRENCY_CODE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    e.STG_SEQUENCE_ID,
    et.TFM_SEQUENCE_ID,
    e.SOURCE_ID,
    -- EXPENDITURE_ID does not exist on PJC_EXPENDITURES TFM
    et.ORIG_TRANSACTION_REFERENCE AS EXPENDITURE_REF,
    NVL(et.EXPENDITURE_TYPE, e.EXPENDITURE_TYPE) AS EXPENDITURE_TYPE,
    et.EXPENDITURE_ITEM_DATE AS TRANSACTION_DATE,
    NVL(et.DENOM_RAW_COST, e.DENOM_RAW_COST) AS AMOUNT,
    NVL(et.DENOM_CURRENCY_CODE, e.DENOM_CURRENCY_CODE) AS CURRENCY_CODE,
    e.STATUS AS STG_STATUS,
    et.STATUS AS TFM_STATUS,
    NVL(et.STATUS, e.STATUS) AS OVERALL_STATUS,
    NVL(et.STATUS, e.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(et.ERROR_TEXT, e.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    e.STAGE_DATE,
    et.RESULTS_UPDATED_DATE,
    NULL AS FUSION_LINK,
    e.SCENARIO_ID
FROM
    DMT_OWNER.DMT_PJC_EXPENDITURES_STG_TBL e
    LEFT JOIN DMT_OWNER.DMT_PJC_EXPENDITURES_TFM_TBL et
        ON et.STG_SEQUENCE_ID = e.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = et.INTEGRATION_ID
ORDER BY
    e.STAGE_DATE DESC,
    e.STG_SEQUENCE_ID DESC;
