-- DMT_RUN_HISTORY_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_RUN_HISTORY_V" ("RUN_ID", "PIPELINE_CODES", "SCENARIO_NAME", "PREFIX", "RUN_MODE", "RUN_STATUS", "ON_FAILURE_POLICY", "SUBMITTED_DATE", "COMPLETED_DATE", "SUBMITTED_BY", "TOTAL_OBJECTS", "DONE_COUNT", "FAILED_COUNT", "SKIPPED_COUNT", "CURRENT_STEP")  AS 
  SELECT r.RUN_ID,
       r.PIPELINE_CODES,
       r.SCENARIO_NAME,
       r.PREFIX,
       r.RUN_MODE,
       r.RUN_STATUS,
       r.ON_FAILURE_POLICY,
       r.SUBMITTED_DATE,
       r.COMPLETED_DATE,
       r.SUBMITTED_BY,
       (SELECT COUNT(*) FROM DMT_WORK_QUEUE_TBL q WHERE q.RUN_ID = r.RUN_ID) AS TOTAL_OBJECTS,
       (SELECT COUNT(*) FROM DMT_WORK_QUEUE_TBL q WHERE q.RUN_ID = r.RUN_ID AND q.WORK_STATUS = 'DONE') AS DONE_COUNT,
       (SELECT COUNT(*) FROM DMT_WORK_QUEUE_TBL q WHERE q.RUN_ID = r.RUN_ID AND q.WORK_STATUS = 'FAILED') AS FAILED_COUNT,
       (SELECT COUNT(*) FROM DMT_WORK_QUEUE_TBL q WHERE q.RUN_ID = r.RUN_ID AND q.WORK_STATUS = 'SKIPPED') AS SKIPPED_COUNT,
       (SELECT q.CEMLI_CODE || ' (' || q.WORK_STATUS || ')'
        FROM DMT_WORK_QUEUE_TBL q
        WHERE q.RUN_ID = r.RUN_ID
          AND q.WORK_STATUS NOT IN ('DONE','FAILED','SKIPPED','PENDING')
        FETCH FIRST 1 ROW ONLY) AS CURRENT_STEP
FROM DMT_PIPELINE_RUN_TBL r;
