-- DMT_P2P_SUPPLIERS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_P2P_SUPPLIERS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "VENDOR_NAME", "SUPPLIER_NUMBER", "SUPPLIER_TYPE", "STAGE_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "FUSION_VENDOR_ID", "FUSION_VENDOR_NUMBER", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    h.STG_SEQUENCE_ID,
    ht.TFM_SEQUENCE_ID,
    h.SOURCE_ID,
    NVL(ht.VENDOR_NAME, h.VENDOR_NAME) AS VENDOR_NAME,
    NVL(ht.SEGMENT1, h.SEGMENT1) AS SUPPLIER_NUMBER,
    NVL(ht.VENDOR_TYPE_LOOKUP_CODE, h.VENDOR_TYPE_LOOKUP_CODE) AS SUPPLIER_TYPE,
    h.STAGE_DATE,
    h.STATUS AS STG_STATUS,
    ht.STATUS AS TFM_STATUS,
    NVL(ht.STATUS, h.STATUS) AS OVERALL_STATUS,
    NVL(ht.STATUS, h.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(ht.ERROR_TEXT, h.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ht.FUSION_VENDOR_ID,
    ht.FUSION_VENDOR_NUMBER,
    ht.RESULTS_UPDATED_DATE,
    DMT_UTIL_PKG.GET_DEEP_LINK('Suppliers', ht.FUSION_VENDOR_ID) AS FUSION_LINK,
    h.SCENARIO_ID
FROM
    DMT_OWNER.DMT_POZ_SUPPLIERS_STG_TBL h
    LEFT JOIN DMT_OWNER.DMT_POZ_SUPPLIERS_TFM_TBL ht
        ON ht.STG_SEQUENCE_ID = h.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ht.INTEGRATION_ID
ORDER BY
    h.STAGE_DATE DESC,
    h.STG_SEQUENCE_ID DESC;
