-- DMT_PROJECT_BUDGETS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_PROJECT_BUDGETS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "PROJECT_NAME", "PROJECT_NUMBER", "TASK_NUMBER", "EXPENDITURE_TYPE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT m.INTEGRATION_ID, m.ORCHESTRATION_CODE, m.START_DATE AS RUN_DATE, m.PREFIX,
    t.STG_SEQUENCE_ID, tt.TFM_SEQUENCE_ID, t.SOURCE_ID,
    NVL(tt.PROJECT_NAME, t.PROJECT_NAME) AS PROJECT_NAME,
    NVL(tt.PROJECT_NUMBER, t.PROJECT_NUMBER) AS PROJECT_NUMBER,
    NVL(tt.TASK_NUMBER, t.TASK_NUMBER) AS TASK_NUMBER,
    NVL(tt.EXPENDITURE_TYPE, t.EXPENDITURE_TYPE) AS EXPENDITURE_TYPE,
    t.STATUS AS STG_STATUS,
    tt.STATUS AS TFM_STATUS,
    NVL(tt.STATUS, t.STATUS) AS OVERALL_STATUS,
    NVL(tt.STATUS, t.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(tt.ERROR_TEXT, t.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    t.STAGE_DATE, tt.RESULTS_UPDATED_DATE, NULL AS FUSION_LINK, t.SCENARIO_ID
FROM DMT_OWNER.DMT_PJC_TXN_CONTROLS_STG_TBL t
    LEFT JOIN DMT_OWNER.DMT_PJC_TXN_CONTROLS_TFM_TBL tt ON tt.STG_SEQUENCE_ID = t.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m ON m.INTEGRATION_ID = tt.INTEGRATION_ID
ORDER BY t.STAGE_DATE DESC, t.STG_SEQUENCE_ID DESC;
