-- DMT_V_SUP_SITE_ASSN_DETAIL
CREATE OR REPLACE EDITIONABLE VIEW "DMT_V_SUP_SITE_ASSN_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "VENDOR_NAME", "VENDOR_SITE_CODE", "BUSINESS_UNIT_NAME", "IMPORT_ACTION", "PROCUREMENT_BUSINESS_UNIT_NAME", "BILL_TO_BU_NAME", "SHIP_TO_LOCATION_CODE", "BILL_TO_LOCATION_CODE", "ALLOW_AWT_FLAG", "AWT_GROUP_NAME", "ACCTS_PAY_CONCAT_SEGMENTS", "PREPAY_CONCAT_SEGMENTS", "FUTURE_DATED_CONCAT_SEGMENTS", "DISTRIBUTION_SET_NAME", "INACTIVE_DATE", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    -- 1. Run status
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    -- 2. Error text
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    -- 3. Human identifiers
    stg.VENDOR_NAME                                         AS VENDOR_NAME,
    stg.VENDOR_SITE_CODE                                    AS VENDOR_SITE_CODE,
    stg.BUSINESS_UNIT_NAME                                  AS BUSINESS_UNIT_NAME,
    -- 4. All remaining STG business columns
    stg.IMPORT_ACTION,
    stg.PROCUREMENT_BUSINESS_UNIT_NAME,
    stg.BILL_TO_BU_NAME,
    stg.SHIP_TO_LOCATION_CODE,
    stg.BILL_TO_LOCATION_CODE,
    stg.ALLOW_AWT_FLAG,
    stg.AWT_GROUP_NAME,
    stg.ACCTS_PAY_CONCAT_SEGMENTS,
    stg.PREPAY_CONCAT_SEGMENTS,
    stg.FUTURE_DATED_CONCAT_SEGMENTS,
    stg.DISTRIBUTION_SET_NAME,
    stg.INACTIVE_DATE,
    stg.SOURCE_ID,
    -- 5. STG_SEQUENCE_ID
    stg.STG_SEQUENCE_ID,
    -- 6. RUN_ID
    tfm.RUN_ID,
    -- 7. PREFIX (from PIPELINE_RUN)
    cm.PREFIX,
    -- 8. SCENARIO_ID
    stg.SCENARIO_ID,
    -- 9. STAGE_DATE
    stg.STAGE_DATE,
    -- 10. LAST_UPDATED_DATE
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_POZ_SUP_SITE_ASSN_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_POZ_SUP_SITE_ASSN_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
