-- DMT_STG_ATTEMPT_V  (backlog #310 -- FAILED-mode selection from the run-stamped record)
-- ============================================================
-- One row per stage-to-transform ATTEMPT of a staging row, in every run, read
-- only from the two run-stamped homes the design names (DMT_DESIGN.html
-- section 5, DMT_STG_TFM_ERROR_TBL: "run-mode selection (NEW / FAILED / ALL)
-- becomes predicates over this table and TFM, not over an STG status column"):
--
--   * a TFM row   -> the attempt reached TFM; OUTCOME = its TFM_STATUS
--                    (LOADED / FAILED / UNACCOUNTED / GENERATED / STAGED ...)
--   * an error row in DMT_STG_TFM_ERROR_TBL -> the attempt died before TFM;
--                    OUTCOME = 'STG_TFM_ERROR'
--
-- Its single reader is DMT_UTIL_PKG.FAILED_RETRY_SELECTED, which picks each
-- row's most recent attempt (ORDER BY RUN_ID, ATTEMPT_RANK, ATTEMPT_ID) and
-- tells FAILED mode whether to retry it. STG_STATUS is never read here.
--
-- Columns:
--   STG_TABLE        the staging table the attempt belongs to (STG_SEQUENCE_ID
--                    is an identity per STG table, so the pair is the key)
--   STG_SEQUENCE_ID  the staging row
--   RUN_ID           the run that made the attempt
--   ATTEMPT_RANK     0 = pre-TFM error row, 1 = TFM row (a run that has both
--                    reached TFM, so its TFM row is the later attempt)
--   ATTEMPT_ID       TFM_SEQUENCE_ID or ERROR_ID (tie-break within a run)
--   OUTCOME          TFM_STATUS, or 'STG_TFM_ERROR'
--
-- TEMPLATE (every arm is identical except the names; keep it that way):
--   TFM arm:   SELECT '<STG table>', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS
--              FROM <TFM table>
--   error arm: one arm for the whole error table, joined to the SUB_OBJECT ->
--              STG table map below. The SUB_OBJECT literals are exactly the
--              ones each object's FLAG_STG_FAILED / transform-error handler
--              writes, so an error row maps to the STG table it flagged.
-- Adding an object = one TFM arm + its SUB_OBJECT line(s) in the map.
-- ============================================================
CREATE OR REPLACE EDITIONABLE VIEW "DMT_STG_ATTEMPT_V" (
    "STG_TABLE", "STG_SEQUENCE_ID", "RUN_ID", "ATTEMPT_RANK", "ATTEMPT_ID", "OUTCOME"
) AS
    SELECT 'DMT_ABSENCE_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_ABSENCE_TFM_TBL
    UNION ALL
    SELECT 'DMT_AP_INVOICES_INT_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_AP_INVOICES_INT_TFM_TBL
    UNION ALL
    SELECT 'DMT_AP_INVOICE_LINES_INT_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_AP_INVOICE_LINES_INT_TFM_TBL
    UNION ALL
    SELECT 'DMT_AP_PAY_TERM_HDR_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_AP_PAY_TERM_HDR_TFM_TBL
    UNION ALL
    SELECT 'DMT_AP_PAY_TERM_LINE_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_AP_PAY_TERM_LINE_TFM_TBL
    UNION ALL
    SELECT 'DMT_ASSIGNMENT_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_ASSIGNMENT_TFM_TBL
    UNION ALL
    SELECT 'DMT_BEN_BENFY_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_BEN_BENFY_TFM_TBL
    UNION ALL
    SELECT 'DMT_BEN_DEPEND_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_BEN_DEPEND_TFM_TBL
    UNION ALL
    SELECT 'DMT_BEN_PARTIC_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_BEN_PARTIC_TFM_TBL
    UNION ALL
    SELECT 'DMT_CE_BANK_ACCT_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_CE_BANK_ACCT_TFM_TBL
    UNION ALL
    SELECT 'DMT_CE_BANK_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_CE_BANK_TFM_TBL
    UNION ALL
    SELECT 'DMT_CE_BRANCH_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_CE_BRANCH_TFM_TBL
    UNION ALL
    SELECT 'DMT_EGP_ITEM_CAT_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_EGP_ITEM_CAT_TFM_TBL
    UNION ALL
    SELECT 'DMT_EGP_ITEM_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_EGP_ITEM_TFM_TBL
    UNION ALL
    SELECT 'DMT_FA_ASSET_ASSIGN_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_FA_ASSET_ASSIGN_TFM_TBL
    UNION ALL
    SELECT 'DMT_FA_ASSET_BOOK_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_FA_ASSET_BOOK_TFM_TBL
    UNION ALL
    SELECT 'DMT_FA_ASSET_HDR_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_FA_ASSET_HDR_TFM_TBL
    UNION ALL
    SELECT 'DMT_FND_LOOKUP_TYPE_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_FND_LOOKUP_TYPE_TFM_TBL
    UNION ALL
    SELECT 'DMT_FND_LOOKUP_VALUE_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_FND_LOOKUP_VALUE_TFM_TBL
    UNION ALL
    SELECT 'DMT_FND_VS_SET_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_FND_VS_SET_TFM_TBL
    UNION ALL
    SELECT 'DMT_FND_VS_VALUE_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_FND_VS_VALUE_TFM_TBL
    UNION ALL
    SELECT 'DMT_GL_BUDGET_INT_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GL_BUDGET_INT_TFM_TBL
    UNION ALL
    SELECT 'DMT_GL_CALENDAR_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GL_CALENDAR_TFM_TBL
    UNION ALL
    SELECT 'DMT_GL_INTERFACE_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GL_INTERFACE_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_BDGT_PRDS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_BDGT_PRDS_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_CERTS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_CERTS_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_CFDAS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_CFDAS_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_FUNDING_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_FUNDING_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_FUND_ALLOC_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_FUND_ALLOC_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_FUND_SRC_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_FUND_SRC_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_HEADERS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_HEADERS_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_KEYWORDS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_KEYWORDS_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_ORG_CREDITS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_ORG_CREDITS_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_PERSONNEL_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_PERSONNEL_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_PRJ_FUND_SRC_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_PRJ_FUND_SRC_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_PRJ_TSK_BRD_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_PRJ_TSK_BRD_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_PROJECTS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_PROJECTS_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_REFERENCES_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_REFERENCES_TFM_TBL
    UNION ALL
    SELECT 'DMT_GMS_AWD_TERMS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_GMS_AWD_TERMS_TFM_TBL
    UNION ALL
    SELECT 'DMT_HZ_ACCOUNTS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_HZ_ACCOUNTS_TFM_TBL
    UNION ALL
    SELECT 'DMT_HZ_ACCT_SITES_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_HZ_ACCT_SITES_TFM_TBL
    UNION ALL
    SELECT 'DMT_HZ_ACCT_SITE_USES_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_HZ_ACCT_SITE_USES_TFM_TBL
    UNION ALL
    SELECT 'DMT_HZ_LOCATIONS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_HZ_LOCATIONS_TFM_TBL
    UNION ALL
    SELECT 'DMT_HZ_PARTIES_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_HZ_PARTIES_TFM_TBL
    UNION ALL
    SELECT 'DMT_HZ_PARTY_SITES_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_HZ_PARTY_SITES_TFM_TBL
    UNION ALL
    SELECT 'DMT_HZ_PARTY_SITE_USES_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_HZ_PARTY_SITE_USES_TFM_TBL
    UNION ALL
    SELECT 'DMT_INV_TRX_LOTS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_INV_TRX_LOTS_TFM_TBL
    UNION ALL
    SELECT 'DMT_INV_TRX_SERIALS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_INV_TRX_SERIALS_TFM_TBL
    UNION ALL
    SELECT 'DMT_INV_TRX_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_INV_TRX_TFM_TBL
    UNION ALL
    SELECT 'DMT_INV_UOM_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_INV_UOM_TFM_TBL
    UNION ALL
    SELECT 'DMT_PAY_REL_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PAY_REL_TFM_TBL
    UNION ALL
    SELECT 'DMT_PERF_EVAL_RATING_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PERF_EVAL_RATING_TFM_TBL
    UNION ALL
    SELECT 'DMT_PERF_EVAL_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PERF_EVAL_TFM_TBL
    UNION ALL
    SELECT 'DMT_PERSON_ADDR_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PERSON_ADDR_TFM_TBL
    UNION ALL
    SELECT 'DMT_PERSON_EMAIL_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PERSON_EMAIL_TFM_TBL
    UNION ALL
    SELECT 'DMT_PERSON_LEGISL_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PERSON_LEGISL_TFM_TBL
    UNION ALL
    SELECT 'DMT_PERSON_NAME_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PERSON_NAME_TFM_TBL
    UNION ALL
    SELECT 'DMT_PERSON_NID_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PERSON_NID_TFM_TBL
    UNION ALL
    SELECT 'DMT_PERSON_PHONE_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PERSON_PHONE_TFM_TBL
    UNION ALL
    SELECT 'DMT_PJB_BILL_EVENTS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PJB_BILL_EVENTS_TFM_TBL
    UNION ALL
    SELECT 'DMT_PJC_EXPENDITURES_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PJC_EXPENDITURES_TFM_TBL
    UNION ALL
    SELECT 'DMT_PJC_TXN_CONTROLS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PJC_TXN_CONTROLS_TFM_TBL
    UNION ALL
    SELECT 'DMT_PJF_PROJECTS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PJF_PROJECTS_TFM_TBL
    UNION ALL
    SELECT 'DMT_PJF_TASKS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PJF_TASKS_TFM_TBL
    UNION ALL
    SELECT 'DMT_PJF_TEAM_MEMBERS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PJF_TEAM_MEMBERS_TFM_TBL
    UNION ALL
    SELECT 'DMT_PLAN_BUDGET_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PLAN_BUDGET_TFM_TBL
    UNION ALL
    SELECT 'DMT_POR_REQ_DISTS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_POR_REQ_DISTS_TFM_TBL
    UNION ALL
    SELECT 'DMT_POR_REQ_HEADERS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_POR_REQ_HEADERS_TFM_TBL
    UNION ALL
    SELECT 'DMT_POR_REQ_LINES_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_POR_REQ_LINES_TFM_TBL
    UNION ALL
    SELECT 'DMT_POZ_SUPPLIERS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_POZ_SUPPLIERS_TFM_TBL
    UNION ALL
    SELECT 'DMT_POZ_SUP_ADDR_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_POZ_SUP_ADDR_TFM_TBL
    UNION ALL
    SELECT 'DMT_POZ_SUP_CONTACTS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_POZ_SUP_CONTACTS_TFM_TBL
    UNION ALL
    SELECT 'DMT_POZ_SUP_SITE_ASSN_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_POZ_SUP_SITE_ASSN_TFM_TBL
    UNION ALL
    SELECT 'DMT_POZ_SUP_SITE_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_POZ_SUP_SITE_TFM_TBL
    UNION ALL
    SELECT 'DMT_PO_DISTS_INT_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PO_DISTS_INT_TFM_TBL
    UNION ALL
    SELECT 'DMT_PO_HEADERS_INT_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PO_HEADERS_INT_TFM_TBL
    UNION ALL
    SELECT 'DMT_PO_LINES_INT_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PO_LINES_INT_TFM_TBL
    UNION ALL
    SELECT 'DMT_PO_LINE_LOCS_INT_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PO_LINE_LOCS_INT_TFM_TBL
    UNION ALL
    SELECT 'DMT_PRJ_BUDGET_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_PRJ_BUDGET_TFM_TBL
    UNION ALL
    SELECT 'DMT_RA_DISTS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_RA_DISTS_TFM_TBL
    UNION ALL
    SELECT 'DMT_RA_LINES_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_RA_LINES_TFM_TBL
    UNION ALL
    SELECT 'DMT_SALARY_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_SALARY_TFM_TBL
    UNION ALL
    SELECT 'DMT_SAL_BASIS_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_SAL_BASIS_TFM_TBL
    UNION ALL
    SELECT 'DMT_TALENT_PROF_ITEM_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_TALENT_PROF_ITEM_TFM_TBL
    UNION ALL
    SELECT 'DMT_TALENT_PROF_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_TALENT_PROF_TFM_TBL
    UNION ALL
    SELECT 'DMT_TAX_CARD_COMP_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_TAX_CARD_COMP_TFM_TBL
    UNION ALL
    SELECT 'DMT_TAX_CARD_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_TAX_CARD_TFM_TBL
    UNION ALL
    SELECT 'DMT_W2_BAL_DTL_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_W2_BAL_DTL_TFM_TBL
    UNION ALL
    SELECT 'DMT_W2_BAL_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_W2_BAL_TFM_TBL
    UNION ALL
    SELECT 'DMT_WORKER_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_WORKER_TFM_TBL
    UNION ALL
    SELECT 'DMT_WORK_REL_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_WORK_REL_TFM_TBL
    UNION ALL
    SELECT 'DMT_WORK_SCHED_DTL_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_WORK_SCHED_DTL_TFM_TBL
    UNION ALL
    SELECT 'DMT_WORK_SCHED_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_WORK_SCHED_TFM_TBL
    UNION ALL
    SELECT 'DMT_ZX_RATE_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_ZX_RATE_TFM_TBL
    UNION ALL
    SELECT 'DMT_ZX_REGIME_STG_TBL', STG_SEQUENCE_ID, RUN_ID, 1, TFM_SEQUENCE_ID, TFM_STATUS FROM DMT_ZX_REGIME_TFM_TBL
    UNION ALL
    SELECT m.STG_TABLE, e.STG_SEQUENCE_ID, e.RUN_ID, 0, e.ERROR_ID, 'STG_TFM_ERROR'
    FROM   DMT_STG_TFM_ERROR_TBL e
    JOIN   (
            SELECT 'Absences' AS SUB_OBJECT, 'DMT_ABSENCE_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'AP Invoice Headers' AS SUB_OBJECT, 'DMT_AP_INVOICES_INT_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'AP Invoice Lines' AS SUB_OBJECT, 'DMT_AP_INVOICE_LINES_INT_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Payment Term Headers' AS SUB_OBJECT, 'DMT_AP_PAY_TERM_HDR_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Payment Term Lines' AS SUB_OBJECT, 'DMT_AP_PAY_TERM_LINE_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Assignments' AS SUB_OBJECT, 'DMT_ASSIGNMENT_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Beneficiary Enrollment' AS SUB_OBJECT, 'DMT_BEN_BENFY_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Dependent Enrollment' AS SUB_OBJECT, 'DMT_BEN_DEPEND_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Participant Enrollment' AS SUB_OBJECT, 'DMT_BEN_PARTIC_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Bank Accounts' AS SUB_OBJECT, 'DMT_CE_BANK_ACCT_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Banks' AS SUB_OBJECT, 'DMT_CE_BANK_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Bank Branches' AS SUB_OBJECT, 'DMT_CE_BRANCH_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Item Categories' AS SUB_OBJECT, 'DMT_EGP_ITEM_CAT_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Item Master' AS SUB_OBJECT, 'DMT_EGP_ITEM_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Asset Assignments' AS SUB_OBJECT, 'DMT_FA_ASSET_ASSIGN_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Asset Books' AS SUB_OBJECT, 'DMT_FA_ASSET_BOOK_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Asset Headers' AS SUB_OBJECT, 'DMT_FA_ASSET_HDR_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Lookup Types' AS SUB_OBJECT, 'DMT_FND_LOOKUP_TYPE_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Lookup Values' AS SUB_OBJECT, 'DMT_FND_LOOKUP_VALUE_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Value Sets' AS SUB_OBJECT, 'DMT_FND_VS_SET_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Value Set Values' AS SUB_OBJECT, 'DMT_FND_VS_VALUE_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'GL Budget Balances' AS SUB_OBJECT, 'DMT_GL_BUDGET_INT_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'GL Calendar' AS SUB_OBJECT, 'DMT_GL_CALENDAR_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'GL Journals' AS SUB_OBJECT, 'DMT_GL_INTERFACE_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Budget Periods' AS SUB_OBJECT, 'DMT_GMS_AWD_BDGT_PRDS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Award Certifications' AS SUB_OBJECT, 'DMT_GMS_AWD_CERTS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Award CFDAs' AS SUB_OBJECT, 'DMT_GMS_AWD_CFDAS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Award Funding' AS SUB_OBJECT, 'DMT_GMS_AWD_FUNDING_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Funding Allocations' AS SUB_OBJECT, 'DMT_GMS_AWD_FUND_ALLOC_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Award Funding Sources' AS SUB_OBJECT, 'DMT_GMS_AWD_FUND_SRC_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Award Headers' AS SUB_OBJECT, 'DMT_GMS_AWD_HEADERS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Award Keywords' AS SUB_OBJECT, 'DMT_GMS_AWD_KEYWORDS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Org Credits' AS SUB_OBJECT, 'DMT_GMS_AWD_ORG_CREDITS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Award Personnel' AS SUB_OBJECT, 'DMT_GMS_AWD_PERSONNEL_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Project Funding Sources' AS SUB_OBJECT, 'DMT_GMS_AWD_PRJ_FUND_SRC_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Project Task Burden' AS SUB_OBJECT, 'DMT_GMS_AWD_PRJ_TSK_BRD_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Award Projects' AS SUB_OBJECT, 'DMT_GMS_AWD_PROJECTS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Award References' AS SUB_OBJECT, 'DMT_GMS_AWD_REFERENCES_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Award Terms' AS SUB_OBJECT, 'DMT_GMS_AWD_TERMS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Accounts' AS SUB_OBJECT, 'DMT_HZ_ACCOUNTS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Account Sites' AS SUB_OBJECT, 'DMT_HZ_ACCT_SITES_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Account Site Uses' AS SUB_OBJECT, 'DMT_HZ_ACCT_SITE_USES_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Locations' AS SUB_OBJECT, 'DMT_HZ_LOCATIONS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Parties' AS SUB_OBJECT, 'DMT_HZ_PARTIES_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Party Sites' AS SUB_OBJECT, 'DMT_HZ_PARTY_SITES_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Party Site Uses' AS SUB_OBJECT, 'DMT_HZ_PARTY_SITE_USES_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Transaction Lots' AS SUB_OBJECT, 'DMT_INV_TRX_LOTS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Transaction Serials' AS SUB_OBJECT, 'DMT_INV_TRX_SERIALS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Inventory Transactions' AS SUB_OBJECT, 'DMT_INV_TRX_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Units of Measure' AS SUB_OBJECT, 'DMT_INV_UOM_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Payroll Relationships' AS SUB_OBJECT, 'DMT_PAY_REL_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Performance Ratings' AS SUB_OBJECT, 'DMT_PERF_EVAL_RATING_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Performance Docs' AS SUB_OBJECT, 'DMT_PERF_EVAL_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Person Addresses' AS SUB_OBJECT, 'DMT_PERSON_ADDR_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Person Emails' AS SUB_OBJECT, 'DMT_PERSON_EMAIL_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Person Legislation' AS SUB_OBJECT, 'DMT_PERSON_LEGISL_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Person Names' AS SUB_OBJECT, 'DMT_PERSON_NAME_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Person NIDs' AS SUB_OBJECT, 'DMT_PERSON_NID_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Person Phones' AS SUB_OBJECT, 'DMT_PERSON_PHONE_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Billing Events' AS SUB_OBJECT, 'DMT_PJB_BILL_EVENTS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Project Expenditures' AS SUB_OBJECT, 'DMT_PJC_EXPENDITURES_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Txn Controls' AS SUB_OBJECT, 'DMT_PJC_TXN_CONTROLS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Projects' AS SUB_OBJECT, 'DMT_PJF_PROJECTS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Project Tasks' AS SUB_OBJECT, 'DMT_PJF_TASKS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Team Members' AS SUB_OBJECT, 'DMT_PJF_TEAM_MEMBERS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Planning Budget Lines' AS SUB_OBJECT, 'DMT_PLAN_BUDGET_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Req Distributions' AS SUB_OBJECT, 'DMT_POR_REQ_DISTS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Req Headers' AS SUB_OBJECT, 'DMT_POR_REQ_HEADERS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Req Lines' AS SUB_OBJECT, 'DMT_POR_REQ_LINES_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Suppliers' AS SUB_OBJECT, 'DMT_POZ_SUPPLIERS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Supplier Addresses' AS SUB_OBJECT, 'DMT_POZ_SUP_ADDR_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Supplier Contacts' AS SUB_OBJECT, 'DMT_POZ_SUP_CONTACTS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Site Assignments' AS SUB_OBJECT, 'DMT_POZ_SUP_SITE_ASSN_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Supplier Sites' AS SUB_OBJECT, 'DMT_POZ_SUP_SITE_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'PO Distributions' AS SUB_OBJECT, 'DMT_PO_DISTS_INT_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Blanket PO Headers' AS SUB_OBJECT, 'DMT_PO_HEADERS_INT_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Contract Headers' AS SUB_OBJECT, 'DMT_PO_HEADERS_INT_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'PO Headers' AS SUB_OBJECT, 'DMT_PO_HEADERS_INT_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Blanket PO Lines' AS SUB_OBJECT, 'DMT_PO_LINES_INT_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'PO Lines' AS SUB_OBJECT, 'DMT_PO_LINES_INT_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'PO Line Locations' AS SUB_OBJECT, 'DMT_PO_LINE_LOCS_INT_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Project Budget Lines' AS SUB_OBJECT, 'DMT_PRJ_BUDGET_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Project Budgets' AS SUB_OBJECT, 'DMT_PRJ_BUDGET_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'AR Distributions' AS SUB_OBJECT, 'DMT_RA_DISTS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'AR Lines' AS SUB_OBJECT, 'DMT_RA_LINES_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Salaries' AS SUB_OBJECT, 'DMT_SALARY_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Salary Bases' AS SUB_OBJECT, 'DMT_SAL_BASIS_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Profile Items' AS SUB_OBJECT, 'DMT_TALENT_PROF_ITEM_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Talent Profiles' AS SUB_OBJECT, 'DMT_TALENT_PROF_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Tax Card Components' AS SUB_OBJECT, 'DMT_TAX_CARD_COMP_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Tax Cards' AS SUB_OBJECT, 'DMT_TAX_CARD_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'W2 Balance Details' AS SUB_OBJECT, 'DMT_W2_BAL_DTL_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'W2 Balances' AS SUB_OBJECT, 'DMT_W2_BAL_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Workers' AS SUB_OBJECT, 'DMT_WORKER_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Work Relationships' AS SUB_OBJECT, 'DMT_WORK_REL_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Schedule Details' AS SUB_OBJECT, 'DMT_WORK_SCHED_DTL_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Work Schedules' AS SUB_OBJECT, 'DMT_WORK_SCHED_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Tax Rates' AS SUB_OBJECT, 'DMT_ZX_RATE_STG_TBL' AS STG_TABLE FROM DUAL
            UNION ALL
            SELECT 'Tax Regimes' AS SUB_OBJECT, 'DMT_ZX_REGIME_STG_TBL' AS STG_TABLE FROM DUAL
           ) m
    ON     m.SUB_OBJECT = e.SUB_OBJECT;
