-- DMT_V_CUST_LOCATIONS_DETAIL
CREATE OR REPLACE EDITIONABLE VIEW "DMT_V_CUST_LOCATIONS_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "LOCATION_ORIG_SYSTEM_REFERENCE", "BATCH_ID", "LOCATION_ORIG_SYSTEM", "INSERT_UPDATE_FLAG", "COUNTRY", "ADDRESS1", "ADDRESS2", "ADDRESS3", "ADDRESS4", "CITY", "STATE", "PROVINCE", "COUNTY", "POSTAL_CODE", "POSTAL_PLUS4_CODE", "LOCATION_LANGUAGE", "DESCRIPTION", "SHORT_DESCRIPTION", "SALES_TAX_GEOCODE", "SALES_TAX_INSIDE_CITY_LIMITS", "TIMEZONE_CODE", "ADDRESS1_STD", "ADAPTER_CONTENT_SOURCE", "ADDR_VALID_STATUS_CODE", "DATE_VALIDATED", "ADDRESS_EFFECTIVE_DATE", "ADDRESS_EXPIRATION_DATE", "VALIDATED_FLAG", "DO_NOT_VALIDATE_FLAG", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "ATTRIBUTE16", "ATTRIBUTE17", "ATTRIBUTE18", "ATTRIBUTE19", "ATTRIBUTE20", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    -- 1. Run status
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    -- 2. Error text
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    -- 3. Human identifier
    stg.LOCATION_ORIG_SYSTEM_REFERENCE                       AS LOCATION_ORIG_SYSTEM_REFERENCE,
    -- 4. All remaining STG business columns
    stg.BATCH_ID,
    stg.LOCATION_ORIG_SYSTEM,
    stg.INSERT_UPDATE_FLAG,
    stg.COUNTRY,
    stg.ADDRESS1,
    stg.ADDRESS2,
    stg.ADDRESS3,
    stg.ADDRESS4,
    stg.CITY,
    stg.STATE,
    stg.PROVINCE,
    stg.COUNTY,
    stg.POSTAL_CODE,
    stg.POSTAL_PLUS4_CODE,
    stg.LOCATION_LANGUAGE,
    stg.DESCRIPTION,
    stg.SHORT_DESCRIPTION,
    stg.SALES_TAX_GEOCODE,
    stg.SALES_TAX_INSIDE_CITY_LIMITS,
    stg.TIMEZONE_CODE,
    stg.ADDRESS1_STD,
    stg.ADAPTER_CONTENT_SOURCE,
    stg.ADDR_VALID_STATUS_CODE,
    stg.DATE_VALIDATED,
    stg.ADDRESS_EFFECTIVE_DATE,
    stg.ADDRESS_EXPIRATION_DATE,
    stg.VALIDATED_FLAG,
    stg.DO_NOT_VALIDATE_FLAG,
    stg.ATTRIBUTE_CATEGORY,
    stg.ATTRIBUTE1,
    stg.ATTRIBUTE2,
    stg.ATTRIBUTE3,
    stg.ATTRIBUTE4,
    stg.ATTRIBUTE5,
    stg.ATTRIBUTE6,
    stg.ATTRIBUTE7,
    stg.ATTRIBUTE8,
    stg.ATTRIBUTE9,
    stg.ATTRIBUTE10,
    stg.ATTRIBUTE11,
    stg.ATTRIBUTE12,
    stg.ATTRIBUTE13,
    stg.ATTRIBUTE14,
    stg.ATTRIBUTE15,
    stg.ATTRIBUTE16,
    stg.ATTRIBUTE17,
    stg.ATTRIBUTE18,
    stg.ATTRIBUTE19,
    stg.ATTRIBUTE20,
    stg.SOURCE_ID,
    -- 5. STG_SEQUENCE_ID
    stg.STG_SEQUENCE_ID,
    -- 6. RUN_ID
    tfm.RUN_ID,
    -- 7. PREFIX (from PIPELINE_RUN)
    cm.PREFIX,
    -- 8. SCENARIO_ID (not on customer STG tables)
    CAST(NULL AS NUMBER)                                     AS SCENARIO_ID,
    -- 9. STAGE_DATE
    stg.STAGE_DATE,
    -- 10. LAST_UPDATED_DATE
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_HZ_LOCATIONS_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_HZ_LOCATIONS_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
