-- DMT_V_GL_BUDGET_DETAIL
CREATE OR REPLACE EDITIONABLE VIEW "DMT_V_GL_BUDGET_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "BUDGET_NAME", "LEDGER_NAME", "RUN_NAME", "LEDGER_ID", "BUDGET_ENTITY_NAME", "PERIOD_NAME", "CURRENCY_CODE", "JOURNAL_STATUS", "SEGMENT1", "SEGMENT2", "SEGMENT3", "SEGMENT4", "SEGMENT5", "SEGMENT6", "SEGMENT7", "SEGMENT8", "SEGMENT9", "SEGMENT10", "SEGMENT11", "SEGMENT12", "SEGMENT13", "SEGMENT14", "SEGMENT15", "SEGMENT16", "SEGMENT17", "SEGMENT18", "SEGMENT19", "SEGMENT20", "SEGMENT21", "SEGMENT22", "SEGMENT23", "SEGMENT24", "SEGMENT25", "SEGMENT26", "SEGMENT27", "SEGMENT28", "SEGMENT29", "SEGMENT30", "BUDGET_AMOUNT", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    -- 1. Run status (TFM uses TFM_STATUS, not STATUS)
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                        AS RUN_STATUS,
    -- 2. Error text
    tfm.ERROR_TEXT                                          AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    -- 3. Human identifiers
    stg.BUDGET_NAME                                         AS BUDGET_NAME,
    stg.LEDGER_NAME                                         AS LEDGER_NAME,
    -- 4. All STG business columns
    stg.RUN_NAME,
    stg.LEDGER_ID,
    stg.BUDGET_ENTITY_NAME,
    stg.PERIOD_NAME,
    stg.CURRENCY_CODE,
    stg.JOURNAL_STATUS,
    stg.SEGMENT1,
    stg.SEGMENT2,
    stg.SEGMENT3,
    stg.SEGMENT4,
    stg.SEGMENT5,
    stg.SEGMENT6,
    stg.SEGMENT7,
    stg.SEGMENT8,
    stg.SEGMENT9,
    stg.SEGMENT10,
    stg.SEGMENT11,
    stg.SEGMENT12,
    stg.SEGMENT13,
    stg.SEGMENT14,
    stg.SEGMENT15,
    stg.SEGMENT16,
    stg.SEGMENT17,
    stg.SEGMENT18,
    stg.SEGMENT19,
    stg.SEGMENT20,
    stg.SEGMENT21,
    stg.SEGMENT22,
    stg.SEGMENT23,
    stg.SEGMENT24,
    stg.SEGMENT25,
    stg.SEGMENT26,
    stg.SEGMENT27,
    stg.SEGMENT28,
    stg.SEGMENT29,
    stg.SEGMENT30,
    stg.BUDGET_AMOUNT,
    stg.SOURCE_ID,
    -- 5. STG_SEQUENCE_ID
    stg.STG_SEQUENCE_ID,
    -- 6. RUN_ID
    tfm.RUN_ID,
    -- 7. PREFIX (from PIPELINE_RUN)
    cm.PREFIX,
    -- 8. SCENARIO_ID
    stg.SCENARIO_ID,
    -- 9. STAGE_DATE
    stg.STAGE_DATE,
    -- 10. LAST_UPDATED_DATE
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_GL_BUDGET_INT_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_GL_BUDGET_INT_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
