-- DMT_MST_BANK_ACCTS_V
-- Repaired 2026-07-15 (Stage F / APEX port): master joined to TFM on RUN_ID
-- (was INTEGRATION_ID, renamed in the rebuild); FORCE dropped now that it compiles.
CREATE OR REPLACE EDITIONABLE VIEW "DMT_MST_BANK_ACCTS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "BANK_NAME", "BRANCH_NAME", "ACCOUNT_NAME", "ACCOUNT_NUMBER", "CURRENCY_CODE", "ACCOUNT_TYPE", "STAGE_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "ERROR_TEXT", "RESULTS_UPDATED_DATE", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    h.STG_SEQUENCE_ID,
    ht.TFM_SEQUENCE_ID,
    h.SOURCE_ID,
    NVL(ht.BANK_NAME, h.BANK_NAME) AS BANK_NAME,
    NVL(ht.BRANCH_NAME, h.BRANCH_NAME) AS BRANCH_NAME,
    NVL(ht.ACCOUNT_NAME, h.ACCOUNT_NAME) AS ACCOUNT_NAME,
    NVL(ht.ACCOUNT_NUMBER, h.ACCOUNT_NUMBER) AS ACCOUNT_NUMBER,
    NVL(ht.CURRENCY_CODE, h.CURRENCY_CODE) AS CURRENCY_CODE,
    NVL(ht.ACCOUNT_TYPE, h.ACCOUNT_TYPE) AS ACCOUNT_TYPE,
    h.STAGE_DATE,
    h.STG_STATUS AS STG_STATUS,
    ht.TFM_STATUS,
    NVL(ht.TFM_STATUS, h.STG_STATUS) AS OVERALL_STATUS,
    DBMS_LOB.SUBSTR(NVL(ht.ERROR_TEXT, h.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ht.RESULTS_UPDATED_DATE,
    h.SCENARIO_ID
FROM
    DMT_OWNER.DMT_CE_BANK_ACCT_STG_TBL h
    LEFT JOIN DMT_OWNER.DMT_CE_BANK_ACCT_TFM_TBL ht
        ON ht.STG_SEQUENCE_ID = h.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ht.RUN_ID;
