-- DMT_V_GRANT_CERTS_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_GRANT_CERTS_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "AWARD_NUMBER", "PROJECT_NUMBER", "CERTIFICATION_NAME", "CERTIFICATION_DATE", "CERTIFIED_BY", "CERT_STATUS", "APPROVAL_DATE", "EXPIRATION_DATE", "EXPEDITED_REVIEW", "FULL_REVIEW", "ASSURANCE_NUMBER", "EXEMPTION_NUMBER", "COMMENTS", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.AWARD_NUMBER                                        AS AWARD_NUMBER,
    stg.PROJECT_NUMBER,
    stg.CERTIFICATION_NAME,
    stg.CERTIFICATION_DATE,
    stg.CERTIFIED_BY,
    stg.CERT_STATUS,
    stg.APPROVAL_DATE,
    stg.EXPIRATION_DATE,
    stg.EXPEDITED_REVIEW,
    stg.FULL_REVIEW,
    stg.ASSURANCE_NUMBER,
    stg.EXEMPTION_NUMBER,
    stg.COMMENTS,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    cm.PREFIX,
    CAST(NULL AS NUMBER)                                    AS SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_GMS_AWD_CERTS_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_GMS_AWD_CERTS_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
