-- DMT_CFG_GL_CALENDAR_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_CFG_GL_CALENDAR_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "PERIOD_SET_NAME", "PERIOD_NAME", "PERIOD_TYPE", "PERIOD_YEAR", "PERIOD_NUM", "PERIOD_START_DATE", "PERIOD_END_DATE", "ADJUSTMENT_PERIOD_FLAG", "STAGE_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "ERROR_TEXT", "RESULTS_UPDATED_DATE", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    h.STG_SEQUENCE_ID,
    ht.TFM_SEQUENCE_ID,
    h.SOURCE_ID,
    NVL(ht.PERIOD_SET_NAME, h.PERIOD_SET_NAME) AS PERIOD_SET_NAME,
    NVL(ht.PERIOD_NAME, h.PERIOD_NAME) AS PERIOD_NAME,
    NVL(ht.PERIOD_TYPE, h.PERIOD_TYPE) AS PERIOD_TYPE,
    NVL(ht.PERIOD_YEAR, h.PERIOD_YEAR) AS PERIOD_YEAR,
    NVL(ht.PERIOD_NUM, h.PERIOD_NUM) AS PERIOD_NUM,
    NVL(ht.START_DATE, h.START_DATE) AS PERIOD_START_DATE,
    NVL(ht.END_DATE, h.END_DATE) AS PERIOD_END_DATE,
    NVL(ht.ADJUSTMENT_PERIOD_FLAG, h.ADJUSTMENT_PERIOD_FLAG) AS ADJUSTMENT_PERIOD_FLAG,
    h.STAGE_DATE,
    h.STG_STATUS AS STG_STATUS,
    ht.TFM_STATUS,
    NVL(ht.TFM_STATUS, h.STG_STATUS) AS OVERALL_STATUS,
    DBMS_LOB.SUBSTR(NVL(ht.ERROR_TEXT, h.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ht.RESULTS_UPDATED_DATE,
    h.SCENARIO_ID
FROM
    DMT_OWNER.DMT_GL_CALENDAR_STG_TBL h
    LEFT JOIN DMT_OWNER.DMT_GL_CALENDAR_TFM_TBL ht
        ON ht.STG_SEQUENCE_ID = h.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ht.INTEGRATION_ID;
