-- DMT_PROJECTS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_PROJECTS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "PROJECT_NUMBER", "PROJECT_NAME", "PROJECT_TYPE", "PROJECT_STATUS", "ORGANIZATION_NAME", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "FUSION_PROJECT_ID", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    p.STG_SEQUENCE_ID,
    pt.TFM_SEQUENCE_ID,
    p.SOURCE_ID,
    NVL(pt.PROJECT_NUMBER, p.PROJECT_NUMBER) AS PROJECT_NUMBER,
    NVL(pt.PROJECT_NAME, p.PROJECT_NAME) AS PROJECT_NAME,
    -- PROJECT_TYPE does not exist on PJF_PROJECTS TFM
    pt.SERVICE_TYPE_CODE AS PROJECT_TYPE,
    pt.PROJECT_STATUS_NAME AS PROJECT_STATUS,
    NVL(pt.ORGANIZATION_NAME, p.ORGANIZATION_NAME) AS ORGANIZATION_NAME,
    p.STATUS AS STG_STATUS,
    pt.STATUS AS TFM_STATUS,
    NVL(pt.STATUS, p.STATUS) AS OVERALL_STATUS,
    NVL(pt.STATUS, p.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(pt.ERROR_TEXT, p.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    pt.FUSION_PROJECT_ID,
    p.STAGE_DATE,
    pt.RESULTS_UPDATED_DATE,
    DMT_UTIL_PKG.GET_DEEP_LINK('Projects', pt.FUSION_PROJECT_ID) AS FUSION_LINK,
    p.SCENARIO_ID
FROM
    DMT_OWNER.DMT_PJF_PROJECTS_STG_TBL p
    LEFT JOIN DMT_OWNER.DMT_PJF_PROJECTS_TFM_TBL pt
        ON pt.STG_SEQUENCE_ID = p.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = pt.INTEGRATION_ID
ORDER BY
    p.STAGE_DATE DESC,
    p.STG_SEQUENCE_ID DESC;
