-- DMT_V_ASSIGNMENT_DETAIL
CREATE OR REPLACE EDITIONABLE VIEW "DMT_V_ASSIGNMENT_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "PERSON_NUMBER", "ASSIGNMENT_NUMBER", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "ASSIGNMENT_NAME", "ASSIGNMENT_STATUS_TYPE_CODE", "BUSINESS_UNIT_NAME", "ACTION_CODE", "JOB_CODE", "GRADE_CODE", "LOCATION_CODE", "DEPARTMENT_NAME", "POSITION_CODE", "WORKER_CATEGORY", "ASSIGNMENT_CATEGORY", "FULL_PART_TIME", "PERMANENT_TEMPORARY", "NORMAL_HOURS", "FREQUENCY", "MANAGER_PERSON_NUMBER", "MANAGER_ASSIGNMENT_NUMBER", "PRIMARY_ASSIGNMENT_FLAG", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.PERSON_NUMBER                                       AS PERSON_NUMBER,
    stg.ASSIGNMENT_NUMBER                                   AS ASSIGNMENT_NUMBER,
    stg.EFFECTIVE_START_DATE,
    stg.EFFECTIVE_END_DATE,
    stg.ASSIGNMENT_NAME,
    stg.ASSIGNMENT_STATUS_TYPE_CODE,
    stg.BUSINESS_UNIT_NAME,
    stg.ACTION_CODE,
    stg.JOB_CODE,
    stg.GRADE_CODE,
    stg.LOCATION_CODE,
    stg.DEPARTMENT_NAME,
    stg.POSITION_CODE,
    stg.WORKER_CATEGORY,
    stg.ASSIGNMENT_CATEGORY,
    stg.FULL_PART_TIME,
    stg.PERMANENT_TEMPORARY,
    stg.NORMAL_HOURS,
    stg.FREQUENCY,
    stg.MANAGER_PERSON_NUMBER,
    stg.MANAGER_ASSIGNMENT_NUMBER,
    stg.PRIMARY_ASSIGNMENT_FLAG,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID AS INTEGRATION_ID,
    cm.PREFIX,
    stg.SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_ASSIGNMENT_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_ASSIGNMENT_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
