-- DMT_TIMECARDS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_TIMECARDS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "WORK_SCHEDULE_NAME", "SCHEDULE_START_DATE", "SCHEDULE_END_DATE", "WORK_SCHEDULE_TYPE", "LEGISLATIVE_DATA_GROUP_NAME", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    s.STG_SEQUENCE_ID,
    st.TFM_SEQUENCE_ID,
    s.SOURCE_ID,
    -- WORK_SCHED TFM is a WorkSchedule (not timecard); columns renamed accordingly
    NVL(st.WORK_SCHEDULE_NAME, s.WORK_SCHEDULE_NAME) AS WORK_SCHEDULE_NAME,
    st.SCHEDULE_START_DATE,
    st.SCHEDULE_END_DATE,
    NVL(st.WORK_SCHEDULE_TYPE, s.WORK_SCHEDULE_TYPE) AS WORK_SCHEDULE_TYPE,
    -- TIMECARD_PERIOD_NAME does not exist on WORK_SCHED TFM
    NVL(st.LEGISLATIVE_DATA_GROUP_NAME, s.LEGISLATIVE_DATA_GROUP_NAME) AS LEGISLATIVE_DATA_GROUP_NAME,
    s.STATUS AS STG_STATUS,
    st.STATUS AS TFM_STATUS,
    NVL(st.STATUS, s.STATUS) AS OVERALL_STATUS,
    NVL(st.STATUS, s.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(st.ERROR_TEXT, s.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    s.STAGE_DATE,
    st.RESULTS_UPDATED_DATE,
    NULL AS FUSION_LINK,
    s.SCENARIO_ID
FROM
    DMT_OWNER.DMT_WORK_SCHED_STG_TBL s
    LEFT JOIN DMT_OWNER.DMT_WORK_SCHED_TFM_TBL st
        ON st.STG_SEQUENCE_ID = s.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = st.INTEGRATION_ID
ORDER BY
    s.STAGE_DATE DESC,
    s.STG_SEQUENCE_ID DESC;
