-- DMT_V_PO_LINES_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_PO_LINES_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "INTERFACE_HEADER_KEY", "LINE_NUM", "INTERFACE_LINE_KEY", "ACTION", "LINE_TYPE", "ITEM", "ITEM_DESCRIPTION", "ITEM_REVISION", "CATEGORY", "AMOUNT", "QUANTITY", "UNIT_OF_MEASURE", "UNIT_PRICE", "SECONDARY_QUANTITY", "SECONDARY_UNIT_OF_MEASURE", "VENDOR_PRODUCT_NUM", "NEGOTIATED_BY_PREPARER_FLAG", "HAZARD_CLASS", "UN_NUMBER", "NOTE_TO_VENDOR", "NOTE_TO_RECEIVER", "LINE_ATTRIBUTE_CATEGORY_LINES", "LINE_ATTRIBUTE1", "LINE_ATTRIBUTE2", "LINE_ATTRIBUTE3", "LINE_ATTRIBUTE4", "LINE_ATTRIBUTE5", "LINE_ATTRIBUTE6", "LINE_ATTRIBUTE7", "LINE_ATTRIBUTE8", "LINE_ATTRIBUTE9", "LINE_ATTRIBUTE10", "LINE_ATTRIBUTE11", "LINE_ATTRIBUTE12", "LINE_ATTRIBUTE13", "LINE_ATTRIBUTE14", "LINE_ATTRIBUTE15", "ATTRIBUTE16", "ATTRIBUTE17", "ATTRIBUTE18", "ATTRIBUTE19", "ATTRIBUTE20", "ATTRIBUTE_DATE1", "ATTRIBUTE_DATE2", "ATTRIBUTE_DATE3", "ATTRIBUTE_DATE4", "ATTRIBUTE_DATE5", "ATTRIBUTE_DATE6", "ATTRIBUTE_DATE7", "ATTRIBUTE_DATE8", "ATTRIBUTE_DATE9", "ATTRIBUTE_DATE10", "ATTRIBUTE_NUMBER1", "ATTRIBUTE_NUMBER2", "ATTRIBUTE_NUMBER3", "ATTRIBUTE_NUMBER4", "ATTRIBUTE_NUMBER5", "ATTRIBUTE_NUMBER6", "ATTRIBUTE_NUMBER7", "ATTRIBUTE_NUMBER8", "ATTRIBUTE_NUMBER9", "ATTRIBUTE_NUMBER10", "ATTRIBUTE_TIMESTAMP1", "ATTRIBUTE_TIMESTAMP2", "ATTRIBUTE_TIMESTAMP3", "ATTRIBUTE_TIMESTAMP4", "ATTRIBUTE_TIMESTAMP5", "ATTRIBUTE_TIMESTAMP6", "ATTRIBUTE_TIMESTAMP7", "ATTRIBUTE_TIMESTAMP8", "ATTRIBUTE_TIMESTAMP9", "ATTRIBUTE_TIMESTAMP10", "UNIT_WEIGHT", "WEIGHT_UOM_CODE", "WEIGHT_UNIT_OF_MEASURE", "UNIT_VOLUME", "VOLUME_UOM_CODE", "VOLUME_UNIT_OF_MEASURE", "TEMPLATE_NAME", "ITEM_ATTRIBUTE_CATEGORY", "ITEM_ATTRIBUTE1", "ITEM_ATTRIBUTE2", "ITEM_ATTRIBUTE3", "ITEM_ATTRIBUTE4", "ITEM_ATTRIBUTE5", "ITEM_ATTRIBUTE6", "ITEM_ATTRIBUTE7", "ITEM_ATTRIBUTE8", "ITEM_ATTRIBUTE9", "ITEM_ATTRIBUTE10", "ITEM_ATTRIBUTE11", "ITEM_ATTRIBUTE12", "ITEM_ATTRIBUTE13", "ITEM_ATTRIBUTE14", "ITEM_ATTRIBUTE15", "SOURCE_AGREEMENT_PRC_BU_NAME", "SOURCE_AGREEMENT", "SOURCE_AGREEMENT_LINE", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    -- 1. Run status
    NVL(tfm.STATUS, stg.STATUS)                             AS RUN_STATUS,
    -- 2. Error text
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    -- 3. Human identifiers
    stg.INTERFACE_HEADER_KEY                                AS INTERFACE_HEADER_KEY,
    stg.LINE_NUM                                            AS LINE_NUM,
    -- 4. All remaining STG business columns
    stg.INTERFACE_LINE_KEY,
    stg.ACTION,
    stg.LINE_TYPE,
    stg.ITEM,
    stg.ITEM_DESCRIPTION,
    stg.ITEM_REVISION,
    stg.CATEGORY,
    stg.AMOUNT,
    stg.QUANTITY,
    stg.UNIT_OF_MEASURE,
    stg.UNIT_PRICE,
    stg.SECONDARY_QUANTITY,
    stg.SECONDARY_UNIT_OF_MEASURE,
    stg.VENDOR_PRODUCT_NUM,
    stg.NEGOTIATED_BY_PREPARER_FLAG,
    stg.HAZARD_CLASS,
    stg.UN_NUMBER,
    stg.NOTE_TO_VENDOR,
    stg.NOTE_TO_RECEIVER,
    stg.LINE_ATTRIBUTE_CATEGORY_LINES,
    stg.LINE_ATTRIBUTE1,
    stg.LINE_ATTRIBUTE2,
    stg.LINE_ATTRIBUTE3,
    stg.LINE_ATTRIBUTE4,
    stg.LINE_ATTRIBUTE5,
    stg.LINE_ATTRIBUTE6,
    stg.LINE_ATTRIBUTE7,
    stg.LINE_ATTRIBUTE8,
    stg.LINE_ATTRIBUTE9,
    stg.LINE_ATTRIBUTE10,
    stg.LINE_ATTRIBUTE11,
    stg.LINE_ATTRIBUTE12,
    stg.LINE_ATTRIBUTE13,
    stg.LINE_ATTRIBUTE14,
    stg.LINE_ATTRIBUTE15,
    stg.ATTRIBUTE16,
    stg.ATTRIBUTE17,
    stg.ATTRIBUTE18,
    stg.ATTRIBUTE19,
    stg.ATTRIBUTE20,
    stg.ATTRIBUTE_DATE1,
    stg.ATTRIBUTE_DATE2,
    stg.ATTRIBUTE_DATE3,
    stg.ATTRIBUTE_DATE4,
    stg.ATTRIBUTE_DATE5,
    stg.ATTRIBUTE_DATE6,
    stg.ATTRIBUTE_DATE7,
    stg.ATTRIBUTE_DATE8,
    stg.ATTRIBUTE_DATE9,
    stg.ATTRIBUTE_DATE10,
    stg.ATTRIBUTE_NUMBER1,
    stg.ATTRIBUTE_NUMBER2,
    stg.ATTRIBUTE_NUMBER3,
    stg.ATTRIBUTE_NUMBER4,
    stg.ATTRIBUTE_NUMBER5,
    stg.ATTRIBUTE_NUMBER6,
    stg.ATTRIBUTE_NUMBER7,
    stg.ATTRIBUTE_NUMBER8,
    stg.ATTRIBUTE_NUMBER9,
    stg.ATTRIBUTE_NUMBER10,
    stg.ATTRIBUTE_TIMESTAMP1,
    stg.ATTRIBUTE_TIMESTAMP2,
    stg.ATTRIBUTE_TIMESTAMP3,
    stg.ATTRIBUTE_TIMESTAMP4,
    stg.ATTRIBUTE_TIMESTAMP5,
    stg.ATTRIBUTE_TIMESTAMP6,
    stg.ATTRIBUTE_TIMESTAMP7,
    stg.ATTRIBUTE_TIMESTAMP8,
    stg.ATTRIBUTE_TIMESTAMP9,
    stg.ATTRIBUTE_TIMESTAMP10,
    stg.UNIT_WEIGHT,
    stg.WEIGHT_UOM_CODE,
    stg.WEIGHT_UNIT_OF_MEASURE,
    stg.UNIT_VOLUME,
    stg.VOLUME_UOM_CODE,
    stg.VOLUME_UNIT_OF_MEASURE,
    stg.TEMPLATE_NAME,
    stg.ITEM_ATTRIBUTE_CATEGORY,
    stg.ITEM_ATTRIBUTE1,
    stg.ITEM_ATTRIBUTE2,
    stg.ITEM_ATTRIBUTE3,
    stg.ITEM_ATTRIBUTE4,
    stg.ITEM_ATTRIBUTE5,
    stg.ITEM_ATTRIBUTE6,
    stg.ITEM_ATTRIBUTE7,
    stg.ITEM_ATTRIBUTE8,
    stg.ITEM_ATTRIBUTE9,
    stg.ITEM_ATTRIBUTE10,
    stg.ITEM_ATTRIBUTE11,
    stg.ITEM_ATTRIBUTE12,
    stg.ITEM_ATTRIBUTE13,
    stg.ITEM_ATTRIBUTE14,
    stg.ITEM_ATTRIBUTE15,
    stg.SOURCE_AGREEMENT_PRC_BU_NAME,
    stg.SOURCE_AGREEMENT,
    stg.SOURCE_AGREEMENT_LINE,
    stg.SOURCE_ID,
    -- 5. STG_SEQUENCE_ID
    stg.STG_SEQUENCE_ID,
    -- 6. RUN_ID
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    -- 7. PREFIX (from PIPELINE_RUN)
    cm.PREFIX,
    -- 8. SCENARIO_ID
    stg.SCENARIO_ID,
    -- 9. STAGE_DATE
    stg.STAGE_DATE,
    -- 10. LAST_UPDATED_DATE
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_PO_LINES_INT_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_PO_LINES_INT_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
