-- DMT_OTC_AR_INVOICES_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_OTC_AR_INVOICES_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "CUSTOMER_ACCOUNT", "INVOICE_REFERENCE", "LINE_NUMBER", "LINE_AMOUNT", "LINE_CONTEXT", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    r.STG_SEQUENCE_ID,
    rt.TFM_SEQUENCE_ID,
    r.SOURCE_ID,
    NVL(rt.BILL_CUSTOMER_ACCOUNT_NUMBER, r.BILL_CUSTOMER_ACCOUNT_NUMBER) AS CUSTOMER_ACCOUNT,
    NVL(rt.TRX_NUMBER, r.TRX_NUMBER) AS INVOICE_REFERENCE,
    -- LINE_NUMBER does not exist on RA_LINES TFM
    rt.INTERFACE_LINE_ATTRIBUTE1 AS LINE_NUMBER,
    NVL(rt.AMOUNT, r.AMOUNT) AS LINE_AMOUNT,
    -- REVENUE_ACCOUNT does not exist on RA_LINES TFM
    rt.INTERFACE_LINE_CONTEXT AS LINE_CONTEXT,
    r.STATUS AS STG_STATUS,
    rt.STATUS AS TFM_STATUS,
    NVL(rt.STATUS, r.STATUS) AS OVERALL_STATUS,
    NVL(rt.STATUS, r.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(rt.ERROR_TEXT, r.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    r.STAGE_DATE,
    rt.RESULTS_UPDATED_DATE,
    DMT_UTIL_PKG.GET_DEEP_LINK('ARInvoices', rt.FUSION_CUSTOMER_TRX_ID) AS FUSION_LINK,
    r.SCENARIO_ID
FROM
    DMT_OWNER.DMT_RA_LINES_STG_TBL r
    LEFT JOIN DMT_OWNER.DMT_RA_LINES_TFM_TBL rt
        ON rt.STG_SEQUENCE_ID = r.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = rt.INTEGRATION_ID
ORDER BY
    r.STAGE_DATE DESC,
    r.STG_SEQUENCE_ID DESC;
