-- DMT_RECORD_DETAIL_V
CREATE OR REPLACE EDITIONABLE VIEW "DMT_RECORD_DETAIL_V" ("CEMLI_CODE", "SUB_OBJECT", "TFM_SEQUENCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "DISPLAY_KEY", "LOOKUP_KEY", "TFM_STATUS", "ERROR_TEXT", "ERROR_CATEGORY", "RESULTS_UPDATED_DATE", "RECONCILIATION_STATUS")  AS 
  SELECT q.CEMLI_CODE, q.SUB_OBJECT,
       q.TFM_SEQUENCE_ID, q.STG_SEQUENCE_ID, q.RUN_ID, q.RUN_ID AS INTEGRATION_ID,
       q.DISPLAY_KEY, q.LOOKUP_KEY, q.TFM_STATUS, q.ERROR_TEXT,
       q.ERROR_CATEGORY, q.RESULTS_UPDATED_DATE, q.RECONCILIATION_STATUS
FROM (
-- RECONCILIATION_STATUS: drives row-level badge color
--   CONFIRMED = LOADED or FAILED-with-error (green)
--   UNRECONCILED = FAILED with no error text (red)
--   IN_PROGRESS = GENERATED or earlier (yellow)
-- ---- Suppliers ----
SELECT 'Suppliers' AS CEMLI_CODE, 'Suppliers' AS SUB_OBJECT,
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       VENDOR_NAME AS DISPLAY_KEY,
       VENDOR_NAME AS LOOKUP_KEY,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1) AS ERROR_CATEGORY,
       RESULTS_UPDATED_DATE,
       CASE
           WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED'
           WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
           WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 'UNRECONCILED'
           ELSE 'IN_PROGRESS'
       END AS RECONCILIATION_STATUS
FROM DMT_OWNER.DMT_POZ_SUPPLIERS_TFM_TBL
UNION ALL
SELECT 'SupplierAddresses', 'Supplier Addresses',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       VENDOR_NAME || ' - ' || PARTY_SITE_NAME,
       VENDOR_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_POZ_SUP_ADDR_TFM_TBL
UNION ALL
SELECT 'SupplierSites', 'Supplier Sites',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       VENDOR_NAME || ' - ' || VENDOR_SITE_CODE,
       VENDOR_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_POZ_SUP_SITE_TFM_TBL
UNION ALL
SELECT 'SupplierSiteAssignments', 'Site Assignments',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       VENDOR_NAME || ' - ' || VENDOR_SITE_CODE,
       VENDOR_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_POZ_SUP_SITE_ASSN_TFM_TBL
UNION ALL
SELECT 'SupplierContacts', 'Supplier Contacts',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       FIRST_NAME || ' ' || LAST_NAME,
       VENDOR_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_POZ_SUP_CONTACTS_TFM_TBL
-- ---- Purchase Orders ----
UNION ALL
SELECT 'PurchaseOrders', 'PO Headers',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       DOCUMENT_NUM,
       DOCUMENT_NUM,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL
WHERE STYLE_DISPLAY_NAME = 'Purchase Order' OR STYLE_DISPLAY_NAME IS NULL
UNION ALL
SELECT 'PurchaseOrders', 'PO Lines',
       l.TFM_SEQUENCE_ID, l.STG_SEQUENCE_ID, l.RUN_ID,
       l.INTERFACE_LINE_KEY,
       h.DOCUMENT_NUM,
       l.TFM_STATUS, l.ERROR_TEXT,
       REGEXP_SUBSTR(l.ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       l.RESULTS_UPDATED_DATE,
       CASE WHEN l.TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN l.TFM_STATUS = 'FAILED' AND l.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN l.TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PO_LINES_INT_TFM_TBL l
LEFT JOIN DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL h
    ON l.INTERFACE_HEADER_KEY = h.INTERFACE_HEADER_KEY
UNION ALL
SELECT 'PurchaseOrders', 'PO Line Locations',
       ll.TFM_SEQUENCE_ID, ll.STG_SEQUENCE_ID, ll.RUN_ID,
       ll.INTERFACE_LINE_LOCATION_KEY,
       h.DOCUMENT_NUM,
       ll.TFM_STATUS, ll.ERROR_TEXT,
       REGEXP_SUBSTR(ll.ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       ll.RESULTS_UPDATED_DATE,
       CASE WHEN ll.TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN ll.TFM_STATUS = 'FAILED' AND ll.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN ll.TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PO_LINE_LOCS_INT_TFM_TBL ll
LEFT JOIN DMT_OWNER.DMT_PO_LINES_INT_TFM_TBL l
    ON ll.INTERFACE_LINE_KEY = l.INTERFACE_LINE_KEY
LEFT JOIN DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL h
    ON l.INTERFACE_HEADER_KEY = h.INTERFACE_HEADER_KEY
UNION ALL
SELECT 'PurchaseOrders', 'PO Distributions',
       d.TFM_SEQUENCE_ID, d.STG_SEQUENCE_ID, d.RUN_ID,
       d.INTERFACE_DISTRIBUTION_KEY,
       h.DOCUMENT_NUM,
       d.TFM_STATUS, d.ERROR_TEXT,
       REGEXP_SUBSTR(d.ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       d.RESULTS_UPDATED_DATE,
       CASE WHEN d.TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN d.TFM_STATUS = 'FAILED' AND d.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN d.TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PO_DISTS_INT_TFM_TBL d
LEFT JOIN DMT_OWNER.DMT_PO_LINE_LOCS_INT_TFM_TBL ll
    ON d.INTERFACE_LINE_LOCATION_KEY = ll.INTERFACE_LINE_LOCATION_KEY
LEFT JOIN DMT_OWNER.DMT_PO_LINES_INT_TFM_TBL l
    ON ll.INTERFACE_LINE_KEY = l.INTERFACE_LINE_KEY
LEFT JOIN DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL h
    ON l.INTERFACE_HEADER_KEY = h.INTERFACE_HEADER_KEY
-- ---- Blanket POs ----
UNION ALL
SELECT 'BlanketPOs', 'Blanket PO Headers',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       DOCUMENT_NUM,
       DOCUMENT_NUM,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL
WHERE STYLE_DISPLAY_NAME = 'Blanket Purchase Agreement'
UNION ALL
SELECT 'BlanketPOs', 'Blanket PO Lines',
       l.TFM_SEQUENCE_ID, l.STG_SEQUENCE_ID, l.RUN_ID,
       l.INTERFACE_LINE_KEY,
       h.DOCUMENT_NUM,
       l.TFM_STATUS, l.ERROR_TEXT,
       REGEXP_SUBSTR(l.ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       l.RESULTS_UPDATED_DATE,
       CASE WHEN l.TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN l.TFM_STATUS = 'FAILED' AND l.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN l.TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PO_LINES_INT_TFM_TBL l
LEFT JOIN DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL h
    ON l.INTERFACE_HEADER_KEY = h.INTERFACE_HEADER_KEY
WHERE h.STYLE_DISPLAY_NAME = 'Blanket Purchase Agreement'
-- ---- Contracts ----
UNION ALL
SELECT 'Contracts', 'Contract Headers',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       DOCUMENT_NUM,
       DOCUMENT_NUM,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL
WHERE STYLE_DISPLAY_NAME = 'Contract Purchase Agreement'
-- ---- AP Invoices ----
UNION ALL
SELECT 'APInvoices', 'AP Invoice Headers',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       INVOICE_NUM,
       INVOICE_NUM,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_AP_INVOICES_INT_TFM_TBL
WHERE INVOICE_TYPE_LOOKUP_CODE NOT LIKE '%1099%' OR INVOICE_TYPE_LOOKUP_CODE IS NULL
UNION ALL
SELECT 'APInvoices', 'AP Invoice Lines',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       'Line ' || LINE_NUMBER || ': ' || DESCRIPTION,
       (SELECT MAX(h.INVOICE_NUM) FROM DMT_OWNER.DMT_AP_INVOICES_INT_TFM_TBL h WHERE h.INVOICE_ID = DMT_AP_INVOICE_LINES_INT_TFM_TBL.INVOICE_ID),
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_AP_INVOICE_LINES_INT_TFM_TBL
WHERE INVOICE_ID IN (SELECT INVOICE_ID FROM DMT_OWNER.DMT_AP_INVOICES_INT_TFM_TBL WHERE INVOICE_TYPE_LOOKUP_CODE NOT LIKE '%1099%' OR INVOICE_TYPE_LOOKUP_CODE IS NULL)
-- ---- 1099 Invoices ----
UNION ALL
SELECT '1099Invoices', '1099 Invoice Headers',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       INVOICE_NUM,
       INVOICE_NUM,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_AP_INVOICES_INT_TFM_TBL
WHERE INVOICE_TYPE_LOOKUP_CODE LIKE '%1099%'
UNION ALL
SELECT '1099Invoices', '1099 Invoice Lines',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       'Line ' || LINE_NUMBER || ': ' || DESCRIPTION,
       (SELECT MAX(h.INVOICE_NUM) FROM DMT_OWNER.DMT_AP_INVOICES_INT_TFM_TBL h WHERE h.INVOICE_ID = DMT_AP_INVOICE_LINES_INT_TFM_TBL.INVOICE_ID),
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_AP_INVOICE_LINES_INT_TFM_TBL
WHERE INVOICE_ID IN (SELECT INVOICE_ID FROM DMT_OWNER.DMT_AP_INVOICES_INT_TFM_TBL WHERE INVOICE_TYPE_LOOKUP_CODE LIKE '%1099%')
-- ---- Customers ----
UNION ALL
SELECT 'Customers', 'Parties',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       ORGANIZATION_NAME,
       PARTY_ORIG_SYSTEM_REFERENCE,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_HZ_PARTIES_TFM_TBL
UNION ALL
SELECT 'Customers', 'Locations',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       LOCATION_ORIG_SYSTEM_REFERENCE,
       LOCATION_ORIG_SYSTEM_REFERENCE,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_HZ_LOCATIONS_TFM_TBL
UNION ALL
SELECT 'Customers', 'Party Sites',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PARTY_SITE_NAME,
       PARTY_ORIG_SYSTEM_REFERENCE,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_HZ_PARTY_SITES_TFM_TBL
UNION ALL
SELECT 'Customers', 'Party Site Uses',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       SITE_USE_TYPE,
       PARTY_ORIG_SYSTEM_REFERENCE,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_HZ_PARTY_SITE_USES_TFM_TBL
UNION ALL
SELECT 'Customers', 'Accounts',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       ACCOUNT_NUMBER,
       ACCOUNT_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_HZ_ACCOUNTS_TFM_TBL
UNION ALL
SELECT 'Customers', 'Account Sites',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       CUST_SITE_ORIG_SYS_REF,
       ACCOUNT_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_HZ_ACCT_SITES_TFM_TBL
UNION ALL
SELECT 'Customers', 'Account Site Uses',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       SITE_USE_CODE,
       CUST_SITE_ORIG_SYS_REF,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_HZ_ACCT_SITE_USES_TFM_TBL
-- ---- AR Invoices ----
UNION ALL
SELECT 'ARInvoices', 'AR Lines',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       TRX_NUMBER || ' - ' || DESCRIPTION,
       TRX_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_RA_LINES_TFM_TBL
UNION ALL
SELECT 'ARInvoices', 'AR Distributions',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       ACCOUNT_CLASS || ' ' || SEGMENT1 || '.' || SEGMENT2 || '.' || SEGMENT3,
       ACCOUNT_CLASS,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_RA_DISTS_TFM_TBL
-- ---- GL ----
UNION ALL
SELECT 'GLBalances', 'GL Journals',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       -- DISPLAY_KEY: the (run-prefixed) journal name that reconciliation keys
       -- on, plus this line's account -- so the record identifies its journal
       -- (accounts repeat across journals; the journal name does not within a run).
       REFERENCE1 || ' - ' || SEGMENT1 || '.' || SEGMENT2 || '.' || SEGMENT3,
       -- LOOKUP_KEY: REFERENCE1 is the prefixed batch name written to Fusion and
       -- the key DMT_GL_RESULTS_PKG matches BIP results back to the TFM row on.
       REFERENCE1,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_GL_INTERFACE_TFM_TBL
UNION ALL
SELECT 'GLBudgets', 'GL Budget Balances',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       BUDGET_NAME || ' - ' || SEGMENT1 || '.' || SEGMENT2 || '.' || SEGMENT3,
       BUDGET_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_GL_BUDGET_INT_TFM_TBL
UNION ALL
SELECT 'PlanningBudgets', 'Planning Budget Lines',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       ENTITY || ' - ' || ACCOUNT || ' - ' || PERIOD,
       DATA_LOAD_DEFINITION_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PLAN_BUDGET_TFM_TBL
-- ---- Assets ----
UNION ALL
SELECT 'Assets', 'Asset Headers',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       ASSET_NUMBER,
       ASSET_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_FA_ASSET_HDR_TFM_TBL
UNION ALL
SELECT 'Assets', 'Asset Books',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       ASSET_NUMBER || ' - ' || BOOK_TYPE_CODE,
       ASSET_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_FA_ASSET_BOOK_TFM_TBL
UNION ALL
SELECT 'Assets', 'Asset Assignments',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       ASSET_NUMBER || ' - ' || UNITS_ASSIGNED,
       ASSET_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_FA_ASSET_ASSIGN_TFM_TBL
-- ---- Projects ----
UNION ALL
SELECT 'Projects', 'Projects',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PROJECT_NAME,
       PROJECT_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PJF_PROJECTS_TFM_TBL
UNION ALL
SELECT 'Projects', 'Project Tasks',
       t.TFM_SEQUENCE_ID, t.STG_SEQUENCE_ID, t.RUN_ID,
       t.TASK_NAME,
       t.PROJECT_NUMBER,
       t.TFM_STATUS, t.ERROR_TEXT,
       REGEXP_SUBSTR(t.ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       t.RESULTS_UPDATED_DATE,
       CASE WHEN t.TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN t.TFM_STATUS = 'FAILED' AND t.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN t.TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PJF_TASKS_TFM_TBL t
UNION ALL
SELECT 'Projects', 'Team Members',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PROJECT_NAME || ' - ' || TEAM_MEMBER_NAME,
       PROJECT_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PJF_TEAM_MEMBERS_TFM_TBL
UNION ALL
SELECT 'Projects', 'Transaction Controls',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PROJECT_NAME || ' - ' || EXPENDITURE_TYPE,
       PROJECT_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PJC_TXN_CONTROLS_TFM_TBL
UNION ALL
SELECT 'ProjectBudgets', 'Project Budget Lines',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PROJECT_NUMBER || ' - ' || TASK_NAME,
       PROJECT_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PRJ_BUDGET_TFM_TBL
-- ---- Expenditures ----
UNION ALL
SELECT 'Expenditures', 'Project Expenditures',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       ORIG_TRANSACTION_REFERENCE,
       ORIG_TRANSACTION_REFERENCE,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PJC_EXPENDITURES_TFM_TBL
-- ---- Billing Events ----
UNION ALL
SELECT 'BillingEvents', 'Billing Events',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       SOURCENAME || ' - ' || EVENT_DESC,
       SOURCENAME || ' - ' || EVENT_DESC,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PJB_BILL_EVENTS_TFM_TBL
-- ---- Grants ----
UNION ALL
SELECT 'Grants', 'Award Headers',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       AWARD_NUMBER,
       AWARD_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_GMS_AWD_HEADERS_TFM_TBL
-- ---- Requisitions ----
UNION ALL
SELECT 'Requisitions', 'Req Headers',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       REQUISITION_NUMBER,
       REQUISITION_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_POR_REQ_HEADERS_TFM_TBL
UNION ALL
SELECT 'Requisitions', 'Req Lines',
       l.TFM_SEQUENCE_ID, l.STG_SEQUENCE_ID, l.RUN_ID,
       l.INTERFACE_LINE_KEY,
       h.REQUISITION_NUMBER,
       l.TFM_STATUS, l.ERROR_TEXT,
       REGEXP_SUBSTR(l.ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       l.RESULTS_UPDATED_DATE,
       CASE WHEN l.TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN l.TFM_STATUS = 'FAILED' AND l.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN l.TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_POR_REQ_LINES_TFM_TBL l
LEFT JOIN DMT_OWNER.DMT_POR_REQ_HEADERS_TFM_TBL h
    ON l.INTERFACE_HEADER_KEY = h.INTERFACE_HEADER_KEY
UNION ALL
SELECT 'Requisitions', 'Req Distributions',
       d.TFM_SEQUENCE_ID, d.STG_SEQUENCE_ID, d.RUN_ID,
       d.INTERFACE_DISTRIBUTION_KEY,
       h.REQUISITION_NUMBER,
       d.TFM_STATUS, d.ERROR_TEXT,
       REGEXP_SUBSTR(d.ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       d.RESULTS_UPDATED_DATE,
       CASE WHEN d.TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN d.TFM_STATUS = 'FAILED' AND d.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN d.TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_POR_REQ_DISTS_TFM_TBL d
LEFT JOIN DMT_OWNER.DMT_POR_REQ_LINES_TFM_TBL l
    ON d.INTERFACE_LINE_KEY = l.INTERFACE_LINE_KEY
LEFT JOIN DMT_OWNER.DMT_POR_REQ_HEADERS_TFM_TBL h
    ON l.INTERFACE_HEADER_KEY = h.INTERFACE_HEADER_KEY
-- ---- MiscReceipts ----
UNION ALL
SELECT 'MiscReceipts', 'Receipt Headers',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       RECEIPT_NUM,
       RECEIPT_NUM,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_RCV_HEADERS_TFM_TBL
UNION ALL
SELECT 'MiscReceipts', 'Receipt Transactions',
       t.TFM_SEQUENCE_ID, t.STG_SEQUENCE_ID, t.RUN_ID,
       'Line ' || t.INTERFACE_LINE_NUM || ' - ' || t.ITEM_NUM,
       h.RECEIPT_NUM,
       t.TFM_STATUS, t.ERROR_TEXT,
       REGEXP_SUBSTR(t.ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       t.RESULTS_UPDATED_DATE,
       CASE WHEN t.TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN t.TFM_STATUS = 'FAILED' AND t.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN t.TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_RCV_TRANSACTIONS_TFM_TBL t
LEFT JOIN DMT_OWNER.DMT_RCV_HEADERS_TFM_TBL h
    ON t.HEADER_INTERFACE_NUM = h.HEADER_INTERFACE_NUM
-- ---- Workers ----
UNION ALL
SELECT 'Workers', 'Workers',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_WORKER_TFM_TBL
UNION ALL
SELECT 'Workers', 'Person Names',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       FIRST_NAME || ' ' || LAST_NAME,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PERSON_NAME_TFM_TBL
UNION ALL
SELECT 'Workers', 'Person Emails',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || EMAIL_ADDRESS,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PERSON_EMAIL_TFM_TBL
UNION ALL
SELECT 'Workers', 'Person Phones',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || PHONE_NUMBER,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PERSON_PHONE_TFM_TBL
UNION ALL
SELECT 'Workers', 'Person Addresses',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || ADDRESS_LINE_1,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PERSON_ADDR_TFM_TBL
UNION ALL
SELECT 'Workers', 'Person NIDs',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || NATIONAL_IDENTIFIER_NUMBER,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PERSON_NID_TFM_TBL
UNION ALL
SELECT 'Workers', 'Person Legislation',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || LEGISLATION_CODE,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PERSON_LEGISL_TFM_TBL
UNION ALL
SELECT 'Workers', 'Work Relationships',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || LEGAL_EMPLOYER_NAME,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_WORK_REL_TFM_TBL
-- ---- Assignments ----
UNION ALL
SELECT 'Assignments', 'Assignments',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || ASSIGNMENT_NUMBER,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_ASSIGNMENT_TFM_TBL
-- ---- Salaries ----
UNION ALL
SELECT 'Salaries', 'Salaries',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || SALARY_AMOUNT,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_SALARY_TFM_TBL
-- ---- Salary Bases ----
UNION ALL
SELECT 'SalaryBases', 'Salary Bases',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       SALARY_BASIS_NAME,
       SALARY_BASIS_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_SAL_BASIS_TFM_TBL
-- ---- Payroll Relationships ----
UNION ALL
SELECT 'PayrollRels', 'Payroll Relationships',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || PAYROLL_NAME,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PAY_REL_TFM_TBL
-- ---- Tax Cards ----
UNION ALL
SELECT 'TaxCards', 'Tax Cards',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || DIRECTIVE_CARD_NAME,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_TAX_CARD_TFM_TBL
UNION ALL
SELECT 'TaxCards', 'Tax Card Components',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || COMPONENT_NAME,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_TAX_CARD_COMP_TFM_TBL
-- ---- W2 Balances ----
UNION ALL
SELECT 'W2Balances', 'W2 Balances',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || PAYROLL_NAME,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_W2_BAL_TFM_TBL
UNION ALL
SELECT 'W2Balances', 'W2 Balance Details',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || BALANCE_NAME,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_W2_BAL_DTL_TFM_TBL
-- ---- Benefits ----
UNION ALL
SELECT 'BenParticipant', 'Participant Enrollment',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || PLAN_NAME,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_BEN_PARTIC_TFM_TBL
UNION ALL
SELECT 'BenDependent', 'Dependent Enrollment',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || DEPENDENT_PERSON_NUMBER,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_BEN_DEPEND_TFM_TBL
UNION ALL
SELECT 'BenBeneficiary', 'Beneficiary Enrollment',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || BENEFICIARY_PERSON_NUMBER,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_BEN_BENFY_TFM_TBL
-- ---- Absences ----
UNION ALL
SELECT 'Absences', 'Absences',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || ABSENCE_TYPE,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_ABSENCE_TFM_TBL
-- ---- Talent Profiles ----
UNION ALL
SELECT 'TalentProfiles', 'Talent Profiles',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || PROFILE_CODE,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_TALENT_PROF_TFM_TBL
UNION ALL
SELECT 'TalentProfiles', 'Profile Items',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || CONTENT_TYPE_NAME,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_TALENT_PROF_ITEM_TFM_TBL
-- ---- Performance Evaluations ----
UNION ALL
SELECT 'PerfEvaluations', 'Performance Evaluations',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || DOCUMENT_NAME,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PERF_EVAL_TFM_TBL
UNION ALL
SELECT 'PerfEvaluations', 'Performance Ratings',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERSON_NUMBER || ' - ' || SECTION_NAME,
       PERSON_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_PERF_EVAL_RATING_TFM_TBL
-- ---- Work Schedules ----
UNION ALL
SELECT 'WorkSchedules', 'Work Schedules',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       WORK_SCHEDULE_NAME,
       WORK_SCHEDULE_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_WORK_SCHED_TFM_TBL
UNION ALL
SELECT 'WorkSchedules', 'Schedule Details',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       WORK_SCHEDULE_NAME || ' - ' || SHIFT_NAME,
       WORK_SCHEDULE_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_WORK_SCHED_DTL_TFM_TBL
-- ---- Configuration ----
UNION ALL
SELECT 'GLCalendar', 'Calendar Periods',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       PERIOD_SET_NAME || ' - ' || PERIOD_NAME,
       PERIOD_SET_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_GL_CALENDAR_TFM_TBL
UNION ALL
SELECT 'ValueSets', 'Value Set Definitions',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       VALUE_SET_CODE,
       VALUE_SET_CODE,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_FND_VS_SET_TFM_TBL
UNION ALL
SELECT 'ValueSetValues', 'Value Set Values',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       VALUE_SET_CODE || ' - ' || VALUE,
       VALUE_SET_CODE,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_FND_VS_VALUE_TFM_TBL
UNION ALL
SELECT 'LookupTypes', 'Lookup Type Definitions',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       LOOKUP_TYPE,
       LOOKUP_TYPE,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_FND_LOOKUP_TYPE_TFM_TBL
UNION ALL
SELECT 'LookupValues', 'Lookup Values',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       LOOKUP_TYPE || ' - ' || LOOKUP_CODE,
       LOOKUP_TYPE,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_FND_LOOKUP_VALUE_TFM_TBL
UNION ALL
SELECT 'UOM', 'Units of Measure',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       UOM_CODE || ' - ' || UNIT_OF_MEASURE,
       UOM_CODE,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_INV_UOM_TFM_TBL
UNION ALL
SELECT 'PaymentTerms', 'Payment Term Headers',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       NAME,
       NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_AP_PAY_TERM_HDR_TFM_TBL
UNION ALL
SELECT 'PaymentTermLines', 'Payment Term Lines',
       l.TFM_SEQUENCE_ID, l.STG_SEQUENCE_ID, l.RUN_ID,
       h.NAME || ' - Line ' || l.SEQUENCE_NUM,
       h.NAME,
       l.TFM_STATUS, l.ERROR_TEXT,
       REGEXP_SUBSTR(l.ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       l.RESULTS_UPDATED_DATE,
       CASE WHEN l.TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN l.TFM_STATUS = 'FAILED' AND l.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN l.TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_AP_PAY_TERM_LINE_TFM_TBL l
LEFT JOIN DMT_OWNER.DMT_AP_PAY_TERM_HDR_TFM_TBL h
    ON l.SOURCE_GROUP_ID = h.SOURCE_GROUP_ID
UNION ALL
SELECT 'TaxRegimes', 'Tax Regime Definitions',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       TAX_REGIME_CODE || ' - ' || TAX_REGIME_NAME,
       TAX_REGIME_CODE,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_ZX_REGIME_TFM_TBL
UNION ALL
SELECT 'TaxRates', 'Tax Rate Definitions',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       TAX_RATE_CODE || ' - ' || TAX_RATE_NAME,
       TAX_REGIME_CODE,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_ZX_RATE_TFM_TBL
-- ---- Master Data ----
UNION ALL
SELECT 'Items', 'Item Master',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       ITEM_NUMBER,
       ITEM_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_EGP_ITEM_TFM_TBL
UNION ALL
SELECT 'ItemCategories', 'Item Categories',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       ITEM_NUMBER || ' - ' || CATEGORY_SET_NAME,
       ITEM_NUMBER,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_EGP_ITEM_CAT_TFM_TBL
UNION ALL
SELECT 'Banks', 'Bank Definitions',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       BANK_NAME || ' - ' || BANK_NUMBER,
       BANK_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_CE_BANK_TFM_TBL
UNION ALL
SELECT 'BankBranches', 'Bank Branches',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       BANK_NAME || ' - ' || BRANCH_NAME,
       BANK_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_CE_BRANCH_TFM_TBL
UNION ALL
SELECT 'BankAccounts', 'Bank Accounts',
       TFM_SEQUENCE_ID, STG_SEQUENCE_ID, RUN_ID,
       BANK_NAME || ' - ' || ACCOUNT_NAME,
       BANK_NAME,
       TFM_STATUS, ERROR_TEXT,
       REGEXP_SUBSTR(ERROR_TEXT, '^\[([^\]]+)\]', 1, 1, NULL, 1),
       RESULTS_UPDATED_DATE,
       CASE WHEN TFM_STATUS = 'LOADED' THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NOT NULL THEN 'CONFIRMED' WHEN TFM_STATUS = 'FAILED' THEN 'UNRECONCILED' ELSE 'IN_PROGRESS' END
FROM DMT_OWNER.DMT_CE_BANK_ACCT_TFM_TBL
) q;
