-- DMT_PO_IMP_RPT_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_PO_IMP_RPT_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_STATUS", "START_DATE", "END_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "INTERFACE_HEADER_KEY", "DOCUMENT_NUM", "DOCUMENT_TYPE_CODE", "STYLE_DISPLAY_NAME", "VENDOR_NAME", "VENDOR_NUM", "VENDOR_SITE_CODE", "PRC_BU_NAME", "CURRENCY_CODE", "STG_STATUS", "TFM_STATUS", "EFFECTIVE_STATUS", "RECONCILIATION_STATUS", "STG_ERRORS", "TFM_ERRORS", "ALL_ERRORS", "FUSION_PO_HEADER_ID", "FUSION_DOCUMENT_NUM", "RESULTS_UPDATED_DATE", "STAGE_DATE", "SOURCE_RECORD_ID", "LINE_COUNT", "LINES_LOADED", "LINES_FAILED", "LOC_COUNT", "DIST_COUNT")  AS 
  SELECT
    t.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.STATUS                                        AS RUN_STATUS,
    m.START_DATE,
    m.END_DATE,
    m.PREFIX,
    -- Identification (from STG -- always present)
    s.STG_SEQUENCE_ID,
    t.TFM_SEQUENCE_ID,
    s.INTERFACE_HEADER_KEY,
    s.DOCUMENT_NUM,
    s.DOCUMENT_TYPE_CODE,
    s.STYLE_DISPLAY_NAME,
    s.VENDOR_NAME,
    s.VENDOR_NUM,
    s.VENDOR_SITE_CODE,
    s.PRC_BU_NAME,
    s.CURRENCY_CODE,
    -- Raw status from each layer
    s.STATUS                                        AS STG_STATUS,
    t.STATUS                                        AS TFM_STATUS,
    -- Effective status: worst wins
    CASE
        WHEN 'FAILED' IN (s.STATUS, NVL(t.STATUS, 'X'))  THEN 'FAILED'
        WHEN t.STATUS = 'GENERATED'                        THEN 'GENERATED'
        WHEN t.STATUS IS NOT NULL                          THEN t.STATUS
        ELSE s.STATUS
    END                                             AS EFFECTIVE_STATUS,
    -- Reconciliation status (badge color)
    CASE
        WHEN NVL(t.STATUS, s.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(t.STATUS, s.STATUS) = 'FAILED' AND COALESCE(t.ERROR_TEXT, s.ERROR_TEXT) IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(t.STATUS, s.STATUS) = 'FAILED' AND COALESCE(t.ERROR_TEXT, s.ERROR_TEXT) IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                             AS RECONCILIATION_STATUS,
    -- Error text from each layer
    DBMS_LOB.SUBSTR(s.ERROR_TEXT, 4000, 1)         AS STG_ERRORS,
    DBMS_LOB.SUBSTR(t.ERROR_TEXT, 4000, 1)         AS TFM_ERRORS,
    -- Combined errors
    CASE
        WHEN s.ERROR_TEXT IS NOT NULL AND t.ERROR_TEXT IS NOT NULL
        THEN DBMS_LOB.SUBSTR(s.ERROR_TEXT, 2000, 1) || ' | ' ||
             DBMS_LOB.SUBSTR(t.ERROR_TEXT, 2000, 1)
        ELSE DBMS_LOB.SUBSTR(COALESCE(s.ERROR_TEXT, t.ERROR_TEXT), 4000, 1)
    END                                             AS ALL_ERRORS,
    -- Fusion outcome (NULL until BIP reconciliation completes)
    t.FUSION_PO_HEADER_ID,
    t.FUSION_DOCUMENT_NUM,
    t.RESULTS_UPDATED_DATE,
    s.STAGE_DATE,
    s.SOURCE_ID                                     AS SOURCE_RECORD_ID,
    -- Rollup counts for child objects (NULL pre-pipeline)
    (SELECT COUNT(*)
     FROM   DMT_OWNER.DMT_PO_LINES_INT_TFM_TBL lt
     WHERE  lt.INTEGRATION_ID      = t.INTEGRATION_ID
     AND    lt.INTERFACE_HEADER_KEY = t.INTERFACE_HEADER_KEY)  AS LINE_COUNT,
    (SELECT COUNT(*)
     FROM   DMT_OWNER.DMT_PO_LINES_INT_TFM_TBL lt
     WHERE  lt.INTEGRATION_ID      = t.INTEGRATION_ID
     AND    lt.INTERFACE_HEADER_KEY = t.INTERFACE_HEADER_KEY
     AND    lt.STATUS               = 'LOADED')                AS LINES_LOADED,
    (SELECT COUNT(*)
     FROM   DMT_OWNER.DMT_PO_LINES_INT_TFM_TBL lt
     WHERE  lt.INTEGRATION_ID      = t.INTEGRATION_ID
     AND    lt.INTERFACE_HEADER_KEY = t.INTERFACE_HEADER_KEY
     AND    lt.STATUS               = 'FAILED')                AS LINES_FAILED,
    (SELECT COUNT(*)
     FROM   DMT_OWNER.DMT_PO_LINE_LOCS_INT_TFM_TBL llt
     JOIN   DMT_OWNER.DMT_PO_LINES_INT_TFM_TBL lt2
            ON lt2.INTERFACE_LINE_KEY = llt.INTERFACE_LINE_KEY
            AND lt2.INTEGRATION_ID    = llt.INTEGRATION_ID
     WHERE  llt.INTEGRATION_ID       = t.INTEGRATION_ID
     AND    lt2.INTERFACE_HEADER_KEY  = t.INTERFACE_HEADER_KEY) AS LOC_COUNT,
    (SELECT COUNT(*)
     FROM   DMT_OWNER.DMT_PO_DISTS_INT_TFM_TBL dt
     JOIN   DMT_OWNER.DMT_PO_LINE_LOCS_INT_TFM_TBL llt2
            ON llt2.INTERFACE_LINE_LOCATION_KEY = dt.INTERFACE_LINE_LOCATION_KEY
            AND llt2.INTEGRATION_ID             = dt.INTEGRATION_ID
     JOIN   DMT_OWNER.DMT_PO_LINES_INT_TFM_TBL lt3
            ON lt3.INTERFACE_LINE_KEY = llt2.INTERFACE_LINE_KEY
            AND lt3.INTEGRATION_ID    = llt2.INTEGRATION_ID
     WHERE  dt.INTEGRATION_ID        = t.INTEGRATION_ID
     AND    lt3.INTERFACE_HEADER_KEY  = t.INTERFACE_HEADER_KEY) AS DIST_COUNT
FROM
    DMT_OWNER.DMT_PO_HEADERS_INT_STG_TBL        s
    LEFT JOIN DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL t
        ON  t.STG_SEQUENCE_ID  = s.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON  m.INTEGRATION_ID   = t.INTEGRATION_ID
ORDER BY
    t.INTEGRATION_ID DESC NULLS LAST,
    s.DOCUMENT_NUM;
