-- DMT_V_PRJ_BUDGET_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_PRJ_BUDGET_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "PROJECT_NUMBER", "FINANCIAL_PLAN_TYPE", "AWARD_NUMBER", "PROJECT_NAME", "TASK_NAME", "TASK_NUMBER", "PLAN_VERSION_NAME", "PLAN_VERSION_DESCRIPTION", "PLAN_VERSION_STATUS", "RESOURCE_NAME", "PERIOD_NAME", "PLANNING_CURRENCY", "TOTAL_QUANTITY", "TOTAL_TC_RAW_COST", "TOTAL_TC_REVENUE", "SRC_BUDGET_LINE_REFERENCE", "FUNDING_SOURCE_NUMBER", "FUNDING_SOURCE_NAME", "PC_RAW_COST", "PC_REVENUE", "PFC_RAW_COST", "PFC_REVENUE", "TOTAL_TC_BRDND_COST", "PC_BRDND_COST", "PFC_BRDND_COST", "LINE_TYPE", "PLANNING_START_DATE", "PLANNING_END_DATE", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "ATTRIBUTE16", "ATTRIBUTE17", "ATTRIBUTE18", "ATTRIBUTE19", "ATTRIBUTE20", "ATTRIBUTE21", "ATTRIBUTE22", "ATTRIBUTE23", "ATTRIBUTE24", "ATTRIBUTE25", "ATTRIBUTE26", "ATTRIBUTE27", "ATTRIBUTE28", "ATTRIBUTE29", "ATTRIBUTE30", "PLAN_VERSION_NUMBER", "PROCESSING_MODE", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.STATUS, stg.STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.PROJECT_NUMBER                                      AS PROJECT_NUMBER,
    stg.FINANCIAL_PLAN_TYPE                                 AS FINANCIAL_PLAN_TYPE,
    stg.AWARD_NUMBER,
    stg.PROJECT_NAME,
    stg.TASK_NAME,
    stg.TASK_NUMBER,
    stg.PLAN_VERSION_NAME,
    stg.PLAN_VERSION_DESCRIPTION,
    stg.PLAN_VERSION_STATUS,
    stg.RESOURCE_NAME,
    stg.PERIOD_NAME,
    stg.PLANNING_CURRENCY,
    stg.TOTAL_QUANTITY,
    stg.TOTAL_TC_RAW_COST,
    stg.TOTAL_TC_REVENUE,
    stg.SRC_BUDGET_LINE_REFERENCE,
    stg.FUNDING_SOURCE_NUMBER,
    stg.FUNDING_SOURCE_NAME,
    stg.PC_RAW_COST,
    stg.PC_REVENUE,
    stg.PFC_RAW_COST,
    stg.PFC_REVENUE,
    stg.TOTAL_TC_BRDND_COST,
    stg.PC_BRDND_COST,
    stg.PFC_BRDND_COST,
    stg.LINE_TYPE,
    stg.PLANNING_START_DATE,
    stg.PLANNING_END_DATE,
    stg.ATTRIBUTE_CATEGORY,
    stg.ATTRIBUTE1,
    stg.ATTRIBUTE2,
    stg.ATTRIBUTE3,
    stg.ATTRIBUTE4,
    stg.ATTRIBUTE5,
    stg.ATTRIBUTE6,
    stg.ATTRIBUTE7,
    stg.ATTRIBUTE8,
    stg.ATTRIBUTE9,
    stg.ATTRIBUTE10,
    stg.ATTRIBUTE11,
    stg.ATTRIBUTE12,
    stg.ATTRIBUTE13,
    stg.ATTRIBUTE14,
    stg.ATTRIBUTE15,
    stg.ATTRIBUTE16,
    stg.ATTRIBUTE17,
    stg.ATTRIBUTE18,
    stg.ATTRIBUTE19,
    stg.ATTRIBUTE20,
    stg.ATTRIBUTE21,
    stg.ATTRIBUTE22,
    stg.ATTRIBUTE23,
    stg.ATTRIBUTE24,
    stg.ATTRIBUTE25,
    stg.ATTRIBUTE26,
    stg.ATTRIBUTE27,
    stg.ATTRIBUTE28,
    stg.ATTRIBUTE29,
    stg.ATTRIBUTE30,
    stg.PLAN_VERSION_NUMBER,
    stg.PROCESSING_MODE,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    cm.PREFIX,
    stg.SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_PRJ_BUDGET_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_PRJ_BUDGET_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
