-- DMT_V_PERSON_LEGISL_DETAIL
CREATE OR REPLACE EDITIONABLE VIEW "DMT_V_PERSON_LEGISL_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "PERSON_NUMBER", "LEGISLATION_CODE", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "SEX", "MARITAL_STATUS", "HIGHEST_EDUCATION_LEVEL", "ETHNICITY", "VETERAN_SELF_IDENT_FLAG", "TOBACCO_USER", "DISABLED_FLAG", "PER_INFORMATION1", "PER_INFORMATION2", "PER_INFORMATION3", "PER_INFORMATION4", "PER_INFORMATION5", "PER_INFORMATION6", "PER_INFORMATION7", "PER_INFORMATION8", "PER_INFORMATION9", "PER_INFORMATION10", "PER_INFORMATION11", "PER_INFORMATION12", "PER_INFORMATION13", "PER_INFORMATION14", "PER_INFORMATION15", "PER_INFORMATION16", "PER_INFORMATION17", "PER_INFORMATION18", "PER_INFORMATION19", "PER_INFORMATION20", "PER_INFORMATION21", "PER_INFORMATION22", "PER_INFORMATION23", "PER_INFORMATION24", "PER_INFORMATION25", "PER_INFORMATION26", "PER_INFORMATION27", "PER_INFORMATION28", "PER_INFORMATION29", "PER_INFORMATION30", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.PERSON_NUMBER                                       AS PERSON_NUMBER,
    stg.LEGISLATION_CODE                                    AS LEGISLATION_CODE,
    stg.EFFECTIVE_START_DATE,
    stg.EFFECTIVE_END_DATE,
    stg.SEX,
    stg.MARITAL_STATUS,
    stg.HIGHEST_EDUCATION_LEVEL,
    stg.ETHNICITY,
    stg.VETERAN_SELF_IDENT_FLAG,
    stg.TOBACCO_USER,
    stg.DISABLED_FLAG,
    stg.PER_INFORMATION1,
    stg.PER_INFORMATION2,
    stg.PER_INFORMATION3,
    stg.PER_INFORMATION4,
    stg.PER_INFORMATION5,
    stg.PER_INFORMATION6,
    stg.PER_INFORMATION7,
    stg.PER_INFORMATION8,
    stg.PER_INFORMATION9,
    stg.PER_INFORMATION10,
    stg.PER_INFORMATION11,
    stg.PER_INFORMATION12,
    stg.PER_INFORMATION13,
    stg.PER_INFORMATION14,
    stg.PER_INFORMATION15,
    stg.PER_INFORMATION16,
    stg.PER_INFORMATION17,
    stg.PER_INFORMATION18,
    stg.PER_INFORMATION19,
    stg.PER_INFORMATION20,
    stg.PER_INFORMATION21,
    stg.PER_INFORMATION22,
    stg.PER_INFORMATION23,
    stg.PER_INFORMATION24,
    stg.PER_INFORMATION25,
    stg.PER_INFORMATION26,
    stg.PER_INFORMATION27,
    stg.PER_INFORMATION28,
    stg.PER_INFORMATION29,
    stg.PER_INFORMATION30,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    cm.PREFIX,
    stg.SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_PERSON_LEGISL_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_PERSON_LEGISL_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
