-- DMT_ESS_JOBS_MONITOR_V
CREATE OR REPLACE EDITIONABLE VIEW "DMT_ESS_JOBS_MONITOR_V" ("ESS_JOB_ID", "INTEGRATION_ID", "REQUEST_ID", "PARENT_REQUEST_ID", "JOB_DEFINITION", "JOB_SHORT_NAME", "STATE", "STATE_TEXT", "SUBMITTER", "SUBMIT_TIME", "START_TIME", "END_TIME", "DURATION_MINUTES", "CEMLI_CODE", "DEPTH_LEVEL", "CREATED_DATE")  AS 
  SELECT
    ej.ESS_JOB_ID,
    ej.INTEGRATION_ID,
    ej.REQUEST_ID,
    ej.PARENT_REQUEST_ID,
    ej.JOB_DEFINITION,
    ej.JOB_SHORT_NAME,
    ej.STATE,
    ej.STATE_TEXT,
    ej.SUBMITTER,
    ej.SUBMIT_TIME,
    ej.START_TIME,
    ej.END_TIME,
    TRUNC((ej.END_TIME - ej.START_TIME) * 24 * 60) AS DURATION_MINUTES,
    ej.CEMLI_CODE,
    ej.DEPTH_LEVEL,
    ej.CREATED_DATE
FROM
    DMT_OWNER.DMT_ESS_JOB_TBL ej
ORDER BY
    ej.REQUEST_ID DESC,
    ej.DEPTH_LEVEL;
