-- DMT_V_WORKER_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_WORKER_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "PERSON_NUMBER", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "DATE_OF_BIRTH", "ACTION_CODE", "START_DATE", "LEGAL_ENTITY_NAME", "CATEGORY_CODE", "PROJECTED_TERMINATION_DATE", "BLOOD_TYPE", "CORRESPONDENCE_LANGUAGE", "TOWN_OF_BIRTH", "REGION_OF_BIRTH", "COUNTRY_OF_BIRTH", "DATE_OF_DEATH", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.STATUS, stg.STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.PERSON_NUMBER                                       AS PERSON_NUMBER,
    stg.EFFECTIVE_START_DATE,
    stg.EFFECTIVE_END_DATE,
    stg.DATE_OF_BIRTH,
    stg.ACTION_CODE,
    stg.START_DATE,
    stg.LEGAL_ENTITY_NAME,
    stg.CATEGORY_CODE,
    stg.PROJECTED_TERMINATION_DATE,
    stg.BLOOD_TYPE,
    stg.CORRESPONDENCE_LANGUAGE,
    stg.TOWN_OF_BIRTH,
    stg.REGION_OF_BIRTH,
    stg.COUNTRY_OF_BIRTH,
    stg.DATE_OF_DEATH,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    cm.PREFIX,
    stg.SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_WORKER_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_WORKER_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
