-- DMT_ABSENCES_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_ABSENCES_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "PERSON_NUMBER", "ABSENCE_TYPE", "ABSENCE_START_DATE", "ABSENCE_END_DATE", "DURATION_IN_DAYS", "ABSENCE_REASON", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    a.STG_SEQUENCE_ID,
    at.TFM_SEQUENCE_ID,
    a.SOURCE_ID,
    at.PERSON_NUMBER,
    NVL(at.ABSENCE_TYPE, a.ABSENCE_TYPE) AS ABSENCE_TYPE,
    at.START_DATE AS ABSENCE_START_DATE,
    at.END_DATE AS ABSENCE_END_DATE,
    at.DURATION AS DURATION_IN_DAYS,
    NVL(at.ABSENCE_REASON, a.ABSENCE_REASON) AS ABSENCE_REASON,
    a.STATUS AS STG_STATUS,
    at.STATUS AS TFM_STATUS,
    NVL(at.STATUS, a.STATUS) AS OVERALL_STATUS,
    NVL(at.STATUS, a.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(at.ERROR_TEXT, a.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    a.STAGE_DATE,
    at.RESULTS_UPDATED_DATE,
    NULL AS FUSION_LINK,
    a.SCENARIO_ID
FROM
    DMT_OWNER.DMT_ABSENCE_STG_TBL a
    LEFT JOIN DMT_OWNER.DMT_ABSENCE_TFM_TBL at
        ON at.STG_SEQUENCE_ID = a.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = at.INTEGRATION_ID
ORDER BY
    a.STAGE_DATE DESC,
    a.STG_SEQUENCE_ID DESC;
