-- DMT_OTC_CUSTOMERS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_OTC_CUSTOMERS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "ACCOUNT_NAME", "ACCOUNT_NUMBER", "PARTY_REFERENCE", "CUSTOMER_REFERENCE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "FUSION_CUST_ACCOUNT_ID", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    c.STG_SEQUENCE_ID,
    ct.TFM_SEQUENCE_ID,
    c.SOURCE_ID,
    NVL(ct.ACCOUNT_NAME, c.ACCOUNT_NAME) AS ACCOUNT_NAME,
    NVL(ct.ACCOUNT_NUMBER, c.ACCOUNT_NUMBER) AS ACCOUNT_NUMBER,
    -- PARTY_NAME does not exist on HZ_ACCOUNTS TFM; lives on HZ_PARTIES TFM
    ct.PARTY_ORIG_SYSTEM_REFERENCE AS PARTY_REFERENCE,
    -- PARTY_SITE_NAME does not exist on HZ_ACCOUNTS TFM; lives on HZ_PARTY_SITES TFM
    ct.CUST_ORIG_SYSTEM_REFERENCE AS CUSTOMER_REFERENCE,
    c.STATUS AS STG_STATUS,
    ct.STATUS AS TFM_STATUS,
    NVL(ct.STATUS, c.STATUS) AS OVERALL_STATUS,
    NVL(ct.STATUS, c.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(ct.ERROR_TEXT, c.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ct.FUSION_CUST_ACCOUNT_ID,
    c.STAGE_DATE,
    ct.RESULTS_UPDATED_DATE,
    DMT_UTIL_PKG.GET_DEEP_LINK('Customers', ct.FUSION_CUST_ACCOUNT_ID) AS FUSION_LINK,
    c.SCENARIO_ID
FROM
    DMT_OWNER.DMT_HZ_ACCOUNTS_STG_TBL c
    LEFT JOIN DMT_OWNER.DMT_HZ_ACCOUNTS_TFM_TBL ct
        ON ct.STG_SEQUENCE_ID = c.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ct.INTEGRATION_ID
ORDER BY
    c.STAGE_DATE DESC,
    c.STG_SEQUENCE_ID DESC;
