-- DMT_SALARIES_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_SALARIES_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "PERSON_NUMBER", "ASSIGNMENT_NUMBER", "SALARY_AMOUNT", "SALARY_BASIS_NAME", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT m.INTEGRATION_ID, m.ORCHESTRATION_CODE, m.START_DATE AS RUN_DATE, m.PREFIX,
    s.STG_SEQUENCE_ID, st.TFM_SEQUENCE_ID, s.SOURCE_ID,
    st.PERSON_NUMBER, st.ASSIGNMENT_NUMBER,
    NVL(st.SALARY_AMOUNT, s.SALARY_AMOUNT) AS SALARY_AMOUNT,
    NVL(st.SALARY_BASIS_NAME, s.SALARY_BASIS_NAME) AS SALARY_BASIS_NAME,
    s.STATUS AS STG_STATUS,
    st.STATUS AS TFM_STATUS,
    NVL(st.STATUS, s.STATUS) AS OVERALL_STATUS,
    NVL(st.STATUS, s.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(st.ERROR_TEXT, s.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    s.STAGE_DATE, st.RESULTS_UPDATED_DATE, NULL AS FUSION_LINK, s.SCENARIO_ID
FROM DMT_OWNER.DMT_SALARY_STG_TBL s
    LEFT JOIN DMT_OWNER.DMT_SALARY_TFM_TBL st ON st.STG_SEQUENCE_ID = s.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m ON m.INTEGRATION_ID = st.INTEGRATION_ID
ORDER BY s.STAGE_DATE DESC, s.STG_SEQUENCE_ID DESC;
