-- DMT_V_SALARY_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_SALARY_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "PERSON_NUMBER", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "ASSIGNMENT_NUMBER", "SALARY_AMOUNT", "SALARY_BASIS_NAME", "ANNUAL_SALARY", "ANNUAL_FULL_TIME_SALARY", "CURRENCY_CODE", "ACTION_CODE", "FREQUENCY_NAME", "NEXT_SAL_REVIEW_DATE", "DATE_FROM", "DATE_TO", "SALARY_APPROVED", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.STATUS, stg.STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.PERSON_NUMBER                                       AS PERSON_NUMBER,
    stg.EFFECTIVE_START_DATE,
    stg.EFFECTIVE_END_DATE,
    stg.ASSIGNMENT_NUMBER,
    stg.SALARY_AMOUNT,
    stg.SALARY_BASIS_NAME,
    stg.ANNUAL_SALARY,
    stg.ANNUAL_FULL_TIME_SALARY,
    stg.CURRENCY_CODE,
    stg.ACTION_CODE,
    stg.FREQUENCY_NAME,
    stg.NEXT_SAL_REVIEW_DATE,
    stg.DATE_FROM,
    stg.DATE_TO,
    stg.SALARY_APPROVED,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    cm.PREFIX,
    stg.SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_SALARY_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_SALARY_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
