-- DMT_V_GL_JOURNAL_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_GL_JOURNAL_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "LEDGER_NAME", "USER_JE_CATEGORY_NAME", "JOURNAL_STATUS", "ACCOUNTING_DATE", "CURRENCY_CODE", "DATE_CREATED", "CREATED_BY", "ACTUAL_FLAG", "USER_JE_SOURCE_NAME", "CURRENCY_CONVERSION_DATE", "USER_CURRENCY_CONVERSION_TYPE", "CURRENCY_CONVERSION_RATE", "SEGMENT1", "SEGMENT2", "SEGMENT3", "SEGMENT4", "SEGMENT5", "SEGMENT6", "SEGMENT7", "SEGMENT8", "SEGMENT9", "SEGMENT10", "SEGMENT11", "SEGMENT12", "SEGMENT13", "SEGMENT14", "SEGMENT15", "SEGMENT16", "SEGMENT17", "SEGMENT18", "SEGMENT19", "SEGMENT20", "SEGMENT21", "SEGMENT22", "SEGMENT23", "SEGMENT24", "SEGMENT25", "SEGMENT26", "SEGMENT27", "SEGMENT28", "SEGMENT29", "SEGMENT30", "ENTERED_DR", "ENTERED_CR", "ACCOUNTED_DR", "ACCOUNTED_CR", "REFERENCE1", "REFERENCE2", "REFERENCE4", "REFERENCE5", "REFERENCE6", "REFERENCE7", "REFERENCE8", "REFERENCE10", "STAT_AMOUNT", "GROUP_ID", "PERIOD_NAME", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "ATTRIBUTE16", "ATTRIBUTE17", "ATTRIBUTE18", "ATTRIBUTE19", "ATTRIBUTE20", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    -- 1. Run status
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                        AS RUN_STATUS,
    -- 2. Error text
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    -- 3. Human identifiers
    stg.LEDGER_NAME                                         AS LEDGER_NAME,
    stg.USER_JE_CATEGORY_NAME                               AS USER_JE_CATEGORY_NAME,
    -- 4. All remaining STG business columns
    stg.JOURNAL_STATUS,
    stg.ACCOUNTING_DATE,
    stg.CURRENCY_CODE,
    stg.DATE_CREATED,
    stg.CREATED_BY,
    stg.ACTUAL_FLAG,
    stg.USER_JE_SOURCE_NAME,
    stg.CURRENCY_CONVERSION_DATE,
    stg.USER_CURRENCY_CONVERSION_TYPE,
    stg.CURRENCY_CONVERSION_RATE,
    stg.SEGMENT1,
    stg.SEGMENT2,
    stg.SEGMENT3,
    stg.SEGMENT4,
    stg.SEGMENT5,
    stg.SEGMENT6,
    stg.SEGMENT7,
    stg.SEGMENT8,
    stg.SEGMENT9,
    stg.SEGMENT10,
    stg.SEGMENT11,
    stg.SEGMENT12,
    stg.SEGMENT13,
    stg.SEGMENT14,
    stg.SEGMENT15,
    stg.SEGMENT16,
    stg.SEGMENT17,
    stg.SEGMENT18,
    stg.SEGMENT19,
    stg.SEGMENT20,
    stg.SEGMENT21,
    stg.SEGMENT22,
    stg.SEGMENT23,
    stg.SEGMENT24,
    stg.SEGMENT25,
    stg.SEGMENT26,
    stg.SEGMENT27,
    stg.SEGMENT28,
    stg.SEGMENT29,
    stg.SEGMENT30,
    stg.ENTERED_DR,
    stg.ENTERED_CR,
    stg.ACCOUNTED_DR,
    stg.ACCOUNTED_CR,
    stg.REFERENCE1,
    stg.REFERENCE2,
    stg.REFERENCE4,
    stg.REFERENCE5,
    stg.REFERENCE6,
    stg.REFERENCE7,
    stg.REFERENCE8,
    stg.REFERENCE10,
    stg.STAT_AMOUNT,
    stg.GROUP_ID,
    stg.PERIOD_NAME,
    stg.ATTRIBUTE_CATEGORY,
    stg.ATTRIBUTE1,
    stg.ATTRIBUTE2,
    stg.ATTRIBUTE3,
    stg.ATTRIBUTE4,
    stg.ATTRIBUTE5,
    stg.ATTRIBUTE6,
    stg.ATTRIBUTE7,
    stg.ATTRIBUTE8,
    stg.ATTRIBUTE9,
    stg.ATTRIBUTE10,
    stg.ATTRIBUTE11,
    stg.ATTRIBUTE12,
    stg.ATTRIBUTE13,
    stg.ATTRIBUTE14,
    stg.ATTRIBUTE15,
    stg.ATTRIBUTE16,
    stg.ATTRIBUTE17,
    stg.ATTRIBUTE18,
    stg.ATTRIBUTE19,
    stg.ATTRIBUTE20,
    stg.SOURCE_ID,
    -- 5. STG_SEQUENCE_ID
    stg.STG_SEQUENCE_ID,
    -- 6. RUN_ID
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    -- 7. PREFIX (from PIPELINE_RUN)
    cm.PREFIX,
    -- 8. SCENARIO_ID
    stg.SCENARIO_ID,
    -- 9. STAGE_DATE
    stg.STAGE_DATE,
    -- 10. LAST_UPDATED_DATE
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_GL_INTERFACE_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_GL_INTERFACE_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
