-- DMT_ASSIGNMENTS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_ASSIGNMENTS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "ASSIGNMENT_NUMBER", "PERSON_NUMBER", "POSITION_NAME", "JOB_NAME", "ASSIGNMENT_TYPE", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    a.STG_SEQUENCE_ID,
    at.TFM_SEQUENCE_ID,
    a.SOURCE_ID,
    at.ASSIGNMENT_NUMBER,
    at.PERSON_NUMBER,
    at.POSITION_CODE AS POSITION_NAME,
    at.JOB_CODE AS JOB_NAME,
    -- ASSIGNMENT_TYPE does not exist on ASSIGNMENT TFM
    at.ASSIGNMENT_CATEGORY AS ASSIGNMENT_TYPE,
    at.EFFECTIVE_START_DATE,
    at.EFFECTIVE_END_DATE,
    a.STATUS AS STG_STATUS,
    at.STATUS AS TFM_STATUS,
    NVL(at.STATUS, a.STATUS) AS OVERALL_STATUS,
    NVL(at.STATUS, a.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(at.ERROR_TEXT, a.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    a.STAGE_DATE,
    at.RESULTS_UPDATED_DATE,
    NULL AS FUSION_LINK,
    a.SCENARIO_ID
FROM
    DMT_OWNER.DMT_ASSIGNMENT_STG_TBL a
    LEFT JOIN DMT_OWNER.DMT_ASSIGNMENT_TFM_TBL at
        ON at.STG_SEQUENCE_ID = a.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = at.INTEGRATION_ID
ORDER BY
    a.STAGE_DATE DESC,
    a.STG_SEQUENCE_ID DESC;
