-- DMT_V_PO_HEADERS_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_PO_HEADERS_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "DOCUMENT_NUM", "VENDOR_NAME", "INTERFACE_HEADER_KEY", "ACTION", "BATCH_ID", "INTERFACE_SOURCE_CODE", "APPROVAL_ACTION", "DOCUMENT_TYPE_CODE", "STYLE_DISPLAY_NAME", "PRC_BU_NAME", "REQ_BU_NAME", "SOLDTO_LE_NAME", "BILLTO_BU_NAME", "AGENT_NAME", "CURRENCY_CODE", "RATE", "RATE_TYPE", "RATE_DATE", "COMMENTS", "BILL_TO_LOCATION", "SHIP_TO_LOCATION", "VENDOR_NUM", "VENDOR_SITE_CODE", "VENDOR_CONTACT", "VENDOR_DOC_NUM", "FOB", "FREIGHT_CARRIER", "FREIGHT_TERMS", "PAY_ON_CODE", "PAYMENT_TERMS", "ORIGINATOR_ROLE", "CHANGE_ORDER_DESC", "ACCEPTANCE_REQUIRED_FLAG", "ACCEPTANCE_WITHIN_DAYS", "SUPPLIER_NOTIF_METHOD", "FAX", "EMAIL_ADDRESS", "CONFIRMING_ORDER_FLAG", "NOTE_TO_VENDOR", "NOTE_TO_RECEIVER", "DEFAULT_TAXATION_COUNTRY", "TAX_DOCUMENT_SUBTYPE", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "ATTRIBUTE16", "ATTRIBUTE17", "ATTRIBUTE18", "ATTRIBUTE19", "ATTRIBUTE20", "ATTRIBUTE_DATE1", "ATTRIBUTE_DATE2", "ATTRIBUTE_DATE3", "ATTRIBUTE_DATE4", "ATTRIBUTE_DATE5", "ATTRIBUTE_DATE6", "ATTRIBUTE_DATE7", "ATTRIBUTE_DATE8", "ATTRIBUTE_DATE9", "ATTRIBUTE_DATE10", "ATTRIBUTE_NUMBER1", "ATTRIBUTE_NUMBER2", "ATTRIBUTE_NUMBER3", "ATTRIBUTE_NUMBER4", "ATTRIBUTE_NUMBER5", "ATTRIBUTE_NUMBER6", "ATTRIBUTE_NUMBER7", "ATTRIBUTE_NUMBER8", "ATTRIBUTE_NUMBER9", "ATTRIBUTE_NUMBER10", "ATTRIBUTE_TIMESTAMP1", "ATTRIBUTE_TIMESTAMP2", "ATTRIBUTE_TIMESTAMP3", "ATTRIBUTE_TIMESTAMP4", "ATTRIBUTE_TIMESTAMP5", "ATTRIBUTE_TIMESTAMP6", "ATTRIBUTE_TIMESTAMP7", "ATTRIBUTE_TIMESTAMP8", "ATTRIBUTE_TIMESTAMP9", "ATTRIBUTE_TIMESTAMP10", "AGENT_EMAIL_ADDRESS", "MODE_OF_TRANSPORT", "SERVICE_LEVEL", "FIRST_PTY_REG_NUM", "THIRD_PTY_REG_NUM", "BUYER_MANAGED_TRANSPORT_FLAG", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    -- 1. Run status
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    -- 2. Error text
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    -- 3. Human identifiers
    stg.DOCUMENT_NUM                                        AS DOCUMENT_NUM,
    stg.VENDOR_NAME                                         AS VENDOR_NAME,
    -- 4. All remaining STG business columns
    stg.INTERFACE_HEADER_KEY,
    stg.ACTION,
    stg.BATCH_ID,
    stg.INTERFACE_SOURCE_CODE,
    stg.APPROVAL_ACTION,
    stg.DOCUMENT_TYPE_CODE,
    stg.STYLE_DISPLAY_NAME,
    stg.PRC_BU_NAME,
    stg.REQ_BU_NAME,
    stg.SOLDTO_LE_NAME,
    stg.BILLTO_BU_NAME,
    stg.AGENT_NAME,
    stg.CURRENCY_CODE,
    stg.RATE,
    stg.RATE_TYPE,
    stg.RATE_DATE,
    stg.COMMENTS,
    stg.BILL_TO_LOCATION,
    stg.SHIP_TO_LOCATION,
    stg.VENDOR_NUM,
    stg.VENDOR_SITE_CODE,
    stg.VENDOR_CONTACT,
    stg.VENDOR_DOC_NUM,
    stg.FOB,
    stg.FREIGHT_CARRIER,
    stg.FREIGHT_TERMS,
    stg.PAY_ON_CODE,
    stg.PAYMENT_TERMS,
    stg.ORIGINATOR_ROLE,
    stg.CHANGE_ORDER_DESC,
    stg.ACCEPTANCE_REQUIRED_FLAG,
    stg.ACCEPTANCE_WITHIN_DAYS,
    stg.SUPPLIER_NOTIF_METHOD,
    stg.FAX,
    stg.EMAIL_ADDRESS,
    stg.CONFIRMING_ORDER_FLAG,
    stg.NOTE_TO_VENDOR,
    stg.NOTE_TO_RECEIVER,
    stg.DEFAULT_TAXATION_COUNTRY,
    stg.TAX_DOCUMENT_SUBTYPE,
    stg.ATTRIBUTE_CATEGORY,
    stg.ATTRIBUTE1,
    stg.ATTRIBUTE2,
    stg.ATTRIBUTE3,
    stg.ATTRIBUTE4,
    stg.ATTRIBUTE5,
    stg.ATTRIBUTE6,
    stg.ATTRIBUTE7,
    stg.ATTRIBUTE8,
    stg.ATTRIBUTE9,
    stg.ATTRIBUTE10,
    stg.ATTRIBUTE11,
    stg.ATTRIBUTE12,
    stg.ATTRIBUTE13,
    stg.ATTRIBUTE14,
    stg.ATTRIBUTE15,
    stg.ATTRIBUTE16,
    stg.ATTRIBUTE17,
    stg.ATTRIBUTE18,
    stg.ATTRIBUTE19,
    stg.ATTRIBUTE20,
    stg.ATTRIBUTE_DATE1,
    stg.ATTRIBUTE_DATE2,
    stg.ATTRIBUTE_DATE3,
    stg.ATTRIBUTE_DATE4,
    stg.ATTRIBUTE_DATE5,
    stg.ATTRIBUTE_DATE6,
    stg.ATTRIBUTE_DATE7,
    stg.ATTRIBUTE_DATE8,
    stg.ATTRIBUTE_DATE9,
    stg.ATTRIBUTE_DATE10,
    stg.ATTRIBUTE_NUMBER1,
    stg.ATTRIBUTE_NUMBER2,
    stg.ATTRIBUTE_NUMBER3,
    stg.ATTRIBUTE_NUMBER4,
    stg.ATTRIBUTE_NUMBER5,
    stg.ATTRIBUTE_NUMBER6,
    stg.ATTRIBUTE_NUMBER7,
    stg.ATTRIBUTE_NUMBER8,
    stg.ATTRIBUTE_NUMBER9,
    stg.ATTRIBUTE_NUMBER10,
    stg.ATTRIBUTE_TIMESTAMP1,
    stg.ATTRIBUTE_TIMESTAMP2,
    stg.ATTRIBUTE_TIMESTAMP3,
    stg.ATTRIBUTE_TIMESTAMP4,
    stg.ATTRIBUTE_TIMESTAMP5,
    stg.ATTRIBUTE_TIMESTAMP6,
    stg.ATTRIBUTE_TIMESTAMP7,
    stg.ATTRIBUTE_TIMESTAMP8,
    stg.ATTRIBUTE_TIMESTAMP9,
    stg.ATTRIBUTE_TIMESTAMP10,
    stg.AGENT_EMAIL_ADDRESS,
    stg.MODE_OF_TRANSPORT,
    stg.SERVICE_LEVEL,
    stg.FIRST_PTY_REG_NUM,
    stg.THIRD_PTY_REG_NUM,
    stg.BUYER_MANAGED_TRANSPORT_FLAG,
    stg.SOURCE_ID,
    -- 5. STG_SEQUENCE_ID
    stg.STG_SEQUENCE_ID,
    -- 6. RUN_ID
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    -- 7. PREFIX (from PIPELINE_RUN)
    cm.PREFIX,
    -- 8. SCENARIO_ID
    stg.SCENARIO_ID,
    -- 9. STAGE_DATE
    stg.STAGE_DATE,
    -- 10. LAST_UPDATED_DATE
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_PO_HEADERS_INT_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
