-- DMT_WORKERS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_WORKERS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "PERSON_NUMBER", "CATEGORY_CODE", "LEGAL_ENTITY_NAME", "DATE_OF_BIRTH", "HIRE_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "FUSION_PERSON_ID", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    w.STG_SEQUENCE_ID,
    wt.TFM_SEQUENCE_ID,
    w.SOURCE_ID,
    wt.PERSON_NUMBER,
    -- FIRST_NAME, LAST_NAME, FULL_NAME do not exist on WORKER TFM (HDL Worker has no name columns)
    wt.CATEGORY_CODE,
    wt.LEGAL_ENTITY_NAME,
    wt.DATE_OF_BIRTH,
    -- EMPLOYEE_NUMBER does not exist on WORKER TFM; PERSON_NUMBER is the identifier
    wt.START_DATE AS HIRE_DATE,
    w.STATUS AS STG_STATUS,
    wt.STATUS AS TFM_STATUS,
    NVL(wt.STATUS, w.STATUS) AS OVERALL_STATUS,
    NVL(wt.STATUS, w.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(wt.ERROR_TEXT, w.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    wt.FUSION_PERSON_ID,
    w.STAGE_DATE,
    wt.RESULTS_UPDATED_DATE,
    DMT_UTIL_PKG.GET_DEEP_LINK('Workers', wt.FUSION_PERSON_ID) AS FUSION_LINK,
    w.SCENARIO_ID
FROM
    DMT_OWNER.DMT_WORKER_STG_TBL w
    LEFT JOIN DMT_OWNER.DMT_WORKER_TFM_TBL wt
        ON wt.STG_SEQUENCE_ID = w.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = wt.INTEGRATION_ID
ORDER BY
    w.STAGE_DATE DESC,
    w.STG_SEQUENCE_ID DESC;
