-- DMT_V_ASSET_ASSIGN_DETAIL
CREATE OR REPLACE EDITIONABLE VIEW "DMT_V_ASSET_ASSIGN_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "ASSET_NUMBER", "LOCATION_SEGMENT1", "UNITS_ASSIGNED", "EXPENSE_ACCOUNT_SEGMENT1", "EXPENSE_ACCOUNT_SEGMENT2", "EXPENSE_ACCOUNT_SEGMENT3", "EXPENSE_ACCOUNT_SEGMENT4", "EXPENSE_ACCOUNT_SEGMENT5", "EXPENSE_ACCOUNT_SEGMENT6", "EXPENSE_ACCOUNT_SEGMENT7", "EXPENSE_ACCOUNT_SEGMENT8", "EXPENSE_ACCOUNT_SEGMENT9", "EXPENSE_ACCOUNT_SEGMENT10", "LOCATION_SEGMENT2", "LOCATION_SEGMENT3", "LOCATION_SEGMENT4", "LOCATION_SEGMENT5", "LOCATION_SEGMENT6", "LOCATION_SEGMENT7", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.ASSET_NUMBER                                        AS ASSET_NUMBER,
    stg.LOCATION_SEGMENT1                                   AS LOCATION_SEGMENT1,
    stg.UNITS_ASSIGNED,
    stg.EXPENSE_ACCOUNT_SEGMENT1,
    stg.EXPENSE_ACCOUNT_SEGMENT2,
    stg.EXPENSE_ACCOUNT_SEGMENT3,
    stg.EXPENSE_ACCOUNT_SEGMENT4,
    stg.EXPENSE_ACCOUNT_SEGMENT5,
    stg.EXPENSE_ACCOUNT_SEGMENT6,
    stg.EXPENSE_ACCOUNT_SEGMENT7,
    stg.EXPENSE_ACCOUNT_SEGMENT8,
    stg.EXPENSE_ACCOUNT_SEGMENT9,
    stg.EXPENSE_ACCOUNT_SEGMENT10,
    stg.LOCATION_SEGMENT2,
    stg.LOCATION_SEGMENT3,
    stg.LOCATION_SEGMENT4,
    stg.LOCATION_SEGMENT5,
    stg.LOCATION_SEGMENT6,
    stg.LOCATION_SEGMENT7,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID AS INTEGRATION_ID,
    cm.PREFIX,
    stg.SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_FA_ASSET_ASSIGN_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_FA_ASSET_ASSIGN_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
