-- DMT_V_SUP_CONTACTS_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_SUP_CONTACTS_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "VENDOR_NAME", "FIRST_NAME", "LAST_NAME", "IMPORT_ACTION", "NAME_PREFIX", "FIRST_NAME_NEW", "MIDDLE_NAME", "LAST_NAME_NEW", "TITLE", "PRIMARY_ADMIN_CONTACT", "EMAIL_ADDRESS", "EMAIL_ADDRESS_NEW", "PHONE_COUNTRY_CODE", "AREA_CODE", "PHONE", "PHONE_EXTENSION", "FAX_COUNTRY_CODE", "FAX_AREA_CODE", "FAX", "MOBILE_COUNTRY_CODE", "MOBILE_AREA_CODE", "MOBILE", "INACTIVE_DATE", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "ATTRIBUTE16", "ATTRIBUTE17", "ATTRIBUTE18", "ATTRIBUTE19", "ATTRIBUTE20", "ATTRIBUTE21", "ATTRIBUTE22", "ATTRIBUTE23", "ATTRIBUTE24", "ATTRIBUTE25", "ATTRIBUTE26", "ATTRIBUTE27", "ATTRIBUTE28", "ATTRIBUTE29", "ATTRIBUTE30", "ATTRIBUTE_NUMBER1", "ATTRIBUTE_NUMBER2", "ATTRIBUTE_NUMBER3", "ATTRIBUTE_NUMBER4", "ATTRIBUTE_NUMBER5", "ATTRIBUTE_NUMBER6", "ATTRIBUTE_NUMBER7", "ATTRIBUTE_NUMBER8", "ATTRIBUTE_NUMBER9", "ATTRIBUTE_NUMBER10", "ATTRIBUTE_NUMBER11", "ATTRIBUTE_NUMBER12", "ATTRIBUTE_DATE1", "ATTRIBUTE_DATE2", "ATTRIBUTE_DATE3", "ATTRIBUTE_DATE4", "ATTRIBUTE_DATE5", "ATTRIBUTE_DATE6", "ATTRIBUTE_DATE7", "ATTRIBUTE_DATE8", "ATTRIBUTE_DATE9", "ATTRIBUTE_DATE10", "ATTRIBUTE_DATE11", "ATTRIBUTE_DATE12", "USER_ACCOUNT_ACTION", "ROLE1", "ROLE2", "ROLE3", "ROLE4", "ROLE5", "ROLE6", "ROLE7", "ROLE8", "ROLE9", "ROLE10", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    -- 1. Run status
    NVL(tfm.STATUS, stg.STATUS)                             AS RUN_STATUS,
    -- 2. Error text
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    -- 3. Human identifiers
    stg.VENDOR_NAME                                         AS VENDOR_NAME,
    stg.FIRST_NAME                                          AS FIRST_NAME,
    stg.LAST_NAME                                           AS LAST_NAME,
    -- 4. All remaining STG business columns
    stg.IMPORT_ACTION,
    stg.PREFIX                                              AS NAME_PREFIX,
    stg.FIRST_NAME_NEW,
    stg.MIDDLE_NAME,
    stg.LAST_NAME_NEW,
    stg.TITLE,
    stg.PRIMARY_ADMIN_CONTACT,
    stg.EMAIL_ADDRESS,
    stg.EMAIL_ADDRESS_NEW,
    stg.PHONE_COUNTRY_CODE,
    stg.AREA_CODE,
    stg.PHONE,
    stg.PHONE_EXTENSION,
    stg.FAX_COUNTRY_CODE,
    stg.FAX_AREA_CODE,
    stg.FAX,
    stg.MOBILE_COUNTRY_CODE,
    stg.MOBILE_AREA_CODE,
    stg.MOBILE,
    stg.INACTIVE_DATE,
    stg.ATTRIBUTE_CATEGORY,
    stg.ATTRIBUTE1,
    stg.ATTRIBUTE2,
    stg.ATTRIBUTE3,
    stg.ATTRIBUTE4,
    stg.ATTRIBUTE5,
    stg.ATTRIBUTE6,
    stg.ATTRIBUTE7,
    stg.ATTRIBUTE8,
    stg.ATTRIBUTE9,
    stg.ATTRIBUTE10,
    stg.ATTRIBUTE11,
    stg.ATTRIBUTE12,
    stg.ATTRIBUTE13,
    stg.ATTRIBUTE14,
    stg.ATTRIBUTE15,
    stg.ATTRIBUTE16,
    stg.ATTRIBUTE17,
    stg.ATTRIBUTE18,
    stg.ATTRIBUTE19,
    stg.ATTRIBUTE20,
    stg.ATTRIBUTE21,
    stg.ATTRIBUTE22,
    stg.ATTRIBUTE23,
    stg.ATTRIBUTE24,
    stg.ATTRIBUTE25,
    stg.ATTRIBUTE26,
    stg.ATTRIBUTE27,
    stg.ATTRIBUTE28,
    stg.ATTRIBUTE29,
    stg.ATTRIBUTE30,
    stg.ATTRIBUTE_NUMBER1,
    stg.ATTRIBUTE_NUMBER2,
    stg.ATTRIBUTE_NUMBER3,
    stg.ATTRIBUTE_NUMBER4,
    stg.ATTRIBUTE_NUMBER5,
    stg.ATTRIBUTE_NUMBER6,
    stg.ATTRIBUTE_NUMBER7,
    stg.ATTRIBUTE_NUMBER8,
    stg.ATTRIBUTE_NUMBER9,
    stg.ATTRIBUTE_NUMBER10,
    stg.ATTRIBUTE_NUMBER11,
    stg.ATTRIBUTE_NUMBER12,
    stg.ATTRIBUTE_DATE1,
    stg.ATTRIBUTE_DATE2,
    stg.ATTRIBUTE_DATE3,
    stg.ATTRIBUTE_DATE4,
    stg.ATTRIBUTE_DATE5,
    stg.ATTRIBUTE_DATE6,
    stg.ATTRIBUTE_DATE7,
    stg.ATTRIBUTE_DATE8,
    stg.ATTRIBUTE_DATE9,
    stg.ATTRIBUTE_DATE10,
    stg.ATTRIBUTE_DATE11,
    stg.ATTRIBUTE_DATE12,
    stg.USER_ACCOUNT_ACTION,
    stg.ROLE1,
    stg.ROLE2,
    stg.ROLE3,
    stg.ROLE4,
    stg.ROLE5,
    stg.ROLE6,
    stg.ROLE7,
    stg.ROLE8,
    stg.ROLE9,
    stg.ROLE10,
    stg.SOURCE_ID,
    -- 5. STG_SEQUENCE_ID
    stg.STG_SEQUENCE_ID,
    -- 6. RUN_ID (+ INTEGRATION_ID compat alias â legacy APEX IRs still reference INTEGRATION_ID)
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    -- 7. PREFIX (from PIPELINE_RUN â run prefix, not person name prefix)
    cm.PREFIX,
    -- 8. SCENARIO_ID
    stg.SCENARIO_ID,
    -- 9. STAGE_DATE
    stg.STAGE_DATE,
    -- 10. LAST_UPDATED_DATE
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_POZ_SUP_CONTACTS_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_POZ_SUP_CONTACTS_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
