-- DMT_V_PLAN_BUDGET_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_PLAN_BUDGET_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "SCENARIO", "VERSION", "ENTITY", "ACCOUNT", "PERIOD", "AMOUNT", "CURRENCY", "DATA_LOAD_DEFINITION_NAME", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.STATUS, stg.STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.SCENARIO                                            AS SCENARIO,
    stg.VERSION                                             AS VERSION,
    stg.ENTITY,
    stg.ACCOUNT,
    stg.PERIOD,
    stg.AMOUNT,
    stg.CURRENCY,
    stg.DATA_LOAD_DEFINITION_NAME,
    stg.ATTRIBUTE1,
    stg.ATTRIBUTE2,
    stg.ATTRIBUTE3,
    stg.ATTRIBUTE4,
    stg.ATTRIBUTE5,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    cm.PREFIX,
    stg.SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_PLAN_BUDGET_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_PLAN_BUDGET_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
