-- DMT_SCENARIO_SUMMARY_V
CREATE OR REPLACE EDITIONABLE VIEW "DMT_SCENARIO_SUMMARY_V" ("OBJECT_CODE", "SCENARIO_ID", "STG_STATUS", "STG_SEQUENCE_ID")  AS 
  SELECT 'Suppliers' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_POZ_SUPPLIERS_STG_TBL
UNION ALL
SELECT 'Supplier Sites' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_POZ_SUP_SITE_STG_TBL
UNION ALL
SELECT 'Supplier Contacts' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_POZ_SUP_CONTACTS_STG_TBL
UNION ALL
SELECT 'Supplier Addresses' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_POZ_SUP_ADDR_STG_TBL
UNION ALL
SELECT 'Supplier Site Assignments' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_POZ_SUP_SITE_ASSN_STG_TBL
UNION ALL
-- ---- Purchase Orders (C004) ----
SELECT 'PO Headers' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PO_HEADERS_INT_STG_TBL
UNION ALL
SELECT 'PO Lines' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PO_LINES_INT_STG_TBL
UNION ALL
SELECT 'PO Line Locations' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PO_LINE_LOCS_INT_STG_TBL
UNION ALL
SELECT 'PO Distributions' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PO_DISTS_INT_STG_TBL
UNION ALL
-- ---- Customers (C005) ----
SELECT 'Customer Parties' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_HZ_PARTIES_STG_TBL
UNION ALL
SELECT 'Customer Locations' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_HZ_LOCATIONS_STG_TBL
UNION ALL
SELECT 'Customer Party Sites' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_HZ_PARTY_SITES_STG_TBL
UNION ALL
SELECT 'Customer Party Site Uses' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_HZ_PARTY_SITE_USES_STG_TBL
UNION ALL
SELECT 'Customer Accounts' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_HZ_ACCOUNTS_STG_TBL
UNION ALL
SELECT 'Customer Account Sites' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_HZ_ACCT_SITES_STG_TBL
UNION ALL
SELECT 'Customer Account Site Uses' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_HZ_ACCT_SITE_USES_STG_TBL
UNION ALL
-- ---- AR Invoices (C006) ----
SELECT 'AR Invoice Lines' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_RA_LINES_STG_TBL
UNION ALL
SELECT 'AR Invoice Distributions' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_RA_DISTS_STG_TBL
UNION ALL
-- ---- AP Invoices (C003) ----
SELECT 'AP Invoice Headers' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_AP_INVOICES_INT_STG_TBL
UNION ALL
SELECT 'AP Invoice Lines' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_AP_INVOICE_LINES_INT_STG_TBL
UNION ALL
-- ---- Projects (C007) ----
SELECT 'Projects' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PJF_PROJECTS_STG_TBL
UNION ALL
SELECT 'Project Tasks' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PJF_TASKS_STG_TBL
UNION ALL
SELECT 'Project Team Members' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PJF_TEAM_MEMBERS_STG_TBL
UNION ALL
SELECT 'Project Transaction Controls' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PJC_TXN_CONTROLS_STG_TBL
UNION ALL
SELECT 'Project Billing Events' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PJB_BILL_EVENTS_STG_TBL
UNION ALL
SELECT 'Project Expenditures' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PJC_EXPENDITURES_STG_TBL
UNION ALL
-- ---- Grants (C008) ----
SELECT 'Grant Award Headers' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_HEADERS_STG_TBL
UNION ALL
SELECT 'Grant Award Funding' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_FUNDING_STG_TBL
UNION ALL
SELECT 'Grant Award Projects' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_PROJECTS_STG_TBL
UNION ALL
SELECT 'Grant Award Personnel' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_PERSONNEL_STG_TBL
UNION ALL
SELECT 'Grant Award Fund Sources' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_FUND_SRC_STG_TBL
UNION ALL
SELECT 'Grant Award Project Fund Sources' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_PRJ_FUND_SRC_STG_TBL
UNION ALL
SELECT 'Grant Award Keywords' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_KEYWORDS_STG_TBL
UNION ALL
SELECT 'Grant Award Budget Periods' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_BDGT_PRDS_STG_TBL
UNION ALL
SELECT 'Grant Award Certifications' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_CERTS_STG_TBL
UNION ALL
SELECT 'Grant Award CFDAs' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_CFDAS_STG_TBL
UNION ALL
SELECT 'Grant Award Fund Allocations' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_FUND_ALLOC_STG_TBL
UNION ALL
SELECT 'Grant Award Org Credits' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_ORG_CREDITS_STG_TBL
UNION ALL
SELECT 'Grant Award Project Task Breakdowns' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_PRJ_TSK_BRD_STG_TBL
UNION ALL
SELECT 'Grant Award References' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_REFERENCES_STG_TBL
UNION ALL
SELECT 'Grant Award Terms' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GMS_AWD_TERMS_STG_TBL
UNION ALL
-- ---- Receipts ----
SELECT 'Receipt Headers' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_RCV_HEADERS_STG_TBL
UNION ALL
SELECT 'Receipt Transactions' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_RCV_TRANSACTIONS_STG_TBL
UNION ALL
-- ---- HCM Workers ----
SELECT 'Workers' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_WORKER_STG_TBL
UNION ALL
SELECT 'Person Names' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PERSON_NAME_STG_TBL
UNION ALL
SELECT 'Person Emails' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PERSON_EMAIL_STG_TBL
UNION ALL
SELECT 'Person Phones' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PERSON_PHONE_STG_TBL
UNION ALL
SELECT 'Person Addresses' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PERSON_ADDR_STG_TBL
UNION ALL
SELECT 'Person National IDs' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PERSON_NID_STG_TBL
UNION ALL
SELECT 'Person Legislative Data' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PERSON_LEGISL_STG_TBL
UNION ALL
SELECT 'Work Relationships' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_WORK_REL_STG_TBL
UNION ALL
SELECT 'Assignments' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_ASSIGNMENT_STG_TBL
UNION ALL
SELECT 'Salaries' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_SALARY_STG_TBL
UNION ALL
SELECT 'Salary Bases' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_SAL_BASIS_STG_TBL
UNION ALL
SELECT 'Absences' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_ABSENCE_STG_TBL
UNION ALL
SELECT 'W2 Balances' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_W2_BAL_STG_TBL
UNION ALL
SELECT 'W2 Balance Details' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_W2_BAL_DTL_STG_TBL
UNION ALL
SELECT 'Benefits Participants' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_BEN_PARTIC_STG_TBL
UNION ALL
SELECT 'Benefits Dependents' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_BEN_DEPEND_STG_TBL
UNION ALL
SELECT 'Benefits Beneficiaries' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_BEN_BENFY_STG_TBL
UNION ALL
SELECT 'Pay Relationships' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PAY_REL_STG_TBL
UNION ALL
SELECT 'Tax Cards' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_TAX_CARD_STG_TBL
UNION ALL
SELECT 'Tax Card Components' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_TAX_CARD_COMP_STG_TBL
UNION ALL
SELECT 'Talent Profiles' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_TALENT_PROF_STG_TBL
UNION ALL
SELECT 'Talent Profile Items' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_TALENT_PROF_ITEM_STG_TBL
UNION ALL
SELECT 'Performance Evaluations' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PERF_EVAL_STG_TBL
UNION ALL
SELECT 'Performance Evaluation Ratings' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PERF_EVAL_RATING_STG_TBL
UNION ALL
SELECT 'Work Schedules' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_WORK_SCHED_STG_TBL
UNION ALL
SELECT 'Work Schedule Details' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_WORK_SCHED_DTL_STG_TBL
UNION ALL
-- ---- Project Budgets ----
SELECT 'Project Budgets' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PRJ_BUDGET_STG_TBL
UNION ALL
-- ---- GL ----
SELECT 'GL Journal Entries' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GL_INTERFACE_STG_TBL
UNION ALL
SELECT 'GL Budget Entries' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_GL_BUDGET_INT_STG_TBL
UNION ALL
SELECT 'Planning Budgets' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_PLAN_BUDGET_STG_TBL
UNION ALL
-- ---- Fixed Assets ----
SELECT 'FA Asset Headers' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_FA_ASSET_HDR_STG_TBL
UNION ALL
SELECT 'FA Asset Assignments' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_FA_ASSET_ASSIGN_STG_TBL
UNION ALL
SELECT 'FA Asset Books' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_FA_ASSET_BOOK_STG_TBL
UNION ALL
-- ---- Requisitions ----
SELECT 'Requisition Headers' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_POR_REQ_HEADERS_STG_TBL
UNION ALL
SELECT 'Requisition Lines' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_POR_REQ_LINES_STG_TBL
UNION ALL
SELECT 'Requisition Distributions' AS OBJECT_CODE, SCENARIO_ID, STG_STATUS, STG_SEQUENCE_ID
FROM DMT_POR_REQ_DISTS_STG_TBL;
