-- DMT_RUN_STATUS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_RUN_STATUS_V" ("RUN_ID", "INTEGRATION_ID", "SCENARIO_ID", "PIPELINE_CODES", "PREFIX", "RUN_STATUS", "SUBMITTED_DATE", "COMPLETED_DATE", "OBJECT_TYPE", "TOTAL_ROWS", "LOADED_ROWS", "FAILED_ROWS", "GENERATED_ROWS", "OTHER_ROWS", "ZIP_FILENAME", "ZIP_SIZE_BYTES", "LOAD_ESS_JOB_ID", "IMPORT_ESS_JOB_ID", "POSTRUN_ESS_JOB_ID", "RECENT_LOGS")  AS 
  WITH tfm_summary AS (
    -- ---- Suppliers (C001) — 5 separate imports ----
    SELECT RUN_ID,
           'Suppliers'           AS OBJECT_TYPE,
           COUNT(*)              AS TOTAL_ROWS,
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END) AS LOADED_ROWS,
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END) AS FAILED_ROWS,
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END) AS GENERATED_ROWS,
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END) AS OTHER_ROWS
    FROM   DMT_OWNER.DMT_POZ_SUPPLIERS_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    SELECT RUN_ID, 'SupplierAddresses', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_POZ_SUP_ADDR_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    SELECT RUN_ID, 'SupplierSites', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_POZ_SUP_SITE_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    SELECT RUN_ID, 'SupplierSiteAssignments', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_POZ_SUP_SITE_ASSN_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    SELECT RUN_ID, 'SupplierContacts', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_POZ_SUP_CONTACTS_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- Purchase Orders (C004) — grouped by BU ----
    SELECT RUN_ID,
           'PurchaseOrders:' || PRC_BU_NAME, COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL
    WHERE  NVL(DOCUMENT_TYPE_CODE, 'STANDARD') = 'STANDARD'
    GROUP  BY RUN_ID, PRC_BU_NAME
    UNION ALL
    -- ---- Blanket POs — grouped by BU ----
    SELECT RUN_ID,
           'BlanketPOs' || CASE WHEN PRC_BU_NAME IS NOT NULL THEN ':' || PRC_BU_NAME END,
           COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL
    WHERE  DOCUMENT_TYPE_CODE = 'BLANKET'
    GROUP  BY RUN_ID, PRC_BU_NAME
    UNION ALL
    -- ---- Contracts — grouped by BU ----
    SELECT RUN_ID,
           'Contracts' || CASE WHEN PRC_BU_NAME IS NOT NULL THEN ':' || PRC_BU_NAME END,
           COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL
    WHERE  DOCUMENT_TYPE_CODE = 'CONTRACT'
    GROUP  BY RUN_ID, PRC_BU_NAME
    UNION ALL
    -- ---- AP Invoices (C003) — optionally grouped by OU ----
    SELECT RUN_ID,
           'APInvoices' || CASE WHEN OPERATING_UNIT IS NOT NULL THEN ':' || OPERATING_UNIT END,
           COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_AP_INVOICES_INT_TFM_TBL
    GROUP  BY RUN_ID, OPERATING_UNIT
    UNION ALL
    -- ---- Customers (C005) — single zip, count accounts as primary ----
    SELECT RUN_ID, 'Customers', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_HZ_ACCOUNTS_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- AR Invoices (C006) — grouped by BU + BatchSource ----
    SELECT RUN_ID,
           'ARInvoices' || CASE WHEN BU_NAME IS NOT NULL
               THEN ':' || BU_NAME || CASE WHEN BATCH_SOURCE_NAME IS NOT NULL
                   THEN ':' || BATCH_SOURCE_NAME END
               END,
           COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_RA_LINES_TFM_TBL
    GROUP  BY RUN_ID, BU_NAME, BATCH_SOURCE_NAME
    UNION ALL
    -- ---- GL Balances — uses TFM_STATUS ----
    SELECT RUN_ID, 'GLBalances', COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN TFM_STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN TFM_STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN TFM_STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_GL_INTERFACE_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- GL Budget Balances — uses TFM_STATUS ----
    SELECT RUN_ID, 'GLBudgetBalances', COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN TFM_STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN TFM_STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN TFM_STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_GL_BUDGET_INT_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- Planning Budgets ----
    SELECT RUN_ID, 'PlanningBudgets', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_PLAN_BUDGET_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- Projects (C007) ----
    SELECT RUN_ID, 'Projects', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_PJF_PROJECTS_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- Project Budgets ----
    SELECT RUN_ID, 'ProjectBudgets', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_PRJ_BUDGET_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- Expenditures (C008) ----
    SELECT RUN_ID, 'Expenditures', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_PJC_EXPENDITURES_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- Billing Events ----
    SELECT RUN_ID, 'BillingEvents', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_PJB_BILL_EVENTS_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- Grants ----
    SELECT RUN_ID, 'Grants', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_GMS_AWD_HEADERS_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- Fixed Assets ----
    SELECT RUN_ID, 'Assets', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_FA_ASSET_HDR_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- Requisitions ----
    SELECT RUN_ID, 'Requisitions', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_POR_REQ_HEADERS_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- Misc Receipts (On Hand Qty) ----
    SELECT RUN_ID, 'MiscReceipts', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_RCV_HEADERS_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- HCM: Workers ----
    SELECT RUN_ID, 'Workers', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_WORKER_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- HCM: Worker Assignments ----
    SELECT RUN_ID, 'WorkerAssignments', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_ASSIGNMENT_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- HCM: Salaries ----
    SELECT RUN_ID, 'Salaries', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_SALARY_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- HCM: Salary Bases ----
    SELECT RUN_ID, 'SalaryBases', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_SAL_BASIS_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- HCM: Absence Entries ----
    SELECT RUN_ID, 'AbsenceEntries', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_ABSENCE_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- HCM: W2 Balances ----
    SELECT RUN_ID, 'W2Balances', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_W2_BAL_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- HCM: Participant Enrollments ----
    SELECT RUN_ID, 'ParticipantEnrollments', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_BEN_PARTIC_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- HCM: Dependent Enrollments ----
    SELECT RUN_ID, 'DependentEnrollments', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_BEN_DEPEND_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- HCM: Beneficiary Designations ----
    SELECT RUN_ID, 'BeneficiaryDesignations', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_BEN_BENFY_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- HCM: Payroll Relationships ----
    SELECT RUN_ID, 'PayrollRelationships', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_PAY_REL_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- HCM: Tax Cards ----
    SELECT RUN_ID, 'TaxCards', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_TAX_CARD_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- HCM: Talent Profiles ----
    SELECT RUN_ID, 'TalentProfiles', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_TALENT_PROF_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- HCM: Performance Documents ----
    SELECT RUN_ID, 'PerformanceDocuments', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_PERF_EVAL_TFM_TBL
    GROUP  BY RUN_ID
    UNION ALL
    -- ---- HCM: Work Schedules ----
    SELECT RUN_ID, 'WorkSchedules', COUNT(*),
           SUM(CASE WHEN STATUS = 'LOADED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'FAILED'    THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS = 'GENERATED' THEN 1 ELSE 0 END),
           SUM(CASE WHEN STATUS NOT IN ('LOADED','FAILED','GENERATED') THEN 1 ELSE 0 END)
    FROM   DMT_OWNER.DMT_WORK_SCHED_TFM_TBL
    GROUP  BY RUN_ID
)
SELECT
    m.RUN_ID,
    m.RUN_ID                     AS INTEGRATION_ID,
    m.RUN_ID                     AS SCENARIO_ID,
    m.PIPELINE_CODES,
    m.PREFIX,
    m.RUN_STATUS,
    m.SUBMITTED_DATE,
    m.COMPLETED_DATE,
    t.OBJECT_TYPE,
    t.TOTAL_ROWS,
    t.LOADED_ROWS,
    t.FAILED_ROWS,
    t.GENERATED_ROWS,
    t.OTHER_ROWS,
    z.FILENAME                   AS ZIP_FILENAME,
    z.ZIP_SIZE_BYTES,
    q.LOAD_ESS_JOB_ID,
    q.IMPORT_ESS_JOB_ID,
    q.POSTRUN_ESS_JOB_ID,
    (SELECT XMLCAST(
                XMLAGG(
                    XMLELEMENT(e, '[' || l.LOG_TYPE || '] ' ||
                                  NVL(l.PROCEDURE_NAME, l.PACKAGE_NAME) || ': ' ||
                                  DBMS_LOB.SUBSTR(l.MESSAGE, 200, 1)
                               || CHR(10))
                    ORDER BY l.LOG_ID DESC
                ) AS CLOB)
     FROM   (SELECT LOG_ID, LOG_TYPE, PACKAGE_NAME, PROCEDURE_NAME, MESSAGE
             FROM   DMT_OWNER.DMT_LOG_TBL
             WHERE  RUN_ID = m.RUN_ID
             ORDER  BY LOG_ID DESC
             FETCH  FIRST 10 ROWS ONLY) l
    )                            AS RECENT_LOGS
FROM   DMT_OWNER.DMT_PIPELINE_RUN_TBL m
JOIN   tfm_summary t
    ON t.RUN_ID  = m.RUN_ID
LEFT JOIN DMT_OWNER.DMT_FBDI_ZIP_TBL z
    ON  z.RUN_ID = m.RUN_ID
    AND z.OBJECT_TYPE    = t.OBJECT_TYPE
LEFT JOIN DMT_OWNER.DMT_WORK_QUEUE_TBL q
    ON  q.RUN_ID = m.RUN_ID
    AND q.CEMLI_CODE     = t.OBJECT_TYPE
ORDER BY
    m.RUN_ID DESC,
    CASE
        WHEN t.OBJECT_TYPE = 'Suppliers'               THEN 1
        WHEN t.OBJECT_TYPE = 'SupplierAddresses'       THEN 2
        WHEN t.OBJECT_TYPE = 'SupplierSites'           THEN 3
        WHEN t.OBJECT_TYPE = 'SupplierSiteAssignments' THEN 4
        WHEN t.OBJECT_TYPE = 'SupplierContacts'        THEN 5
        WHEN t.OBJECT_TYPE LIKE 'PurchaseOrders%'      THEN 10
        WHEN t.OBJECT_TYPE LIKE 'BlanketPOs%'          THEN 11
        WHEN t.OBJECT_TYPE LIKE 'Contracts%'           THEN 12
        WHEN t.OBJECT_TYPE LIKE 'APInvoices%'          THEN 13
        WHEN t.OBJECT_TYPE LIKE '1099Invoices%'        THEN 14
        WHEN t.OBJECT_TYPE = 'Customers'               THEN 20
        WHEN t.OBJECT_TYPE LIKE 'ARInvoices%'          THEN 21
        WHEN t.OBJECT_TYPE = 'MiscReceipts'            THEN 22
        WHEN t.OBJECT_TYPE = 'GLBalances'              THEN 30
        WHEN t.OBJECT_TYPE = 'GLBudgetBalances'        THEN 31
        WHEN t.OBJECT_TYPE = 'PlanningBudgets'         THEN 32
        WHEN t.OBJECT_TYPE = 'Assets'                  THEN 33
        WHEN t.OBJECT_TYPE = 'Projects'                THEN 40
        WHEN t.OBJECT_TYPE = 'ProjectBudgets'          THEN 41
        WHEN t.OBJECT_TYPE = 'Expenditures'            THEN 42
        WHEN t.OBJECT_TYPE = 'BillingEvents'           THEN 43
        WHEN t.OBJECT_TYPE = 'Grants'                  THEN 44
        WHEN t.OBJECT_TYPE = 'Requisitions'            THEN 45
        WHEN t.OBJECT_TYPE = 'Workers'                 THEN 50
        WHEN t.OBJECT_TYPE = 'WorkerAssignments'       THEN 51
        WHEN t.OBJECT_TYPE = 'Salaries'                THEN 52
        WHEN t.OBJECT_TYPE = 'SalaryBases'             THEN 53
        WHEN t.OBJECT_TYPE = 'AbsenceEntries'          THEN 54
        WHEN t.OBJECT_TYPE = 'W2Balances'              THEN 55
        WHEN t.OBJECT_TYPE = 'ParticipantEnrollments'  THEN 56
        WHEN t.OBJECT_TYPE = 'DependentEnrollments'    THEN 57
        WHEN t.OBJECT_TYPE = 'BeneficiaryDesignations' THEN 58
        WHEN t.OBJECT_TYPE = 'PayrollRelationships'    THEN 59
        WHEN t.OBJECT_TYPE = 'TaxCards'                THEN 60
        WHEN t.OBJECT_TYPE = 'TalentProfiles'          THEN 61
        WHEN t.OBJECT_TYPE = 'PerformanceDocuments'    THEN 62
        WHEN t.OBJECT_TYPE = 'WorkSchedules'           THEN 63
        ELSE 99
    END;
