-- DMT_ESS_JOB_DETAIL_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_ESS_JOB_DETAIL_V" ("ESS_JOB_ID", "RUN_ID", "INTEGRATION_ID", "REQUEST_ID", "PARENT_REQUEST_ID", "JOB_DEFINITION", "JOB_SHORT_NAME", "STATE", "STATE_TEXT", "SUBMITTER", "SUBMIT_TIME", "START_TIME", "END_TIME", "DURATION_SECS", "CEMLI_CODE", "DEPTH_LEVEL", "ROOT_REQUEST_ID", "JOB_ROLE", "OBJECT_TYPE", "ZIP_FILENAME", "ESS_FILE_ID", "OUTPUT_FILE_TYPE", "OUTPUT_FILE_NAME", "PIPELINE_CODES", "PREFIX", "RUN_STATUS")  AS 
  SELECT
    j.ESS_JOB_ID,
    j.RUN_ID,
    j.RUN_ID                     AS INTEGRATION_ID,
    j.REQUEST_ID,
    j.PARENT_REQUEST_ID,
    j.JOB_DEFINITION,
    j.JOB_SHORT_NAME,
    j.STATE,
    j.STATE_TEXT,
    j.SUBMITTER,
    j.SUBMIT_TIME,
    j.START_TIME,
    j.END_TIME,
    ROUND((j.END_TIME - j.START_TIME) * 86400) AS DURATION_SECS,
    j.CEMLI_CODE,
    j.DEPTH_LEVEL,
    -- Resolve the root request ID (the Load ESS job) for grouping
    NVL(j.PARENT_REQUEST_ID, j.REQUEST_ID) AS ROOT_REQUEST_ID,
    -- Job role: is this a Load, Import, or Post-Run job?
    CASE
        WHEN q_load.QUEUE_ID IS NOT NULL   THEN 'LOAD'
        WHEN q_import.QUEUE_ID IS NOT NULL THEN 'IMPORT'
        WHEN q_post.QUEUE_ID IS NOT NULL   THEN 'POSTRUN'
        ELSE NULL
    END AS JOB_ROLE,
    -- FBDI context
    COALESCE(z_load.OBJECT_TYPE, z_import.OBJECT_TYPE, z_post.OBJECT_TYPE) AS OBJECT_TYPE,
    COALESCE(z_load.FILENAME, z_import.FILENAME, z_post.FILENAME)           AS ZIP_FILENAME,
    -- File download metadata
    f.ESS_FILE_ID,
    f.FILE_TYPE                   AS OUTPUT_FILE_TYPE,
    f.FILE_NAME                   AS OUTPUT_FILE_NAME,
    -- Master run context
    m.PIPELINE_CODES,
    m.PREFIX,
    m.RUN_STATUS
FROM
    DMT_OWNER.DMT_ESS_JOB_TBL j
LEFT JOIN DMT_OWNER.DMT_WORK_QUEUE_TBL q_load
    ON  TO_CHAR(j.REQUEST_ID) = q_load.LOAD_ESS_JOB_ID
LEFT JOIN DMT_OWNER.DMT_WORK_QUEUE_TBL q_import
    ON  TO_CHAR(j.REQUEST_ID) = q_import.IMPORT_ESS_JOB_ID
LEFT JOIN DMT_OWNER.DMT_WORK_QUEUE_TBL q_post
    ON  TO_CHAR(j.REQUEST_ID) = q_post.POSTRUN_ESS_JOB_ID
LEFT JOIN DMT_OWNER.DMT_FBDI_ZIP_TBL z_load
    ON  z_load.FBDI_ZIP_ID = q_load.FBDI_ZIP_ID
LEFT JOIN DMT_OWNER.DMT_FBDI_ZIP_TBL z_import
    ON  z_import.FBDI_ZIP_ID = q_import.FBDI_ZIP_ID
LEFT JOIN DMT_OWNER.DMT_FBDI_ZIP_TBL z_post
    ON  z_post.FBDI_ZIP_ID = q_post.FBDI_ZIP_ID
LEFT JOIN DMT_OWNER.DMT_ESS_JOB_FILE_TBL f
    ON  f.ESS_JOB_ID = j.ESS_JOB_ID
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL m
    ON  m.RUN_ID = j.RUN_ID
ORDER BY
    j.RUN_ID DESC,
    j.DEPTH_LEVEL,
    j.REQUEST_ID;
