-- DMT_CFG_VALUE_SETS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_CFG_VALUE_SETS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "VALUE_SET_CODE", "DESCRIPTION", "MODULE_ID", "VALIDATION_TYPE", "VALUE_DATA_TYPE", "STAGE_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "ERROR_TEXT", "RESULTS_UPDATED_DATE", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    h.STG_SEQUENCE_ID,
    ht.TFM_SEQUENCE_ID,
    h.SOURCE_ID,
    NVL(ht.VALUE_SET_CODE, h.VALUE_SET_CODE) AS VALUE_SET_CODE,
    NVL(ht.DESCRIPTION, h.DESCRIPTION) AS DESCRIPTION,
    NVL(ht.MODULE_ID, h.MODULE_ID) AS MODULE_ID,
    NVL(ht.VALIDATION_TYPE, h.VALIDATION_TYPE) AS VALIDATION_TYPE,
    NVL(ht.VALUE_DATA_TYPE, h.VALUE_DATA_TYPE) AS VALUE_DATA_TYPE,
    h.STAGE_DATE,
    h.STG_STATUS AS STG_STATUS,
    ht.TFM_STATUS,
    NVL(ht.TFM_STATUS, h.STG_STATUS) AS OVERALL_STATUS,
    DBMS_LOB.SUBSTR(NVL(ht.ERROR_TEXT, h.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ht.RESULTS_UPDATED_DATE,
    h.SCENARIO_ID
FROM
    DMT_OWNER.DMT_FND_VS_SET_STG_TBL h
    LEFT JOIN DMT_OWNER.DMT_FND_VS_SET_TFM_TBL ht
        ON ht.STG_SEQUENCE_ID = h.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ht.INTEGRATION_ID;
