-- DMT_V_SAL_BASIS_DETAIL
CREATE OR REPLACE EDITIONABLE VIEW "DMT_V_SAL_BASIS_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "SALARY_BASIS_NAME", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "ELEMENT_NAME", "INPUT_VALUE_NAME", "SALARY_BASIS_CODE", "ANNUALIZATION_FACTOR", "GRADE_RATE_TYPE", "LEGISLATIVE_DATA_GROUP_NAME", "DESCRIPTION", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.SALARY_BASIS_NAME                                   AS SALARY_BASIS_NAME,
    stg.EFFECTIVE_START_DATE,
    stg.EFFECTIVE_END_DATE,
    stg.ELEMENT_NAME,
    stg.INPUT_VALUE_NAME,
    stg.SALARY_BASIS_CODE,
    stg.ANNUALIZATION_FACTOR,
    stg.GRADE_RATE_TYPE,
    stg.LEGISLATIVE_DATA_GROUP_NAME,
    stg.DESCRIPTION,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID AS INTEGRATION_ID,
    cm.PREFIX,
    stg.SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_SAL_BASIS_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_SAL_BASIS_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
