-- DMT_P2P_REQUISITIONS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_P2P_REQUISITIONS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "REQUISITION_NUMBER", "BUSINESS_UNIT", "DOCUMENT_STATUS", "REQ_DESCRIPTION", "PREPARER", "STAGE_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "RESULTS_UPDATED_DATE", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    h.STG_SEQUENCE_ID,
    ht.TFM_SEQUENCE_ID,
    h.SOURCE_ID,
    ht.REQUISITION_NUMBER,
    ht.REQ_BU_NAME AS BUSINESS_UNIT,
    ht.DOCUMENT_STATUS,
    ht.DESCRIPTION AS REQ_DESCRIPTION,
    ht.PREPARER_EMAIL_ADDR AS PREPARER,
    h.STAGE_DATE,
    h.STATUS AS STG_STATUS,
    ht.STATUS AS TFM_STATUS,
    NVL(ht.STATUS, h.STATUS) AS OVERALL_STATUS,
    NVL(ht.STATUS, h.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(ht.ERROR_TEXT, h.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ht.RESULTS_UPDATED_DATE,
    h.SCENARIO_ID
FROM
    DMT_OWNER.DMT_POR_REQ_HEADERS_STG_TBL h
    LEFT JOIN DMT_OWNER.DMT_POR_REQ_HEADERS_TFM_TBL ht
        ON ht.STG_SEQUENCE_ID = h.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ht.INTEGRATION_ID
ORDER BY
    h.STAGE_DATE DESC,
    h.STG_SEQUENCE_ID DESC;
