-- DMT_V_GRANT_PERSONNEL_DETAIL
CREATE OR REPLACE EDITIONABLE VIEW "DMT_V_GRANT_PERSONNEL_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "AWARD_NUMBER", "PROJECT_NUMBER", "INTERNAL", "PERSON_EMAIL", "PERSON_NAME", "PERSON_NUMBER", "ROLE", "START_DATE", "END_DATE", "CREDIT_PERCENTAGE", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "ATTRIBUTE16", "ATTRIBUTE17", "ATTRIBUTE18", "ATTRIBUTE19", "ATTRIBUTE20", "ATTRIBUTE_NUMBER1", "ATTRIBUTE_NUMBER2", "ATTRIBUTE_NUMBER3", "ATTRIBUTE_NUMBER4", "ATTRIBUTE_NUMBER5", "ATTRIBUTE_NUMBER6", "ATTRIBUTE_NUMBER7", "ATTRIBUTE_NUMBER8", "ATTRIBUTE_NUMBER9", "ATTRIBUTE_NUMBER10", "ATTRIBUTE_DATE1", "ATTRIBUTE_DATE2", "ATTRIBUTE_DATE3", "ATTRIBUTE_DATE4", "ATTRIBUTE_DATE5", "ATTRIBUTE_DATE6", "ATTRIBUTE_DATE7", "ATTRIBUTE_DATE8", "ATTRIBUTE_DATE9", "ATTRIBUTE_DATE10", "ATTRIBUTE_TIMESTAMP1", "ATTRIBUTE_TIMESTAMP2", "ATTRIBUTE_TIMESTAMP3", "ATTRIBUTE_TIMESTAMP4", "ATTRIBUTE_TIMESTAMP5", "ATTRIBUTE_TIMESTAMP6", "ATTRIBUTE_TIMESTAMP7", "ATTRIBUTE_TIMESTAMP8", "ATTRIBUTE_TIMESTAMP9", "ATTRIBUTE_TIMESTAMP10", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.AWARD_NUMBER                                        AS AWARD_NUMBER,
    stg.PROJECT_NUMBER,
    stg.INTERNAL,
    stg.PERSON_EMAIL,
    stg.PERSON_NAME,
    stg.PERSON_NUMBER,
    stg.ROLE,
    stg.START_DATE,
    stg.END_DATE,
    stg.CREDIT_PERCENTAGE,
    stg.ATTRIBUTE_CATEGORY,
    stg.ATTRIBUTE1,
    stg.ATTRIBUTE2,
    stg.ATTRIBUTE3,
    stg.ATTRIBUTE4,
    stg.ATTRIBUTE5,
    stg.ATTRIBUTE6,
    stg.ATTRIBUTE7,
    stg.ATTRIBUTE8,
    stg.ATTRIBUTE9,
    stg.ATTRIBUTE10,
    stg.ATTRIBUTE11,
    stg.ATTRIBUTE12,
    stg.ATTRIBUTE13,
    stg.ATTRIBUTE14,
    stg.ATTRIBUTE15,
    stg.ATTRIBUTE16,
    stg.ATTRIBUTE17,
    stg.ATTRIBUTE18,
    stg.ATTRIBUTE19,
    stg.ATTRIBUTE20,
    stg.ATTRIBUTE_NUMBER1,
    stg.ATTRIBUTE_NUMBER2,
    stg.ATTRIBUTE_NUMBER3,
    stg.ATTRIBUTE_NUMBER4,
    stg.ATTRIBUTE_NUMBER5,
    stg.ATTRIBUTE_NUMBER6,
    stg.ATTRIBUTE_NUMBER7,
    stg.ATTRIBUTE_NUMBER8,
    stg.ATTRIBUTE_NUMBER9,
    stg.ATTRIBUTE_NUMBER10,
    stg.ATTRIBUTE_DATE1,
    stg.ATTRIBUTE_DATE2,
    stg.ATTRIBUTE_DATE3,
    stg.ATTRIBUTE_DATE4,
    stg.ATTRIBUTE_DATE5,
    stg.ATTRIBUTE_DATE6,
    stg.ATTRIBUTE_DATE7,
    stg.ATTRIBUTE_DATE8,
    stg.ATTRIBUTE_DATE9,
    stg.ATTRIBUTE_DATE10,
    stg.ATTRIBUTE_TIMESTAMP1,
    stg.ATTRIBUTE_TIMESTAMP2,
    stg.ATTRIBUTE_TIMESTAMP3,
    stg.ATTRIBUTE_TIMESTAMP4,
    stg.ATTRIBUTE_TIMESTAMP5,
    stg.ATTRIBUTE_TIMESTAMP6,
    stg.ATTRIBUTE_TIMESTAMP7,
    stg.ATTRIBUTE_TIMESTAMP8,
    stg.ATTRIBUTE_TIMESTAMP9,
    stg.ATTRIBUTE_TIMESTAMP10,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID AS INTEGRATION_ID,
    cm.PREFIX,
    CAST(NULL AS NUMBER)                                    AS SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_GMS_AWD_PERSONNEL_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_GMS_AWD_PERSONNEL_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
