-- DMT_DASHBOARD_RUNS_V
CREATE OR REPLACE EDITIONABLE VIEW "DMT_DASHBOARD_RUNS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "STATUS", "START_DATE", "END_DATE", "SOURCE_FILENAME", "FBDI_FILENAME", "ESS_JOB_ID", "PREFIX", "TOTAL_RECORDS", "VALID_RECORDS", "INVALID_RECORDS", "SUCCESSFUL_RECORDS", "ERRORED_RECORDS", "SUCCESS_RATE_PCT", "RESULT", "LAST_UPDATED_DATE")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.STATUS,
    m.START_DATE,
    m.END_DATE,
    m.SOURCE_FILENAME,
    m.FBDI_FILENAME,
    m.ESS_JOB_ID,
    m.PREFIX,
    m.TOTAL_RECORDS,
    m.VALID_RECORDS,
    m.INVALID_RECORDS,
    m.SUCCESSFUL_RECORDS,
    m.ERRORED_RECORDS,
    ROUND(CASE
        WHEN m.TOTAL_RECORDS > 0
        THEN (m.SUCCESSFUL_RECORDS / m.TOTAL_RECORDS * 100)
        ELSE NULL
    END, 2) AS SUCCESS_RATE_PCT,
    m.RESULT,
    m.LAST_UPDATED_DATE
FROM
    DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
ORDER BY
    m.START_DATE DESC;
