-- DMT_V_ABSENCE_DETAIL
CREATE OR REPLACE EDITIONABLE VIEW "DMT_V_ABSENCE_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "PERSON_NUMBER", "ABSENCE_TYPE", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "EMPLOYER_NAME", "ABSENCE_NAME", "ABSENCE_CATEGORY", "ABSENCE_STATUS", "START_DATE", "END_DATE", "START_TIME", "END_TIME", "APPROVAL_STATUS_CODE", "DURATION", "SUBMISSION_DATE", "ABSENCE_REASON", "COMMENTS", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.PERSON_NUMBER                                       AS PERSON_NUMBER,
    stg.ABSENCE_TYPE                                        AS ABSENCE_TYPE,
    stg.EFFECTIVE_START_DATE,
    stg.EFFECTIVE_END_DATE,
    stg.EMPLOYER_NAME,
    stg.ABSENCE_NAME,
    stg.ABSENCE_CATEGORY,
    stg.ABSENCE_STATUS,
    stg.START_DATE,
    stg.END_DATE,
    stg.START_TIME,
    stg.END_TIME,
    stg.APPROVAL_STATUS_CODE,
    stg.DURATION,
    stg.SUBMISSION_DATE,
    stg.ABSENCE_REASON,
    stg.COMMENTS,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID AS INTEGRATION_ID,
    cm.PREFIX,
    stg.SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_ABSENCE_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_ABSENCE_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
