-- DMT_BILLING_EVENTS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_BILLING_EVENTS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "EVENT_TYPE_NAME", "EVENT_DESC", "BILL_TRNS_AMOUNT", "CONTRACT_NUMBER", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT m.INTEGRATION_ID, m.ORCHESTRATION_CODE, m.START_DATE AS RUN_DATE, m.PREFIX,
    b.STG_SEQUENCE_ID, bt.TFM_SEQUENCE_ID, b.SOURCE_ID,
    NVL(bt.EVENT_TYPE_NAME, b.EVENT_TYPE_NAME) AS EVENT_TYPE_NAME,
    NVL(bt.EVENT_DESC, b.EVENT_DESC) AS EVENT_DESC,
    NVL(bt.BILL_TRNS_AMOUNT, b.BILL_TRNS_AMOUNT) AS BILL_TRNS_AMOUNT,
    NVL(bt.CONTRACT_NUMBER, b.CONTRACT_NUMBER) AS CONTRACT_NUMBER,
    b.STATUS AS STG_STATUS,
    bt.STATUS AS TFM_STATUS,
    NVL(bt.STATUS, b.STATUS) AS OVERALL_STATUS,
    NVL(bt.STATUS, b.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(bt.ERROR_TEXT, b.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    b.STAGE_DATE, bt.RESULTS_UPDATED_DATE, NULL AS FUSION_LINK, b.SCENARIO_ID
FROM DMT_OWNER.DMT_PJB_BILL_EVENTS_STG_TBL b
    LEFT JOIN DMT_OWNER.DMT_PJB_BILL_EVENTS_TFM_TBL bt ON bt.STG_SEQUENCE_ID = b.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m ON m.INTEGRATION_ID = bt.INTEGRATION_ID
ORDER BY b.STAGE_DATE DESC, b.STG_SEQUENCE_ID DESC;
