-- DMT_CFG_LOOKUP_VALUES_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_CFG_LOOKUP_VALUES_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "LOOKUP_TYPE", "LOOKUP_CODE", "MEANING", "ENABLED_FLAG", "START_DATE_ACTIVE", "END_DATE_ACTIVE", "STAGE_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "ERROR_TEXT", "RESULTS_UPDATED_DATE", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    h.STG_SEQUENCE_ID,
    ht.TFM_SEQUENCE_ID,
    h.SOURCE_ID,
    NVL(ht.LOOKUP_TYPE, h.LOOKUP_TYPE) AS LOOKUP_TYPE,
    NVL(ht.LOOKUP_CODE, h.LOOKUP_CODE) AS LOOKUP_CODE,
    NVL(ht.MEANING, h.MEANING) AS MEANING,
    NVL(ht.ENABLED_FLAG, h.ENABLED_FLAG) AS ENABLED_FLAG,
    NVL(ht.START_DATE_ACTIVE, h.START_DATE_ACTIVE) AS START_DATE_ACTIVE,
    NVL(ht.END_DATE_ACTIVE, h.END_DATE_ACTIVE) AS END_DATE_ACTIVE,
    h.STAGE_DATE,
    h.STATUS AS STG_STATUS,
    ht.TFM_STATUS,
    NVL(ht.TFM_STATUS, h.STATUS) AS OVERALL_STATUS,
    DBMS_LOB.SUBSTR(NVL(ht.ERROR_TEXT, h.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ht.RESULTS_UPDATED_DATE,
    h.SCENARIO_ID
FROM
    DMT_OWNER.DMT_FND_LOOKUP_VALUE_STG_TBL h
    LEFT JOIN DMT_OWNER.DMT_FND_LOOKUP_VALUE_TFM_TBL ht
        ON ht.STG_SEQUENCE_ID = h.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ht.INTEGRATION_ID;
