-- DMT_CFG_UOM_V
-- Repaired 2026-07-15 (Stage F / APEX port): master joined to TFM on RUN_ID
-- (was INTEGRATION_ID, renamed in the rebuild); FORCE dropped now that it compiles.
CREATE OR REPLACE EDITIONABLE VIEW "DMT_CFG_UOM_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "UOM_CODE", "UNIT_OF_MEASURE", "UOM_CLASS", "DESCRIPTION", "BASE_UOM_FLAG", "STAGE_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "ERROR_TEXT", "RESULTS_UPDATED_DATE", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    h.STG_SEQUENCE_ID,
    ht.TFM_SEQUENCE_ID,
    h.SOURCE_ID,
    NVL(ht.UOM_CODE, h.UOM_CODE) AS UOM_CODE,
    NVL(ht.UNIT_OF_MEASURE, h.UNIT_OF_MEASURE) AS UNIT_OF_MEASURE,
    NVL(ht.UOM_CLASS, h.UOM_CLASS) AS UOM_CLASS,
    NVL(ht.DESCRIPTION, h.DESCRIPTION) AS DESCRIPTION,
    NVL(ht.BASE_UOM_FLAG, h.BASE_UOM_FLAG) AS BASE_UOM_FLAG,
    h.STAGE_DATE,
    h.STG_STATUS AS STG_STATUS,
    ht.TFM_STATUS,
    NVL(ht.TFM_STATUS, h.STG_STATUS) AS OVERALL_STATUS,
    DBMS_LOB.SUBSTR(NVL(ht.ERROR_TEXT, h.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ht.RESULTS_UPDATED_DATE,
    h.SCENARIO_ID
FROM
    DMT_OWNER.DMT_INV_UOM_STG_TBL h
    LEFT JOIN DMT_OWNER.DMT_INV_UOM_TFM_TBL ht
        ON ht.STG_SEQUENCE_ID = h.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ht.RUN_ID;
