-- DMT_BENEFITS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_BENEFITS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "PERSON_NUMBER", "PLAN_NAME", "OPTION_NAME", "ENROLLMENT_STATUS", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT m.INTEGRATION_ID, m.ORCHESTRATION_CODE, m.START_DATE AS RUN_DATE, m.PREFIX,
    b.STG_SEQUENCE_ID, bt.TFM_SEQUENCE_ID, b.SOURCE_ID,
    bt.PERSON_NUMBER,
    NVL(bt.PLAN_NAME, b.PLAN_NAME) AS PLAN_NAME,
    NVL(bt.OPTION_NAME, b.OPTION_NAME) AS OPTION_NAME,
    NVL(bt.ENROLLMENT_STATUS, b.ENROLLMENT_STATUS) AS ENROLLMENT_STATUS,
    b.STATUS AS STG_STATUS,
    bt.STATUS AS TFM_STATUS,
    NVL(bt.STATUS, b.STATUS) AS OVERALL_STATUS,
    NVL(bt.STATUS, b.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(bt.ERROR_TEXT, b.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    b.STAGE_DATE, bt.RESULTS_UPDATED_DATE, NULL AS FUSION_LINK, b.SCENARIO_ID
FROM DMT_OWNER.DMT_BEN_PARTIC_STG_TBL b
    LEFT JOIN DMT_OWNER.DMT_BEN_PARTIC_TFM_TBL bt ON bt.STG_SEQUENCE_ID = b.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m ON m.INTEGRATION_ID = bt.INTEGRATION_ID
ORDER BY b.STAGE_DATE DESC, b.STG_SEQUENCE_ID DESC;
