-- DMT_V_W2_BAL_DTL_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_W2_BAL_DTL_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "PERSON_NUMBER", "BALANCE_NAME", "DIMENSION_NAME", "CONTEXT_NAME", "CONTEXT_VALUE", "VALUE", "CURRENCY_CODE", "LEGISLATIVE_DATA_GROUP_NAME", "LEGAL_EMPLOYER_NAME", "PAYROLL_RELATIONSHIP_NUMBER", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.STATUS, stg.STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.PERSON_NUMBER                                       AS PERSON_NUMBER,
    stg.BALANCE_NAME,
    stg.DIMENSION_NAME,
    stg.CONTEXT_NAME,
    stg.CONTEXT_VALUE,
    stg.VALUE,
    stg.CURRENCY_CODE,
    stg.LEGISLATIVE_DATA_GROUP_NAME,
    stg.LEGAL_EMPLOYER_NAME,
    stg.PAYROLL_RELATIONSHIP_NUMBER,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    cm.PREFIX,
    stg.SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_W2_BAL_DTL_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_W2_BAL_DTL_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
