-- DMT_FA_ASSETS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_FA_ASSETS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "ASSET_NUMBER", "ASSET_DESCRIPTION", "ASSET_TYPE", "ASSET_COST", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    a.STG_SEQUENCE_ID,
    at.TFM_SEQUENCE_ID,
    a.SOURCE_ID,
    NVL(at.ASSET_NUMBER, a.ASSET_NUMBER) AS ASSET_NUMBER,
    NVL(at.DESCRIPTION, a.DESCRIPTION) AS ASSET_DESCRIPTION,
    NVL(at.ASSET_TYPE, a.ASSET_TYPE) AS ASSET_TYPE,
    -- ASSET_COST does not exist on FA header TFM; cost lives on the book TFM table
    NULL AS ASSET_COST,
    a.STATUS AS STG_STATUS,
    at.STATUS AS TFM_STATUS,
    NVL(at.STATUS, a.STATUS) AS OVERALL_STATUS,
    NVL(at.STATUS, a.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(at.ERROR_TEXT, a.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    a.STAGE_DATE,
    at.RESULTS_UPDATED_DATE,
    NULL AS FUSION_LINK,
    a.SCENARIO_ID
FROM
    DMT_OWNER.DMT_FA_ASSET_HDR_STG_TBL a
    LEFT JOIN DMT_OWNER.DMT_FA_ASSET_HDR_TFM_TBL at
        ON at.STG_SEQUENCE_ID = a.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = at.INTEGRATION_ID
ORDER BY
    a.STAGE_DATE DESC,
    a.STG_SEQUENCE_ID DESC;
