-- DMT_V_PERSON_NAME_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_PERSON_NAME_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "PERSON_NUMBER", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "LEGISLATION_CODE", "NAME_TYPE", "LAST_NAME", "FIRST_NAME", "MIDDLE_NAMES", "TITLE", "SUFFIX", "PRE_NAME_ADJUNCT", "KNOWN_AS", "DISPLAY_NAME", "ORDER_NAME", "LIST_NAME", "FULL_NAME", "NAME_INFORMATION1", "NAME_INFORMATION2", "NAME_INFORMATION3", "NAME_INFORMATION4", "NAME_INFORMATION5", "NAME_INFORMATION6", "NAME_INFORMATION7", "NAME_INFORMATION8", "NAME_INFORMATION9", "NAME_INFORMATION10", "NAME_INFORMATION11", "NAME_INFORMATION12", "NAME_INFORMATION13", "NAME_INFORMATION14", "NAME_INFORMATION15", "NAME_INFORMATION16", "NAME_INFORMATION17", "NAME_INFORMATION18", "NAME_INFORMATION19", "NAME_INFORMATION20", "NAME_INFORMATION21", "NAME_INFORMATION22", "NAME_INFORMATION23", "NAME_INFORMATION24", "NAME_INFORMATION25", "NAME_INFORMATION26", "NAME_INFORMATION27", "NAME_INFORMATION28", "NAME_INFORMATION29", "NAME_INFORMATION30", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.STATUS, stg.STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.STATUS, stg.STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.PERSON_NUMBER                                       AS PERSON_NUMBER,
    stg.EFFECTIVE_START_DATE,
    stg.EFFECTIVE_END_DATE,
    stg.LEGISLATION_CODE,
    stg.NAME_TYPE,
    stg.LAST_NAME,
    stg.FIRST_NAME,
    stg.MIDDLE_NAMES,
    stg.TITLE,
    stg.SUFFIX,
    stg.PRE_NAME_ADJUNCT,
    stg.KNOWN_AS,
    stg.DISPLAY_NAME,
    stg.ORDER_NAME,
    stg.LIST_NAME,
    stg.FULL_NAME,
    stg.NAME_INFORMATION1,
    stg.NAME_INFORMATION2,
    stg.NAME_INFORMATION3,
    stg.NAME_INFORMATION4,
    stg.NAME_INFORMATION5,
    stg.NAME_INFORMATION6,
    stg.NAME_INFORMATION7,
    stg.NAME_INFORMATION8,
    stg.NAME_INFORMATION9,
    stg.NAME_INFORMATION10,
    stg.NAME_INFORMATION11,
    stg.NAME_INFORMATION12,
    stg.NAME_INFORMATION13,
    stg.NAME_INFORMATION14,
    stg.NAME_INFORMATION15,
    stg.NAME_INFORMATION16,
    stg.NAME_INFORMATION17,
    stg.NAME_INFORMATION18,
    stg.NAME_INFORMATION19,
    stg.NAME_INFORMATION20,
    stg.NAME_INFORMATION21,
    stg.NAME_INFORMATION22,
    stg.NAME_INFORMATION23,
    stg.NAME_INFORMATION24,
    stg.NAME_INFORMATION25,
    stg.NAME_INFORMATION26,
    stg.NAME_INFORMATION27,
    stg.NAME_INFORMATION28,
    stg.NAME_INFORMATION29,
    stg.NAME_INFORMATION30,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    cm.PREFIX,
    stg.SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_PERSON_NAME_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_PERSON_NAME_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
