-- DMT_MST_BANKS_V
-- Repaired 2026-07-15 (Stage F / APEX port): master joined to TFM on RUN_ID
-- (was INTEGRATION_ID, renamed in the rebuild); FORCE dropped now that it compiles.
CREATE OR REPLACE EDITIONABLE VIEW "DMT_MST_BANKS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "BANK_NAME", "BANK_NUMBER", "COUNTRY_CODE", "SHORT_BANK_NAME", "DESCRIPTION", "STAGE_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "ERROR_TEXT", "RESULTS_UPDATED_DATE", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    h.STG_SEQUENCE_ID,
    ht.TFM_SEQUENCE_ID,
    h.SOURCE_ID,
    NVL(ht.BANK_NAME, h.BANK_NAME) AS BANK_NAME,
    NVL(ht.BANK_NUMBER, h.BANK_NUMBER) AS BANK_NUMBER,
    NVL(ht.COUNTRY_CODE, h.COUNTRY_CODE) AS COUNTRY_CODE,
    NVL(ht.SHORT_BANK_NAME, h.SHORT_BANK_NAME) AS SHORT_BANK_NAME,
    NVL(ht.DESCRIPTION, h.DESCRIPTION) AS DESCRIPTION,
    h.STAGE_DATE,
    h.STG_STATUS AS STG_STATUS,
    ht.TFM_STATUS,
    NVL(ht.TFM_STATUS, h.STG_STATUS) AS OVERALL_STATUS,
    DBMS_LOB.SUBSTR(NVL(ht.ERROR_TEXT, h.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ht.RESULTS_UPDATED_DATE,
    h.SCENARIO_ID
FROM
    DMT_OWNER.DMT_CE_BANK_STG_TBL h
    LEFT JOIN DMT_OWNER.DMT_CE_BANK_TFM_TBL ht
        ON ht.STG_SEQUENCE_ID = h.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ht.RUN_ID;
