-- DMT_ESS_JOB_FILES_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_ESS_JOB_FILES_V" ("ESS_FILE_ID", "ESS_JOB_ID", "REQUEST_ID", "JOB_SHORT_NAME", "FILE_TYPE", "FILE_NAME", "CONTENT_TYPE", "CREATED_DATE", "STATE_TEXT")  AS 
  SELECT
    ejf.ESS_FILE_ID,
    ejf.ESS_JOB_ID,
    ejf.REQUEST_ID,
    ej.JOB_SHORT_NAME,
    ejf.FILE_TYPE,
    ejf.FILE_NAME,
    ejf.CONTENT_TYPE,
    ejf.CREATED_DATE,
    ej.STATE_TEXT
FROM
    DMT_OWNER.DMT_ESS_JOB_FILE_TBL ejf
    LEFT JOIN DMT_OWNER.DMT_ESS_JOB_TBL ej
        ON ej.ESS_JOB_ID = ejf.ESS_JOB_ID
ORDER BY
    ejf.REQUEST_ID DESC,
    ejf.CREATED_DATE DESC;
