-- DMT_GL_BALANCES_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_GL_BALANCES_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "CODE_COMBINATION", "PERIOD_NAME", "PERIOD_YEAR", "ENTERED_DR", "ENTERED_CR", "NET_AMOUNT", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    g.STG_SEQUENCE_ID,
    gt.TFM_SEQUENCE_ID,
    g.SOURCE_ID,
    gt.SEGMENT1 || '.' || gt.SEGMENT2 || '.' || gt.SEGMENT3 || '.' || gt.SEGMENT4 || '.' || gt.SEGMENT5 AS CODE_COMBINATION,
    gt.PERIOD_NAME,
    -- PERIOD_YEAR does not exist on GL TFM; derived from ACCOUNTING_DATE
    EXTRACT(YEAR FROM gt.ACCOUNTING_DATE) AS PERIOD_YEAR,
    -- BEGINNING_BALANCE / TRANSACTION_BALANCE / ENDING_BALANCE do not exist on GL TFM
    gt.ENTERED_DR,
    gt.ENTERED_CR,
    (NVL(gt.ENTERED_DR, 0) - NVL(gt.ENTERED_CR, 0)) AS NET_AMOUNT,
    g.STATUS AS STG_STATUS,
    gt.TFM_STATUS AS TFM_STATUS,
    NVL(gt.TFM_STATUS, g.STATUS) AS OVERALL_STATUS,
    NVL(gt.TFM_STATUS, g.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(gt.ERROR_TEXT, g.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    g.STAGE_DATE,
    gt.RESULTS_UPDATED_DATE,
    NULL AS FUSION_LINK,
    g.SCENARIO_ID
FROM
    DMT_OWNER.DMT_GL_INTERFACE_STG_TBL g
    LEFT JOIN DMT_OWNER.DMT_GL_INTERFACE_TFM_TBL gt
        ON gt.STG_SEQUENCE_ID = g.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = gt.INTEGRATION_ID
ORDER BY
    g.STAGE_DATE DESC,
    g.STG_SEQUENCE_ID DESC;
