-- DMT_OBJECT_DETAIL_V
CREATE OR REPLACE EDITIONABLE VIEW "DMT_OBJECT_DETAIL_V" ("CEMLI_CODE", "SUB_OBJECT", "SUB_ORDER", "RUN_ID", "INTEGRATION_ID", "TOTAL_ROWS", "LOADED_ROWS", "FAILED_ROWS", "GENERATED_ROWS", "IN_PROGRESS_ROWS", "UNRECONCILED_ROWS", "PIPELINE_CODES", "SCENARIO_NAME", "PREFIX", "SUBMITTED_DATE", "COMPLETED_DATE", "RUN_STATUS", "LOAD_ESS_JOB_ID", "IMPORT_ESS_JOB_ID", "POSTRUN_ESS_JOB_ID")  AS 
  WITH sub_counts AS (
    -- ---- P2P: Suppliers ----
    -- UNRECONCILED_CNT: FAILED rows with no ERROR_TEXT (no positive/negative confirmation)
    SELECT 'Suppliers' AS CEMLI_CODE, 'Suppliers' AS SUB_OBJECT, 1 AS SUB_ORDER, RUN_ID, TFM_STATUS, COUNT(*) AS CNT,
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END) AS UNRECONCILED_CNT
    FROM DMT_OWNER.DMT_POZ_SUPPLIERS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'SupplierAddresses', 'Supplier Addresses', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_POZ_SUP_ADDR_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'SupplierSites', 'Supplier Sites', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_POZ_SUP_SITE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'SupplierSiteAssignments', 'Site Assignments', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_POZ_SUP_SITE_ASSN_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'SupplierContacts', 'Supplier Contacts', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_POZ_SUP_CONTACTS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    -- ---- P2P: Purchase Orders (multi-sub-object) ----
    UNION ALL
    SELECT 'PurchaseOrders', 'PO Headers', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL
    WHERE STYLE_DISPLAY_NAME = 'Purchase Order' OR STYLE_DISPLAY_NAME IS NULL
    GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'PurchaseOrders', 'PO Lines', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PO_LINES_INT_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'PurchaseOrders', 'PO Line Locations', 3, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PO_LINE_LOCS_INT_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'PurchaseOrders', 'PO Distributions', 4, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PO_DISTS_INT_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    -- ---- P2P: Blanket POs ----
    UNION ALL
    SELECT 'BlanketPOs', 'Blanket PO Headers', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL
    WHERE STYLE_DISPLAY_NAME = 'Blanket Purchase Agreement'
    GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'BlanketPOs', 'Blanket PO Lines', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PO_LINES_INT_TFM_TBL
    WHERE INTERFACE_HEADER_KEY IN (SELECT INTERFACE_HEADER_KEY FROM DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL WHERE STYLE_DISPLAY_NAME = 'Blanket Purchase Agreement')
    GROUP BY RUN_ID, TFM_STATUS
    -- ---- P2P: Contracts ----
    UNION ALL
    SELECT 'Contracts', 'Contract Headers', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL
    WHERE STYLE_DISPLAY_NAME = 'Contract Purchase Agreement'
    GROUP BY RUN_ID, TFM_STATUS
    -- ---- P2P: AP Invoices (all invoice types, incl. 1099 — 1099 is not a separate object) ----
    UNION ALL
    SELECT 'APInvoices', 'AP Invoice Headers', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_AP_INVOICES_INT_TFM_TBL
    GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'APInvoices', 'AP Invoice Lines', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_AP_INVOICE_LINES_INT_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    -- ---- O2C: Customers ----
    UNION ALL
    SELECT 'Customers', 'Parties', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_HZ_PARTIES_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Customers', 'Locations', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_HZ_LOCATIONS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Customers', 'Party Sites', 3, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_HZ_PARTY_SITES_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Customers', 'Party Site Uses', 4, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_HZ_PARTY_SITE_USES_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Customers', 'Accounts', 5, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_HZ_ACCOUNTS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Customers', 'Account Sites', 6, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_HZ_ACCT_SITES_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Customers', 'Account Site Uses', 7, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_HZ_ACCT_SITE_USES_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    -- ---- O2C: AR Invoices ----
    UNION ALL
    SELECT 'ARInvoices', 'AR Lines', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_RA_LINES_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'ARInvoices', 'AR Distributions', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_RA_DISTS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    -- ---- Financials ----
    UNION ALL
    SELECT 'GLBalances', 'GL Journals', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_GL_INTERFACE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'GLBudgets', 'GL Budget Lines', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_GL_BUDGET_INT_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'PlanningBudgets', 'Planning Budget Lines', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PLAN_BUDGET_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Assets', 'Asset Headers', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_FA_ASSET_HDR_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Assets', 'Asset Books', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_FA_ASSET_BOOK_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Assets', 'Asset Assignments', 3, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_FA_ASSET_ASSIGN_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    -- ---- Projects ----
    UNION ALL
    SELECT 'Projects', 'Projects', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PJF_PROJECTS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Projects', 'Project Tasks', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PJF_TASKS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Projects', 'Team Members', 3, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PJF_TEAM_MEMBERS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Projects', 'Txn Controls', 4, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PJC_TXN_CONTROLS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'ProjectBudgets', 'Project Budget Lines', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PRJ_BUDGET_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Expenditures', 'Project Expenditures', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PJC_EXPENDITURES_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'BillingEvents', 'Billing Events', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PJB_BILL_EVENTS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Grants', 'Award Headers', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_GMS_AWD_HEADERS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    -- ---- Standalone ----
    UNION ALL
    SELECT 'Requisitions', 'Req Headers', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_POR_REQ_HEADERS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Requisitions', 'Req Lines', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_POR_REQ_LINES_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Requisitions', 'Req Distributions', 3, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_POR_REQ_DISTS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'MiscReceipts', 'Receipt Headers', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_RCV_HEADERS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'MiscReceipts', 'Receipt Transactions', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_RCV_TRANSACTIONS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    -- ---- HCM ----
    UNION ALL
    SELECT 'Workers', 'Workers', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_WORKER_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Workers', 'Person Names', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PERSON_NAME_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Workers', 'Person Emails', 3, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PERSON_EMAIL_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Workers', 'Person Phones', 4, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PERSON_PHONE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Workers', 'Person Addresses', 5, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PERSON_ADDR_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Workers', 'Person NIDs', 6, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PERSON_NID_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Workers', 'Person Legislation', 7, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PERSON_LEGISL_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Workers', 'Work Relationships', 8, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_WORK_REL_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Assignments', 'Assignments', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_ASSIGNMENT_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Salaries', 'Salaries', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_SALARY_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'SalaryBases', 'Salary Bases', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_SAL_BASIS_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'PayrollRelationships', 'Payroll Relationships', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PAY_REL_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'TaxCards', 'Tax Cards', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_TAX_CARD_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'TaxCards', 'Tax Card Components', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_TAX_CARD_COMP_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'W2Balances', 'W2 Balances', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_W2_BAL_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'W2Balances', 'W2 Balance Details', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_W2_BAL_DTL_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'BenParticipant', 'Participant Enrollment', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_BEN_PARTIC_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'BenDependent', 'Dependent Enrollment', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_BEN_DEPEND_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'BenBeneficiary', 'Beneficiary Enrollment', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_BEN_BENFY_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Absences', 'Absences', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_ABSENCE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'TalentProfiles', 'Talent Profiles', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_TALENT_PROF_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'TalentProfiles', 'Profile Items', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_TALENT_PROF_ITEM_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'PerfEvaluations', 'Performance Docs', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PERF_EVAL_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'PerfEvaluations', 'Performance Ratings', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_PERF_EVAL_RATING_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'WorkSchedules', 'Work Schedules', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_WORK_SCHED_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'WorkSchedules', 'Schedule Details', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_WORK_SCHED_DTL_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    -- ---- Configuration ----
    UNION ALL
    SELECT 'GLCalendar', 'GL Calendar', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_GL_CALENDAR_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'ValueSets', 'Value Sets', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_FND_VS_SET_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'ValueSets', 'Value Set Values', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_FND_VS_VALUE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Lookups', 'Lookup Types', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_FND_LOOKUP_TYPE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Lookups', 'Lookup Values', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_FND_LOOKUP_VALUE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'UnitsOfMeasure', 'Units of Measure', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_INV_UOM_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'PaymentTerms', 'Payment Term Headers', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_AP_PAY_TERM_HDR_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'PaymentTerms', 'Payment Term Lines', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_AP_PAY_TERM_LINE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'TaxConfig', 'Tax Regimes', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_ZX_REGIME_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'TaxConfig', 'Tax Rates', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_ZX_RATE_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    -- ---- Master Data ----
    UNION ALL
    SELECT 'Items', 'Item Master', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_EGP_ITEM_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    -- Categories bundle into the Items FBDI ZIP — show them as a sub-object of the Items
    -- card (SUB_ORDER 2, after 'Item Master'), mirroring PO header/line/distribution sub-rows.
    SELECT 'Items', 'Item Categories', 2, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_EGP_ITEM_CAT_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Banks', 'Banks', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_CE_BANK_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Banks', 'Bank Branches', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_CE_BRANCH_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
    UNION ALL
    SELECT 'Banks', 'Bank Accounts', 1, RUN_ID, TFM_STATUS, COUNT(*),
           SUM(CASE WHEN TFM_STATUS = 'FAILED' AND ERROR_TEXT IS NULL THEN 1 ELSE 0 END)
    FROM DMT_OWNER.DMT_CE_BANK_ACCT_TFM_TBL GROUP BY RUN_ID, TFM_STATUS
)
SELECT
    sc.CEMLI_CODE,
    sc.SUB_OBJECT,
    sc.SUB_ORDER,
    sc.RUN_ID,
    sc.RUN_ID                                                          AS INTEGRATION_ID,
    SUM(sc.CNT)                                                    AS TOTAL_ROWS,
    SUM(CASE WHEN sc.TFM_STATUS = 'LOADED'    THEN sc.CNT ELSE 0 END) AS LOADED_ROWS,
    SUM(CASE WHEN sc.TFM_STATUS = 'FAILED'    THEN sc.CNT ELSE 0 END) AS FAILED_ROWS,
    SUM(CASE WHEN sc.TFM_STATUS = 'GENERATED' THEN sc.CNT ELSE 0 END) AS GENERATED_ROWS,
    SUM(CASE WHEN sc.TFM_STATUS NOT IN ('LOADED','FAILED','GENERATED')
                                          THEN sc.CNT ELSE 0 END) AS IN_PROGRESS_ROWS,
    SUM(NVL(sc.UNRECONCILED_CNT, 0))                              AS UNRECONCILED_ROWS,
    -- Master context
    m.PIPELINE_CODES,
    m.SCENARIO_NAME,
    m.PREFIX,
    m.SUBMITTED_DATE,
    m.COMPLETED_DATE,
    m.RUN_STATUS,
    -- ESS job IDs (from work queue — pre-aggregated to ONE row per run+cemli).
    -- Must be aggregated, NOT a raw join: an object retried within a run has
    -- multiple work-queue rows, and a raw join would fan out SUM(sc.CNT) by that
    -- multiplicity (the Assets "counts doubled" bug — Assets had 2 queue rows).
    q.LOAD_ESS_JOB_ID,
    q.IMPORT_ESS_JOB_ID,
    q.POSTRUN_ESS_JOB_ID
FROM
    sub_counts sc
JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL m
    ON  m.RUN_ID = sc.RUN_ID
LEFT JOIN (
    SELECT RUN_ID, CEMLI_CODE,
           MAX(LOAD_ESS_JOB_ID)    AS LOAD_ESS_JOB_ID,
           MAX(IMPORT_ESS_JOB_ID)  AS IMPORT_ESS_JOB_ID,
           MAX(POSTRUN_ESS_JOB_ID) AS POSTRUN_ESS_JOB_ID
    FROM   DMT_OWNER.DMT_WORK_QUEUE_TBL
    GROUP BY RUN_ID, CEMLI_CODE
) q
    ON  q.RUN_ID = sc.RUN_ID
    AND q.CEMLI_CODE     = sc.CEMLI_CODE
GROUP BY
    sc.CEMLI_CODE, sc.SUB_OBJECT, sc.SUB_ORDER, sc.RUN_ID,
    m.PIPELINE_CODES, m.SCENARIO_NAME,
    m.PREFIX, m.SUBMITTED_DATE, m.COMPLETED_DATE, m.RUN_STATUS,
    q.LOAD_ESS_JOB_ID, q.IMPORT_ESS_JOB_ID, q.POSTRUN_ESS_JOB_ID
ORDER BY
    sc.RUN_ID DESC,
    sc.CEMLI_CODE,
    sc.SUB_ORDER;
