-- DMT_P2P_PO_HEADERS_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_P2P_PO_HEADERS_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "PO_NUMBER", "PO_TYPE", "VENDOR_NAME", "AMOUNT", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "FUSION_PO_HEADER_ID", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    h.STG_SEQUENCE_ID,
    ht.TFM_SEQUENCE_ID,
    h.SOURCE_ID,
    NVL(ht.DOCUMENT_NUM, h.DOCUMENT_NUM) AS PO_NUMBER,
    NVL(ht.DOCUMENT_TYPE_CODE, h.DOCUMENT_TYPE_CODE) AS PO_TYPE,
    NVL(ht.VENDOR_NAME, h.VENDOR_NAME) AS VENDOR_NAME,
    NULL AS AMOUNT,
    h.STATUS AS STG_STATUS,
    ht.STATUS AS TFM_STATUS,
    NVL(ht.STATUS, h.STATUS) AS OVERALL_STATUS,
    NVL(ht.STATUS, h.STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(ht.ERROR_TEXT, h.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ht.FUSION_PO_HEADER_ID,
    h.STAGE_DATE,
    ht.RESULTS_UPDATED_DATE,
    DMT_UTIL_PKG.GET_DEEP_LINK('PurchaseOrders', ht.FUSION_PO_HEADER_ID) AS FUSION_LINK,
    h.SCENARIO_ID
FROM
    DMT_OWNER.DMT_PO_HEADERS_INT_STG_TBL h
    LEFT JOIN DMT_OWNER.DMT_PO_HEADERS_INT_TFM_TBL ht
        ON ht.STG_SEQUENCE_ID = h.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ht.INTEGRATION_ID
ORDER BY
    h.STAGE_DATE DESC,
    h.STG_SEQUENCE_ID DESC;
