-- DMT_V_TALENT_PROF_ITEM_DETAIL
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_V_TALENT_PROF_ITEM_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "PERSON_NUMBER", "CONTENT_TYPE_NAME", "CONTENT_ITEM_NAME", "DATE_FROM", "DATE_TO", "RATING", "PROFILE_CODE", "INTEREST_LEVEL", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.PERSON_NUMBER                                       AS PERSON_NUMBER,
    stg.CONTENT_TYPE_NAME,
    stg.CONTENT_ITEM_NAME,
    stg.DATE_FROM,
    stg.DATE_TO,
    stg.RATING,
    stg.PROFILE_CODE,
    stg.INTEREST_LEVEL,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID                                              AS INTEGRATION_ID,
    cm.PREFIX,
    stg.SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_TALENT_PROF_ITEM_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_TALENT_PROF_ITEM_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
