-- DMT_V_ASSET_HDR_DETAIL
CREATE OR REPLACE EDITIONABLE VIEW "DMT_V_ASSET_HDR_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "ASSET_NUMBER", "DESCRIPTION", "ASSET_CATEGORY_SEGMENT1", "ASSET_CATEGORY_SEGMENT2", "ASSET_CATEGORY_SEGMENT3", "ASSET_CATEGORY_SEGMENT4", "ASSET_CATEGORY_SEGMENT5", "ASSET_CATEGORY_SEGMENT6", "ASSET_CATEGORY_SEGMENT7", "ASSET_TYPE", "MANUFACTURER_NAME", "SERIAL_NUMBER", "TAG_NUMBER", "MODEL_NUMBER", "PROPERTY_TYPE_CODE", "PROPERTY_1245_1250_CODE", "IN_USE_FLAG", "OWNED_LEASED", "NEW_USED", "DATE_PLACED_IN_SERVICE", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "PARENT_ASSET_NUMBER", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "INTEGRATION_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    stg.ASSET_NUMBER                                        AS ASSET_NUMBER,
    stg.DESCRIPTION                                         AS DESCRIPTION,
    stg.ASSET_CATEGORY_SEGMENT1,
    stg.ASSET_CATEGORY_SEGMENT2,
    stg.ASSET_CATEGORY_SEGMENT3,
    stg.ASSET_CATEGORY_SEGMENT4,
    stg.ASSET_CATEGORY_SEGMENT5,
    stg.ASSET_CATEGORY_SEGMENT6,
    stg.ASSET_CATEGORY_SEGMENT7,
    stg.ASSET_TYPE,
    stg.MANUFACTURER_NAME,
    stg.SERIAL_NUMBER,
    stg.TAG_NUMBER,
    stg.MODEL_NUMBER,
    stg.PROPERTY_TYPE_CODE,
    stg.PROPERTY_1245_1250_CODE,
    stg.IN_USE_FLAG,
    stg.OWNED_LEASED,
    stg.NEW_USED,
    stg.DATE_PLACED_IN_SERVICE,
    stg.ATTRIBUTE_CATEGORY,
    stg.ATTRIBUTE1,
    stg.ATTRIBUTE2,
    stg.ATTRIBUTE3,
    stg.ATTRIBUTE4,
    stg.ATTRIBUTE5,
    stg.ATTRIBUTE6,
    stg.ATTRIBUTE7,
    stg.ATTRIBUTE8,
    stg.ATTRIBUTE9,
    stg.ATTRIBUTE10,
    stg.ATTRIBUTE11,
    stg.ATTRIBUTE12,
    stg.ATTRIBUTE13,
    stg.ATTRIBUTE14,
    stg.ATTRIBUTE15,
    stg.PARENT_ASSET_NUMBER,
    stg.SOURCE_ID,
    stg.STG_SEQUENCE_ID,
    tfm.RUN_ID,
    tfm.RUN_ID AS INTEGRATION_ID,
    cm.PREFIX,
    stg.SCENARIO_ID,
    stg.STAGE_DATE,
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_FA_ASSET_HDR_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_FA_ASSET_HDR_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
