-- DMT_GL_BUDGET_V
-- Repaired 2026-07-15 (Stage F / APEX port): master joined to TFM on RUN_ID
-- (was INTEGRATION_ID, renamed in the rebuild); FORCE dropped now that it compiles.
CREATE OR REPLACE EDITIONABLE VIEW "DMT_GL_BUDGET_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "BUDGET_NAME", "BUDGET_ENTITY_NAME", "CODE_COMBINATION", "PERIOD_NAME", "BUDGET_AMOUNT", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "TRANSFORMATION_STATUS", "ERROR_TEXT", "STAGE_DATE", "RESULTS_UPDATED_DATE", "FUSION_LINK", "SCENARIO_ID")  AS 
  SELECT m.INTEGRATION_ID, m.ORCHESTRATION_CODE, m.START_DATE AS RUN_DATE, m.PREFIX,
    g.STG_SEQUENCE_ID, gt.TFM_SEQUENCE_ID, g.SOURCE_ID,
    gt.BUDGET_NAME, g.BUDGET_ENTITY_NAME,
    gt.SEGMENT1 || chr(46) || gt.SEGMENT2 || chr(46) || gt.SEGMENT3 || chr(46) || gt.SEGMENT4 || chr(46) || gt.SEGMENT5 AS CODE_COMBINATION,
    gt.PERIOD_NAME, gt.BUDGET_AMOUNT,
    g.STG_STATUS AS STG_STATUS,
    gt.TFM_STATUS AS TFM_STATUS,
    NVL(gt.TFM_STATUS, g.STG_STATUS) AS OVERALL_STATUS,
    NVL(gt.TFM_STATUS, g.STG_STATUS) AS TRANSFORMATION_STATUS,
    DBMS_LOB.SUBSTR(NVL(gt.ERROR_TEXT, g.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    g.STAGE_DATE, gt.RESULTS_UPDATED_DATE, NULL AS FUSION_LINK, g.SCENARIO_ID
FROM DMT_OWNER.DMT_GL_BUDGET_INT_STG_TBL g
    LEFT JOIN DMT_OWNER.DMT_GL_BUDGET_INT_TFM_TBL gt ON gt.STG_SEQUENCE_ID = g.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m ON m.INTEGRATION_ID = gt.RUN_ID
ORDER BY g.STAGE_DATE DESC, g.STG_SEQUENCE_ID DESC;
