-- DMT_DASHBOARD_CEMLI_SUMMARY_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_DASHBOARD_CEMLI_SUMMARY_V" ("OBJECT_CODE", "TOTAL_ROWS", "NEW_ROWS", "TRANSFORMED_ROWS", "LOADED_ROWS", "FAILED_ROWS", "OTHER_ROWS", "SUCCESS_RATE_PCT")  AS 
  SELECT
    v.OBJECT_CODE,
    COUNT(*)                                                                AS TOTAL_ROWS,
    SUM(CASE WHEN v.STATUS = 'NEW'         THEN 1 ELSE 0 END)             AS NEW_ROWS,
    SUM(CASE WHEN v.STATUS = 'TRANSFORMED' THEN 1 ELSE 0 END)             AS TRANSFORMED_ROWS,
    SUM(CASE WHEN v.STATUS = 'LOADED'      THEN 1 ELSE 0 END)             AS LOADED_ROWS,
    SUM(CASE WHEN v.STATUS = 'FAILED'      THEN 1 ELSE 0 END)             AS FAILED_ROWS,
    SUM(CASE WHEN v.STATUS NOT IN ('NEW','TRANSFORMED','LOADED','FAILED')
                  THEN 1 ELSE 0 END)                                       AS OTHER_ROWS,
    ROUND(CASE WHEN COUNT(*) > 0
        THEN SUM(CASE WHEN v.STATUS = 'LOADED' THEN 1 ELSE 0 END) / COUNT(*) * 100
        ELSE NULL END, 2)                                                  AS SUCCESS_RATE_PCT
FROM
    DMT_OWNER.DMT_SCENARIO_SUMMARY_V v
GROUP BY
    v.OBJECT_CODE
ORDER BY
    v.OBJECT_CODE;
