-- DMT_V_AR_DISTS_DETAIL
CREATE OR REPLACE EDITIONABLE VIEW "DMT_V_AR_DISTS_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "ACCOUNT_CLASS", "ORG_ID", "AMOUNT", "PERCENT", "ACCTD_AMOUNT", "INTERFACE_LINE_CONTEXT", "INTERFACE_LINE_ATTRIBUTE1", "INTERFACE_LINE_ATTRIBUTE2", "INTERFACE_LINE_ATTRIBUTE3", "INTERFACE_LINE_ATTRIBUTE4", "INTERFACE_LINE_ATTRIBUTE5", "INTERFACE_LINE_ATTRIBUTE6", "INTERFACE_LINE_ATTRIBUTE7", "INTERFACE_LINE_ATTRIBUTE8", "INTERFACE_LINE_ATTRIBUTE9", "INTERFACE_LINE_ATTRIBUTE10", "INTERFACE_LINE_ATTRIBUTE11", "INTERFACE_LINE_ATTRIBUTE12", "INTERFACE_LINE_ATTRIBUTE13", "INTERFACE_LINE_ATTRIBUTE14", "INTERFACE_LINE_ATTRIBUTE15", "SEGMENT1", "SEGMENT2", "SEGMENT3", "SEGMENT4", "SEGMENT5", "SEGMENT6", "SEGMENT7", "SEGMENT8", "SEGMENT9", "SEGMENT10", "SEGMENT11", "SEGMENT12", "SEGMENT13", "SEGMENT14", "SEGMENT15", "SEGMENT16", "SEGMENT17", "SEGMENT18", "SEGMENT19", "SEGMENT20", "SEGMENT21", "SEGMENT22", "SEGMENT23", "SEGMENT24", "SEGMENT25", "SEGMENT26", "SEGMENT27", "SEGMENT28", "SEGMENT29", "SEGMENT30", "COMMENTS", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "BU_NAME", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    -- 1. Run status
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    -- 2. Error text
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    -- 3. Human identifier
    stg.ACCOUNT_CLASS                                       AS ACCOUNT_CLASS,
    -- 4. All remaining STG business columns
    stg.ORG_ID,
    stg.AMOUNT,
    stg.PERCENT,
    stg.ACCTD_AMOUNT,
    stg.INTERFACE_LINE_CONTEXT,
    stg.INTERFACE_LINE_ATTRIBUTE1,
    stg.INTERFACE_LINE_ATTRIBUTE2,
    stg.INTERFACE_LINE_ATTRIBUTE3,
    stg.INTERFACE_LINE_ATTRIBUTE4,
    stg.INTERFACE_LINE_ATTRIBUTE5,
    stg.INTERFACE_LINE_ATTRIBUTE6,
    stg.INTERFACE_LINE_ATTRIBUTE7,
    stg.INTERFACE_LINE_ATTRIBUTE8,
    stg.INTERFACE_LINE_ATTRIBUTE9,
    stg.INTERFACE_LINE_ATTRIBUTE10,
    stg.INTERFACE_LINE_ATTRIBUTE11,
    stg.INTERFACE_LINE_ATTRIBUTE12,
    stg.INTERFACE_LINE_ATTRIBUTE13,
    stg.INTERFACE_LINE_ATTRIBUTE14,
    stg.INTERFACE_LINE_ATTRIBUTE15,
    stg.SEGMENT1,
    stg.SEGMENT2,
    stg.SEGMENT3,
    stg.SEGMENT4,
    stg.SEGMENT5,
    stg.SEGMENT6,
    stg.SEGMENT7,
    stg.SEGMENT8,
    stg.SEGMENT9,
    stg.SEGMENT10,
    stg.SEGMENT11,
    stg.SEGMENT12,
    stg.SEGMENT13,
    stg.SEGMENT14,
    stg.SEGMENT15,
    stg.SEGMENT16,
    stg.SEGMENT17,
    stg.SEGMENT18,
    stg.SEGMENT19,
    stg.SEGMENT20,
    stg.SEGMENT21,
    stg.SEGMENT22,
    stg.SEGMENT23,
    stg.SEGMENT24,
    stg.SEGMENT25,
    stg.SEGMENT26,
    stg.SEGMENT27,
    stg.SEGMENT28,
    stg.SEGMENT29,
    stg.SEGMENT30,
    stg.COMMENTS,
    stg.ATTRIBUTE_CATEGORY,
    stg.ATTRIBUTE1,
    stg.ATTRIBUTE2,
    stg.ATTRIBUTE3,
    stg.ATTRIBUTE4,
    stg.ATTRIBUTE5,
    stg.ATTRIBUTE6,
    stg.ATTRIBUTE7,
    stg.ATTRIBUTE8,
    stg.ATTRIBUTE9,
    stg.ATTRIBUTE10,
    stg.ATTRIBUTE11,
    stg.ATTRIBUTE12,
    stg.ATTRIBUTE13,
    stg.ATTRIBUTE14,
    stg.ATTRIBUTE15,
    stg.BU_NAME,
    stg.SOURCE_ID,
    -- 5. STG_SEQUENCE_ID
    stg.STG_SEQUENCE_ID,
    -- 6. RUN_ID
    tfm.RUN_ID,
    -- 7. PREFIX (from PIPELINE_RUN)
    cm.PREFIX,
    -- 8. SCENARIO_ID
    stg.SCENARIO_ID,
    -- 9. STAGE_DATE
    stg.STAGE_DATE,
    -- 10. LAST_UPDATED_DATE
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_RA_DISTS_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_RA_DISTS_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
