-- DMT_CFG_TAX_REGIMES_V
CREATE OR REPLACE FORCE EDITIONABLE VIEW "DMT_CFG_TAX_REGIMES_V" ("INTEGRATION_ID", "ORCHESTRATION_CODE", "RUN_DATE", "PREFIX", "STG_SEQUENCE_ID", "TFM_SEQUENCE_ID", "SOURCE_ID", "TAX_REGIME_CODE", "TAX_REGIME_NAME", "COUNTRY_CODE", "EFFECTIVE_FROM", "EFFECTIVE_TO", "STAGE_DATE", "STG_STATUS", "TFM_STATUS", "OVERALL_STATUS", "ERROR_TEXT", "RESULTS_UPDATED_DATE", "SCENARIO_ID")  AS 
  SELECT
    m.INTEGRATION_ID,
    m.ORCHESTRATION_CODE,
    m.START_DATE AS RUN_DATE,
    m.PREFIX,
    h.STG_SEQUENCE_ID,
    ht.TFM_SEQUENCE_ID,
    h.SOURCE_ID,
    NVL(ht.TAX_REGIME_CODE, h.TAX_REGIME_CODE) AS TAX_REGIME_CODE,
    NVL(ht.TAX_REGIME_NAME, h.TAX_REGIME_NAME) AS TAX_REGIME_NAME,
    NVL(ht.COUNTRY_CODE, h.COUNTRY_CODE) AS COUNTRY_CODE,
    NVL(ht.EFFECTIVE_FROM, h.EFFECTIVE_FROM) AS EFFECTIVE_FROM,
    NVL(ht.EFFECTIVE_TO, h.EFFECTIVE_TO) AS EFFECTIVE_TO,
    h.STAGE_DATE,
    h.STATUS AS STG_STATUS,
    ht.TFM_STATUS,
    NVL(ht.TFM_STATUS, h.STATUS) AS OVERALL_STATUS,
    DBMS_LOB.SUBSTR(NVL(ht.ERROR_TEXT, h.ERROR_TEXT), 1000, 1) AS ERROR_TEXT,
    ht.RESULTS_UPDATED_DATE,
    h.SCENARIO_ID
FROM
    DMT_OWNER.DMT_ZX_REGIME_STG_TBL h
    LEFT JOIN DMT_OWNER.DMT_ZX_REGIME_TFM_TBL ht
        ON ht.STG_SEQUENCE_ID = h.STG_SEQUENCE_ID
    LEFT JOIN DMT_OWNER.DMT_CONVERSION_MASTER_TBL m
        ON m.INTEGRATION_ID = ht.INTEGRATION_ID;
