-- DMT_V_CUST_ACCT_SITE_USES_DETAIL
CREATE OR REPLACE EDITIONABLE VIEW "DMT_V_CUST_ACCT_SITE_USES_DETAIL" ("RUN_STATUS", "ERROR_TEXT", "RECONCILIATION_STATUS", "CUST_SITE_ORIG_SYS_REF", "SITE_USE_CODE", "BATCH_ID", "CUST_SITE_ORIG_SYSTEM", "CUST_SITEUSE_ORIG_SYSTEM", "CUST_SITEUSE_ORIG_SYS_REF", "PRIMARY_FLAG", "INSERT_UPDATE_FLAG", "LOCATION", "SET_CODE", "START_DATE", "END_DATE", "ACCOUNT_NUMBER", "PARTY_SITE_NUMBER", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "ATTRIBUTE16", "ATTRIBUTE17", "ATTRIBUTE18", "ATTRIBUTE19", "ATTRIBUTE20", "SOURCE_ID", "STG_SEQUENCE_ID", "RUN_ID", "PREFIX", "SCENARIO_ID", "STAGE_DATE", "LAST_UPDATED_DATE")  AS 
  SELECT
    -- 1. Run status
    NVL(tfm.TFM_STATUS, stg.STG_STATUS)                             AS RUN_STATUS,
    -- 2. Error text
    tfm.ERROR_TEXT                                           AS ERROR_TEXT,
    CASE
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'LOADED' THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NOT NULL THEN 'CONFIRMED'
        WHEN NVL(tfm.TFM_STATUS, stg.STG_STATUS) = 'FAILED' AND tfm.ERROR_TEXT IS NULL THEN 'UNRECONCILED'
        ELSE 'IN_PROGRESS'
    END                                                      AS RECONCILIATION_STATUS,
    -- 3. Human identifiers
    stg.CUST_SITE_ORIG_SYS_REF                               AS CUST_SITE_ORIG_SYS_REF,
    stg.SITE_USE_CODE                                        AS SITE_USE_CODE,
    -- 4. All remaining STG business columns
    stg.BATCH_ID,
    stg.CUST_SITE_ORIG_SYSTEM,
    stg.CUST_SITEUSE_ORIG_SYSTEM,
    stg.CUST_SITEUSE_ORIG_SYS_REF,
    stg.PRIMARY_FLAG,
    stg.INSERT_UPDATE_FLAG,
    stg.LOCATION,
    stg.SET_CODE,
    stg.START_DATE,
    stg.END_DATE,
    stg.ACCOUNT_NUMBER,
    stg.PARTY_SITE_NUMBER,
    stg.ATTRIBUTE_CATEGORY,
    stg.ATTRIBUTE1,
    stg.ATTRIBUTE2,
    stg.ATTRIBUTE3,
    stg.ATTRIBUTE4,
    stg.ATTRIBUTE5,
    stg.ATTRIBUTE6,
    stg.ATTRIBUTE7,
    stg.ATTRIBUTE8,
    stg.ATTRIBUTE9,
    stg.ATTRIBUTE10,
    stg.ATTRIBUTE11,
    stg.ATTRIBUTE12,
    stg.ATTRIBUTE13,
    stg.ATTRIBUTE14,
    stg.ATTRIBUTE15,
    stg.ATTRIBUTE16,
    stg.ATTRIBUTE17,
    stg.ATTRIBUTE18,
    stg.ATTRIBUTE19,
    stg.ATTRIBUTE20,
    stg.SOURCE_ID,
    -- 5. STG_SEQUENCE_ID
    stg.STG_SEQUENCE_ID,
    -- 6. RUN_ID
    tfm.RUN_ID,
    -- 7. PREFIX (from PIPELINE_RUN)
    cm.PREFIX,
    -- 8. SCENARIO_ID (not on customer STG tables)
    CAST(NULL AS NUMBER)                                     AS SCENARIO_ID,
    -- 9. STAGE_DATE
    stg.STAGE_DATE,
    -- 10. LAST_UPDATED_DATE
    NVL(tfm.LAST_UPDATED_DATE, stg.LAST_UPDATED_DATE)      AS LAST_UPDATED_DATE
FROM DMT_OWNER.DMT_HZ_ACCT_SITE_USES_STG_TBL stg
LEFT JOIN (
    SELECT t.*,
           ROW_NUMBER() OVER (PARTITION BY t.STG_SEQUENCE_ID
                              ORDER BY t.TFM_SEQUENCE_ID DESC) AS rn
    FROM   DMT_OWNER.DMT_HZ_ACCT_SITE_USES_TFM_TBL t
) tfm ON tfm.STG_SEQUENCE_ID = stg.STG_SEQUENCE_ID AND tfm.rn = 1
LEFT JOIN DMT_OWNER.DMT_PIPELINE_RUN_TBL cm
    ON cm.RUN_ID = tfm.RUN_ID;
