-- PROCEDURE DMT_SUBMIT_TEST

  CREATE OR REPLACE EDITIONABLE PROCEDURE "DMT_SUBMIT_TEST" (x_run_id OUT NUMBER) AS
BEGIN
    INSERT INTO DMT_PIPELINE_RUN_TBL (PIPELINE_CODES, RUN_TYPE, CEMLI_SEQUENCE, RUN_MODE, PREFIX)
    VALUES ('TEST', 'PIPELINE', 'X', 'NEW', '0000') RETURNING RUN_ID INTO x_run_id;
    COMMIT;
END;
/
