-- PROCEDURE DMT_SUBMIT_SIMPLE

  CREATE OR REPLACE EDITIONABLE PROCEDURE "DMT_SUBMIT_SIMPLE" (
    p_cemli IN VARCHAR2, p_by IN VARCHAR2, x_run_id OUT NUMBER
) AS
    l_prefix VARCHAR2(20);
BEGIN
    SELECT TO_CHAR(DMT_RUN_PREFIX_SEQ.NEXTVAL) INTO l_prefix FROM DUAL;
    INSERT INTO DMT_PIPELINE_RUN_TBL (PIPELINE_CODES, RUN_TYPE, SUBMITTED_BY,
        CEMLI_SEQUENCE, RUN_MODE, PREFIX, ON_FAILURE_POLICY)
    VALUES ('STANDALONE:' || p_cemli, 'PIPELINE', p_by,
        p_cemli, 'NEW', l_prefix, 'HALT')
    RETURNING RUN_ID INTO x_run_id;
    INSERT INTO DMT_WORK_QUEUE_TBL (RUN_ID, PIPELINE, CEMLI_CODE, SORT_ORDER, WORK_STATUS)
    VALUES (x_run_id, 'STANDALONE', p_cemli, 1, 'READY');
    COMMIT;
END;
/
