-- PACKAGE BODY DMT_MISC_RECEIPT_TRANSFORM_PKG

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "DMT_MISC_RECEIPT_TRANSFORM_PKG" AS
-- ============================================================
-- DMT_MISC_RECEIPT_TRANSFORM_PKG Body
-- Inventory Transactions (On Hand Qty) per MCCS RICE_011/012
-- ============================================================

    C_PKG CONSTANT VARCHAR2(50) := 'DMT_MISC_RECEIPT_TRANSFORM_PKG';

    FUNCTION get_prefix (p_run_id IN NUMBER) RETURN VARCHAR2 IS
        l_prefix VARCHAR2(30);
    BEGIN
        SELECT PREFIX
        INTO   l_prefix
        FROM   DMT_OWNER.DMT_PIPELINE_RUN_TBL
        WHERE  RUN_ID = p_run_id;
        RETURN l_prefix;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20001,
                'RUN_ID ' || p_run_id || ' not found in DMT_PIPELINE_RUN_TBL');
    END get_prefix;

    PROCEDURE TRANSFORM (
        p_run_id   IN NUMBER,
        p_reprocess_errors IN BOOLEAN DEFAULT FALSE,
        p_scenario_id      IN NUMBER DEFAULT NULL,
        p_include_untagged IN VARCHAR2 DEFAULT 'N',
        p_run_mode         IN VARCHAR2 DEFAULT 'NEW'
    ) IS
        C_PROC       CONSTANT VARCHAR2(30) := 'TRANSFORM';
        l_prefix     VARCHAR2(30);
        l_ok_count   NUMBER := 0;
        l_lot_count  NUMBER := 0;
        l_ser_count  NUMBER := 0;
    BEGIN
        l_prefix := get_prefix(p_run_id);

        DMT_UTIL_PKG.LOG(
            p_run_id => p_run_id,
            p_message        => 'TRANSFORM start. prefix=' || l_prefix,
            p_package        => C_PKG,
            p_procedure      => C_PROC);

        IF p_reprocess_errors THEN
            UPDATE DMT_OWNER.DMT_INV_TRX_STG_TBL
            SET    ERROR_TEXT = NULL, LAST_UPDATED_DATE = SYSDATE
            WHERE  STG_STATUS IN ('FAILED', 'TRANSFORM_FAILED');
        END IF;

        -- ── Main transactions: STG → TFM ──
        INSERT INTO DMT_OWNER.DMT_INV_TRX_TFM_TBL (
            STG_SEQUENCE_ID, RUN_ID,
            -- Organization & Item (no prefix on ITEM_NUMBER — items already exist in Fusion)
            ORGANIZATION_NAME, ITEM_NUMBER, REVISION,
            SUBINVENTORY_CODE, LOCATOR_NAME,
            LOC_SEGMENT1, LOC_SEGMENT2, LOC_SEGMENT3, LOC_SEGMENT4, LOC_SEGMENT5,
            LOC_SEGMENT6, LOC_SEGMENT7, LOC_SEGMENT8, LOC_SEGMENT9, LOC_SEGMENT10,
            LOC_SEGMENT11, LOC_SEGMENT12, LOC_SEGMENT13, LOC_SEGMENT14, LOC_SEGMENT15,
            LOC_SEGMENT16, LOC_SEGMENT17, LOC_SEGMENT18, LOC_SEGMENT19, LOC_SEGMENT20,
            -- Transaction Identity
            TRANSACTION_QUANTITY, TRANSACTION_UOM, TRANSACTION_UNIT_OF_MEASURE,
            RESERVATION_QUANTITY, TRANSACTION_DATE,
            TRANSACTION_SOURCE_TYPE_NAME, TRANSACTION_TYPE_NAME,
            TRANSACTION_ACTION_NAME, TRANSACTION_SOURCE_NAME,
            TRANSACTION_REFERENCE, TRANSACTION_MODE, LOCK_FLAG, PROCESS_FLAG,
            INV_LOTSERIAL_INTERFACE_NUM,
            -- Batch / Group
            TRANSACTION_GROUP_ID, TRANSACTION_GROUP_SEQ,
            TRANSACTION_BATCH_ID, TRANSACTION_BATCH_SEQ,
            -- Transfer
            TRANSFER_ORGANIZATION_TYPE, TRANSFER_ORGANIZATION_NAME,
            TRANSFER_SUBINVENTORY, TRANSFER_LOCATOR_NAME,
            XFER_LOC_SEGMENT1, XFER_LOC_SEGMENT2, XFER_LOC_SEGMENT3, XFER_LOC_SEGMENT4, XFER_LOC_SEGMENT5,
            XFER_LOC_SEGMENT6, XFER_LOC_SEGMENT7, XFER_LOC_SEGMENT8, XFER_LOC_SEGMENT9, XFER_LOC_SEGMENT10,
            XFER_LOC_SEGMENT11, XFER_LOC_SEGMENT12, XFER_LOC_SEGMENT13, XFER_LOC_SEGMENT14, XFER_LOC_SEGMENT15,
            XFER_LOC_SEGMENT16, XFER_LOC_SEGMENT17, XFER_LOC_SEGMENT18, XFER_LOC_SEGMENT19, XFER_LOC_SEGMENT20,
            -- Quantities
            PRIMARY_QUANTITY, SECONDARY_TRANSACTION_QUANTITY,
            SECONDARY_UOM_CODE, SECONDARY_UNIT_OF_MEASURE,
            -- Source tracking
            SOURCE_CODE, SOURCE_HEADER_ID, SOURCE_LINE_ID, INVENTORY_ITEM,
            -- DSP segments
            DSP_SEGMENT1, DSP_SEGMENT2, DSP_SEGMENT3, DSP_SEGMENT4, DSP_SEGMENT5,
            DSP_SEGMENT6, DSP_SEGMENT7, DSP_SEGMENT8, DSP_SEGMENT9, DSP_SEGMENT10,
            DSP_SEGMENT11, DSP_SEGMENT12, DSP_SEGMENT13, DSP_SEGMENT14, DSP_SEGMENT15,
            DSP_SEGMENT16, DSP_SEGMENT17, DSP_SEGMENT18, DSP_SEGMENT19, DSP_SEGMENT20,
            DSP_SEGMENT21, DSP_SEGMENT22, DSP_SEGMENT23, DSP_SEGMENT24, DSP_SEGMENT25,
            DSP_SEGMENT26, DSP_SEGMENT27, DSP_SEGMENT28, DSP_SEGMENT29, DSP_SEGMENT30,
            -- DST segments
            DST_SEGMENT1, DST_SEGMENT2, DST_SEGMENT3, DST_SEGMENT4, DST_SEGMENT5,
            DST_SEGMENT6, DST_SEGMENT7, DST_SEGMENT8, DST_SEGMENT9, DST_SEGMENT10,
            DST_SEGMENT11, DST_SEGMENT12, DST_SEGMENT13, DST_SEGMENT14, DST_SEGMENT15,
            DST_SEGMENT16, DST_SEGMENT17, DST_SEGMENT18, DST_SEGMENT19, DST_SEGMENT20,
            DST_SEGMENT21, DST_SEGMENT22, DST_SEGMENT23, DST_SEGMENT24, DST_SEGMENT25,
            DST_SEGMENT26, DST_SEGMENT27, DST_SEGMENT28, DST_SEGMENT29, DST_SEGMENT30,
            -- Cost / Currency
            REASON_NAME, CURRENCY_NAME, CURRENCY_CODE,
            CURRENCY_CONVERSION_TYPE, CURRENCY_CONVERSION_RATE, CURRENCY_CONVERSION_DATE,
            TRANSACTION_COST, TRANSFER_COST, NEW_AVERAGE_COST,
            VALUE_CHANGE, PERCENTAGE_CHANGE,
            TRANSACTION_COST_IDENTIFIER, USE_CURRENT_COST,
            -- Flexfields
            ATTRIBUTE_CATEGORY,
            ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5,
            ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10,
            ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15,
            ATTRIBUTE16, ATTRIBUTE17, ATTRIBUTE18, ATTRIBUTE19, ATTRIBUTE20,
            ATTRIBUTE_NUMBER1, ATTRIBUTE_NUMBER2, ATTRIBUTE_NUMBER3, ATTRIBUTE_NUMBER4, ATTRIBUTE_NUMBER5,
            ATTRIBUTE_NUMBER6, ATTRIBUTE_NUMBER7, ATTRIBUTE_NUMBER8, ATTRIBUTE_NUMBER9, ATTRIBUTE_NUMBER10,
            ATTRIBUTE_DATE1, ATTRIBUTE_DATE2, ATTRIBUTE_DATE3, ATTRIBUTE_DATE4, ATTRIBUTE_DATE5,
            ATTRIBUTE_TIMESTAMP1, ATTRIBUTE_TIMESTAMP2, ATTRIBUTE_TIMESTAMP3, ATTRIBUTE_TIMESTAMP4, ATTRIBUTE_TIMESTAMP5,
            -- Pipeline
            TFM_STATUS, LAST_UPDATED_DATE
        )
        SELECT
            s.STG_SEQUENCE_ID, p_run_id,
            -- Organization & Item
            s.ORGANIZATION_NAME, s.ITEM_NUMBER, s.REVISION,
            s.SUBINVENTORY_CODE, s.LOCATOR_NAME,
            s.LOC_SEGMENT1, s.LOC_SEGMENT2, s.LOC_SEGMENT3, s.LOC_SEGMENT4, s.LOC_SEGMENT5,
            s.LOC_SEGMENT6, s.LOC_SEGMENT7, s.LOC_SEGMENT8, s.LOC_SEGMENT9, s.LOC_SEGMENT10,
            s.LOC_SEGMENT11, s.LOC_SEGMENT12, s.LOC_SEGMENT13, s.LOC_SEGMENT14, s.LOC_SEGMENT15,
            s.LOC_SEGMENT16, s.LOC_SEGMENT17, s.LOC_SEGMENT18, s.LOC_SEGMENT19, s.LOC_SEGMENT20,
            -- Transaction Identity — apply MCCS defaults
            s.TRANSACTION_QUANTITY,
            s.TRANSACTION_UOM,
            s.TRANSACTION_UNIT_OF_MEASURE,
            s.RESERVATION_QUANTITY,
            s.TRANSACTION_DATE,
            NVL(s.TRANSACTION_SOURCE_TYPE_NAME, 'Inventory'),
            NVL(s.TRANSACTION_TYPE_NAME, 'Miscellaneous Receipt'),
            s.TRANSACTION_ACTION_NAME,
            s.TRANSACTION_SOURCE_NAME,   -- NULL for Miscellaneous Receipt (type 42, source_type=Inventory)
            NVL(s.TRANSACTION_REFERENCE, 'DMT-' || TO_CHAR(p_run_id)),
            NVL(s.TRANSACTION_MODE, '3'),   -- 3 = background processing (MCCS pattern)
            NVL(s.LOCK_FLAG, '2'),          -- 2 = not locked (MCCS pattern)
            NVL(s.PROCESS_FLAG, '1'),       -- 1 = pending (MCCS pattern)
            s.INV_LOTSERIAL_INTERFACE_NUM,
            -- Batch / Group
            s.TRANSACTION_GROUP_ID, s.TRANSACTION_GROUP_SEQ,
            s.TRANSACTION_BATCH_ID, s.TRANSACTION_BATCH_SEQ,
            -- Transfer
            s.TRANSFER_ORGANIZATION_TYPE, s.TRANSFER_ORGANIZATION_NAME,
            s.TRANSFER_SUBINVENTORY, s.TRANSFER_LOCATOR_NAME,
            s.XFER_LOC_SEGMENT1, s.XFER_LOC_SEGMENT2, s.XFER_LOC_SEGMENT3, s.XFER_LOC_SEGMENT4, s.XFER_LOC_SEGMENT5,
            s.XFER_LOC_SEGMENT6, s.XFER_LOC_SEGMENT7, s.XFER_LOC_SEGMENT8, s.XFER_LOC_SEGMENT9, s.XFER_LOC_SEGMENT10,
            s.XFER_LOC_SEGMENT11, s.XFER_LOC_SEGMENT12, s.XFER_LOC_SEGMENT13, s.XFER_LOC_SEGMENT14, s.XFER_LOC_SEGMENT15,
            s.XFER_LOC_SEGMENT16, s.XFER_LOC_SEGMENT17, s.XFER_LOC_SEGMENT18, s.XFER_LOC_SEGMENT19, s.XFER_LOC_SEGMENT20,
            -- Quantities
            s.PRIMARY_QUANTITY, s.SECONDARY_TRANSACTION_QUANTITY,
            s.SECONDARY_UOM_CODE, s.SECONDARY_UNIT_OF_MEASURE,
            -- Source tracking — SOURCE_CODE = 'DMT', SOURCE_HEADER_ID = run_id
            NVL(s.SOURCE_CODE, 'DMT'),
            NVL(s.SOURCE_HEADER_ID, p_run_id),
            NVL(s.SOURCE_LINE_ID, s.STG_SEQUENCE_ID),
            s.INVENTORY_ITEM,
            -- DSP segments
            s.DSP_SEGMENT1, s.DSP_SEGMENT2, s.DSP_SEGMENT3, s.DSP_SEGMENT4, s.DSP_SEGMENT5,
            s.DSP_SEGMENT6, s.DSP_SEGMENT7, s.DSP_SEGMENT8, s.DSP_SEGMENT9, s.DSP_SEGMENT10,
            s.DSP_SEGMENT11, s.DSP_SEGMENT12, s.DSP_SEGMENT13, s.DSP_SEGMENT14, s.DSP_SEGMENT15,
            s.DSP_SEGMENT16, s.DSP_SEGMENT17, s.DSP_SEGMENT18, s.DSP_SEGMENT19, s.DSP_SEGMENT20,
            s.DSP_SEGMENT21, s.DSP_SEGMENT22, s.DSP_SEGMENT23, s.DSP_SEGMENT24, s.DSP_SEGMENT25,
            s.DSP_SEGMENT26, s.DSP_SEGMENT27, s.DSP_SEGMENT28, s.DSP_SEGMENT29, s.DSP_SEGMENT30,
            -- DST segments
            s.DST_SEGMENT1, s.DST_SEGMENT2, s.DST_SEGMENT3, s.DST_SEGMENT4, s.DST_SEGMENT5,
            s.DST_SEGMENT6, s.DST_SEGMENT7, s.DST_SEGMENT8, s.DST_SEGMENT9, s.DST_SEGMENT10,
            s.DST_SEGMENT11, s.DST_SEGMENT12, s.DST_SEGMENT13, s.DST_SEGMENT14, s.DST_SEGMENT15,
            s.DST_SEGMENT16, s.DST_SEGMENT17, s.DST_SEGMENT18, s.DST_SEGMENT19, s.DST_SEGMENT20,
            s.DST_SEGMENT21, s.DST_SEGMENT22, s.DST_SEGMENT23, s.DST_SEGMENT24, s.DST_SEGMENT25,
            s.DST_SEGMENT26, s.DST_SEGMENT27, s.DST_SEGMENT28, s.DST_SEGMENT29, s.DST_SEGMENT30,
            -- Cost / Currency
            s.REASON_NAME, s.CURRENCY_NAME, s.CURRENCY_CODE,
            s.CURRENCY_CONVERSION_TYPE, s.CURRENCY_CONVERSION_RATE, s.CURRENCY_CONVERSION_DATE,
            s.TRANSACTION_COST, s.TRANSFER_COST, s.NEW_AVERAGE_COST,
            s.VALUE_CHANGE, s.PERCENTAGE_CHANGE,
            s.TRANSACTION_COST_IDENTIFIER, NVL(s.USE_CURRENT_COST, 'Y'),
            -- Flexfields
            s.ATTRIBUTE_CATEGORY,
            s.ATTRIBUTE1, s.ATTRIBUTE2, s.ATTRIBUTE3, s.ATTRIBUTE4, s.ATTRIBUTE5,
            s.ATTRIBUTE6, s.ATTRIBUTE7, s.ATTRIBUTE8, s.ATTRIBUTE9, s.ATTRIBUTE10,
            s.ATTRIBUTE11, s.ATTRIBUTE12, s.ATTRIBUTE13, s.ATTRIBUTE14, s.ATTRIBUTE15,
            s.ATTRIBUTE16, s.ATTRIBUTE17, s.ATTRIBUTE18, s.ATTRIBUTE19, s.ATTRIBUTE20,
            s.ATTRIBUTE_NUMBER1, s.ATTRIBUTE_NUMBER2, s.ATTRIBUTE_NUMBER3, s.ATTRIBUTE_NUMBER4, s.ATTRIBUTE_NUMBER5,
            s.ATTRIBUTE_NUMBER6, s.ATTRIBUTE_NUMBER7, s.ATTRIBUTE_NUMBER8, s.ATTRIBUTE_NUMBER9, s.ATTRIBUTE_NUMBER10,
            s.ATTRIBUTE_DATE1, s.ATTRIBUTE_DATE2, s.ATTRIBUTE_DATE3, s.ATTRIBUTE_DATE4, s.ATTRIBUTE_DATE5,
            s.ATTRIBUTE_TIMESTAMP1, s.ATTRIBUTE_TIMESTAMP2, s.ATTRIBUTE_TIMESTAMP3, s.ATTRIBUTE_TIMESTAMP4, s.ATTRIBUTE_TIMESTAMP5,
            -- Pipeline
            'STAGED',
            SYSDATE
        FROM DMT_OWNER.DMT_INV_TRX_STG_TBL s
        WHERE (
            (p_run_mode = 'NEW' AND s.STG_STATUS IN ('NEW', 'RETRY'))
            OR (p_run_mode = 'FAILED' AND s.STG_STATUS = 'FAILED')
            OR (p_run_mode = 'ALL')
            OR (p_reprocess_errors AND s.STG_STATUS IN ('FAILED', 'TRANSFORM_FAILED'))
          )
        AND NOT EXISTS (
            SELECT 1 FROM DMT_OWNER.DMT_INV_TRX_TFM_TBL t
            WHERE  t.STG_SEQUENCE_ID = s.STG_SEQUENCE_ID
            AND    t.RUN_ID  = p_run_id
        );

        l_ok_count := SQL%ROWCOUNT;

        -- Update STG stg_status
        UPDATE DMT_OWNER.DMT_INV_TRX_STG_TBL s
        SET    s.STG_STATUS            = 'TRANSFORMED',
               s.LAST_UPDATED_DATE = SYSDATE
        WHERE  EXISTS (
            SELECT 1 FROM DMT_OWNER.DMT_INV_TRX_TFM_TBL t
            WHERE  t.STG_SEQUENCE_ID = s.STG_SEQUENCE_ID
            AND    t.RUN_ID  = p_run_id
        )
        AND s.STG_STATUS != 'TRANSFORMED';

        -- ── Lots: STG → TFM (if any exist) ──
        INSERT INTO DMT_OWNER.DMT_INV_TRX_LOTS_TFM_TBL (
            STG_SEQUENCE_ID, RUN_ID,
            INVENTORY_LOT_INTERFACE_NUMBER, INVENTORY_SERIAL_INTERFACE_NUM,
            SOURCE_CODE, SOURCE_LINE_ID, LOT_NUMBER, DESCRIPTION,
            LOT_EXPIRATION_DATE, TRANSACTION_QUANTITY, PRIMARY_QUANTITY,
            SECONDARY_TRANSACTION_QUANTITY,
            ORIGINATION_TYPE, ORIGINATION_DATE, STATUS_CODE, GRADE_CODE,
            REASON_NAME, PROCESS_FLAG, SUPPLIER_LOT_NUMBER,
            PARENT_LOT_NUMBER, SUBLOT_NUM,
            TFM_STATUS, LAST_UPDATED_DATE
        )
        SELECT
            s.STG_SEQUENCE_ID, p_run_id,
            s.INVENTORY_LOT_INTERFACE_NUMBER, s.INVENTORY_SERIAL_INTERFACE_NUM,
            NVL(s.SOURCE_CODE, 'DMT'), s.SOURCE_LINE_ID, s.LOT_NUMBER, s.DESCRIPTION,
            s.LOT_EXPIRATION_DATE, s.TRANSACTION_QUANTITY, s.PRIMARY_QUANTITY,
            s.SECONDARY_TRANSACTION_QUANTITY,
            s.ORIGINATION_TYPE, s.ORIGINATION_DATE, s.STATUS_CODE, s.GRADE_CODE,
            s.REASON_NAME, s.PROCESS_FLAG, s.SUPPLIER_LOT_NUMBER,
            s.PARENT_LOT_NUMBER, s.SUBLOT_NUM,
            'STAGED', SYSDATE
        FROM DMT_OWNER.DMT_INV_TRX_LOTS_STG_TBL s
        WHERE s.STG_STATUS IN ('NEW', 'RETRY')
        AND NOT EXISTS (
            SELECT 1 FROM DMT_OWNER.DMT_INV_TRX_LOTS_TFM_TBL t
            WHERE  t.STG_SEQUENCE_ID = s.STG_SEQUENCE_ID
            AND    t.RUN_ID  = p_run_id
        );

        l_lot_count := SQL%ROWCOUNT;

        UPDATE DMT_OWNER.DMT_INV_TRX_LOTS_STG_TBL
        SET    STG_STATUS = 'TRANSFORMED', LAST_UPDATED_DATE = SYSDATE
        WHERE  STG_STATUS IN ('NEW', 'RETRY')
        AND    EXISTS (
            SELECT 1 FROM DMT_OWNER.DMT_INV_TRX_LOTS_TFM_TBL t
            WHERE  t.STG_SEQUENCE_ID = DMT_INV_TRX_LOTS_STG_TBL.STG_SEQUENCE_ID
            AND    t.RUN_ID  = p_run_id
        );

        -- ── Serials: STG → TFM (if any exist) ──
        INSERT INTO DMT_OWNER.DMT_INV_TRX_SERIALS_TFM_TBL (
            STG_SEQUENCE_ID, RUN_ID,
            FM_SERIAL_NUMBER, TO_SERIAL_NUMBER,
            VENDOR_SERIAL_NUMBER, VENDOR_LOT_NUMBER, PARENT_SERIAL_NUMBER,
            STATUS_NAME, STATUS_CODE, ORIGINATION_DATE,
            TFM_STATUS, LAST_UPDATED_DATE
        )
        SELECT
            s.STG_SEQUENCE_ID, p_run_id,
            s.FM_SERIAL_NUMBER, s.TO_SERIAL_NUMBER,
            s.VENDOR_SERIAL_NUMBER, s.VENDOR_LOT_NUMBER, s.PARENT_SERIAL_NUMBER,
            s.STATUS_NAME, s.STATUS_CODE, s.ORIGINATION_DATE,
            'STAGED', SYSDATE
        FROM DMT_OWNER.DMT_INV_TRX_SERIALS_STG_TBL s
        WHERE s.STG_STATUS IN ('NEW', 'RETRY')
        AND NOT EXISTS (
            SELECT 1 FROM DMT_OWNER.DMT_INV_TRX_SERIALS_TFM_TBL t
            WHERE  t.STG_SEQUENCE_ID = s.STG_SEQUENCE_ID
            AND    t.RUN_ID  = p_run_id
        );

        l_ser_count := SQL%ROWCOUNT;

        UPDATE DMT_OWNER.DMT_INV_TRX_SERIALS_STG_TBL
        SET    STG_STATUS = 'TRANSFORMED', LAST_UPDATED_DATE = SYSDATE
        WHERE  STG_STATUS IN ('NEW', 'RETRY')
        AND    EXISTS (
            SELECT 1 FROM DMT_OWNER.DMT_INV_TRX_SERIALS_TFM_TBL t
            WHERE  t.STG_SEQUENCE_ID = DMT_INV_TRX_SERIALS_STG_TBL.STG_SEQUENCE_ID
            AND    t.RUN_ID  = p_run_id
        );

        DMT_UTIL_PKG.LOG(
            p_run_id => p_run_id,
            p_message        => 'TRANSFORM complete. Transactions: ' || l_ok_count
                                || ', Lots: ' || l_lot_count
                                || ', Serials: ' || l_ser_count,
            p_package        => C_PKG,
            p_procedure      => C_PROC);

    EXCEPTION
        WHEN OTHERS THEN
            DMT_UTIL_PKG.LOG_ERROR(
                p_run_id => p_run_id,
                p_message        => 'TRANSFORM failed.',
                p_sqlerrm        => SQLERRM,
                p_package        => C_PKG,
                p_procedure      => C_PROC);
            RAISE;
    END TRANSFORM;

END DMT_MISC_RECEIPT_TRANSFORM_PKG;
/
