-- PACKAGE DMT_POZ_SUP_SITE_ASSN_VALIDATOR_PKG

  CREATE OR REPLACE EDITIONABLE PACKAGE "DMT_POZ_SUP_SITE_ASSN_VALIDATOR_PKG" 
AUTHID DEFINER
AS
    PROCEDURE VALIDATE_BATCH (p_run_id IN NUMBER);
END DMT_POZ_SUP_SITE_ASSN_VALIDATOR_PKG;
/
