-- PACKAGE DMT_POZ_SUP_ADDR_VALIDATOR_PKG

  CREATE OR REPLACE EDITIONABLE PACKAGE "DMT_POZ_SUP_ADDR_VALIDATOR_PKG" 
AUTHID DEFINER
AS
    PROCEDURE VALIDATE_PRE_TRANSFORM (p_run_id IN NUMBER, p_scenario_id IN NUMBER DEFAULT NULL, p_run_mode IN VARCHAR2 DEFAULT 'NEW');
END DMT_POZ_SUP_ADDR_VALIDATOR_PKG;
/
