-- PACKAGE DMT_QUEUE_PKG

  CREATE OR REPLACE EDITIONABLE PACKAGE "DMT_QUEUE_PKG" 
AUTHID DEFINER
AS
-- ============================================================
-- DMT_QUEUE_PKG — Heartbeat + async child-job queue poller
--
-- Architecture:
--   One permanent DBMS_SCHEDULER job fires HEARTBEAT_TICK every
--   60s. The heartbeat is lightweight (status checks + job spawns,
--   no Fusion calls). Heavy work runs in one-shot child jobs:
--     EXECUTE_ONE  — validate + transform + generate + SUBMIT_LOAD
--     RECONCILE_ONE — BIP reconciliation
--   Each child runs in its own DB session, so multiple objects
--   process in parallel and nothing blocks the heartbeat.
--
-- Job lifecycle:
--   The heartbeat job (DMT_QUEUE_POLLER) is created ONCE at deploy
--   time and never dropped. ENSURE_POLLER_RUNNING enables it;
--   STOP_POLLER_IF_IDLE disables it. No CREATE_JOB/DROP_JOB at
--   runtime = no library cache lock contention with APEX sessions.
--
-- Child job naming: DMT_WQ_{QUEUE_ID} / DMT_RC_{QUEUE_ID}
-- ============================================================

    C_POLLER_JOB     CONSTANT VARCHAR2(30) := 'DMT_QUEUE_POLLER';
    C_POLL_INTERVAL  CONSTANT PLS_INTEGER  := 60;   -- seconds
    -- (A3, 2026-07-08: the hardcoded C_ESS_TIMEOUT constant is retired —
    --  the poll timeout is the ESS_POLL_TIMEOUT_MINUTES configuration
    --  value in DMT_CONFIG_TBL, read by DMT_QUEUE_WORKER_PKG.POLL_ONE;
    --  design section 2 "Timeouts (decided 2026-07-07)".)

    -- Heartbeat: called by DBMS_SCHEDULER every 60s.
    -- Promotes PENDING, polls ESS, spawns child jobs for
    -- READY/RECONCILING rows, handles failures, and rolls run
    -- statuses up from work items (the single RUN_STATUS writer).
    PROCEDURE HEARTBEAT_TICK;

    -- Legacy alias — calls HEARTBEAT_TICK.
    PROCEDURE PROCESS_QUEUE;

    -- Enable the permanent heartbeat job.
    PROCEDURE ENSURE_POLLER_RUNNING;

    -- Disable the heartbeat job if no active work remains.
    PROCEDURE STOP_POLLER_IF_IDLE;

    -- ============================================================
    -- RERUN_RUN — re-run reconcile for an entire run (backlog #95).
    --
    -- A run can finish with rows the tool never accounted for: if a
    -- reconcile faulted mid-pass, the shared sweep marked the object's
    -- still-GENERATED rows UNACCOUNTED and the run settled terminal.
    -- Because the sweep and every per-object APPLY proc act only on
    -- GENERATED rows, just re-dispatching the reconcile would leave those
    -- UNACCOUNTED rows untouched. This procedure fixes that for the whole
    -- run, with NO per-object code:
    --   1. For every object in the run that has unaccounted rows, reset
    --      its UNACCOUNTED TFM rows back to GENERATED by dispatching the
    --      object's OWN static RESET_UNACCOUNTED proc (named in
    --      DMT_PIPELINE_DEF_TBL.RESET_PROC) through the existing sanctioned
    --      invoke_registered site (the DMT_QUEUE_WORKER_PKG.INVOKE_RESET
    --      wrapper). The reset is a STATIC UPDATE inside the object's results
    --      package over its literally-named TFM table(s) — RERUN_RUN itself
    --      holds no dynamic SQL and names no TFM table.
    --   2. Flip each terminal work-queue row whose object now has
    --      GENERATED rows back to WORK_STATUS='RECONCILING' and clear
    --      NEXT_POLL_AFTER, so the existing poller (dispatch_reconcile)
    --      re-spawns its reconcile through the object's registered
    --      RECON_PROC — the SAME dispatch the live poller uses, never a
    --      parallel path. RECONCILE_ONE then runs SWEEP + gate again and
    --      the row reaches a real terminal verdict.
    --   3. Reopen the run row to IN_PROGRESS (clear COMPLETED_DATE) so the
    --      heartbeat rollup re-settles it once the re-dispatched objects
    --      finish, and ensure the poller is running.
    --
    -- Idempotent: a run with no UNACCOUNTED rows resets nothing, flips no
    -- work items, and leaves the run status untouched.
    -- ============================================================
    PROCEDURE RERUN_RUN (p_run_id IN NUMBER);

    -- ============================================================
    -- CANCEL_RUN -- the sanctioned way to end a run that can never
    -- finish on its own (owner-approved 2026-10-08, backlog #635).
    --
    --   1. Refuses a run that is already terminal (COMPLETED /
    --      COMPLETED_ERRORS / FAILED / NO_ROWS_PROCESSED); a run that is
    --      already CANCELLED is a no-op success. p_reason is required.
    --   2. Marks every not-yet-terminal work item of the run CANCELLED
    --      (ERROR_MESSAGE = the reason, COMPLETED_AT stamped) and the run
    --      row RUN_STATUS = 'CANCELLED' with COMPLETED_DATE and an
    --      ERROR_MESSAGE recording who cancelled it, when, and why. Items
    --      already DONE / FAILED / SKIPPED keep their verdicts. Commits
    --      before touching the scheduler so the heartbeat cannot dispatch
    --      anything new for the run.
    --   3. Stops and drops every scheduler job of the run: DMT_PF_<run>
    --      (preflight) and DMT_WQ_ / DMT_PL_ / DMT_RC_<queue_id> (data
    --      phase, ESS poll, reconcile). A stopped job's uncommitted work
    --      rolls back. Then re-marks CANCELLED any item a job moved in the
    --      meantime.
    --   4. Writes a WARN entry to the activity log (DMT_LOG_TBL) with the
    --      reason, the item count and the jobs stopped.
    --
    -- NEVER touches STG or TFM rows: rows the run already generated stay
    -- exactly as they are (a re-run uses a new prefix). A Fusion ESS job
    -- the run already submitted keeps running in Fusion; only our
    -- watching of it stops. A run with no work items (a hand-inserted run
    -- row) is cancelled by its run row alone.
    --
    -- p_cancelled_by: who asked (NULL = the database session user).
    -- x_error_code: DMT_UTIL_PKG.C_SUCCESS, or C_ERROR with the reason in
    -- the activity log (unknown run, blank reason, run already terminal,
    -- or a job that could not be stopped).
    -- ============================================================
    PROCEDURE CANCEL_RUN (
        p_run_id       IN  NUMBER,
        p_reason       IN  VARCHAR2,
        p_cancelled_by IN  VARCHAR2 DEFAULT NULL,
        x_error_code   OUT NUMBER
    );

    -- ============================================================
    -- RECOVER_ORPHAN_PREFLIGHT -- heartbeat recovery for a run whose
    -- preflight job died without recording a verdict (backlog #565: a
    -- DMT_PF_ job that fails to start, e.g. ORA-04063 while a package is
    -- being redeployed, leaves PREFLIGHT_STATUS = 'PREFLIGHTING' forever).
    -- Acts only on a QUEUED run that is PREFLIGHTING with no DMT_PF_<run>
    -- scheduler job: the first time it releases the claim (NULL) so the
    -- same tick re-spawns the preflight once; the second time it fails the
    -- run through DMT_QUEUE_WORKER_PKG.FAIL_RUN_PREFLIGHT with a clear
    -- message. Any other run is left untouched. Called by HEARTBEAT_TICK
    -- for every candidate run; public so it can be unit-tested.
    -- ============================================================
    PROCEDURE RECOVER_ORPHAN_PREFLIGHT (
        p_run_id     IN  NUMBER,
        x_error_code OUT NUMBER
    );

END DMT_QUEUE_PKG;
/
