-- PACKAGE BODY DMT_PRJ_BUDGET_TRANSFORM_PKG

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "DMT_PRJ_BUDGET_TRANSFORM_PKG" AS

    C_PKG CONSTANT VARCHAR2(50) := 'DMT_PRJ_BUDGET_TRANSFORM_PKG';

    PROCEDURE TRANSFORM (
        p_run_id   IN NUMBER,
        p_reprocess_errors IN BOOLEAN DEFAULT FALSE,
        p_scenario_id      IN NUMBER DEFAULT NULL,
        p_include_untagged IN VARCHAR2 DEFAULT 'N', p_run_mode IN VARCHAR2 DEFAULT 'NEW'
    ) IS
        l_ok         NUMBER := 0;
        l_dep_prefix VARCHAR2(30);
    BEGIN
        DMT_UTIL_PKG.LOG(p_run_id, 'TRANSFORM start.', C_PKG, 'TRANSFORM');

        -- Prefix for project references: budgets load against projects
        -- migrated in the same run, whose Fusion number/name carry the
        -- run prefix (same pattern as DMT_EXPENDITURE_TRANSFORM_PKG).
        SELECT PREFIX
        INTO   l_dep_prefix
        FROM   DMT_OWNER.DMT_PIPELINE_RUN_TBL
        WHERE  RUN_ID = p_run_id;

        INSERT INTO DMT_OWNER.DMT_PRJ_BUDGET_TFM_TBL (
            STG_SEQUENCE_ID, RUN_ID,
            AWARD_NUMBER, FINANCIAL_PLAN_TYPE, PROJECT_NUMBER, PROJECT_NAME,
            TASK_NAME, TASK_NUMBER,
            PLAN_VERSION_NAME, PLAN_VERSION_DESCRIPTION, PLAN_VERSION_STATUS,
            RESOURCE_NAME, PERIOD_NAME, PLANNING_CURRENCY,
            TOTAL_QUANTITY, TOTAL_TC_RAW_COST, TOTAL_TC_REVENUE,
            SRC_BUDGET_LINE_REFERENCE,
            FUNDING_SOURCE_NUMBER, FUNDING_SOURCE_NAME,
            PC_RAW_COST, PC_REVENUE, PFC_RAW_COST, PFC_REVENUE,
            TOTAL_TC_BRDND_COST, PC_BRDND_COST, PFC_BRDND_COST,
            LINE_TYPE, PLANNING_START_DATE, PLANNING_END_DATE,
            ATTRIBUTE_CATEGORY,
            ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5,
            ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10,
            ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15,
            ATTRIBUTE16, ATTRIBUTE17, ATTRIBUTE18, ATTRIBUTE19, ATTRIBUTE20,
            ATTRIBUTE21, ATTRIBUTE22, ATTRIBUTE23, ATTRIBUTE24, ATTRIBUTE25,
            ATTRIBUTE26, ATTRIBUTE27, ATTRIBUTE28, ATTRIBUTE29, ATTRIBUTE30,
            PLAN_VERSION_NUMBER, PROCESSING_MODE,
            TFM_STATUS
        )
        SELECT
            s.STG_SEQUENCE_ID, p_run_id,
            s.AWARD_NUMBER, s.FINANCIAL_PLAN_TYPE,
            DMT_UTIL_PKG.PREFIXED(l_dep_prefix, s.PROJECT_NUMBER, 25),
            DMT_UTIL_PKG.PREFIXED(l_dep_prefix, s.PROJECT_NAME, 240),
            s.TASK_NAME, s.TASK_NUMBER,
            s.PLAN_VERSION_NAME, s.PLAN_VERSION_DESCRIPTION, s.PLAN_VERSION_STATUS,
            s.RESOURCE_NAME, s.PERIOD_NAME, s.PLANNING_CURRENCY,
            s.TOTAL_QUANTITY, s.TOTAL_TC_RAW_COST, s.TOTAL_TC_REVENUE,
            s.SRC_BUDGET_LINE_REFERENCE,
            s.FUNDING_SOURCE_NUMBER, s.FUNDING_SOURCE_NAME,
            s.PC_RAW_COST, s.PC_REVENUE, s.PFC_RAW_COST, s.PFC_REVENUE,
            s.TOTAL_TC_BRDND_COST, s.PC_BRDND_COST, s.PFC_BRDND_COST,
            s.LINE_TYPE, s.PLANNING_START_DATE, s.PLANNING_END_DATE,
            s.ATTRIBUTE_CATEGORY,
            s.ATTRIBUTE1, s.ATTRIBUTE2, s.ATTRIBUTE3, s.ATTRIBUTE4, s.ATTRIBUTE5,
            s.ATTRIBUTE6, s.ATTRIBUTE7, s.ATTRIBUTE8, s.ATTRIBUTE9, s.ATTRIBUTE10,
            s.ATTRIBUTE11, s.ATTRIBUTE12, s.ATTRIBUTE13, s.ATTRIBUTE14, s.ATTRIBUTE15,
            s.ATTRIBUTE16, s.ATTRIBUTE17, s.ATTRIBUTE18, s.ATTRIBUTE19, s.ATTRIBUTE20,
            s.ATTRIBUTE21, s.ATTRIBUTE22, s.ATTRIBUTE23, s.ATTRIBUTE24, s.ATTRIBUTE25,
            s.ATTRIBUTE26, s.ATTRIBUTE27, s.ATTRIBUTE28, s.ATTRIBUTE29, s.ATTRIBUTE30,
            s.PLAN_VERSION_NUMBER, s.PROCESSING_MODE,
            'STAGED'
        FROM   DMT_OWNER.DMT_PRJ_BUDGET_STG_TBL s
        WHERE  (
            (p_run_mode = 'NEW' AND s.STG_STATUS IN ('NEW', 'RETRY'))
            OR (p_run_mode = 'FAILED' AND s.STG_STATUS = 'FAILED')
            OR (p_run_mode = 'ALL' AND s.STG_STATUS IN ('NEW', 'RETRY'))
          )
        AND (p_scenario_id IS NULL
             OR s.SCENARIO_ID = p_scenario_id
             OR (p_include_untagged = 'Y' AND s.SCENARIO_ID IS NULL))
          AND NOT EXISTS (
              SELECT 1 FROM DMT_OWNER.DMT_STG_TFM_ERROR_TBL e
              WHERE  e.RUN_ID = p_run_id
              AND    e.SUB_OBJECT = 'Project Budgets'
              AND    e.STG_SEQUENCE_ID = s.STG_SEQUENCE_ID);

        l_ok := SQL%ROWCOUNT;

        UPDATE DMT_OWNER.DMT_PRJ_BUDGET_STG_TBL
        SET    STG_STATUS = 'TRANSFORMED', LAST_UPDATED_DATE = SYSDATE
        WHERE  (
            (p_run_mode = 'NEW' AND STG_STATUS IN ('NEW', 'RETRY'))
            OR (p_run_mode = 'FAILED' AND STG_STATUS = 'FAILED')
            OR (p_run_mode = 'ALL' AND STG_STATUS IN ('NEW', 'RETRY'))
          )
        AND (p_scenario_id IS NULL
             OR SCENARIO_ID = p_scenario_id
             OR (p_include_untagged = 'Y' AND SCENARIO_ID IS NULL))
          AND NOT EXISTS (
              SELECT 1 FROM DMT_OWNER.DMT_STG_TFM_ERROR_TBL e
              WHERE  e.RUN_ID = p_run_id
              AND    e.SUB_OBJECT = 'Project Budgets'
              AND    e.STG_SEQUENCE_ID = STG_SEQUENCE_ID);

        DMT_UTIL_PKG.LOG(p_run_id, 'TRANSFORM complete. Rows: ' || l_ok, C_PKG, 'TRANSFORM');
    EXCEPTION
        WHEN OTHERS THEN
            DMT_UTIL_PKG.LOG_ERROR(p_run_id, 'TRANSFORM failed.', SQLERRM, C_PKG, 'TRANSFORM');
            RAISE;
    END TRANSFORM;

END DMT_PRJ_BUDGET_TRANSFORM_PKG;
/
