#!/bin/sh
# test_workers_golden.sh - golden byte compare for the Workers HDL generator.
# Workers is the FIRST HDL object: golden is Worker.dat (10 pipe-delimited
# METADATA/MERGE sections) inside test/fbdi_zips/Workers_116.zip. Compare uses
# the hdl_dat member mode of compare_fbdi.py. Pipeline: land 7 CSVs -> INIT_RUN
# -> 7 transforms -> GENERATE_HDL -> extract zip -> byte compare Worker.dat.
# Input rows reproduce ConversionTool/scripts/insert_hcm_regression_data.py
# (2 GOOD DMTW001/DMTW002 all 10 components + 1 BAD DMTW-BAD mandatory-5 only).
# Worker STG landed in golden order (DMTW001, DMTW-BAD, DMTW002). Validator NOT
# called here (stub; exercised in test/unit/test_workers.sql). WorkRelationship,
# WorkTerms, Assignment auto-generated by the generator (no STG tables).
# Scenario-scoped teardown mirrors test_suppliers_golden.sh; never a status reset.
# Usage: sh test/golden/test_workers_golden.sh   Env: DMT2_CONN SQLCL JAVA_HOME PYTHON
set -u
JAVA_HOME="${JAVA_HOME:-/c/Users/Monroe/tools/jdk-21.0.11+10}"; export JAVA_HOME
PATH="$JAVA_HOME/bin:$PATH"; export PATH
SQLCL="${SQLCL:-/c/Users/Monroe/tools/sqlcl/bin/sql}"
PYTHON="${PYTHON:-python}"
DMT2_CONN="${DMT2_CONN:-dmt_owner/DmtLocal#2026@//localhost:1523/FREEPDB1}"
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
MAP_JSON="$SCRIPT_DIR/normalization_map.json"
WORK_DIR="${TMPDIR:-/tmp}/dmt2_golden_workers"; mkdir -p "$WORK_DIR"
SQL_FILE="$WORK_DIR/run_workers.sql"; LOG_FILE="$WORK_DIR/run_workers.log"
fail () { echo "FAIL  test_workers_golden.sh  ($1)  [log: $LOG_FILE]"; exit 1; }
for f in Workers Workers_PersonName Workers_PersonEmail Workers_PersonPhone Workers_PersonAddress Workers_PersonNID Workers_PersonLegislativeData; do
    [ -f "$SCRIPT_DIR/inputs/${f}_input.csv" ] || fail "missing input CSV inputs/${f}_input.csv"
done
CSV_WRK=$(cat "$SCRIPT_DIR/inputs/Workers_input.csv") || fail "read Workers"
CSV_NME=$(cat "$SCRIPT_DIR/inputs/Workers_PersonName_input.csv") || fail "read PersonName"
CSV_EML=$(cat "$SCRIPT_DIR/inputs/Workers_PersonEmail_input.csv") || fail "read PersonEmail"
CSV_PHN=$(cat "$SCRIPT_DIR/inputs/Workers_PersonPhone_input.csv") || fail "read PersonPhone"
CSV_ADR=$(cat "$SCRIPT_DIR/inputs/Workers_PersonAddress_input.csv") || fail "read PersonAddress"
CSV_NID=$(cat "$SCRIPT_DIR/inputs/Workers_PersonNID_input.csv") || fail "read PersonNID"
CSV_LEG=$(cat "$SCRIPT_DIR/inputs/Workers_PersonLegislativeData_input.csv") || fail "read PersonLegisl"
cat > "$SQL_FILE" <<SQLEOF
whenever sqlerror exit failure
set serveroutput on size unlimited
set feedback off
set define off
set linesize 32767
set trimout on
declare
    l_scn number;
begin
    select max(scenario_id) into l_scn from dmt_scenario_tbl where upper(scenario_name) = 'GOLDEN_WRK_SCN';
    if l_scn is not null then
        delete from dmt_worker_tfm_tbl where stg_sequence_id in (select stg_sequence_id from dmt_worker_stg_tbl where scenario_id = l_scn);
        delete from dmt_person_name_tfm_tbl where stg_sequence_id in (select stg_sequence_id from dmt_person_name_stg_tbl where scenario_id = l_scn);
        delete from dmt_person_email_tfm_tbl where stg_sequence_id in (select stg_sequence_id from dmt_person_email_stg_tbl where scenario_id = l_scn);
        delete from dmt_person_phone_tfm_tbl where stg_sequence_id in (select stg_sequence_id from dmt_person_phone_stg_tbl where scenario_id = l_scn);
        delete from dmt_person_addr_tfm_tbl where stg_sequence_id in (select stg_sequence_id from dmt_person_addr_stg_tbl where scenario_id = l_scn);
        delete from dmt_person_nid_tfm_tbl where stg_sequence_id in (select stg_sequence_id from dmt_person_nid_stg_tbl where scenario_id = l_scn);
        delete from dmt_person_legisl_tfm_tbl where stg_sequence_id in (select stg_sequence_id from dmt_person_legisl_stg_tbl where scenario_id = l_scn);
        delete from dmt_worker_stg_tbl where scenario_id = l_scn;
        delete from dmt_person_name_stg_tbl where scenario_id = l_scn;
        delete from dmt_person_email_stg_tbl where scenario_id = l_scn;
        delete from dmt_person_phone_stg_tbl where scenario_id = l_scn;
        delete from dmt_person_addr_stg_tbl where scenario_id = l_scn;
        delete from dmt_person_nid_stg_tbl where scenario_id = l_scn;
        delete from dmt_person_legisl_stg_tbl where scenario_id = l_scn;
    end if;
    delete from dmt_csv_landing_tbl where batch_id like 'GOLDEN_WRK%';
    commit;
end;
/
declare
    procedure land_one (p_batch varchar2, p_table varchar2, p_file varchar2, p_csv clob) is
        l_id number; l_status varchar2(30); l_err clob;
    begin
        insert into dmt_csv_landing_tbl (batch_id, view_name, atp_table_name, file_name, csv_data, scenario_name)
        values (p_batch, p_batch || '_VIEW', p_table, p_file, p_csv, 'GOLDEN_WRK_SCN')
        returning csv_landing_id into l_id;
        commit;
        dmt_csv_loader_pkg.load_csv(p_csv_landing_id => l_id);
        select status, error_text into l_status, l_err from dmt_csv_landing_tbl where csv_landing_id = l_id;
        if l_status <> 'LOADED' then
            raise_application_error(-20999, p_batch || ' CSV load failed (' || l_status || '): ' || dbms_lob.substr(l_err, 3000, 1));
        end if;
        dbms_output.put_line('LOADED_OK:' || p_batch);
    end land_one;
begin
    land_one('GOLDEN_WRK_1', 'DMT_WORKER_STG_TBL',        'Workers_input.csv',                       to_clob(q'[${CSV_WRK}]'));
    land_one('GOLDEN_WRK_2', 'DMT_PERSON_NAME_STG_TBL',   'Workers_PersonName_input.csv',            to_clob(q'[${CSV_NME}]'));
    land_one('GOLDEN_WRK_3', 'DMT_PERSON_EMAIL_STG_TBL',  'Workers_PersonEmail_input.csv',           to_clob(q'[${CSV_EML}]'));
    land_one('GOLDEN_WRK_4', 'DMT_PERSON_PHONE_STG_TBL',  'Workers_PersonPhone_input.csv',           to_clob(q'[${CSV_PHN}]'));
    land_one('GOLDEN_WRK_5', 'DMT_PERSON_ADDR_STG_TBL',   'Workers_PersonAddress_input.csv',         to_clob(q'[${CSV_ADR}]'));
    land_one('GOLDEN_WRK_6', 'DMT_PERSON_NID_STG_TBL',    'Workers_PersonNID_input.csv',             to_clob(q'[${CSV_NID}]'));
    land_one('GOLDEN_WRK_7', 'DMT_PERSON_LEGISL_STG_TBL', 'Workers_PersonLegislativeData_input.csv', to_clob(q'[${CSV_LEG}]'));
end;
/
declare
    l_run number; l_prefix varchar2(20); l_scn number; l_zip blob; l_fn varchar2(200); l_csv_id number;
    procedure dump_zip (p_object varchar2, p_zip blob) is
        l_len integer; l_pos integer := 1; l_b64 varchar2(32000);
    begin
        if p_zip is null then raise_application_error(-20999, p_object || ': GENERATE_HDL produced no zip'); end if;
        dbms_output.put_line('ZIPSTART:' || p_object);
        l_len := dbms_lob.getlength(p_zip);
        while l_pos <= l_len loop
            l_b64 := utl_raw.cast_to_varchar2(utl_encode.base64_encode(dbms_lob.substr(p_zip, 2400, l_pos)));
            l_b64 := replace(replace(l_b64, chr(13), ''), chr(10), '');
            dbms_output.put_line('B64:' || l_b64);
            l_pos := l_pos + 2400;
        end loop;
        dbms_output.put_line('ZIPEND:' || p_object);
    end dump_zip;
begin
    dmt_pipeline_init_pkg.init_run(p_orchestration_code => 'Workers', p_scenario_name => 'GOLDEN_WRK_SCN',
        p_source_filename => 'Workers_input.csv', p_instance_id => 'GOLDEN_TEST', x_integration_id => l_run, x_prefix => l_prefix);
    if l_prefix is null then raise_application_error(-20999, 'INIT_RUN returned no prefix'); end if;
    select scenario_id into l_scn from dmt_scenario_tbl where upper(scenario_name) = 'GOLDEN_WRK_SCN';
    dmt_worker_transform_pkg.transform_workers(l_run, p_scenario_id => l_scn);
    dmt_worker_transform_pkg.transform_person_names(l_run, p_scenario_id => l_scn);
    dmt_worker_transform_pkg.transform_person_emails(l_run, p_scenario_id => l_scn);
    dmt_worker_transform_pkg.transform_person_phones(l_run, p_scenario_id => l_scn);
    dmt_worker_transform_pkg.transform_person_addresses(l_run, p_scenario_id => l_scn);
    dmt_worker_transform_pkg.transform_person_nids(l_run, p_scenario_id => l_scn);
    dmt_worker_transform_pkg.transform_person_legisl(l_run, p_scenario_id => l_scn);
    dbms_output.put_line('RUNID:'  || l_run);
    dbms_output.put_line('PREFIX:' || l_prefix);
    dmt_worker_hdl_gen_pkg.generate_hdl(l_run, l_zip, l_fn, l_csv_id);
    dump_zip('Workers', l_zip);
    commit;
    dbms_output.put_line('ALLZIPSDONE');
end;
/
exit success
SQLEOF
echo exit | "$SQLCL" -S "$DMT2_CONN" "@$SQL_FILE" > "$LOG_FILE" 2>&1
rc=$?
[ $rc -eq 0 ] || fail "SQL driver exit $rc: $(grep -E 'ORA-|SP2-' "$LOG_FILE" | head -1)"
grep -q '^ALLZIPSDONE' "$LOG_FILE" || fail "zip dump incomplete (no ALLZIPSDONE marker)"
RUN_ID=$(grep '^RUNID:'  "$LOG_FILE" | head -1 | cut -d: -f2 | tr -d '[:space:]')
PREFIX=$(grep '^PREFIX:' "$LOG_FILE" | head -1 | cut -d: -f2 | tr -d '[:space:]')
[ -n "$RUN_ID" ] && [ -n "$PREFIX" ] || fail "could not parse RUN_ID/PREFIX from log"
echo "run_id=$RUN_ID prefix=$PREFIX work_dir=$WORK_DIR"
OBJ=Workers
GEN_ZIP="$WORK_DIR/${OBJ}_generated_${RUN_ID}.zip"
sed -n "/^ZIPSTART:${OBJ}\$/,/^ZIPEND:${OBJ}\$/p" "$LOG_FILE" | grep '^B64:' | sed 's/^B64://' | tr -d '\r' | base64 -d > "$GEN_ZIP" || fail "$OBJ: base64 decode failed"
[ -s "$GEN_ZIP" ] || fail "$OBJ: generated zip is empty"
"$PYTHON" "$SCRIPT_DIR/compare_fbdi.py" --object "$OBJ" --generated "$GEN_ZIP" --map "$MAP_JSON" --prefix "$PREFIX" --run-id "$RUN_ID"
crc=$?
if [ $crc -ne 0 ]; then echo "DIFF  $OBJ: compare exit $crc"; fail "Worker.dat differs from its golden"; fi
echo "PASS  test_workers_golden.sh  (Worker.dat byte-identical after declared normalization; run $RUN_ID prefix $PREFIX)"
exit 0
