-- DMT_POZ_SUP_ADDR_TFM_TBL (generated from ATP 2026-07-03)

-- Identity-PK conversion (accepted coding standard 2026-07-08: "Identity
-- columns for keys; sequences only for shared, meaningful values").
-- In-place conversion of an existing non-identity column is NOT possible on
-- Oracle 26ai: every ALTER TABLE ... MODIFY variant (GENERATED ALWAYS,
-- GENERATED BY DEFAULT ON NULL) raises ORA-30673, even on an empty table
-- (probed on dmt2-local 2026-07-08). So a pre-identity table is converted by
-- drop-and-recreate -- EMPTY tables only. A populated table is never dropped
-- (staging rows are never deleted): the block raises with the manual
-- data-preserving rebuild recipe instead.
-- Deploy this file via db/install.sql: any FK dropped by the CASCADE here is
-- re-added by tables/_foreign_keys.sql later in the same install run.
declare
  l_exists   pls_integer;
  l_identity pls_integer;
  l_rows     pls_integer;
begin
  select count(*) into l_exists from user_tables
  where  table_name = 'DMT_POZ_SUP_ADDR_TFM_TBL';
  if l_exists = 1 then
    select count(*) into l_identity from user_tab_identity_cols
    where  table_name = 'DMT_POZ_SUP_ADDR_TFM_TBL' and column_name = 'TFM_SEQUENCE_ID';
    if l_identity = 0 then
      execute immediate 'select count(*) from "DMT_POZ_SUP_ADDR_TFM_TBL" where rownum = 1' into l_rows;
      if l_rows = 0 then
        execute immediate 'drop table "DMT_POZ_SUP_ADDR_TFM_TBL" cascade constraints purge';
      else
        raise_application_error(-20001,
          'DMT_POZ_SUP_ADDR_TFM_TBL: cannot convert a populated table to an identity PK in place (ORA-30673). ' ||
          'Manual rebuild required: create a swap table with TFM_SEQUENCE_ID GENERATED BY DEFAULT ON NULL AS IDENTITY, ' ||
          'insert the rows preserving ids, rename, re-add constraints, then ALTER ... MODIFY to GENERATED ALWAYS (START WITH LIMIT VALUE).');
      end if;
    end if;
  end if;
end;
/

begin
  execute immediate 'CREATE TABLE "DMT_POZ_SUP_ADDR_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"IMPORT_ACTION" VARCHAR2(10), 
	"VENDOR_NAME" VARCHAR2(360) NOT NULL ENABLE, 
	"PARTY_SITE_NAME" VARCHAR2(240) NOT NULL ENABLE, 
	"PARTY_SITE_NAME_NEW" VARCHAR2(240), 
	"COUNTRY" VARCHAR2(2) NOT NULL ENABLE, 
	"ADDRESS_LINE1" VARCHAR2(240) NOT NULL ENABLE, 
	"ADDRESS_LINE2" VARCHAR2(240), 
	"ADDRESS_LINE3" VARCHAR2(240), 
	"ADDRESS_LINE4" VARCHAR2(240), 
	"ADDRESS_LINES_PHONETIC" VARCHAR2(560), 
	"ADDR_ELEMENT_ATTRIBUTE1" VARCHAR2(150), 
	"ADDR_ELEMENT_ATTRIBUTE2" VARCHAR2(150), 
	"ADDR_ELEMENT_ATTRIBUTE3" VARCHAR2(150), 
	"ADDR_ELEMENT_ATTRIBUTE4" VARCHAR2(150), 
	"ADDR_ELEMENT_ATTRIBUTE5" VARCHAR2(150), 
	"BUILDING" VARCHAR2(40), 
	"FLOOR_NUMBER" VARCHAR2(40), 
	"CITY" VARCHAR2(60), 
	"STATE" VARCHAR2(60), 
	"PROVINCE" VARCHAR2(60), 
	"COUNTY" VARCHAR2(60), 
	"POSTAL_CODE" VARCHAR2(20), 
	"POSTAL_PLUS4_CODE" VARCHAR2(20), 
	"ADDRESSEE" VARCHAR2(360), 
	"GLOBAL_LOCATION_NUMBER" VARCHAR2(40), 
	"PARTY_SITE_LANGUAGE" VARCHAR2(4), 
	"INACTIVE_DATE" DATE, 
	"PHONE_COUNTRY_CODE" VARCHAR2(10), 
	"PHONE_AREA_CODE" VARCHAR2(10), 
	"PHONE" VARCHAR2(40), 
	"PHONE_EXTENSION" VARCHAR2(20), 
	"FAX_COUNTRY_CODE" VARCHAR2(10), 
	"FAX_AREA_CODE" VARCHAR2(10), 
	"FAX" VARCHAR2(40), 
	"RFQ_OR_BIDDING_PURPOSE_FLAG" VARCHAR2(1), 
	"ORDERING_PURPOSE_FLAG" VARCHAR2(1), 
	"REMIT_TO_PURPOSE_FLAG" VARCHAR2(1), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"ATTRIBUTE21" VARCHAR2(150), 
	"ATTRIBUTE22" VARCHAR2(150), 
	"ATTRIBUTE23" VARCHAR2(150), 
	"ATTRIBUTE24" VARCHAR2(150), 
	"ATTRIBUTE25" VARCHAR2(150), 
	"ATTRIBUTE26" VARCHAR2(150), 
	"ATTRIBUTE27" VARCHAR2(150), 
	"ATTRIBUTE28" VARCHAR2(150), 
	"ATTRIBUTE29" VARCHAR2(150), 
	"ATTRIBUTE30" VARCHAR2(150), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_NUMBER11" NUMBER, 
	"ATTRIBUTE_NUMBER12" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_DATE6" DATE, 
	"ATTRIBUTE_DATE7" DATE, 
	"ATTRIBUTE_DATE8" DATE, 
	"ATTRIBUTE_DATE9" DATE, 
	"ATTRIBUTE_DATE10" DATE, 
	"ATTRIBUTE_DATE11" DATE, 
	"ATTRIBUTE_DATE12" DATE, 
	"EMAIL_ADDRESS" VARCHAR2(240), 
	"DELIVERY_CHANNEL_CODE" VARCHAR2(30), 
	"BANK_INSTRUCTION1_CODE" VARCHAR2(30), 
	"BANK_INSTRUCTION2_CODE" VARCHAR2(30), 
	"BANK_INSTRUCTION_DETAILS" VARCHAR2(255), 
	"SETTLEMENT_PRIORITY" NUMBER, 
	"PAYMENT_TEXT_MESSAGE1" VARCHAR2(150), 
	"PAYMENT_TEXT_MESSAGE2" VARCHAR2(150), 
	"PAYMENT_TEXT_MESSAGE3" VARCHAR2(150), 
	"SERVICE_LEVEL_CODE" VARCHAR2(30), 
	"EXCLUSIVE_PAYMENT_FLAG" VARCHAR2(1), 
	"IBY_BANK_CHARGE_BEARER" VARCHAR2(30), 
	"PAYMENT_REASON_CODE" VARCHAR2(30), 
	"PAYMENT_REASON_COMMENTS" VARCHAR2(240), 
	"REMIT_ADVICE_DELIVERY_METHOD" VARCHAR2(30), 
	"REMIT_ADVICE_EMAIL" VARCHAR2(240), 
	"REMIT_ADVICE_FAX" VARCHAR2(100), 
	"FUSION_PARTY_SITE_ID" NUMBER, 
	"RESULTS_UPDATED_DATE" DATE, 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	"RECON_KEY" VARCHAR2(1000), 
	"WORK_QUEUE_ID" NUMBER, 
	 CONSTRAINT "DMT_POZ_SUP_ADDR_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- 2026-07-08 conformance tranche: rename must precede the index DDL below
-- (a pre-existing database still has the old column when the index runs).
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_POZ_SUP_ADDR_TFM_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_POZ_SUP_ADDR_TFM_TBL" RENAME COLUMN "STATUS" TO "TFM_STATUS"';
  end if;
end;
/



COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - identity column (GENERATED ALWAYS).';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_POZ_SUP_ADDR_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when FBDI generator runs';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."FUSION_PARTY_SITE_ID" IS 'Fusion internal PARTY_SITE_ID - populated by BIP reconciliation';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."RESULTS_UPDATED_DATE" IS 'Timestamp of last BIP reconciliation update';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten. Prefixed: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_POZ_SUP_ADDR_TFM_TBL"  IS 'Supplier address transformed. Run-specific data â€” one row per staging row per run attempt. No key prefix applied (addresses use VENDOR_NAME + PARTY_SITE_NAME as natural key). Reconciliation populated by BIP. Interface table: POZ_SUP_ADDRESSES_INT.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_POZ_SUP_ADDR_TFM_TBL' and column_name = 'RECON_KEY';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_POZ_SUP_ADDR_TFM_TBL" ADD ("RECON_KEY" VARCHAR2(1000))';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_ADDR_TFM_N1" ON "DMT_POZ_SUP_ADDR_TFM_TBL" ("RUN_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_ADDR_TFM_N2" ON "DMT_POZ_SUP_ADDR_TFM_TBL" ("RUN_ID", "TFM_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."TFM_STATUS" IS 'Transform lifecycle: STAGED > GENERATED > LOADED / FAILED.';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."RECON_KEY" IS 'Pre-concatenated business key (run prefix included) that BIP reconciliation matches against Fusion rows.';

-- ---------------------------------------------------------------------------
-- 2026-07-09 conformance review F11: the supplier tables carried two index
-- numbering schemes (DMT_POZ_SUP_ADDR_TFM_TBL_N* and DMT_POZ_SUP_ADDR_TFM_N* both in
-- flight, colliding at N1). Renumbered to the single clean per-table sequence
-- used by every other object table; old non-conforming names are dropped by
-- the guarded block below, then the clean set is (re)created.
-- ---------------------------------------------------------------------------
declare
  l_n    pls_integer;
  l_cols varchar2(400);
begin
  select count(*) into l_n from user_indexes where index_name = 'DMT_POZ_SUP_ADDR_TFM_TBL_N1';
  if l_n > 0 then execute immediate 'DROP INDEX "DMT_POZ_SUP_ADDR_TFM_TBL_N1"'; end if;
  select count(*) into l_n from user_indexes where index_name = 'DMT_POZ_SUP_ADDR_TFM_TBL_N4';
  if l_n > 0 then execute immediate 'DROP INDEX "DMT_POZ_SUP_ADDR_TFM_TBL_N4"'; end if;
  select listagg(column_name,',') within group (order by column_position) into l_cols
    from user_ind_columns where index_name = 'DMT_POZ_SUP_ADDR_TFM_N3';
  if l_cols = 'RECON_KEY' then execute immediate 'DROP INDEX "DMT_POZ_SUP_ADDR_TFM_N3"'; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_ADDR_TFM_N3" ON "DMT_POZ_SUP_ADDR_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_ADDR_TFM_N4" ON "DMT_POZ_SUP_ADDR_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_ADDR_TFM_N5" ON "DMT_POZ_SUP_ADDR_TFM_TBL" ("RECON_KEY")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
