-- DMT_PERSON_NAME_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PERSON_NAME_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PERSON_NAME_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" VARCHAR2(240), 
	"EFFECTIVE_END_DATE" VARCHAR2(240), 
	"PERSON_NUMBER" VARCHAR2(240), 
	"LEGISLATION_CODE" VARCHAR2(240), 
	"NAME_TYPE" VARCHAR2(240), 
	"LAST_NAME" VARCHAR2(240), 
	"FIRST_NAME" VARCHAR2(240), 
	"MIDDLE_NAMES" VARCHAR2(240), 
	"TITLE" VARCHAR2(240), 
	"SUFFIX" VARCHAR2(240), 
	"PRE_NAME_ADJUNCT" VARCHAR2(240), 
	"KNOWN_AS" VARCHAR2(240), 
	"DISPLAY_NAME" VARCHAR2(240), 
	"ORDER_NAME" VARCHAR2(240), 
	"LIST_NAME" VARCHAR2(240), 
	"FULL_NAME" VARCHAR2(240), 
	"NAME_INFORMATION1" VARCHAR2(240), 
	"NAME_INFORMATION2" VARCHAR2(240), 
	"NAME_INFORMATION3" VARCHAR2(240), 
	"NAME_INFORMATION4" VARCHAR2(240), 
	"NAME_INFORMATION5" VARCHAR2(240), 
	"NAME_INFORMATION6" VARCHAR2(240), 
	"NAME_INFORMATION7" VARCHAR2(240), 
	"NAME_INFORMATION8" VARCHAR2(240), 
	"NAME_INFORMATION9" VARCHAR2(240), 
	"NAME_INFORMATION10" VARCHAR2(240), 
	"NAME_INFORMATION11" VARCHAR2(240), 
	"NAME_INFORMATION12" VARCHAR2(240), 
	"NAME_INFORMATION13" VARCHAR2(240), 
	"NAME_INFORMATION14" VARCHAR2(240), 
	"NAME_INFORMATION15" VARCHAR2(240), 
	"NAME_INFORMATION16" VARCHAR2(240), 
	"NAME_INFORMATION17" VARCHAR2(240), 
	"NAME_INFORMATION18" VARCHAR2(240), 
	"NAME_INFORMATION19" VARCHAR2(240), 
	"NAME_INFORMATION20" VARCHAR2(240), 
	"NAME_INFORMATION21" VARCHAR2(240), 
	"NAME_INFORMATION22" VARCHAR2(240), 
	"NAME_INFORMATION23" VARCHAR2(240), 
	"NAME_INFORMATION24" VARCHAR2(240), 
	"NAME_INFORMATION25" VARCHAR2(240), 
	"NAME_INFORMATION26" VARCHAR2(240), 
	"NAME_INFORMATION27" VARCHAR2(240), 
	"NAME_INFORMATION28" VARCHAR2(240), 
	"NAME_INFORMATION29" VARCHAR2(240), 
	"NAME_INFORMATION30" VARCHAR2(240), 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_PERSON_NAME_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PERSON_NAME_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_PERSON_NAME_STG_SEQ. Populated by DB default, never supplied by user.';
COMMENT ON COLUMN "DMT_PERSON_NAME_STG_TBL"."PERSON_NUMBER" IS 'Worker person number â€” FK to Worker business object';
COMMENT ON COLUMN "DMT_PERSON_NAME_STG_TBL"."NAME_TYPE" IS 'Name type: GLOBAL, LOCAL, etc.';
COMMENT ON COLUMN "DMT_PERSON_NAME_STG_TBL"."SOURCE_ID" IS 'Natural key from source system';
COMMENT ON COLUMN "DMT_PERSON_NAME_STG_TBL"."STATUS" IS 'NEW > RETRY > TRANSFORMED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_PERSON_NAME_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten.';
COMMENT ON TABLE "DMT_PERSON_NAME_STG_TBL"  IS 'Person name staging. Raw user-loaded data only. Run-specific data in DMT_PERSON_NAME_TFM_TBL. HDL business object: PersonName.';
