-- DMT_LOOKUP_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_LOOKUP_TBL" 
   (	"LOOKUP_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"LOOKUP_TYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"LOOKUP_CODE" VARCHAR2(500) NOT NULL ENABLE, 
	"LOOKUP_VALUE" VARCHAR2(500), 
	"LOOKUP_VALUE2" VARCHAR2(500), 
	"DESCRIPTION" VARCHAR2(500), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATED_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("LOOKUP_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DMT_LOOKUP_UK" UNIQUE ("LOOKUP_TYPE", "LOOKUP_CODE", "LOOKUP_VALUE")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_LOOKUP_TBL"."LOOKUP_TYPE" IS 'Category: LEDGER, DATA_ACCESS_SET, etc.';
COMMENT ON COLUMN "DMT_LOOKUP_TBL"."LOOKUP_CODE" IS 'Name/code (e.g. ledger name)';
COMMENT ON COLUMN "DMT_LOOKUP_TBL"."LOOKUP_VALUE" IS 'Primary value (e.g. ledger_id)';
COMMENT ON COLUMN "DMT_LOOKUP_TBL"."LOOKUP_VALUE2" IS 'Secondary value (e.g. data_access_set_id)';
COMMENT ON TABLE "DMT_LOOKUP_TBL"  IS 'Generic lookup table for Fusion instance-specific values (ledgers, data access sets, etc.). Populated via BIP reports at pipeline start.';
