-- DMT_AP_PAY_TERM_LINE_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_AP_PAY_TERM_LINE_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_AP_PAY_TERM_LINE_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"SOURCE_GROUP_ID" NUMBER, 
	"SEQUENCE_NUM" NUMBER, 
	"DUE_PERCENT" NUMBER, 
	"DUE_AMOUNT" NUMBER, 
	"DUE_DAYS" NUMBER, 
	"DUE_DATE" DATE, 
	"DISCOUNT_PERCENT" NUMBER, 
	"DISCOUNT_DAYS" NUMBER, 
	"DISCOUNT_PERCENT_2" NUMBER, 
	"DISCOUNT_DAYS_2" NUMBER, 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'', 
	"ERROR_TEXT" CLOB, 
	"RESULTS_UPDATED_DATE" DATE, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_AP_PAY_TERM_LINE_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
