-- DMT_HZ_LOCATIONS_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_HZ_LOCATIONS_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_HZ_LOCATIONS_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"BATCH_ID" NUMBER, 
	"LOCATION_ORIG_SYSTEM" VARCHAR2(30), 
	"LOCATION_ORIG_SYSTEM_REFERENCE" VARCHAR2(240), 
	"INSERT_UPDATE_FLAG" VARCHAR2(1), 
	"COUNTRY" VARCHAR2(60), 
	"ADDRESS1" VARCHAR2(240), 
	"ADDRESS2" VARCHAR2(240), 
	"ADDRESS3" VARCHAR2(240), 
	"ADDRESS4" VARCHAR2(240), 
	"CITY" VARCHAR2(60), 
	"STATE" VARCHAR2(60), 
	"PROVINCE" VARCHAR2(60), 
	"COUNTY" VARCHAR2(60), 
	"POSTAL_CODE" VARCHAR2(60), 
	"POSTAL_PLUS4_CODE" VARCHAR2(10), 
	"LOCATION_LANGUAGE" VARCHAR2(4), 
	"DESCRIPTION" VARCHAR2(2000), 
	"SHORT_DESCRIPTION" VARCHAR2(240), 
	"SALES_TAX_GEOCODE" VARCHAR2(30), 
	"SALES_TAX_INSIDE_CITY_LIMITS" VARCHAR2(1), 
	"TIMEZONE_CODE" VARCHAR2(50), 
	"ADDRESS1_STD" VARCHAR2(240), 
	"ADAPTER_CONTENT_SOURCE" VARCHAR2(30), 
	"ADDR_VALID_STATUS_CODE" VARCHAR2(30), 
	"DATE_VALIDATED" DATE, 
	"ADDRESS_EFFECTIVE_DATE" DATE, 
	"ADDRESS_EXPIRATION_DATE" DATE, 
	"VALIDATED_FLAG" VARCHAR2(1), 
	"DO_NOT_VALIDATE_FLAG" VARCHAR2(1), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"FUSION_LOCATION_ID" NUMBER, 
	"RESULTS_UPDATED_DATE" DATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_HZ_LOCATIONS_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_HZ_LOCATIONS_TFM_TBL_N1" ON "DMT_HZ_LOCATIONS_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_HZ_LOCATIONS_TFM_TBL_N4" ON "DMT_HZ_LOCATIONS_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_HZ_LOCATIONS_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - from DMT_HZ_LOCATIONS_TFM_SEQ';
COMMENT ON COLUMN "DMT_HZ_LOCATIONS_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_HZ_LOCATIONS_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_HZ_LOCATIONS_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when FBDI generator runs';
COMMENT ON COLUMN "DMT_HZ_LOCATIONS_TFM_TBL"."LOCATION_ORIG_SYSTEM_REFERENCE" IS 'Location reference with run prefix applied: NVL(prefix,'''') || stg.LOCATION_ORIG_SYSTEM_REFERENCE';
COMMENT ON COLUMN "DMT_HZ_LOCATIONS_TFM_TBL"."FUSION_LOCATION_ID" IS 'Fusion internal LOCATION_ID â€” populated by BIP reconciliation';
COMMENT ON COLUMN "DMT_HZ_LOCATIONS_TFM_TBL"."STATUS" IS 'STAGED > GENERATED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_HZ_LOCATIONS_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step â€” never overwritten. Prefixes: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_HZ_LOCATIONS_TFM_TBL"  IS 'Customer location transformed. Run-specific â€” one row per staging row per run attempt. LOCATION_ORIG_SYSTEM_REFERENCE has run prefix applied. Reconciliation populated by BIP.';
