-- DMT_POZ_SUP_SITE_ASSN_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_POZ_SUP_SITE_ASSN_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_POZ_SUP_SITE_ASSN_TFM_ID_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"IMPORT_ACTION" VARCHAR2(10), 
	"VENDOR_NAME" VARCHAR2(360) NOT NULL ENABLE, 
	"VENDOR_SITE_CODE" VARCHAR2(15) NOT NULL ENABLE, 
	"PROCUREMENT_BUSINESS_UNIT_NAME" VARCHAR2(240) NOT NULL ENABLE, 
	"BUSINESS_UNIT_NAME" VARCHAR2(240) NOT NULL ENABLE, 
	"BILL_TO_BU_NAME" VARCHAR2(240), 
	"SHIP_TO_LOCATION_CODE" VARCHAR2(60), 
	"BILL_TO_LOCATION_CODE" VARCHAR2(60), 
	"ALLOW_AWT_FLAG" VARCHAR2(1), 
	"AWT_GROUP_NAME" VARCHAR2(25), 
	"ACCTS_PAY_CONCAT_SEGMENTS" VARCHAR2(250), 
	"PREPAY_CONCAT_SEGMENTS" VARCHAR2(250), 
	"FUTURE_DATED_CONCAT_SEGMENTS" VARCHAR2(250), 
	"DISTRIBUTION_SET_NAME" VARCHAR2(50), 
	"INACTIVE_DATE" DATE, 
	"FUSION_ASSIGNMENT_ID" NUMBER, 
	"RESULTS_UPDATED_DATE" DATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_POZ_SUP_SITE_ASSN_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_SITE_ASSN_TFM_TBL_N1" ON "DMT_POZ_SUP_SITE_ASSN_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_SITE_ASSN_TFM_TBL_N4" ON "DMT_POZ_SUP_SITE_ASSN_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - from DMT_POZ_SUP_SITE_ASSN_TFM_ID_SEQ';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_POZ_SUP_SITE_ASSN_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when FBDI generator runs';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."FUSION_ASSIGNMENT_ID" IS 'Fusion internal assignment ID - populated by BIP reconciliation';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."RESULTS_UPDATED_DATE" IS 'Timestamp of last BIP reconciliation update';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."STATUS" IS 'STAGED > GENERATED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten. Prefixed: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"  IS 'Supplier site assignment transformed. Run-specific data â€” one row per staging row per run attempt. All columns copied verbatim. Reconciliation populated by BIP. Interface table: POZ_SITE_ASSIGNMENTS_INT.';
