-- DMT_FND_LOOKUP_TYPE_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_FND_LOOKUP_TYPE_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_FND_LOOKUP_TYPE_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"SOURCE_GROUP_ID" NUMBER, 
	"LOOKUP_TYPE" VARCHAR2(30), 
	"MEANING" VARCHAR2(80), 
	"DESCRIPTION" VARCHAR2(240), 
	"MODULE_TYPE" VARCHAR2(30), 
	"MODULE_KEY" VARCHAR2(30), 
	"REFERENCE_GROUP_NAME" VARCHAR2(240), 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'', 
	"ERROR_TEXT" CLOB, 
	"RESULTS_UPDATED_DATE" DATE, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_FND_LKP_TYPE_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
