-- DMT_W2_BAL_DTL_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_W2_BAL_DTL_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_W2_BAL_DTL_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"PERSON_NUMBER" VARCHAR2(240) NOT NULL ENABLE, 
	"BALANCE_NAME" VARCHAR2(240), 
	"DIMENSION_NAME" VARCHAR2(240), 
	"CONTEXT_NAME" VARCHAR2(240), 
	"CONTEXT_VALUE" VARCHAR2(240), 
	"VALUE" VARCHAR2(240), 
	"CURRENCY_CODE" VARCHAR2(240), 
	"LEGISLATIVE_DATA_GROUP_NAME" VARCHAR2(240), 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(240), 
	"PAYROLL_RELATIONSHIP_NUMBER" VARCHAR2(240), 
	"RESULTS_UPDATED_DATE" DATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_W2_BAL_DTL_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
