-- DMT_GL_CALENDAR_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_GL_CALENDAR_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_GL_CALENDAR_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"PERIOD_SET_NAME" VARCHAR2(15), 
	"PERIOD_NAME" VARCHAR2(15), 
	"PERIOD_TYPE" VARCHAR2(15), 
	"PERIOD_YEAR" NUMBER, 
	"PERIOD_NUM" NUMBER, 
	"QUARTER_NUM" NUMBER, 
	"ENTERED_PERIOD_NAME" VARCHAR2(15), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"YEAR_START_DATE" DATE, 
	"QUARTER_START_DATE" DATE, 
	"ADJUSTMENT_PERIOD_FLAG" VARCHAR2(1), 
	"DESCRIPTION" VARCHAR2(240), 
	"CONFIRMATION_STATUS" VARCHAR2(30), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'', 
	"ERROR_TEXT" CLOB, 
	"RESULTS_UPDATED_DATE" DATE, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_GL_CALENDAR_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
