-- DMT_WORK_SCHED_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_WORK_SCHED_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_WORK_SCHED_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"WORK_SCHEDULE_NAME" VARCHAR2(240) NOT NULL ENABLE, 
	"SCHEDULE_START_DATE" VARCHAR2(240), 
	"SCHEDULE_END_DATE" VARCHAR2(240), 
	"WORK_SCHEDULE_TYPE" VARCHAR2(240), 
	"DESCRIPTION" VARCHAR2(240), 
	"LEGISLATIVE_DATA_GROUP_NAME" VARCHAR2(240), 
	"RESULTS_UPDATED_DATE" DATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"PERSON_NUMBER" VARCHAR2(30), 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_WORK_SCHED_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
