-- DMT_SCENARIO_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_SCENARIO_TBL" 
   (	"SCENARIO_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"SCENARIO_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500), 
	"STATUS" VARCHAR2(30) DEFAULT ''ACTIVE'', 
	"CREATED_BY" VARCHAR2(100), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"LAST_UPDATED_DATE" DATE, 
	 PRIMARY KEY ("SCENARIO_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DMT_SCENARIO_UK" UNIQUE ("SCENARIO_NAME")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
