-- DMT_PJC_EXPENDITURES_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PJC_EXPENDITURES_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PJC_EXPENDITURES_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"TRANSACTION_TYPE" VARCHAR2(240), 
	"BUSINESS_UNIT" VARCHAR2(240), 
	"ORG_ID" NUMBER, 
	"USER_TRANSACTION_SOURCE" VARCHAR2(240), 
	"TRANSACTION_SOURCE_ID" NUMBER, 
	"DOCUMENT_NAME" VARCHAR2(240), 
	"DOCUMENT_ID" NUMBER, 
	"DOC_ENTRY_NAME" VARCHAR2(240), 
	"DOC_ENTRY_ID" NUMBER, 
	"BATCH_NAME" VARCHAR2(240), 
	"BATCH_ENDING_DATE" DATE, 
	"BATCH_DESCRIPTION" VARCHAR2(240), 
	"EXPENDITURE_ITEM_DATE" DATE, 
	"PERSON_NUMBER" VARCHAR2(30), 
	"PERSON_NAME" VARCHAR2(2000), 
	"PERSON_ID" NUMBER, 
	"HCM_ASSIGNMENT_NAME" VARCHAR2(240), 
	"HCM_ASSIGNMENT_ID" NUMBER, 
	"PROJECT_NUMBER" VARCHAR2(25), 
	"PROJECT_NAME" VARCHAR2(240), 
	"PROJECT_ID" NUMBER, 
	"TASK_NUMBER" VARCHAR2(100), 
	"TASK_NAME" VARCHAR2(240), 
	"TASK_ID" NUMBER, 
	"EXPENDITURE_TYPE" VARCHAR2(240), 
	"EXPENDITURE_TYPE_ID" NUMBER, 
	"ORGANIZATION_NAME" VARCHAR2(240), 
	"ORGANIZATION_ID" NUMBER, 
	"NON_LABOR_RESOURCE" VARCHAR2(240), 
	"NON_LABOR_RESOURCE_ID" NUMBER, 
	"NON_LABOR_RESOURCE_ORG" VARCHAR2(240), 
	"NON_LABOR_RESOURCE_ORG_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"UNIT_OF_MEASURE_NAME" VARCHAR2(240), 
	"UNIT_OF_MEASURE" VARCHAR2(240), 
	"WORK_TYPE" VARCHAR2(240), 
	"WORK_TYPE_ID" NUMBER, 
	"BILLABLE_FLAG" VARCHAR2(1), 
	"CAPITALIZABLE_FLAG" VARCHAR2(1), 
	"ACCRUAL_FLAG" VARCHAR2(1), 
	"SUPPLIER_NUMBER" VARCHAR2(30), 
	"SUPPLIER_NAME" VARCHAR2(360), 
	"VENDOR_ID" NUMBER, 
	"INVENTORY_ITEM_NAME" VARCHAR2(300), 
	"INVENTORY_ITEM_ID" NUMBER, 
	"ORIG_TRANSACTION_REFERENCE" VARCHAR2(240), 
	"UNMATCHED_NEGATIVE_TXN_FLAG" VARCHAR2(1), 
	"REVERSED_ORIG_TXN_REFERENCE" VARCHAR2(240), 
	"EXPENDITURE_COMMENT" VARCHAR2(240), 
	"GL_DATE" DATE, 
	"DENOM_CURRENCY_CODE" VARCHAR2(15), 
	"DENOM_CURRENCY" VARCHAR2(15), 
	"DENOM_RAW_COST" NUMBER, 
	"DENOM_BURDENED_COST" NUMBER, 
	"RAW_COST_CR_CCID" NUMBER, 
	"RAW_COST_CR_ACCOUNT" VARCHAR2(2000), 
	"RAW_COST_DR_CCID" NUMBER, 
	"RAW_COST_DR_ACCOUNT" VARCHAR2(2000), 
	"BURDENED_COST_CR_CCID" NUMBER, 
	"BURDENED_COST_CR_ACCOUNT" VARCHAR2(2000), 
	"BURDENED_COST_DR_CCID" NUMBER, 
	"BURDENED_COST_DR_ACCOUNT" VARCHAR2(2000), 
	"BURDEN_COST_CR_CCID" NUMBER, 
	"BURDEN_COST_CR_ACCOUNT" VARCHAR2(2000), 
	"BURDEN_COST_DR_CCID" NUMBER, 
	"BURDEN_COST_DR_ACCOUNT" VARCHAR2(2000), 
	"ACCT_CURRENCY_CODE" VARCHAR2(15), 
	"ACCT_CURRENCY" VARCHAR2(15), 
	"ACCT_RAW_COST" NUMBER, 
	"ACCT_BURDENED_COST" NUMBER, 
	"ACCT_RATE_TYPE" VARCHAR2(30), 
	"ACCT_RATE_DATE" DATE, 
	"ACCT_RATE_DATE_TYPE" VARCHAR2(30), 
	"ACCT_EXCHANGE_RATE" NUMBER, 
	"ACCT_EXCHANGE_ROUNDING_LIMIT" NUMBER, 
	"RECEIPT_CURRENCY_CODE" VARCHAR2(15), 
	"RECEIPT_CURRENCY" VARCHAR2(15), 
	"RECEIPT_CURRENCY_AMOUNT" NUMBER, 
	"RECEIPT_EXCHANGE_RATE" NUMBER, 
	"CONVERTED_FLAG" VARCHAR2(1), 
	"CONTEXT_CATEGORY" VARCHAR2(30), 
	"USER_DEF_ATTRIBUTE1" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE2" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE3" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE4" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE5" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE6" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE7" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE8" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE9" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE10" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE1" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE2" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE3" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE4" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE5" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE6" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE7" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE8" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE9" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE10" VARCHAR2(240), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"CONTRACT_NUMBER" VARCHAR2(240), 
	"CONTRACT_NAME" VARCHAR2(300), 
	"CONTRACT_ID" NUMBER, 
	"FUNDING_SOURCE_NUMBER" VARCHAR2(240), 
	"FUNDING_SOURCE_NAME" VARCHAR2(240), 
	"PROJECT_ROLE_NAME" VARCHAR2(240), 
	"PROJECT_ROLE_ID" NUMBER, 
	"FUSION_EXPENDITURE_ITEM_ID" NUMBER, 
	"RESULTS_UPDATED_DATE" DATE, 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	"RECON_KEY" VARCHAR2(1000), 
	 CONSTRAINT "DMT_PJC_EXPENDITURES_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PJC_EXPENDITURES_TFM_TBL_N1" ON "DMT_PJC_EXPENDITURES_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PJC_EXPENDITURES_TFM_TBL_N4" ON "DMT_PJC_EXPENDITURES_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PJC_EXPENDITURES_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - from DMT_PJC_EXPENDITURES_TFM_SEQ';
COMMENT ON COLUMN "DMT_PJC_EXPENDITURES_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_PJC_EXPENDITURES_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_PJC_EXPENDITURES_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when FBDI generator runs';
COMMENT ON COLUMN "DMT_PJC_EXPENDITURES_TFM_TBL"."PROJECT_NUMBER" IS 'Project number with dependent prefix applied: NVL(dep_prefix,'''') || stg.PROJECT_NUMBER';
COMMENT ON COLUMN "DMT_PJC_EXPENDITURES_TFM_TBL"."FUSION_EXPENDITURE_ITEM_ID" IS 'Fusion internal EXPENDITURE_ITEM_ID â€” populated by BIP reconciliation';
COMMENT ON COLUMN "DMT_PJC_EXPENDITURES_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step â€” never overwritten. Prefixes: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_PJC_EXPENDITURES_TFM_TBL"  IS 'Expenditures transformed. Run-specific â€” one row per staging row per run attempt. PROJECT_NUMBER has dependent prefix applied. Reconciliation populated by BIP.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_PJC_EXPENDITURES_TFM_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_PJC_EXPENDITURES_TFM_TBL" RENAME COLUMN "STATUS" TO "TFM_STATUS"';
  end if;
end;
/
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_PJC_EXPENDITURES_TFM_TBL' and column_name = 'RECON_KEY';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_PJC_EXPENDITURES_TFM_TBL" ADD ("RECON_KEY" VARCHAR2(1000))';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_PJC_EXPENDITURES_TFM_N1" ON "DMT_PJC_EXPENDITURES_TFM_TBL" ("RUN_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_PJC_EXPENDITURES_TFM_N2" ON "DMT_PJC_EXPENDITURES_TFM_TBL" ("RUN_ID", "TFM_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_PJC_EXPENDITURES_TFM_N3" ON "DMT_PJC_EXPENDITURES_TFM_TBL" ("RECON_KEY")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PJC_EXPENDITURES_TFM_TBL"."TFM_STATUS" IS 'Transform lifecycle: STAGED > GENERATED > LOADED / FAILED.';
COMMENT ON COLUMN "DMT_PJC_EXPENDITURES_TFM_TBL"."RECON_KEY" IS 'Pre-concatenated business key (run prefix included) that BIP reconciliation matches against Fusion rows.';
