-- DMT_AP_INVOICES_INT_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_AP_INVOICES_INT_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_AP_INVOICES_INT_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"INVOICE_ID" NUMBER, 
	"OPERATING_UNIT" VARCHAR2(240), 
	"SOURCE" VARCHAR2(80), 
	"INVOICE_NUM" VARCHAR2(50), 
	"INVOICE_AMOUNT" NUMBER, 
	"INVOICE_DATE" DATE, 
	"VENDOR_NAME" VARCHAR2(360), 
	"VENDOR_NUM" VARCHAR2(30), 
	"VENDOR_SITE_CODE" VARCHAR2(240), 
	"INVOICE_CURRENCY_CODE" VARCHAR2(15), 
	"PAYMENT_CURRENCY_CODE" VARCHAR2(15), 
	"DESCRIPTION" VARCHAR2(240), 
	"GROUP_ID" VARCHAR2(80), 
	"INVOICE_TYPE_LOOKUP_CODE" VARCHAR2(25), 
	"LEGAL_ENTITY_NAME" VARCHAR2(240), 
	"CUST_REGISTRATION_NUMBER" VARCHAR2(50), 
	"CUST_REGISTRATION_CODE" VARCHAR2(50), 
	"FIRST_PARTY_REGISTRATION_NUM" VARCHAR2(50), 
	"THIRD_PARTY_REGISTRATION_NUM" VARCHAR2(50), 
	"TERMS_NAME" VARCHAR2(50), 
	"TERMS_DATE" DATE, 
	"GOODS_RECEIVED_DATE" DATE, 
	"INVOICE_RECEIVED_DATE" DATE, 
	"GL_DATE" DATE, 
	"PAYMENT_METHOD_CODE" VARCHAR2(30), 
	"PAY_GROUP_LOOKUP_CODE" VARCHAR2(25), 
	"EXCLUSIVE_PAYMENT_FLAG" VARCHAR2(1), 
	"AMOUNT_APPLICABLE_TO_DISCOUNT" NUMBER, 
	"PREPAY_NUM" VARCHAR2(50), 
	"PREPAY_LINE_NUM" NUMBER, 
	"PREPAY_APPLY_AMOUNT" NUMBER, 
	"PREPAY_GL_DATE" DATE, 
	"INVOICE_INCLUDES_PREPAY_FLAG" VARCHAR2(1), 
	"EXCHANGE_RATE_TYPE" VARCHAR2(30), 
	"EXCHANGE_DATE" DATE, 
	"EXCHANGE_RATE" NUMBER, 
	"ACCTS_PAY_CODE_CONCATENATED" VARCHAR2(250), 
	"DOC_CATEGORY_CODE" VARCHAR2(30), 
	"VOUCHER_NUM" VARCHAR2(50), 
	"REQUESTER_FIRST_NAME" VARCHAR2(150), 
	"REQUESTER_LAST_NAME" VARCHAR2(150), 
	"REQUESTER_EMPLOYEE_NUM" VARCHAR2(30), 
	"DELIVERY_CHANNEL_CODE" VARCHAR2(30), 
	"BANK_CHARGE_BEARER" VARCHAR2(30), 
	"REMIT_TO_SUPPLIER_NAME" VARCHAR2(360), 
	"REMIT_TO_SUPPLIER_NUM" VARCHAR2(30), 
	"REMIT_TO_ADDRESS_NAME" VARCHAR2(240), 
	"PAYMENT_PRIORITY" NUMBER, 
	"SETTLEMENT_PRIORITY" VARCHAR2(30), 
	"UNIQUE_REMITTANCE_IDENTIFIER" VARCHAR2(256), 
	"URI_CHECK_DIGIT" VARCHAR2(2), 
	"PAYMENT_REASON_CODE" VARCHAR2(30), 
	"PAYMENT_REASON_COMMENTS" VARCHAR2(240), 
	"REMITTANCE_MESSAGE1" VARCHAR2(150), 
	"REMITTANCE_MESSAGE2" VARCHAR2(150), 
	"REMITTANCE_MESSAGE3" VARCHAR2(150), 
	"AWT_GROUP_NAME" VARCHAR2(80), 
	"SHIP_TO_LOCATION" VARCHAR2(60), 
	"TAXATION_COUNTRY" VARCHAR2(2), 
	"DOCUMENT_SUB_TYPE" VARCHAR2(240), 
	"TAX_INVOICE_INTERNAL_SEQ" VARCHAR2(150), 
	"SUPPLIER_TAX_INVOICE_NUMBER" VARCHAR2(150), 
	"TAX_INVOICE_RECORDING_DATE" DATE, 
	"SUPPLIER_TAX_INVOICE_DATE" DATE, 
	"SUPPLIER_TAX_EXCHANGE_RATE" NUMBER, 
	"PORT_OF_ENTRY_CODE" VARCHAR2(30), 
	"CORRECTION_YEAR" NUMBER, 
	"CORRECTION_PERIOD" VARCHAR2(15), 
	"IMPORT_DOCUMENT_NUMBER" VARCHAR2(50), 
	"IMPORT_DOCUMENT_DATE" DATE, 
	"CONTROL_AMOUNT" NUMBER, 
	"CALC_TAX_DURING_IMPORT_FLAG" VARCHAR2(1), 
	"ADD_TAX_TO_INV_AMT_FLAG" VARCHAR2(1), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"GLOBAL_ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"GLOBAL_ATTRIBUTE1" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE2" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE3" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE4" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE5" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE6" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE7" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE8" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE9" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE10" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE11" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE12" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE13" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE14" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE15" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE16" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE17" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE18" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE19" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE20" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE_NUMBER1" NUMBER, 
	"GLOBAL_ATTRIBUTE_NUMBER2" NUMBER, 
	"GLOBAL_ATTRIBUTE_NUMBER3" NUMBER, 
	"GLOBAL_ATTRIBUTE_NUMBER4" NUMBER, 
	"GLOBAL_ATTRIBUTE_NUMBER5" NUMBER, 
	"GLOBAL_ATTRIBUTE_DATE1" DATE, 
	"GLOBAL_ATTRIBUTE_DATE2" DATE, 
	"GLOBAL_ATTRIBUTE_DATE3" DATE, 
	"GLOBAL_ATTRIBUTE_DATE4" DATE, 
	"GLOBAL_ATTRIBUTE_DATE5" DATE, 
	"IMAGE_DOCUMENT_URI" VARCHAR2(4000), 
	"EXTERNAL_BANK_ACCOUNT_NUMBER" VARCHAR2(100), 
	"EXT_BANK_ACCOUNT_IBAN_NUMBER" VARCHAR2(50), 
	"REQUESTER_EMAIL_ADDRESS" VARCHAR2(240), 
	"INTERCOMPANY_CROSSCHARGE_FLAG" VARCHAR2(1), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STG_STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_AP_INVOICES_INT_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_AP_INV_STG_N1" ON "DMT_AP_INVOICES_INT_STG_TBL" ("STG_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_AP_INVOICES_INT_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_AP_INVOICES_INT_STG_SEQ';
COMMENT ON COLUMN "DMT_AP_INVOICES_INT_STG_TBL"."INVOICE_NUM" IS 'Invoice number from source system â€” prefix applied in TFM table';
COMMENT ON COLUMN "DMT_AP_INVOICES_INT_STG_TBL"."VENDOR_NUM" IS 'Supplier number â€” expected to have DEPENDENT_PREFIX applied when looking up migrated supplier';
COMMENT ON COLUMN "DMT_AP_INVOICES_INT_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors â€” appended at each step, never overwritten. Prefixed: [PRE_VALIDATION] [TRANSFORM_ERROR] [FUSION_ERROR].';
COMMENT ON TABLE "DMT_AP_INVOICES_INT_STG_TBL"  IS 'AP Invoice header staging. Raw user data only. Run-specific data in DMT_AP_INVOICES_INT_TFM_TBL. FBDI interface: AP_INVOICES_INTERFACE. CSV: ApInvoicesInterface.csv.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_AP_INVOICES_INT_STG_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_AP_INVOICES_INT_STG_TBL" RENAME COLUMN "STATUS" TO "STG_STATUS"';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_AP_INVOICES_INT_STG_N1" ON "DMT_AP_INVOICES_INT_STG_TBL" ("SCENARIO_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_AP_INVOICES_INT_STG_TBL"."STG_STATUS" IS 'Staging lifecycle: NEW > TRANSFORMED / FAILED. Forward-only, never reset; errors accumulate in ERROR_TEXT.';
