-- DMT_CE_BRANCH_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_CE_BRANCH_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_CE_BRANCH_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"SOURCE_GROUP_ID" NUMBER, 
	"SOURCE_LINE_ID" NUMBER, 
	"BANK_NAME" VARCHAR2(360), 
	"BRANCH_NAME" VARCHAR2(360), 
	"BRANCH_NUMBER" VARCHAR2(30), 
	"BIC_CODE" VARCHAR2(15), 
	"ALTERNATE_NAME" VARCHAR2(320), 
	"DESCRIPTION" VARCHAR2(240), 
	"EFT_SWIFT_CODE" VARCHAR2(12), 
	"COUNTRY_CODE" VARCHAR2(2), 
	"ADDRESS_LINE1" VARCHAR2(240), 
	"CITY" VARCHAR2(60), 
	"STATE" VARCHAR2(60), 
	"POSTAL_CODE" VARCHAR2(30), 
	"END_DATE" DATE, 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'', 
	"ERROR_TEXT" CLOB, 
	"RESULTS_UPDATED_DATE" DATE, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_CE_BRANCH_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
