-- DMT_PJF_TASKS_TFM_TBL (generated from ATP 2026-07-03)

-- Identity-PK conversion (accepted coding standard 2026-07-08: "Identity
-- columns for keys; sequences only for shared, meaningful values").
-- In-place conversion of an existing non-identity column is NOT possible on
-- Oracle 26ai: every ALTER TABLE ... MODIFY variant raises ORA-30673, even on
-- an empty table. So a pre-identity table is converted by drop-and-recreate --
-- EMPTY tables only. A populated table is never dropped (staging/transform rows
-- are never deleted): the block raises with the manual rebuild recipe instead.
-- Deploy this file via db/install.sql: any FK dropped by the CASCADE here is
-- re-added by the FK DDL later in the same install run.
declare
  l_exists   pls_integer;
  l_identity pls_integer;
  l_rows     pls_integer;
begin
  select count(*) into l_exists from user_tables
  where  table_name = 'DMT_PJF_TASKS_TFM_TBL';
  if l_exists = 1 then
    select count(*) into l_identity from user_tab_identity_cols
    where  table_name = 'DMT_PJF_TASKS_TFM_TBL' and column_name = 'TFM_SEQUENCE_ID';
    if l_identity = 0 then
      execute immediate 'select count(*) from "DMT_PJF_TASKS_TFM_TBL" where rownum = 1' into l_rows;
      if l_rows = 0 then
        execute immediate 'drop table "DMT_PJF_TASKS_TFM_TBL" cascade constraints purge';
      else
        raise_application_error(-20001,
          'DMT_PJF_TASKS_TFM_TBL: cannot convert a populated table to an identity PK in place (ORA-30673). ' ||
          'Manual rebuild required: create a swap table with TFM_SEQUENCE_ID GENERATED BY DEFAULT ON NULL AS IDENTITY, ' ||
          'insert the rows preserving ids, rename, re-add constraints, then ALTER ... MODIFY to GENERATED ALWAYS (START WITH LIMIT VALUE).');
      end if;
    end if;
  end if;
end;
/

begin
  execute immediate 'CREATE TABLE "DMT_PJF_TASKS_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"PROJECT_NAME" VARCHAR2(240), 
	"PROJECT_NUMBER" VARCHAR2(25), 
	"TASK_NAME" VARCHAR2(240), 
	"TASK_NUMBER" VARCHAR2(100), 
	"TASK_DESCRIPTION" VARCHAR2(2000), 
	"PARENT_TASK_NUMBER" VARCHAR2(100), 
	"PLANNING_START_DATE" DATE, 
	"PLANNING_END_DATE" DATE, 
	"MILESTONE_FLAG" VARCHAR2(1), 
	"CRITICAL_FLAG" VARCHAR2(1), 
	"CHARGEABLE_FLAG" VARCHAR2(1), 
	"BILLABLE_FLAG" VARCHAR2(1), 
	"CAPITALIZABLE_FLAG" VARCHAR2(1), 
	"LIMIT_TO_TXN_CONTROLS_FLAG" VARCHAR2(1), 
	"SOURCE_TASK_REFERENCE" VARCHAR2(25), 
	"SOURCE_APPLICATION_CODE" VARCHAR2(30), 
	"SERVICE_TYPE_CODE" VARCHAR2(30), 
	"WORK_TYPE_ID" VARCHAR2(240), 
	"MANAGER_PERSON_ID" VARCHAR2(240), 
	"ALLOW_CROSS_CHARGE_FLAG" VARCHAR2(1), 
	"CC_PROCESS_LABOR_FLAG" VARCHAR2(1), 
	"CC_PROCESS_NL_FLAG" VARCHAR2(1), 
	"RECEIVE_PROJECT_INVOICE_FLAG" VARCHAR2(1), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"ATTRIBUTE21" VARCHAR2(150), 
	"ATTRIBUTE22" VARCHAR2(150), 
	"ATTRIBUTE23" VARCHAR2(150), 
	"ATTRIBUTE24" VARCHAR2(150), 
	"ATTRIBUTE25" VARCHAR2(150), 
	"ATTRIBUTE26" VARCHAR2(150), 
	"ATTRIBUTE27" VARCHAR2(150), 
	"ATTRIBUTE28" VARCHAR2(150), 
	"ATTRIBUTE29" VARCHAR2(150), 
	"ATTRIBUTE30" VARCHAR2(150), 
	"ATTRIBUTE31" VARCHAR2(150), 
	"ATTRIBUTE32" VARCHAR2(150), 
	"ATTRIBUTE33" VARCHAR2(150), 
	"ATTRIBUTE34" VARCHAR2(150), 
	"ATTRIBUTE35" VARCHAR2(150), 
	"ATTRIBUTE36" VARCHAR2(150), 
	"ATTRIBUTE37" VARCHAR2(150), 
	"ATTRIBUTE38" VARCHAR2(150), 
	"ATTRIBUTE39" VARCHAR2(150), 
	"ATTRIBUTE40" VARCHAR2(150), 
	"ATTRIBUTE41" VARCHAR2(150), 
	"ATTRIBUTE42" VARCHAR2(150), 
	"ATTRIBUTE43" VARCHAR2(150), 
	"ATTRIBUTE44" VARCHAR2(150), 
	"ATTRIBUTE45" VARCHAR2(150), 
	"ATTRIBUTE46" VARCHAR2(150), 
	"ATTRIBUTE47" VARCHAR2(150), 
	"ATTRIBUTE48" VARCHAR2(150), 
	"ATTRIBUTE49" VARCHAR2(150), 
	"ATTRIBUTE50" VARCHAR2(150), 
	"ATTRIBUTE1_NUMBER" NUMBER, 
	"ATTRIBUTE2_NUMBER" NUMBER, 
	"ATTRIBUTE3_NUMBER" NUMBER, 
	"ATTRIBUTE4_NUMBER" NUMBER, 
	"ATTRIBUTE5_NUMBER" NUMBER, 
	"ATTRIBUTE6_NUMBER" NUMBER, 
	"ATTRIBUTE7_NUMBER" NUMBER, 
	"ATTRIBUTE8_NUMBER" NUMBER, 
	"ATTRIBUTE9_NUMBER" NUMBER, 
	"ATTRIBUTE10_NUMBER" NUMBER, 
	"ATTRIBUTE11_NUMBER" NUMBER, 
	"ATTRIBUTE12_NUMBER" NUMBER, 
	"ATTRIBUTE13_NUMBER" NUMBER, 
	"ATTRIBUTE14_NUMBER" NUMBER, 
	"ATTRIBUTE15_NUMBER" NUMBER, 
	"ATTRIBUTE1_DATE" DATE, 
	"ATTRIBUTE2_DATE" DATE, 
	"ATTRIBUTE3_DATE" DATE, 
	"ATTRIBUTE4_DATE" DATE, 
	"ATTRIBUTE5_DATE" DATE, 
	"ATTRIBUTE6_DATE" DATE, 
	"ATTRIBUTE7_DATE" DATE, 
	"ATTRIBUTE8_DATE" DATE, 
	"ATTRIBUTE9_DATE" DATE, 
	"ATTRIBUTE10_DATE" DATE, 
	"ATTRIBUTE11_DATE" DATE, 
	"ATTRIBUTE12_DATE" DATE, 
	"ATTRIBUTE13_DATE" DATE, 
	"ATTRIBUTE14_DATE" DATE, 
	"ATTRIBUTE15_DATE" DATE, 
	"ORGANIZATION_NAME" VARCHAR2(240), 
	"FINANCIAL_TASK" VARCHAR2(1), 
	"PLANNED_EFFORT" VARCHAR2(240), 
	"PLANNED_DURATION" VARCHAR2(240), 
	"REQMNT_CODE" VARCHAR2(30), 
	"SPRINT" VARCHAR2(240), 
	"PRIORITY" VARCHAR2(30), 
	"SCHEDULE_MODE" VARCHAR2(30), 
	"BASELINE_START_DATE" DATE, 
	"BASELINE_FINISH_DATE" DATE, 
	"BASELINE_EFFORT" VARCHAR2(240), 
	"BASELINE_DURATION" VARCHAR2(240), 
	"BASELINE_ALLOCATION" VARCHAR2(240), 
	"CONSTRAINT_TYPE" VARCHAR2(30), 
	"CONSTRAINT_DATE" DATE, 
	"BASELINE_LABOR_COST_AMOUNT" VARCHAR2(240), 
	"BASELINE_LABOR_BILLED_AMOUNT" VARCHAR2(240), 
	"BASELINE_EXPENSE_COST_AMOUNT" VARCHAR2(240), 
	"PROCESSING_MODE" VARCHAR2(30), 
	"FUSION_TASK_ID" NUMBER, 
	"RESULTS_UPDATED_DATE" DATE, 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	"RECON_KEY" VARCHAR2(1000), 
	"WORK_QUEUE_ID" NUMBER, 
	 CONSTRAINT "DMT_PJF_TASKS_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- 2026-07-08 conformance tranche: rename must precede the index DDL below
-- (a pre-existing database still has the old column when the index runs).
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_PJF_TASKS_TFM_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_PJF_TASKS_TFM_TBL" RENAME COLUMN "STATUS" TO "TFM_STATUS"';
  end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PJF_TASKS_TFM_TBL_N1" ON "DMT_PJF_TASKS_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PJF_TASKS_TFM_TBL_N4" ON "DMT_PJF_TASKS_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PJF_TASKS_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - GENERATED ALWAYS AS IDENTITY';
COMMENT ON COLUMN "DMT_PJF_TASKS_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_PJF_TASKS_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_PJF_TASKS_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when FBDI generator runs';
COMMENT ON COLUMN "DMT_PJF_TASKS_TFM_TBL"."PROJECT_NUMBER" IS 'Project number with run prefix applied';
COMMENT ON COLUMN "DMT_PJF_TASKS_TFM_TBL"."TASK_NUMBER" IS 'Task number with run prefix applied';
COMMENT ON COLUMN "DMT_PJF_TASKS_TFM_TBL"."FUSION_TASK_ID" IS 'Fusion internal TASK_ID â€” populated by BIP reconciliation';
COMMENT ON COLUMN "DMT_PJF_TASKS_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step â€” never overwritten. Prefixes: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_PJF_TASKS_TFM_TBL"  IS 'Project tasks transformed. Run-specific â€” one row per staging row per run attempt. PROJECT_NUMBER and TASK_NUMBER have run prefix applied. Reconciliation populated by BIP.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_PJF_TASKS_TFM_TBL' and column_name = 'RECON_KEY';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_PJF_TASKS_TFM_TBL" ADD ("RECON_KEY" VARCHAR2(1000))';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_PJF_TASKS_TFM_N1" ON "DMT_PJF_TASKS_TFM_TBL" ("RUN_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_PJF_TASKS_TFM_N2" ON "DMT_PJF_TASKS_TFM_TBL" ("RUN_ID", "TFM_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_PJF_TASKS_TFM_N3" ON "DMT_PJF_TASKS_TFM_TBL" ("RECON_KEY")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PJF_TASKS_TFM_TBL"."TFM_STATUS" IS 'Transform lifecycle: STAGED > GENERATED > LOADED / FAILED.';
COMMENT ON COLUMN "DMT_PJF_TASKS_TFM_TBL"."RECON_KEY" IS 'Pre-concatenated business key (run prefix included) that BIP reconciliation matches against Fusion rows.';

-- WORK_QUEUE_ID (work-queue-ID granularity foundation, accepted 2026-07-20;
-- docs/FIX_PLAN.md item 1). Guarded in-file ALTER so an existing DB converges
-- via db/install.sql (the CREATE above carries it for fresh installs). FK is
-- in db/tables/_foreign_keys.sql. NULLABLE for now; NOT NULL deferred.
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where table_name = 'DMT_PJF_TASKS_TFM_TBL' and column_name = 'WORK_QUEUE_ID';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_PJF_TASKS_TFM_TBL" ADD ("WORK_QUEUE_ID" NUMBER)';
  end if;
end;
/
COMMENT ON COLUMN "DMT_PJF_TASKS_TFM_TBL"."WORK_QUEUE_ID" IS 'The work queue item (DMT_WORK_QUEUE_TBL.QUEUE_ID) that processed this record. FK in _foreign_keys.sql. Stamped at generation; unit of per-work-item processing (design section 7, accepted 2026-07-20).';
