-- DMT_WORK_SCHED_DTL_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_WORK_SCHED_DTL_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_WORK_SCHED_DTL_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"WORK_SCHEDULE_NAME" VARCHAR2(240), 
	"SHIFT_NAME" VARCHAR2(240), 
	"SHIFT_DATE" VARCHAR2(240), 
	"START_TIME" VARCHAR2(240), 
	"END_TIME" VARCHAR2(240), 
	"DURATION" VARCHAR2(240), 
	"UNIT_OF_MEASURE" VARCHAR2(240), 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_WORK_SCHED_DTL_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_WORK_SCHED_DTL_STG_TBL"."STATUS" IS 'NEW > RETRY > TRANSFORMED > LOADED / FAILED';
COMMENT ON TABLE "DMT_WORK_SCHED_DTL_STG_TBL"  IS 'WorkScheduleShift staging. HDL business object: WorkScheduleShift.';
