-- DMT_GL_INTERFACE_TFM_TBL (generated from ATP 2026-07-03)

-- Identity-PK conversion (accepted coding standard 2026-07-08: "Identity
-- columns for keys; sequences only for shared, meaningful values").
-- In-place conversion of an existing non-identity column is NOT possible on
-- Oracle 26ai: every ALTER TABLE ... MODIFY variant (GENERATED ALWAYS,
-- GENERATED BY DEFAULT ON NULL) raises ORA-30673, even on an empty table
-- (probed on dmt2-local 2026-07-08). So a pre-identity table is converted by
-- drop-and-recreate -- EMPTY tables only. A populated table is never dropped:
-- the block raises with the manual data-preserving rebuild recipe instead.
-- Deploy this file via db/install.sql: any FK dropped by the CASCADE here is
-- re-added by tables/_foreign_keys.sql later in the same install run.
declare
  l_exists   pls_integer;
  l_identity pls_integer;
  l_rows     pls_integer;
begin
  select count(*) into l_exists from user_tables
  where  table_name = 'DMT_GL_INTERFACE_TFM_TBL';
  if l_exists = 1 then
    select count(*) into l_identity from user_tab_identity_cols
    where  table_name = 'DMT_GL_INTERFACE_TFM_TBL' and column_name = 'TFM_SEQUENCE_ID';
    if l_identity = 0 then
      execute immediate 'select count(*) from "DMT_GL_INTERFACE_TFM_TBL" where rownum = 1' into l_rows;
      if l_rows = 0 then
        execute immediate 'drop table "DMT_GL_INTERFACE_TFM_TBL" cascade constraints purge';
      else
        raise_application_error(-20001,
          'DMT_GL_INTERFACE_TFM_TBL: cannot convert a populated table to an identity PK in place (ORA-30673). ' ||
          'Manual rebuild required: create a swap table with TFM_SEQUENCE_ID GENERATED BY DEFAULT ON NULL AS IDENTITY, ' ||
          'insert the rows preserving ids, rename, re-add constraints, then ALTER ... MODIFY to GENERATED ALWAYS (START WITH LIMIT VALUE).');
      end if;
    end if;
  end if;
end;
/

begin
  execute immediate 'CREATE TABLE "DMT_GL_INTERFACE_TFM_TBL"
   (	"TFM_SEQUENCE_ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE,
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"JOURNAL_STATUS" VARCHAR2(50), 
	"LEDGER_NAME" VARCHAR2(240), 
	"ACCOUNTING_DATE" DATE, 
	"CURRENCY_CODE" VARCHAR2(15), 
	"DATE_CREATED" DATE, 
	"CREATED_BY" VARCHAR2(100), 
	"ACTUAL_FLAG" VARCHAR2(1), 
	"USER_JE_CATEGORY_NAME" VARCHAR2(25), 
	"USER_JE_SOURCE_NAME" VARCHAR2(25), 
	"CURRENCY_CONVERSION_DATE" DATE, 
	"USER_CURRENCY_CONVERSION_TYPE" VARCHAR2(30), 
	"CURRENCY_CONVERSION_RATE" NUMBER, 
	"SEGMENT1" VARCHAR2(25), 
	"SEGMENT2" VARCHAR2(25), 
	"SEGMENT3" VARCHAR2(25), 
	"SEGMENT4" VARCHAR2(25), 
	"SEGMENT5" VARCHAR2(25), 
	"SEGMENT6" VARCHAR2(25), 
	"SEGMENT7" VARCHAR2(25), 
	"SEGMENT8" VARCHAR2(25), 
	"SEGMENT9" VARCHAR2(25), 
	"SEGMENT10" VARCHAR2(25), 
	"SEGMENT11" VARCHAR2(25), 
	"SEGMENT12" VARCHAR2(25), 
	"SEGMENT13" VARCHAR2(25), 
	"SEGMENT14" VARCHAR2(25), 
	"SEGMENT15" VARCHAR2(25), 
	"SEGMENT16" VARCHAR2(25), 
	"SEGMENT17" VARCHAR2(25), 
	"SEGMENT18" VARCHAR2(25), 
	"SEGMENT19" VARCHAR2(25), 
	"SEGMENT20" VARCHAR2(25), 
	"SEGMENT21" VARCHAR2(25), 
	"SEGMENT22" VARCHAR2(25), 
	"SEGMENT23" VARCHAR2(25), 
	"SEGMENT24" VARCHAR2(25), 
	"SEGMENT25" VARCHAR2(25), 
	"SEGMENT26" VARCHAR2(25), 
	"SEGMENT27" VARCHAR2(25), 
	"SEGMENT28" VARCHAR2(25), 
	"SEGMENT29" VARCHAR2(25), 
	"SEGMENT30" VARCHAR2(25), 
	"ENTERED_DR" NUMBER, 
	"ENTERED_CR" NUMBER, 
	"ACCOUNTED_DR" NUMBER, 
	"ACCOUNTED_CR" NUMBER, 
	"REFERENCE1" VARCHAR2(100), 
	"REFERENCE2" VARCHAR2(240), 
	"REFERENCE4" VARCHAR2(100), 
	"REFERENCE5" VARCHAR2(240), 
	"REFERENCE6" VARCHAR2(100), 
	"REFERENCE7" VARCHAR2(100), 
	"REFERENCE8" VARCHAR2(100), 
	"REFERENCE10" VARCHAR2(240), 
	"STAT_AMOUNT" NUMBER, 
	"GROUP_ID" NUMBER, 
	"PERIOD_NAME" VARCHAR2(15), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"RESULTS_UPDATED_DATE" DATE, 
	"LAST_UPDATED_DATE" DATE, 
	"LEDGER_ID" VARCHAR2(100), 
	"REFERENCE3" VARCHAR2(240), 
	"REFERENCE9" VARCHAR2(240), 
	"REFERENCE21" VARCHAR2(240), 
	"REFERENCE22" VARCHAR2(240), 
	"REFERENCE23" VARCHAR2(240), 
	"REFERENCE24" VARCHAR2(240), 
	"REFERENCE25" VARCHAR2(240), 
	"REFERENCE26" VARCHAR2(240), 
	"REFERENCE27" VARCHAR2(240), 
	"REFERENCE28" VARCHAR2(240), 
	"REFERENCE29" VARCHAR2(240), 
	"REFERENCE30" VARCHAR2(240), 
	"CONTEXT2" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY3" VARCHAR2(150), 
	"CONTEXT3" VARCHAR2(150), 
	"ENCUMBRANCE_TYPE_ID" VARCHAR2(100), 
	"JGZZ_RECON_REF" VARCHAR2(240), 
	"JE_LINE_NUM" VARCHAR2(100), 
	"CHART_OF_ACCOUNTS_ID" VARCHAR2(100), 
	"FUNCTIONAL_CURRENCY_CODE" VARCHAR2(15), 
	"CODE_COMBINATION_ID" VARCHAR2(100), 
	"DATE_CREATED_IN_GL" VARCHAR2(100), 
	"WARNING_CODE" VARCHAR2(4), 
	"STATUS_DESCRIPTION" VARCHAR2(240), 
	"AVERAGE_JOURNAL_FLAG" VARCHAR2(1), 
	"ORIGINATING_BAL_SEG_VALUE" VARCHAR2(25), 
	"GL_SL_LINK_ID" VARCHAR2(100), 
	"GL_SL_LINK_TABLE" VARCHAR2(30), 
	"REFERENCE_DATE" VARCHAR2(100), 
	"USSGL_TRANSACTION_CODE" VARCHAR2(30), 
	"TRANSACTION_DATE" VARCHAR2(100), 
	"BALANCING_SEGMENT_VALUE" VARCHAR2(25), 
	"MANAGEMENT_SEGMENT_VALUE" VARCHAR2(25), 
	"INTERCOMPANY_SEGMENT_VALUE" VARCHAR2(25), 
	"INTERCOMPANY_MODE" VARCHAR2(1), 
	"CONTEXT4" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY5" VARCHAR2(150), 
	"CONTEXT5" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY6" VARCHAR2(150), 
	"CONTEXT6" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY7" VARCHAR2(150), 
	"CONTEXT7" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY8" VARCHAR2(150), 
	"CONTEXT8" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY9" VARCHAR2(150), 
	"CONTEXT9" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY10" VARCHAR2(150), 
	"CONTEXT10" VARCHAR2(150), 
	"GL_SL_LINK_KEY" VARCHAR2(100), 
	"SUBLEDGER_DOC_SEQUENCE_ID" VARCHAR2(100), 
	"SUBLEDGER_DOC_SEQUENCE_VALUE" VARCHAR2(240), 
	"REFERENCE_FLEX_NUM" VARCHAR2(100), 
	"REFERENCE11" VARCHAR2(240), 
	"REFERENCE12" VARCHAR2(240), 
	"REFERENCE13" VARCHAR2(240), 
	"REFERENCE14" VARCHAR2(240), 
	"REFERENCE15" VARCHAR2(240), 
	"REFERENCE16" VARCHAR2(240), 
	"REFERENCE17" VARCHAR2(240), 
	"REFERENCE18" VARCHAR2(240), 
	"REFERENCE19" VARCHAR2(240), 
	"REFERENCE20" VARCHAR2(240), 
	"CLEARING_COMPANY" VARCHAR2(240), 
	"CLEARING_DOMAIN" VARCHAR2(240), 
	"CLEARING_INTERCOMPANY" VARCHAR2(240), 
	"INVOICE_DATE" VARCHAR2(100), 
	"INVOICE_IDENTIFIER" VARCHAR2(50), 
	"INVOICE_AMOUNT" VARCHAR2(100), 
	"TAX_CODE" VARCHAR2(50), 
	"FUNDS_CHECK_INDICATOR" VARCHAR2(1), 
	"BUDGET_VERSION_ID" VARCHAR2(100), 
	"RUN_ID" NUMBER, 
	"RECON_KEY" VARCHAR2(1000), 
	"FUSION_JE_HEADER_ID" NUMBER, 
	"WORK_QUEUE_ID" NUMBER, 
	 CONSTRAINT "DMT_GL_INTERFACE_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_GL_INTERFACE_TFM_TBL' and column_name = 'RECON_KEY';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_GL_INTERFACE_TFM_TBL" ADD ("RECON_KEY" VARCHAR2(1000))';
  end if;
end;
/
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_GL_INTERFACE_TFM_TBL' and column_name = 'FUSION_JE_HEADER_ID';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_GL_INTERFACE_TFM_TBL" ADD ("FUSION_JE_HEADER_ID" NUMBER)';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_GL_INTERFACE_TFM_N1" ON "DMT_GL_INTERFACE_TFM_TBL" ("RUN_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_GL_INTERFACE_TFM_N2" ON "DMT_GL_INTERFACE_TFM_TBL" ("RUN_ID", "TFM_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_GL_INTERFACE_TFM_N3" ON "DMT_GL_INTERFACE_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_GL_INTERFACE_TFM_N4" ON "DMT_GL_INTERFACE_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_GL_INTERFACE_TFM_N5" ON "DMT_GL_INTERFACE_TFM_TBL" ("RECON_KEY")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_GL_INTERFACE_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - identity column (GENERATED ALWAYS). Populated by the DB, never supplied by user.';
COMMENT ON COLUMN "DMT_GL_INTERFACE_TFM_TBL"."TFM_STATUS" IS 'Transform lifecycle: STAGED > GENERATED > LOADED / FAILED.';
COMMENT ON COLUMN "DMT_GL_INTERFACE_TFM_TBL"."RECON_KEY" IS 'Pre-concatenated business key (run prefix included) that BIP reconciliation matches against Fusion rows.';
COMMENT ON COLUMN "DMT_GL_INTERFACE_TFM_TBL"."FUSION_JE_HEADER_ID" IS 'Fusion-assigned identifier captured from the Fusion base tables - written only by BIP reconciliation (positive proof of load).';

-- ---------------------------------------------------------------------------
-- 2026-07-09 conformance review F2 (STG/TFM infra-column dictionary, design
-- section 7 accepted 2026-07-08): TFM_STATUS is VARCHAR2(30) DEFAULT 'STAGED'
-- NOT NULL. Backfills any NULL statuses to the default, then converges a
-- pre-existing database; fresh installs get the shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_nullable varchar2(1);
begin
  select nullable into l_nullable from user_tab_columns
   where table_name = 'DMT_GL_INTERFACE_TFM_TBL' and column_name = 'TFM_STATUS';
  if l_nullable = 'Y' then
    execute immediate 'UPDATE "DMT_GL_INTERFACE_TFM_TBL" SET "TFM_STATUS" = ''STAGED'' WHERE "TFM_STATUS" IS NULL';
    execute immediate 'ALTER TABLE "DMT_GL_INTERFACE_TFM_TBL" MODIFY ("TFM_STATUS" DEFAULT ''STAGED'' NOT NULL)';
  end if;
end;
/

-- WORK_QUEUE_ID (work-queue-ID granularity foundation, accepted 2026-07-20;
-- docs/FIX_PLAN.md item 1). Guarded in-file ALTER so an existing DB converges
-- via db/install.sql (the CREATE above carries it for fresh installs). FK is
-- in db/tables/_foreign_keys.sql. NULLABLE for now; NOT NULL deferred.
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where table_name = 'DMT_GL_INTERFACE_TFM_TBL' and column_name = 'WORK_QUEUE_ID';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_GL_INTERFACE_TFM_TBL" ADD ("WORK_QUEUE_ID" NUMBER)';
  end if;
end;
/
COMMENT ON COLUMN "DMT_GL_INTERFACE_TFM_TBL"."WORK_QUEUE_ID" IS 'The work queue item (DMT_WORK_QUEUE_TBL.QUEUE_ID) that processed this record. FK in _foreign_keys.sql. Stamped at generation; unit of per-work-item processing (design section 7, accepted 2026-07-20).';
