-- DMT_FND_LOOKUP_TYPE_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_FND_LOOKUP_TYPE_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_FND_LOOKUP_TYPE_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"SOURCE_GROUP_ID" NUMBER, 
	"LOOKUP_TYPE" VARCHAR2(30), 
	"MEANING" VARCHAR2(80), 
	"DESCRIPTION" VARCHAR2(240), 
	"MODULE_TYPE" VARCHAR2(30), 
	"MODULE_KEY" VARCHAR2(30), 
	"REFERENCE_GROUP_NAME" VARCHAR2(240), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_FND_LKP_TYPE_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON TABLE "DMT_FND_LOOKUP_TYPE_STG_TBL"  IS 'Lookup Type Definitions staging. Raw user-loaded data. Run-specific data in DMT_FND_LOOKUP_TYPE_TFM_TBL.';
