-- DMT_HZ_ACCOUNTS_TFM_TBL (generated from ATP 2026-07-03)

-- Identity-PK conversion (accepted coding standard 2026-07-08: "Identity
-- columns for keys; sequences only for shared, meaningful values"). Customers
-- Wave-1 offline port 2026-07-09, mirroring the Stage D Suppliers conversion.
-- In-place conversion of an existing non-identity column is NOT possible on
-- Oracle 26ai (ORA-30673, even on an empty table), so a pre-identity table is
-- converted by drop-and-recreate -- EMPTY tables only. A populated table is
-- never dropped (staging rows are never deleted): the block raises with the
-- manual data-preserving rebuild recipe instead.
declare
  l_exists   pls_integer;
  l_identity pls_integer;
  l_rows     pls_integer;
begin
  select count(*) into l_exists from user_tables
  where  table_name = 'DMT_HZ_ACCOUNTS_TFM_TBL';
  if l_exists = 1 then
    select count(*) into l_identity from user_tab_identity_cols
    where  table_name = 'DMT_HZ_ACCOUNTS_TFM_TBL' and column_name = 'TFM_SEQUENCE_ID';
    if l_identity = 0 then
      execute immediate 'select count(*) from "DMT_HZ_ACCOUNTS_TFM_TBL" where rownum = 1' into l_rows;
      if l_rows = 0 then
        execute immediate 'drop table "DMT_HZ_ACCOUNTS_TFM_TBL" cascade constraints purge';
      else
        raise_application_error(-20001,
          'DMT_HZ_ACCOUNTS_TFM_TBL: cannot convert a populated table to an identity PK in place (ORA-30673). ' ||
          'Manual rebuild required: create a swap table with TFM_SEQUENCE_ID GENERATED BY DEFAULT ON NULL AS IDENTITY, ' ||
          'insert the rows preserving ids, rename, re-add constraints, then ALTER ... MODIFY to GENERATED ALWAYS (START WITH LIMIT VALUE).');
      end if;
    end if;
  end if;
end;
/

begin
  execute immediate 'CREATE TABLE "DMT_HZ_ACCOUNTS_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"BATCH_ID" NUMBER, 
	"CUST_ORIG_SYSTEM" VARCHAR2(30), 
	"CUST_ORIG_SYSTEM_REFERENCE" VARCHAR2(240), 
	"PARTY_ORIG_SYSTEM" VARCHAR2(30), 
	"PARTY_ORIG_SYSTEM_REFERENCE" VARCHAR2(240), 
	"ACCOUNT_NUMBER" VARCHAR2(30), 
	"INSERT_UPDATE_FLAG" VARCHAR2(1), 
	"CUSTOMER_TYPE" VARCHAR2(30), 
	"CUSTOMER_CLASS_CODE" VARCHAR2(30), 
	"ACCOUNT_NAME" VARCHAR2(240), 
	"ACCOUNT_ESTABLISHED_DATE" DATE, 
	"ACCOUNT_TERMINATION_DATE" DATE, 
	"REL_ORIG_SYSTEM" VARCHAR2(30), 
	"REL_ORIG_SYSTEM_REFERENCE" VARCHAR2(240), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"FUSION_CUST_ACCOUNT_ID" NUMBER, 
	"FUSION_ACCOUNT_NUMBER" VARCHAR2(30), 
	"RESULTS_UPDATED_DATE" DATE, 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	"RECON_KEY" VARCHAR2(1000), 
	 CONSTRAINT "DMT_HZ_ACCOUNTS_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- 2026-07-08 conformance tranche: rename must precede the index DDL below
-- (a pre-existing database still has the old column when the index runs).
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_HZ_ACCOUNTS_TFM_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_HZ_ACCOUNTS_TFM_TBL" RENAME COLUMN "STATUS" TO "TFM_STATUS"';
  end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_HZ_ACCOUNTS_TFM_TBL_N1" ON "DMT_HZ_ACCOUNTS_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_HZ_ACCOUNTS_TFM_TBL_N4" ON "DMT_HZ_ACCOUNTS_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_HZ_ACCOUNTS_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - identity column (GENERATED ALWAYS). Populated by the DB, never supplied by user';
COMMENT ON COLUMN "DMT_HZ_ACCOUNTS_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_HZ_ACCOUNTS_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_HZ_ACCOUNTS_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when FBDI generator runs';
COMMENT ON COLUMN "DMT_HZ_ACCOUNTS_TFM_TBL"."CUST_ORIG_SYSTEM_REFERENCE" IS 'Account reference with run prefix applied: NVL(prefix,'''') || stg.CUST_ORIG_SYSTEM_REFERENCE';
COMMENT ON COLUMN "DMT_HZ_ACCOUNTS_TFM_TBL"."FUSION_CUST_ACCOUNT_ID" IS 'Fusion internal CUST_ACCOUNT_ID â€” populated by BIP reconciliation';
COMMENT ON COLUMN "DMT_HZ_ACCOUNTS_TFM_TBL"."FUSION_ACCOUNT_NUMBER" IS 'Fusion-assigned account number â€” populated by BIP reconciliation';
COMMENT ON COLUMN "DMT_HZ_ACCOUNTS_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step â€” never overwritten. Prefixes: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_HZ_ACCOUNTS_TFM_TBL"  IS 'Customer account transformed. Run-specific â€” one row per staging row per run attempt. CUST_ORIG_SYSTEM_REFERENCE has run prefix applied. Reconciliation populated by BIP.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_HZ_ACCOUNTS_TFM_TBL' and column_name = 'RECON_KEY';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_HZ_ACCOUNTS_TFM_TBL" ADD ("RECON_KEY" VARCHAR2(1000))';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_HZ_ACCOUNTS_TFM_N1" ON "DMT_HZ_ACCOUNTS_TFM_TBL" ("RUN_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_HZ_ACCOUNTS_TFM_N2" ON "DMT_HZ_ACCOUNTS_TFM_TBL" ("RUN_ID", "TFM_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_HZ_ACCOUNTS_TFM_N3" ON "DMT_HZ_ACCOUNTS_TFM_TBL" ("RECON_KEY")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_HZ_ACCOUNTS_TFM_TBL"."TFM_STATUS" IS 'Transform lifecycle: STAGED > GENERATED > LOADED / FAILED.';
COMMENT ON COLUMN "DMT_HZ_ACCOUNTS_TFM_TBL"."RECON_KEY" IS 'Pre-concatenated business key (run prefix included) that BIP reconciliation matches against Fusion rows.';
