-- DMT_PJF_TEAM_MEMBERS_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PJF_TEAM_MEMBERS_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PJF_TEAM_MEMBERS_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"PROJECT_NAME" VARCHAR2(240), 
	"TEAM_MEMBER_NUMBER" VARCHAR2(30), 
	"TEAM_MEMBER_NAME" VARCHAR2(240), 
	"TEAM_MEMBER_EMAIL" VARCHAR2(240), 
	"PROJECT_ROLE_NAME" VARCHAR2(240), 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"TRACK_TIME_FLAG" VARCHAR2(1), 
	"ALLOCATION" NUMBER, 
	"EFFORT" NUMBER, 
	"COST_RATE" NUMBER, 
	"BILL_RATE" NUMBER, 
	"ASSIGNMENT_TYPE" VARCHAR2(30), 
	"BILLABLE_PERCENT" NUMBER, 
	"BILLABLE_PERCENT_REASON_CODE" VARCHAR2(30), 
	"RESULTS_UPDATED_DATE" DATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_PJF_TEAM_MEMBERS_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PJF_TEAM_MEMBERS_TFM_TBL_N1" ON "DMT_PJF_TEAM_MEMBERS_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PJF_TEAM_MEMBERS_TFM_TBL_N4" ON "DMT_PJF_TEAM_MEMBERS_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PJF_TEAM_MEMBERS_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - from DMT_PJF_TEAM_MEMBERS_TFM_SEQ';
COMMENT ON COLUMN "DMT_PJF_TEAM_MEMBERS_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_PJF_TEAM_MEMBERS_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_PJF_TEAM_MEMBERS_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when FBDI generator runs';
COMMENT ON COLUMN "DMT_PJF_TEAM_MEMBERS_TFM_TBL"."PROJECT_NAME" IS 'Project name â€” links team member to parent project';
COMMENT ON COLUMN "DMT_PJF_TEAM_MEMBERS_TFM_TBL"."STATUS" IS 'STAGED > GENERATED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_PJF_TEAM_MEMBERS_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step â€” never overwritten. Prefixes: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_PJF_TEAM_MEMBERS_TFM_TBL"  IS 'Project team members transformed. Run-specific â€” one row per staging row per run attempt. Reconciliation populated by BIP.';
