-- DMT_UPLOAD_OBJECT_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_UPLOAD_OBJECT_TBL" 
   (	"OBJECT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"OBJECT_CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"DISPLAY_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"PAGE_NUMBER" NUMBER NOT NULL ENABLE, 
	"STAGING_TABLE" VARCHAR2(100) NOT NULL ENABLE, 
	"CSV_FILENAME" VARCHAR2(100), 
	"DISPLAY_ORDER" NUMBER DEFAULT 0, 
	"PARENT_OBJECT_CODE" VARCHAR2(50), 
	"IS_ACTIVE" VARCHAR2(1) DEFAULT ''Y'', 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"FBDI_CSV_FILENAME" VARCHAR2(100), 
	 CONSTRAINT "DMT_UPLOAD_OBJ_ACTIVE_CK" CHECK (IS_ACTIVE IN (''Y'',''N'')) ENABLE, 
	 PRIMARY KEY ("OBJECT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DMT_UPLOAD_OBJ_UK" UNIQUE ("OBJECT_CODE")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "IDX_UPLOAD_OBJ_PAGE" ON "DMT_UPLOAD_OBJECT_TBL" ("PAGE_NUMBER")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_UPLOAD_OBJECT_TBL"."OBJECT_CODE" IS 'Unique object identifier, e.g. POZ_SUPPLIERS';
COMMENT ON COLUMN "DMT_UPLOAD_OBJECT_TBL"."STAGING_TABLE" IS 'Target staging table name, e.g. DMT_POZ_SUPPLIERS_STG_TBL';
COMMENT ON COLUMN "DMT_UPLOAD_OBJECT_TBL"."CSV_FILENAME" IS 'Expected filename in ZIP bundle, e.g. POZ_SUPPLIERS.csv';
COMMENT ON COLUMN "DMT_UPLOAD_OBJECT_TBL"."PARENT_OBJECT_CODE" IS 'Parent object code for child objects. NULL for top-level objects.';
COMMENT ON COLUMN "DMT_UPLOAD_OBJECT_TBL"."IS_ACTIVE" IS 'Y = available for upload, N = disabled';
COMMENT ON COLUMN "DMT_UPLOAD_OBJECT_TBL"."FBDI_CSV_FILENAME" IS 'CSV filename inside FBDI zip files (from CTL INFILE directive). Used for FBDI zip upload routing.';
COMMENT ON TABLE "DMT_UPLOAD_OBJECT_TBL"  IS 'Upload object registry. Maps object codes to staging tables and APEX pages. Drives select lists and ZIP bundle routing.';
