-- DMT_PERSON_NID_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PERSON_NID_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PERSON_NID_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" VARCHAR2(240), 
	"EFFECTIVE_END_DATE" VARCHAR2(240), 
	"PERSON_NUMBER" VARCHAR2(240), 
	"LEGISLATION_CODE" VARCHAR2(240), 
	"NATIONAL_IDENTIFIER_TYPE" VARCHAR2(240), 
	"NATIONAL_IDENTIFIER_NUMBER" VARCHAR2(240), 
	"ISSUE_DATE" VARCHAR2(240), 
	"EXPIRATION_DATE" VARCHAR2(240), 
	"PLACE_OF_ISSUE" VARCHAR2(240), 
	"PRIMARY_FLAG" VARCHAR2(240), 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_PERSON_NID_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PERSON_NID_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_PERSON_NID_STG_SEQ. Populated by DB default, never supplied by user.';
COMMENT ON COLUMN "DMT_PERSON_NID_STG_TBL"."PERSON_NUMBER" IS 'Worker person number â€” FK to Worker business object';
COMMENT ON COLUMN "DMT_PERSON_NID_STG_TBL"."NATIONAL_IDENTIFIER_TYPE" IS 'Identifier type: SSN, SIN, etc.';
COMMENT ON COLUMN "DMT_PERSON_NID_STG_TBL"."SOURCE_ID" IS 'Natural key from source system';
COMMENT ON COLUMN "DMT_PERSON_NID_STG_TBL"."STATUS" IS 'NEW > RETRY > TRANSFORMED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_PERSON_NID_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten.';
COMMENT ON TABLE "DMT_PERSON_NID_STG_TBL"  IS 'Person national identifier staging. Raw user-loaded data only. Run-specific data in DMT_PERSON_NID_TFM_TBL. HDL business object: PersonNationalIdentifier.';
