-- DMT_POZ_SUP_SITE_ASSN_TFM_TBL (generated from ATP 2026-07-03)

-- Identity-PK conversion (accepted coding standard 2026-07-08: "Identity
-- columns for keys; sequences only for shared, meaningful values").
-- In-place conversion of an existing non-identity column is NOT possible on
-- Oracle 26ai: every ALTER TABLE ... MODIFY variant (GENERATED ALWAYS,
-- GENERATED BY DEFAULT ON NULL) raises ORA-30673, even on an empty table
-- (probed on dmt2-local 2026-07-08). So a pre-identity table is converted by
-- drop-and-recreate -- EMPTY tables only. A populated table is never dropped
-- (staging rows are never deleted): the block raises with the manual
-- data-preserving rebuild recipe instead.
-- Deploy this file via db/install.sql: any FK dropped by the CASCADE here is
-- re-added by tables/_foreign_keys.sql later in the same install run.
declare
  l_exists   pls_integer;
  l_identity pls_integer;
  l_rows     pls_integer;
begin
  select count(*) into l_exists from user_tables
  where  table_name = 'DMT_POZ_SUP_SITE_ASSN_TFM_TBL';
  if l_exists = 1 then
    select count(*) into l_identity from user_tab_identity_cols
    where  table_name = 'DMT_POZ_SUP_SITE_ASSN_TFM_TBL' and column_name = 'TFM_SEQUENCE_ID';
    if l_identity = 0 then
      execute immediate 'select count(*) from "DMT_POZ_SUP_SITE_ASSN_TFM_TBL" where rownum = 1' into l_rows;
      if l_rows = 0 then
        execute immediate 'drop table "DMT_POZ_SUP_SITE_ASSN_TFM_TBL" cascade constraints purge';
      else
        raise_application_error(-20001,
          'DMT_POZ_SUP_SITE_ASSN_TFM_TBL: cannot convert a populated table to an identity PK in place (ORA-30673). ' ||
          'Manual rebuild required: create a swap table with TFM_SEQUENCE_ID GENERATED BY DEFAULT ON NULL AS IDENTITY, ' ||
          'insert the rows preserving ids, rename, re-add constraints, then ALTER ... MODIFY to GENERATED ALWAYS (START WITH LIMIT VALUE).');
      end if;
    end if;
  end if;
end;
/

begin
  execute immediate 'CREATE TABLE "DMT_POZ_SUP_SITE_ASSN_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"IMPORT_ACTION" VARCHAR2(10), 
	"VENDOR_NAME" VARCHAR2(360) NOT NULL ENABLE, 
	"VENDOR_SITE_CODE" VARCHAR2(15) NOT NULL ENABLE, 
	"PROCUREMENT_BUSINESS_UNIT_NAME" VARCHAR2(240) NOT NULL ENABLE, 
	"BUSINESS_UNIT_NAME" VARCHAR2(240) NOT NULL ENABLE, 
	"BILL_TO_BU_NAME" VARCHAR2(240), 
	"SHIP_TO_LOCATION_CODE" VARCHAR2(60), 
	"BILL_TO_LOCATION_CODE" VARCHAR2(60), 
	"ALLOW_AWT_FLAG" VARCHAR2(1), 
	"AWT_GROUP_NAME" VARCHAR2(25), 
	"ACCTS_PAY_CONCAT_SEGMENTS" VARCHAR2(250), 
	"PREPAY_CONCAT_SEGMENTS" VARCHAR2(250), 
	"FUTURE_DATED_CONCAT_SEGMENTS" VARCHAR2(250), 
	"DISTRIBUTION_SET_NAME" VARCHAR2(50), 
	"INACTIVE_DATE" DATE, 
	"FUSION_ASSIGNMENT_ID" NUMBER, 
	"RESULTS_UPDATED_DATE" DATE, 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	"RECON_KEY" VARCHAR2(1000), 
	 CONSTRAINT "DMT_POZ_SUP_SITE_ASSN_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_SITE_ASSN_TFM_TBL_N1" ON "DMT_POZ_SUP_SITE_ASSN_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_SITE_ASSN_TFM_TBL_N4" ON "DMT_POZ_SUP_SITE_ASSN_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - identity column (GENERATED ALWAYS).';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_POZ_SUP_SITE_ASSN_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when FBDI generator runs';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."FUSION_ASSIGNMENT_ID" IS 'Fusion internal assignment ID - populated by BIP reconciliation';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."RESULTS_UPDATED_DATE" IS 'Timestamp of last BIP reconciliation update';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten. Prefixed: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"  IS 'Supplier site assignment transformed. Run-specific data â€” one row per staging row per run attempt. All columns copied verbatim. Reconciliation populated by BIP. Interface table: POZ_SITE_ASSIGNMENTS_INT.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_POZ_SUP_SITE_ASSN_TFM_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_POZ_SUP_SITE_ASSN_TFM_TBL" RENAME COLUMN "STATUS" TO "TFM_STATUS"';
  end if;
end;
/
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_POZ_SUP_SITE_ASSN_TFM_TBL' and column_name = 'RECON_KEY';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_POZ_SUP_SITE_ASSN_TFM_TBL" ADD ("RECON_KEY" VARCHAR2(1000))';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_SITE_ASSN_TFM_N1" ON "DMT_POZ_SUP_SITE_ASSN_TFM_TBL" ("RUN_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_SITE_ASSN_TFM_N2" ON "DMT_POZ_SUP_SITE_ASSN_TFM_TBL" ("RUN_ID", "TFM_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_SITE_ASSN_TFM_N3" ON "DMT_POZ_SUP_SITE_ASSN_TFM_TBL" ("RECON_KEY")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."TFM_STATUS" IS 'Transform lifecycle: STAGED > GENERATED > LOADED / FAILED.';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_TFM_TBL"."RECON_KEY" IS 'Pre-concatenated business key (run prefix included) that BIP reconciliation matches against Fusion rows.';
