-- DMT_EGP_ITEM_CAT_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_EGP_ITEM_CAT_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_EGP_ITEM_CAT_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"TRANSACTION_TYPE" VARCHAR2(10), 
	"BATCH_ID" NUMBER, 
	"BATCH_NUMBER" VARCHAR2(40), 
	"ORGANIZATION_CODE" VARCHAR2(18), 
	"ITEM_NUMBER" VARCHAR2(300), 
	"CATEGORY_SET_NAME" VARCHAR2(30), 
	"CATEGORY_CODE" VARCHAR2(250), 
	"CATEGORY_NAME" VARCHAR2(250), 
	"OLD_CATEGORY_CODE" VARCHAR2(250), 
	"OLD_CATEGORY_NAME" VARCHAR2(250), 
	"SOURCE_SYSTEM_CODE" VARCHAR2(30), 
	"SOURCE_SYSTEM_REFERENCE" VARCHAR2(255), 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'', 
	"ERROR_TEXT" CLOB, 
	"RESULTS_UPDATED_DATE" DATE, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_EGP_ITEM_CAT_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
