-- DMT_MIGRATION_LOG (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_MIGRATION_LOG" 
   (	"MIGRATION_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"CHECKSUM" VARCHAR2(40), 
	"APPLIED_BY" VARCHAR2(128) DEFAULT USER, 
	"APPLIED_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	 CONSTRAINT "DMT_MIGRATION_LOG_PK" PRIMARY KEY ("MIGRATION_NAME")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
