-- DMT_PJF_TEAM_MEMBERS_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PJF_TEAM_MEMBERS_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PJF_TEAM_MEMBERS_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"PROJECT_NAME" VARCHAR2(240), 
	"TEAM_MEMBER_NUMBER" VARCHAR2(30), 
	"TEAM_MEMBER_NAME" VARCHAR2(240), 
	"TEAM_MEMBER_EMAIL" VARCHAR2(240), 
	"PROJECT_ROLE_NAME" VARCHAR2(240), 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"TRACK_TIME_FLAG" VARCHAR2(1), 
	"ALLOCATION" NUMBER, 
	"EFFORT" NUMBER, 
	"COST_RATE" NUMBER, 
	"BILL_RATE" NUMBER, 
	"ASSIGNMENT_TYPE" VARCHAR2(30), 
	"BILLABLE_PERCENT" NUMBER, 
	"BILLABLE_PERCENT_REASON_CODE" VARCHAR2(30), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_PJF_TEAM_MEMBERS_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PJF_TEAM_MEMBERS_STG_TBL_N1" ON "DMT_PJF_TEAM_MEMBERS_STG_TBL" ("STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PJF_TEAM_MEMBERS_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_PJF_TEAM_MEMBERS_STG_SEQ';
COMMENT ON COLUMN "DMT_PJF_TEAM_MEMBERS_STG_TBL"."PROJECT_NAME" IS 'Project name â€” links team member to parent project';
COMMENT ON COLUMN "DMT_PJF_TEAM_MEMBERS_STG_TBL"."TEAM_MEMBER_NUMBER" IS 'Employee/person number of the team member';
COMMENT ON COLUMN "DMT_PJF_TEAM_MEMBERS_STG_TBL"."STATUS" IS 'NEW > TRANSFORMED > LOADED / FAILED. RETRY = user override for selective reprocess.';
COMMENT ON COLUMN "DMT_PJF_TEAM_MEMBERS_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors â€” appended at each step, never overwritten. Prefixed: [PRE_VALIDATION] [TRANSFORM_ERROR] [FUSION_ERROR].';
COMMENT ON TABLE "DMT_PJF_TEAM_MEMBERS_STG_TBL"  IS 'Project team members staging. Raw user data only. Run-specific data in DMT_PJF_TEAM_MEMBERS_TFM_TBL. FBDI interface: PJF_PROJECT_PARTIES_INT. CSV: PjfProjectPartiesInt.csv.';
