-- DMT_PO_LINE_LOCS_INT_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PO_LINE_LOCS_INT_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PO_LINE_LOCS_INT_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"INTERFACE_LINE_LOCATION_KEY" VARCHAR2(50), 
	"INTERFACE_LINE_KEY" VARCHAR2(50), 
	"SHIPMENT_NUM" NUMBER, 
	"SHIP_TO_LOCATION" VARCHAR2(60), 
	"SHIP_TO_ORGANIZATION_CODE" VARCHAR2(18), 
	"AMOUNT" NUMBER, 
	"QUANTITY" NUMBER, 
	"NEED_BY_DATE" DATE, 
	"PROMISED_DATE" DATE, 
	"SECONDARY_QUANTITY" NUMBER, 
	"SECONDARY_UNIT_OF_MEASURE" VARCHAR2(18), 
	"DESTINATION_TYPE_CODE" VARCHAR2(25), 
	"ACCRUE_ON_RECEIPT_FLAG" VARCHAR2(1), 
	"ALLOW_SUBSTITUTE_RECEIPTS_FLAG" VARCHAR2(1), 
	"ASSESSABLE_VALUE" NUMBER, 
	"DAYS_EARLY_RECEIPT_ALLOWED" NUMBER, 
	"DAYS_LATE_RECEIPT_ALLOWED" NUMBER, 
	"ENFORCE_SHIP_TO_LOCATION_CODE" VARCHAR2(25), 
	"INSPECTION_REQUIRED_FLAG" VARCHAR2(1), 
	"RECEIPT_REQUIRED_FLAG" VARCHAR2(1), 
	"INVOICE_CLOSE_TOLERANCE" NUMBER, 
	"RECEIVE_CLOSE_TOLERANCE" NUMBER, 
	"QTY_RCV_TOLERANCE" NUMBER, 
	"QTY_RCV_EXCEPTION_CODE" VARCHAR2(25), 
	"RECEIPT_DAYS_EXCEPTION_CODE" VARCHAR2(25), 
	"RECEIVING_ROUTING" VARCHAR2(30), 
	"NOTE_TO_RECEIVER" VARCHAR2(1000), 
	"INPUT_TAX_CLASSIFICATION_CODE" VARCHAR2(30), 
	"LINE_INTENDED_USE" VARCHAR2(240), 
	"PRODUCT_CATEGORY" VARCHAR2(240), 
	"PRODUCT_FISC_CLASSIFICATION" VARCHAR2(240), 
	"PRODUCT_TYPE" VARCHAR2(240), 
	"TRX_BUSINESS_CATEGORY" VARCHAR2(240), 
	"USER_DEFINED_FISC_CLASS" VARCHAR2(30), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_DATE6" DATE, 
	"ATTRIBUTE_DATE7" DATE, 
	"ATTRIBUTE_DATE8" DATE, 
	"ATTRIBUTE_DATE9" DATE, 
	"ATTRIBUTE_DATE10" DATE, 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_TIMESTAMP1" DATE, 
	"ATTRIBUTE_TIMESTAMP2" DATE, 
	"ATTRIBUTE_TIMESTAMP3" DATE, 
	"ATTRIBUTE_TIMESTAMP4" DATE, 
	"ATTRIBUTE_TIMESTAMP5" DATE, 
	"ATTRIBUTE_TIMESTAMP6" DATE, 
	"ATTRIBUTE_TIMESTAMP7" DATE, 
	"ATTRIBUTE_TIMESTAMP8" DATE, 
	"ATTRIBUTE_TIMESTAMP9" DATE, 
	"ATTRIBUTE_TIMESTAMP10" DATE, 
	"FREIGHT_CARRIER" VARCHAR2(360), 
	"MODE_OF_TRANSPORT" VARCHAR2(80), 
	"SERVICE_LEVEL" VARCHAR2(80), 
	"FINAL_DISCHARGE_LOCATION_CODE" VARCHAR2(60), 
	"REQUESTED_SHIP_DATE" DATE, 
	"PROMISED_SHIP_DATE" DATE, 
	"REQUESTED_DELIVERY_DATE" DATE, 
	"PROMISED_DELIVERY_DATE" DATE, 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STG_STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_PO_LINE_LOCS_INT_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- 2026-07-08 conformance tranche: rename must precede the index DDL below
-- (a pre-existing database still has the old column when the index runs).
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_PO_LINE_LOCS_INT_STG_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_PO_LINE_LOCS_INT_STG_TBL" RENAME COLUMN "STATUS" TO "STG_STATUS"';
  end if;
end;
/

COMMENT ON COLUMN "DMT_PO_LINE_LOCS_INT_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_PO_LINE_LOCS_INT_STG_SEQ';
COMMENT ON COLUMN "DMT_PO_LINE_LOCS_INT_STG_TBL"."INTERFACE_LINE_LOCATION_KEY" IS 'Unique key for this shipment â€” links distributions back to this location';
COMMENT ON COLUMN "DMT_PO_LINE_LOCS_INT_STG_TBL"."INTERFACE_LINE_KEY" IS 'FK to line â€” must match DMT_PO_LINES_INT_STG_TBL.INTERFACE_LINE_KEY';
COMMENT ON TABLE "DMT_PO_LINE_LOCS_INT_STG_TBL"  IS 'Purchase Order line locations (shipments) staging. Raw user data only. FBDI interface: PO_LINE_LOCATIONS_INTERFACE. CSV: PoLineLocationsInterfaceOrder.csv.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
begin
  execute immediate 'CREATE INDEX "DMT_PO_LINE_LOCS_INT_STG_N1" ON "DMT_PO_LINE_LOCS_INT_STG_TBL" ("STG_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_PO_LINE_LOCS_INT_STG_N2" ON "DMT_PO_LINE_LOCS_INT_STG_TBL" ("SCENARIO_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PO_LINE_LOCS_INT_STG_TBL"."STG_STATUS" IS 'Staging lifecycle: NEW > TRANSFORMED / FAILED. Forward-only, never reset; errors accumulate in ERROR_TEXT.';
