-- DMT_CEMLI_SPLIT_CFG (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_CEMLI_SPLIT_CFG" 
   (	"CEMLI_CODE" VARCHAR2(60) NOT NULL ENABLE, 
	"TFM_TABLE" VARCHAR2(128) NOT NULL ENABLE, 
	"PARTITION_COLUMNS" VARCHAR2(500) NOT NULL ENABLE, 
	"LABEL_EXPRESSION" VARCHAR2(500) NOT NULL ENABLE, 
	"WHERE_TEMPLATE" VARCHAR2(4000) NOT NULL ENABLE, 
	"STATUS_COLUMN" VARCHAR2(30) DEFAULT ''STATUS'', 
	 CONSTRAINT "DMT_CEMLI_SPLIT_CFG_PK" PRIMARY KEY ("CEMLI_CODE")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
