-- DMT_PLAN_BUDGET_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PLAN_BUDGET_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PLAN_BUDGET_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"SCENARIO" VARCHAR2(240), 
	"VERSION" VARCHAR2(240), 
	"ENTITY" VARCHAR2(240), 
	"ACCOUNT" VARCHAR2(240), 
	"PERIOD" VARCHAR2(240), 
	"AMOUNT" NUMBER, 
	"CURRENCY" VARCHAR2(15), 
	"DATA_LOAD_DEFINITION_NAME" VARCHAR2(240), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_PLAN_BUDGET_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
