-- DMT_POR_REQ_LINES_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_POR_REQ_LINES_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_POR_REQ_LINES_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"INTERFACE_LINE_KEY" VARCHAR2(50), 
	"INTERFACE_HEADER_KEY" VARCHAR2(50), 
	"GROUP_CODE" VARCHAR2(30), 
	"DESTINATION_TYPE_CODE" VARCHAR2(25), 
	"DELIVER_TO_LOCATION_CODE" VARCHAR2(60), 
	"DESTINATION_ORGANIZATION_CODE" VARCHAR2(18), 
	"DESTINATION_SUBINVENTORY" VARCHAR2(10), 
	"REQUESTER_EMAIL_ADDR" VARCHAR2(240), 
	"ITEM_DESCRIPTION" VARCHAR2(240), 
	"CATEGORY_NAME" VARCHAR2(250), 
	"NEED_BY_DATE" VARCHAR2(240), 
	"ITEM_NUMBER" VARCHAR2(300), 
	"ITEM_REVISION" VARCHAR2(18), 
	"UOM_CODE" VARCHAR2(3), 
	"LINE_TYPE" VARCHAR2(30), 
	"QUANTITY" NUMBER, 
	"CURRENCY_CODE" VARCHAR2(15), 
	"CURRENCY_UNIT_PRICE" NUMBER, 
	"RATE" NUMBER, 
	"RATE_DATE" VARCHAR2(240), 
	"RATE_TYPE" VARCHAR2(30), 
	"SECONDARY_UOM_CODE" VARCHAR2(3), 
	"SECONDARY_QUANTITY" NUMBER, 
	"CURRENCY_AMOUNT" NUMBER, 
	"UN_NUMBER" VARCHAR2(25), 
	"HAZARD_CLASS" VARCHAR2(40), 
	"PRC_BU_NAME" VARCHAR2(240), 
	"SOURCE_DOC_HEADER_NUMBER" VARCHAR2(30), 
	"SOURCE_DOC_LINE_NUMBER" NUMBER, 
	"SUGGESTED_VENDOR_NAME" VARCHAR2(360), 
	"SUGGESTED_VENDOR_SITE" VARCHAR2(240), 
	"SUGGESTED_VENDOR_CONTACT" VARCHAR2(80), 
	"SUGGESTED_VENDOR_CONTACT_PHONE" VARCHAR2(30), 
	"SUGGESTED_VENDOR_CONTACT_FAX" VARCHAR2(30), 
	"SUGGESTED_VENDOR_CONTACT_EMAIL" VARCHAR2(1000), 
	"SUGGESTED_SUPPLIER_ITEM_NUM" VARCHAR2(300), 
	"SUGGESTED_BUYER_EMAIL_ADDR" VARCHAR2(240), 
	"AUTOSOURCE_FLAG" VARCHAR2(1), 
	"NEGOTIATED_BY_PREPARER_FLAG" VARCHAR2(1), 
	"NEGOTIATION_REQUIRED_FLAG" VARCHAR2(1), 
	"URGENT_FLAG" VARCHAR2(1), 
	"NEW_SUPPLIER_FLAG" VARCHAR2(1), 
	"NOTE_TO_BUYER" VARCHAR2(1000), 
	"NOTE_TO_RECEIVER" VARCHAR2(1000), 
	"TRX_BUSINESS_CATEGORY" VARCHAR2(240), 
	"TRX_BUSINESS_CATEGORY_NAME" VARCHAR2(240), 
	"PRODUCT_TYPE" VARCHAR2(240), 
	"PRODUCT_TYPE_NAME" VARCHAR2(80), 
	"PRODUCT_FISC_CLASSIFICATION" VARCHAR2(240), 
	"PRODUCT_FISC_CLASS_NAME" VARCHAR2(250), 
	"PRODUCT_CATEGORY" VARCHAR2(240), 
	"PRODUCT_CATEGORY_NAME" VARCHAR2(1996), 
	"LINE_INTENDED_USE" VARCHAR2(240), 
	"LINE_INTENDED_USE_NAME" VARCHAR2(250), 
	"USER_DEFINED_FISC_CLASS" VARCHAR2(240), 
	"USER_DEFINED_FISC_CLASS_NAME" VARCHAR2(240), 
	"TAX_CLASSIFICATION_CODE" VARCHAR2(50), 
	"TAX_CLASSIFICATION_NAME" VARCHAR2(80), 
	"ASSESSABLE_VALUE" NUMBER, 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"ATTRIBUTE_DATE1" VARCHAR2(240), 
	"ATTRIBUTE_DATE2" VARCHAR2(240), 
	"ATTRIBUTE_DATE3" VARCHAR2(240), 
	"ATTRIBUTE_DATE4" VARCHAR2(240), 
	"ATTRIBUTE_DATE5" VARCHAR2(240), 
	"ATTRIBUTE_DATE6" VARCHAR2(240), 
	"ATTRIBUTE_DATE7" VARCHAR2(240), 
	"ATTRIBUTE_DATE8" VARCHAR2(240), 
	"ATTRIBUTE_DATE9" VARCHAR2(240), 
	"ATTRIBUTE_DATE10" VARCHAR2(240), 
	"ATTRIBUTE_TIMESTAMP1" VARCHAR2(240), 
	"ATTRIBUTE_TIMESTAMP2" VARCHAR2(240), 
	"ATTRIBUTE_TIMESTAMP3" VARCHAR2(240), 
	"ATTRIBUTE_TIMESTAMP4" VARCHAR2(240), 
	"ATTRIBUTE_TIMESTAMP5" VARCHAR2(240), 
	"ATTRIBUTE_TIMESTAMP6" VARCHAR2(240), 
	"ATTRIBUTE_TIMESTAMP7" VARCHAR2(240), 
	"ATTRIBUTE_TIMESTAMP8" VARCHAR2(240), 
	"ATTRIBUTE_TIMESTAMP9" VARCHAR2(240), 
	"ATTRIBUTE_TIMESTAMP10" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"VENDOR_NUMBER" VARCHAR2(30), 
	"FIRST_PTY_REG_NUMBER" VARCHAR2(50), 
	"THIRD_PTY_REG_NUMBER" VARCHAR2(50), 
	"FINAL_DISCHARGE_LOC_CODE" VARCHAR2(60), 
	"UNIT_OF_MEASURE" VARCHAR2(25), 
	"SECONDARY_UNIT_OF_MEASURE" VARCHAR2(25), 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STG_STATUS" VARCHAR2(30) DEFAULT ''NEW'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_POR_REQ_LN_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- 2026-07-08 conformance tranche: rename must precede the index DDL below
-- (a pre-existing database still has the old column when the index runs).
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_POR_REQ_LINES_STG_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_POR_REQ_LINES_STG_TBL" RENAME COLUMN "STATUS" TO "STG_STATUS"';
  end if;
end;
/

COMMENT ON TABLE "DMT_POR_REQ_LINES_STG_TBL"  IS 'Requisition line staging. Raw user-loaded data.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
begin
  execute immediate 'CREATE INDEX "DMT_POR_REQ_LINES_STG_N1" ON "DMT_POR_REQ_LINES_STG_TBL" ("STG_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_POR_REQ_LINES_STG_N2" ON "DMT_POR_REQ_LINES_STG_TBL" ("SCENARIO_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_POR_REQ_LINES_STG_TBL"."STG_STATUS" IS 'Staging lifecycle: NEW > TRANSFORMED / FAILED. Forward-only, never reset; errors accumulate in ERROR_TEXT.';

-- ---------------------------------------------------------------------------
-- 2026-07-09 conformance review F2 (STG/TFM infra-column dictionary, design
-- section 7 accepted 2026-07-08): STG_STATUS is VARCHAR2(30) DEFAULT 'NEW'
-- NOT NULL. Backfills any NULL statuses to the default, then converges a
-- pre-existing database; fresh installs get the shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_nullable varchar2(1);
begin
  select nullable into l_nullable from user_tab_columns
   where table_name = 'DMT_POR_REQ_LINES_STG_TBL' and column_name = 'STG_STATUS';
  if l_nullable = 'Y' then
    execute immediate 'UPDATE "DMT_POR_REQ_LINES_STG_TBL" SET "STG_STATUS" = ''NEW'' WHERE "STG_STATUS" IS NULL';
    execute immediate 'ALTER TABLE "DMT_POR_REQ_LINES_STG_TBL" MODIFY ("STG_STATUS" DEFAULT ''NEW'' NOT NULL)';
  end if;
end;
/
