-- DMT_POZ_SUP_ADDR_STG_TBL (generated from ATP 2026-07-03)

-- Identity-PK conversion (accepted coding standard 2026-07-08: "Identity
-- columns for keys; sequences only for shared, meaningful values").
-- In-place conversion of an existing non-identity column is NOT possible on
-- Oracle 26ai: every ALTER TABLE ... MODIFY variant (GENERATED ALWAYS,
-- GENERATED BY DEFAULT ON NULL) raises ORA-30673, even on an empty table
-- (probed on dmt2-local 2026-07-08). So a pre-identity table is converted by
-- drop-and-recreate -- EMPTY tables only. A populated table is never dropped
-- (staging rows are never deleted): the block raises with the manual
-- data-preserving rebuild recipe instead.
-- Deploy this file via db/install.sql: any FK dropped by the CASCADE here is
-- re-added by tables/_foreign_keys.sql later in the same install run.
declare
  l_exists   pls_integer;
  l_identity pls_integer;
  l_rows     pls_integer;
begin
  select count(*) into l_exists from user_tables
  where  table_name = 'DMT_POZ_SUP_ADDR_STG_TBL';
  if l_exists = 1 then
    select count(*) into l_identity from user_tab_identity_cols
    where  table_name = 'DMT_POZ_SUP_ADDR_STG_TBL' and column_name = 'STG_SEQUENCE_ID';
    if l_identity = 0 then
      execute immediate 'select count(*) from "DMT_POZ_SUP_ADDR_STG_TBL" where rownum = 1' into l_rows;
      if l_rows = 0 then
        execute immediate 'drop table "DMT_POZ_SUP_ADDR_STG_TBL" cascade constraints purge';
      else
        raise_application_error(-20001,
          'DMT_POZ_SUP_ADDR_STG_TBL: cannot convert a populated table to an identity PK in place (ORA-30673). ' ||
          'Manual rebuild required: create a swap table with STG_SEQUENCE_ID GENERATED BY DEFAULT ON NULL AS IDENTITY, ' ||
          'insert the rows preserving ids, rename, re-add constraints, then ALTER ... MODIFY to GENERATED ALWAYS (START WITH LIMIT VALUE).');
      end if;
    end if;
  end if;
end;
/

begin
  execute immediate 'CREATE TABLE "DMT_POZ_SUP_ADDR_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE, 
	"IMPORT_ACTION" VARCHAR2(10), 
	"VENDOR_NAME" VARCHAR2(360), 
	"PARTY_SITE_NAME" VARCHAR2(240), 
	"PARTY_SITE_NAME_NEW" VARCHAR2(240), 
	"COUNTRY" VARCHAR2(2), 
	"ADDRESS_LINE1" VARCHAR2(240), 
	"ADDRESS_LINE2" VARCHAR2(240), 
	"ADDRESS_LINE3" VARCHAR2(240), 
	"ADDRESS_LINE4" VARCHAR2(240), 
	"ADDRESS_LINES_PHONETIC" VARCHAR2(560), 
	"ADDR_ELEMENT_ATTRIBUTE1" VARCHAR2(150), 
	"ADDR_ELEMENT_ATTRIBUTE2" VARCHAR2(150), 
	"ADDR_ELEMENT_ATTRIBUTE3" VARCHAR2(150), 
	"ADDR_ELEMENT_ATTRIBUTE4" VARCHAR2(150), 
	"ADDR_ELEMENT_ATTRIBUTE5" VARCHAR2(150), 
	"BUILDING" VARCHAR2(40), 
	"FLOOR_NUMBER" VARCHAR2(40), 
	"CITY" VARCHAR2(60), 
	"STATE" VARCHAR2(60), 
	"PROVINCE" VARCHAR2(60), 
	"COUNTY" VARCHAR2(60), 
	"POSTAL_CODE" VARCHAR2(20), 
	"POSTAL_PLUS4_CODE" VARCHAR2(20), 
	"ADDRESSEE" VARCHAR2(360), 
	"GLOBAL_LOCATION_NUMBER" VARCHAR2(40), 
	"PARTY_SITE_LANGUAGE" VARCHAR2(4), 
	"INACTIVE_DATE" DATE, 
	"PHONE_COUNTRY_CODE" VARCHAR2(10), 
	"PHONE_AREA_CODE" VARCHAR2(10), 
	"PHONE" VARCHAR2(40), 
	"PHONE_EXTENSION" VARCHAR2(20), 
	"FAX_COUNTRY_CODE" VARCHAR2(10), 
	"FAX_AREA_CODE" VARCHAR2(10), 
	"FAX" VARCHAR2(40), 
	"RFQ_OR_BIDDING_PURPOSE_FLAG" VARCHAR2(1), 
	"ORDERING_PURPOSE_FLAG" VARCHAR2(1), 
	"REMIT_TO_PURPOSE_FLAG" VARCHAR2(1), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"ATTRIBUTE21" VARCHAR2(150), 
	"ATTRIBUTE22" VARCHAR2(150), 
	"ATTRIBUTE23" VARCHAR2(150), 
	"ATTRIBUTE24" VARCHAR2(150), 
	"ATTRIBUTE25" VARCHAR2(150), 
	"ATTRIBUTE26" VARCHAR2(150), 
	"ATTRIBUTE27" VARCHAR2(150), 
	"ATTRIBUTE28" VARCHAR2(150), 
	"ATTRIBUTE29" VARCHAR2(150), 
	"ATTRIBUTE30" VARCHAR2(150), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_NUMBER11" NUMBER, 
	"ATTRIBUTE_NUMBER12" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_DATE6" DATE, 
	"ATTRIBUTE_DATE7" DATE, 
	"ATTRIBUTE_DATE8" DATE, 
	"ATTRIBUTE_DATE9" DATE, 
	"ATTRIBUTE_DATE10" DATE, 
	"ATTRIBUTE_DATE11" DATE, 
	"ATTRIBUTE_DATE12" DATE, 
	"EMAIL_ADDRESS" VARCHAR2(240), 
	"DELIVERY_CHANNEL_CODE" VARCHAR2(30), 
	"BANK_INSTRUCTION1_CODE" VARCHAR2(30), 
	"BANK_INSTRUCTION2_CODE" VARCHAR2(30), 
	"BANK_INSTRUCTION_DETAILS" VARCHAR2(255), 
	"SETTLEMENT_PRIORITY" NUMBER, 
	"PAYMENT_TEXT_MESSAGE1" VARCHAR2(150), 
	"PAYMENT_TEXT_MESSAGE2" VARCHAR2(150), 
	"PAYMENT_TEXT_MESSAGE3" VARCHAR2(150), 
	"SERVICE_LEVEL_CODE" VARCHAR2(30), 
	"EXCLUSIVE_PAYMENT_FLAG" VARCHAR2(1), 
	"IBY_BANK_CHARGE_BEARER" VARCHAR2(30), 
	"PAYMENT_REASON_CODE" VARCHAR2(30), 
	"PAYMENT_REASON_COMMENTS" VARCHAR2(240), 
	"REMIT_ADVICE_DELIVERY_METHOD" VARCHAR2(30), 
	"REMIT_ADVICE_EMAIL" VARCHAR2(240), 
	"REMIT_ADVICE_FAX" VARCHAR2(100), 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STG_STATUS" VARCHAR2(30) DEFAULT ''NEW'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_POZ_SUP_ADDR_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- 2026-07-08 conformance tranche: rename must precede the index DDL below
-- (a pre-existing database still has the old column when the index runs).
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_POZ_SUP_ADDR_STG_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_POZ_SUP_ADDR_STG_TBL" RENAME COLUMN "STATUS" TO "STG_STATUS"';
  end if;
end;
/


COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - identity column (GENERATED ALWAYS). Populated by the DB, never supplied by user.';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_STG_TBL"."IMPORT_ACTION" IS 'CREATE or UPDATE';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_STG_TBL"."PARTY_SITE_NAME" IS 'Address name â€” unique per supplier. Maps to POZ_SUP_ADDRESSES_INT.PARTY_SITE_NAME';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_STG_TBL"."SOURCE_ID" IS 'Natural key from source system';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten.';
COMMENT ON TABLE "DMT_POZ_SUP_ADDR_STG_TBL"  IS 'Supplier address staging. Raw user-loaded data only. Run-specific data in DMT_POZ_SUP_ADDR_TFM_TBL. Interface table: POZ_SUP_ADDRESSES_INT. CTL: PozSupAddressesInt.ctl (25B).';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------

COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_STG_TBL"."STG_STATUS" IS 'Staging lifecycle: NEW > TRANSFORMED / FAILED. Forward-only, never reset; errors accumulate in ERROR_TEXT.';

-- ---------------------------------------------------------------------------
-- 2026-07-09 conformance review F2 (STG/TFM infra-column dictionary, design
-- section 7 accepted 2026-07-08): STG_STATUS is VARCHAR2(30) DEFAULT 'NEW'
-- NOT NULL. Backfills any NULL statuses to the default, then converges a
-- pre-existing database; fresh installs get the shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_nullable varchar2(1);
begin
  select nullable into l_nullable from user_tab_columns
   where table_name = 'DMT_POZ_SUP_ADDR_STG_TBL' and column_name = 'STG_STATUS';
  if l_nullable = 'Y' then
    execute immediate 'UPDATE "DMT_POZ_SUP_ADDR_STG_TBL" SET "STG_STATUS" = ''NEW'' WHERE "STG_STATUS" IS NULL';
    execute immediate 'ALTER TABLE "DMT_POZ_SUP_ADDR_STG_TBL" MODIFY ("STG_STATUS" DEFAULT ''NEW'' NOT NULL)';
  end if;
end;
/

-- ---------------------------------------------------------------------------
-- 2026-07-09 conformance review F11: the supplier tables carried two index
-- numbering schemes (DMT_POZ_SUP_ADDR_STG_TBL_N* and DMT_POZ_SUP_ADDR_STG_N* both in
-- flight, colliding at N1). Renumbered to the single clean per-table sequence
-- used by every other object table; old non-conforming names are dropped by
-- the guarded block below, then the clean set is (re)created.
-- ---------------------------------------------------------------------------
declare
  l_n    pls_integer;
  l_cols varchar2(400);
begin
  select count(*) into l_n from user_indexes where index_name = 'DMT_POZ_SUP_ADDR_STG_TBL_N1';
  if l_n > 0 then execute immediate 'DROP INDEX "DMT_POZ_SUP_ADDR_STG_TBL_N1"'; end if;
  select listagg(column_name,',') within group (order by column_position) into l_cols
    from user_ind_columns where index_name = 'DMT_POZ_SUP_ADDR_STG_N1';
  if l_cols = 'SCENARIO_ID' then execute immediate 'DROP INDEX "DMT_POZ_SUP_ADDR_STG_N1"'; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_ADDR_STG_N1" ON "DMT_POZ_SUP_ADDR_STG_TBL" ("STG_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_ADDR_STG_N2" ON "DMT_POZ_SUP_ADDR_STG_TBL" ("SCENARIO_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
