-- DMT_CSV_LANDING_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_CSV_LANDING_TBL" 
   (	"CSV_LANDING_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"BATCH_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"VIEW_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"ATP_TABLE_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(200), 
	"CSV_DATA" CLOB, 
	"ROW_COUNT" NUMBER, 
	"SCENARIO_NAME" VARCHAR2(100), 
	"STATUS" VARCHAR2(30) DEFAULT ''PENDING'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"ROWS_LOADED" NUMBER, 
	"ROWS_SKIPPED" NUMBER, 
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"PROCESSED_DATE" DATE, 
	 CONSTRAINT "DMT_CSV_LANDING_PK" PRIMARY KEY ("CSV_LANDING_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_CSV_LANDING_BATCH_N1" ON "DMT_CSV_LANDING_TBL" ("BATCH_ID", "STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON TABLE "DMT_CSV_LANDING_TBL"  IS 'Landing table for CSV CLOBs. Parsed into STG tables by DMT_CSV_LOADER_PKG.';
