-- DMT_BEN_BENFY_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_BEN_BENFY_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_BEN_BENFY_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"PERSON_NUMBER" VARCHAR2(240), 
	"BENEFICIARY_PERSON_NUMBER" VARCHAR2(240), 
	"BENEFIT_RELATIONSHIP_NAME" VARCHAR2(240), 
	"PROGRAM_NAME" VARCHAR2(240), 
	"PLAN_NAME" VARCHAR2(240), 
	"DESIGNATION_DATE" VARCHAR2(240), 
	"DESIGNATION_END_DATE" VARCHAR2(240), 
	"PERCENTAGE" VARCHAR2(240), 
	"BENEFICIARY_TYPE" VARCHAR2(240), 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(240), 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_BEN_BENFY_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_BEN_BENFY_STG_TBL"."STATUS" IS 'NEW > RETRY > TRANSFORMED > LOADED / FAILED';
COMMENT ON TABLE "DMT_BEN_BENFY_STG_TBL"  IS 'BeneficiaryDesignation staging. HDL business object: BeneficiaryDesignation.';
