-- DMT_PJF_PROJECTS_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PJF_PROJECTS_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PJF_PROJECTS_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"PROJECT_NAME" VARCHAR2(240), 
	"PROJECT_NUMBER" VARCHAR2(25), 
	"SOURCE_TEMPLATE_NUMBER" VARCHAR2(25), 
	"SOURCE_APPLICATION_CODE" VARCHAR2(30), 
	"SOURCE_PROJECT_REFERENCE" VARCHAR2(25), 
	"ORGANIZATION_NAME" VARCHAR2(240), 
	"LEGAL_ENTITY_NAME" VARCHAR2(240), 
	"DESCRIPTION" VARCHAR2(2000), 
	"PROJECT_MANAGER_NUMBER" VARCHAR2(30), 
	"PROJECT_MANAGER_NAME" VARCHAR2(360), 
	"PROJECT_MANAGER_EMAIL" VARCHAR2(360), 
	"PROJECT_START_DATE" DATE, 
	"PROJECT_FINISH_DATE" DATE, 
	"CLOSED_DATE" DATE, 
	"PROJECT_STATUS_NAME" VARCHAR2(80), 
	"PROJECT_PRIORITY_CODE" VARCHAR2(30), 
	"OUTLINE_DISPLAY_LEVEL" VARCHAR2(30), 
	"PLANNING_PROJECT_FLAG" VARCHAR2(1), 
	"SERVICE_TYPE_CODE" VARCHAR2(30), 
	"WORK_TYPE_NAME" VARCHAR2(240), 
	"LIMIT_TO_TXN_CONTROLS_CODE" VARCHAR2(1), 
	"PROJECT_CURRENCY_CODE" VARCHAR2(15), 
	"CURRENCY_CONV_RATE_TYPE" VARCHAR2(30), 
	"CURRENCY_CONV_DATE_TYPE_CODE" VARCHAR2(30), 
	"CURRENCY_CONV_DATE" DATE, 
	"CINT_ELIGIBLE_FLAG" VARCHAR2(1), 
	"CINT_RATE_SCH_NAME" VARCHAR2(240), 
	"CINT_STOP_DATE" DATE, 
	"ASSET_ALLOCATION_METHOD_CODE" VARCHAR2(30), 
	"CAPITAL_EVENT_PROCESSING_CODE" VARCHAR2(30), 
	"ALLOW_CROSS_CHARGE_FLAG" VARCHAR2(1), 
	"CC_PROCESS_LABOR_FLAG" VARCHAR2(1), 
	"LABOR_TP_SCHEDULE_NAME" VARCHAR2(240), 
	"LABOR_TP_FIXED_DATE" DATE, 
	"CC_PROCESS_NL_FLAG" VARCHAR2(1), 
	"NL_TP_SCHEDULE_NAME" VARCHAR2(240), 
	"NL_TP_FIXED_DATE" DATE, 
	"BURDEN_SCHEDULE_NAME" VARCHAR2(240), 
	"BURDEN_SCH_FIXED_DATED" DATE, 
	"KPI_NOTIFICATION_ENABLED" VARCHAR2(1), 
	"KPI_NOTIFICATION_RECIPIENTS" VARCHAR2(240), 
	"KPI_NOTIFICATION_INCLUDE_NOTES" VARCHAR2(1), 
	"COPY_TEAM_MEMBERS_FLAG" VARCHAR2(1), 
	"COPY_PROJECT_CLASSES_FLAG" VARCHAR2(1), 
	"COPY_ATTACHMENTS_FLAG" VARCHAR2(1), 
	"COPY_DFF_FLAG" VARCHAR2(1), 
	"COPY_GROUP_SPACE_FLAG" VARCHAR2(1), 
	"COPY_TASKS_FLAG" VARCHAR2(1), 
	"COPY_TASK_ATTACHMENTS_FLAG" VARCHAR2(1), 
	"COPY_TASK_DFF_FLAG" VARCHAR2(1), 
	"COPY_TASK_ASSIGNMENTS_FLAG" VARCHAR2(1), 
	"COPY_TRANSACTION_CONTROLS_FLAG" VARCHAR2(1), 
	"COPY_ASSETS_FLAG" VARCHAR2(1), 
	"COPY_ASSET_ASSIGNMENTS_FLAG" VARCHAR2(1), 
	"COPY_COST_OVERRIDES_FLAG" VARCHAR2(1), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"ATTRIBUTE21" VARCHAR2(150), 
	"ATTRIBUTE22" VARCHAR2(150), 
	"ATTRIBUTE23" VARCHAR2(150), 
	"ATTRIBUTE24" VARCHAR2(150), 
	"ATTRIBUTE25" VARCHAR2(150), 
	"ATTRIBUTE26" VARCHAR2(150), 
	"ATTRIBUTE27" VARCHAR2(150), 
	"ATTRIBUTE28" VARCHAR2(150), 
	"ATTRIBUTE29" VARCHAR2(150), 
	"ATTRIBUTE30" VARCHAR2(150), 
	"ATTRIBUTE31" VARCHAR2(150), 
	"ATTRIBUTE32" VARCHAR2(150), 
	"ATTRIBUTE33" VARCHAR2(150), 
	"ATTRIBUTE34" VARCHAR2(150), 
	"ATTRIBUTE35" VARCHAR2(150), 
	"ATTRIBUTE36" VARCHAR2(150), 
	"ATTRIBUTE37" VARCHAR2(150), 
	"ATTRIBUTE38" VARCHAR2(150), 
	"ATTRIBUTE39" VARCHAR2(150), 
	"ATTRIBUTE40" VARCHAR2(150), 
	"ATTRIBUTE41" VARCHAR2(150), 
	"ATTRIBUTE42" VARCHAR2(150), 
	"ATTRIBUTE43" VARCHAR2(150), 
	"ATTRIBUTE44" VARCHAR2(150), 
	"ATTRIBUTE45" VARCHAR2(150), 
	"ATTRIBUTE46" VARCHAR2(150), 
	"ATTRIBUTE47" VARCHAR2(150), 
	"ATTRIBUTE48" VARCHAR2(150), 
	"ATTRIBUTE49" VARCHAR2(150), 
	"ATTRIBUTE50" VARCHAR2(150), 
	"ATTRIBUTE1_NUMBER" NUMBER, 
	"ATTRIBUTE2_NUMBER" NUMBER, 
	"ATTRIBUTE3_NUMBER" NUMBER, 
	"ATTRIBUTE4_NUMBER" NUMBER, 
	"ATTRIBUTE5_NUMBER" NUMBER, 
	"ATTRIBUTE6_NUMBER" NUMBER, 
	"ATTRIBUTE7_NUMBER" NUMBER, 
	"ATTRIBUTE8_NUMBER" NUMBER, 
	"ATTRIBUTE9_NUMBER" NUMBER, 
	"ATTRIBUTE10_NUMBER" NUMBER, 
	"ATTRIBUTE11_NUMBER" NUMBER, 
	"ATTRIBUTE12_NUMBER" NUMBER, 
	"ATTRIBUTE13_NUMBER" NUMBER, 
	"ATTRIBUTE14_NUMBER" NUMBER, 
	"ATTRIBUTE15_NUMBER" NUMBER, 
	"ATTRIBUTE1_DATE" DATE, 
	"ATTRIBUTE2_DATE" DATE, 
	"ATTRIBUTE3_DATE" DATE, 
	"ATTRIBUTE4_DATE" DATE, 
	"ATTRIBUTE5_DATE" DATE, 
	"ATTRIBUTE6_DATE" DATE, 
	"ATTRIBUTE7_DATE" DATE, 
	"ATTRIBUTE8_DATE" DATE, 
	"ATTRIBUTE9_DATE" DATE, 
	"ATTRIBUTE10_DATE" DATE, 
	"ATTRIBUTE11_DATE" DATE, 
	"ATTRIBUTE12_DATE" DATE, 
	"ATTRIBUTE13_DATE" DATE, 
	"ATTRIBUTE14_DATE" DATE, 
	"ATTRIBUTE15_DATE" DATE, 
	"SCHEDULE_NAME" VARCHAR2(240), 
	"EPS_NAME" VARCHAR2(240), 
	"PROJECT_PLAN_VIEW_ACCESS" VARCHAR2(30), 
	"SCHEDULE_TYPE" VARCHAR2(30), 
	"OPPORTUNITY_ID" VARCHAR2(240), 
	"OPPORTUNITY_NUMBER" VARCHAR2(240), 
	"OPPORTUNITY_CUSTOMER_NUMBER" VARCHAR2(240), 
	"OPPORTUNITY_CUSTOMER_ID" VARCHAR2(240), 
	"OPPORTUNITY_AMT" VARCHAR2(240), 
	"OPPORTUNITY_CURRCODE" VARCHAR2(15), 
	"OPPORTUNITY_WIN_CONF_PERCENT" VARCHAR2(240), 
	"OPPORTUNITY_NAME" VARCHAR2(240), 
	"OPPORTUNITY_DESC" VARCHAR2(1000), 
	"OPPORTUNITY_CUSTOMER_NAME" VARCHAR2(900), 
	"OPPORTUNITY_STATUS" VARCHAR2(240), 
	"PRJ_PLAN_BASELINE_NAME" VARCHAR2(240), 
	"PRJ_PLAN_BASELINE_DESC" VARCHAR2(1000), 
	"PRJ_PLAN_BASELINE_DATE" DATE, 
	"BUDGETARY_CONTROL_FLAG" VARCHAR2(1), 
	"SOURCE_TEMPLATE_NAME" VARCHAR2(240), 
	"CASCADE_OPTION" VARCHAR2(30), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STG_STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_PJF_PROJECTS_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PJF_PROJECTS_STG_TBL_N1" ON "DMT_PJF_PROJECTS_STG_TBL" ("STG_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PJF_PROJECTS_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_PJF_PROJECTS_STG_SEQ';
COMMENT ON COLUMN "DMT_PJF_PROJECTS_STG_TBL"."PROJECT_NAME" IS 'Name of the project â€” must be unique within the organization';
COMMENT ON COLUMN "DMT_PJF_PROJECTS_STG_TBL"."PROJECT_NUMBER" IS 'Project number from source system â€” prefix applied in TFM table';
COMMENT ON COLUMN "DMT_PJF_PROJECTS_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors â€” appended at each step, never overwritten. Prefixed: [PRE_VALIDATION] [TRANSFORM_ERROR] [FUSION_ERROR].';
COMMENT ON TABLE "DMT_PJF_PROJECTS_STG_TBL"  IS 'Project header staging. Raw user data only. Run-specific data in DMT_PJF_PROJECTS_TFM_TBL. FBDI interface: PJF_PROJECTS_ALL_XFACE. CSV: PjfProjectsAllXface.csv.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_PJF_PROJECTS_STG_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_PJF_PROJECTS_STG_TBL" RENAME COLUMN "STATUS" TO "STG_STATUS"';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_PJF_PROJECTS_STG_N1" ON "DMT_PJF_PROJECTS_STG_TBL" ("SCENARIO_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PJF_PROJECTS_STG_TBL"."STG_STATUS" IS 'Staging lifecycle: NEW > TRANSFORMED / FAILED. Forward-only, never reset; errors accumulate in ERROR_TEXT.';
