-- DMT_FND_LOOKUP_VALUE_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_FND_LOOKUP_VALUE_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_FND_LOOKUP_VALUE_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"SOURCE_GROUP_ID" NUMBER, 
	"LOOKUP_TYPE" VARCHAR2(30), 
	"LOOKUP_CODE" VARCHAR2(30), 
	"DISPLAY_SEQUENCE" NUMBER, 
	"ENABLED_FLAG" VARCHAR2(1), 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"MEANING" VARCHAR2(80), 
	"DESCRIPTION" VARCHAR2(240), 
	"TAG" VARCHAR2(150), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_FND_LKP_VAL_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON TABLE "DMT_FND_LOOKUP_VALUE_STG_TBL"  IS 'Lookup Values staging. Raw user-loaded data, child of FND_LOOKUP_TYPE. Run-specific data in DMT_FND_LOOKUP_VALUE_TFM_TBL.';
