-- DMT_PERSON_LEGISL_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PERSON_LEGISL_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PERSON_LEGISL_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" VARCHAR2(240), 
	"EFFECTIVE_END_DATE" VARCHAR2(240), 
	"PERSON_NUMBER" VARCHAR2(240), 
	"LEGISLATION_CODE" VARCHAR2(240), 
	"SEX" VARCHAR2(240), 
	"MARITAL_STATUS" VARCHAR2(240), 
	"HIGHEST_EDUCATION_LEVEL" VARCHAR2(240), 
	"ETHNICITY" VARCHAR2(240), 
	"VETERAN_SELF_IDENT_FLAG" VARCHAR2(240), 
	"TOBACCO_USER" VARCHAR2(240), 
	"DISABLED_FLAG" VARCHAR2(240), 
	"PER_INFORMATION1" VARCHAR2(240), 
	"PER_INFORMATION2" VARCHAR2(240), 
	"PER_INFORMATION3" VARCHAR2(240), 
	"PER_INFORMATION4" VARCHAR2(240), 
	"PER_INFORMATION5" VARCHAR2(240), 
	"PER_INFORMATION6" VARCHAR2(240), 
	"PER_INFORMATION7" VARCHAR2(240), 
	"PER_INFORMATION8" VARCHAR2(240), 
	"PER_INFORMATION9" VARCHAR2(240), 
	"PER_INFORMATION10" VARCHAR2(240), 
	"PER_INFORMATION11" VARCHAR2(240), 
	"PER_INFORMATION12" VARCHAR2(240), 
	"PER_INFORMATION13" VARCHAR2(240), 
	"PER_INFORMATION14" VARCHAR2(240), 
	"PER_INFORMATION15" VARCHAR2(240), 
	"PER_INFORMATION16" VARCHAR2(240), 
	"PER_INFORMATION17" VARCHAR2(240), 
	"PER_INFORMATION18" VARCHAR2(240), 
	"PER_INFORMATION19" VARCHAR2(240), 
	"PER_INFORMATION20" VARCHAR2(240), 
	"PER_INFORMATION21" VARCHAR2(240), 
	"PER_INFORMATION22" VARCHAR2(240), 
	"PER_INFORMATION23" VARCHAR2(240), 
	"PER_INFORMATION24" VARCHAR2(240), 
	"PER_INFORMATION25" VARCHAR2(240), 
	"PER_INFORMATION26" VARCHAR2(240), 
	"PER_INFORMATION27" VARCHAR2(240), 
	"PER_INFORMATION28" VARCHAR2(240), 
	"PER_INFORMATION29" VARCHAR2(240), 
	"PER_INFORMATION30" VARCHAR2(240), 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_PERSON_LEGISL_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PERSON_LEGISL_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_PERSON_LEGISL_STG_SEQ. Populated by DB default, never supplied by user.';
COMMENT ON COLUMN "DMT_PERSON_LEGISL_STG_TBL"."PERSON_NUMBER" IS 'Worker person number â€” FK to Worker business object';
COMMENT ON COLUMN "DMT_PERSON_LEGISL_STG_TBL"."ETHNICITY" IS 'Ethnicity â€” US-specific legislative data';
COMMENT ON COLUMN "DMT_PERSON_LEGISL_STG_TBL"."VETERAN_SELF_IDENT_FLAG" IS 'Veteran self-identification flag';
COMMENT ON COLUMN "DMT_PERSON_LEGISL_STG_TBL"."SOURCE_ID" IS 'Natural key from source system';
COMMENT ON COLUMN "DMT_PERSON_LEGISL_STG_TBL"."STATUS" IS 'NEW > RETRY > TRANSFORMED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_PERSON_LEGISL_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten.';
COMMENT ON TABLE "DMT_PERSON_LEGISL_STG_TBL"  IS 'Person legislative data staging. Raw user-loaded data only. Run-specific data in DMT_PERSON_LEGISL_TFM_TBL. HDL business object: PersonLegislativeData.';
