-- DMT_AP_PAY_TERM_LINE_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_AP_PAY_TERM_LINE_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_AP_PAY_TERM_LINE_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"SOURCE_GROUP_ID" NUMBER, 
	"SEQUENCE_NUM" NUMBER, 
	"DUE_PERCENT" NUMBER, 
	"DUE_AMOUNT" NUMBER, 
	"DUE_DAYS" NUMBER, 
	"DUE_DATE" DATE, 
	"DISCOUNT_PERCENT" NUMBER, 
	"DISCOUNT_DAYS" NUMBER, 
	"DISCOUNT_PERCENT_2" NUMBER, 
	"DISCOUNT_DAYS_2" NUMBER, 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_AP_PAY_TERM_LINE_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
