-- DMT_CE_BANK_ACCT_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_CE_BANK_ACCT_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_CE_BANK_ACCT_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"SOURCE_GROUP_ID" NUMBER, 
	"SOURCE_LINE_ID" NUMBER, 
	"BANK_NAME" VARCHAR2(360), 
	"BRANCH_NAME" VARCHAR2(360), 
	"ACCOUNT_NAME" VARCHAR2(80), 
	"ACCOUNT_NUMBER" VARCHAR2(30), 
	"CURRENCY_CODE" VARCHAR2(15), 
	"ACCOUNT_TYPE" VARCHAR2(25), 
	"LEGAL_ENTITY_NAME" VARCHAR2(240), 
	"DESCRIPTION" VARCHAR2(240), 
	"IBAN" VARCHAR2(50), 
	"CHECK_DIGITS" VARCHAR2(30), 
	"MULTI_CURRENCY_ALLOWED_FLAG" VARCHAR2(1), 
	"ACCOUNT_SUFFIX" VARCHAR2(30), 
	"SECONDARY_ACCOUNT_REFERENCE" VARCHAR2(30), 
	"END_DATE" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_CE_BANK_ACCT_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
