-- DMT_POZ_SUP_SITE_ASSN_STG_TBL (generated from ATP 2026-07-03)

-- Identity-PK conversion (accepted coding standard 2026-07-08: "Identity
-- columns for keys; sequences only for shared, meaningful values").
-- In-place conversion of an existing non-identity column is NOT possible on
-- Oracle 26ai: every ALTER TABLE ... MODIFY variant (GENERATED ALWAYS,
-- GENERATED BY DEFAULT ON NULL) raises ORA-30673, even on an empty table
-- (probed on dmt2-local 2026-07-08). So a pre-identity table is converted by
-- drop-and-recreate -- EMPTY tables only. A populated table is never dropped
-- (staging rows are never deleted): the block raises with the manual
-- data-preserving rebuild recipe instead.
-- Deploy this file via db/install.sql: any FK dropped by the CASCADE here is
-- re-added by tables/_foreign_keys.sql later in the same install run.
declare
  l_exists   pls_integer;
  l_identity pls_integer;
  l_rows     pls_integer;
begin
  select count(*) into l_exists from user_tables
  where  table_name = 'DMT_POZ_SUP_SITE_ASSN_STG_TBL';
  if l_exists = 1 then
    select count(*) into l_identity from user_tab_identity_cols
    where  table_name = 'DMT_POZ_SUP_SITE_ASSN_STG_TBL' and column_name = 'STG_SEQUENCE_ID';
    if l_identity = 0 then
      execute immediate 'select count(*) from "DMT_POZ_SUP_SITE_ASSN_STG_TBL" where rownum = 1' into l_rows;
      if l_rows = 0 then
        execute immediate 'drop table "DMT_POZ_SUP_SITE_ASSN_STG_TBL" cascade constraints purge';
      else
        raise_application_error(-20001,
          'DMT_POZ_SUP_SITE_ASSN_STG_TBL: cannot convert a populated table to an identity PK in place (ORA-30673). ' ||
          'Manual rebuild required: create a swap table with STG_SEQUENCE_ID GENERATED BY DEFAULT ON NULL AS IDENTITY, ' ||
          'insert the rows preserving ids, rename, re-add constraints, then ALTER ... MODIFY to GENERATED ALWAYS (START WITH LIMIT VALUE).');
      end if;
    end if;
  end if;
end;
/

begin
  execute immediate 'CREATE TABLE "DMT_POZ_SUP_SITE_ASSN_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE, 
	"IMPORT_ACTION" VARCHAR2(10), 
	"VENDOR_NAME" VARCHAR2(360), 
	"VENDOR_SITE_CODE" VARCHAR2(15), 
	"PROCUREMENT_BUSINESS_UNIT_NAME" VARCHAR2(240), 
	"BUSINESS_UNIT_NAME" VARCHAR2(240), 
	"BILL_TO_BU_NAME" VARCHAR2(240), 
	"SHIP_TO_LOCATION_CODE" VARCHAR2(60), 
	"BILL_TO_LOCATION_CODE" VARCHAR2(60), 
	"ALLOW_AWT_FLAG" VARCHAR2(1), 
	"AWT_GROUP_NAME" VARCHAR2(25), 
	"ACCTS_PAY_CONCAT_SEGMENTS" VARCHAR2(250), 
	"PREPAY_CONCAT_SEGMENTS" VARCHAR2(250), 
	"FUTURE_DATED_CONCAT_SEGMENTS" VARCHAR2(250), 
	"DISTRIBUTION_SET_NAME" VARCHAR2(50), 
	"INACTIVE_DATE" DATE, 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STG_STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_POZ_SUP_SITE_ASSN_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- 2026-07-08 conformance tranche: rename must precede the index DDL below
-- (a pre-existing database still has the old column when the index runs).
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_POZ_SUP_SITE_ASSN_STG_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_POZ_SUP_SITE_ASSN_STG_TBL" RENAME COLUMN "STATUS" TO "STG_STATUS"';
  end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_SITE_ASSN_STG_TBL_N1" ON "DMT_POZ_SUP_SITE_ASSN_STG_TBL" ("STG_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - identity column (GENERATED ALWAYS). Populated by the DB, never supplied by user.';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."IMPORT_ACTION" IS 'CREATE or UPDATE';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."PROCUREMENT_BUSINESS_UNIT_NAME" IS 'Procurement BU that owns the site';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."BUSINESS_UNIT_NAME" IS 'Payables BU being assigned to this site';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."ACCTS_PAY_CONCAT_SEGMENTS" IS 'AP liabilities account in concatenated flexfield segment format';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."PREPAY_CONCAT_SEGMENTS" IS 'Prepayment account in concatenated flexfield segment format';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."FUTURE_DATED_CONCAT_SEGMENTS" IS 'Future-dated payment account in concatenated flexfield segment format';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."SOURCE_ID" IS 'Natural key from source system';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten.';
COMMENT ON TABLE "DMT_POZ_SUP_SITE_ASSN_STG_TBL"  IS 'Supplier site assignment staging. Raw user-loaded data only. Run-specific data in DMT_POZ_SUP_SITE_ASSN_TFM_TBL. Interface table: POZ_SITE_ASSIGNMENTS_INT. CTL: PozSiteAssignmentsInt.ctl (25B).';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_SITE_ASSN_STG_N1" ON "DMT_POZ_SUP_SITE_ASSN_STG_TBL" ("SCENARIO_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."STG_STATUS" IS 'Staging lifecycle: NEW > TRANSFORMED / FAILED. Forward-only, never reset; errors accumulate in ERROR_TEXT.';
