-- DMT_PJC_EXPENDITURES_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PJC_EXPENDITURES_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PJC_EXPENDITURES_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"TRANSACTION_TYPE" VARCHAR2(240), 
	"BUSINESS_UNIT" VARCHAR2(240), 
	"ORG_ID" NUMBER, 
	"USER_TRANSACTION_SOURCE" VARCHAR2(240), 
	"TRANSACTION_SOURCE_ID" NUMBER, 
	"DOCUMENT_NAME" VARCHAR2(240), 
	"DOCUMENT_ID" NUMBER, 
	"DOC_ENTRY_NAME" VARCHAR2(240), 
	"DOC_ENTRY_ID" NUMBER, 
	"BATCH_NAME" VARCHAR2(240), 
	"BATCH_ENDING_DATE" DATE, 
	"BATCH_DESCRIPTION" VARCHAR2(240), 
	"EXPENDITURE_ITEM_DATE" DATE, 
	"PERSON_NUMBER" VARCHAR2(30), 
	"PERSON_NAME" VARCHAR2(2000), 
	"PERSON_ID" NUMBER, 
	"HCM_ASSIGNMENT_NAME" VARCHAR2(240), 
	"HCM_ASSIGNMENT_ID" NUMBER, 
	"PROJECT_NUMBER" VARCHAR2(25), 
	"PROJECT_NAME" VARCHAR2(240), 
	"PROJECT_ID" NUMBER, 
	"TASK_NUMBER" VARCHAR2(100), 
	"TASK_NAME" VARCHAR2(240), 
	"TASK_ID" NUMBER, 
	"EXPENDITURE_TYPE" VARCHAR2(240), 
	"EXPENDITURE_TYPE_ID" NUMBER, 
	"ORGANIZATION_NAME" VARCHAR2(240), 
	"ORGANIZATION_ID" NUMBER, 
	"NON_LABOR_RESOURCE" VARCHAR2(240), 
	"NON_LABOR_RESOURCE_ID" NUMBER, 
	"NON_LABOR_RESOURCE_ORG" VARCHAR2(240), 
	"NON_LABOR_RESOURCE_ORG_ID" NUMBER, 
	"QUANTITY" NUMBER, 
	"UNIT_OF_MEASURE_NAME" VARCHAR2(240), 
	"UNIT_OF_MEASURE" VARCHAR2(240), 
	"WORK_TYPE" VARCHAR2(240), 
	"WORK_TYPE_ID" NUMBER, 
	"BILLABLE_FLAG" VARCHAR2(1), 
	"CAPITALIZABLE_FLAG" VARCHAR2(1), 
	"ACCRUAL_FLAG" VARCHAR2(1), 
	"SUPPLIER_NUMBER" VARCHAR2(30), 
	"SUPPLIER_NAME" VARCHAR2(360), 
	"VENDOR_ID" NUMBER, 
	"INVENTORY_ITEM_NAME" VARCHAR2(300), 
	"INVENTORY_ITEM_ID" NUMBER, 
	"ORIG_TRANSACTION_REFERENCE" VARCHAR2(240), 
	"UNMATCHED_NEGATIVE_TXN_FLAG" VARCHAR2(1), 
	"REVERSED_ORIG_TXN_REFERENCE" VARCHAR2(240), 
	"EXPENDITURE_COMMENT" VARCHAR2(240), 
	"GL_DATE" DATE, 
	"DENOM_CURRENCY_CODE" VARCHAR2(15), 
	"DENOM_CURRENCY" VARCHAR2(15), 
	"DENOM_RAW_COST" NUMBER, 
	"DENOM_BURDENED_COST" NUMBER, 
	"RAW_COST_CR_CCID" NUMBER, 
	"RAW_COST_CR_ACCOUNT" VARCHAR2(2000), 
	"RAW_COST_DR_CCID" NUMBER, 
	"RAW_COST_DR_ACCOUNT" VARCHAR2(2000), 
	"BURDENED_COST_CR_CCID" NUMBER, 
	"BURDENED_COST_CR_ACCOUNT" VARCHAR2(2000), 
	"BURDENED_COST_DR_CCID" NUMBER, 
	"BURDENED_COST_DR_ACCOUNT" VARCHAR2(2000), 
	"BURDEN_COST_CR_CCID" NUMBER, 
	"BURDEN_COST_CR_ACCOUNT" VARCHAR2(2000), 
	"BURDEN_COST_DR_CCID" NUMBER, 
	"BURDEN_COST_DR_ACCOUNT" VARCHAR2(2000), 
	"ACCT_CURRENCY_CODE" VARCHAR2(15), 
	"ACCT_CURRENCY" VARCHAR2(15), 
	"ACCT_RAW_COST" NUMBER, 
	"ACCT_BURDENED_COST" NUMBER, 
	"ACCT_RATE_TYPE" VARCHAR2(30), 
	"ACCT_RATE_DATE" DATE, 
	"ACCT_RATE_DATE_TYPE" VARCHAR2(30), 
	"ACCT_EXCHANGE_RATE" NUMBER, 
	"ACCT_EXCHANGE_ROUNDING_LIMIT" NUMBER, 
	"RECEIPT_CURRENCY_CODE" VARCHAR2(15), 
	"RECEIPT_CURRENCY" VARCHAR2(15), 
	"RECEIPT_CURRENCY_AMOUNT" NUMBER, 
	"RECEIPT_EXCHANGE_RATE" NUMBER, 
	"CONVERTED_FLAG" VARCHAR2(1), 
	"CONTEXT_CATEGORY" VARCHAR2(30), 
	"USER_DEF_ATTRIBUTE1" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE2" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE3" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE4" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE5" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE6" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE7" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE8" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE9" VARCHAR2(240), 
	"USER_DEF_ATTRIBUTE10" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE1" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE2" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE3" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE4" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE5" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE6" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE7" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE8" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE9" VARCHAR2(240), 
	"RESERVED_ATTRIBUTE10" VARCHAR2(240), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"CONTRACT_NUMBER" VARCHAR2(240), 
	"CONTRACT_NAME" VARCHAR2(300), 
	"CONTRACT_ID" NUMBER, 
	"FUNDING_SOURCE_NUMBER" VARCHAR2(240), 
	"FUNDING_SOURCE_NAME" VARCHAR2(240), 
	"PROJECT_ROLE_NAME" VARCHAR2(240), 
	"PROJECT_ROLE_ID" NUMBER, 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STG_STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_PJC_EXPENDITURES_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PJC_EXPENDITURES_STG_TBL_N1" ON "DMT_PJC_EXPENDITURES_STG_TBL" ("STG_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PJC_EXPENDITURES_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_PJC_EXPENDITURES_STG_SEQ';
COMMENT ON COLUMN "DMT_PJC_EXPENDITURES_STG_TBL"."PROJECT_NUMBER" IS 'Project number from source system â€” prefix applied in TFM table';
COMMENT ON COLUMN "DMT_PJC_EXPENDITURES_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors â€” appended at each step, never overwritten. Prefixed: [PRE_VALIDATION] [TRANSFORM_ERROR] [FUSION_ERROR].';
COMMENT ON TABLE "DMT_PJC_EXPENDITURES_STG_TBL"  IS 'Expenditures staging. Raw user data only. Run-specific data in DMT_PJC_EXPENDITURES_TFM_TBL. FBDI interface: PJC_TXN_XFACE_STAGE_ALL. CSV: PjcTxnXfaceStageAll.csv.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_PJC_EXPENDITURES_STG_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_PJC_EXPENDITURES_STG_TBL" RENAME COLUMN "STATUS" TO "STG_STATUS"';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_PJC_EXPENDITURES_STG_N1" ON "DMT_PJC_EXPENDITURES_STG_TBL" ("SCENARIO_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PJC_EXPENDITURES_STG_TBL"."STG_STATUS" IS 'Staging lifecycle: NEW > TRANSFORMED / FAILED. Forward-only, never reset; errors accumulate in ERROR_TEXT.';
