-- DMT_POZ_SUP_SITE_ASSN_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_POZ_SUP_SITE_ASSN_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_POZ_SUP_SITE_ASSN_ID_SEQ.NEXTVAL NOT NULL ENABLE, 
	"IMPORT_ACTION" VARCHAR2(10), 
	"VENDOR_NAME" VARCHAR2(360), 
	"VENDOR_SITE_CODE" VARCHAR2(15), 
	"PROCUREMENT_BUSINESS_UNIT_NAME" VARCHAR2(240), 
	"BUSINESS_UNIT_NAME" VARCHAR2(240), 
	"BILL_TO_BU_NAME" VARCHAR2(240), 
	"SHIP_TO_LOCATION_CODE" VARCHAR2(60), 
	"BILL_TO_LOCATION_CODE" VARCHAR2(60), 
	"ALLOW_AWT_FLAG" VARCHAR2(1), 
	"AWT_GROUP_NAME" VARCHAR2(25), 
	"ACCTS_PAY_CONCAT_SEGMENTS" VARCHAR2(250), 
	"PREPAY_CONCAT_SEGMENTS" VARCHAR2(250), 
	"FUTURE_DATED_CONCAT_SEGMENTS" VARCHAR2(250), 
	"DISTRIBUTION_SET_NAME" VARCHAR2(50), 
	"INACTIVE_DATE" DATE, 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_POZ_SUP_SITE_ASSN_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_SITE_ASSN_STG_TBL_N1" ON "DMT_POZ_SUP_SITE_ASSN_STG_TBL" ("STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_POZ_SUP_SITE_ASSN_ID_SEQ. Populated by DB default, never supplied by user.';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."IMPORT_ACTION" IS 'CREATE or UPDATE';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."PROCUREMENT_BUSINESS_UNIT_NAME" IS 'Procurement BU that owns the site';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."BUSINESS_UNIT_NAME" IS 'Payables BU being assigned to this site';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."ACCTS_PAY_CONCAT_SEGMENTS" IS 'AP liabilities account in concatenated flexfield segment format';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."PREPAY_CONCAT_SEGMENTS" IS 'Prepayment account in concatenated flexfield segment format';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."FUTURE_DATED_CONCAT_SEGMENTS" IS 'Future-dated payment account in concatenated flexfield segment format';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."SOURCE_ID" IS 'Natural key from source system';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."STATUS" IS 'NEW > RETRY > TRANSFORMED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_POZ_SUP_SITE_ASSN_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten.';
COMMENT ON TABLE "DMT_POZ_SUP_SITE_ASSN_STG_TBL"  IS 'Supplier site assignment staging. Raw user-loaded data only. Run-specific data in DMT_POZ_SUP_SITE_ASSN_TFM_TBL. Interface table: POZ_SITE_ASSIGNMENTS_INT. CTL: PozSiteAssignmentsInt.ctl (25B).';
