-- DMT_ERP_INTERFACE_OPTIONS_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_ERP_INTERFACE_OPTIONS_TBL" 
   (	"ERP_INTERFACE_OPTIONS_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"ERP_FAMILY" VARCHAR2(50), 
	"BUSINESS_OBJECT" VARCHAR2(100), 
	"UCM_ACCOUNT" VARCHAR2(200), 
	"LOAD_JOB_NAME" VARCHAR2(500), 
	"IMPORT_JOB_NAME" VARCHAR2(500), 
	"POST_LOAD_JOB_NAME" VARCHAR2(500), 
	"LOAD_INTERFACE_FLAG" VARCHAR2(1), 
	"LOADER_TYPE" VARCHAR2(50), 
	"SERVICE_NAME" VARCHAR2(200), 
	"CEMLI_CODE" VARCHAR2(100), 
	"SOURCE_ERP_OPTIONS_ID" VARCHAR2(30), 
	"REPORT_JOB_DEF" VARCHAR2(200), 
	"FUSION_USERNAME" VARCHAR2(100), 
	"FUSION_PASSWORD" VARCHAR2(100), 
	 CONSTRAINT "DMT_ERP_INT_OPT_TBL_PK" PRIMARY KEY ("ERP_INTERFACE_OPTIONS_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DMT_ERP_INT_OPT_TBL_UQ" UNIQUE ("CEMLI_CODE")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_ERP_INTERFACE_OPTIONS_TBL"."ERP_INTERFACE_OPTIONS_ID" IS 'PK from Fusion FUN_ERP_INTERFACE_OPTIONS';
COMMENT ON COLUMN "DMT_ERP_INTERFACE_OPTIONS_TBL"."UCM_ACCOUNT" IS 'UCM document account for FBDI upload (DocumentAccount in loadAndImportData)';
COMMENT ON COLUMN "DMT_ERP_INTERFACE_OPTIONS_TBL"."IMPORT_JOB_NAME" IS 'Full ESS job path; semicolon separates package from definition name';
COMMENT ON COLUMN "DMT_ERP_INTERFACE_OPTIONS_TBL"."LOAD_INTERFACE_FLAG" IS 'Y = uses loadAndImportData pattern; N = BIP extract only';
COMMENT ON COLUMN "DMT_ERP_INTERFACE_OPTIONS_TBL"."CEMLI_CODE" IS 'DMT CEMLI code e.g. C001-Suppliers. NULL for rows not used by DMT pipeline.';
COMMENT ON TABLE "DMT_ERP_INTERFACE_OPTIONS_TBL"  IS 'Local mirror of Fusion FUN_ERP_INTERFACE_OPTIONS. CEMLI_CODE links rows used by the DMT pipeline.';
