-- DMT_ABSENCE_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_ABSENCE_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_ABSENCE_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" VARCHAR2(240), 
	"EFFECTIVE_END_DATE" VARCHAR2(240), 
	"PERSON_NUMBER" VARCHAR2(240), 
	"EMPLOYER_NAME" VARCHAR2(240), 
	"ABSENCE_NAME" VARCHAR2(240), 
	"ABSENCE_TYPE" VARCHAR2(240), 
	"ABSENCE_CATEGORY" VARCHAR2(240), 
	"ABSENCE_STATUS" VARCHAR2(240), 
	"START_DATE" VARCHAR2(240), 
	"END_DATE" VARCHAR2(240), 
	"START_TIME" VARCHAR2(240), 
	"END_TIME" VARCHAR2(240), 
	"APPROVAL_STATUS_CODE" VARCHAR2(240), 
	"DURATION" VARCHAR2(240), 
	"SUBMISSION_DATE" VARCHAR2(240), 
	"ABSENCE_REASON" VARCHAR2(240), 
	"COMMENTS" VARCHAR2(4000), 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_ABSENCE_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_ABSENCE_STG_TBL"."STATUS" IS 'NEW > RETRY > TRANSFORMED > LOADED / FAILED';
COMMENT ON TABLE "DMT_ABSENCE_STG_TBL"  IS 'AbsenceEntry staging. HDL business object: AbsenceEntry.';
