-- DMT_POZ_SUP_ADDR_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_POZ_SUP_ADDR_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_POZ_SUP_ADDR_TFM_ID_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"IMPORT_ACTION" VARCHAR2(10), 
	"VENDOR_NAME" VARCHAR2(360) NOT NULL ENABLE, 
	"PARTY_SITE_NAME" VARCHAR2(240) NOT NULL ENABLE, 
	"PARTY_SITE_NAME_NEW" VARCHAR2(240), 
	"COUNTRY" VARCHAR2(2) NOT NULL ENABLE, 
	"ADDRESS_LINE1" VARCHAR2(240) NOT NULL ENABLE, 
	"ADDRESS_LINE2" VARCHAR2(240), 
	"ADDRESS_LINE3" VARCHAR2(240), 
	"ADDRESS_LINE4" VARCHAR2(240), 
	"ADDRESS_LINES_PHONETIC" VARCHAR2(560), 
	"ADDR_ELEMENT_ATTRIBUTE1" VARCHAR2(150), 
	"ADDR_ELEMENT_ATTRIBUTE2" VARCHAR2(150), 
	"ADDR_ELEMENT_ATTRIBUTE3" VARCHAR2(150), 
	"ADDR_ELEMENT_ATTRIBUTE4" VARCHAR2(150), 
	"ADDR_ELEMENT_ATTRIBUTE5" VARCHAR2(150), 
	"BUILDING" VARCHAR2(40), 
	"FLOOR_NUMBER" VARCHAR2(40), 
	"CITY" VARCHAR2(60), 
	"STATE" VARCHAR2(60), 
	"PROVINCE" VARCHAR2(60), 
	"COUNTY" VARCHAR2(60), 
	"POSTAL_CODE" VARCHAR2(20), 
	"POSTAL_PLUS4_CODE" VARCHAR2(20), 
	"ADDRESSEE" VARCHAR2(360), 
	"GLOBAL_LOCATION_NUMBER" VARCHAR2(40), 
	"PARTY_SITE_LANGUAGE" VARCHAR2(4), 
	"INACTIVE_DATE" DATE, 
	"PHONE_COUNTRY_CODE" VARCHAR2(10), 
	"PHONE_AREA_CODE" VARCHAR2(10), 
	"PHONE" VARCHAR2(40), 
	"PHONE_EXTENSION" VARCHAR2(20), 
	"FAX_COUNTRY_CODE" VARCHAR2(10), 
	"FAX_AREA_CODE" VARCHAR2(10), 
	"FAX" VARCHAR2(40), 
	"RFQ_OR_BIDDING_PURPOSE_FLAG" VARCHAR2(1), 
	"ORDERING_PURPOSE_FLAG" VARCHAR2(1), 
	"REMIT_TO_PURPOSE_FLAG" VARCHAR2(1), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"ATTRIBUTE21" VARCHAR2(150), 
	"ATTRIBUTE22" VARCHAR2(150), 
	"ATTRIBUTE23" VARCHAR2(150), 
	"ATTRIBUTE24" VARCHAR2(150), 
	"ATTRIBUTE25" VARCHAR2(150), 
	"ATTRIBUTE26" VARCHAR2(150), 
	"ATTRIBUTE27" VARCHAR2(150), 
	"ATTRIBUTE28" VARCHAR2(150), 
	"ATTRIBUTE29" VARCHAR2(150), 
	"ATTRIBUTE30" VARCHAR2(150), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_NUMBER11" NUMBER, 
	"ATTRIBUTE_NUMBER12" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_DATE6" DATE, 
	"ATTRIBUTE_DATE7" DATE, 
	"ATTRIBUTE_DATE8" DATE, 
	"ATTRIBUTE_DATE9" DATE, 
	"ATTRIBUTE_DATE10" DATE, 
	"ATTRIBUTE_DATE11" DATE, 
	"ATTRIBUTE_DATE12" DATE, 
	"EMAIL_ADDRESS" VARCHAR2(240), 
	"DELIVERY_CHANNEL_CODE" VARCHAR2(30), 
	"BANK_INSTRUCTION1_CODE" VARCHAR2(30), 
	"BANK_INSTRUCTION2_CODE" VARCHAR2(30), 
	"BANK_INSTRUCTION_DETAILS" VARCHAR2(255), 
	"SETTLEMENT_PRIORITY" NUMBER, 
	"PAYMENT_TEXT_MESSAGE1" VARCHAR2(150), 
	"PAYMENT_TEXT_MESSAGE2" VARCHAR2(150), 
	"PAYMENT_TEXT_MESSAGE3" VARCHAR2(150), 
	"SERVICE_LEVEL_CODE" VARCHAR2(30), 
	"EXCLUSIVE_PAYMENT_FLAG" VARCHAR2(1), 
	"IBY_BANK_CHARGE_BEARER" VARCHAR2(30), 
	"PAYMENT_REASON_CODE" VARCHAR2(30), 
	"PAYMENT_REASON_COMMENTS" VARCHAR2(240), 
	"REMIT_ADVICE_DELIVERY_METHOD" VARCHAR2(30), 
	"REMIT_ADVICE_EMAIL" VARCHAR2(240), 
	"REMIT_ADVICE_FAX" VARCHAR2(100), 
	"FUSION_PARTY_SITE_ID" NUMBER, 
	"RESULTS_UPDATED_DATE" DATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_POZ_SUP_ADDR_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_ADDR_TFM_TBL_N1" ON "DMT_POZ_SUP_ADDR_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_ADDR_TFM_TBL_N4" ON "DMT_POZ_SUP_ADDR_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - from DMT_POZ_SUP_ADDR_TFM_ID_SEQ';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_POZ_SUP_ADDR_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when FBDI generator runs';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."FUSION_PARTY_SITE_ID" IS 'Fusion internal PARTY_SITE_ID - populated by BIP reconciliation';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."RESULTS_UPDATED_DATE" IS 'Timestamp of last BIP reconciliation update';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."STATUS" IS 'STAGED > GENERATED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_POZ_SUP_ADDR_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten. Prefixed: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_POZ_SUP_ADDR_TFM_TBL"  IS 'Supplier address transformed. Run-specific data â€” one row per staging row per run attempt. No key prefix applied (addresses use VENDOR_NAME + PARTY_SITE_NAME as natural key). Reconciliation populated by BIP. Interface table: POZ_SUP_ADDRESSES_INT.';
