-- DMT_GMS_AWD_FUND_SRC_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_GMS_AWD_FUND_SRC_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_GMS_AWD_FSRC_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"AWARD_NUMBER" VARCHAR2(300), 
	"FUNDING_SOURCE_NAME" VARCHAR2(360), 
	"FUNDING_SOURCE_NUMBER" VARCHAR2(240), 
	"COST_SHARE_REQ_BY_SPONSOR" VARCHAR2(1), 
	"COST_SHARE_APPROVED_BY_EMAIL" VARCHAR2(240), 
	"COST_SHARE_APPROVED_BY_NAME" VARCHAR2(240), 
	"COST_SHARE_APPROVED_BY_NUMBER" VARCHAR2(30), 
	"COST_SHARE_APPROVAL_DATE" DATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RESULTS_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_GMS_AWD_FSRC_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_GMS_AWD_FSRC_TFM_AWD_IX" ON "DMT_GMS_AWD_FUND_SRC_TFM_TBL" ("AWARD_NUMBER")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_GMS_AWD_FSRC_TFM_STG_IX" ON "DMT_GMS_AWD_FUND_SRC_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON TABLE "DMT_GMS_AWD_FUND_SRC_TFM_TBL"  IS 'Grant award funding sources transformed. FBDI interface: GMS_AWD_FND_SRC_INT.';
