-- DMT_PRJ_BUDGET_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PRJ_BUDGET_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PRJ_BUDGET_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"AWARD_NUMBER" VARCHAR2(240), 
	"FINANCIAL_PLAN_TYPE" VARCHAR2(150), 
	"PROJECT_NUMBER" VARCHAR2(25), 
	"PROJECT_NAME" VARCHAR2(240), 
	"TASK_NAME" VARCHAR2(255), 
	"TASK_NUMBER" VARCHAR2(100), 
	"PLAN_VERSION_NAME" VARCHAR2(240), 
	"PLAN_VERSION_DESCRIPTION" VARCHAR2(2000), 
	"PLAN_VERSION_STATUS" VARCHAR2(30), 
	"RESOURCE_NAME" VARCHAR2(240), 
	"PERIOD_NAME" VARCHAR2(50), 
	"PLANNING_CURRENCY" VARCHAR2(15), 
	"TOTAL_QUANTITY" NUMBER, 
	"TOTAL_TC_RAW_COST" NUMBER, 
	"TOTAL_TC_REVENUE" NUMBER, 
	"SRC_BUDGET_LINE_REFERENCE" VARCHAR2(240), 
	"FUNDING_SOURCE_NUMBER" VARCHAR2(240), 
	"FUNDING_SOURCE_NAME" VARCHAR2(240), 
	"PC_RAW_COST" NUMBER, 
	"PC_REVENUE" NUMBER, 
	"PFC_RAW_COST" NUMBER, 
	"PFC_REVENUE" NUMBER, 
	"TOTAL_TC_BRDND_COST" NUMBER, 
	"PC_BRDND_COST" NUMBER, 
	"PFC_BRDND_COST" NUMBER, 
	"LINE_TYPE" VARCHAR2(30), 
	"PLANNING_START_DATE" DATE, 
	"PLANNING_END_DATE" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150), 
	"ATTRIBUTE1" VARCHAR2(240), 
	"ATTRIBUTE2" VARCHAR2(240), 
	"ATTRIBUTE3" VARCHAR2(240), 
	"ATTRIBUTE4" VARCHAR2(240), 
	"ATTRIBUTE5" VARCHAR2(240), 
	"ATTRIBUTE6" VARCHAR2(240), 
	"ATTRIBUTE7" VARCHAR2(240), 
	"ATTRIBUTE8" VARCHAR2(240), 
	"ATTRIBUTE9" VARCHAR2(240), 
	"ATTRIBUTE10" VARCHAR2(240), 
	"ATTRIBUTE11" VARCHAR2(240), 
	"ATTRIBUTE12" VARCHAR2(240), 
	"ATTRIBUTE13" VARCHAR2(240), 
	"ATTRIBUTE14" VARCHAR2(240), 
	"ATTRIBUTE15" VARCHAR2(240), 
	"ATTRIBUTE16" VARCHAR2(240), 
	"ATTRIBUTE17" VARCHAR2(240), 
	"ATTRIBUTE18" VARCHAR2(240), 
	"ATTRIBUTE19" VARCHAR2(240), 
	"ATTRIBUTE20" VARCHAR2(240), 
	"ATTRIBUTE21" VARCHAR2(240), 
	"ATTRIBUTE22" VARCHAR2(240), 
	"ATTRIBUTE23" VARCHAR2(240), 
	"ATTRIBUTE24" VARCHAR2(240), 
	"ATTRIBUTE25" VARCHAR2(240), 
	"ATTRIBUTE26" VARCHAR2(240), 
	"ATTRIBUTE27" VARCHAR2(240), 
	"ATTRIBUTE28" VARCHAR2(240), 
	"ATTRIBUTE29" VARCHAR2(240), 
	"ATTRIBUTE30" VARCHAR2(240), 
	"PLAN_VERSION_NUMBER" NUMBER, 
	"PROCESSING_MODE" VARCHAR2(30), 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'', 
	"ERROR_TEXT" CLOB, 
	"RESULTS_UPDATED_DATE" DATE, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_PRJ_BUDGET_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PRJ_BUDGET_TFM_TBL_N1" ON "DMT_PRJ_BUDGET_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PRJ_BUDGET_TFM_TBL_N4" ON "DMT_PRJ_BUDGET_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
