-- DMT_HZ_PARTY_SITE_USES_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_HZ_PARTY_SITE_USES_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_HZ_PARTY_SITE_USES_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"BATCH_ID" NUMBER, 
	"PARTY_ORIG_SYSTEM" VARCHAR2(30), 
	"PARTY_ORIG_SYSTEM_REFERENCE" VARCHAR2(240), 
	"SITE_ORIG_SYSTEM" VARCHAR2(30), 
	"SITE_ORIG_SYSTEM_REFERENCE" VARCHAR2(240), 
	"SITE_USE_TYPE" VARCHAR2(30), 
	"PRIMARY_FLAG" VARCHAR2(1), 
	"INSERT_UPDATE_FLAG" VARCHAR2(1), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"SITEUSE_ORIG_SYSTEM" VARCHAR2(30), 
	"SITEUSE_ORIG_SYSTEM_REF" VARCHAR2(240), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_HZ_PTY_SITE_USES_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_HZ_PARTY_SITE_USES_STG_TBL_N1" ON "DMT_HZ_PARTY_SITE_USES_STG_TBL" ("STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_HZ_PARTY_SITE_USES_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_HZ_PARTY_SITE_USES_STG_SEQ';
COMMENT ON COLUMN "DMT_HZ_PARTY_SITE_USES_STG_TBL"."SITE_ORIG_SYSTEM_REFERENCE" IS 'Party site reference â€” links this use back to the parent party site in HZ_IMP_PARTYSITES_T';
COMMENT ON COLUMN "DMT_HZ_PARTY_SITE_USES_STG_TBL"."SITE_USE_TYPE" IS 'Site use purpose code â€” e.g. BILL_TO, SHIP_TO';
COMMENT ON COLUMN "DMT_HZ_PARTY_SITE_USES_STG_TBL"."STATUS" IS 'NEW > TRANSFORMED > LOADED / FAILED. RETRY = user override for selective reprocess.';
COMMENT ON COLUMN "DMT_HZ_PARTY_SITE_USES_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors â€” appended at each step, never overwritten. Prefixed: [PRE_VALIDATION] [TRANSFORM_ERROR] [FUSION_ERROR].';
COMMENT ON TABLE "DMT_HZ_PARTY_SITE_USES_STG_TBL"  IS 'Customer party site use staging. Raw user data only. Run-specific data in TFM table. FBDI interface: HZ_IMP_PARTYSITEUSES_T. CSV: HzImpPartySiteUsesT.csv.';
