-- DMT_TALENT_PROF_ITEM_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_TALENT_PROF_ITEM_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_TALENT_PROF_ITEM_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"PERSON_NUMBER" VARCHAR2(240) NOT NULL ENABLE, 
	"CONTENT_TYPE_NAME" VARCHAR2(240), 
	"CONTENT_ITEM_NAME" VARCHAR2(240), 
	"DATE_FROM" VARCHAR2(240), 
	"DATE_TO" VARCHAR2(240), 
	"RATING" VARCHAR2(240), 
	"PROFILE_CODE" VARCHAR2(240), 
	"INTEREST_LEVEL" VARCHAR2(240), 
	"RESULTS_UPDATED_DATE" DATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_TALENT_PROF_ITEM_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
