-- DMT_PJC_TXN_CONTROLS_TFM_TBL (generated from ATP 2026-07-03)

-- Identity-PK conversion (accepted coding standard 2026-07-08: "Identity
-- columns for keys; sequences only for shared, meaningful values").
-- In-place conversion of an existing non-identity column is NOT possible on
-- Oracle 26ai: every ALTER TABLE ... MODIFY variant raises ORA-30673, even on
-- an empty table. So a pre-identity table is converted by drop-and-recreate --
-- EMPTY tables only. A populated table is never dropped (staging/transform rows
-- are never deleted): the block raises with the manual rebuild recipe instead.
-- Deploy this file via db/install.sql: any FK dropped by the CASCADE here is
-- re-added by the FK DDL later in the same install run.
declare
  l_exists   pls_integer;
  l_identity pls_integer;
  l_rows     pls_integer;
begin
  select count(*) into l_exists from user_tables
  where  table_name = 'DMT_PJC_TXN_CONTROLS_TFM_TBL';
  if l_exists = 1 then
    select count(*) into l_identity from user_tab_identity_cols
    where  table_name = 'DMT_PJC_TXN_CONTROLS_TFM_TBL' and column_name = 'TFM_SEQUENCE_ID';
    if l_identity = 0 then
      execute immediate 'select count(*) from "DMT_PJC_TXN_CONTROLS_TFM_TBL" where rownum = 1' into l_rows;
      if l_rows = 0 then
        execute immediate 'drop table "DMT_PJC_TXN_CONTROLS_TFM_TBL" cascade constraints purge';
      else
        raise_application_error(-20001,
          'DMT_PJC_TXN_CONTROLS_TFM_TBL: cannot convert a populated table to an identity PK in place (ORA-30673). ' ||
          'Manual rebuild required: create a swap table with TFM_SEQUENCE_ID GENERATED BY DEFAULT ON NULL AS IDENTITY, ' ||
          'insert the rows preserving ids, rename, re-add constraints, then ALTER ... MODIFY to GENERATED ALWAYS (START WITH LIMIT VALUE).');
      end if;
    end if;
  end if;
end;
/

begin
  execute immediate 'CREATE TABLE "DMT_PJC_TXN_CONTROLS_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"TXN_CTRL_REFERENCE" VARCHAR2(240), 
	"PROJECT_NAME" VARCHAR2(240), 
	"PROJECT_NUMBER" VARCHAR2(25), 
	"TASK_NUMBER" VARCHAR2(100), 
	"TASK_NAME" VARCHAR2(240), 
	"EXPENDITURE_CATEGORY_NAME" VARCHAR2(240), 
	"EXPENDITURE_TYPE" VARCHAR2(240), 
	"NON_LABOR_RESOURCE" VARCHAR2(240), 
	"PERSON_NUMBER" VARCHAR2(30), 
	"PERSON_NAME" VARCHAR2(2000), 
	"PERSON_EMAILID" VARCHAR2(240), 
	"PERSON_TYPE" VARCHAR2(30), 
	"JOB_NAME" VARCHAR2(240), 
	"ORGANIZATION_NAME" VARCHAR2(240), 
	"CHARGEABLE_FLAG" VARCHAR2(1), 
	"BILLABLE_FLAG" VARCHAR2(1), 
	"CAPITALIZABLE_FLAG" VARCHAR2(1), 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"RESULTS_UPDATED_DATE" DATE, 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	"RECON_KEY" VARCHAR2(1000), 
	"FUSION_TXN_CONTROL_ID" NUMBER, 
	"WORK_QUEUE_ID" NUMBER, 
	 CONSTRAINT "DMT_PJC_TXN_CONTROLS_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- 2026-07-08 conformance tranche: rename must precede the index DDL below
-- (a pre-existing database still has the old column when the index runs).
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_PJC_TXN_CONTROLS_TFM_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_PJC_TXN_CONTROLS_TFM_TBL" RENAME COLUMN "STATUS" TO "TFM_STATUS"';
  end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PJC_TXN_CONTROLS_TFM_TBL_N1" ON "DMT_PJC_TXN_CONTROLS_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PJC_TXN_CONTROLS_TFM_TBL_N4" ON "DMT_PJC_TXN_CONTROLS_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - GENERATED ALWAYS AS IDENTITY';
COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_PJC_TXN_CONTROLS_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when FBDI generator runs';
COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."PROJECT_NUMBER" IS 'Project number with run prefix applied';
COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."TASK_NUMBER" IS 'Task number with run prefix applied (if populated)';
COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step â€” never overwritten. Prefixes: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_PJC_TXN_CONTROLS_TFM_TBL"  IS 'Project transaction controls transformed. Run-specific â€” one row per staging row per run attempt. PROJECT_NUMBER and TASK_NUMBER have run prefix applied. Reconciliation populated by BIP.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_PJC_TXN_CONTROLS_TFM_TBL' and column_name = 'RECON_KEY';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_PJC_TXN_CONTROLS_TFM_TBL" ADD ("RECON_KEY" VARCHAR2(1000))';
  end if;
end;
/
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_PJC_TXN_CONTROLS_TFM_TBL' and column_name = 'FUSION_TXN_CONTROL_ID';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_PJC_TXN_CONTROLS_TFM_TBL" ADD ("FUSION_TXN_CONTROL_ID" NUMBER)';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_PJC_TXN_CONTROLS_TFM_N1" ON "DMT_PJC_TXN_CONTROLS_TFM_TBL" ("RUN_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_PJC_TXN_CONTROLS_TFM_N2" ON "DMT_PJC_TXN_CONTROLS_TFM_TBL" ("RUN_ID", "TFM_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_PJC_TXN_CONTROLS_TFM_N3" ON "DMT_PJC_TXN_CONTROLS_TFM_TBL" ("RECON_KEY")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."TFM_STATUS" IS 'Transform lifecycle: STAGED > GENERATED > LOADED / FAILED.';
COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."RECON_KEY" IS 'Pre-concatenated business key (run prefix included) that BIP reconciliation matches against Fusion rows.';
COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."FUSION_TXN_CONTROL_ID" IS 'Fusion-assigned identifier captured from the Fusion base tables - written only by BIP reconciliation (positive proof of load).';

-- WORK_QUEUE_ID (work-queue-ID granularity foundation, accepted 2026-07-20;
-- docs/FIX_PLAN.md item 1). Guarded in-file ALTER so an existing DB converges
-- via db/install.sql (the CREATE above carries it for fresh installs). FK is
-- in db/tables/_foreign_keys.sql. NULLABLE for now; NOT NULL deferred.
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where table_name = 'DMT_PJC_TXN_CONTROLS_TFM_TBL' and column_name = 'WORK_QUEUE_ID';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_PJC_TXN_CONTROLS_TFM_TBL" ADD ("WORK_QUEUE_ID" NUMBER)';
  end if;
end;
/
COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."WORK_QUEUE_ID" IS 'The work queue item (DMT_WORK_QUEUE_TBL.QUEUE_ID) that processed this record. FK in _foreign_keys.sql. Stamped at generation; unit of per-work-item processing (design section 7, accepted 2026-07-20).';
