-- DMT_PJB_BILL_EVENTS_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PJB_BILL_EVENTS_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PJB_BILL_EVENTS_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"SOURCENAME" VARCHAR2(240), 
	"SOURCEREF" VARCHAR2(240), 
	"ORGANIZATION_NAME" VARCHAR2(240), 
	"CONTRACT_TYPE_NAME" VARCHAR2(240), 
	"CONTRACT_NUMBER" VARCHAR2(240), 
	"CONTRACT_LINE_NUMBER" VARCHAR2(240), 
	"EVENT_TYPE_NAME" VARCHAR2(240), 
	"EVENT_DESC" VARCHAR2(240), 
	"COMPLETION_DATE" DATE, 
	"BILL_TRNS_CURRENCY_CODE" VARCHAR2(15), 
	"BILL_TRNS_AMOUNT" NUMBER, 
	"PROJECT_NUMBER" VARCHAR2(25), 
	"TASK_NUMBER" VARCHAR2(100), 
	"BILL_HOLD_FLAG" VARCHAR2(1), 
	"REVENUE_HOLD_FLAG" VARCHAR2(1), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE_CHAR11" VARCHAR2(150), 
	"ATTRIBUTE_CHAR12" VARCHAR2(150), 
	"ATTRIBUTE_CHAR13" VARCHAR2(150), 
	"ATTRIBUTE_CHAR14" VARCHAR2(150), 
	"ATTRIBUTE_CHAR15" VARCHAR2(150), 
	"ATTRIBUTE_CHAR16" VARCHAR2(150), 
	"ATTRIBUTE_CHAR17" VARCHAR2(150), 
	"ATTRIBUTE_CHAR18" VARCHAR2(150), 
	"ATTRIBUTE_CHAR19" VARCHAR2(150), 
	"ATTRIBUTE_CHAR20" VARCHAR2(150), 
	"ATTRIBUTE_CHAR21" VARCHAR2(1000), 
	"ATTRIBUTE_CHAR22" VARCHAR2(1000), 
	"ATTRIBUTE_CHAR23" VARCHAR2(1000), 
	"ATTRIBUTE_CHAR24" VARCHAR2(1000), 
	"ATTRIBUTE_CHAR25" VARCHAR2(1000), 
	"ATTRIBUTE_CHAR26" VARCHAR2(1000), 
	"ATTRIBUTE_CHAR27" VARCHAR2(1000), 
	"ATTRIBUTE_CHAR28" VARCHAR2(1000), 
	"ATTRIBUTE_CHAR29" VARCHAR2(1000), 
	"ATTRIBUTE_CHAR30" VARCHAR2(1000), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_DATE6" DATE, 
	"ATTRIBUTE_DATE7" DATE, 
	"ATTRIBUTE_DATE8" DATE, 
	"ATTRIBUTE_DATE9" DATE, 
	"ATTRIBUTE_DATE10" DATE, 
	"ATTRIBUTE_TIMESTAMP1" DATE, 
	"ATTRIBUTE_TIMESTAMP2" DATE, 
	"ATTRIBUTE_TIMESTAMP3" DATE, 
	"ATTRIBUTE_TIMESTAMP4" DATE, 
	"ATTRIBUTE_TIMESTAMP5" DATE, 
	"REVERSE_ACCRUAL_FLAG" VARCHAR2(1), 
	"ITEM_EVENT_FLAG" VARCHAR2(1), 
	"QUANTITY" VARCHAR2(240), 
	"ITEM_NUMBER" VARCHAR2(300), 
	"UNIT_OF_MEASURE" VARCHAR2(240), 
	"UNIT_PRICE" VARCHAR2(240), 
	"PREPAYMENT_REQ_EVENT_NUM" VARCHAR2(240), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_PJB_BILL_EVENTS_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PJB_BILL_EVENTS_STG_TBL_N1" ON "DMT_PJB_BILL_EVENTS_STG_TBL" ("STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PJB_BILL_EVENTS_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_PJB_BILL_EVENTS_STG_SEQ';
COMMENT ON COLUMN "DMT_PJB_BILL_EVENTS_STG_TBL"."PROJECT_NUMBER" IS 'Project number from source system â€” prefix applied in TFM table';
COMMENT ON COLUMN "DMT_PJB_BILL_EVENTS_STG_TBL"."STATUS" IS 'NEW > TRANSFORMED > LOADED / FAILED. RETRY = user override for selective reprocess.';
COMMENT ON COLUMN "DMT_PJB_BILL_EVENTS_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors â€” appended at each step, never overwritten. Prefixed: [PRE_VALIDATION] [TRANSFORM_ERROR] [FUSION_ERROR].';
COMMENT ON TABLE "DMT_PJB_BILL_EVENTS_STG_TBL"  IS 'Billing Events staging. Raw user data only. Run-specific data in DMT_PJB_BILL_EVENTS_TFM_TBL. FBDI interface: PJB_BILLING_EVENTS_INT. CSV: PjbBillingEventsXface.csv.';
