-- DMT_ASSIGNMENT_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_ASSIGNMENT_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_ASSIGNMENT_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"EFFECTIVE_START_DATE" VARCHAR2(240), 
	"EFFECTIVE_END_DATE" VARCHAR2(240), 
	"PERSON_NUMBER" VARCHAR2(240) NOT NULL ENABLE, 
	"ASSIGNMENT_NAME" VARCHAR2(240), 
	"ASSIGNMENT_NUMBER" VARCHAR2(240), 
	"ASSIGNMENT_STATUS_TYPE_CODE" VARCHAR2(240), 
	"BUSINESS_UNIT_NAME" VARCHAR2(240), 
	"ACTION_CODE" VARCHAR2(240), 
	"JOB_CODE" VARCHAR2(240), 
	"GRADE_CODE" VARCHAR2(240), 
	"LOCATION_CODE" VARCHAR2(240), 
	"DEPARTMENT_NAME" VARCHAR2(240), 
	"POSITION_CODE" VARCHAR2(240), 
	"WORKER_CATEGORY" VARCHAR2(240), 
	"ASSIGNMENT_CATEGORY" VARCHAR2(240), 
	"FULL_PART_TIME" VARCHAR2(240), 
	"PERMANENT_TEMPORARY" VARCHAR2(240), 
	"NORMAL_HOURS" VARCHAR2(240), 
	"FREQUENCY" VARCHAR2(240), 
	"MANAGER_PERSON_NUMBER" VARCHAR2(240), 
	"MANAGER_ASSIGNMENT_NUMBER" VARCHAR2(240), 
	"PRIMARY_ASSIGNMENT_FLAG" VARCHAR2(240), 
	"FUSION_ASSIGNMENT_ID" NUMBER, 
	"RESULTS_UPDATED_DATE" DATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_ASSIGNMENT_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_ASSIGNMENT_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - from DMT_ASSIGNMENT_TFM_SEQ';
COMMENT ON COLUMN "DMT_ASSIGNMENT_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_ASSIGNMENT_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_ASSIGNMENT_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when DAT generator runs';
COMMENT ON COLUMN "DMT_ASSIGNMENT_TFM_TBL"."PERSON_NUMBER" IS 'Person number with run prefix applied';
COMMENT ON COLUMN "DMT_ASSIGNMENT_TFM_TBL"."FUSION_ASSIGNMENT_ID" IS 'Fusion internal ASSIGNMENT_ID - populated by reconciliation';
COMMENT ON COLUMN "DMT_ASSIGNMENT_TFM_TBL"."RESULTS_UPDATED_DATE" IS 'Timestamp of last reconciliation update';
COMMENT ON COLUMN "DMT_ASSIGNMENT_TFM_TBL"."STATUS" IS 'STAGED > GENERATED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_ASSIGNMENT_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten. Prefixed: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_ASSIGNMENT_TFM_TBL"  IS 'Assignment transformed. Run-specific data â€” one row per staging row per run attempt. PERSON_NUMBER has run prefix applied. Reconciliation populated after Fusion load. HDL business object: Assignment.';
