-- DMT_WORK_SCHED_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_WORK_SCHED_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_WORK_SCHED_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"WORK_SCHEDULE_NAME" VARCHAR2(240), 
	"SCHEDULE_START_DATE" VARCHAR2(240), 
	"SCHEDULE_END_DATE" VARCHAR2(240), 
	"WORK_SCHEDULE_TYPE" VARCHAR2(240), 
	"DESCRIPTION" VARCHAR2(240), 
	"LEGISLATIVE_DATA_GROUP_NAME" VARCHAR2(240), 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	"PERSON_NUMBER" VARCHAR2(30), 
	 CONSTRAINT "DMT_WORK_SCHED_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_WORK_SCHED_STG_TBL"."STATUS" IS 'NEW > RETRY > TRANSFORMED > LOADED / FAILED';
COMMENT ON TABLE "DMT_WORK_SCHED_STG_TBL"  IS 'WorkSchedule staging. HDL business object: WorkSchedule.';
