-- DMT_UPLOAD_ERROR_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_UPLOAD_ERROR_TBL" 
   (	"ERROR_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"LOG_ID" NUMBER NOT NULL ENABLE, 
	"ROW_NUMBER" NUMBER, 
	"COLUMN_NAME" VARCHAR2(100), 
	"ERROR_TYPE" VARCHAR2(50), 
	"ERROR_MESSAGE" VARCHAR2(4000), 
	"RAW_VALUE" VARCHAR2(4000), 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"BATCH_TAG" VARCHAR2(200), 
	 PRIMARY KEY ("ERROR_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "IDX_UPLOAD_ERR_LOG" ON "DMT_UPLOAD_ERROR_TBL" ("LOG_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_UPLOAD_ERROR_TBL"."ERROR_TYPE" IS 'PARSE_ERROR, TYPE_MISMATCH, REQUIRED_MISSING, INSERT_FAILED';
COMMENT ON COLUMN "DMT_UPLOAD_ERROR_TBL"."BATCH_TAG" IS 'Human-readable load identifier: scenario~filename~YYMMDDHHMISS';
COMMENT ON TABLE "DMT_UPLOAD_ERROR_TBL"  IS 'Per-row upload errors. FK to DMT_UPLOAD_LOG_TBL.LOG_ID.';
