-- DMT_GMS_AWD_HEADERS_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_GMS_AWD_HEADERS_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_GMS_AWD_HDR_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"AWARD_NAME" VARCHAR2(300), 
	"AWARD_NUMBER" VARCHAR2(300), 
	"SOURCE_TEMPLATE_NUMBER" VARCHAR2(25), 
	"BUSINESS_UNIT" VARCHAR2(240), 
	"LEGAL_ENTITY" VARCHAR2(240), 
	"CONTRACT_TYPE" VARCHAR2(240), 
	"PRIMARY_SPONSOR" VARCHAR2(360), 
	"PRINCIPAL_INVESTIGATOR_EMAIL" VARCHAR2(240), 
	"PI_NAME" VARCHAR2(240), 
	"PI_NUMBER" VARCHAR2(30), 
	"AWARD_START_DATE" DATE, 
	"AWARD_END_DATE" DATE, 
	"AWARD_DESCRIPTION" VARCHAR2(240), 
	"ORGANIZATION" VARCHAR2(240), 
	"INSTITUTION" VARCHAR2(240), 
	"SPONSOR_AWARD_NUMBER" VARCHAR2(240), 
	"AWARD_PURPOSE" VARCHAR2(240), 
	"AWARD_TYPE" VARCHAR2(240), 
	"EXPANDED_AUTHORITY_FLAG" VARCHAR2(1), 
	"COST_SHARE" VARCHAR2(240), 
	"DEFAULT_BURDEN_SCHEDULE" VARCHAR2(240), 
	"FIXED_DATE" DATE, 
	"PRE_AWARD_DATE" DATE, 
	"PRE_AWARD_SPENDING_ALLOWED" VARCHAR2(1), 
	"PRE_AWARD_GSF" VARCHAR2(240), 
	"CLOSE_DATE" DATE, 
	"COI_INST_POLICY_COMPLIANT" VARCHAR2(1), 
	"COI_REVIEW_COMPLETED" VARCHAR2(1), 
	"COI_APPROVAL_DATE" DATE, 
	"FT_PRIMARY_SPONSOR" VARCHAR2(360), 
	"FT_REF_AWARD_NAME" VARCHAR2(240), 
	"FT_FROM_DATE" DATE, 
	"FT_TO_DATE" DATE, 
	"FT_AMOUNT" VARCHAR2(240), 
	"FT_IS_FEDERAL" VARCHAR2(1), 
	"IS_INTELL_PROP_REPORTED" VARCHAR2(1), 
	"INTELL_PROP_DESC" VARCHAR2(240), 
	"PREV_AWARD_BU" VARCHAR2(240), 
	"PREV_AWARD_NAME" VARCHAR2(300), 
	"PREV_AWARD_RENEWAL_INPRG" VARCHAR2(1), 
	"PREV_AWARD_ABR" VARCHAR2(240), 
	"COST_SHARE_REQ_BY_SPONSOR" VARCHAR2(1), 
	"COST_SHARE_APPROVED_BY" VARCHAR2(240), 
	"COST_SHARE_APPROVAL_DATE" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"ATTRIBUTE_NUMBER1" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER2" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER3" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER4" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER5" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER6" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER7" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER8" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER9" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER10" VARCHAR2(240), 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_DATE6" DATE, 
	"ATTRIBUTE_DATE7" DATE, 
	"ATTRIBUTE_DATE8" DATE, 
	"ATTRIBUTE_DATE9" DATE, 
	"ATTRIBUTE_DATE10" DATE, 
	"ATTRIBUTE_TIMESTAMP1" DATE, 
	"ATTRIBUTE_TIMESTAMP2" DATE, 
	"ATTRIBUTE_TIMESTAMP3" DATE, 
	"ATTRIBUTE_TIMESTAMP4" DATE, 
	"ATTRIBUTE_TIMESTAMP5" DATE, 
	"ATTRIBUTE_TIMESTAMP6" DATE, 
	"ATTRIBUTE_TIMESTAMP7" DATE, 
	"ATTRIBUTE_TIMESTAMP8" DATE, 
	"ATTRIBUTE_TIMESTAMP9" DATE, 
	"ATTRIBUTE_TIMESTAMP10" DATE, 
	"CONTRACT_STATUS" VARCHAR2(240), 
	"CONTRACT_LINE_NAME" VARCHAR2(1995), 
	"LOC_FLAG" VARCHAR2(1), 
	"DOC_NUMBER" VARCHAR2(240), 
	"FED_INVOICE_FORMAT" VARCHAR2(240), 
	"BILL_PLAN_NAME" VARCHAR2(240), 
	"REVENUE_PLAN_NAME" VARCHAR2(240), 
	"INVOICE_METHOD" VARCHAR2(240), 
	"REVENUE_METHOD" VARCHAR2(240), 
	"BILLING_CYCLE" VARCHAR2(240), 
	"PAYMENT_TERM" VARCHAR2(240), 
	"LABOR_FORMAT" VARCHAR2(240), 
	"NON_LABOR_FORMAT" VARCHAR2(240), 
	"EVENT_FORMAT" VARCHAR2(240), 
	"CURRENCY_CODE" VARCHAR2(15), 
	"PRIMARY_SPONSOR_NUMBER" VARCHAR2(240), 
	"FT_PRIMARY_SPONSOR_NUMBER" VARCHAR2(240), 
	"NET_INVOICE_FLAG" VARCHAR2(1), 
	"INV_HDR_GROUPING_OPTIONS" VARCHAR2(2000), 
	"BILL_TO_SITE_LOCATION" VARCHAR2(150), 
	"BILL_TO_CONTACT_NAME" VARCHAR2(360), 
	"BILL_TO_CONTACT_EMAIL" VARCHAR2(320), 
	"SHIP_TO_SITE_LOCATION" VARCHAR2(150), 
	"BILL_SET_NUMBER" VARCHAR2(240), 
	"GENERATED_INVOICE_STATUS" VARCHAR2(80), 
	"INV_TRX_TYPE_NAME" VARCHAR2(20), 
	"BILL_TO_ACCT_NUMBER" VARCHAR2(30), 
	"SHIP_TO_ACCT_NUMBER" VARCHAR2(30), 
	"PREPAY_TRX_TYPE_NAME" VARCHAR2(20), 
	"FUSION_AWARD_ID" NUMBER, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RESULTS_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_GMS_AWD_HDR_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_GMS_AWD_HDR_TFM_AWD_IX" ON "DMT_GMS_AWD_HEADERS_TFM_TBL" ("AWARD_NUMBER")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_GMS_AWD_HDR_TFM_CSV_IX" ON "DMT_GMS_AWD_HEADERS_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_GMS_AWD_HDR_TFM_STG_IX" ON "DMT_GMS_AWD_HEADERS_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_GMS_AWD_HDR_TFM_STS_IX" ON "DMT_GMS_AWD_HEADERS_TFM_TBL" ("STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON TABLE "DMT_GMS_AWD_HEADERS_TFM_TBL"  IS 'Grant award header transformed. Run-specific data with INTEGRATION_ID. FBDI interface: GMS_AWARD_HEADERS_INT.';
