-- DMT_RA_DISTS_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_RA_DISTS_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_RA_DISTS_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"ORG_ID" VARCHAR2(240), 
	"ACCOUNT_CLASS" VARCHAR2(20), 
	"AMOUNT" NUMBER, 
	"PERCENT" NUMBER, 
	"ACCTD_AMOUNT" NUMBER, 
	"INTERFACE_LINE_CONTEXT" VARCHAR2(30), 
	"INTERFACE_LINE_ATTRIBUTE1" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE2" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE3" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE4" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE5" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE6" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE7" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE8" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE9" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE10" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE11" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE12" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE13" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE14" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE15" VARCHAR2(150), 
	"SEGMENT1" VARCHAR2(25), 
	"SEGMENT2" VARCHAR2(25), 
	"SEGMENT3" VARCHAR2(25), 
	"SEGMENT4" VARCHAR2(25), 
	"SEGMENT5" VARCHAR2(25), 
	"SEGMENT6" VARCHAR2(25), 
	"SEGMENT7" VARCHAR2(25), 
	"SEGMENT8" VARCHAR2(25), 
	"SEGMENT9" VARCHAR2(25), 
	"SEGMENT10" VARCHAR2(25), 
	"SEGMENT11" VARCHAR2(25), 
	"SEGMENT12" VARCHAR2(25), 
	"SEGMENT13" VARCHAR2(25), 
	"SEGMENT14" VARCHAR2(25), 
	"SEGMENT15" VARCHAR2(25), 
	"SEGMENT16" VARCHAR2(25), 
	"SEGMENT17" VARCHAR2(25), 
	"SEGMENT18" VARCHAR2(25), 
	"SEGMENT19" VARCHAR2(25), 
	"SEGMENT20" VARCHAR2(25), 
	"SEGMENT21" VARCHAR2(25), 
	"SEGMENT22" VARCHAR2(25), 
	"SEGMENT23" VARCHAR2(25), 
	"SEGMENT24" VARCHAR2(25), 
	"SEGMENT25" VARCHAR2(25), 
	"SEGMENT26" VARCHAR2(25), 
	"SEGMENT27" VARCHAR2(25), 
	"SEGMENT28" VARCHAR2(25), 
	"SEGMENT29" VARCHAR2(25), 
	"SEGMENT30" VARCHAR2(25), 
	"COMMENTS" VARCHAR2(240), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"BU_NAME" VARCHAR2(240), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_RA_DISTS_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_RA_DISTS_STG_TBL_N1" ON "DMT_RA_DISTS_STG_TBL" ("STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_RA_DISTS_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_RA_DISTS_STG_SEQ';
COMMENT ON COLUMN "DMT_RA_DISTS_STG_TBL"."INTERFACE_LINE_CONTEXT" IS 'Flexfield context â€” links this distribution to its parent line via INTERFACE_LINE_ATTRIBUTE1-15';
COMMENT ON COLUMN "DMT_RA_DISTS_STG_TBL"."STATUS" IS 'NEW > TRANSFORMED > LOADED / FAILED. RETRY = user override for selective reprocess.';
COMMENT ON COLUMN "DMT_RA_DISTS_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors â€” appended at each step, never overwritten. Prefixed: [PRE_VALIDATION] [TRANSFORM_ERROR] [FUSION_ERROR].';
COMMENT ON TABLE "DMT_RA_DISTS_STG_TBL"  IS 'AR Invoice distributions staging. Raw user data only. Run-specific data in DMT_RA_DISTS_TFM_TBL. FBDI interface: RA_INTERFACE_DISTRIBUTIONS_ALL. CSV: RaInterfaceDistributionsAll.csv.';
