-- DMT_PJC_TXN_CONTROLS_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PJC_TXN_CONTROLS_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PJC_TXN_CONTROLS_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"TXN_CTRL_REFERENCE" VARCHAR2(240), 
	"PROJECT_NAME" VARCHAR2(240), 
	"PROJECT_NUMBER" VARCHAR2(25), 
	"TASK_NUMBER" VARCHAR2(100), 
	"TASK_NAME" VARCHAR2(240), 
	"EXPENDITURE_CATEGORY_NAME" VARCHAR2(240), 
	"EXPENDITURE_TYPE" VARCHAR2(240), 
	"NON_LABOR_RESOURCE" VARCHAR2(240), 
	"PERSON_NUMBER" VARCHAR2(30), 
	"PERSON_NAME" VARCHAR2(2000), 
	"PERSON_EMAILID" VARCHAR2(240), 
	"PERSON_TYPE" VARCHAR2(30), 
	"JOB_NAME" VARCHAR2(240), 
	"ORGANIZATION_NAME" VARCHAR2(240), 
	"CHARGEABLE_FLAG" VARCHAR2(1), 
	"BILLABLE_FLAG" VARCHAR2(1), 
	"CAPITALIZABLE_FLAG" VARCHAR2(1), 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"RESULTS_UPDATED_DATE" DATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_PJC_TXN_CONTROLS_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PJC_TXN_CONTROLS_TFM_TBL_N1" ON "DMT_PJC_TXN_CONTROLS_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PJC_TXN_CONTROLS_TFM_TBL_N4" ON "DMT_PJC_TXN_CONTROLS_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - from DMT_PJC_TXN_CONTROLS_TFM_SEQ';
COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_PJC_TXN_CONTROLS_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when FBDI generator runs';
COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."PROJECT_NUMBER" IS 'Project number with run prefix applied';
COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."TASK_NUMBER" IS 'Task number with run prefix applied (if populated)';
COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."STATUS" IS 'STAGED > GENERATED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_PJC_TXN_CONTROLS_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step â€” never overwritten. Prefixes: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_PJC_TXN_CONTROLS_TFM_TBL"  IS 'Project transaction controls transformed. Run-specific â€” one row per staging row per run attempt. PROJECT_NUMBER and TASK_NUMBER have run prefix applied. Reconciliation populated by BIP.';
