-- DMT_FA_ASSET_ASSIGN_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_FA_ASSET_ASSIGN_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_FA_ASSET_ASSIGN_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"ASSET_NUMBER" VARCHAR2(30), 
	"UNITS_ASSIGNED" NUMBER, 
	"EXPENSE_ACCOUNT_SEGMENT1" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT2" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT3" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT4" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT5" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT6" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT7" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT8" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT9" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT10" VARCHAR2(25), 
	"LOCATION_SEGMENT1" VARCHAR2(30), 
	"LOCATION_SEGMENT2" VARCHAR2(30), 
	"LOCATION_SEGMENT3" VARCHAR2(30), 
	"LOCATION_SEGMENT4" VARCHAR2(30), 
	"LOCATION_SEGMENT5" VARCHAR2(30), 
	"LOCATION_SEGMENT6" VARCHAR2(30), 
	"LOCATION_SEGMENT7" VARCHAR2(30), 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'', 
	"ERROR_TEXT" CLOB, 
	"RESULTS_UPDATED_DATE" DATE, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_FA_ASSET_ASSIGN_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
