-- DMT_PIPELINE_RUN_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PIPELINE_RUN_TBL" 
   (	"RUN_ID" NUMBER DEFAULT DMT_OWNER.DMT_PIPELINE_RUN_SEQ.NEXTVAL NOT NULL ENABLE, 
	"INTEGRATION_ID" NUMBER, 
	"PIPELINE_CODES" VARCHAR2(500) NOT NULL ENABLE, 
	"RUN_TYPE" VARCHAR2(30) DEFAULT ''PIPELINE'' NOT NULL ENABLE, 
	"SCHEDULER_JOB_NAME" VARCHAR2(128), 
	"SUBMITTED_BY" VARCHAR2(100), 
	"SUBMITTED_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"STARTED_DATE" TIMESTAMP (6), 
	"COMPLETED_DATE" TIMESTAMP (6), 
	"RUN_STATUS" VARCHAR2(30) DEFAULT ''QUEUED'' NOT NULL ENABLE, 
	"CURRENT_CEMLI" VARCHAR2(60), 
	"CURRENT_STEP" VARCHAR2(30), 
	"CEMLI_SEQUENCE" VARCHAR2(4000) NOT NULL ENABLE, 
	"COMPLETED_CEMLIS" VARCHAR2(4000), 
	"FAILED_CEMLI" VARCHAR2(60), 
	"ERROR_MESSAGE" VARCHAR2(4000), 
	"SCENARIO_NAME" VARCHAR2(100), 
	"RUN_MODE" VARCHAR2(20) DEFAULT ''NEW'', 
	"INCLUDE_UNTAGGED" VARCHAR2(1) DEFAULT ''N'', 
	"PREFIX" VARCHAR2(20), 
	"ON_FAILURE_POLICY" VARCHAR2(30) DEFAULT ''HALT'', 
	"SCENARIO_ID" NUMBER GENERATED ALWAYS AS ("RUN_ID"+0) VIRTUAL , 
	 CONSTRAINT "DMT_PIPELINE_RUN_TYPE_CK" CHECK (
        RUN_TYPE IN (''PIPELINE'', ''STANDALONE'')
    ) ENABLE, 
	 CONSTRAINT "DMT_PIPELINE_RUN_PK" PRIMARY KEY ("RUN_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DMT_PIPELINE_RUN_STATUS_CK" CHECK (RUN_STATUS IN (''QUEUED'',''IN_PROGRESS'',''COMPLETED'',''COMPLETED_ERRORS'',''FAILED'',''CANCELLED'',''NO_ROWS_PROCESSED'')) ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_PIPELINE_RUN_STATUS_IX" ON "DMT_PIPELINE_RUN_TBL" ("RUN_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PIPELINE_RUN_TBL"."RUN_STATUS" IS 'QUEUED -> IN_PROGRESS -> COMPLETED | FAILED | CANCELLED';
COMMENT ON COLUMN "DMT_PIPELINE_RUN_TBL"."CURRENT_CEMLI" IS 'Which object type is currently executing (updated via autonomous txn)';
COMMENT ON COLUMN "DMT_PIPELINE_RUN_TBL"."CURRENT_STEP" IS 'VALIDATE | GENERATE | LOAD | POLL_LOAD | POLL_IMPORT | RECONCILE';
COMMENT ON COLUMN "DMT_PIPELINE_RUN_TBL"."CEMLI_SEQUENCE" IS 'Ordered CSV of all CEMLIs to run in this pipeline';
COMMENT ON COLUMN "DMT_PIPELINE_RUN_TBL"."COMPLETED_CEMLIS" IS 'CSV of CEMLIs that have finished successfully';
COMMENT ON TABLE "DMT_PIPELINE_RUN_TBL"  IS 'Async pipeline execution tracking. One row per DBMS_SCHEDULER submission.';
