-- DMT_POZ_SUP_CONTACTS_STG_TBL (generated from ATP 2026-07-03)

-- Identity-PK conversion (accepted coding standard 2026-07-08: "Identity
-- columns for keys; sequences only for shared, meaningful values").
-- In-place conversion of an existing non-identity column is NOT possible on
-- Oracle 26ai: every ALTER TABLE ... MODIFY variant (GENERATED ALWAYS,
-- GENERATED BY DEFAULT ON NULL) raises ORA-30673, even on an empty table
-- (probed on dmt2-local 2026-07-08). So a pre-identity table is converted by
-- drop-and-recreate -- EMPTY tables only. A populated table is never dropped
-- (staging rows are never deleted): the block raises with the manual
-- data-preserving rebuild recipe instead.
-- Deploy this file via db/install.sql: any FK dropped by the CASCADE here is
-- re-added by tables/_foreign_keys.sql later in the same install run.
declare
  l_exists   pls_integer;
  l_identity pls_integer;
  l_rows     pls_integer;
begin
  select count(*) into l_exists from user_tables
  where  table_name = 'DMT_POZ_SUP_CONTACTS_STG_TBL';
  if l_exists = 1 then
    select count(*) into l_identity from user_tab_identity_cols
    where  table_name = 'DMT_POZ_SUP_CONTACTS_STG_TBL' and column_name = 'STG_SEQUENCE_ID';
    if l_identity = 0 then
      execute immediate 'select count(*) from "DMT_POZ_SUP_CONTACTS_STG_TBL" where rownum = 1' into l_rows;
      if l_rows = 0 then
        execute immediate 'drop table "DMT_POZ_SUP_CONTACTS_STG_TBL" cascade constraints purge';
      else
        raise_application_error(-20001,
          'DMT_POZ_SUP_CONTACTS_STG_TBL: cannot convert a populated table to an identity PK in place (ORA-30673). ' ||
          'Manual rebuild required: create a swap table with STG_SEQUENCE_ID GENERATED BY DEFAULT ON NULL AS IDENTITY, ' ||
          'insert the rows preserving ids, rename, re-add constraints, then ALTER ... MODIFY to GENERATED ALWAYS (START WITH LIMIT VALUE).');
      end if;
    end if;
  end if;
end;
/

begin
  execute immediate 'CREATE TABLE "DMT_POZ_SUP_CONTACTS_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE, 
	"IMPORT_ACTION" VARCHAR2(10), 
	"VENDOR_NAME" VARCHAR2(360), 
	"PREFIX" VARCHAR2(30), 
	"FIRST_NAME" VARCHAR2(150), 
	"FIRST_NAME_NEW" VARCHAR2(150), 
	"MIDDLE_NAME" VARCHAR2(60), 
	"LAST_NAME" VARCHAR2(150), 
	"LAST_NAME_NEW" VARCHAR2(150), 
	"TITLE" VARCHAR2(30), 
	"PRIMARY_ADMIN_CONTACT" VARCHAR2(1), 
	"EMAIL_ADDRESS" VARCHAR2(240), 
	"EMAIL_ADDRESS_NEW" VARCHAR2(240), 
	"PHONE_COUNTRY_CODE" VARCHAR2(10), 
	"AREA_CODE" VARCHAR2(10), 
	"PHONE" VARCHAR2(40), 
	"PHONE_EXTENSION" VARCHAR2(20), 
	"FAX_COUNTRY_CODE" VARCHAR2(10), 
	"FAX_AREA_CODE" VARCHAR2(10), 
	"FAX" VARCHAR2(40), 
	"MOBILE_COUNTRY_CODE" VARCHAR2(10), 
	"MOBILE_AREA_CODE" VARCHAR2(10), 
	"MOBILE" VARCHAR2(40), 
	"INACTIVE_DATE" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"ATTRIBUTE21" VARCHAR2(150), 
	"ATTRIBUTE22" VARCHAR2(150), 
	"ATTRIBUTE23" VARCHAR2(150), 
	"ATTRIBUTE24" VARCHAR2(150), 
	"ATTRIBUTE25" VARCHAR2(150), 
	"ATTRIBUTE26" VARCHAR2(150), 
	"ATTRIBUTE27" VARCHAR2(150), 
	"ATTRIBUTE28" VARCHAR2(150), 
	"ATTRIBUTE29" VARCHAR2(150), 
	"ATTRIBUTE30" VARCHAR2(150), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_NUMBER11" NUMBER, 
	"ATTRIBUTE_NUMBER12" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_DATE6" DATE, 
	"ATTRIBUTE_DATE7" DATE, 
	"ATTRIBUTE_DATE8" DATE, 
	"ATTRIBUTE_DATE9" DATE, 
	"ATTRIBUTE_DATE10" DATE, 
	"ATTRIBUTE_DATE11" DATE, 
	"ATTRIBUTE_DATE12" DATE, 
	"USER_ACCOUNT_ACTION" VARCHAR2(30), 
	"ROLE1" VARCHAR2(100), 
	"ROLE2" VARCHAR2(100), 
	"ROLE3" VARCHAR2(100), 
	"ROLE4" VARCHAR2(100), 
	"ROLE5" VARCHAR2(100), 
	"ROLE6" VARCHAR2(100), 
	"ROLE7" VARCHAR2(100), 
	"ROLE8" VARCHAR2(100), 
	"ROLE9" VARCHAR2(100), 
	"ROLE10" VARCHAR2(100), 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_POZ_SUP_CONTACTS_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_POZ_SUP_CONTACTS_STG_TBL_N1" ON "DMT_POZ_SUP_CONTACTS_STG_TBL" ("STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_POZ_SUP_CONTACTS_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - identity column (GENERATED ALWAYS). Populated by the DB, never supplied by user.';
COMMENT ON COLUMN "DMT_POZ_SUP_CONTACTS_STG_TBL"."IMPORT_ACTION" IS 'CREATE or UPDATE';
COMMENT ON COLUMN "DMT_POZ_SUP_CONTACTS_STG_TBL"."PREFIX" IS 'Person name prefix e.g. Mr., Mrs., Dr. Maps to POZ_SUP_CONTACTS_INT.PREFIX';
COMMENT ON COLUMN "DMT_POZ_SUP_CONTACTS_STG_TBL"."PRIMARY_ADMIN_CONTACT" IS 'Y if this contact is the primary admin contact for the supplier';
COMMENT ON COLUMN "DMT_POZ_SUP_CONTACTS_STG_TBL"."USER_ACCOUNT_ACTION" IS 'CREATE_USER, INACTIVE_USER etc. â€” triggers Fusion user account creation';
COMMENT ON COLUMN "DMT_POZ_SUP_CONTACTS_STG_TBL"."ROLE1" IS 'Supplier portal role to assign. Up to 10 roles supported.';
COMMENT ON COLUMN "DMT_POZ_SUP_CONTACTS_STG_TBL"."SOURCE_ID" IS 'Natural key from source system';
COMMENT ON COLUMN "DMT_POZ_SUP_CONTACTS_STG_TBL"."STATUS" IS 'NEW > RETRY > TRANSFORMED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_POZ_SUP_CONTACTS_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten.';
COMMENT ON TABLE "DMT_POZ_SUP_CONTACTS_STG_TBL"  IS 'Supplier contact staging. Raw user-loaded data only. Run-specific data in DMT_POZ_SUP_CONTACTS_TFM_TBL. Interface table: POZ_SUP_CONTACTS_INT. CTL: PozSupContactsInt.ctl (25B). Contacts are at supplier level, not site level.';
