-- DMT_INV_TRX_SERIALS_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_INV_TRX_SERIALS_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_INV_TRX_SERIALS_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"FM_SERIAL_NUMBER" VARCHAR2(80), 
	"TO_SERIAL_NUMBER" VARCHAR2(80), 
	"VENDOR_SERIAL_NUMBER" VARCHAR2(80), 
	"VENDOR_LOT_NUMBER" VARCHAR2(30), 
	"PARENT_SERIAL_NUMBER" VARCHAR2(80), 
	"TERRITORY_CODE" VARCHAR2(30), 
	"ORIGINATION_DATE" DATE, 
	"STATUS_NAME" VARCHAR2(30), 
	"STATUS_CODE" VARCHAR2(80), 
	"TIME_SINCE_NEW" NUMBER, 
	"CYCLES_SINCE_NEW" NUMBER, 
	"TIME_SINCE_OVERHAUL" NUMBER, 
	"CYCLES_SINCE_OVERHAUL" NUMBER, 
	"TIME_SINCE_REPAIR" NUMBER, 
	"CYCLES_SINCE_REPAIR" NUMBER, 
	"TIME_SINCE_VISIT" NUMBER, 
	"CYCLES_SINCE_VISIT" NUMBER, 
	"TIME_SINCE_MARK" NUMBER, 
	"NUMBER_OF_REPAIRS" NUMBER, 
	"SERIAL_ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"C_ATTRIBUTE1" VARCHAR2(150), 
	"C_ATTRIBUTE2" VARCHAR2(150), 
	"C_ATTRIBUTE3" VARCHAR2(150), 
	"C_ATTRIBUTE4" VARCHAR2(150), 
	"C_ATTRIBUTE5" VARCHAR2(150), 
	"C_ATTRIBUTE6" VARCHAR2(150), 
	"C_ATTRIBUTE7" VARCHAR2(150), 
	"C_ATTRIBUTE8" VARCHAR2(150), 
	"C_ATTRIBUTE9" VARCHAR2(150), 
	"C_ATTRIBUTE10" VARCHAR2(150), 
	"C_ATTRIBUTE11" VARCHAR2(150), 
	"C_ATTRIBUTE12" VARCHAR2(150), 
	"C_ATTRIBUTE13" VARCHAR2(150), 
	"C_ATTRIBUTE14" VARCHAR2(150), 
	"C_ATTRIBUTE15" VARCHAR2(150), 
	"C_ATTRIBUTE16" VARCHAR2(150), 
	"C_ATTRIBUTE17" VARCHAR2(150), 
	"C_ATTRIBUTE18" VARCHAR2(150), 
	"C_ATTRIBUTE19" VARCHAR2(150), 
	"C_ATTRIBUTE20" VARCHAR2(150), 
	"D_ATTRIBUTE1" DATE, 
	"D_ATTRIBUTE2" DATE, 
	"D_ATTRIBUTE3" DATE, 
	"D_ATTRIBUTE4" DATE, 
	"D_ATTRIBUTE5" DATE, 
	"D_ATTRIBUTE6" DATE, 
	"D_ATTRIBUTE7" DATE, 
	"D_ATTRIBUTE8" DATE, 
	"D_ATTRIBUTE9" DATE, 
	"D_ATTRIBUTE10" DATE, 
	"N_ATTRIBUTE1" NUMBER, 
	"N_ATTRIBUTE2" NUMBER, 
	"N_ATTRIBUTE3" NUMBER, 
	"N_ATTRIBUTE4" NUMBER, 
	"N_ATTRIBUTE5" NUMBER, 
	"N_ATTRIBUTE6" NUMBER, 
	"N_ATTRIBUTE7" NUMBER, 
	"N_ATTRIBUTE8" NUMBER, 
	"N_ATTRIBUTE9" NUMBER, 
	"N_ATTRIBUTE10" NUMBER, 
	"T_ATTRIBUTE1" TIMESTAMP (6), 
	"T_ATTRIBUTE2" TIMESTAMP (6), 
	"T_ATTRIBUTE3" TIMESTAMP (6), 
	"T_ATTRIBUTE4" TIMESTAMP (6), 
	"T_ATTRIBUTE5" TIMESTAMP (6), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_TIMESTAMP1" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP2" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP3" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP4" TIMESTAMP (6), 
	"ATTRIBUTE_TIMESTAMP5" TIMESTAMP (6), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STG_STATUS" VARCHAR2(30) DEFAULT ''NEW'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_INV_TRX_SERIALS_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- 2026-07-08 conformance tranche: rename must precede the index DDL below
-- (a pre-existing database still has the old column when the index runs).
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_INV_TRX_SERIALS_STG_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_INV_TRX_SERIALS_STG_TBL" RENAME COLUMN "STATUS" TO "STG_STATUS"';
  end if;
end;
/

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_INV_TRX_SERIALS_STG_TBL' and column_name = 'SCENARIO_ID';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_INV_TRX_SERIALS_STG_TBL" ADD ("SCENARIO_ID" NUMBER)';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_INV_TRX_SERIALS_STG_N1" ON "DMT_INV_TRX_SERIALS_STG_TBL" ("STG_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_INV_TRX_SERIALS_STG_N2" ON "DMT_INV_TRX_SERIALS_STG_TBL" ("SCENARIO_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_INV_TRX_SERIALS_STG_TBL"."STG_STATUS" IS 'Staging lifecycle: NEW > TRANSFORMED / FAILED. Forward-only, never reset; errors accumulate in ERROR_TEXT.';

-- ---------------------------------------------------------------------------
-- 2026-07-09 conformance review F2 (STG/TFM infra-column dictionary, design
-- section 7 accepted 2026-07-08): STG_STATUS is VARCHAR2(30) DEFAULT 'NEW'
-- NOT NULL. Backfills any NULL statuses to the default, then converges a
-- pre-existing database; fresh installs get the shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_nullable varchar2(1);
begin
  select nullable into l_nullable from user_tab_columns
   where table_name = 'DMT_INV_TRX_SERIALS_STG_TBL' and column_name = 'STG_STATUS';
  if l_nullable = 'Y' then
    execute immediate 'UPDATE "DMT_INV_TRX_SERIALS_STG_TBL" SET "STG_STATUS" = ''NEW'' WHERE "STG_STATUS" IS NULL';
    execute immediate 'ALTER TABLE "DMT_INV_TRX_SERIALS_STG_TBL" MODIFY ("STG_STATUS" DEFAULT ''NEW'' NOT NULL)';
  end if;
end;
/
