-- DMT_PO_HEADERS_INT_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PO_HEADERS_INT_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PO_HEADERS_INT_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"INTERFACE_HEADER_KEY" VARCHAR2(50), 
	"ACTION" VARCHAR2(25), 
	"BATCH_ID" NUMBER, 
	"INTERFACE_SOURCE_CODE" VARCHAR2(25), 
	"APPROVAL_ACTION" VARCHAR2(25), 
	"DOCUMENT_NUM" VARCHAR2(20), 
	"DOCUMENT_TYPE_CODE" VARCHAR2(25), 
	"STYLE_DISPLAY_NAME" VARCHAR2(240), 
	"PRC_BU_NAME" VARCHAR2(240), 
	"REQ_BU_NAME" VARCHAR2(240), 
	"SOLDTO_LE_NAME" VARCHAR2(240), 
	"BILLTO_BU_NAME" VARCHAR2(240), 
	"AGENT_NAME" VARCHAR2(2000), 
	"CURRENCY_CODE" VARCHAR2(15), 
	"RATE" NUMBER, 
	"RATE_TYPE" VARCHAR2(30), 
	"RATE_DATE" DATE, 
	"COMMENTS" VARCHAR2(240), 
	"BILL_TO_LOCATION" VARCHAR2(60), 
	"SHIP_TO_LOCATION" VARCHAR2(60), 
	"VENDOR_NAME" VARCHAR2(360), 
	"VENDOR_NUM" VARCHAR2(30), 
	"VENDOR_SITE_CODE" VARCHAR2(15), 
	"VENDOR_CONTACT" VARCHAR2(360), 
	"VENDOR_DOC_NUM" VARCHAR2(25), 
	"FOB" VARCHAR2(30), 
	"FREIGHT_CARRIER" VARCHAR2(360), 
	"FREIGHT_TERMS" VARCHAR2(30), 
	"PAY_ON_CODE" VARCHAR2(25), 
	"PAYMENT_TERMS" VARCHAR2(50), 
	"ORIGINATOR_ROLE" VARCHAR2(25), 
	"CHANGE_ORDER_DESC" VARCHAR2(2000), 
	"ACCEPTANCE_REQUIRED_FLAG" VARCHAR2(1), 
	"ACCEPTANCE_WITHIN_DAYS" NUMBER, 
	"SUPPLIER_NOTIF_METHOD" VARCHAR2(25), 
	"FAX" VARCHAR2(60), 
	"EMAIL_ADDRESS" VARCHAR2(2000), 
	"CONFIRMING_ORDER_FLAG" VARCHAR2(1), 
	"NOTE_TO_VENDOR" VARCHAR2(1000), 
	"NOTE_TO_RECEIVER" VARCHAR2(1000), 
	"DEFAULT_TAXATION_COUNTRY" VARCHAR2(2), 
	"TAX_DOCUMENT_SUBTYPE" VARCHAR2(240), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_DATE6" DATE, 
	"ATTRIBUTE_DATE7" DATE, 
	"ATTRIBUTE_DATE8" DATE, 
	"ATTRIBUTE_DATE9" DATE, 
	"ATTRIBUTE_DATE10" DATE, 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_TIMESTAMP1" DATE, 
	"ATTRIBUTE_TIMESTAMP2" DATE, 
	"ATTRIBUTE_TIMESTAMP3" DATE, 
	"ATTRIBUTE_TIMESTAMP4" DATE, 
	"ATTRIBUTE_TIMESTAMP5" DATE, 
	"ATTRIBUTE_TIMESTAMP6" DATE, 
	"ATTRIBUTE_TIMESTAMP7" DATE, 
	"ATTRIBUTE_TIMESTAMP8" DATE, 
	"ATTRIBUTE_TIMESTAMP9" DATE, 
	"ATTRIBUTE_TIMESTAMP10" DATE, 
	"AGENT_EMAIL_ADDRESS" VARCHAR2(240), 
	"MODE_OF_TRANSPORT" VARCHAR2(80), 
	"SERVICE_LEVEL" VARCHAR2(80), 
	"FIRST_PTY_REG_NUM" VARCHAR2(50), 
	"THIRD_PTY_REG_NUM" VARCHAR2(50), 
	"BUYER_MANAGED_TRANSPORT_FLAG" VARCHAR2(1), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STG_STATUS" VARCHAR2(30) DEFAULT ''NEW'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_PO_HEADERS_INT_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- 2026-07-08 conformance tranche: rename must precede the index DDL below
-- (a pre-existing database still has the old column when the index runs).
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_PO_HEADERS_INT_STG_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_PO_HEADERS_INT_STG_TBL" RENAME COLUMN "STATUS" TO "STG_STATUS"';
  end if;
end;
/

COMMENT ON COLUMN "DMT_PO_HEADERS_INT_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_PO_HEADERS_INT_STG_SEQ';
COMMENT ON COLUMN "DMT_PO_HEADERS_INT_STG_TBL"."INTERFACE_HEADER_KEY" IS 'Unique key for this PO header in the FBDI import â€” links lines/locs/dists back to this header';
COMMENT ON COLUMN "DMT_PO_HEADERS_INT_STG_TBL"."DOCUMENT_NUM" IS 'PO number from source system â€” prefix applied in TFM table';
COMMENT ON COLUMN "DMT_PO_HEADERS_INT_STG_TBL"."VENDOR_NUM" IS 'Supplier number â€” expected to have DEPENDENT_PREFIX applied when looking up migrated supplier';
COMMENT ON COLUMN "DMT_PO_HEADERS_INT_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors â€” appended at each step, never overwritten. Prefixed: [PRE_VALIDATION] [TRANSFORM_ERROR] [FUSION_ERROR].';
COMMENT ON TABLE "DMT_PO_HEADERS_INT_STG_TBL"  IS 'Purchase Order header staging. Raw user data only. Run-specific data in DMT_PO_HEADERS_INT_TFM_TBL. FBDI interface: PO_HEADERS_INTERFACE. CSV: PoHeadersInterfaceOrder.csv.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
begin
  execute immediate 'CREATE INDEX "DMT_PO_HEADERS_INT_STG_N1" ON "DMT_PO_HEADERS_INT_STG_TBL" ("STG_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_PO_HEADERS_INT_STG_N2" ON "DMT_PO_HEADERS_INT_STG_TBL" ("SCENARIO_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PO_HEADERS_INT_STG_TBL"."STG_STATUS" IS 'Staging lifecycle: NEW > TRANSFORMED / FAILED. Forward-only, never reset; errors accumulate in ERROR_TEXT.';

-- ---------------------------------------------------------------------------
-- 2026-07-09 conformance review F2 (STG/TFM infra-column dictionary, design
-- section 7 accepted 2026-07-08): STG_STATUS is VARCHAR2(30) DEFAULT 'NEW'
-- NOT NULL. Backfills any NULL statuses to the default, then converges a
-- pre-existing database; fresh installs get the shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_nullable varchar2(1);
begin
  select nullable into l_nullable from user_tab_columns
   where table_name = 'DMT_PO_HEADERS_INT_STG_TBL' and column_name = 'STG_STATUS';
  if l_nullable = 'Y' then
    execute immediate 'UPDATE "DMT_PO_HEADERS_INT_STG_TBL" SET "STG_STATUS" = ''NEW'' WHERE "STG_STATUS" IS NULL';
    execute immediate 'ALTER TABLE "DMT_PO_HEADERS_INT_STG_TBL" MODIFY ("STG_STATUS" DEFAULT ''NEW'' NOT NULL)';
  end if;
end;
/
