-- DMT_ABSENCE_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_ABSENCE_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_ABSENCE_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"EFFECTIVE_START_DATE" VARCHAR2(240), 
	"EFFECTIVE_END_DATE" VARCHAR2(240), 
	"PERSON_NUMBER" VARCHAR2(240) NOT NULL ENABLE, 
	"EMPLOYER_NAME" VARCHAR2(240), 
	"ABSENCE_NAME" VARCHAR2(240), 
	"ABSENCE_TYPE" VARCHAR2(240), 
	"ABSENCE_CATEGORY" VARCHAR2(240), 
	"ABSENCE_STATUS" VARCHAR2(240), 
	"START_DATE" VARCHAR2(240), 
	"END_DATE" VARCHAR2(240), 
	"START_TIME" VARCHAR2(240), 
	"END_TIME" VARCHAR2(240), 
	"APPROVAL_STATUS_CODE" VARCHAR2(240), 
	"DURATION" VARCHAR2(240), 
	"SUBMISSION_DATE" VARCHAR2(240), 
	"ABSENCE_REASON" VARCHAR2(240), 
	"COMMENTS" VARCHAR2(4000), 
	"RESULTS_UPDATED_DATE" DATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_ABSENCE_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
