-- DMT_INV_TRX_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_INV_TRX_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_INV_TRX_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"ORGANIZATION_NAME" VARCHAR2(240), 
	"ITEM_NUMBER" VARCHAR2(300), 
	"REVISION" VARCHAR2(18), 
	"SUBINVENTORY_CODE" VARCHAR2(10), 
	"LOCATOR_NAME" VARCHAR2(2000), 
	"LOC_SEGMENT1" VARCHAR2(40), 
	"LOC_SEGMENT2" VARCHAR2(40), 
	"LOC_SEGMENT3" VARCHAR2(40), 
	"LOC_SEGMENT4" VARCHAR2(40), 
	"LOC_SEGMENT5" VARCHAR2(40), 
	"LOC_SEGMENT6" VARCHAR2(40), 
	"LOC_SEGMENT7" VARCHAR2(40), 
	"LOC_SEGMENT8" VARCHAR2(40), 
	"LOC_SEGMENT9" VARCHAR2(40), 
	"LOC_SEGMENT10" VARCHAR2(40), 
	"LOC_SEGMENT11" VARCHAR2(40), 
	"LOC_SEGMENT12" VARCHAR2(40), 
	"LOC_SEGMENT13" VARCHAR2(40), 
	"LOC_SEGMENT14" VARCHAR2(40), 
	"LOC_SEGMENT15" VARCHAR2(40), 
	"LOC_SEGMENT16" VARCHAR2(40), 
	"LOC_SEGMENT17" VARCHAR2(40), 
	"LOC_SEGMENT18" VARCHAR2(40), 
	"LOC_SEGMENT19" VARCHAR2(40), 
	"LOC_SEGMENT20" VARCHAR2(40), 
	"TRANSACTION_QUANTITY" NUMBER, 
	"TRANSACTION_UOM" VARCHAR2(3), 
	"TRANSACTION_UNIT_OF_MEASURE" VARCHAR2(25), 
	"RESERVATION_QUANTITY" NUMBER, 
	"TRANSACTION_DATE" DATE, 
	"TRANSACTION_SOURCE_TYPE_NAME" VARCHAR2(30), 
	"TRANSACTION_TYPE_NAME" VARCHAR2(80), 
	"TRANSACTION_ACTION_NAME" VARCHAR2(80), 
	"TRANSACTION_SOURCE_NAME" VARCHAR2(80), 
	"TRANSACTION_REFERENCE" VARCHAR2(240), 
	"TRANSACTION_MODE" VARCHAR2(30), 
	"LOCK_FLAG" VARCHAR2(30), 
	"PROCESS_FLAG" VARCHAR2(30), 
	"INV_LOTSERIAL_INTERFACE_NUM" VARCHAR2(30), 
	"TRANSACTION_GROUP_ID" NUMBER, 
	"TRANSACTION_GROUP_SEQ" NUMBER, 
	"TRANSACTION_BATCH_ID" NUMBER, 
	"TRANSACTION_BATCH_SEQ" NUMBER, 
	"TRANSFER_ORGANIZATION_TYPE" VARCHAR2(30), 
	"TRANSFER_ORGANIZATION_NAME" VARCHAR2(240), 
	"TRANSFER_SUBINVENTORY" VARCHAR2(10), 
	"TRANSFER_LOCATOR_NAME" VARCHAR2(2000), 
	"XFER_LOC_SEGMENT1" VARCHAR2(40), 
	"XFER_LOC_SEGMENT2" VARCHAR2(40), 
	"XFER_LOC_SEGMENT3" VARCHAR2(40), 
	"XFER_LOC_SEGMENT4" VARCHAR2(40), 
	"XFER_LOC_SEGMENT5" VARCHAR2(40), 
	"XFER_LOC_SEGMENT6" VARCHAR2(40), 
	"XFER_LOC_SEGMENT7" VARCHAR2(40), 
	"XFER_LOC_SEGMENT8" VARCHAR2(40), 
	"XFER_LOC_SEGMENT9" VARCHAR2(40), 
	"XFER_LOC_SEGMENT10" VARCHAR2(40), 
	"XFER_LOC_SEGMENT11" VARCHAR2(40), 
	"XFER_LOC_SEGMENT12" VARCHAR2(40), 
	"XFER_LOC_SEGMENT13" VARCHAR2(40), 
	"XFER_LOC_SEGMENT14" VARCHAR2(40), 
	"XFER_LOC_SEGMENT15" VARCHAR2(40), 
	"XFER_LOC_SEGMENT16" VARCHAR2(40), 
	"XFER_LOC_SEGMENT17" VARCHAR2(40), 
	"XFER_LOC_SEGMENT18" VARCHAR2(40), 
	"XFER_LOC_SEGMENT19" VARCHAR2(40), 
	"XFER_LOC_SEGMENT20" VARCHAR2(40), 
	"PRIMARY_QUANTITY" NUMBER, 
	"SECONDARY_TRANSACTION_QUANTITY" NUMBER, 
	"SECONDARY_UOM_CODE" VARCHAR2(3), 
	"SECONDARY_UNIT_OF_MEASURE" VARCHAR2(25), 
	"SOURCE_CODE" VARCHAR2(30), 
	"SOURCE_HEADER_ID" NUMBER, 
	"SOURCE_LINE_ID" NUMBER, 
	"INVENTORY_ITEM" VARCHAR2(2000), 
	"DSP_SEGMENT1" VARCHAR2(40), 
	"DSP_SEGMENT2" VARCHAR2(40), 
	"DSP_SEGMENT3" VARCHAR2(40), 
	"DSP_SEGMENT4" VARCHAR2(40), 
	"DSP_SEGMENT5" VARCHAR2(40), 
	"DSP_SEGMENT6" VARCHAR2(40), 
	"DSP_SEGMENT7" VARCHAR2(40), 
	"DSP_SEGMENT8" VARCHAR2(40), 
	"DSP_SEGMENT9" VARCHAR2(40), 
	"DSP_SEGMENT10" VARCHAR2(40), 
	"DSP_SEGMENT11" VARCHAR2(40), 
	"DSP_SEGMENT12" VARCHAR2(40), 
	"DSP_SEGMENT13" VARCHAR2(40), 
	"DSP_SEGMENT14" VARCHAR2(40), 
	"DSP_SEGMENT15" VARCHAR2(40), 
	"DSP_SEGMENT16" VARCHAR2(40), 
	"DSP_SEGMENT17" VARCHAR2(40), 
	"DSP_SEGMENT18" VARCHAR2(40), 
	"DSP_SEGMENT19" VARCHAR2(40), 
	"DSP_SEGMENT20" VARCHAR2(40), 
	"DSP_SEGMENT21" VARCHAR2(40), 
	"DSP_SEGMENT22" VARCHAR2(40), 
	"DSP_SEGMENT23" VARCHAR2(40), 
	"DSP_SEGMENT24" VARCHAR2(40), 
	"DSP_SEGMENT25" VARCHAR2(40), 
	"DSP_SEGMENT26" VARCHAR2(40), 
	"DSP_SEGMENT27" VARCHAR2(40), 
	"DSP_SEGMENT28" VARCHAR2(40), 
	"DSP_SEGMENT29" VARCHAR2(40), 
	"DSP_SEGMENT30" VARCHAR2(40), 
	"DST_SEGMENT1" VARCHAR2(25), 
	"DST_SEGMENT2" VARCHAR2(25), 
	"DST_SEGMENT3" VARCHAR2(25), 
	"DST_SEGMENT4" VARCHAR2(25), 
	"DST_SEGMENT5" VARCHAR2(25), 
	"DST_SEGMENT6" VARCHAR2(25), 
	"DST_SEGMENT7" VARCHAR2(25), 
	"DST_SEGMENT8" VARCHAR2(25), 
	"DST_SEGMENT9" VARCHAR2(25), 
	"DST_SEGMENT10" VARCHAR2(25), 
	"DST_SEGMENT11" VARCHAR2(25), 
	"DST_SEGMENT12" VARCHAR2(25), 
	"DST_SEGMENT13" VARCHAR2(25), 
	"DST_SEGMENT14" VARCHAR2(25), 
	"DST_SEGMENT15" VARCHAR2(25), 
	"DST_SEGMENT16" VARCHAR2(25), 
	"DST_SEGMENT17" VARCHAR2(25), 
	"DST_SEGMENT18" VARCHAR2(25), 
	"DST_SEGMENT19" VARCHAR2(25), 
	"DST_SEGMENT20" VARCHAR2(25), 
	"DST_SEGMENT21" VARCHAR2(25), 
	"DST_SEGMENT22" VARCHAR2(25), 
	"DST_SEGMENT23" VARCHAR2(25), 
	"DST_SEGMENT24" VARCHAR2(25), 
	"DST_SEGMENT25" VARCHAR2(25), 
	"DST_SEGMENT26" VARCHAR2(25), 
	"DST_SEGMENT27" VARCHAR2(25), 
	"DST_SEGMENT28" VARCHAR2(25), 
	"DST_SEGMENT29" VARCHAR2(25), 
	"DST_SEGMENT30" VARCHAR2(25), 
	"REASON_NAME" VARCHAR2(80), 
	"CURRENCY_NAME" VARCHAR2(80), 
	"CURRENCY_CODE" VARCHAR2(30), 
	"CURRENCY_CONVERSION_TYPE" VARCHAR2(30), 
	"CURRENCY_CONVERSION_RATE" NUMBER, 
	"CURRENCY_CONVERSION_DATE" DATE, 
	"TRANSACTION_COST" NUMBER, 
	"TRANSFER_COST" NUMBER, 
	"NEW_AVERAGE_COST" NUMBER, 
	"VALUE_CHANGE" NUMBER, 
	"PERCENTAGE_CHANGE" NUMBER, 
	"TRANSACTION_COST_IDENTIFIER" VARCHAR2(30), 
	"USE_CURRENT_COST" VARCHAR2(1), 
	"LOCATION_TYPE" VARCHAR2(30), 
	"EMPLOYEE_CODE" VARCHAR2(10), 
	"RECEIVING_DOCUMENT" VARCHAR2(10), 
	"LINE_ITEM_NUM" NUMBER, 
	"SHIPMENT_NUMBER" VARCHAR2(30), 
	"TRANSPORTATION_COST" NUMBER, 
	"CONTAINERS" NUMBER, 
	"WAYBILL_AIRBILL" VARCHAR2(20), 
	"EXPECTED_ARRIVAL_DATE" DATE, 
	"REQUIRED_FLAG" VARCHAR2(1), 
	"SHIPPABLE_FLAG" VARCHAR2(1), 
	"SHIPPED_QUANTITY" NUMBER, 
	"VALIDATION_REQUIRED" NUMBER, 
	"NEGATIVE_REQ_FLAG" NUMBER, 
	"OWNING_TP_TYPE" VARCHAR2(30), 
	"TRANSFER_OWNING_TP_TYPE" VARCHAR2(30), 
	"OWNING_ORGANIZATION_NAME" VARCHAR2(240), 
	"OWNING_ORGANIZATION_ID" NUMBER, 
	"XFR_OWNING_ORGANIZATION_NAME" VARCHAR2(240), 
	"XFR_OWNING_ORGANIZATION_ID" NUMBER, 
	"TRANSFER_PERCENTAGE" NUMBER, 
	"PLANNING_TP_TYPE" VARCHAR2(30), 
	"TRANSFER_PLANNING_TP_TYPE" VARCHAR2(30), 
	"ROUTING_REVISION" VARCHAR2(3), 
	"ROUTING_REVISION_DATE" DATE, 
	"ALTERNATE_BOM_DESIGNATOR" VARCHAR2(10), 
	"ALTERNATE_ROUTING_DESIGNATOR" VARCHAR2(10), 
	"ORGANIZATION_TYPE" VARCHAR2(30), 
	"USSGL_TRANSACTION_CODE" VARCHAR2(30), 
	"WIP_ENTITY_TYPE" NUMBER, 
	"SCHEDULE_UPDATE_CODE" NUMBER, 
	"SETUP_TEARDOWN_CODE" NUMBER, 
	"PRIMARY_SWITCH" NUMBER, 
	"MRP_CODE" NUMBER, 
	"OPERATION_SEQ_NUM" NUMBER, 
	"WIP_SUPPLY_TYPE" NUMBER, 
	"RELIEVE_RESERVATIONS_FLAG" VARCHAR2(1), 
	"RELIEVE_HIGH_LEVEL_RSV_FLAG" VARCHAR2(1), 
	"TRANSFER_PRICE" NUMBER, 
	"BUILD_BREAK_TO_UOM" VARCHAR2(3), 
	"BUILD_BREAK_TO_UNIT_OF_MEASURE" VARCHAR2(25), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_TIMESTAMP1" DATE, 
	"ATTRIBUTE_TIMESTAMP2" DATE, 
	"ATTRIBUTE_TIMESTAMP3" DATE, 
	"ATTRIBUTE_TIMESTAMP4" DATE, 
	"ATTRIBUTE_TIMESTAMP5" DATE, 
	"DEFAULT_TAXATION_COUNTRY" VARCHAR2(30), 
	"DOCUMENT_SUB_TYPE" VARCHAR2(30), 
	"TRX_BUSINESS_CATEGORY" VARCHAR2(30), 
	"USER_DEFINED_FISC_CLASS" VARCHAR2(30), 
	"TAX_INVOICE_NUMBER" VARCHAR2(30), 
	"TAX_INVOICE_DATE" VARCHAR2(30), 
	"PRODUCT_CATEGORY" VARCHAR2(30), 
	"PRODUCT_TYPE" VARCHAR2(30), 
	"ASSESSABLE_VALUE" VARCHAR2(30), 
	"TAX_CLASSIFICATION_CODE" VARCHAR2(30), 
	"EXEMPT_CERTIFICATE_NUMBER" VARCHAR2(30), 
	"EXEMPT_REASON_CODE" VARCHAR2(30), 
	"INTENDED_USE" VARCHAR2(30), 
	"FIRST_PTY_NUMBER" VARCHAR2(30), 
	"THIRD_PTY_NUMBER" VARCHAR2(30), 
	"FINAL_DISCHARGE_LOC_CODE" VARCHAR2(30), 
	"CATEGORY_NAME" VARCHAR2(30), 
	"PRC_BU_NAME" VARCHAR2(240), 
	"VENDOR_NAME" VARCHAR2(240), 
	"VENDOR_NUMBER" VARCHAR2(30), 
	"CONSIGNMENT_AGREEMENT_NUM" VARCHAR2(30), 
	"EXTERNAL_SYSTEM_PACKING_UNIT" VARCHAR2(150), 
	"INV_PROJECT" VARCHAR2(25), 
	"INV_TASK" VARCHAR2(100), 
	"COUNTRY_OF_ORIGIN_NAME" VARCHAR2(80), 
	"TRANSFER_INV_PROJECT" VARCHAR2(25), 
	"TRANSFER_INV_TASK" VARCHAR2(100), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"RESULTS_UPDATED_DATE" DATE, 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"FUSION_ID" VARCHAR2(30), 
	"RUN_ID" NUMBER, 
	"RECON_KEY" VARCHAR2(1000), 
	"WORK_QUEUE_ID" NUMBER, 
	 CONSTRAINT "DMT_INV_TRX_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_INV_TRX_TFM_TBL' and column_name = 'RECON_KEY';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_INV_TRX_TFM_TBL" ADD ("RECON_KEY" VARCHAR2(1000))';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_INV_TRX_TFM_N1" ON "DMT_INV_TRX_TFM_TBL" ("RUN_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_INV_TRX_TFM_N2" ON "DMT_INV_TRX_TFM_TBL" ("RUN_ID", "TFM_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_INV_TRX_TFM_N3" ON "DMT_INV_TRX_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_INV_TRX_TFM_N4" ON "DMT_INV_TRX_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_INV_TRX_TFM_N5" ON "DMT_INV_TRX_TFM_TBL" ("RECON_KEY")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_INV_TRX_TFM_TBL"."TFM_STATUS" IS 'Transform lifecycle: STAGED > GENERATED > LOADED / FAILED.';
COMMENT ON COLUMN "DMT_INV_TRX_TFM_TBL"."RECON_KEY" IS 'Pre-concatenated business key (run prefix included) that BIP reconciliation matches against Fusion rows.';

-- ---------------------------------------------------------------------------
-- 2026-07-09 conformance review F2 (STG/TFM infra-column dictionary, design
-- section 7 accepted 2026-07-08): TFM_STATUS is VARCHAR2(30) DEFAULT 'STAGED'
-- NOT NULL. Backfills any NULL statuses to the default, then converges a
-- pre-existing database; fresh installs get the shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_nullable varchar2(1);
begin
  select nullable into l_nullable from user_tab_columns
   where table_name = 'DMT_INV_TRX_TFM_TBL' and column_name = 'TFM_STATUS';
  if l_nullable = 'Y' then
    execute immediate 'UPDATE "DMT_INV_TRX_TFM_TBL" SET "TFM_STATUS" = ''STAGED'' WHERE "TFM_STATUS" IS NULL';
    execute immediate 'ALTER TABLE "DMT_INV_TRX_TFM_TBL" MODIFY ("TFM_STATUS" DEFAULT ''STAGED'' NOT NULL)';
  end if;
end;
/
