-- DMT_FA_ASSET_HDR_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_FA_ASSET_HDR_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_FA_ASSET_HDR_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"ASSET_NUMBER" VARCHAR2(30), 
	"DESCRIPTION" VARCHAR2(240), 
	"ASSET_CATEGORY_SEGMENT1" VARCHAR2(30), 
	"ASSET_CATEGORY_SEGMENT2" VARCHAR2(30), 
	"ASSET_CATEGORY_SEGMENT3" VARCHAR2(30), 
	"ASSET_CATEGORY_SEGMENT4" VARCHAR2(30), 
	"ASSET_CATEGORY_SEGMENT5" VARCHAR2(30), 
	"ASSET_CATEGORY_SEGMENT6" VARCHAR2(30), 
	"ASSET_CATEGORY_SEGMENT7" VARCHAR2(30), 
	"ASSET_TYPE" VARCHAR2(11), 
	"MANUFACTURER_NAME" VARCHAR2(30), 
	"SERIAL_NUMBER" VARCHAR2(35), 
	"TAG_NUMBER" VARCHAR2(15), 
	"MODEL_NUMBER" VARCHAR2(40), 
	"PROPERTY_TYPE_CODE" VARCHAR2(30), 
	"PROPERTY_1245_1250_CODE" VARCHAR2(4), 
	"IN_USE_FLAG" VARCHAR2(3), 
	"OWNED_LEASED" VARCHAR2(15), 
	"NEW_USED" VARCHAR2(4), 
	"DATE_PLACED_IN_SERVICE" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(210), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"PARENT_ASSET_NUMBER" VARCHAR2(30), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_FA_ASSET_HDR_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
