-- DMT_REST_LOOKUP_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_REST_LOOKUP_TBL" 
   (	"REST_LOOKUP_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"OBJECT_TYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"REST_ENDPOINT" VARCHAR2(500) NOT NULL ENABLE, 
	"QUERY_FILTER" VARCHAR2(500) NOT NULL ENABLE, 
	"KEY_COLUMN" VARCHAR2(100) NOT NULL ENABLE, 
	"DISPLAY_FIELDS" VARCHAR2(1000) NOT NULL ENABLE, 
	"DISPLAY_LABELS" VARCHAR2(1000) NOT NULL ENABLE, 
	"AUTH_TYPE" VARCHAR2(30) DEFAULT ''ERP'', 
	"ENABLED" VARCHAR2(1) DEFAULT ''Y'' NOT NULL ENABLE, 
	"NOTES" VARCHAR2(500), 
	 PRIMARY KEY ("REST_LOOKUP_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DMT_REST_LOOKUP_OBJ_UK" UNIQUE ("OBJECT_TYPE")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
