-- DMT_RCV_HEADERS_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_RCV_HEADERS_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_RCV_HEADERS_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"PROCESSING_STATUS_CODE" VARCHAR2(25), 
	"HEADER_INTERFACE_NUM" VARCHAR2(25), 
	"RECEIPT_SOURCE_CODE" VARCHAR2(25), 
	"ASN_TYPE" VARCHAR2(25), 
	"TRANSACTION_TYPE" VARCHAR2(25), 
	"NOTICE_CREATION_DATE" DATE, 
	"SHIPMENT_NUM" VARCHAR2(30), 
	"RECEIPT_NUM" VARCHAR2(30), 
	"VENDOR_NAME" VARCHAR2(240), 
	"VENDOR_NUM" VARCHAR2(30), 
	"VENDOR_SITE_CODE" VARCHAR2(240), 
	"FROM_ORGANIZATION_CODE" VARCHAR2(18), 
	"SHIP_TO_ORGANIZATION_CODE" VARCHAR2(18), 
	"LOCATION_CODE" VARCHAR2(60), 
	"BILL_OF_LADING" VARCHAR2(25), 
	"PACKING_SLIP" VARCHAR2(25), 
	"SHIPPED_DATE" DATE, 
	"FREIGHT_CARRIER_NAME" VARCHAR2(360), 
	"EXPECTED_RECEIPT_DATE" DATE, 
	"NUM_OF_CONTAINERS" NUMBER, 
	"WAYBILL_AIRBILL_NUM" VARCHAR2(20), 
	"COMMENTS" VARCHAR2(4000), 
	"GROSS_WEIGHT" NUMBER, 
	"GROSS_WEIGHT_UNIT_OF_MEASURE" VARCHAR2(25), 
	"NET_WEIGHT" NUMBER, 
	"NET_WEIGHT_UNIT_OF_MEASURE" VARCHAR2(25), 
	"TAR_WEIGHT" NUMBER, 
	"TAR_WEIGHT_UNIT_OF_MEASURE" VARCHAR2(25), 
	"PACKAGING_CODE" VARCHAR2(5), 
	"CARRIER_METHOD" VARCHAR2(2), 
	"CARRIER_EQUIPMENT" VARCHAR2(10), 
	"SPECIAL_HANDLING_CODE" VARCHAR2(3), 
	"HAZARD_CODE" VARCHAR2(1), 
	"HAZARD_CLASS" VARCHAR2(40), 
	"HAZARD_DESCRIPTION" VARCHAR2(80), 
	"FREIGHT_TERMS" VARCHAR2(25), 
	"FREIGHT_BILL_NUMBER" VARCHAR2(35), 
	"INVOICE_NUM" VARCHAR2(50), 
	"INVOICE_DATE" DATE, 
	"TOTAL_INVOICE_AMOUNT" NUMBER, 
	"TAX_NAME" VARCHAR2(50), 
	"TAX_AMOUNT" NUMBER, 
	"FREIGHT_AMOUNT" NUMBER, 
	"CURRENCY_CODE" VARCHAR2(15), 
	"CONVERSION_RATE_TYPE" VARCHAR2(30), 
	"CONVERSION_RATE" NUMBER, 
	"CONVERSION_RATE_DATE" DATE, 
	"PAYMENT_TERMS_NAME" VARCHAR2(50), 
	"EMPLOYEE_NAME" VARCHAR2(240), 
	"VALIDATION_FLAG" VARCHAR2(1), 
	"TRANSACTION_DATE" DATE, 
	"CUSTOMER_ACCOUNT_NUMBER" VARCHAR2(30), 
	"CUSTOMER_PARTY_NAME" VARCHAR2(360), 
	"CUSTOMER_PARTY_NUMBER" VARCHAR2(30), 
	"BUSINESS_UNIT" VARCHAR2(240), 
	"RA_OUTSOURCER_PARTY_NAME" VARCHAR2(240), 
	"RECEIPT_ADVICE_NUMBER" VARCHAR2(240), 
	"RA_DOCUMENT_CODE" VARCHAR2(240), 
	"RA_DOCUMENT_NUMBER" VARCHAR2(240), 
	"RA_DOC_REVISION_NUMBER" VARCHAR2(240), 
	"RA_DOC_REVISION_DATE" DATE, 
	"RA_DOC_CREATION_DATE" DATE, 
	"RA_DOC_LAST_UPDATE_DATE" DATE, 
	"RA_OUTSOURCER_CONTACT_NAME" VARCHAR2(240), 
	"RA_VENDOR_SITE_NAME" VARCHAR2(240), 
	"RA_NOTE_TO_RECEIVER" VARCHAR2(480), 
	"RA_DOO_SOURCE_SYSTEM_NAME" VARCHAR2(240), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_NUMBER6" NUMBER, 
	"ATTRIBUTE_NUMBER7" NUMBER, 
	"ATTRIBUTE_NUMBER8" NUMBER, 
	"ATTRIBUTE_NUMBER9" NUMBER, 
	"ATTRIBUTE_NUMBER10" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_TIMESTAMP1" DATE, 
	"ATTRIBUTE_TIMESTAMP2" DATE, 
	"ATTRIBUTE_TIMESTAMP3" DATE, 
	"ATTRIBUTE_TIMESTAMP4" DATE, 
	"ATTRIBUTE_TIMESTAMP5" DATE, 
	"GL_DATE" DATE, 
	"RECEIPT_HEADER_ID" VARCHAR2(240), 
	"EXTERNAL_SYS_TXN_REFERENCE" VARCHAR2(300), 
	"EMPLOYEE_ID" VARCHAR2(240), 
	"FUSION_RECEIPT_HEADER_ID" NUMBER, 
	"RESULTS_UPDATED_DATE" DATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_RCV_HEADERS_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_RCV_HDR_TFM_N1" ON "DMT_RCV_HEADERS_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_RCV_HDR_TFM_N4" ON "DMT_RCV_HEADERS_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_RCV_HEADERS_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - from DMT_RCV_HEADERS_TFM_SEQ';
COMMENT ON COLUMN "DMT_RCV_HEADERS_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_RCV_HEADERS_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_RCV_HEADERS_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when FBDI generator runs';
COMMENT ON COLUMN "DMT_RCV_HEADERS_TFM_TBL"."RECEIPT_NUM" IS 'Receipt number with run prefix applied: NVL(prefix,'''') || stg.RECEIPT_NUM';
COMMENT ON COLUMN "DMT_RCV_HEADERS_TFM_TBL"."FUSION_RECEIPT_HEADER_ID" IS 'Fusion internal RECEIPT_HEADER_ID â€” populated by BIP reconciliation';
COMMENT ON COLUMN "DMT_RCV_HEADERS_TFM_TBL"."STATUS" IS 'STAGED > GENERATED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_RCV_HEADERS_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step â€” never overwritten. Prefixes: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_RCV_HEADERS_TFM_TBL"  IS 'Receiving header transformed (MiscReceipts / Items on Hand). Run-specific â€” one row per staging row per run attempt. RECEIPT_NUM has run prefix applied. Reconciliation populated by BIP.';
