-- DMT_PERSON_PHONE_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_PERSON_PHONE_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_PERSON_PHONE_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"EFFECTIVE_START_DATE" VARCHAR2(240), 
	"EFFECTIVE_END_DATE" VARCHAR2(240), 
	"PERSON_NUMBER" VARCHAR2(240) NOT NULL ENABLE, 
	"PHONE_TYPE" VARCHAR2(240), 
	"COUNTRY_CODE_NUMBER" VARCHAR2(240), 
	"AREA_CODE" VARCHAR2(240), 
	"PHONE_NUMBER" VARCHAR2(240), 
	"EXTENSION" VARCHAR2(240), 
	"PRIMARY_FLAG" VARCHAR2(240), 
	"FROM_DATE" VARCHAR2(240), 
	"TO_DATE" VARCHAR2(240), 
	"RESULTS_UPDATED_DATE" DATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_PERSON_PHONE_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_PERSON_PHONE_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - from DMT_PERSON_PHONE_TFM_SEQ';
COMMENT ON COLUMN "DMT_PERSON_PHONE_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_PERSON_PHONE_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_PERSON_PHONE_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when DAT generator runs';
COMMENT ON COLUMN "DMT_PERSON_PHONE_TFM_TBL"."PERSON_NUMBER" IS 'Person number with run prefix applied';
COMMENT ON COLUMN "DMT_PERSON_PHONE_TFM_TBL"."RESULTS_UPDATED_DATE" IS 'Timestamp of last reconciliation update';
COMMENT ON COLUMN "DMT_PERSON_PHONE_TFM_TBL"."STATUS" IS 'STAGED > GENERATED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_PERSON_PHONE_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten. Prefixed: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_PERSON_PHONE_TFM_TBL"  IS 'Person phone transformed. Run-specific data â€” one row per staging row per run attempt. HDL business object: PersonPhone.';
