-- DMT_GMS_AWD_HEADERS_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_GMS_AWD_HEADERS_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_GMS_AWD_HDR_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"AWARD_NAME" VARCHAR2(300), 
	"AWARD_NUMBER" VARCHAR2(300), 
	"SOURCE_TEMPLATE_NUMBER" VARCHAR2(25), 
	"BUSINESS_UNIT" VARCHAR2(240), 
	"LEGAL_ENTITY" VARCHAR2(240), 
	"CONTRACT_TYPE" VARCHAR2(240), 
	"PRIMARY_SPONSOR" VARCHAR2(360), 
	"PRINCIPAL_INVESTIGATOR_EMAIL" VARCHAR2(240), 
	"PI_NAME" VARCHAR2(240), 
	"PI_NUMBER" VARCHAR2(30), 
	"AWARD_START_DATE" DATE, 
	"AWARD_END_DATE" DATE, 
	"AWARD_DESCRIPTION" VARCHAR2(240), 
	"ORGANIZATION" VARCHAR2(240), 
	"INSTITUTION" VARCHAR2(240), 
	"SPONSOR_AWARD_NUMBER" VARCHAR2(240), 
	"AWARD_PURPOSE" VARCHAR2(240), 
	"AWARD_TYPE" VARCHAR2(240), 
	"EXPANDED_AUTHORITY_FLAG" VARCHAR2(1), 
	"COST_SHARE" VARCHAR2(240), 
	"DEFAULT_BURDEN_SCHEDULE" VARCHAR2(240), 
	"FIXED_DATE" DATE, 
	"PRE_AWARD_DATE" DATE, 
	"PRE_AWARD_SPENDING_ALLOWED" VARCHAR2(1), 
	"PRE_AWARD_GSF" VARCHAR2(240), 
	"CLOSE_DATE" DATE, 
	"COI_INST_POLICY_COMPLIANT" VARCHAR2(1), 
	"COI_REVIEW_COMPLETED" VARCHAR2(1), 
	"COI_APPROVAL_DATE" DATE, 
	"FT_PRIMARY_SPONSOR" VARCHAR2(360), 
	"FT_REF_AWARD_NAME" VARCHAR2(240), 
	"FT_FROM_DATE" DATE, 
	"FT_TO_DATE" DATE, 
	"FT_AMOUNT" VARCHAR2(240), 
	"FT_IS_FEDERAL" VARCHAR2(1), 
	"IS_INTELL_PROP_REPORTED" VARCHAR2(1), 
	"INTELL_PROP_DESC" VARCHAR2(240), 
	"PREV_AWARD_BU" VARCHAR2(240), 
	"PREV_AWARD_NAME" VARCHAR2(300), 
	"PREV_AWARD_RENEWAL_INPRG" VARCHAR2(1), 
	"PREV_AWARD_ABR" VARCHAR2(240), 
	"COST_SHARE_REQ_BY_SPONSOR" VARCHAR2(1), 
	"COST_SHARE_APPROVED_BY" VARCHAR2(240), 
	"COST_SHARE_APPROVAL_DATE" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"ATTRIBUTE_NUMBER1" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER2" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER3" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER4" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER5" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER6" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER7" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER8" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER9" VARCHAR2(240), 
	"ATTRIBUTE_NUMBER10" VARCHAR2(240), 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"ATTRIBUTE_DATE6" DATE, 
	"ATTRIBUTE_DATE7" DATE, 
	"ATTRIBUTE_DATE8" DATE, 
	"ATTRIBUTE_DATE9" DATE, 
	"ATTRIBUTE_DATE10" DATE, 
	"ATTRIBUTE_TIMESTAMP1" DATE, 
	"ATTRIBUTE_TIMESTAMP2" DATE, 
	"ATTRIBUTE_TIMESTAMP3" DATE, 
	"ATTRIBUTE_TIMESTAMP4" DATE, 
	"ATTRIBUTE_TIMESTAMP5" DATE, 
	"ATTRIBUTE_TIMESTAMP6" DATE, 
	"ATTRIBUTE_TIMESTAMP7" DATE, 
	"ATTRIBUTE_TIMESTAMP8" DATE, 
	"ATTRIBUTE_TIMESTAMP9" DATE, 
	"ATTRIBUTE_TIMESTAMP10" DATE, 
	"CONTRACT_STATUS" VARCHAR2(240), 
	"CONTRACT_LINE_NAME" VARCHAR2(1995), 
	"LOC_FLAG" VARCHAR2(1), 
	"DOC_NUMBER" VARCHAR2(240), 
	"FED_INVOICE_FORMAT" VARCHAR2(240), 
	"BILL_PLAN_NAME" VARCHAR2(240), 
	"REVENUE_PLAN_NAME" VARCHAR2(240), 
	"INVOICE_METHOD" VARCHAR2(240), 
	"REVENUE_METHOD" VARCHAR2(240), 
	"BILLING_CYCLE" VARCHAR2(240), 
	"PAYMENT_TERM" VARCHAR2(240), 
	"LABOR_FORMAT" VARCHAR2(240), 
	"NON_LABOR_FORMAT" VARCHAR2(240), 
	"EVENT_FORMAT" VARCHAR2(240), 
	"CURRENCY_CODE" VARCHAR2(15), 
	"PRIMARY_SPONSOR_NUMBER" VARCHAR2(240), 
	"FT_PRIMARY_SPONSOR_NUMBER" VARCHAR2(240), 
	"NET_INVOICE_FLAG" VARCHAR2(1), 
	"INV_HDR_GROUPING_OPTIONS" VARCHAR2(2000), 
	"BILL_TO_SITE_LOCATION" VARCHAR2(150), 
	"BILL_TO_CONTACT_NAME" VARCHAR2(360), 
	"BILL_TO_CONTACT_EMAIL" VARCHAR2(320), 
	"SHIP_TO_SITE_LOCATION" VARCHAR2(150), 
	"BILL_SET_NUMBER" VARCHAR2(240), 
	"GENERATED_INVOICE_STATUS" VARCHAR2(80), 
	"INV_TRX_TYPE_NAME" VARCHAR2(20), 
	"BILL_TO_ACCT_NUMBER" VARCHAR2(30), 
	"SHIP_TO_ACCT_NUMBER" VARCHAR2(30), 
	"PREPAY_TRX_TYPE_NAME" VARCHAR2(20), 
	"FUSION_AWARD_ID" NUMBER, 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RESULTS_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	"RECON_KEY" VARCHAR2(1000), 
	"WORK_QUEUE_ID" NUMBER, 
	 CONSTRAINT "DMT_GMS_AWD_HDR_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- 2026-07-08 conformance tranche: rename must precede the index DDL below
-- (a pre-existing database still has the old column when the index runs).
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_GMS_AWD_HEADERS_TFM_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_GMS_AWD_HEADERS_TFM_TBL" RENAME COLUMN "STATUS" TO "TFM_STATUS"';
  end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_GMS_AWD_HDR_TFM_AWD_IX" ON "DMT_GMS_AWD_HEADERS_TFM_TBL" ("AWARD_NUMBER")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_GMS_AWD_HDR_TFM_CSV_IX" ON "DMT_GMS_AWD_HEADERS_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_GMS_AWD_HDR_TFM_STG_IX" ON "DMT_GMS_AWD_HEADERS_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_GMS_AWD_HDR_TFM_STS_IX" ON "DMT_GMS_AWD_HEADERS_TFM_TBL" ("TFM_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON TABLE "DMT_GMS_AWD_HEADERS_TFM_TBL"  IS 'Grant award header transformed. Run-specific data with INTEGRATION_ID. FBDI interface: GMS_AWARD_HEADERS_INT.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_GMS_AWD_HEADERS_TFM_TBL' and column_name = 'RECON_KEY';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_GMS_AWD_HEADERS_TFM_TBL" ADD ("RECON_KEY" VARCHAR2(1000))';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_GMS_AWD_HEADERS_TFM_N1" ON "DMT_GMS_AWD_HEADERS_TFM_TBL" ("RUN_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_GMS_AWD_HEADERS_TFM_N2" ON "DMT_GMS_AWD_HEADERS_TFM_TBL" ("RUN_ID", "TFM_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_GMS_AWD_HEADERS_TFM_N3" ON "DMT_GMS_AWD_HEADERS_TFM_TBL" ("RECON_KEY")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_GMS_AWD_HEADERS_TFM_TBL"."TFM_STATUS" IS 'Transform lifecycle: STAGED > GENERATED > LOADED / FAILED.';
COMMENT ON COLUMN "DMT_GMS_AWD_HEADERS_TFM_TBL"."RECON_KEY" IS 'Pre-concatenated business key (run prefix included) that BIP reconciliation matches against Fusion rows.';

-- WORK_QUEUE_ID (work-queue-ID granularity foundation, accepted 2026-07-20;
-- docs/FIX_PLAN.md item 1). Guarded in-file ALTER so an existing DB converges
-- via db/install.sql (the CREATE above carries it for fresh installs). FK is
-- in db/tables/_foreign_keys.sql. NULLABLE for now; NOT NULL deferred.
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where table_name = 'DMT_GMS_AWD_HEADERS_TFM_TBL' and column_name = 'WORK_QUEUE_ID';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_GMS_AWD_HEADERS_TFM_TBL" ADD ("WORK_QUEUE_ID" NUMBER)';
  end if;
end;
/
COMMENT ON COLUMN "DMT_GMS_AWD_HEADERS_TFM_TBL"."WORK_QUEUE_ID" IS 'The work queue item (DMT_WORK_QUEUE_TBL.QUEUE_ID) that processed this record. FK in _foreign_keys.sql. Stamped at generation; unit of per-work-item processing (design section 7, accepted 2026-07-20).';
