-- DMT_WORKER_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_WORKER_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_WORKER_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"EFFECTIVE_START_DATE" VARCHAR2(240), 
	"EFFECTIVE_END_DATE" VARCHAR2(240), 
	"PERSON_NUMBER" VARCHAR2(240) NOT NULL ENABLE, 
	"DATE_OF_BIRTH" VARCHAR2(240), 
	"ACTION_CODE" VARCHAR2(240), 
	"START_DATE" VARCHAR2(240), 
	"LEGAL_ENTITY_NAME" VARCHAR2(240), 
	"CATEGORY_CODE" VARCHAR2(240), 
	"PROJECTED_TERMINATION_DATE" VARCHAR2(240), 
	"BLOOD_TYPE" VARCHAR2(240), 
	"CORRESPONDENCE_LANGUAGE" VARCHAR2(240), 
	"TOWN_OF_BIRTH" VARCHAR2(240), 
	"REGION_OF_BIRTH" VARCHAR2(240), 
	"COUNTRY_OF_BIRTH" VARCHAR2(240), 
	"DATE_OF_DEATH" VARCHAR2(240), 
	"FUSION_PERSON_ID" NUMBER, 
	"RESULTS_UPDATED_DATE" DATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	 CONSTRAINT "DMT_WORKER_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_WORKER_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - from DMT_WORKER_TFM_SEQ';
COMMENT ON COLUMN "DMT_WORKER_TFM_TBL"."STG_SEQUENCE_ID" IS 'FK to DMT_WORKER_STG_TBL â€” which staging row this was transformed from';
COMMENT ON COLUMN "DMT_WORKER_TFM_TBL"."FBDI_CSV_ID" IS 'FK to DMT_FBDI_CSV_TBL â€” populated when DAT generator runs';
COMMENT ON COLUMN "DMT_WORKER_TFM_TBL"."PERSON_NUMBER" IS 'Person number with run prefix applied';
COMMENT ON COLUMN "DMT_WORKER_TFM_TBL"."FUSION_PERSON_ID" IS 'Fusion internal PERSON_ID - populated by reconciliation';
COMMENT ON COLUMN "DMT_WORKER_TFM_TBL"."RESULTS_UPDATED_DATE" IS 'Timestamp of last reconciliation update';
COMMENT ON COLUMN "DMT_WORKER_TFM_TBL"."STATUS" IS 'STAGED > GENERATED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_WORKER_TFM_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten. Prefixed: [TRANSFORM_ERROR] [POST_VALIDATION] [FUSION_ERROR]';
COMMENT ON TABLE "DMT_WORKER_TFM_TBL"  IS 'Worker transformed. Run-specific data â€” one row per staging row per run attempt. PERSON_NUMBER has run prefix applied. Reconciliation populated after Fusion load. HDL business object: Worker.';
