-- DMT_FA_ASSET_ASSIGN_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_FA_ASSET_ASSIGN_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_FA_ASSET_ASSIGN_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"ASSET_NUMBER" VARCHAR2(30), 
	"UNITS_ASSIGNED" NUMBER, 
	"EXPENSE_ACCOUNT_SEGMENT1" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT2" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT3" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT4" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT5" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT6" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT7" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT8" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT9" VARCHAR2(25), 
	"EXPENSE_ACCOUNT_SEGMENT10" VARCHAR2(25), 
	"LOCATION_SEGMENT1" VARCHAR2(30), 
	"LOCATION_SEGMENT2" VARCHAR2(30), 
	"LOCATION_SEGMENT3" VARCHAR2(30), 
	"LOCATION_SEGMENT4" VARCHAR2(30), 
	"LOCATION_SEGMENT5" VARCHAR2(30), 
	"LOCATION_SEGMENT6" VARCHAR2(30), 
	"LOCATION_SEGMENT7" VARCHAR2(30), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_FA_ASSET_ASSIGN_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/
