-- DMT_W2_BAL_DTL_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_W2_BAL_DTL_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_W2_BAL_DTL_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"PERSON_NUMBER" VARCHAR2(240), 
	"BALANCE_NAME" VARCHAR2(240), 
	"DIMENSION_NAME" VARCHAR2(240), 
	"CONTEXT_NAME" VARCHAR2(240), 
	"CONTEXT_VALUE" VARCHAR2(240), 
	"VALUE" VARCHAR2(240), 
	"CURRENCY_CODE" VARCHAR2(240), 
	"LEGISLATIVE_DATA_GROUP_NAME" VARCHAR2(240), 
	"LEGAL_EMPLOYER_NAME" VARCHAR2(240), 
	"PAYROLL_RELATIONSHIP_NUMBER" VARCHAR2(240), 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_W2_BAL_DTL_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_W2_BAL_DTL_STG_TBL"."STATUS" IS 'NEW > RETRY > TRANSFORMED > LOADED / FAILED';
COMMENT ON TABLE "DMT_W2_BAL_DTL_STG_TBL"  IS 'BalInitializationDetails staging. HDL business object: BalInitializationDetails.';
