-- DMT_RA_LINES_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_RA_LINES_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_RA_LINES_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"ORG_ID" VARCHAR2(240), 
	"BATCH_SOURCE_NAME" VARCHAR2(240), 
	"CUST_TRX_TYPE_NAME" VARCHAR2(240), 
	"TERM_NAME" VARCHAR2(240), 
	"TRX_DATE" DATE, 
	"GL_DATE" DATE, 
	"TRX_NUMBER" VARCHAR2(30), 
	"ORIG_SYSTEM_BILL_CUSTOMER_REF" VARCHAR2(240), 
	"ORIG_SYSTEM_BILL_ADDRESS_REF" VARCHAR2(240), 
	"ORIG_SYSTEM_BILL_CONTACT_REF" VARCHAR2(240), 
	"ORIG_SYS_SHIP_PARTY_REF" VARCHAR2(240), 
	"ORIG_SYS_SHIP_PARTY_SITE_REF" VARCHAR2(240), 
	"ORIG_SYS_SHIP_PTY_CONTACT_REF" VARCHAR2(240), 
	"ORIG_SYSTEM_SHIP_CUSTOMER_REF" VARCHAR2(240), 
	"ORIG_SYSTEM_SHIP_ADDRESS_REF" VARCHAR2(240), 
	"ORIG_SYSTEM_SHIP_CONTACT_REF" VARCHAR2(240), 
	"ORIG_SYS_SOLD_PARTY_REF" VARCHAR2(240), 
	"ORIG_SYSTEM_SOLD_CUSTOMER_REF" VARCHAR2(240), 
	"BILL_CUSTOMER_ACCOUNT_NUMBER" VARCHAR2(30), 
	"BILL_CUSTOMER_SITE_NUMBER" VARCHAR2(30), 
	"BILL_CONTACT_PARTY_NUMBER" VARCHAR2(30), 
	"SHIP_CUSTOMER_ACCOUNT_NUMBER" VARCHAR2(30), 
	"SHIP_CUSTOMER_SITE_NUMBER" VARCHAR2(30), 
	"SHIP_CONTACT_PARTY_NUMBER" VARCHAR2(30), 
	"SOLD_CUSTOMER_ACCOUNT_NUMBER" VARCHAR2(30), 
	"LINE_TYPE" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(240), 
	"CURRENCY_CODE" VARCHAR2(15), 
	"CONVERSION_TYPE" VARCHAR2(30), 
	"CONVERSION_DATE" DATE, 
	"CONVERSION_RATE" NUMBER, 
	"AMOUNT" NUMBER, 
	"QUANTITY" NUMBER, 
	"QUANTITY_ORDERED" NUMBER, 
	"UNIT_SELLING_PRICE" NUMBER, 
	"UNIT_STANDARD_PRICE" NUMBER, 
	"INTERFACE_LINE_CONTEXT" VARCHAR2(30), 
	"INTERFACE_LINE_ATTRIBUTE1" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE2" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE3" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE4" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE5" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE6" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE7" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE8" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE9" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE10" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE11" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE12" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE13" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE14" VARCHAR2(150), 
	"INTERFACE_LINE_ATTRIBUTE15" VARCHAR2(150), 
	"PRIMARY_SALESREP_NUMBER" VARCHAR2(30), 
	"TAX_CODE" VARCHAR2(50), 
	"LEGAL_ENTITY_IDENTIFIER" VARCHAR2(240), 
	"ACCTD_AMOUNT" NUMBER, 
	"SALES_ORDER" VARCHAR2(50), 
	"SALES_ORDER_DATE" DATE, 
	"SHIP_DATE_ACTUAL" DATE, 
	"WAREHOUSE_CODE" VARCHAR2(18), 
	"UOM_CODE" VARCHAR2(3), 
	"UOM_NAME" VARCHAR2(25), 
	"INVOICING_RULE_NAME" VARCHAR2(240), 
	"ACCOUNTING_RULE_NAME" VARCHAR2(240), 
	"ACCOUNTING_RULE_DURATION" VARCHAR2(240), 
	"RULE_START_DATE" DATE, 
	"RULE_END_DATE" DATE, 
	"REASON_CODE_MEANING" VARCHAR2(240), 
	"LAST_PERIOD_TO_CREDIT" NUMBER, 
	"TRX_BUSINESS_CATEGORY" VARCHAR2(240), 
	"PRODUCT_FISC_CLASSIFICATION" VARCHAR2(240), 
	"PRODUCT_CATEGORY" VARCHAR2(240), 
	"PRODUCT_TYPE" VARCHAR2(240), 
	"LINE_INTENDED_USE" VARCHAR2(240), 
	"ASSESSABLE_VALUE" NUMBER, 
	"DOCUMENT_SUB_TYPE" VARCHAR2(240), 
	"DEFAULT_TAXATION_COUNTRY" VARCHAR2(2), 
	"USER_DEFINED_FISC_CLASS" VARCHAR2(240), 
	"TAX_INVOICE_NUMBER" VARCHAR2(240), 
	"TAX_INVOICE_DATE" DATE, 
	"TAX_REGIME_CODE" VARCHAR2(30), 
	"TAX" VARCHAR2(50), 
	"TAX_STATUS_CODE" VARCHAR2(30), 
	"TAX_RATE_CODE" VARCHAR2(240), 
	"TAX_JURISDICTION_CODE" VARCHAR2(240), 
	"FIRST_PTY_REG_NUM" VARCHAR2(50), 
	"THIRD_PTY_REG_NUM" VARCHAR2(50), 
	"FINAL_DISCHARGE_LOCATION_CODE" VARCHAR2(240), 
	"TAXABLE_AMOUNT" NUMBER, 
	"TAXABLE_FLAG" VARCHAR2(1), 
	"TAX_EXEMPT_FLAG" VARCHAR2(1), 
	"TAX_EXEMPT_REASON_CODE" VARCHAR2(30), 
	"TAX_EXEMPT_REASON_CODE_MEANING" VARCHAR2(240), 
	"TAX_EXEMPT_NUMBER" VARCHAR2(80), 
	"AMOUNT_INCLUDES_TAX_FLAG" VARCHAR2(1), 
	"TAX_PRECEDENCE" NUMBER, 
	"CREDIT_METHOD_FOR_ACCT_RULE" VARCHAR2(240), 
	"CREDIT_METHOD_FOR_INSTALLMENTS" VARCHAR2(240), 
	"REASON_CODE" VARCHAR2(30), 
	"TAX_RATE" NUMBER, 
	"FOB_POINT" VARCHAR2(30), 
	"SHIP_VIA" VARCHAR2(240), 
	"WAYBILL_NUMBER" VARCHAR2(50), 
	"SALES_ORDER_LINE" VARCHAR2(30), 
	"SALES_ORDER_SOURCE" VARCHAR2(50), 
	"SALES_ORDER_REVISION" NUMBER, 
	"PURCHASE_ORDER" VARCHAR2(50), 
	"PURCHASE_ORDER_REVISION" VARCHAR2(240), 
	"PURCHASE_ORDER_DATE" DATE, 
	"AGREEMENT_NAME" VARCHAR2(240), 
	"MEMO_LINE_NAME" VARCHAR2(50), 
	"DOCUMENT_NUMBER" VARCHAR2(240), 
	"ORIG_SYSTEM_BATCH_NAME" VARCHAR2(50), 
	"LINK_TO_LINE_CONTEXT" VARCHAR2(30), 
	"LINK_TO_LINE_ATTRIBUTE1" VARCHAR2(150), 
	"LINK_TO_LINE_ATTRIBUTE2" VARCHAR2(150), 
	"LINK_TO_LINE_ATTRIBUTE3" VARCHAR2(150), 
	"LINK_TO_LINE_ATTRIBUTE4" VARCHAR2(150), 
	"LINK_TO_LINE_ATTRIBUTE5" VARCHAR2(150), 
	"LINK_TO_LINE_ATTRIBUTE6" VARCHAR2(150), 
	"RECEIPT_METHOD_NAME" VARCHAR2(240), 
	"PRINTING_OPTION" VARCHAR2(240), 
	"RELATED_BATCH_SOURCE_NAME" VARCHAR2(240), 
	"RELATED_TRX_NUMBER" VARCHAR2(30), 
	"TRANSLATED_DESCRIPTION" VARCHAR2(1000), 
	"CONS_BILLING_NUMBER" VARCHAR2(240), 
	"PROMISED_COMMITMENT_AMOUNT" NUMBER, 
	"PAYMENT_SET_ID" NUMBER, 
	"ORIGINAL_GL_DATE" DATE, 
	"INVOICED_LINE_ACCTG_LEVEL" VARCHAR2(15), 
	"OVERRIDE_AUTO_ACCOUNTING_FLAG" VARCHAR2(1), 
	"HISTORICAL_FLAG" VARCHAR2(1), 
	"DEFERRAL_EXCLUSION_FLAG" VARCHAR2(1), 
	"BILLING_DATE" DATE, 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"HEADER_ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"HEADER_ATTRIBUTE1" VARCHAR2(150), 
	"HEADER_ATTRIBUTE2" VARCHAR2(150), 
	"HEADER_ATTRIBUTE3" VARCHAR2(150), 
	"HEADER_ATTRIBUTE4" VARCHAR2(150), 
	"HEADER_ATTRIBUTE5" VARCHAR2(150), 
	"HEADER_ATTRIBUTE6" VARCHAR2(150), 
	"HEADER_ATTRIBUTE7" VARCHAR2(150), 
	"HEADER_ATTRIBUTE8" VARCHAR2(150), 
	"HEADER_ATTRIBUTE9" VARCHAR2(150), 
	"HEADER_ATTRIBUTE10" VARCHAR2(150), 
	"HEADER_ATTRIBUTE11" VARCHAR2(150), 
	"HEADER_ATTRIBUTE12" VARCHAR2(150), 
	"HEADER_ATTRIBUTE13" VARCHAR2(150), 
	"HEADER_ATTRIBUTE14" VARCHAR2(150), 
	"HEADER_ATTRIBUTE15" VARCHAR2(150), 
	"BU_NAME" VARCHAR2(240), 
	"COMMENTS" VARCHAR2(240), 
	"INTERNAL_NOTES" VARCHAR2(240), 
	"RESET_TRX_DATE_FLAG" VARCHAR2(1), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STG_STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_RA_LINES_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_RA_LINES_STG_TBL_N1" ON "DMT_RA_LINES_STG_TBL" ("STG_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_RA_LINES_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_RA_LINES_STG_SEQ';
COMMENT ON COLUMN "DMT_RA_LINES_STG_TBL"."TRX_NUMBER" IS 'Transaction number from source system â€” prefix applied in TFM table';
COMMENT ON COLUMN "DMT_RA_LINES_STG_TBL"."INTERFACE_LINE_CONTEXT" IS 'Flexfield context â€” combined with INTERFACE_LINE_ATTRIBUTE1-15 forms the unique line identifier';
COMMENT ON COLUMN "DMT_RA_LINES_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors â€” appended at each step, never overwritten. Prefixed: [PRE_VALIDATION] [TRANSFORM_ERROR] [FUSION_ERROR].';
COMMENT ON TABLE "DMT_RA_LINES_STG_TBL"  IS 'AR Invoice lines staging. Raw user data only. Run-specific data in DMT_RA_LINES_TFM_TBL. FBDI interface: RA_INTERFACE_LINES_ALL. CSV: RaInterfaceLinesAll.csv.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_RA_LINES_STG_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_RA_LINES_STG_TBL" RENAME COLUMN "STATUS" TO "STG_STATUS"';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_RA_LINES_STG_N1" ON "DMT_RA_LINES_STG_TBL" ("SCENARIO_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_RA_LINES_STG_TBL"."STG_STATUS" IS 'Staging lifecycle: NEW > TRANSFORMED / FAILED. Forward-only, never reset; errors accumulate in ERROR_TEXT.';
