-- DMT_AP_INVOICE_LINES_INT_TFM_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_AP_INVOICE_LINES_INT_TFM_TBL" 
   (	"TFM_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_AP_INVOICE_LINES_INT_TFM_SEQ.NEXTVAL NOT NULL ENABLE, 
	"STG_SEQUENCE_ID" NUMBER NOT NULL ENABLE, 
	"FBDI_CSV_ID" NUMBER, 
	"INVOICE_ID" NUMBER, 
	"LINE_NUMBER" NUMBER, 
	"LINE_TYPE_LOOKUP_CODE" VARCHAR2(25), 
	"AMOUNT" NUMBER, 
	"QUANTITY_INVOICED" NUMBER, 
	"UNIT_PRICE" NUMBER, 
	"UNIT_OF_MEAS_LOOKUP_CODE" VARCHAR2(25), 
	"DESCRIPTION" VARCHAR2(240), 
	"PO_NUMBER" VARCHAR2(20), 
	"PO_LINE_NUMBER" NUMBER, 
	"PO_SHIPMENT_NUM" NUMBER, 
	"PO_DISTRIBUTION_NUM" NUMBER, 
	"ITEM_DESCRIPTION" VARCHAR2(240), 
	"RELEASE_NUM" NUMBER, 
	"PURCHASING_CATEGORY" VARCHAR2(250), 
	"RECEIPT_NUMBER" VARCHAR2(30), 
	"RECEIPT_LINE_NUMBER" NUMBER, 
	"CONSUMPTION_ADVICE_NUMBER" VARCHAR2(20), 
	"CONSUMPTION_ADVICE_LINE_NUMBER" NUMBER, 
	"PACKING_SLIP" VARCHAR2(25), 
	"FINAL_MATCH_FLAG" VARCHAR2(1), 
	"DIST_CODE_CONCATENATED" VARCHAR2(250), 
	"DISTRIBUTION_SET_NAME" VARCHAR2(50), 
	"ACCOUNTING_DATE" DATE, 
	"ACCOUNT_SEGMENT" VARCHAR2(25), 
	"BALANCING_SEGMENT" VARCHAR2(25), 
	"COST_CENTER_SEGMENT" VARCHAR2(25), 
	"TAX_CLASSIFICATION_CODE" VARCHAR2(30), 
	"SHIP_TO_LOCATION_CODE" VARCHAR2(60), 
	"SHIP_FROM_LOCATION_CODE" VARCHAR2(60), 
	"FINAL_DISCHARGE_LOCATION_CODE" VARCHAR2(60), 
	"TRX_BUSINESS_CATEGORY" VARCHAR2(240), 
	"PRODUCT_FISC_CLASSIFICATION" VARCHAR2(240), 
	"PRIMARY_INTENDED_USE" VARCHAR2(240), 
	"USER_DEFINED_FISC_CLASS" VARCHAR2(240), 
	"PRODUCT_TYPE" VARCHAR2(240), 
	"ASSESSABLE_VALUE" NUMBER, 
	"PRODUCT_CATEGORY" VARCHAR2(240), 
	"CONTROL_AMOUNT" NUMBER, 
	"TAX_REGIME_CODE" VARCHAR2(30), 
	"TAX" VARCHAR2(30), 
	"TAX_STATUS_CODE" VARCHAR2(30), 
	"TAX_JURISDICTION_CODE" VARCHAR2(30), 
	"TAX_RATE_CODE" VARCHAR2(30), 
	"TAX_RATE" NUMBER, 
	"AWT_GROUP_NAME" VARCHAR2(80), 
	"TYPE_1099" VARCHAR2(10), 
	"INCOME_TAX_REGION" VARCHAR2(10), 
	"PRORATE_ACROSS_FLAG" VARCHAR2(1), 
	"LINE_GROUP_NUMBER" NUMBER, 
	"COST_FACTOR_NAME" VARCHAR2(80), 
	"STAT_AMOUNT" NUMBER, 
	"ASSETS_TRACKING_FLAG" VARCHAR2(1), 
	"ASSET_BOOK_TYPE_CODE" VARCHAR2(15), 
	"ASSET_CATEGORY_ID" NUMBER, 
	"SERIAL_NUMBER" VARCHAR2(35), 
	"MANUFACTURER" VARCHAR2(30), 
	"MODEL_NUMBER" VARCHAR2(40), 
	"WARRANTY_NUMBER" VARCHAR2(15), 
	"PRICE_CORRECTION_FLAG" VARCHAR2(1), 
	"PRICE_CORRECT_INV_NUM" VARCHAR2(50), 
	"PRICE_CORRECT_INV_LINE_NUM" NUMBER, 
	"REQUESTER_FIRST_NAME" VARCHAR2(150), 
	"REQUESTER_LAST_NAME" VARCHAR2(150), 
	"REQUESTER_EMPLOYEE_NUM" VARCHAR2(30), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE_NUMBER1" NUMBER, 
	"ATTRIBUTE_NUMBER2" NUMBER, 
	"ATTRIBUTE_NUMBER3" NUMBER, 
	"ATTRIBUTE_NUMBER4" NUMBER, 
	"ATTRIBUTE_NUMBER5" NUMBER, 
	"ATTRIBUTE_DATE1" DATE, 
	"ATTRIBUTE_DATE2" DATE, 
	"ATTRIBUTE_DATE3" DATE, 
	"ATTRIBUTE_DATE4" DATE, 
	"ATTRIBUTE_DATE5" DATE, 
	"GLOBAL_ATTRIBUTE_CATEGORY" VARCHAR2(30), 
	"GLOBAL_ATTRIBUTE1" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE2" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE3" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE4" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE5" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE6" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE7" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE8" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE9" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE10" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE11" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE12" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE13" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE14" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE15" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE16" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE17" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE18" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE19" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE20" VARCHAR2(150), 
	"GLOBAL_ATTRIBUTE_NUMBER1" NUMBER, 
	"GLOBAL_ATTRIBUTE_NUMBER2" NUMBER, 
	"GLOBAL_ATTRIBUTE_NUMBER3" NUMBER, 
	"GLOBAL_ATTRIBUTE_NUMBER4" NUMBER, 
	"GLOBAL_ATTRIBUTE_NUMBER5" NUMBER, 
	"GLOBAL_ATTRIBUTE_DATE1" DATE, 
	"GLOBAL_ATTRIBUTE_DATE2" DATE, 
	"GLOBAL_ATTRIBUTE_DATE3" DATE, 
	"GLOBAL_ATTRIBUTE_DATE4" DATE, 
	"GLOBAL_ATTRIBUTE_DATE5" DATE, 
	"PJC_PROJECT_ID" NUMBER, 
	"PJC_TASK_ID" NUMBER, 
	"PJC_EXPENDITURE_TYPE_ID" NUMBER, 
	"PJC_EXPENDITURE_ITEM_DATE" DATE, 
	"PJC_ORGANIZATION_ID" NUMBER, 
	"PJC_PROJECT_NUMBER" VARCHAR2(25), 
	"PJC_TASK_NUMBER" VARCHAR2(100), 
	"PJC_EXPENDITURE_TYPE_NAME" VARCHAR2(240), 
	"PJC_ORGANIZATION_NAME" VARCHAR2(240), 
	"PJC_RESERVED_ATTRIBUTE1" VARCHAR2(150), 
	"PJC_RESERVED_ATTRIBUTE2" VARCHAR2(150), 
	"PJC_RESERVED_ATTRIBUTE3" VARCHAR2(150), 
	"PJC_RESERVED_ATTRIBUTE4" VARCHAR2(150), 
	"PJC_RESERVED_ATTRIBUTE5" VARCHAR2(150), 
	"PJC_RESERVED_ATTRIBUTE6" VARCHAR2(150), 
	"PJC_RESERVED_ATTRIBUTE7" VARCHAR2(150), 
	"PJC_RESERVED_ATTRIBUTE8" VARCHAR2(150), 
	"PJC_RESERVED_ATTRIBUTE9" VARCHAR2(150), 
	"PJC_RESERVED_ATTRIBUTE10" VARCHAR2(150), 
	"PJC_USER_DEF_ATTRIBUTE1" VARCHAR2(150), 
	"PJC_USER_DEF_ATTRIBUTE2" VARCHAR2(150), 
	"PJC_USER_DEF_ATTRIBUTE3" VARCHAR2(150), 
	"PJC_USER_DEF_ATTRIBUTE4" VARCHAR2(150), 
	"PJC_USER_DEF_ATTRIBUTE5" VARCHAR2(150), 
	"PJC_USER_DEF_ATTRIBUTE6" VARCHAR2(150), 
	"PJC_USER_DEF_ATTRIBUTE7" VARCHAR2(150), 
	"PJC_USER_DEF_ATTRIBUTE8" VARCHAR2(150), 
	"PJC_USER_DEF_ATTRIBUTE9" VARCHAR2(150), 
	"PJC_USER_DEF_ATTRIBUTE10" VARCHAR2(150), 
	"FISCAL_CHARGE_TYPE" VARCHAR2(30), 
	"DEF_ACCTG_START_DATE" DATE, 
	"DEF_ACCTG_END_DATE" DATE, 
	"DEF_ACCRUAL_CODE_CONCATENATED" VARCHAR2(250), 
	"PJC_PROJECT_NAME" VARCHAR2(240), 
	"PJC_TASK_NAME" VARCHAR2(240), 
	"PJC_WORK_TYPE" VARCHAR2(240), 
	"PJC_CONTRACT_NAME" VARCHAR2(240), 
	"PJC_CONTRACT_NUMBER" VARCHAR2(120), 
	"PJC_FUNDING_SOURCE_NAME" VARCHAR2(240), 
	"PJC_FUNDING_SOURCE_NUMBER" VARCHAR2(50), 
	"REQUESTER_EMAIL_ADDRESS" VARCHAR2(240), 
	"RCV_TRANSACTION_ID" NUMBER, 
	"FUSION_INVOICE_LINE_NUMBER" NUMBER, 
	"RESULTS_UPDATED_DATE" DATE, 
	"TFM_STATUS" VARCHAR2(30) DEFAULT ''STAGED'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"RUN_ID" NUMBER, 
	"RECON_KEY" VARCHAR2(1000), 
	"WORK_QUEUE_ID" NUMBER, 
	 CONSTRAINT "DMT_AP_INV_LINES_INT_TFM_PK" PRIMARY KEY ("TFM_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- 2026-07-08 conformance tranche: rename must precede the index DDL below
-- (a pre-existing database still has the old column when the index runs).
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_AP_INVOICE_LINES_INT_TFM_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_AP_INVOICE_LINES_INT_TFM_TBL" RENAME COLUMN "STATUS" TO "TFM_STATUS"';
  end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_AP_INV_LN_TFM_N1" ON "DMT_AP_INVOICE_LINES_INT_TFM_TBL" ("STG_SEQUENCE_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

begin
  execute immediate 'CREATE INDEX "DMT_AP_INV_LN_TFM_N4" ON "DMT_AP_INVOICE_LINES_INT_TFM_TBL" ("FBDI_CSV_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_AP_INVOICE_LINES_INT_TFM_TBL"."TFM_SEQUENCE_ID" IS 'PK - from DMT_AP_INVOICE_LINES_INT_TFM_SEQ';
COMMENT ON COLUMN "DMT_AP_INVOICE_LINES_INT_TFM_TBL"."FUSION_INVOICE_LINE_NUMBER" IS 'Fusion invoice line number â€” populated by BIP reconciliation';
COMMENT ON TABLE "DMT_AP_INVOICE_LINES_INT_TFM_TBL"  IS 'AP Invoice lines transformed. Run-specific â€” one row per staging row per run attempt. Reconciliation populated by BIP.';

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_AP_INVOICE_LINES_INT_TFM_TBL' and column_name = 'RECON_KEY';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_AP_INVOICE_LINES_INT_TFM_TBL" ADD ("RECON_KEY" VARCHAR2(1000))';
  end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_AP_INVOICE_LINES_INT_TFM_N1" ON "DMT_AP_INVOICE_LINES_INT_TFM_TBL" ("RUN_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_AP_INVOICE_LINES_INT_TFM_N2" ON "DMT_AP_INVOICE_LINES_INT_TFM_TBL" ("RUN_ID", "TFM_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_AP_INVOICE_LINES_INT_TFM_N3" ON "DMT_AP_INVOICE_LINES_INT_TFM_TBL" ("RECON_KEY")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_AP_INVOICE_LINES_INT_TFM_TBL"."TFM_STATUS" IS 'Transform lifecycle: STAGED > GENERATED > LOADED / FAILED.';
COMMENT ON COLUMN "DMT_AP_INVOICE_LINES_INT_TFM_TBL"."RECON_KEY" IS 'Pre-concatenated business key (run prefix included) that BIP reconciliation matches against Fusion rows.';

-- WORK_QUEUE_ID (work-queue-ID granularity foundation, accepted 2026-07-20;
-- docs/FIX_PLAN.md item 1). Guarded in-file ALTER so an existing DB converges
-- via db/install.sql (the CREATE above carries it for fresh installs). FK is
-- in db/tables/_foreign_keys.sql. NULLABLE for now; NOT NULL deferred.
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where table_name = 'DMT_AP_INVOICE_LINES_INT_TFM_TBL' and column_name = 'WORK_QUEUE_ID';
  if l_n = 0 then
    execute immediate 'ALTER TABLE "DMT_AP_INVOICE_LINES_INT_TFM_TBL" ADD ("WORK_QUEUE_ID" NUMBER)';
  end if;
end;
/
COMMENT ON COLUMN "DMT_AP_INVOICE_LINES_INT_TFM_TBL"."WORK_QUEUE_ID" IS 'The work queue item (DMT_WORK_QUEUE_TBL.QUEUE_ID) that processed this record. FK in _foreign_keys.sql. Stamped at generation; unit of per-work-item processing (design section 7, accepted 2026-07-20).';
