-- DMT_WORKER_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_WORKER_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_WORKER_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" VARCHAR2(240), 
	"EFFECTIVE_END_DATE" VARCHAR2(240), 
	"PERSON_NUMBER" VARCHAR2(240), 
	"DATE_OF_BIRTH" VARCHAR2(240), 
	"ACTION_CODE" VARCHAR2(240), 
	"START_DATE" VARCHAR2(240), 
	"LEGAL_ENTITY_NAME" VARCHAR2(240), 
	"CATEGORY_CODE" VARCHAR2(240), 
	"PROJECTED_TERMINATION_DATE" VARCHAR2(240), 
	"BLOOD_TYPE" VARCHAR2(240), 
	"CORRESPONDENCE_LANGUAGE" VARCHAR2(240), 
	"TOWN_OF_BIRTH" VARCHAR2(240), 
	"REGION_OF_BIRTH" VARCHAR2(240), 
	"COUNTRY_OF_BIRTH" VARCHAR2(240), 
	"DATE_OF_DEATH" VARCHAR2(240), 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_WORKER_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_WORKER_STG_TBL"."STG_SEQUENCE_ID" IS 'PK - from DMT_WORKER_STG_SEQ. Populated by DB default, never supplied by user.';
COMMENT ON COLUMN "DMT_WORKER_STG_TBL"."PERSON_NUMBER" IS 'Worker person number â€” unique identifier in Fusion HCM';
COMMENT ON COLUMN "DMT_WORKER_STG_TBL"."ACTION_CODE" IS 'HIRE or ADD_CWK';
COMMENT ON COLUMN "DMT_WORKER_STG_TBL"."CATEGORY_CODE" IS 'Employment category: FR (full-time regular), PT (part-time), etc.';
COMMENT ON COLUMN "DMT_WORKER_STG_TBL"."SOURCE_ID" IS 'Natural key from source system';
COMMENT ON COLUMN "DMT_WORKER_STG_TBL"."STATUS" IS 'NEW > RETRY > TRANSFORMED > LOADED / FAILED';
COMMENT ON COLUMN "DMT_WORKER_STG_TBL"."ERROR_TEXT" IS 'Concatenated errors. Appended at each step - never overwritten.';
COMMENT ON TABLE "DMT_WORKER_STG_TBL"  IS 'Worker staging. Raw user-loaded data only. Run-specific data in DMT_WORKER_TFM_TBL. HDL business object: Worker.';
