-- DMT_GL_INTERFACE_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_GL_INTERFACE_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_GL_INTERFACE_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"JOURNAL_STATUS" VARCHAR2(50), 
	"LEDGER_NAME" VARCHAR2(240), 
	"ACCOUNTING_DATE" DATE, 
	"CURRENCY_CODE" VARCHAR2(15), 
	"DATE_CREATED" DATE, 
	"CREATED_BY" VARCHAR2(100), 
	"ACTUAL_FLAG" VARCHAR2(1), 
	"USER_JE_CATEGORY_NAME" VARCHAR2(25), 
	"USER_JE_SOURCE_NAME" VARCHAR2(25), 
	"CURRENCY_CONVERSION_DATE" DATE, 
	"USER_CURRENCY_CONVERSION_TYPE" VARCHAR2(30), 
	"CURRENCY_CONVERSION_RATE" NUMBER, 
	"SEGMENT1" VARCHAR2(25), 
	"SEGMENT2" VARCHAR2(25), 
	"SEGMENT3" VARCHAR2(25), 
	"SEGMENT4" VARCHAR2(25), 
	"SEGMENT5" VARCHAR2(25), 
	"SEGMENT6" VARCHAR2(25), 
	"SEGMENT7" VARCHAR2(25), 
	"SEGMENT8" VARCHAR2(25), 
	"SEGMENT9" VARCHAR2(25), 
	"SEGMENT10" VARCHAR2(25), 
	"SEGMENT11" VARCHAR2(25), 
	"SEGMENT12" VARCHAR2(25), 
	"SEGMENT13" VARCHAR2(25), 
	"SEGMENT14" VARCHAR2(25), 
	"SEGMENT15" VARCHAR2(25), 
	"SEGMENT16" VARCHAR2(25), 
	"SEGMENT17" VARCHAR2(25), 
	"SEGMENT18" VARCHAR2(25), 
	"SEGMENT19" VARCHAR2(25), 
	"SEGMENT20" VARCHAR2(25), 
	"SEGMENT21" VARCHAR2(25), 
	"SEGMENT22" VARCHAR2(25), 
	"SEGMENT23" VARCHAR2(25), 
	"SEGMENT24" VARCHAR2(25), 
	"SEGMENT25" VARCHAR2(25), 
	"SEGMENT26" VARCHAR2(25), 
	"SEGMENT27" VARCHAR2(25), 
	"SEGMENT28" VARCHAR2(25), 
	"SEGMENT29" VARCHAR2(25), 
	"SEGMENT30" VARCHAR2(25), 
	"ENTERED_DR" NUMBER, 
	"ENTERED_CR" NUMBER, 
	"ACCOUNTED_DR" NUMBER, 
	"ACCOUNTED_CR" NUMBER, 
	"REFERENCE1" VARCHAR2(100), 
	"REFERENCE2" VARCHAR2(240), 
	"REFERENCE4" VARCHAR2(100), 
	"REFERENCE5" VARCHAR2(240), 
	"REFERENCE6" VARCHAR2(100), 
	"REFERENCE7" VARCHAR2(100), 
	"REFERENCE8" VARCHAR2(100), 
	"REFERENCE10" VARCHAR2(240), 
	"STAT_AMOUNT" NUMBER, 
	"GROUP_ID" NUMBER, 
	"PERIOD_NAME" VARCHAR2(15), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150), 
	"ATTRIBUTE1" VARCHAR2(150), 
	"ATTRIBUTE2" VARCHAR2(150), 
	"ATTRIBUTE3" VARCHAR2(150), 
	"ATTRIBUTE4" VARCHAR2(150), 
	"ATTRIBUTE5" VARCHAR2(150), 
	"ATTRIBUTE6" VARCHAR2(150), 
	"ATTRIBUTE7" VARCHAR2(150), 
	"ATTRIBUTE8" VARCHAR2(150), 
	"ATTRIBUTE9" VARCHAR2(150), 
	"ATTRIBUTE10" VARCHAR2(150), 
	"ATTRIBUTE11" VARCHAR2(150), 
	"ATTRIBUTE12" VARCHAR2(150), 
	"ATTRIBUTE13" VARCHAR2(150), 
	"ATTRIBUTE14" VARCHAR2(150), 
	"ATTRIBUTE15" VARCHAR2(150), 
	"ATTRIBUTE16" VARCHAR2(150), 
	"ATTRIBUTE17" VARCHAR2(150), 
	"ATTRIBUTE18" VARCHAR2(150), 
	"ATTRIBUTE19" VARCHAR2(150), 
	"ATTRIBUTE20" VARCHAR2(150), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STG_STATUS" VARCHAR2(30) DEFAULT ''NEW'' NOT NULL ENABLE, 
	"ERROR_TEXT" CLOB, 
	"SOURCE_ID" VARCHAR2(240), 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	"LEDGER_ID" VARCHAR2(100), 
	"REFERENCE3" VARCHAR2(240), 
	"REFERENCE9" VARCHAR2(240), 
	"REFERENCE21" VARCHAR2(240), 
	"REFERENCE22" VARCHAR2(240), 
	"REFERENCE23" VARCHAR2(240), 
	"REFERENCE24" VARCHAR2(240), 
	"REFERENCE25" VARCHAR2(240), 
	"REFERENCE26" VARCHAR2(240), 
	"REFERENCE27" VARCHAR2(240), 
	"REFERENCE28" VARCHAR2(240), 
	"REFERENCE29" VARCHAR2(240), 
	"REFERENCE30" VARCHAR2(240), 
	"CONTEXT2" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY3" VARCHAR2(150), 
	"CONTEXT3" VARCHAR2(150), 
	"ENCUMBRANCE_TYPE_ID" VARCHAR2(100), 
	"JGZZ_RECON_REF" VARCHAR2(240), 
	"JE_LINE_NUM" VARCHAR2(100), 
	"CHART_OF_ACCOUNTS_ID" VARCHAR2(100), 
	"FUNCTIONAL_CURRENCY_CODE" VARCHAR2(15), 
	"CODE_COMBINATION_ID" VARCHAR2(100), 
	"DATE_CREATED_IN_GL" VARCHAR2(100), 
	"WARNING_CODE" VARCHAR2(4), 
	"STATUS_DESCRIPTION" VARCHAR2(240), 
	"AVERAGE_JOURNAL_FLAG" VARCHAR2(1), 
	"ORIGINATING_BAL_SEG_VALUE" VARCHAR2(25), 
	"GL_SL_LINK_ID" VARCHAR2(100), 
	"GL_SL_LINK_TABLE" VARCHAR2(30), 
	"REFERENCE_DATE" VARCHAR2(100), 
	"USSGL_TRANSACTION_CODE" VARCHAR2(30), 
	"TRANSACTION_DATE" VARCHAR2(100), 
	"BALANCING_SEGMENT_VALUE" VARCHAR2(25), 
	"MANAGEMENT_SEGMENT_VALUE" VARCHAR2(25), 
	"INTERCOMPANY_SEGMENT_VALUE" VARCHAR2(25), 
	"INTERCOMPANY_MODE" VARCHAR2(1), 
	"CONTEXT4" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY5" VARCHAR2(150), 
	"CONTEXT5" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY6" VARCHAR2(150), 
	"CONTEXT6" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY7" VARCHAR2(150), 
	"CONTEXT7" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY8" VARCHAR2(150), 
	"CONTEXT8" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY9" VARCHAR2(150), 
	"CONTEXT9" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY10" VARCHAR2(150), 
	"CONTEXT10" VARCHAR2(150), 
	"GL_SL_LINK_KEY" VARCHAR2(100), 
	"SUBLEDGER_DOC_SEQUENCE_ID" VARCHAR2(100), 
	"SUBLEDGER_DOC_SEQUENCE_VALUE" VARCHAR2(240), 
	"REFERENCE_FLEX_NUM" VARCHAR2(100), 
	"REFERENCE11" VARCHAR2(240), 
	"REFERENCE12" VARCHAR2(240), 
	"REFERENCE13" VARCHAR2(240), 
	"REFERENCE14" VARCHAR2(240), 
	"REFERENCE15" VARCHAR2(240), 
	"REFERENCE16" VARCHAR2(240), 
	"REFERENCE17" VARCHAR2(240), 
	"REFERENCE18" VARCHAR2(240), 
	"REFERENCE19" VARCHAR2(240), 
	"REFERENCE20" VARCHAR2(240), 
	"CLEARING_COMPANY" VARCHAR2(240), 
	"CLEARING_DOMAIN" VARCHAR2(240), 
	"CLEARING_INTERCOMPANY" VARCHAR2(240), 
	"INVOICE_DATE" VARCHAR2(100), 
	"INVOICE_IDENTIFIER" VARCHAR2(50), 
	"INVOICE_AMOUNT" VARCHAR2(100), 
	"TAX_CODE" VARCHAR2(50), 
	"FUNDS_CHECK_INDICATOR" VARCHAR2(1), 
	"BUDGET_VERSION_ID" VARCHAR2(100), 
	 CONSTRAINT "DMT_GL_INTERFACE_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

-- 2026-07-08 conformance tranche: rename must precede the index DDL below
-- (a pre-existing database still has the old column when the index runs).
declare
  l_n pls_integer;
begin
  select count(*) into l_n from user_tab_columns
  where  table_name = 'DMT_GL_INTERFACE_STG_TBL' and column_name = 'STATUS';
  if l_n = 1 then
    execute immediate 'ALTER TABLE "DMT_GL_INTERFACE_STG_TBL" RENAME COLUMN "STATUS" TO "STG_STATUS"';
  end if;
end;
/

-- ---------------------------------------------------------------------------
-- 2026-07-08 conformance tranche (design section 7: STG/TFM infra-column
-- dictionary + contract-index dictionary): converges a pre-existing database.
-- Fresh installs already get the final shape from the CREATE above.
-- ---------------------------------------------------------------------------
begin
  execute immediate 'CREATE INDEX "DMT_GL_INTERFACE_STG_N1" ON "DMT_GL_INTERFACE_STG_TBL" ("STG_STATUS")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/
begin
  execute immediate 'CREATE INDEX "DMT_GL_INTERFACE_STG_N2" ON "DMT_GL_INTERFACE_STG_TBL" ("SCENARIO_ID")';
exception when others then
  if sqlcode not in (-955,-1408) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_GL_INTERFACE_STG_TBL"."STG_STATUS" IS 'Staging lifecycle: NEW > TRANSFORMED / FAILED. Forward-only, never reset; errors accumulate in ERROR_TEXT.';

-- ---------------------------------------------------------------------------
-- 2026-07-09 conformance review F2 (STG/TFM infra-column dictionary, design
-- section 7 accepted 2026-07-08): STG_STATUS is VARCHAR2(30) DEFAULT 'NEW'
-- NOT NULL. Backfills any NULL statuses to the default, then converges a
-- pre-existing database; fresh installs get the shape from the CREATE above.
-- ---------------------------------------------------------------------------
declare
  l_nullable varchar2(1);
begin
  select nullable into l_nullable from user_tab_columns
   where table_name = 'DMT_GL_INTERFACE_STG_TBL' and column_name = 'STG_STATUS';
  if l_nullable = 'Y' then
    execute immediate 'UPDATE "DMT_GL_INTERFACE_STG_TBL" SET "STG_STATUS" = ''NEW'' WHERE "STG_STATUS" IS NULL';
    execute immediate 'ALTER TABLE "DMT_GL_INTERFACE_STG_TBL" MODIFY ("STG_STATUS" DEFAULT ''NEW'' NOT NULL)';
  end if;
end;
/
