-- DMT_SAL_BASIS_STG_TBL (generated from ATP 2026-07-03)

begin
  execute immediate 'CREATE TABLE "DMT_SAL_BASIS_STG_TBL" 
   (	"STG_SEQUENCE_ID" NUMBER DEFAULT DMT_OWNER.DMT_SAL_BASIS_STG_SEQ.NEXTVAL NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" VARCHAR2(240), 
	"EFFECTIVE_END_DATE" VARCHAR2(240), 
	"SALARY_BASIS_NAME" VARCHAR2(240), 
	"ELEMENT_NAME" VARCHAR2(240), 
	"INPUT_VALUE_NAME" VARCHAR2(240), 
	"SALARY_BASIS_CODE" VARCHAR2(240), 
	"ANNUALIZATION_FACTOR" VARCHAR2(240), 
	"GRADE_RATE_TYPE" VARCHAR2(240), 
	"LEGISLATIVE_DATA_GROUP_NAME" VARCHAR2(240), 
	"DESCRIPTION" VARCHAR2(240), 
	"SOURCE_ID" VARCHAR2(200), 
	"STAGE_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(30) DEFAULT ''NEW'', 
	"ERROR_TEXT" CLOB, 
	"LAST_UPDATED_DATE" DATE, 
	"SCENARIO_ID" NUMBER, 
	 CONSTRAINT "DMT_SAL_BASIS_STG_PK" PRIMARY KEY ("STG_SEQUENCE_ID")
  USING INDEX  ENABLE
   ) ';
exception when others then
  if sqlcode not in (-955) then raise; end if;
end;
/

COMMENT ON COLUMN "DMT_SAL_BASIS_STG_TBL"."STATUS" IS 'NEW > RETRY > TRANSFORMED > LOADED / FAILED';
COMMENT ON TABLE "DMT_SAL_BASIS_STG_TBL"  IS 'SalaryBasis staging. HDL business object: SalaryBasis.';
