prompt --application/pages/page_00007
begin
--   Manifest
--     PAGE: 00007
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2026.03.30'
,p_release=>'26.1.4'
,p_default_workspace_id=>32599344892582845
,p_default_application_id=>500
,p_default_id_offset=>32805213799451421
,p_default_owner=>'DMT2_OWNER'
);
wwv_flow_imp_page.create_page(
 p_id=>7
,p_name=>'HCM Employment'
,p_alias=>'TIMELABOR'
,p_step_title=>'HCM Employment'
,p_autocomplete_on_off=>'OFF'
,p_step_template=>4072355960268175073
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(1453389736507988409)
,p_plug_name=>'Absence Balances'
,p_static_id=>'absence-balances'
,p_region_template_options=>'#DEFAULT#:is-collapsed:t-Region--scrollBody'
,p_plug_template=>2664334895415463485
,p_plug_display_sequence=>40
,p_plug_item_display_point=>'ABOVE'
,p_query_type=>'SQL'
,p_plug_source=>'SELECT * FROM DMT_V_ABSENCE_DETAIL WHERE (:P0_SCENARIO_ID IS NULL OR SCENARIO_ID = :P0_SCENARIO_ID)'
,p_plug_source_type=>'NATIVE_IR'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>11
,p_prn_height=>8.5
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
,p_ai_enabled=>false
,p_plug_comment=>'Absence Balances'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(1453389786219988410)
,p_max_row_count=>'1000000'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_internal_uid=>38603810959212337
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415747307359720706)
,p_db_column_name=>'ABSENCE_CATEGORY'
,p_display_order=>90
,p_column_identifier=>'J'
,p_column_label=>'Absence Category'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415747274110720705)
,p_db_column_name=>'ABSENCE_NAME'
,p_display_order=>80
,p_column_identifier=>'I'
,p_column_label=>'Absence Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415748243046720715)
,p_db_column_name=>'ABSENCE_REASON'
,p_display_order=>180
,p_column_identifier=>'S'
,p_column_label=>'Absence Reason'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415747444338720707)
,p_db_column_name=>'ABSENCE_STATUS'
,p_display_order=>100
,p_column_identifier=>'K'
,p_column_label=>'Absence Status'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415746828980720701)
,p_db_column_name=>'ABSENCE_TYPE'
,p_display_order=>40
,p_column_identifier=>'E'
,p_column_label=>'Absence Type'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415747897357720712)
,p_db_column_name=>'APPROVAL_STATUS_CODE'
,p_display_order=>150
,p_column_identifier=>'P'
,p_column_label=>'Approval Status Code'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415748292404720716)
,p_db_column_name=>'COMMENTS'
,p_display_order=>190
,p_column_identifier=>'T'
,p_column_label=>'Comments'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415747997844720713)
,p_db_column_name=>'DURATION'
,p_display_order=>160
,p_column_identifier=>'Q'
,p_column_label=>'Duration'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415747073040720703)
,p_db_column_name=>'EFFECTIVE_END_DATE'
,p_display_order=>60
,p_column_identifier=>'G'
,p_column_label=>'Effective End Date'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415746959758720702)
,p_db_column_name=>'EFFECTIVE_START_DATE'
,p_display_order=>50
,p_column_identifier=>'F'
,p_column_label=>'Effective Start Date'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415747178829720704)
,p_db_column_name=>'EMPLOYER_NAME'
,p_display_order=>70
,p_column_identifier=>'H'
,p_column_label=>'Employer Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415747618061720709)
,p_db_column_name=>'END_DATE'
,p_display_order=>120
,p_column_identifier=>'M'
,p_column_label=>'End Date'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415747835425720711)
,p_db_column_name=>'END_TIME'
,p_display_order=>140
,p_column_identifier=>'O'
,p_column_label=>'End Time'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415746629204720699)
,p_db_column_name=>'ERROR_TEXT'
,p_display_order=>20
,p_column_identifier=>'C'
,p_column_label=>'Error Text'
,p_allow_sorting=>'N'
,p_allow_ctrl_breaks=>'N'
,p_allow_aggregations=>'N'
,p_allow_computations=>'N'
,p_allow_charting=>'N'
,p_allow_group_by=>'N'
,p_allow_pivot=>'N'
,p_column_type=>'CLOB'
,p_heading_alignment=>'LEFT'
,p_rpt_show_filter_lov=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415749028737720723)
,p_db_column_name=>'LAST_UPDATED_DATE'
,p_display_order=>260
,p_column_identifier=>'AA'
,p_column_label=>'Last Updated Date'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415746691161720700)
,p_db_column_name=>'PERSON_NUMBER'
,p_display_order=>30
,p_column_identifier=>'D'
,p_column_label=>'Person Number'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415748690465720720)
,p_db_column_name=>'PREFIX'
,p_display_order=>230
,p_column_identifier=>'X'
,p_column_label=>'Prefix'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415748669066720719)
,p_db_column_name=>'RUN_ID'
,p_display_order=>220
,p_column_identifier=>'W'
,p_column_label=>'Run Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415746508983720698)
,p_db_column_name=>'RUN_STATUS'
,p_display_order=>10
,p_column_identifier=>'B'
,p_column_label=>'Run Status'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415748797014720721)
,p_db_column_name=>'SCENARIO_ID'
,p_display_order=>240
,p_column_identifier=>'Y'
,p_column_label=>'Scenario Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415748437708720717)
,p_db_column_name=>'SOURCE_ID'
,p_display_order=>200
,p_column_identifier=>'U'
,p_column_label=>'Source Id'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415748914513720722)
,p_db_column_name=>'STAGE_DATE'
,p_display_order=>250
,p_column_identifier=>'Z'
,p_column_label=>'Stage Date'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415747522605720708)
,p_db_column_name=>'START_DATE'
,p_display_order=>110
,p_column_identifier=>'L'
,p_column_label=>'Start Date'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415747777872720710)
,p_db_column_name=>'START_TIME'
,p_display_order=>130
,p_column_identifier=>'N'
,p_column_label=>'Start Time'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415748517356720718)
,p_db_column_name=>'STG_SEQUENCE_ID'
,p_display_order=>210
,p_column_identifier=>'V'
,p_column_label=>'Stg Sequence Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415748172575720714)
,p_db_column_name=>'SUBMISSION_DATE'
,p_display_order=>170
,p_column_identifier=>'R'
,p_column_label=>'Submission Date'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(1338830720476302213)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'475672'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'RUN_STATUS:ERROR_TEXT:PERSON_NUMBER:ABSENCE_TYPE:EFFECTIVE_START_DATE:EFFECTIVE_END_DATE:EMPLOYER_NAME:ABSENCE_NAME:ABSENCE_CATEGORY:ABSENCE_STATUS:START_DATE:END_DATE:START_TIME:END_TIME:APPROVAL_STATUS_CODE:DURATION:SUBMISSION_DATE:ABSENCE_REASON:C'
||'OMMENTS:SOURCE_ID:STG_SEQUENCE_ID:INTEGRATION_ID:PREFIX:SCENARIO_ID:STAGE_DATE:LAST_UPDATED_DATE'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(1580421601240419552)
,p_plug_name=>'Assignments'
,p_static_id=>'assignments'
,p_region_template_options=>'#DEFAULT#:is-collapsed:t-Region--scrollBody'
,p_plug_template=>2664334895415463485
,p_plug_display_sequence=>10
,p_plug_item_display_point=>'ABOVE'
,p_query_type=>'SQL'
,p_plug_source=>'SELECT * FROM DMT_V_ASSIGNMENT_DETAIL WHERE (:P0_SCENARIO_ID IS NULL OR SCENARIO_ID = :P0_SCENARIO_ID)'
,p_plug_source_type=>'NATIVE_IR'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>11
,p_prn_height=>8.5
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
,p_ai_enabled=>false
,p_plug_comment=>'Assignments'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(1588337477607016851)
,p_max_row_count=>'1000000'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_internal_uid=>27514235076814126
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415661912898724407)
,p_db_column_name=>'ACTION_CODE'
,p_display_order=>100
,p_column_identifier=>'AC'
,p_column_label=>'Action Code'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415662667256724414)
,p_db_column_name=>'ASSIGNMENT_CATEGORY'
,p_display_order=>170
,p_column_identifier=>'AJ'
,p_column_label=>'Assignment Category'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415661658534724404)
,p_db_column_name=>'ASSIGNMENT_NAME'
,p_display_order=>70
,p_column_identifier=>'Z'
,p_column_label=>'Assignment Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415661308383724401)
,p_db_column_name=>'ASSIGNMENT_NUMBER'
,p_display_order=>40
,p_column_identifier=>'W'
,p_column_label=>'Assignment Number'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415661762207724405)
,p_db_column_name=>'ASSIGNMENT_STATUS_TYPE_CODE'
,p_display_order=>80
,p_column_identifier=>'AA'
,p_column_label=>'Assignment Status Type Code'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415661843546724406)
,p_db_column_name=>'BUSINESS_UNIT_NAME'
,p_display_order=>90
,p_column_identifier=>'AB'
,p_column_label=>'Business Unit Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415662284516724411)
,p_db_column_name=>'DEPARTMENT_NAME'
,p_display_order=>140
,p_column_identifier=>'AG'
,p_column_label=>'Department Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415661515326724403)
,p_db_column_name=>'EFFECTIVE_END_DATE'
,p_display_order=>60
,p_column_identifier=>'Y'
,p_column_label=>'Effective End Date'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415661389243724402)
,p_db_column_name=>'EFFECTIVE_START_DATE'
,p_display_order=>50
,p_column_identifier=>'X'
,p_column_label=>'Effective Start Date'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415661159621724399)
,p_db_column_name=>'ERROR_TEXT'
,p_display_order=>20
,p_column_identifier=>'U'
,p_column_label=>'Error Text'
,p_allow_sorting=>'N'
,p_allow_ctrl_breaks=>'N'
,p_allow_aggregations=>'N'
,p_allow_computations=>'N'
,p_allow_charting=>'N'
,p_allow_group_by=>'N'
,p_allow_pivot=>'N'
,p_column_type=>'CLOB'
,p_heading_alignment=>'LEFT'
,p_rpt_show_filter_lov=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415663064000724418)
,p_db_column_name=>'FREQUENCY'
,p_display_order=>210
,p_column_identifier=>'AN'
,p_column_label=>'Frequency'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415662689008724415)
,p_db_column_name=>'FULL_PART_TIME'
,p_display_order=>180
,p_column_identifier=>'AK'
,p_column_label=>'Full Part Time'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415662165549724409)
,p_db_column_name=>'GRADE_CODE'
,p_display_order=>120
,p_column_identifier=>'AE'
,p_column_label=>'Grade Code'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415662031401724408)
,p_db_column_name=>'JOB_CODE'
,p_display_order=>110
,p_column_identifier=>'AD'
,p_column_label=>'Job Code'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415664038431724428)
,p_db_column_name=>'LAST_UPDATED_DATE'
,p_display_order=>310
,p_column_identifier=>'AX'
,p_column_label=>'Last Updated Date'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415662203426724410)
,p_db_column_name=>'LOCATION_CODE'
,p_display_order=>130
,p_column_identifier=>'AF'
,p_column_label=>'Location Code'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415663203339724420)
,p_db_column_name=>'MANAGER_ASSIGNMENT_NUMBER'
,p_display_order=>230
,p_column_identifier=>'AP'
,p_column_label=>'Manager Assignment Number'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415663111276724419)
,p_db_column_name=>'MANAGER_PERSON_NUMBER'
,p_display_order=>220
,p_column_identifier=>'AO'
,p_column_label=>'Manager Person Number'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415662907088724417)
,p_db_column_name=>'NORMAL_HOURS'
,p_display_order=>200
,p_column_identifier=>'AM'
,p_column_label=>'Normal Hours'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415662808668724416)
,p_db_column_name=>'PERMANENT_TEMPORARY'
,p_display_order=>190
,p_column_identifier=>'AL'
,p_column_label=>'Permanent Temporary'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415661224198724400)
,p_db_column_name=>'PERSON_NUMBER'
,p_display_order=>30
,p_column_identifier=>'V'
,p_column_label=>'Person Number'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415662455426724412)
,p_db_column_name=>'POSITION_CODE'
,p_display_order=>150
,p_column_identifier=>'AH'
,p_column_label=>'Position Code'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415663766808724425)
,p_db_column_name=>'PREFIX'
,p_display_order=>280
,p_column_identifier=>'AU'
,p_column_label=>'Prefix'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415663356260724421)
,p_db_column_name=>'PRIMARY_ASSIGNMENT_FLAG'
,p_display_order=>240
,p_column_identifier=>'AQ'
,p_column_label=>'Primary Assignment Flag'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415663598632724424)
,p_db_column_name=>'RUN_ID'
,p_display_order=>270
,p_column_identifier=>'AT'
,p_column_label=>'Run Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415660993188724398)
,p_db_column_name=>'RUN_STATUS'
,p_display_order=>10
,p_column_identifier=>'T'
,p_column_label=>'Run Status'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415663803716724426)
,p_db_column_name=>'SCENARIO_ID'
,p_display_order=>290
,p_column_identifier=>'AV'
,p_column_label=>'Scenario Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415663475775724422)
,p_db_column_name=>'SOURCE_ID'
,p_display_order=>250
,p_column_identifier=>'AR'
,p_column_label=>'Source Id'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415663890370724427)
,p_db_column_name=>'STAGE_DATE'
,p_display_order=>300
,p_column_identifier=>'AW'
,p_column_label=>'Stage Date'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415663507191724423)
,p_db_column_name=>'STG_SEQUENCE_ID'
,p_display_order=>260
,p_column_identifier=>'AS'
,p_column_label=>'Stg Sequence Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415662559195724413)
,p_db_column_name=>'WORKER_CATEGORY'
,p_display_order=>160
,p_column_identifier=>'AI'
,p_column_label=>'Worker Category'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(1560838722201277883)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'358513'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(1574404143063473351)
,p_plug_name=>'Bulk Upload'
,p_static_id=>'bulk-upload'
,p_region_template_options=>'#DEFAULT#:is-collapsed:t-Region--scrollBody'
,p_plug_template=>2664334895415463485
,p_plug_display_sequence=>999
,p_plug_item_display_point=>'ABOVE'
,p_location=>null
,p_plug_source=>'<p>Upload a CSV file to bulk import data into the selected object''s staging table. Select the target object, choose your file, and click Upload. See the <a href="f?p=&APP_ID.:9:&SESSION.">Upload Reference Guide</a> for file format details.</p>'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(1580422004238419551)
,p_plug_name=>'Salaries'
,p_static_id=>'salaries'
,p_region_template_options=>'#DEFAULT#:is-collapsed:t-Region--scrollBody'
,p_plug_template=>2664334895415463485
,p_plug_display_sequence=>50
,p_plug_item_display_point=>'ABOVE'
,p_query_type=>'SQL'
,p_plug_source=>'SELECT * FROM DMT_V_SALARY_DETAIL WHERE (:P0_SCENARIO_ID IS NULL OR SCENARIO_ID = :P0_SCENARIO_ID)'
,p_plug_source_type=>'NATIVE_IR'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>11
,p_prn_height=>8.5
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
,p_ai_enabled=>false
,p_plug_comment=>'Salaries'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(1588339362405016870)
,p_max_row_count=>'1000000'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_internal_uid=>27516119874814145
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415750220553720685)
,p_db_column_name=>'ACTION_CODE'
,p_display_order=>120
,p_column_identifier=>'AF'
,p_column_label=>'Action Code'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415750059115720733)
,p_db_column_name=>'ANNUAL_FULL_TIME_SALARY'
,p_display_order=>100
,p_column_identifier=>'AD'
,p_column_label=>'Annual Full Time Salary'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415749918188720732)
,p_db_column_name=>'ANNUAL_SALARY'
,p_display_order=>90
,p_column_identifier=>'AC'
,p_column_label=>'Annual Salary'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415749630890720729)
,p_db_column_name=>'ASSIGNMENT_NUMBER'
,p_display_order=>60
,p_column_identifier=>'Z'
,p_column_label=>'Assignment Number'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415750135024720684)
,p_db_column_name=>'CURRENCY_CODE'
,p_display_order=>110
,p_column_identifier=>'AE'
,p_column_label=>'Currency Code'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415750506847720688)
,p_db_column_name=>'DATE_FROM'
,p_display_order=>150
,p_column_identifier=>'AI'
,p_column_label=>'Date From'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415750660224720689)
,p_db_column_name=>'DATE_TO'
,p_display_order=>160
,p_column_identifier=>'AJ'
,p_column_label=>'Date To'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415749575523720728)
,p_db_column_name=>'EFFECTIVE_END_DATE'
,p_display_order=>50
,p_column_identifier=>'Y'
,p_column_label=>'Effective End Date'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415749458771720727)
,p_db_column_name=>'EFFECTIVE_START_DATE'
,p_display_order=>40
,p_column_identifier=>'X'
,p_column_label=>'Effective Start Date'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415749228579720725)
,p_db_column_name=>'ERROR_TEXT'
,p_display_order=>20
,p_column_identifier=>'V'
,p_column_label=>'Error Text'
,p_allow_sorting=>'N'
,p_allow_ctrl_breaks=>'N'
,p_allow_aggregations=>'N'
,p_allow_computations=>'N'
,p_allow_charting=>'N'
,p_allow_group_by=>'N'
,p_allow_pivot=>'N'
,p_column_type=>'CLOB'
,p_heading_alignment=>'LEFT'
,p_rpt_show_filter_lov=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415750302325720686)
,p_db_column_name=>'FREQUENCY_NAME'
,p_display_order=>130
,p_column_identifier=>'AG'
,p_column_label=>'Frequency Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415751477550720697)
,p_db_column_name=>'LAST_UPDATED_DATE'
,p_display_order=>240
,p_column_identifier=>'AR'
,p_column_label=>'Last Updated Date'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415750379045720687)
,p_db_column_name=>'NEXT_SAL_REVIEW_DATE'
,p_display_order=>140
,p_column_identifier=>'AH'
,p_column_label=>'Next Sal Review Date'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415749364006720726)
,p_db_column_name=>'PERSON_NUMBER'
,p_display_order=>30
,p_column_identifier=>'W'
,p_column_label=>'Person Number'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415751135336720694)
,p_db_column_name=>'PREFIX'
,p_display_order=>210
,p_column_identifier=>'AO'
,p_column_label=>'Prefix'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415751004520720693)
,p_db_column_name=>'RUN_ID'
,p_display_order=>200
,p_column_identifier=>'AN'
,p_column_label=>'Run Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415749112406720724)
,p_db_column_name=>'RUN_STATUS'
,p_display_order=>10
,p_column_identifier=>'U'
,p_column_label=>'Run Status'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415749724395720730)
,p_db_column_name=>'SALARY_AMOUNT'
,p_display_order=>70
,p_column_identifier=>'AA'
,p_column_label=>'Salary Amount'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415750691585720690)
,p_db_column_name=>'SALARY_APPROVED'
,p_display_order=>170
,p_column_identifier=>'AK'
,p_column_label=>'Salary Approved'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415749878700720731)
,p_db_column_name=>'SALARY_BASIS_NAME'
,p_display_order=>80
,p_column_identifier=>'AB'
,p_column_label=>'Salary Basis Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415751212470720695)
,p_db_column_name=>'SCENARIO_ID'
,p_display_order=>220
,p_column_identifier=>'AP'
,p_column_label=>'Scenario Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415750827900720691)
,p_db_column_name=>'SOURCE_ID'
,p_display_order=>180
,p_column_identifier=>'AL'
,p_column_label=>'Source Id'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415751298298720696)
,p_db_column_name=>'STAGE_DATE'
,p_display_order=>230
,p_column_identifier=>'AQ'
,p_column_label=>'Stage Date'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415750888259720692)
,p_db_column_name=>'STG_SEQUENCE_ID'
,p_display_order=>190
,p_column_identifier=>'AM'
,p_column_label=>'Stg Sequence Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(1560839238984277871)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'358518'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(1453389468659988406)
,p_plug_name=>'Salary Bases'
,p_static_id=>'salary-bases'
,p_region_template_options=>'#DEFAULT#:is-collapsed:t-Region--scrollBody'
,p_plug_template=>2664334895415463485
,p_plug_display_sequence=>30
,p_plug_item_display_point=>'ABOVE'
,p_query_type=>'SQL'
,p_plug_source=>'SELECT * FROM DMT_V_SAL_BASIS_DETAIL WHERE (:P0_SCENARIO_ID IS NULL OR SCENARIO_ID = :P0_SCENARIO_ID)'
,p_plug_source_type=>'NATIVE_IR'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>11
,p_prn_height=>8.5
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
,p_ai_enabled=>false
,p_plug_comment=>'Salary Bases'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(1453389556875988407)
,p_max_row_count=>'1000000'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_internal_uid=>38603581615212334
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415745396782720687)
,p_db_column_name=>'ANNUALIZATION_FACTOR'
,p_display_order=>90
,p_column_identifier=>'J'
,p_column_label=>'Annualization Factor'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415745726197720690)
,p_db_column_name=>'DESCRIPTION'
,p_display_order=>120
,p_column_identifier=>'M'
,p_column_label=>'Description'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415664481672724433)
,p_db_column_name=>'EFFECTIVE_END_DATE'
,p_display_order=>50
,p_column_identifier=>'F'
,p_column_label=>'Effective End Date'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415664453741724432)
,p_db_column_name=>'EFFECTIVE_START_DATE'
,p_display_order=>40
,p_column_identifier=>'E'
,p_column_label=>'Effective Start Date'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415745078872720684)
,p_db_column_name=>'ELEMENT_NAME'
,p_display_order=>60
,p_column_identifier=>'G'
,p_column_label=>'Element Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415664244861724430)
,p_db_column_name=>'ERROR_TEXT'
,p_display_order=>20
,p_column_identifier=>'C'
,p_column_label=>'Error Text'
,p_allow_sorting=>'N'
,p_allow_ctrl_breaks=>'N'
,p_allow_aggregations=>'N'
,p_allow_computations=>'N'
,p_allow_charting=>'N'
,p_allow_group_by=>'N'
,p_allow_pivot=>'N'
,p_column_type=>'CLOB'
,p_heading_alignment=>'LEFT'
,p_rpt_show_filter_lov=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415745569944720688)
,p_db_column_name=>'GRADE_RATE_TYPE'
,p_display_order=>100
,p_column_identifier=>'K'
,p_column_label=>'Grade Rate Type'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415745194773720685)
,p_db_column_name=>'INPUT_VALUE_NAME'
,p_display_order=>70
,p_column_identifier=>'H'
,p_column_label=>'Input Value Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415746423219720697)
,p_db_column_name=>'LAST_UPDATED_DATE'
,p_display_order=>190
,p_column_identifier=>'T'
,p_column_label=>'Last Updated Date'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415745619522720689)
,p_db_column_name=>'LEGISLATIVE_DATA_GROUP_NAME'
,p_display_order=>110
,p_column_identifier=>'L'
,p_column_label=>'Legislative Data Group Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415746104209720694)
,p_db_column_name=>'PREFIX'
,p_display_order=>160
,p_column_identifier=>'Q'
,p_column_label=>'Prefix'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415746053795720693)
,p_db_column_name=>'RUN_ID'
,p_display_order=>150
,p_column_identifier=>'P'
,p_column_label=>'Run Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415664169234724429)
,p_db_column_name=>'RUN_STATUS'
,p_display_order=>10
,p_column_identifier=>'B'
,p_column_label=>'Run Status'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415745366151720686)
,p_db_column_name=>'SALARY_BASIS_CODE'
,p_display_order=>80
,p_column_identifier=>'I'
,p_column_label=>'Salary Basis Code'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415664364862724431)
,p_db_column_name=>'SALARY_BASIS_NAME'
,p_display_order=>30
,p_column_identifier=>'D'
,p_column_label=>'Salary Basis Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415746257759720695)
,p_db_column_name=>'SCENARIO_ID'
,p_display_order=>170
,p_column_identifier=>'R'
,p_column_label=>'Scenario Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415745865806720691)
,p_db_column_name=>'SOURCE_ID'
,p_display_order=>130
,p_column_identifier=>'N'
,p_column_label=>'Source Id'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415746334130720696)
,p_db_column_name=>'STAGE_DATE'
,p_display_order=>180
,p_column_identifier=>'S'
,p_column_label=>'Stage Date'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(1415745952426720692)
,p_db_column_name=>'STG_SEQUENCE_ID'
,p_display_order=>140
,p_column_identifier=>'O'
,p_column_label=>'Stg Sequence Id'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_use_as_row_header=>'N'
,p_available_clientside=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(1338830222388302262)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'475667'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'RUN_STATUS:ERROR_TEXT:SALARY_BASIS_NAME:EFFECTIVE_START_DATE:EFFECTIVE_END_DATE:ELEMENT_NAME:INPUT_VALUE_NAME:SALARY_BASIS_CODE:ANNUALIZATION_FACTOR:GRADE_RATE_TYPE:LEGISLATIVE_DATA_GROUP_NAME:DESCRIPTION:SOURCE_ID:STG_SEQUENCE_ID:RUN_ID:PREFIX:SCENA'
||'RIO_ID:STAGE_DATE:LAST_UPDATED_DATE'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(1574404459736473354)
,p_button_sequence=>30
,p_button_plug_id=>wwv_flow_imp.id(1574404143063473351)
,p_button_name=>'UPLOAD_CSV'
,p_static_id=>'upload-csv'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>4072362960822175091
,p_button_image_alt=>'Upload CSV'
,p_grid_new_row=>'Y'
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(989176812264730610)
,p_name=>'P7_SCENARIO'
,p_item_sequence=>15
,p_item_plug_id=>wwv_flow_imp.id(1574404143063473351)
,p_prompt=>'Scenario'
,p_source_type=>'ALWAYS_NULL'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_lov=>'SELECT scenario_name d, scenario_name r FROM dmt_scenario_tbl WHERE status = ''ACTIVE'' ORDER BY scenario_name'
,p_lov_display_null=>'YES'
,p_lov_null_text=>'-- No Scenario --'
,p_cHeight=>1
,p_field_template=>1609121967514267634
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'NO'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'page_action_on_selection', 'NONE')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(1574404394778473353)
,p_name=>'P7_UPLOAD_FILE'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_imp.id(1574404143063473351)
,p_prompt=>'Upload File'
,p_source_type=>'ALWAYS_NULL'
,p_display_as=>'NATIVE_FILE'
,p_cSize=>30
,p_field_template=>1609121967514267634
,p_item_template_options=>'#DEFAULT#'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'allow_copy_paste', 'N',
  'allow_multiple_files', 'N',
  'display_as', 'INLINE',
  'purge_file_at', 'SESSION',
  'storage_type', 'APEX_APPLICATION_TEMP_FILES')).to_clob
);
wwv_flow_imp_page.create_page_item(
 p_id=>wwv_flow_imp.id(1574404280122473352)
,p_name=>'P7_UPLOAD_OBJECT'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_imp.id(1574404143063473351)
,p_prompt=>'Target Object'
,p_source_type=>'ALWAYS_NULL'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_lov=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT DISPLAY_NAME d, OBJECT_CODE r',
'FROM DMT_UPLOAD_OBJECT_TBL',
'WHERE PAGE_NUMBER = 7 AND IS_ACTIVE = ''Y''',
'ORDER BY DISPLAY_ORDER'))
,p_lov_display_null=>'YES'
,p_cHeight=>1
,p_field_template=>1609121967514267634
,p_item_template_options=>'#DEFAULT#'
,p_lov_display_extra=>'YES'
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'page_action_on_selection', 'NONE')).to_clob
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(1583201969375305335)
,p_process_sequence=>10
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'Upload CSV'
,p_static_id=>'upload-csv'
,p_process_sql_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'DECLARE',
'    l_rows_loaded  NUMBER;',
'    l_rows_errored NUMBER;',
'    l_batch_id     NUMBER;',
'    l_error_msg    VARCHAR2(4000);',
'BEGIN',
'    DMT_CSV_UPLOAD_PKG.UPLOAD_CSV(',
'        p_file_name    => :P7_UPLOAD_FILE,',
'        p_object_code  => :P7_UPLOAD_OBJECT,',
'        p_rows_loaded  => l_rows_loaded,',
'        p_rows_errored => l_rows_errored,',
'        p_batch_id_out => l_batch_id,',
'        p_error_msg     => l_error_msg,',
'        p_scenario_name => :P7_SCENARIO',
'    );',
'    IF l_error_msg IS NOT NULL THEN',
'        APEX_ERROR.ADD_ERROR(p_message => l_error_msg, p_display_location => ''INLINE_IN_NOTIFICATION'');',
'    ELSE',
'        APEX_APPLICATION.G_PRINT_SUCCESS_MESSAGE :=',
'            l_rows_loaded || '' rows loaded, '' || l_rows_errored || '' errors. Batch ID: '' || l_batch_id;',
'    END IF;',
'END;'))
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_process_when_button_id=>wwv_flow_imp.id(1574404459736473354)
,p_internal_uid=>22378726845102610
);
wwv_flow_imp.component_end;
end;
/
