"""
FBDI column-position maps for the DMT2 upload feature.

Single source of truth for BOTH:
  * the FBDI_POSITION seed (db/seed/dmt_upload_fbdi_positions.sql is generated
    from this module), and
  * the FBDIFormat.zip test-file builder (build_regression_zips.py).

Each entry maps an upload OBJECT_CODE to
    (fbdi_filename, [column_or_None for each 1-based CSV position]).
None marks a slot the pipeline's FBDI generator writes as a literal empty
value or a value with no staging-table column (a synthetic key such as the
AP invoice INVOICE_ID, or a transform-only column such as GL RECON_KEY). The
seeder and the zip builder both skip None slots and any name not present in
the target staging table, so a round-trip is correct by construction.

Derived by reading the pipeline FBDI generator packages
(db/packages/*_fbdi_gen_pkg.pkb.sql) and cross-checked against the real
generated CSVs stored in DMT_FBDI_CSV_TBL for run 167 (column counts and
sample values matched exactly for the supplier family and items).

Only the ~24 FBDI (.csv) objects appear here. HDL (.dat) objects are out of
scope for the FBDI format and are covered by the proprietary format only.
"""


def rng(prefix, a, b):
    return [f"{prefix}{i}" for i in range(a, b + 1)]


MAPS = {}

# ---------------- GL Balances (GlInterface.csv) ----------------
# 149 emitted fields; slot 53 = RECON_KEY (transform-only, dropped by seeder).
gl = [None] * 152
gl[0] = 'JOURNAL_STATUS'
gl[2] = 'ACCOUNTING_DATE'
gl[3] = 'USER_JE_SOURCE_NAME'
gl[4] = 'USER_JE_CATEGORY_NAME'
gl[5] = 'CURRENCY_CODE'
gl[6] = 'DATE_CREATED'
gl[7] = 'ACTUAL_FLAG'
for i in range(1, 31):
    gl[8 + i - 1] = f'SEGMENT{i}'            # slots 9..38
gl[38] = 'ENTERED_DR'
gl[39] = 'ENTERED_CR'
gl[40] = 'ACCOUNTED_DR'
gl[41] = 'ACCOUNTED_CR'
gl[42] = 'REFERENCE1'
gl[43] = 'REFERENCE2'
gl[45] = 'REFERENCE4'
gl[46] = 'REFERENCE5'
gl[47] = 'REFERENCE6'
gl[48] = 'REFERENCE7'
gl[49] = 'REFERENCE8'
gl[51] = 'REFERENCE10'
gl[52] = 'RECON_KEY'                          # slot 53 (transform-only)
gl[62] = 'STAT_AMOUNT'
gl[63] = 'USER_CURRENCY_CONVERSION_TYPE'
gl[64] = 'CURRENCY_CONVERSION_DATE'
gl[65] = 'CURRENCY_CONVERSION_RATE'
gl[66] = 'GROUP_ID'
gl[67] = 'ATTRIBUTE_CATEGORY'
for i in range(1, 21):
    gl[68 + i - 1] = f'ATTRIBUTE{i}'          # slots 69..88
gl[91] = 'LEDGER_NAME'                        # slot 92
gl[94] = 'PERIOD_NAME'                        # slot 95
MAPS['GL_INTERFACE'] = ('GlInterface.csv', gl)

# ---------------- GL Budgets (GlBudgetInterface.csv) ----------------
glb = ['RUN_NAME', 'STATUS_FBDI', 'LEDGER_ID', 'BUDGET_NAME', 'PERIOD_NAME',
       'CURRENCY_CODE'] + rng('SEGMENT', 1, 30) + ['BUDGET_AMOUNT', 'LEDGER_NAME']
MAPS['GL_BUDGET_INT'] = ('GlBudgetInterface.csv', glb)

# ---------------- Suppliers family ----------------
sup = ['IMPORT_ACTION', 'VENDOR_NAME', 'VENDOR_NAME_NEW', 'SEGMENT1', 'VENDOR_NAME_ALT',
       'ORGANIZATION_TYPE_LOOKUP_CODE', 'VENDOR_TYPE_LOOKUP_CODE', 'END_DATE_ACTIVE',
       'BUSINESS_RELATIONSHIP', 'PARENT_SUPPLIER_NAME', 'ALIAS', 'DUNS_NUMBER', 'ONE_TIME_FLAG',
       'CUSTOMER_NUM', 'STANDARD_INDUSTRY_CLASS', 'NI_NUMBER', 'CORPORATE_WEBSITE',
       'CHIEF_EXECUTIVE_TITLE', 'CHIEF_EXECUTIVE_NAME', 'BC_NOT_APPLICABLE_FLAG', 'TAX_COUNTRY_CODE',
       'NUM_1099', 'FEDERAL_REPORTABLE_FLAG', 'TYPE_1099', 'STATE_REPORTABLE_FLAG',
       'TAX_REPORTING_NAME', 'NAME_CONTROL', 'TAX_VERIFICATION_DATE', 'ALLOW_AWT_FLAG',
       'AWT_GROUP_NAME', 'VAT_CODE', 'VAT_REGISTRATION_NUM', 'AUTO_TAX_CALC_OVERRIDE',
       'PAYMENT_METHOD_LOOKUP_CODE', 'DELIVERY_CHANNEL_CODE', 'BANK_INSTRUCTION1_CODE',
       'BANK_INSTRUCTION2_CODE', 'BANK_INSTRUCTION_DETAILS', 'SETTLEMENT_PRIORITY',
       'PAYMENT_TEXT_MESSAGE1', 'PAYMENT_TEXT_MESSAGE2', 'PAYMENT_TEXT_MESSAGE3',
       'IBY_BANK_CHARGE_BEARER', 'PAYMENT_REASON_CODE', 'PAYMENT_REASON_COMMENTS',
       'PAYMENT_FORMAT_CODE', 'ATTRIBUTE_CATEGORY']
sup += rng('ATTRIBUTE', 1, 20) + rng('ATTRIBUTE_DATE', 1, 10) + rng('ATTRIBUTE_TIMESTAMP', 1, 10) + rng('ATTRIBUTE_NUMBER', 1, 10)
sup += ['GLOBAL_ATTRIBUTE_CATEGORY'] + rng('GLOBAL_ATTRIBUTE', 1, 20) + rng('GLOBAL_ATTRIBUTE_DATE', 1, 10) + rng('GLOBAL_ATTRIBUTE_TIMESTAMP', 1, 10) + rng('GLOBAL_ATTRIBUTE_NUMBER', 1, 10)
sup += ['PARTY_NUMBER', 'SERVICE_LEVEL_CODE', 'EXCLUSIVE_PAYMENT_FLAG', 'REMIT_ADVICE_DELIVERY_METHOD',
        'REMIT_ADVICE_EMAIL', 'REMIT_ADVICE_FAX', 'DATAFOX_COMPANY_ID']
MAPS['POZ_SUPPLIERS'] = ('PoSupplierImport.csv', sup)

addr = ['IMPORT_ACTION', 'VENDOR_NAME', 'PARTY_SITE_NAME', 'PARTY_SITE_NAME_NEW', 'COUNTRY',
        'ADDRESS_LINE1', 'ADDRESS_LINE2', 'ADDRESS_LINE3', 'ADDRESS_LINE4', 'ADDRESS_LINES_PHONETIC']
addr += rng('ADDR_ELEMENT_ATTRIBUTE', 1, 5)
addr += ['BUILDING', 'FLOOR_NUMBER', 'CITY', 'STATE', 'PROVINCE', 'COUNTY', 'POSTAL_CODE',
         'POSTAL_PLUS4_CODE', 'ADDRESSEE', 'GLOBAL_LOCATION_NUMBER', 'PARTY_SITE_LANGUAGE',
         'INACTIVE_DATE', 'PHONE_COUNTRY_CODE', 'PHONE_AREA_CODE', 'PHONE', 'PHONE_EXTENSION',
         'FAX_COUNTRY_CODE', 'FAX_AREA_CODE', 'FAX', 'RFQ_OR_BIDDING_PURPOSE_FLAG',
         'ORDERING_PURPOSE_FLAG', 'REMIT_TO_PURPOSE_FLAG', 'ATTRIBUTE_CATEGORY']
addr += rng('ATTRIBUTE', 1, 30) + rng('ATTRIBUTE_NUMBER', 1, 12) + rng('ATTRIBUTE_DATE', 1, 12)
addr += ['EMAIL_ADDRESS', 'DELIVERY_CHANNEL_CODE', 'BANK_INSTRUCTION1_CODE', 'BANK_INSTRUCTION2_CODE',
         'BANK_INSTRUCTION_DETAILS', 'SETTLEMENT_PRIORITY', 'PAYMENT_TEXT_MESSAGE1',
         'PAYMENT_TEXT_MESSAGE2', 'PAYMENT_TEXT_MESSAGE3', 'SERVICE_LEVEL_CODE',
         'EXCLUSIVE_PAYMENT_FLAG', 'IBY_BANK_CHARGE_BEARER', 'PAYMENT_REASON_CODE',
         'PAYMENT_REASON_COMMENTS', 'REMIT_ADVICE_DELIVERY_METHOD', 'REMIT_ADVICE_EMAIL',
         'REMIT_ADVICE_FAX']
MAPS['POZ_SUP_ADDR'] = ('PozSupAddressesInt.csv', addr)

site = ['IMPORT_ACTION', 'VENDOR_NAME', 'PROCUREMENT_BUSINESS_UNIT_NAME', 'PARTY_SITE_NAME',
        'VENDOR_SITE_CODE', 'VENDOR_SITE_CODE_NEW', 'INACTIVE_DATE', 'RFQ_ONLY_SITE_FLAG',
        'PURCHASING_SITE_FLAG', 'PCARD_SITE_FLAG', 'PAY_SITE_FLAG', 'PRIMARY_PAY_SITE_FLAG',
        'TAX_REPORTING_SITE_FLAG', 'VENDOR_SITE_CODE_ALT', 'CUSTOMER_NUM', 'B2B_COMM_METHOD_CODE',
        'B2B_SITE_CODE', 'SUPPLIER_NOTIF_METHOD', 'EMAIL_ADDRESS', 'FAX_COUNTRY_CODE', 'FAX_AREA_CODE',
        'FAX', 'HOLD_FLAG', 'PURCHASING_HOLD_REASON', 'CARRIER', 'MODE_OF_TRANSPORT_CODE',
        'SERVICE_LEVEL_CODE', 'FREIGHT_TERMS_LOOKUP_CODE', 'PAY_ON_CODE', 'FOB_LOOKUP_CODE',
        'COUNTRY_OF_ORIGIN_CODE', 'BUYER_MANAGED_TRANSPORT_FLAG', 'PAY_ON_USE_FLAG', 'AGING_ONSET_POINT',
        'AGING_PERIOD_DAYS', 'CONSUMPTION_ADVICE_FREQUENCY', 'CONSUMPTION_ADVICE_SUMMARY',
        'DEFAULT_PAY_SITE_CODE', 'PAY_ON_RECEIPT_SUMMARY_CODE', 'GAPLESS_INV_NUM_FLAG',
        'SELLING_COMPANY_IDENTIFIER', 'CREATE_DEBIT_MEMO_FLAG', 'ENFORCE_SHIP_TO_LOCATION_CODE',
        'RECEIVING_ROUTING_ID', 'QTY_RCV_TOLERANCE', 'QTY_RCV_EXCEPTION_CODE',
        'DAYS_EARLY_RECEIPT_ALLOWED', 'DAYS_LATE_RECEIPT_ALLOWED', 'ALLOW_SUBSTITUTE_RECEIPTS_FLAG',
        'ALLOW_UNORDERED_RECEIPTS_FLAG', 'RECEIPT_DAYS_EXCEPTION_CODE', 'INVOICE_CURRENCY_CODE',
        'INVOICE_AMOUNT_LIMIT', 'MATCH_OPTION', 'MATCH_APPROVAL_LEVEL', 'PAYMENT_CURRENCY_CODE',
        'PAYMENT_PRIORITY', 'PAY_GROUP_LOOKUP_CODE', 'TOLERANCE_NAME', 'SERVICES_TOLERANCE',
        'HOLD_ALL_PAYMENTS_FLAG', 'HOLD_UNMATCHED_INVOICES_FLAG', 'HOLD_FUTURE_PAYMENTS_FLAG', 'HOLD_BY',
        'PAYMENT_HOLD_DATE', 'HOLD_REASON', 'TERMS_NAME', 'TERMS_DATE_BASIS',
        'PAY_DATE_BASIS_LOOKUP_CODE', 'BANK_CHARGE_DEDUCTION_TYPE', 'ALWAYS_TAKE_DISC_FLAG',
        'EXCLUDE_FREIGHT_FROM_DISCOUNT', 'EXCLUDE_TAX_FROM_DISCOUNT', 'AUTO_CALCULATE_INTEREST_FLAG',
        'VAT_CODE', 'VAT_REGISTRATION_NUM', 'PAYMENT_METHOD_LOOKUP_CODE', 'DELIVERY_CHANNEL_CODE',
        'BANK_INSTRUCTION1_CODE', 'BANK_INSTRUCTION2_CODE', 'BANK_INSTRUCTION_DETAILS',
        'SETTLEMENT_PRIORITY', 'PAYMENT_TEXT_MESSAGE1', 'PAYMENT_TEXT_MESSAGE2', 'PAYMENT_TEXT_MESSAGE3',
        'IBY_BANK_CHARGE_BEARER', 'PAYMENT_REASON_CODE', 'PAYMENT_REASON_COMMENTS',
        'REMIT_ADVICE_DELIVERY_METHOD', 'REMITTANCE_EMAIL', 'REMITTANCE_FAX', 'ATTRIBUTE_CATEGORY']
site += rng('ATTRIBUTE', 1, 20) + rng('ATTRIBUTE_DATE', 1, 10) + rng('ATTRIBUTE_TIMESTAMP', 1, 10) + rng('ATTRIBUTE_NUMBER', 1, 10)
site += ['GLOBAL_ATTRIBUTE_CATEGORY'] + rng('GLOBAL_ATTRIBUTE', 1, 20) + rng('GLOBAL_ATTRIBUTE_DATE', 1, 10) + rng('GLOBAL_ATTRIBUTE_TIMESTAMP', 1, 10) + rng('GLOBAL_ATTRIBUTE_NUMBER', 1, 10)
site += ['PO_ACK_REQD_CODE', 'PO_ACK_REQD_DAYS', 'INVOICE_CHANNEL', 'PAYEE_SERVICE_LEVEL_CODE',
         'EXCLUSIVE_PAYMENT_FLAG', 'OVERRIDE_B2B_COMM_CODE']
MAPS['POZ_SUP_SITE'] = ('PozSupplierSitesInt.csv', site)

assn = ['IMPORT_ACTION', 'VENDOR_NAME', 'VENDOR_SITE_CODE', 'PROCUREMENT_BUSINESS_UNIT_NAME',
        'BUSINESS_UNIT_NAME', 'BILL_TO_BU_NAME', 'SHIP_TO_LOCATION_CODE', 'BILL_TO_LOCATION_CODE',
        'ALLOW_AWT_FLAG', 'AWT_GROUP_NAME', 'ACCTS_PAY_CONCAT_SEGMENTS', 'PREPAY_CONCAT_SEGMENTS',
        'FUTURE_DATED_CONCAT_SEGMENTS', 'DISTRIBUTION_SET_NAME', 'INACTIVE_DATE']
MAPS['POZ_SUP_SITE_ASSN'] = ('PozSiteAssignmentsInt.csv', assn)

cont = ['IMPORT_ACTION', 'VENDOR_NAME', 'PREFIX', 'FIRST_NAME', 'FIRST_NAME_NEW', 'MIDDLE_NAME',
        'LAST_NAME', 'LAST_NAME_NEW', 'TITLE', 'PRIMARY_ADMIN_CONTACT', 'EMAIL_ADDRESS',
        'EMAIL_ADDRESS_NEW', 'PHONE_COUNTRY_CODE', 'AREA_CODE', 'PHONE', 'PHONE_EXTENSION',
        'FAX_COUNTRY_CODE', 'FAX_AREA_CODE', 'FAX', 'MOBILE_COUNTRY_CODE', 'MOBILE_AREA_CODE', 'MOBILE',
        'INACTIVE_DATE', 'ATTRIBUTE_CATEGORY']
cont += rng('ATTRIBUTE', 1, 30) + rng('ATTRIBUTE_NUMBER', 1, 12) + rng('ATTRIBUTE_DATE', 1, 12)
cont += ['USER_ACCOUNT_ACTION'] + rng('ROLE', 1, 10)
MAPS['POZ_SUP_CONTACTS'] = ('PozSupContactsInt.csv', cont)

# ---------------- PO family (standard "Order" generator) ----------------
poh = ['INTERFACE_HEADER_KEY', 'ACTION', 'BATCH_ID', 'INTERFACE_SOURCE_CODE', 'APPROVAL_ACTION',
       'DOCUMENT_NUM', 'DOCUMENT_TYPE_CODE', 'STYLE_DISPLAY_NAME', 'PRC_BU_NAME', 'REQ_BU_NAME',
       'SOLDTO_LE_NAME', 'BILLTO_BU_NAME', 'AGENT_NAME', 'CURRENCY_CODE', 'RATE', 'RATE_TYPE',
       'RATE_DATE', 'COMMENTS', 'BILL_TO_LOCATION', 'SHIP_TO_LOCATION', 'VENDOR_NAME', 'VENDOR_NUM',
       'VENDOR_SITE_CODE', 'VENDOR_CONTACT', 'VENDOR_DOC_NUM', 'FOB', 'FREIGHT_CARRIER', 'FREIGHT_TERMS',
       'PAY_ON_CODE', 'PAYMENT_TERMS', 'ORIGINATOR_ROLE', 'CHANGE_ORDER_DESC',
       'ACCEPTANCE_REQUIRED_FLAG', 'ACCEPTANCE_WITHIN_DAYS', 'SUPPLIER_NOTIF_METHOD', 'FAX',
       'EMAIL_ADDRESS', 'CONFIRMING_ORDER_FLAG', 'NOTE_TO_VENDOR', 'NOTE_TO_RECEIVER',
       'DEFAULT_TAXATION_COUNTRY', 'TAX_DOCUMENT_SUBTYPE', 'ATTRIBUTE_CATEGORY']
poh += rng('ATTRIBUTE', 1, 20) + rng('ATTRIBUTE_DATE', 1, 10) + rng('ATTRIBUTE_NUMBER', 1, 10) + rng('ATTRIBUTE_TIMESTAMP', 1, 10)
poh += ['AGENT_EMAIL_ADDRESS', 'MODE_OF_TRANSPORT', 'SERVICE_LEVEL', 'FIRST_PTY_REG_NUM',
        'THIRD_PTY_REG_NUM', 'BUYER_MANAGED_TRANSPORT_FLAG']
MAPS['PO_HEADERS_INT'] = ('PoHeadersInterfaceOrder.csv', poh)

pol = ['INTERFACE_LINE_KEY', 'INTERFACE_HEADER_KEY', 'ACTION', 'LINE_NUM', 'LINE_TYPE', 'ITEM',
       'ITEM_DESCRIPTION', 'ITEM_REVISION', 'CATEGORY', 'AMOUNT', 'QUANTITY', 'UNIT_OF_MEASURE',
       'UNIT_PRICE', 'SECONDARY_QUANTITY', 'SECONDARY_UNIT_OF_MEASURE', 'VENDOR_PRODUCT_NUM',
       'NEGOTIATED_BY_PREPARER_FLAG', 'HAZARD_CLASS', 'UN_NUMBER', 'NOTE_TO_VENDOR', 'NOTE_TO_RECEIVER',
       'LINE_ATTRIBUTE_CATEGORY_LINES']
pol += rng('LINE_ATTRIBUTE', 1, 15) + rng('ATTRIBUTE', 16, 20) + rng('ATTRIBUTE_DATE', 1, 10) + rng('ATTRIBUTE_NUMBER', 1, 10) + rng('ATTRIBUTE_TIMESTAMP', 1, 10)
pol += ['UNIT_WEIGHT', 'WEIGHT_UOM_CODE', 'WEIGHT_UNIT_OF_MEASURE', 'UNIT_VOLUME', 'VOLUME_UOM_CODE',
        'VOLUME_UNIT_OF_MEASURE', 'TEMPLATE_NAME', 'ITEM_ATTRIBUTE_CATEGORY']
pol += rng('ITEM_ATTRIBUTE', 1, 15) + ['SOURCE_AGREEMENT_PRC_BU_NAME', 'SOURCE_AGREEMENT', 'SOURCE_AGREEMENT_LINE']
MAPS['PO_LINES_INT'] = ('PoLinesInterfaceOrder.csv', pol)

poll = ['INTERFACE_LINE_LOCATION_KEY', 'INTERFACE_LINE_KEY', 'SHIPMENT_NUM', 'SHIP_TO_LOCATION',
        'SHIP_TO_ORGANIZATION_CODE', 'AMOUNT', 'QUANTITY', 'NEED_BY_DATE', 'PROMISED_DATE',
        'SECONDARY_QUANTITY', 'SECONDARY_UNIT_OF_MEASURE', 'DESTINATION_TYPE_CODE',
        'ACCRUE_ON_RECEIPT_FLAG', 'ALLOW_SUBSTITUTE_RECEIPTS_FLAG', 'ASSESSABLE_VALUE',
        'DAYS_EARLY_RECEIPT_ALLOWED', 'DAYS_LATE_RECEIPT_ALLOWED', 'ENFORCE_SHIP_TO_LOCATION_CODE',
        'INSPECTION_REQUIRED_FLAG', 'RECEIPT_REQUIRED_FLAG', 'INVOICE_CLOSE_TOLERANCE',
        'RECEIVE_CLOSE_TOLERANCE', 'QTY_RCV_TOLERANCE', 'QTY_RCV_EXCEPTION_CODE',
        'RECEIPT_DAYS_EXCEPTION_CODE', 'RECEIVING_ROUTING', 'NOTE_TO_RECEIVER',
        'INPUT_TAX_CLASSIFICATION_CODE', 'LINE_INTENDED_USE', 'PRODUCT_CATEGORY',
        'PRODUCT_FISC_CLASSIFICATION', 'PRODUCT_TYPE', 'TRX_BUSINESS_CATEGORY',
        'USER_DEFINED_FISC_CLASS', 'ATTRIBUTE_CATEGORY']
poll += rng('ATTRIBUTE', 1, 20) + rng('ATTRIBUTE_DATE', 1, 10) + rng('ATTRIBUTE_NUMBER', 1, 10) + rng('ATTRIBUTE_TIMESTAMP', 1, 10)
poll += ['FREIGHT_CARRIER', 'MODE_OF_TRANSPORT', 'SERVICE_LEVEL', 'FINAL_DISCHARGE_LOCATION_CODE',
         'REQUESTED_SHIP_DATE', 'PROMISED_SHIP_DATE', 'REQUESTED_DELIVERY_DATE', 'PROMISED_DELIVERY_DATE']
MAPS['PO_LINE_LOCS_INT'] = ('PoLineLocationsInterfaceOrder.csv', poll)

pod = ['INTERFACE_DISTRIBUTION_KEY', 'INTERFACE_LINE_LOCATION_KEY', 'DISTRIBUTION_NUM',
       'DELIVER_TO_LOCATION', 'DELIVER_TO_PERSON_FULL_NAME', 'DESTINATION_SUBINVENTORY',
       'AMOUNT_ORDERED', 'QUANTITY_ORDERED']
pod += rng('CHARGE_ACCOUNT_SEGMENT', 1, 30)
pod += ['DESTINATION_CONTEXT', 'PROJECT', 'TASK', 'PJC_EXPENDITURE_ITEM_DATE', 'EXPENDITURE',
        'EXPENDITURE_ORGANIZATION', 'PJC_BILLABLE_FLAG', 'PJC_CAPITALIZABLE_FLAG', 'PJC_WORK_TYPE']
pod += rng('PJC_RESERVED_ATTRIBUTE', 1, 10) + rng('PJC_USER_DEF_ATTRIBUTE', 1, 10)
pod += ['RATE', 'RATE_DATE', 'ATTRIBUTE_CATEGORY']
pod += rng('ATTRIBUTE', 1, 4) + rng('ATTRIBUTE', 6, 20)   # ATTRIBUTE5 skipped by the generator
pod += rng('ATTRIBUTE_DATE', 1, 10) + rng('ATTRIBUTE_NUMBER', 1, 10) + rng('ATTRIBUTE_TIMESTAMP', 1, 10)
pod += ['DELIVER_TO_PERSON_EMAIL_ADDR', 'BUDGET_DATE', 'PJC_CONTRACT_NUMBER', 'PJC_FUNDING_SOURCE']
MAPS['PO_DISTS_INT'] = ('PoDistributionsInterfaceOrder.csv', pod)

# ---------------- Customers (7 files) ----------------
hzp = ['BATCH_ID', 'PARTY_ORIG_SYSTEM', 'PARTY_ORIG_SYSTEM_REFERENCE', 'INSERT_UPDATE_FLAG',
       'PARTY_TYPE', 'PARTY_NUMBER', 'SALUTATION', 'PARTY_USAGE_CODE', 'JGZZ_FISCAL_CODE',
       'ORGANIZATION_NAME', 'DUNS_NUMBER_C', 'PERSON_FIRST_NAME', 'PERSON_LAST_NAME',
       'PERSON_LAST_NAME_PREFIX', 'PERSON_SECOND_LAST_NAME', 'PERSON_MIDDLE_NAME', 'PERSON_NAME_SUFFIX',
       'PERSON_TITLE', 'ATTRIBUTE_CATEGORY'] + rng('ATTRIBUTE', 1, 20)
MAPS['HZ_PARTIES'] = ('HzImpPartiesT.csv', hzp)

hzl = ['BATCH_ID', 'LOCATION_ORIG_SYSTEM', 'LOCATION_ORIG_SYSTEM_REFERENCE', 'INSERT_UPDATE_FLAG',
       'COUNTRY', 'ADDRESS1', 'ADDRESS2', 'ADDRESS3', 'ADDRESS4', 'CITY', 'STATE', 'PROVINCE', 'COUNTY',
       'POSTAL_CODE', 'POSTAL_PLUS4_CODE', 'LOCATION_LANGUAGE', 'DESCRIPTION', 'SHORT_DESCRIPTION',
       'SALES_TAX_GEOCODE', 'SALES_TAX_INSIDE_CITY_LIMITS', 'TIMEZONE_CODE', 'ADDRESS1_STD',
       'ADAPTER_CONTENT_SOURCE', 'ADDR_VALID_STATUS_CODE', 'DATE_VALIDATED', 'ADDRESS_EFFECTIVE_DATE',
       'ADDRESS_EXPIRATION_DATE', 'VALIDATED_FLAG', 'DO_NOT_VALIDATE_FLAG',
       'ATTRIBUTE_CATEGORY'] + rng('ATTRIBUTE', 1, 20)
MAPS['HZ_LOCATIONS'] = ('HzImpLocationsT.csv', hzl)

hzps = ['BATCH_ID', 'PARTY_ORIG_SYSTEM', 'PARTY_ORIG_SYSTEM_REFERENCE', 'SITE_ORIG_SYSTEM',
        'SITE_ORIG_SYSTEM_REFERENCE', 'LOCATION_ORIG_SYSTEM', 'LOCATION_ORIG_SYSTEM_REFERENCE',
        'INSERT_UPDATE_FLAG', 'PARTY_SITE_NAME', 'PARTY_SITE_NUMBER', 'START_DATE_ACTIVE',
        'END_DATE_ACTIVE', 'MAILSTOP', 'IDENTIFYING_ADDRESS_FLAG', 'PARTY_SITE_LANGUAGE',
        'REL_ORIG_SYSTEM', 'REL_ORIG_SYSTEM_REFERENCE', 'ATTRIBUTE_CATEGORY'] + rng('ATTRIBUTE', 1, 20)
MAPS['HZ_PARTY_SITES'] = ('HzImpPartySitesT.csv', hzps)

hzpsu = ['BATCH_ID', 'PARTY_ORIG_SYSTEM', 'PARTY_ORIG_SYSTEM_REFERENCE', 'SITE_ORIG_SYSTEM',
         'SITE_ORIG_SYSTEM_REFERENCE', 'SITE_USE_TYPE', 'PRIMARY_FLAG', 'INSERT_UPDATE_FLAG',
         'START_DATE', 'END_DATE', 'SITEUSE_ORIG_SYSTEM', 'SITEUSE_ORIG_SYSTEM_REF',
         'ATTRIBUTE_CATEGORY'] + rng('ATTRIBUTE', 1, 20)
MAPS['HZ_PARTY_SITE_USES'] = ('HzImpPartySiteUsesT.csv', hzpsu)

hza = ['BATCH_ID', 'CUST_ORIG_SYSTEM', 'CUST_ORIG_SYSTEM_REFERENCE', 'PARTY_ORIG_SYSTEM',
       'PARTY_ORIG_SYSTEM_REFERENCE', 'ACCOUNT_NUMBER', 'INSERT_UPDATE_FLAG', 'CUSTOMER_TYPE',
       'CUSTOMER_CLASS_CODE', 'ACCOUNT_NAME', 'ACCOUNT_ESTABLISHED_DATE',
       'ATTRIBUTE_CATEGORY'] + rng('ATTRIBUTE', 1, 20) + ['ACCOUNT_TERMINATION_DATE']
MAPS['HZ_ACCOUNTS'] = ('HzImpAccountsT.csv', hza)

hzas = ['BATCH_ID', 'CUST_ORIG_SYSTEM', 'CUST_ORIG_SYSTEM_REFERENCE', 'CUST_SITE_ORIG_SYSTEM',
        'CUST_SITE_ORIG_SYS_REF', 'SITE_ORIG_SYSTEM', 'SITE_ORIG_SYSTEM_REFERENCE', 'ACCT_SITE_LANGUAGE',
        'INSERT_UPDATE_FLAG', 'CUSTOMER_CATEGORY_CODE', 'TRANSLATED_CUSTOMER_NAME', 'SET_CODE',
        'START_DATE', 'END_DATE', 'KEY_ACCOUNT_FLAG', 'ACCOUNT_NUMBER', 'PARTY_SITE_NUMBER',
        'ATTRIBUTE_CATEGORY'] + rng('ATTRIBUTE', 1, 20)
MAPS['HZ_ACCT_SITES'] = ('HzImpAcctSitesT.csv', hzas)

hzasu = ['BATCH_ID', 'CUST_SITE_ORIG_SYSTEM', 'CUST_SITE_ORIG_SYS_REF', 'CUST_SITEUSE_ORIG_SYSTEM',
         'CUST_SITEUSE_ORIG_SYS_REF', 'SITE_USE_CODE', 'PRIMARY_FLAG', 'INSERT_UPDATE_FLAG', 'LOCATION',
         'SET_CODE', 'START_DATE', 'END_DATE', 'ACCOUNT_NUMBER', 'PARTY_SITE_NUMBER',
         'ATTRIBUTE_CATEGORY'] + rng('ATTRIBUTE', 1, 20)
MAPS['HZ_ACCT_SITE_USES'] = ('HzImpAcctSiteUsesT.csv', hzasu)

# ---------------- Requisitions (3 files) ----------------
rqh = ['INTERFACE_HEADER_KEY', 'INTERFACE_SOURCE_CODE', 'REQ_BU_NAME', 'BATCH_ID',
       'INTERFACE_SOURCE_LINE_ID', 'DOCUMENT_STATUS', 'APPROVER_EMAIL_ADDR', 'PREPARER_EMAIL_ADDR',
       'PRC_BU_NAME', 'REQUISITION_NUMBER', 'DESCRIPTION', 'EMERGENCY_PO_NUMBER',
       'DEFAULT_TAXATION_COUNTRY', 'DEFAULT_TAXATION_TERRITORY', 'DOCUMENT_SUB_TYPE',
       'DOCUMENT_SUB_TYPE_NAME', 'JUSTIFICATION']
rqh += rng('ATTRIBUTE', 1, 20) + rng('ATTRIBUTE_DATE', 1, 10) + rng('ATTRIBUTE_TIMESTAMP', 1, 10) + rng('ATTRIBUTE_NUMBER', 1, 10)
rqh += ['ATTRIBUTE_CATEGORY', 'SOLDTO_LE_NAME', None]   # slot 70 = constant "N"
MAPS['POR_REQ_HEADERS'] = ('PorReqHeadersInterfaceAll.csv', rqh)

rql = ['INTERFACE_LINE_KEY', 'INTERFACE_HEADER_KEY', 'GROUP_CODE', 'DESTINATION_TYPE_CODE',
       'DELIVER_TO_LOCATION_CODE', 'DESTINATION_ORGANIZATION_CODE', 'DESTINATION_SUBINVENTORY',
       'REQUESTER_EMAIL_ADDR', 'ITEM_DESCRIPTION', 'CATEGORY_NAME', 'NEED_BY_DATE', 'ITEM_NUMBER',
       'ITEM_REVISION', 'UOM_CODE', 'LINE_TYPE', 'QUANTITY', 'CURRENCY_CODE', 'CURRENCY_UNIT_PRICE',
       'RATE', 'RATE_DATE', 'RATE_TYPE', 'SECONDARY_UOM_CODE', 'SECONDARY_QUANTITY', 'CURRENCY_AMOUNT',
       'UN_NUMBER', 'HAZARD_CLASS', 'PRC_BU_NAME', 'SOURCE_DOC_HEADER_NUMBER', 'SOURCE_DOC_LINE_NUMBER',
       'SUGGESTED_VENDOR_NAME', 'SUGGESTED_VENDOR_SITE', 'SUGGESTED_VENDOR_CONTACT',
       'SUGGESTED_VENDOR_CONTACT_PHONE', 'SUGGESTED_VENDOR_CONTACT_FAX', 'SUGGESTED_VENDOR_CONTACT_EMAIL',
       'SUGGESTED_SUPPLIER_ITEM_NUM', 'SUGGESTED_BUYER_EMAIL_ADDR', 'AUTOSOURCE_FLAG',
       'NEGOTIATED_BY_PREPARER_FLAG', 'NEGOTIATION_REQUIRED_FLAG', 'URGENT_FLAG', 'NEW_SUPPLIER_FLAG',
       'NOTE_TO_BUYER', 'NOTE_TO_RECEIVER', 'TRX_BUSINESS_CATEGORY', 'TRX_BUSINESS_CATEGORY_NAME',
       'PRODUCT_TYPE', 'PRODUCT_TYPE_NAME', 'PRODUCT_FISC_CLASSIFICATION', 'PRODUCT_FISC_CLASS_NAME',
       'PRODUCT_CATEGORY', 'PRODUCT_CATEGORY_NAME', 'LINE_INTENDED_USE', 'LINE_INTENDED_USE_NAME',
       'USER_DEFINED_FISC_CLASS', 'USER_DEFINED_FISC_CLASS_NAME', 'TAX_CLASSIFICATION_CODE',
       'TAX_CLASSIFICATION_NAME', 'ASSESSABLE_VALUE']
rql += rng('ATTRIBUTE', 1, 20) + rng('ATTRIBUTE_DATE', 1, 10) + rng('ATTRIBUTE_TIMESTAMP', 1, 10) + rng('ATTRIBUTE_NUMBER', 1, 10)
rql += ['ATTRIBUTE_CATEGORY', 'VENDOR_NUMBER', 'FIRST_PTY_REG_NUMBER', 'THIRD_PTY_REG_NUMBER',
        'FINAL_DISCHARGE_LOC_CODE', 'UNIT_OF_MEASURE', 'SECONDARY_UNIT_OF_MEASURE']
MAPS['POR_REQ_LINES'] = ('PorReqLinesInterfaceAll.csv', rql)

rqd = ['INTERFACE_DISTRIBUTION_KEY', 'INTERFACE_LINE_KEY', 'PERCENT', 'DISTRIBUTION_NUMBER',
       'DISTRIBUTION_QUANTITY', 'DISTRIBUTION_CURRENCY_AMOUNT', 'PJC_PROJECT_NAME', 'PJC_TASK_NAME',
       'PJC_EXPENDITURE_TYPE_NAME', 'PJC_EXPENDITURE_ITEM_DATE', 'PJC_ORGANIZATION_NAME',
       'PJC_BILLABLE_FLAG', 'PJC_CAPITALIZABLE_FLAG']
rqd += rng('PJC_RESERVED_ATTRIBUTE', 1, 10) + rng('PJC_USER_DEF_ATTRIBUTE', 1, 10)
rqd += rng('ATTRIBUTE', 1, 20) + rng('ATTRIBUTE_DATE', 1, 10) + rng('ATTRIBUTE_TIMESTAMP', 1, 10) + rng('ATTRIBUTE_NUMBER', 1, 10)
rqd += ['ATTRIBUTE_CATEGORY'] + rng('CHARGE_ACCOUNT_SEGMENT', 1, 30) + ['PJC_WORK_TYPE', 'BUDGET_DATE']
MAPS['POR_REQ_DISTS'] = ('PorReqDistsInterfaceAll.csv', rqd)

# ---------------- Projects (4 files) ----------------
pjp = ['PROJECT_NAME', 'PROJECT_NUMBER', 'SOURCE_TEMPLATE_NUMBER', 'SOURCE_APPLICATION_CODE',
       'SOURCE_PROJECT_REFERENCE', 'ORGANIZATION_NAME', 'LEGAL_ENTITY_NAME', 'DESCRIPTION',
       'PROJECT_MANAGER_NUMBER', 'PROJECT_MANAGER_NAME', 'PROJECT_MANAGER_EMAIL', 'PROJECT_START_DATE',
       'PROJECT_FINISH_DATE', 'CLOSED_DATE', 'PROJECT_STATUS_NAME', 'PROJECT_PRIORITY_CODE',
       'OUTLINE_DISPLAY_LEVEL', 'PLANNING_PROJECT_FLAG', 'SERVICE_TYPE_CODE', 'WORK_TYPE_NAME',
       'LIMIT_TO_TXN_CONTROLS_CODE', 'PROJECT_CURRENCY_CODE', 'CURRENCY_CONV_RATE_TYPE',
       'CURRENCY_CONV_DATE_TYPE_CODE', 'CURRENCY_CONV_DATE', 'CINT_ELIGIBLE_FLAG', 'CINT_RATE_SCH_NAME',
       'CINT_STOP_DATE', 'ASSET_ALLOCATION_METHOD_CODE', 'CAPITAL_EVENT_PROCESSING_CODE',
       'ALLOW_CROSS_CHARGE_FLAG', 'CC_PROCESS_LABOR_FLAG', 'LABOR_TP_SCHEDULE_NAME', 'LABOR_TP_FIXED_DATE',
       'CC_PROCESS_NL_FLAG', 'NL_TP_SCHEDULE_NAME', 'NL_TP_FIXED_DATE', 'BURDEN_SCHEDULE_NAME',
       'BURDEN_SCH_FIXED_DATED', 'KPI_NOTIFICATION_ENABLED', 'KPI_NOTIFICATION_RECIPIENTS',
       'KPI_NOTIFICATION_INCLUDE_NOTES', 'COPY_TEAM_MEMBERS_FLAG', 'COPY_PROJECT_CLASSES_FLAG',
       'COPY_ATTACHMENTS_FLAG', 'COPY_DFF_FLAG', 'COPY_GROUP_SPACE_FLAG', 'COPY_TASKS_FLAG',
       'COPY_TASK_ATTACHMENTS_FLAG', 'COPY_TASK_DFF_FLAG', 'COPY_TASK_ASSIGNMENTS_FLAG',
       'COPY_TRANSACTION_CONTROLS_FLAG', 'COPY_ASSETS_FLAG', 'COPY_ASSET_ASSIGNMENTS_FLAG',
       'COPY_COST_OVERRIDES_FLAG', 'ATTRIBUTE_CATEGORY']
pjp += rng('ATTRIBUTE', 1, 50)
pjp += [f'ATTRIBUTE{i}_NUMBER' for i in range(1, 16)]
pjp += [f'ATTRIBUTE{i}_DATE' for i in range(1, 16)]
pjp += ['SCHEDULE_NAME', 'EPS_NAME', 'PROJECT_PLAN_VIEW_ACCESS', 'SCHEDULE_TYPE', 'OPPORTUNITY_ID',
        'OPPORTUNITY_NUMBER', 'OPPORTUNITY_CUSTOMER_NUMBER', 'OPPORTUNITY_CUSTOMER_ID', 'OPPORTUNITY_AMT',
        'OPPORTUNITY_CURRCODE', 'OPPORTUNITY_WIN_CONF_PERCENT', 'OPPORTUNITY_NAME', 'OPPORTUNITY_DESC',
        'OPPORTUNITY_CUSTOMER_NAME', 'OPPORTUNITY_STATUS', 'PRJ_PLAN_BASELINE_NAME',
        'PRJ_PLAN_BASELINE_DESC', 'PRJ_PLAN_BASELINE_DATE', 'BUDGETARY_CONTROL_FLAG',
        'SOURCE_TEMPLATE_NAME', 'CASCADE_OPTION']
MAPS['PJF_PROJECTS'] = ('PjfProjectsAllXface.csv', pjp)

pjt = ['PROJECT_NAME', 'PROJECT_NUMBER', 'TASK_NAME', 'TASK_NUMBER', 'TASK_DESCRIPTION',
       'PARENT_TASK_NUMBER', 'PLANNING_START_DATE', 'PLANNING_END_DATE', 'MILESTONE_FLAG',
       'CRITICAL_FLAG', 'CHARGEABLE_FLAG', 'BILLABLE_FLAG', 'CAPITALIZABLE_FLAG',
       'LIMIT_TO_TXN_CONTROLS_FLAG', 'SOURCE_TASK_REFERENCE', 'SOURCE_APPLICATION_CODE',
       'SERVICE_TYPE_CODE', 'WORK_TYPE_ID', 'MANAGER_PERSON_ID', 'ALLOW_CROSS_CHARGE_FLAG',
       'CC_PROCESS_LABOR_FLAG', 'CC_PROCESS_NL_FLAG', 'RECEIVE_PROJECT_INVOICE_FLAG',
       'ATTRIBUTE_CATEGORY']
pjt += rng('ATTRIBUTE', 1, 50)
pjt += [f'ATTRIBUTE{i}_NUMBER' for i in range(1, 16)]
pjt += [f'ATTRIBUTE{i}_DATE' for i in range(1, 16)]
pjt += ['ORGANIZATION_NAME', 'FINANCIAL_TASK', 'PLANNED_EFFORT', 'PLANNED_DURATION', 'REQMNT_CODE',
        'SPRINT', 'PRIORITY', 'SCHEDULE_MODE', 'BASELINE_START_DATE', 'BASELINE_FINISH_DATE',
        'BASELINE_EFFORT', 'BASELINE_DURATION', 'BASELINE_ALLOCATION', 'CONSTRAINT_TYPE',
        'CONSTRAINT_DATE', 'BASELINE_LABOR_COST_AMOUNT', 'BASELINE_LABOR_BILLED_AMOUNT',
        'BASELINE_EXPENSE_COST_AMOUNT']
MAPS['PJF_TASKS'] = ('PjfProjElementsXface.csv', pjt)

pjtm = ['PROJECT_NAME', 'TEAM_MEMBER_NUMBER', 'TEAM_MEMBER_NAME', 'TEAM_MEMBER_EMAIL',
        'PROJECT_ROLE_NAME', 'START_DATE_ACTIVE', 'END_DATE_ACTIVE', 'TRACK_TIME_FLAG', 'ALLOCATION',
        'EFFORT', 'COST_RATE', 'BILL_RATE', 'ASSIGNMENT_TYPE', 'BILLABLE_PERCENT',
        'BILLABLE_PERCENT_REASON_CODE']
MAPS['PJF_TEAM_MEMBERS'] = ('PjfProjectPartiesInt.csv', pjtm)

pjtc = ['TXN_CTRL_REFERENCE', 'PROJECT_NAME', 'PROJECT_NUMBER', 'TASK_NUMBER', 'TASK_NAME',
        'EXPENDITURE_CATEGORY_NAME', 'EXPENDITURE_TYPE', 'NON_LABOR_RESOURCE', 'PERSON_NUMBER',
        'PERSON_NAME', 'PERSON_EMAILID', 'PERSON_TYPE', 'JOB_NAME', 'ORGANIZATION_NAME',
        'CHARGEABLE_FLAG', 'BILLABLE_FLAG', 'CAPITALIZABLE_FLAG', 'START_DATE_ACTIVE', 'END_DATE_ACTIVE']
MAPS['PJC_TXN_CONTROLS'] = ('PjcTxnControlsStage.csv', pjtc)

# ---------------- Project Budgets ----------------
prjb = ['AWARD_NUMBER', 'FINANCIAL_PLAN_TYPE', 'PROJECT_NUMBER', 'PROJECT_NAME', 'TASK_NAME',
        'TASK_NUMBER', 'PLAN_VERSION_NAME', 'PLAN_VERSION_DESCRIPTION', 'PLAN_VERSION_STATUS',
        'RESOURCE_NAME', 'PERIOD_NAME', 'PLANNING_CURRENCY', 'TOTAL_QUANTITY', 'TOTAL_TC_RAW_COST',
        'TOTAL_TC_REVENUE', 'SRC_BUDGET_LINE_REFERENCE', 'FUNDING_SOURCE_NUMBER', 'FUNDING_SOURCE_NAME',
        'PC_RAW_COST', 'PC_REVENUE', 'PFC_RAW_COST', 'PFC_REVENUE', 'TOTAL_TC_BRDND_COST',
        'PC_BRDND_COST', 'PFC_BRDND_COST', 'LINE_TYPE', 'PLANNING_START_DATE', 'PLANNING_END_DATE',
        None, 'ATTRIBUTE_CATEGORY'] + rng('ATTRIBUTE', 1, 30) + ['PLAN_VERSION_NUMBER', 'PROCESSING_MODE']
MAPS['PRJ_BUDGET'] = ('PjoPlanVersionsXface.csv', prjb)

# ---------------- Items ----------------
it = [None] * 399
_itm = {1: 'TRANSACTION_TYPE', 2: 'BATCH_ID', 3: 'BATCH_NUMBER', 4: 'ITEM_NUMBER', 6: 'ORGANIZATION_CODE',
        7: 'DESCRIPTION', 8: 'TEMPLATE_NAME', 9: 'SOURCE_SYSTEM_CODE', 10: 'SOURCE_SYSTEM_REFERENCE',
        13: 'PRIMARY_UOM_CODE', 14: 'CURRENT_PHASE_CODE', 15: 'INVENTORY_ITEM_STATUS_CODE',
        16: 'ITEM_CLASS_NAME', 27: 'COSTING_ENABLED_FLAG', 29: 'INVENTORY_ASSET_FLAG',
        38: 'FIXED_DAYS_SUPPLY', 39: 'FIXED_LOT_MULTIPLIER', 40: 'FIXED_ORDER_QUANTITY',
        42: 'INVENTORY_PLANNING_CODE', 46: 'MIN_MINMAX_QUANTITY', 47: 'MAX_MINMAX_QUANTITY',
        48: 'MINIMUM_ORDER_QUANTITY', 49: 'MAXIMUM_ORDER_QUANTITY', 50: 'PLANNER_CODE',
        51: 'PLANNING_MAKE_BUY_CODE', 60: 'RESTRICT_SUBINVENTORIES_CODE', 61: 'RESTRICT_LOCATORS_CODE',
        62: 'CHILD_LOT_FLAG', 69: 'STOCK_ENABLED_FLAG', 71: 'SHELF_LIFE_CODE', 72: 'SHELF_LIFE_DAYS',
        73: 'SERIAL_NUMBER_CONTROL_CODE', 75: 'REVISION_QTY_CONTROL_CODE', 80: 'CHECK_SHORTAGES_FLAG',
        81: 'CYCLE_COUNT_ENABLED_FLAG', 83: 'GRADE_CONTROL_FLAG', 85: 'LOT_DIVISIBLE_FLAG',
        91: 'INVENTORY_ITEM_FLAG', 92: 'LOCATION_CONTROL_CODE', 93: 'LOT_CONTROL_CODE',
        97: 'MTL_TRANSACTIONS_ENABLED_FLAG', 101: 'RESERVABLE_TYPE', 103: 'INVOICING_RULE_NAME',
        104: 'TAX_CODE', 105: 'SALES_ACCOUNT', 106: 'PAYMENT_TERMS_NAME', 107: 'INVOICE_ENABLED_FLAG',
        108: 'INVOICEABLE_ITEM_FLAG', 109: 'ACCOUNTING_RULE_NAME', 119: 'CUM_MANUFACTURING_LEAD_TIME',
        120: 'PREPROCESSING_LEAD_TIME', 121: 'CUMULATIVE_TOTAL_LEAD_TIME', 122: 'FIXED_LEAD_TIME',
        123: 'VARIABLE_LEAD_TIME', 124: 'FULL_LEAD_TIME', 125: 'LEAD_TIME_LOT_SIZE',
        126: 'POSTPROCESSING_LEAD_TIME', 141: 'MRP_PLANNING_CODE', 152: 'SHRINKAGE_RATE',
        157: 'DUAL_UOM_DEVIATION_HIGH', 158: 'DUAL_UOM_DEVIATION_LOW', 159: 'ITEM_TYPE',
        160: 'LONG_DESCRIPTION', 164: 'SECONDARY_UOM_CODE', 168: 'ATP_FLAG', 169: 'OVER_SHIPMENT_TOLERANCE',
        170: 'UNDER_SHIPMENT_TOLERANCE', 171: 'OVER_RETURN_TOLERANCE', 172: 'UNDER_RETURN_TOLERANCE',
        175: 'INDIVISIBLE_FLAG', 176: 'INTERNAL_ORDER_ENABLED_FLAG', 179: 'CUSTOMER_ORDER_ENABLED_FLAG',
        180: 'DEFAULT_SHIPPING_ORG', 184: 'INTERNAL_ORDER_FLAG', 185: 'PICKING_RULE_NAME',
        186: 'RETURNABLE_FLAG', 190: 'SHIPPABLE_ITEM_FLAG', 193: 'CUSTOMER_ORDER_FLAG', 194: 'UNIT_WEIGHT',
        195: 'WEIGHT_UOM_CODE', 196: 'UNIT_VOLUME', 197: 'VOLUME_UOM_CODE', 198: 'DIMENSION_UOM_CODE',
        199: 'UNIT_LENGTH', 200: 'UNIT_WIDTH', 201: 'UNIT_HEIGHT', 221: 'EXPENSE_ACCOUNT',
        222: 'UN_NUMBER_CODE', 225: 'RECEIVE_CLOSE_TOLERANCE', 226: 'PURCHASING_TAX_CODE',
        227: 'PURCHASING_ITEM_FLAG', 228: 'PRICE_TOLERANCE_PERCENT', 232: 'MUST_USE_APPROVED_VENDOR_FLAG',
        233: 'MATCH_APPROVAL_LEVEL', 234: 'INVOICE_MATCH_OPTION', 235: 'LIST_PRICE_PER_UNIT',
        236: 'INVOICE_CLOSE_TOLERANCE', 237: 'HAZARD_CLASS_CODE', 238: 'BUYER_NAME',
        240: 'PURCHASING_ENABLED_FLAG', 241: 'OUTSIDE_OPERATION_FLAG', 242: 'MARKET_PRICE',
        243: 'ASSET_CATEGORY_ID', 244: 'ALLOW_ITEM_DESC_UPDATE_FLAG', 246: 'ALLOW_SUBSTITUTE_RECEIPTS_FLAG',
        247: 'ALLOW_UNORDERED_RECEIPTS_FLAG', 248: 'DAYS_EARLY_RECEIPT_ALLOWED',
        249: 'DAYS_LATE_RECEIPT_ALLOWED', 250: 'RECEIVING_ROUTING_ID', 251: 'ENFORCE_SHIP_TO_LOCATION_CODE',
        252: 'QTY_RCV_EXCEPTION_CODE', 253: 'QTY_RCV_TOLERANCE', 254: 'RECEIPT_DAYS_EXCEPTION_CODE',
        259: 'CONTRACT_ITEM_TYPE_CODE', 265: 'SERVICEABLE_PRODUCT_FLAG', 267: 'SERVICE_DURATION',
        268: 'SERVICE_DURATION_PERIOD_CODE', 279: 'BACK_ORDERABLE_FLAG', 282: 'BUILD_IN_WIP_FLAG',
        285: 'WIP_SUPPLY_TYPE', 286: 'WIP_SUPPLY_SUBINVENTORY', 292: 'STYLE_ITEM_FLAG',
        299: 'GLOBAL_ATTRIBUTE_CATEGORY', 310: 'ATTRIBUTE_CATEGORY'}
for i in range(1, 11):
    _itm[299 + i] = f'GLOBAL_ATTRIBUTE{i}'       # 300..309
for i in range(1, 16):
    _itm[310 + i] = f'ATTRIBUTE{i}'              # 311..325
for i in range(1, 6):
    _itm[340 + i] = f'ATTRIBUTE_NUMBER{i}'       # 341..345
for i in range(1, 6):
    _itm[350 + i] = f'ATTRIBUTE_DATE{i}'         # 351..355
for i in range(11, 21):
    _itm[360 + (i - 10)] = f'GLOBAL_ATTRIBUTE{i}'  # 361..370
for k, v in _itm.items():
    it[k - 1] = v
MAPS['EGP_ITEM'] = ('EgpSystemItemsInterface.csv', it)

itc = ['TRANSACTION_TYPE', 'BATCH_ID', 'BATCH_NUMBER', 'ITEM_NUMBER', 'ORGANIZATION_CODE',
       'CATEGORY_SET_NAME', 'CATEGORY_NAME', 'CATEGORY_CODE', 'OLD_CATEGORY_NAME', 'OLD_CATEGORY_CODE',
       'SOURCE_SYSTEM_CODE', 'SOURCE_SYSTEM_REFERENCE', None, None]
MAPS['EGP_ITEM_CAT'] = ('EgpItemCategoriesInterface.csv', itc)

# ---------------- Grants (headers + personnel used by regression) ----------------
gh = ['AWARD_NAME', 'AWARD_NUMBER', 'SOURCE_TEMPLATE_NUMBER', 'BUSINESS_UNIT', 'LEGAL_ENTITY',
      'CONTRACT_TYPE', 'PRIMARY_SPONSOR', 'PRINCIPAL_INVESTIGATOR_EMAIL', 'PI_NAME', 'PI_NUMBER',
      'AWARD_START_DATE', 'AWARD_END_DATE', 'AWARD_DESCRIPTION', 'ORGANIZATION', 'INSTITUTION',
      'SPONSOR_AWARD_NUMBER', 'AWARD_PURPOSE', 'AWARD_TYPE', 'EXPANDED_AUTHORITY_FLAG', 'COST_SHARE',
      'DEFAULT_BURDEN_SCHEDULE', 'FIXED_DATE', 'PRE_AWARD_DATE', 'PRE_AWARD_SPENDING_ALLOWED',
      'PRE_AWARD_GSF', 'CLOSE_DATE', 'COI_INST_POLICY_COMPLIANT', 'COI_REVIEW_COMPLETED',
      'COI_APPROVAL_DATE', 'FT_PRIMARY_SPONSOR', 'FT_REF_AWARD_NAME', 'FT_FROM_DATE', 'FT_TO_DATE',
      'FT_AMOUNT', 'FT_IS_FEDERAL', 'IS_INTELL_PROP_REPORTED', 'INTELL_PROP_DESC', 'PREV_AWARD_BU',
      'PREV_AWARD_NAME', 'PREV_AWARD_RENEWAL_INPRG', 'PREV_AWARD_ABR', 'COST_SHARE_REQ_BY_SPONSOR',
      'COST_SHARE_APPROVED_BY', 'COST_SHARE_APPROVAL_DATE', 'ATTRIBUTE_CATEGORY']
gh += rng('ATTRIBUTE', 1, 20) + rng('ATTRIBUTE_NUMBER', 1, 10) + rng('ATTRIBUTE_DATE', 1, 10) + rng('ATTRIBUTE_TIMESTAMP', 1, 10)
gh += ['CONTRACT_STATUS', 'CONTRACT_LINE_NAME', 'LOC_FLAG', 'DOC_NUMBER', 'FED_INVOICE_FORMAT',
       'BILL_PLAN_NAME', 'REVENUE_PLAN_NAME', 'INVOICE_METHOD', 'REVENUE_METHOD', 'BILLING_CYCLE',
       'PAYMENT_TERM', 'LABOR_FORMAT', 'NON_LABOR_FORMAT', 'EVENT_FORMAT', 'CURRENCY_CODE',
       'PRIMARY_SPONSOR_NUMBER', 'FT_PRIMARY_SPONSOR_NUMBER', 'NET_INVOICE_FLAG',
       'INV_HDR_GROUPING_OPTIONS', 'BILL_TO_SITE_LOCATION', 'BILL_TO_CONTACT_NAME',
       'BILL_TO_CONTACT_EMAIL', 'SHIP_TO_SITE_LOCATION', 'BILL_SET_NUMBER', 'GENERATED_INVOICE_STATUS',
       'INV_TRX_TYPE_NAME', 'BILL_TO_ACCT_NUMBER', 'SHIP_TO_ACCT_NUMBER', 'PREPAY_TRX_TYPE_NAME']
MAPS['GMS_AWD_HEADERS'] = ('GmsAwardHeadersInterface.csv', gh)

gp = ['AWARD_NUMBER', 'PROJECT_NUMBER', 'INTERNAL', 'PERSON_EMAIL', 'PERSON_NAME', 'PERSON_NUMBER',
      'ROLE', 'START_DATE', 'END_DATE', 'CREDIT_PERCENTAGE', 'ATTRIBUTE_CATEGORY']
gp += rng('ATTRIBUTE', 1, 20) + rng('ATTRIBUTE_NUMBER', 1, 10) + rng('ATTRIBUTE_DATE', 1, 10) + rng('ATTRIBUTE_TIMESTAMP', 1, 10)
MAPS['GMS_AWD_PERSONNEL'] = ('GmsAwardPersonnelInterface.csv', gp)

# ---------------- AP Invoices (slot 1 = synthetic INVOICE_ID key, dropped) ----------------
api = [None, 'OPERATING_UNIT', 'SOURCE', 'INVOICE_NUM', 'INVOICE_AMOUNT', 'INVOICE_DATE', 'VENDOR_NAME',
       'VENDOR_NUM', 'VENDOR_SITE_CODE', 'INVOICE_CURRENCY_CODE', 'PAYMENT_CURRENCY_CODE', 'DESCRIPTION',
       'GROUP_ID', 'INVOICE_TYPE_LOOKUP_CODE', 'LEGAL_ENTITY_NAME', 'CUST_REGISTRATION_NUMBER',
       'CUST_REGISTRATION_CODE', 'FIRST_PARTY_REGISTRATION_NUM', 'THIRD_PARTY_REGISTRATION_NUM',
       'TERMS_NAME', 'TERMS_DATE', 'GOODS_RECEIVED_DATE', 'INVOICE_RECEIVED_DATE', 'GL_DATE',
       'PAYMENT_METHOD_CODE', 'PAY_GROUP_LOOKUP_CODE', 'EXCLUSIVE_PAYMENT_FLAG',
       'AMOUNT_APPLICABLE_TO_DISCOUNT', 'PREPAY_NUM', 'PREPAY_LINE_NUM', 'PREPAY_APPLY_AMOUNT',
       'PREPAY_GL_DATE', 'INVOICE_INCLUDES_PREPAY_FLAG', 'EXCHANGE_RATE_TYPE', 'EXCHANGE_DATE',
       'EXCHANGE_RATE', 'ACCTS_PAY_CODE_CONCATENATED', 'DOC_CATEGORY_CODE', 'VOUCHER_NUM',
       'REQUESTER_FIRST_NAME', 'REQUESTER_LAST_NAME', 'REQUESTER_EMPLOYEE_NUM', 'DELIVERY_CHANNEL_CODE',
       'BANK_CHARGE_BEARER', 'REMIT_TO_SUPPLIER_NAME', 'REMIT_TO_SUPPLIER_NUM', 'REMIT_TO_ADDRESS_NAME',
       'PAYMENT_PRIORITY', 'SETTLEMENT_PRIORITY', 'UNIQUE_REMITTANCE_IDENTIFIER', 'URI_CHECK_DIGIT',
       'PAYMENT_REASON_CODE', 'PAYMENT_REASON_COMMENTS', 'REMITTANCE_MESSAGE1', 'REMITTANCE_MESSAGE2',
       'REMITTANCE_MESSAGE3', 'AWT_GROUP_NAME', 'SHIP_TO_LOCATION', 'TAXATION_COUNTRY',
       'DOCUMENT_SUB_TYPE', 'TAX_INVOICE_INTERNAL_SEQ', 'SUPPLIER_TAX_INVOICE_NUMBER',
       'TAX_INVOICE_RECORDING_DATE', 'SUPPLIER_TAX_INVOICE_DATE', 'SUPPLIER_TAX_EXCHANGE_RATE',
       'PORT_OF_ENTRY_CODE', 'CORRECTION_YEAR', 'CORRECTION_PERIOD', 'IMPORT_DOCUMENT_NUMBER',
       'IMPORT_DOCUMENT_DATE', 'CONTROL_AMOUNT', 'CALC_TAX_DURING_IMPORT_FLAG', 'ADD_TAX_TO_INV_AMT_FLAG',
       'ATTRIBUTE_CATEGORY']
api += rng('ATTRIBUTE', 1, 15) + rng('ATTRIBUTE_NUMBER', 1, 5) + rng('ATTRIBUTE_DATE', 1, 5)
api += ['GLOBAL_ATTRIBUTE_CATEGORY'] + rng('GLOBAL_ATTRIBUTE', 1, 20) + rng('GLOBAL_ATTRIBUTE_NUMBER', 1, 5) + rng('GLOBAL_ATTRIBUTE_DATE', 1, 5)
api += ['IMAGE_DOCUMENT_URI', 'EXTERNAL_BANK_ACCOUNT_NUMBER', 'EXT_BANK_ACCOUNT_IBAN_NUMBER',
        'REQUESTER_EMAIL_ADDRESS', 'INTERCOMPANY_CROSSCHARGE_FLAG']
MAPS['AP_INVOICES_INT'] = ('ApInvoicesInterface.csv', api)

apl = [None, 'LINE_NUMBER', 'LINE_TYPE_LOOKUP_CODE', 'AMOUNT', 'QUANTITY_INVOICED', 'UNIT_PRICE',
       'UNIT_OF_MEAS_LOOKUP_CODE', 'DESCRIPTION', 'PO_NUMBER', 'PO_LINE_NUMBER', 'PO_SHIPMENT_NUM',
       'PO_DISTRIBUTION_NUM', 'ITEM_DESCRIPTION', 'RELEASE_NUM', 'PURCHASING_CATEGORY', 'RECEIPT_NUMBER',
       'RECEIPT_LINE_NUMBER', 'CONSUMPTION_ADVICE_NUMBER', 'CONSUMPTION_ADVICE_LINE_NUMBER',
       'PACKING_SLIP', 'FINAL_MATCH_FLAG', 'DIST_CODE_CONCATENATED', 'DISTRIBUTION_SET_NAME',
       'ACCOUNTING_DATE', 'ACCOUNT_SEGMENT', 'BALANCING_SEGMENT', 'COST_CENTER_SEGMENT',
       'TAX_CLASSIFICATION_CODE', 'SHIP_TO_LOCATION_CODE', 'SHIP_FROM_LOCATION_CODE',
       'FINAL_DISCHARGE_LOCATION_CODE', 'TRX_BUSINESS_CATEGORY', 'PRODUCT_FISC_CLASSIFICATION',
       'PRIMARY_INTENDED_USE', 'USER_DEFINED_FISC_CLASS', 'PRODUCT_TYPE', 'ASSESSABLE_VALUE',
       'PRODUCT_CATEGORY', 'CONTROL_AMOUNT', 'TAX_REGIME_CODE', 'TAX', 'TAX_STATUS_CODE',
       'TAX_JURISDICTION_CODE', 'TAX_RATE_CODE', 'TAX_RATE', 'AWT_GROUP_NAME', 'TYPE_1099',
       'INCOME_TAX_REGION', 'PRORATE_ACROSS_FLAG', 'LINE_GROUP_NUMBER', 'COST_FACTOR_NAME', 'STAT_AMOUNT',
       'ASSETS_TRACKING_FLAG', 'ASSET_BOOK_TYPE_CODE', 'ASSET_CATEGORY_ID', 'SERIAL_NUMBER',
       'MANUFACTURER', 'MODEL_NUMBER', 'WARRANTY_NUMBER', 'PRICE_CORRECTION_FLAG', 'PRICE_CORRECT_INV_NUM',
       'PRICE_CORRECT_INV_LINE_NUM', 'REQUESTER_FIRST_NAME', 'REQUESTER_LAST_NAME',
       'REQUESTER_EMPLOYEE_NUM', 'ATTRIBUTE_CATEGORY']
apl += rng('ATTRIBUTE', 1, 15) + rng('ATTRIBUTE_NUMBER', 1, 5) + rng('ATTRIBUTE_DATE', 1, 5)
apl += ['GLOBAL_ATTRIBUTE_CATEGORY'] + rng('GLOBAL_ATTRIBUTE', 1, 20) + rng('GLOBAL_ATTRIBUTE_NUMBER', 1, 5) + rng('GLOBAL_ATTRIBUTE_DATE', 1, 5)
apl += ['PJC_PROJECT_ID', 'PJC_TASK_ID', 'PJC_EXPENDITURE_TYPE_ID', 'PJC_EXPENDITURE_ITEM_DATE',
        'PJC_ORGANIZATION_ID', 'PJC_PROJECT_NUMBER', 'PJC_TASK_NUMBER', 'PJC_EXPENDITURE_TYPE_NAME',
        'PJC_ORGANIZATION_NAME']
apl += rng('PJC_RESERVED_ATTRIBUTE', 1, 10) + rng('PJC_USER_DEF_ATTRIBUTE', 1, 10)
apl += ['FISCAL_CHARGE_TYPE', 'DEF_ACCTG_START_DATE', 'DEF_ACCTG_END_DATE',
        'DEF_ACCRUAL_CODE_CONCATENATED', 'PJC_PROJECT_NAME', 'PJC_TASK_NAME', 'PJC_WORK_TYPE',
        'PJC_CONTRACT_NAME', 'PJC_CONTRACT_NUMBER', 'PJC_FUNDING_SOURCE_NAME', 'PJC_FUNDING_SOURCE_NUMBER',
        'REQUESTER_EMAIL_ADDRESS', 'RCV_TRANSACTION_ID']
MAPS['AP_INVOICE_LINES_INT'] = ('ApInvoiceLinesInterface.csv', apl)

# ---------------- AR Invoices (RaInterfaceLinesAll.csv) ----------------
ar = [None] * 373
_ar = {1: 'ORG_ID', 2: 'BATCH_SOURCE_NAME', 3: 'CUST_TRX_TYPE_NAME', 4: 'TERM_NAME', 5: 'TRX_DATE',
       6: 'GL_DATE', 7: 'TRX_NUMBER', 8: 'ORIG_SYSTEM_BILL_CUSTOMER_REF', 9: 'ORIG_SYSTEM_BILL_ADDRESS_REF',
       10: 'ORIG_SYSTEM_BILL_CONTACT_REF', 11: 'ORIG_SYS_SHIP_PARTY_REF', 12: 'ORIG_SYS_SHIP_PARTY_SITE_REF',
       13: 'ORIG_SYS_SHIP_PTY_CONTACT_REF', 14: 'ORIG_SYSTEM_SHIP_CUSTOMER_REF',
       15: 'ORIG_SYSTEM_SHIP_ADDRESS_REF', 16: 'ORIG_SYSTEM_SHIP_CONTACT_REF', 17: 'ORIG_SYS_SOLD_PARTY_REF',
       18: 'ORIG_SYSTEM_SOLD_CUSTOMER_REF', 19: 'BILL_CUSTOMER_ACCOUNT_NUMBER',
       20: 'BILL_CUSTOMER_SITE_NUMBER', 21: 'BILL_CONTACT_PARTY_NUMBER', 22: 'SHIP_CUSTOMER_ACCOUNT_NUMBER',
       23: 'SHIP_CUSTOMER_SITE_NUMBER', 24: 'SHIP_CONTACT_PARTY_NUMBER', 25: 'SOLD_CUSTOMER_ACCOUNT_NUMBER',
       26: 'LINE_TYPE', 27: 'DESCRIPTION', 28: 'CURRENCY_CODE', 29: 'CONVERSION_TYPE', 30: 'CONVERSION_DATE',
       31: 'CONVERSION_RATE', 32: 'AMOUNT', 33: 'QUANTITY', 34: 'QUANTITY_ORDERED',
       35: 'UNIT_SELLING_PRICE', 36: 'UNIT_STANDARD_PRICE', 37: 'INTERFACE_LINE_CONTEXT',
       53: 'PRIMARY_SALESREP_NUMBER', 54: 'TAX_CODE', 55: 'LEGAL_ENTITY_IDENTIFIER', 56: 'ACCTD_AMOUNT',
       57: 'SALES_ORDER', 58: 'SALES_ORDER_DATE', 59: 'SHIP_DATE_ACTUAL', 60: 'WAREHOUSE_CODE',
       61: 'UOM_CODE', 62: 'UOM_NAME', 63: 'INVOICING_RULE_NAME', 64: 'ACCOUNTING_RULE_NAME',
       65: 'ACCOUNTING_RULE_DURATION', 66: 'RULE_START_DATE', 67: 'RULE_END_DATE', 68: 'REASON_CODE_MEANING',
       69: 'LAST_PERIOD_TO_CREDIT', 70: 'TRX_BUSINESS_CATEGORY', 71: 'PRODUCT_FISC_CLASSIFICATION',
       72: 'PRODUCT_CATEGORY', 73: 'PRODUCT_TYPE', 74: 'LINE_INTENDED_USE', 75: 'ASSESSABLE_VALUE',
       76: 'DOCUMENT_SUB_TYPE', 77: 'DEFAULT_TAXATION_COUNTRY', 78: 'USER_DEFINED_FISC_CLASS',
       79: 'TAX_INVOICE_NUMBER', 80: 'TAX_INVOICE_DATE', 81: 'TAX_REGIME_CODE', 82: 'TAX',
       83: 'TAX_STATUS_CODE', 84: 'TAX_RATE_CODE', 85: 'TAX_JURISDICTION_CODE', 86: 'FIRST_PTY_REG_NUM',
       87: 'THIRD_PTY_REG_NUM', 88: 'FINAL_DISCHARGE_LOCATION_CODE', 89: 'TAXABLE_AMOUNT', 90: 'TAXABLE_FLAG',
       91: 'TAX_EXEMPT_FLAG', 92: 'TAX_EXEMPT_REASON_CODE', 93: 'TAX_EXEMPT_REASON_CODE_MEANING',
       94: 'TAX_EXEMPT_NUMBER', 95: 'AMOUNT_INCLUDES_TAX_FLAG', 96: 'TAX_PRECEDENCE',
       97: 'CREDIT_METHOD_FOR_ACCT_RULE', 98: 'CREDIT_METHOD_FOR_INSTALLMENTS', 99: 'REASON_CODE',
       100: 'TAX_RATE', 101: 'FOB_POINT', 102: 'SHIP_VIA', 103: 'WAYBILL_NUMBER', 104: 'SALES_ORDER_LINE',
       105: 'SALES_ORDER_SOURCE', 106: 'SALES_ORDER_REVISION', 107: 'PURCHASE_ORDER',
       108: 'PURCHASE_ORDER_REVISION', 109: 'PURCHASE_ORDER_DATE', 110: 'AGREEMENT_NAME',
       111: 'MEMO_LINE_NAME', 112: 'DOCUMENT_NUMBER', 113: 'ORIG_SYSTEM_BATCH_NAME',
       114: 'LINK_TO_LINE_CONTEXT', 162: 'RECEIPT_METHOD_NAME', 163: 'PRINTING_OPTION',
       164: 'RELATED_BATCH_SOURCE_NAME', 165: 'RELATED_TRX_NUMBER', 192: 'TRANSLATED_DESCRIPTION',
       193: 'CONS_BILLING_NUMBER', 194: 'PROMISED_COMMITMENT_AMOUNT', 195: 'PAYMENT_SET_ID',
       196: 'ORIGINAL_GL_DATE', 197: 'INVOICED_LINE_ACCTG_LEVEL', 198: 'OVERRIDE_AUTO_ACCOUNTING_FLAG',
       199: 'HISTORICAL_FLAG', 200: 'DEFERRAL_EXCLUSION_FLAG', 202: 'BILLING_DATE', 203: 'ATTRIBUTE_CATEGORY',
       219: 'HEADER_ATTRIBUTE_CATEGORY', 287: 'BU_NAME', 288: 'COMMENTS', 289: 'INTERNAL_NOTES'}
for i in range(1, 16):
    _ar[37 + i] = f'INTERFACE_LINE_ATTRIBUTE{i}'   # 38..52
for i in range(1, 7):
    _ar[114 + i] = f'LINK_TO_LINE_ATTRIBUTE{i}'    # 115..120
for i in range(1, 16):
    _ar[203 + i] = f'ATTRIBUTE{i}'                 # 204..218
for i in range(1, 16):
    _ar[219 + i] = f'HEADER_ATTRIBUTE{i}'          # 220..234
for k, v in _ar.items():
    ar[k - 1] = v
MAPS['RA_LINES'] = ('RaInterfaceLinesAll.csv', ar)

# ---------------- Billing Events ----------------
be = ['SOURCENAME', 'SOURCEREF', 'ORGANIZATION_NAME', 'CONTRACT_TYPE_NAME', 'CONTRACT_NUMBER',
      'CONTRACT_LINE_NUMBER', 'EVENT_TYPE_NAME', 'EVENT_DESC', 'COMPLETION_DATE',
      'BILL_TRNS_CURRENCY_CODE', 'BILL_TRNS_AMOUNT', 'PROJECT_NUMBER', 'TASK_NUMBER', 'BILL_HOLD_FLAG',
      'REVENUE_HOLD_FLAG', 'ATTRIBUTE_CATEGORY']
be += rng('ATTRIBUTE', 1, 10) + rng('ATTRIBUTE_CHAR', 11, 30) + rng('ATTRIBUTE_NUMBER', 1, 10) + rng('ATTRIBUTE_DATE', 1, 10) + rng('ATTRIBUTE_TIMESTAMP', 1, 5)
be += ['REVERSE_ACCRUAL_FLAG', 'ITEM_EVENT_FLAG', 'QUANTITY', 'ITEM_NUMBER', 'UNIT_OF_MEASURE',
       'UNIT_PRICE', 'PREPAYMENT_REQ_EVENT_NUM']
MAPS['PJB_BILL_EVENTS'] = ('PjbBillingEventsXface.csv', be)

# ---------------- Expenditures ----------------
exp = ['TRANSACTION_TYPE', 'BUSINESS_UNIT', 'ORG_ID', 'USER_TRANSACTION_SOURCE', 'TRANSACTION_SOURCE_ID',
       'DOCUMENT_NAME', 'DOCUMENT_ID', 'DOC_ENTRY_NAME', 'DOC_ENTRY_ID', 'BATCH_NAME',
       'BATCH_ENDING_DATE', 'BATCH_DESCRIPTION', 'EXPENDITURE_ITEM_DATE', 'PERSON_NUMBER', 'PERSON_NAME',
       'PERSON_ID', 'HCM_ASSIGNMENT_NAME', 'HCM_ASSIGNMENT_ID', 'PROJECT_NUMBER', 'PROJECT_NAME',
       'PROJECT_ID', 'TASK_NUMBER', 'TASK_NAME', 'TASK_ID', 'EXPENDITURE_TYPE', 'EXPENDITURE_TYPE_ID',
       'ORGANIZATION_NAME', 'ORGANIZATION_ID', 'QUANTITY', 'UNIT_OF_MEASURE_NAME', 'UNIT_OF_MEASURE',
       'WORK_TYPE', 'WORK_TYPE_ID', 'BILLABLE_FLAG', 'CAPITALIZABLE_FLAG', 'ORIG_TRANSACTION_REFERENCE',
       'UNMATCHED_NEGATIVE_TXN_FLAG', 'REVERSED_ORIG_TXN_REFERENCE', 'EXPENDITURE_COMMENT', 'GL_DATE',
       'DENOM_CURRENCY_CODE', 'DENOM_CURRENCY', 'DENOM_RAW_COST', 'DENOM_BURDENED_COST',
       'RAW_COST_CR_CCID', 'RAW_COST_CR_ACCOUNT', 'RAW_COST_DR_CCID', 'RAW_COST_DR_ACCOUNT',
       'BURDENED_COST_CR_CCID', 'BURDENED_COST_CR_ACCOUNT', 'BURDENED_COST_DR_CCID',
       'BURDENED_COST_DR_ACCOUNT', 'BURDEN_COST_CR_CCID', 'BURDEN_COST_CR_ACCOUNT', 'BURDEN_COST_DR_CCID',
       'BURDEN_COST_DR_ACCOUNT', 'ACCT_CURRENCY_CODE', 'ACCT_CURRENCY', 'ACCT_RAW_COST',
       'ACCT_BURDENED_COST', 'ACCT_RATE_TYPE', 'ACCT_RATE_DATE', 'ACCT_RATE_DATE_TYPE',
       'ACCT_EXCHANGE_RATE', 'ACCT_EXCHANGE_ROUNDING_LIMIT', 'CONVERTED_FLAG', 'CONTEXT_CATEGORY']
exp += rng('USER_DEF_ATTRIBUTE', 1, 10) + rng('RESERVED_ATTRIBUTE', 1, 10)
exp += ['ATTRIBUTE_CATEGORY'] + rng('ATTRIBUTE', 1, 10)
exp += ['CONTRACT_NUMBER', 'CONTRACT_NAME', 'CONTRACT_ID', 'FUNDING_SOURCE_NUMBER', 'FUNDING_SOURCE_NAME',
        None, None]
MAPS['PJC_EXPENDITURES'] = ('PjcTxnXfaceStageAll.csv', exp)


if __name__ == '__main__':
    for oc, (fn, cols) in sorted(MAPS.items()):
        print(f"{oc:22} {fn:35} positions={len(cols)}")
