-- ============================================================================
-- db_full/install.sql — COMPLETE DMT_OWNER schema install, generated from the
-- live ATP (queryapp) schema on 2026-07-03 by db_full/tools/snapshot_atp.py.
--
-- Run with SQLcl connected AS DMT_OWNER (never ADMIN):
--     sql dmt_owner/<pw>@<db> @db_full/install.sql
--
-- Re-runnable: tables/sequences/indexes are guarded (already-exists ignored),
-- code objects are CREATE OR REPLACE, seeds skip duplicate keys.
-- Storage/tablespace clauses were stripped for portability (see README.md).
-- ============================================================================
set define off
set serveroutput on
whenever sqlerror exit failure rollback
alter session set current_schema = DMT_OWNER;


prompt == Sequences ==
@@sequences/dmt_absence_stg_seq.sql
@@sequences/dmt_absence_tfm_seq.sql
@@sequences/dmt_ap_invoices_int_stg_seq.sql
@@sequences/dmt_ap_invoices_int_tfm_seq.sql
@@sequences/dmt_ap_invoice_lines_int_stg_seq.sql
@@sequences/dmt_ap_invoice_lines_int_tfm_seq.sql
@@sequences/dmt_ap_pay_term_hdr_stg_seq.sql
@@sequences/dmt_ap_pay_term_hdr_tfm_seq.sql
@@sequences/dmt_ap_pay_term_line_stg_seq.sql
@@sequences/dmt_ap_pay_term_line_tfm_seq.sql
@@sequences/dmt_assignment_stg_seq.sql
@@sequences/dmt_assignment_tfm_seq.sql
@@sequences/dmt_ben_benfy_stg_seq.sql
@@sequences/dmt_ben_benfy_tfm_seq.sql
@@sequences/dmt_ben_depend_stg_seq.sql
@@sequences/dmt_ben_depend_tfm_seq.sql
@@sequences/dmt_ben_partic_stg_seq.sql
@@sequences/dmt_ben_partic_tfm_seq.sql
@@sequences/dmt_bip_rpt_id_seq.sql
@@sequences/dmt_ce_bank_acct_stg_seq.sql
@@sequences/dmt_ce_bank_acct_tfm_seq.sql
@@sequences/dmt_ce_bank_stg_seq.sql
@@sequences/dmt_ce_bank_tfm_seq.sql
@@sequences/dmt_ce_branch_stg_seq.sql
@@sequences/dmt_ce_branch_tfm_seq.sql
@@sequences/dmt_egp_item_cat_stg_seq.sql
@@sequences/dmt_egp_item_cat_tfm_seq.sql
@@sequences/dmt_egp_item_stg_seq.sql
@@sequences/dmt_egp_item_tfm_seq.sql
@@sequences/dmt_ess_file_seq.sql
@@sequences/dmt_ess_job_seq.sql
@@sequences/dmt_fa_asset_assign_stg_seq.sql
@@sequences/dmt_fa_asset_assign_tfm_seq.sql
@@sequences/dmt_fa_asset_book_stg_seq.sql
@@sequences/dmt_fa_asset_book_tfm_seq.sql
@@sequences/dmt_fa_asset_hdr_stg_seq.sql
@@sequences/dmt_fa_asset_hdr_tfm_seq.sql
@@sequences/dmt_fbdi_csv_id_seq.sql
@@sequences/dmt_fbdi_zip_id_seq.sql
@@sequences/dmt_fnd_lookup_type_stg_seq.sql
@@sequences/dmt_fnd_lookup_type_tfm_seq.sql
@@sequences/dmt_fnd_lookup_value_stg_seq.sql
@@sequences/dmt_fnd_lookup_value_tfm_seq.sql
@@sequences/dmt_fnd_vs_set_stg_seq.sql
@@sequences/dmt_fnd_vs_set_tfm_seq.sql
@@sequences/dmt_fnd_vs_value_stg_seq.sql
@@sequences/dmt_fnd_vs_value_tfm_seq.sql
@@sequences/dmt_gl_budget_int_stg_seq.sql
@@sequences/dmt_gl_budget_int_tfm_seq.sql
@@sequences/dmt_gl_calendar_stg_seq.sql
@@sequences/dmt_gl_calendar_tfm_seq.sql
-- dmt_gl_interface_stg_seq / _tfm_seq removed 2026-07-09: GLBalances STG/TFM PKs
-- converted to GENERATED ALWAYS AS IDENTITY (accepted identity rule 2026-07-08);
-- no standalone sequence object exists for an identity PK.
@@sequences/dmt_gms_awd_bdgt_stg_seq.sql
@@sequences/dmt_gms_awd_bdgt_tfm_seq.sql
@@sequences/dmt_gms_awd_cert_stg_seq.sql
@@sequences/dmt_gms_awd_cert_tfm_seq.sql
@@sequences/dmt_gms_awd_cfda_stg_seq.sql
@@sequences/dmt_gms_awd_cfda_tfm_seq.sql
@@sequences/dmt_gms_awd_falloc_stg_seq.sql
@@sequences/dmt_gms_awd_falloc_tfm_seq.sql
@@sequences/dmt_gms_awd_fsrc_stg_seq.sql
@@sequences/dmt_gms_awd_fsrc_tfm_seq.sql
@@sequences/dmt_gms_awd_fund_stg_seq.sql
@@sequences/dmt_gms_awd_fund_tfm_seq.sql
@@sequences/dmt_gms_awd_hdr_stg_seq.sql
@@sequences/dmt_gms_awd_hdr_tfm_seq.sql
@@sequences/dmt_gms_awd_kw_stg_seq.sql
@@sequences/dmt_gms_awd_kw_tfm_seq.sql
@@sequences/dmt_gms_awd_orgcr_stg_seq.sql
@@sequences/dmt_gms_awd_orgcr_tfm_seq.sql
@@sequences/dmt_gms_awd_pers_stg_seq.sql
@@sequences/dmt_gms_awd_pers_tfm_seq.sql
@@sequences/dmt_gms_awd_pfsrc_stg_seq.sql
@@sequences/dmt_gms_awd_pfsrc_tfm_seq.sql
@@sequences/dmt_gms_awd_proj_stg_seq.sql
@@sequences/dmt_gms_awd_proj_tfm_seq.sql
@@sequences/dmt_gms_awd_ptbrd_stg_seq.sql
@@sequences/dmt_gms_awd_ptbrd_tfm_seq.sql
@@sequences/dmt_gms_awd_ref_stg_seq.sql
@@sequences/dmt_gms_awd_ref_tfm_seq.sql
@@sequences/dmt_gms_awd_term_stg_seq.sql
@@sequences/dmt_gms_awd_term_tfm_seq.sql
-- Customers HZ STG/TFM per-table id sequences retired 2026-07-09: the 14
-- HZ tables now number their PKs with GENERATED ALWAYS AS IDENTITY (Wave-1
-- offline port). Object files removed in the same commit; drop the live
-- objects from an existing DB with db/tools/drop_retired_customer_sequences.sql.
@@sequences/dmt_inv_trx_lots_stg_seq.sql
@@sequences/dmt_inv_trx_lots_tfm_seq.sql
@@sequences/dmt_inv_trx_serials_stg_seq.sql
@@sequences/dmt_inv_trx_serials_tfm_seq.sql
@@sequences/dmt_inv_trx_stg_seq.sql
@@sequences/dmt_inv_trx_tfm_seq.sql
@@sequences/dmt_inv_uom_stg_seq.sql
@@sequences/dmt_inv_uom_tfm_seq.sql
@@sequences/dmt_log_id_seq.sql
@@sequences/dmt_pay_rel_stg_seq.sql
@@sequences/dmt_pay_rel_tfm_seq.sql
@@sequences/dmt_perf_eval_rating_stg_seq.sql
@@sequences/dmt_perf_eval_rating_tfm_seq.sql
@@sequences/dmt_perf_eval_stg_seq.sql
@@sequences/dmt_perf_eval_tfm_seq.sql
@@sequences/dmt_person_addr_stg_seq.sql
@@sequences/dmt_person_addr_tfm_seq.sql
@@sequences/dmt_person_email_stg_seq.sql
@@sequences/dmt_person_email_tfm_seq.sql
@@sequences/dmt_person_legisl_stg_seq.sql
@@sequences/dmt_person_legisl_tfm_seq.sql
@@sequences/dmt_person_name_stg_seq.sql
@@sequences/dmt_person_name_tfm_seq.sql
@@sequences/dmt_person_nid_stg_seq.sql
@@sequences/dmt_person_nid_tfm_seq.sql
@@sequences/dmt_person_phone_stg_seq.sql
@@sequences/dmt_person_phone_tfm_seq.sql
@@sequences/dmt_pipeline_run_seq.sql
@@sequences/dmt_pjb_bill_events_stg_seq.sql
@@sequences/dmt_pjb_bill_events_tfm_seq.sql
@@sequences/dmt_pjc_expenditures_stg_seq.sql
@@sequences/dmt_pjc_expenditures_tfm_seq.sql
-- Projects STG/TFM id sequences retired 2026-07-09 (identity-PK conversion,
-- accepted coding standard 2026-07-08). The 8 Projects STG/TFM tables now use
-- GENERATED ALWAYS AS IDENTITY. Live objects dropped via
-- db/tools/drop_retired_project_sequences.sql.
@@sequences/dmt_plan_budget_stg_seq.sql
@@sequences/dmt_plan_budget_tfm_seq.sql
@@sequences/dmt_por_req_dists_stg_seq.sql
@@sequences/dmt_por_req_dists_tfm_seq.sql
@@sequences/dmt_por_req_headers_stg_seq.sql
@@sequences/dmt_por_req_headers_tfm_seq.sql
@@sequences/dmt_por_req_lines_stg_seq.sql
@@sequences/dmt_por_req_lines_tfm_seq.sql
@@sequences/dmt_po_dists_int_stg_seq.sql
@@sequences/dmt_po_dists_int_tfm_seq.sql
@@sequences/dmt_po_headers_int_stg_seq.sql
@@sequences/dmt_po_headers_int_tfm_seq.sql
@@sequences/dmt_po_lines_int_stg_seq.sql
@@sequences/dmt_po_lines_int_tfm_seq.sql
@@sequences/dmt_po_line_locs_int_stg_seq.sql
@@sequences/dmt_po_line_locs_int_tfm_seq.sql
@@sequences/dmt_prj_budget_stg_seq.sql
@@sequences/dmt_prj_budget_tfm_seq.sql
@@sequences/dmt_ra_dists_stg_seq.sql
@@sequences/dmt_ra_dists_tfm_seq.sql
@@sequences/dmt_ra_lines_stg_seq.sql
@@sequences/dmt_ra_lines_tfm_seq.sql
@@sequences/dmt_rcv_headers_stg_seq.sql
@@sequences/dmt_rcv_headers_tfm_seq.sql
@@sequences/dmt_rcv_transactions_stg_seq.sql
@@sequences/dmt_rcv_transactions_tfm_seq.sql
@@sequences/dmt_run_prefix_seq.sql
@@sequences/dmt_salary_stg_seq.sql
@@sequences/dmt_salary_tfm_seq.sql
@@sequences/dmt_sal_basis_stg_seq.sql
@@sequences/dmt_sal_basis_tfm_seq.sql
@@sequences/dmt_talent_prof_item_stg_seq.sql
@@sequences/dmt_talent_prof_item_tfm_seq.sql
@@sequences/dmt_talent_prof_stg_seq.sql
@@sequences/dmt_talent_prof_tfm_seq.sql
@@sequences/dmt_tax_card_comp_stg_seq.sql
@@sequences/dmt_tax_card_comp_tfm_seq.sql
@@sequences/dmt_tax_card_stg_seq.sql
@@sequences/dmt_tax_card_tfm_seq.sql
@@sequences/dmt_upload_batch_seq.sql
@@sequences/dmt_w2_bal_dtl_stg_seq.sql
@@sequences/dmt_w2_bal_dtl_tfm_seq.sql
@@sequences/dmt_w2_bal_stg_seq.sql
@@sequences/dmt_w2_bal_tfm_seq.sql
@@sequences/dmt_worker_stg_seq.sql
@@sequences/dmt_worker_tfm_seq.sql
@@sequences/dmt_work_queue_seq.sql
@@sequences/dmt_work_rel_stg_seq.sql
@@sequences/dmt_work_rel_tfm_seq.sql
@@sequences/dmt_work_sched_dtl_stg_seq.sql
@@sequences/dmt_work_sched_dtl_tfm_seq.sql
@@sequences/dmt_work_sched_stg_seq.sql
@@sequences/dmt_work_sched_tfm_seq.sql
@@sequences/dmt_zx_rate_stg_seq.sql
@@sequences/dmt_zx_rate_tfm_seq.sql
@@sequences/dmt_zx_regime_stg_seq.sql
@@sequences/dmt_zx_regime_tfm_seq.sql

prompt == Tables ==
@@tables/apex_export_tmp.sql
@@tables/dmt_absence_stg_tbl.sql
@@tables/dmt_absence_tfm_tbl.sql
@@tables/dmt_app_savepoints.sql
@@tables/dmt_ap_invoices_int_stg_tbl.sql
@@tables/dmt_ap_invoices_int_tfm_tbl.sql
@@tables/dmt_ap_invoice_lines_int_stg_tbl.sql
@@tables/dmt_ap_invoice_lines_int_tfm_tbl.sql
@@tables/dmt_ap_pay_term_hdr_stg_tbl.sql
@@tables/dmt_ap_pay_term_hdr_tfm_tbl.sql
@@tables/dmt_ap_pay_term_line_stg_tbl.sql
@@tables/dmt_ap_pay_term_line_tfm_tbl.sql
@@tables/dmt_assignment_stg_tbl.sql
@@tables/dmt_assignment_tfm_tbl.sql
@@tables/dmt_ben_benfy_stg_tbl.sql
@@tables/dmt_ben_benfy_tfm_tbl.sql
@@tables/dmt_ben_depend_stg_tbl.sql
@@tables/dmt_ben_depend_tfm_tbl.sql
@@tables/dmt_ben_partic_stg_tbl.sql
@@tables/dmt_ben_partic_tfm_tbl.sql
@@tables/dmt_bip_report_tbl.sql
@@tables/dmt_bu_lookup_tbl.sql
@@tables/dmt_cemli_catalog_tbl.sql
@@tables/dmt_cemli_split_cfg.sql
@@tables/dmt_ce_bank_acct_stg_tbl.sql
@@tables/dmt_ce_bank_acct_tfm_tbl.sql
@@tables/dmt_ce_bank_stg_tbl.sql
@@tables/dmt_ce_bank_tfm_tbl.sql
@@tables/dmt_ce_branch_stg_tbl.sql
@@tables/dmt_ce_branch_tfm_tbl.sql
@@tables/dmt_config_tbl.sql
@@tables/dmt_conversion_master_archive.sql
@@tables/dmt_csv_landing_tbl.sql
@@tables/dmt_egp_item_cat_stg_tbl.sql
@@tables/dmt_egp_item_cat_tfm_tbl.sql
@@tables/dmt_egp_item_stg_tbl.sql
@@tables/dmt_egp_item_tfm_tbl.sql
@@tables/dmt_erp_interface_options_tbl.sql
@@tables/dmt_ess_job_file_tbl.sql
@@tables/dmt_ess_job_tbl.sql
@@tables/dmt_fa_asset_assign_stg_tbl.sql
@@tables/dmt_fa_asset_assign_tfm_tbl.sql
@@tables/dmt_fa_asset_book_stg_tbl.sql
@@tables/dmt_fa_asset_book_tfm_tbl.sql
@@tables/dmt_fa_asset_hdr_stg_tbl.sql
@@tables/dmt_fa_asset_hdr_tfm_tbl.sql
@@tables/dmt_fbdi_csv_tbl.sql
@@tables/dmt_fbdi_zip_tbl.sql
@@tables/dmt_fnd_lookup_type_stg_tbl.sql
@@tables/dmt_fnd_lookup_type_tfm_tbl.sql
@@tables/dmt_fnd_lookup_value_stg_tbl.sql
@@tables/dmt_fnd_lookup_value_tfm_tbl.sql
@@tables/dmt_fnd_vs_set_stg_tbl.sql
@@tables/dmt_fnd_vs_set_tfm_tbl.sql
@@tables/dmt_fnd_vs_value_stg_tbl.sql
@@tables/dmt_fnd_vs_value_tfm_tbl.sql
@@tables/dmt_gl_budget_int_stg_tbl.sql
@@tables/dmt_gl_budget_int_tfm_tbl.sql
@@tables/dmt_gl_calendar_stg_tbl.sql
@@tables/dmt_gl_calendar_tfm_tbl.sql
@@tables/dmt_gl_interface_stg_tbl.sql
@@tables/dmt_gl_interface_tfm_tbl.sql
@@tables/dmt_gms_awd_bdgt_prds_stg_tbl.sql
@@tables/dmt_gms_awd_bdgt_prds_tfm_tbl.sql
@@tables/dmt_gms_awd_certs_stg_tbl.sql
@@tables/dmt_gms_awd_certs_tfm_tbl.sql
@@tables/dmt_gms_awd_cfdas_stg_tbl.sql
@@tables/dmt_gms_awd_cfdas_tfm_tbl.sql
@@tables/dmt_gms_awd_funding_stg_tbl.sql
@@tables/dmt_gms_awd_funding_tfm_tbl.sql
@@tables/dmt_gms_awd_fund_alloc_stg_tbl.sql
@@tables/dmt_gms_awd_fund_alloc_tfm_tbl.sql
@@tables/dmt_gms_awd_fund_src_stg_tbl.sql
@@tables/dmt_gms_awd_fund_src_tfm_tbl.sql
@@tables/dmt_gms_awd_headers_stg_tbl.sql
@@tables/dmt_gms_awd_headers_tfm_tbl.sql
@@tables/dmt_gms_awd_keywords_stg_tbl.sql
@@tables/dmt_gms_awd_keywords_tfm_tbl.sql
@@tables/dmt_gms_awd_org_credits_stg_tbl.sql
@@tables/dmt_gms_awd_org_credits_tfm_tbl.sql
@@tables/dmt_gms_awd_personnel_stg_tbl.sql
@@tables/dmt_gms_awd_personnel_tfm_tbl.sql
@@tables/dmt_gms_awd_prj_fund_src_stg_tbl.sql
@@tables/dmt_gms_awd_prj_fund_src_tfm_tbl.sql
@@tables/dmt_gms_awd_prj_tsk_brd_stg_tbl.sql
@@tables/dmt_gms_awd_prj_tsk_brd_tfm_tbl.sql
@@tables/dmt_gms_awd_projects_stg_tbl.sql
@@tables/dmt_gms_awd_projects_tfm_tbl.sql
@@tables/dmt_gms_awd_references_stg_tbl.sql
@@tables/dmt_gms_awd_references_tfm_tbl.sql
@@tables/dmt_gms_awd_terms_stg_tbl.sql
@@tables/dmt_gms_awd_terms_tfm_tbl.sql
@@tables/dmt_hz_accounts_stg_tbl.sql
@@tables/dmt_hz_accounts_tfm_tbl.sql
@@tables/dmt_hz_acct_sites_stg_tbl.sql
@@tables/dmt_hz_acct_sites_tfm_tbl.sql
@@tables/dmt_hz_acct_site_uses_stg_tbl.sql
@@tables/dmt_hz_acct_site_uses_tfm_tbl.sql
@@tables/dmt_hz_locations_stg_tbl.sql
@@tables/dmt_hz_locations_tfm_tbl.sql
@@tables/dmt_hz_parties_stg_tbl.sql
@@tables/dmt_hz_parties_tfm_tbl.sql
@@tables/dmt_hz_party_sites_stg_tbl.sql
@@tables/dmt_hz_party_sites_tfm_tbl.sql
@@tables/dmt_hz_party_site_uses_stg_tbl.sql
@@tables/dmt_hz_party_site_uses_tfm_tbl.sql
@@tables/dmt_inv_trx_lots_stg_tbl.sql
@@tables/dmt_inv_trx_lots_tfm_tbl.sql
@@tables/dmt_inv_trx_serials_stg_tbl.sql
@@tables/dmt_inv_trx_serials_tfm_tbl.sql
@@tables/dmt_inv_trx_stg_tbl.sql
@@tables/dmt_inv_trx_tfm_tbl.sql
@@tables/dmt_inv_uom_stg_tbl.sql
@@tables/dmt_inv_uom_tfm_tbl.sql
@@tables/dmt_log_tbl.sql
@@tables/dmt_lookup_tbl.sql
@@tables/dmt_migration_log.sql
@@tables/dmt_mock_tfm_tbl.sql
@@tables/dmt_pay_rel_stg_tbl.sql
@@tables/dmt_pay_rel_tfm_tbl.sql
@@tables/dmt_perf_eval_rating_stg_tbl.sql
@@tables/dmt_perf_eval_rating_tfm_tbl.sql
@@tables/dmt_perf_eval_stg_tbl.sql
@@tables/dmt_perf_eval_tfm_tbl.sql
@@tables/dmt_person_addr_stg_tbl.sql
@@tables/dmt_person_addr_tfm_tbl.sql
@@tables/dmt_person_email_stg_tbl.sql
@@tables/dmt_person_email_tfm_tbl.sql
@@tables/dmt_person_legisl_stg_tbl.sql
@@tables/dmt_person_legisl_tfm_tbl.sql
@@tables/dmt_person_name_stg_tbl.sql
@@tables/dmt_person_name_tfm_tbl.sql
@@tables/dmt_person_nid_stg_tbl.sql
@@tables/dmt_person_nid_tfm_tbl.sql
@@tables/dmt_person_phone_stg_tbl.sql
@@tables/dmt_person_phone_tfm_tbl.sql
@@tables/dmt_pipeline_def_tbl.sql
@@tables/dmt_pipeline_run_tbl.sql
@@tables/dmt_pjb_bill_events_stg_tbl.sql
@@tables/dmt_pjb_bill_events_tfm_tbl.sql
@@tables/dmt_pjc_expenditures_stg_tbl.sql
@@tables/dmt_pjc_expenditures_tfm_tbl.sql
@@tables/dmt_pjc_txn_controls_stg_tbl.sql
@@tables/dmt_pjc_txn_controls_tfm_tbl.sql
@@tables/dmt_pjf_projects_stg_tbl.sql
@@tables/dmt_pjf_projects_tfm_tbl.sql
@@tables/dmt_pjf_tasks_stg_tbl.sql
@@tables/dmt_pjf_tasks_tfm_tbl.sql
@@tables/dmt_pjf_team_members_stg_tbl.sql
@@tables/dmt_pjf_team_members_tfm_tbl.sql
@@tables/dmt_plan_budget_stg_tbl.sql
@@tables/dmt_plan_budget_tfm_tbl.sql
@@tables/dmt_plan_preview_gtt.sql
@@tables/dmt_por_req_dists_stg_tbl.sql
@@tables/dmt_por_req_dists_tfm_tbl.sql
@@tables/dmt_por_req_headers_stg_tbl.sql
@@tables/dmt_por_req_headers_tfm_tbl.sql
@@tables/dmt_por_req_lines_stg_tbl.sql
@@tables/dmt_por_req_lines_tfm_tbl.sql
@@tables/dmt_poz_suppliers_stg_tbl.sql
@@tables/dmt_poz_suppliers_tfm_tbl.sql
@@tables/dmt_poz_sup_addr_stg_tbl.sql
@@tables/dmt_poz_sup_addr_tfm_tbl.sql
@@tables/dmt_poz_sup_contacts_stg_tbl.sql
@@tables/dmt_poz_sup_contacts_tfm_tbl.sql
@@tables/dmt_poz_sup_site_assn_stg_tbl.sql
@@tables/dmt_poz_sup_site_assn_tfm_tbl.sql
@@tables/dmt_poz_sup_site_stg_tbl.sql
@@tables/dmt_poz_sup_site_tfm_tbl.sql
@@tables/dmt_po_dists_int_stg_tbl.sql
@@tables/dmt_po_dists_int_tfm_tbl.sql
@@tables/dmt_po_headers_int_stg_tbl.sql
@@tables/dmt_po_headers_int_tfm_tbl.sql
@@tables/dmt_po_lines_int_stg_tbl.sql
@@tables/dmt_po_lines_int_tfm_tbl.sql
@@tables/dmt_po_line_locs_int_stg_tbl.sql
@@tables/dmt_po_line_locs_int_tfm_tbl.sql
@@tables/dmt_prj_budget_stg_tbl.sql
@@tables/dmt_prj_budget_tfm_tbl.sql
@@tables/dmt_ra_dists_stg_tbl.sql
@@tables/dmt_ra_dists_tfm_tbl.sql
@@tables/dmt_ra_lines_stg_tbl.sql
@@tables/dmt_ra_lines_tfm_tbl.sql
@@tables/dmt_rcv_headers_stg_tbl.sql
@@tables/dmt_rcv_headers_tfm_tbl.sql
@@tables/dmt_rcv_transactions_stg_tbl.sql
@@tables/dmt_rcv_transactions_tfm_tbl.sql
@@tables/dmt_rest_lookup_tbl.sql
@@tables/dmt_salary_stg_tbl.sql
@@tables/dmt_salary_tfm_tbl.sql
@@tables/dmt_sal_basis_stg_tbl.sql
@@tables/dmt_sal_basis_tfm_tbl.sql
@@tables/dmt_scenario_tbl.sql
@@tables/dmt_stg_tfm_error_tbl.sql
@@tables/dmt_talent_prof_item_stg_tbl.sql
@@tables/dmt_talent_prof_item_tfm_tbl.sql
@@tables/dmt_talent_prof_stg_tbl.sql
@@tables/dmt_talent_prof_tfm_tbl.sql
@@tables/dmt_tax_card_comp_stg_tbl.sql
@@tables/dmt_tax_card_comp_tfm_tbl.sql
@@tables/dmt_tax_card_stg_tbl.sql
@@tables/dmt_tax_card_tfm_tbl.sql
@@tables/dmt_upload_dict_tbl.sql
@@tables/dmt_upload_error_tbl.sql
@@tables/dmt_upload_log_tbl.sql
@@tables/dmt_upload_object_tbl.sql
@@tables/dmt_w2_bal_dtl_stg_tbl.sql
@@tables/dmt_w2_bal_dtl_tfm_tbl.sql
@@tables/dmt_w2_bal_stg_tbl.sql
@@tables/dmt_w2_bal_tfm_tbl.sql
@@tables/dmt_worker_stg_tbl.sql
@@tables/dmt_worker_tfm_tbl.sql
@@tables/dmt_work_queue_tbl.sql
@@tables/dmt_work_rel_stg_tbl.sql
@@tables/dmt_work_rel_tfm_tbl.sql
@@tables/dmt_work_sched_dtl_stg_tbl.sql
@@tables/dmt_work_sched_dtl_tfm_tbl.sql
@@tables/dmt_work_sched_stg_tbl.sql
@@tables/dmt_work_sched_tfm_tbl.sql
@@tables/dmt_zx_rate_stg_tbl.sql
@@tables/dmt_zx_rate_tfm_tbl.sql
@@tables/dmt_zx_regime_stg_tbl.sql
@@tables/dmt_zx_regime_tfm_tbl.sql
@@tables/err$_dmt_ap_invoices_int_stg_tbl.sql
@@tables/err$_dmt_ap_pay_term_hdr_stg_tbl.sql
@@tables/err$_dmt_ap_pay_term_line_stg_tbl.sql
@@tables/err$_dmt_ce_bank_acct_stg_tbl.sql
@@tables/err$_dmt_ce_bank_stg_tbl.sql
@@tables/err$_dmt_ce_branch_stg_tbl.sql
@@tables/err$_dmt_egp_item_cat_stg_tbl.sql
@@tables/err$_dmt_egp_item_stg_tbl.sql
@@tables/err$_dmt_fa_asset_hdr_stg_tbl.sql
@@tables/err$_dmt_fnd_lookup_type_stg_tbl.sql
@@tables/err$_dmt_fnd_lookup_value_stg_tbl.sql
@@tables/err$_dmt_fnd_vs_set_stg_tbl.sql
@@tables/err$_dmt_fnd_vs_value_stg_tbl.sql
@@tables/err$_dmt_gl_calendar_stg_tbl.sql
@@tables/err$_dmt_gl_interface_stg_tbl.sql
@@tables/err$_dmt_hz_parties_stg_tbl.sql
@@tables/err$_dmt_inv_uom_stg_tbl.sql
@@tables/err$_dmt_pjf_projects_stg_tbl.sql
@@tables/err$_dmt_poz_suppliers_stg_tbl.sql
@@tables/err$_dmt_po_headers_int_stg_tbl.sql
@@tables/err$_dmt_ra_lines_stg_tbl.sql
@@tables/err$_dmt_worker_stg_tbl.sql
@@tables/err$_dmt_zx_rate_stg_tbl.sql
@@tables/err$_dmt_zx_regime_stg_tbl.sql

prompt == Foreign keys ==
@@tables/_foreign_keys.sql

prompt == Synonyms ==
@@synonyms/dmt_coa_mapping.sql
@@synonyms/dmt_coa_map_config.sql
@@synonyms/dmt_coa_map_pkg.sql
@@synonyms/dmt_coa_segment_def.sql
@@synonyms/dmt_coa_segment_map.sql
@@synonyms/dmt_coa_segment_values.sql
@@synonyms/dmt_coa_set.sql
@@synonyms/dmt_coa_source_combos.sql
@@synonyms/dmt_coa_suggest_pkg.sql
@@synonyms/dmt_coa_target_combos.sql
@@synonyms/dmt_lkp_ebs_unmatched_v.sql
@@synonyms/dmt_lkp_ebs_values.sql
@@synonyms/dmt_lkp_fusion_values.sql
@@synonyms/dmt_lkp_mapping.sql
@@synonyms/dmt_lkp_mapping_status_v.sql
@@synonyms/dmt_lkp_suggest_pkg.sql
@@synonyms/dmt_lkp_type_config.sql

prompt == Views (dependency order) ==
@@views/dmt_conversion_master_tbl.sql
@@views/dmt_bip_reports_admin_v.sql
@@views/dmt_cfg_gl_calendar_v.sql
@@views/dmt_cfg_pay_terms_v.sql
@@views/dmt_cfg_pay_term_lines_v.sql
@@views/dmt_cfg_tax_rates_v.sql
@@views/dmt_cfg_tax_regimes_v.sql
@@views/dmt_cfg_uom_v.sql
@@views/dmt_cfg_value_sets_v.sql
@@views/dmt_cfg_vs_values_v.sql
@@views/dmt_config_admin_v.sql
@@views/dmt_scenario_summary_v.sql
@@views/dmt_dashboard_cemli_summary_v.sql
@@views/dmt_dashboard_runs_v.sql
@@views/dmt_ess_jobs_monitor_v.sql
@@views/dmt_ess_job_detail_v.sql
@@views/dmt_ess_job_files_v.sql
@@views/dmt_gl_budget_v.sql
@@views/dmt_grants_v.sql
@@views/dmt_mst_banks_v.sql
@@views/dmt_mst_bank_accts_v.sql
@@views/dmt_mst_bank_branches_v.sql
@@views/dmt_mst_items_v.sql
@@views/dmt_mst_item_cats_v.sql
@@views/dmt_object_detail_v.sql
@@views/dmt_v_cemli_status.sql
@@views/dmt_pipeline_summary_v.sql
@@views/dmt_record_detail_v.sql
@@views/dmt_run_history_v.sql
@@views/dmt_run_metrics_v.sql
@@views/dmt_run_status_v.sql
@@views/dmt_v_absence_detail.sql
@@views/dmt_v_ap_invoices_detail.sql
@@views/dmt_v_ap_inv_lines_detail.sql
@@views/dmt_v_ar_dists_detail.sql
@@views/dmt_v_ar_lines_detail.sql
@@views/dmt_v_asset_assign_detail.sql
@@views/dmt_v_asset_book_detail.sql
@@views/dmt_v_asset_hdr_detail.sql
@@views/dmt_v_assignment_detail.sql
@@views/dmt_v_ben_benfy_detail.sql
@@views/dmt_v_ben_depend_detail.sql
@@views/dmt_v_ben_partic_detail.sql
@@views/dmt_v_bill_events_detail.sql
@@views/dmt_v_cemli_tfm_tables.sql
@@views/dmt_v_catalog_health.sql
@@views/dmt_v_cust_accounts_detail.sql
@@views/dmt_v_cust_acct_sites_detail.sql
@@views/dmt_v_cust_acct_site_uses_detail.sql
@@views/dmt_v_cust_locations_detail.sql
@@views/dmt_v_cust_parties_detail.sql
@@views/dmt_v_cust_party_sites_detail.sql
@@views/dmt_v_cust_site_uses_detail.sql
@@views/dmt_v_expenditures_detail.sql
@@views/dmt_v_gl_budget_detail.sql
@@views/dmt_v_gl_journal_detail.sql
@@views/dmt_v_grant_bdgt_prds_detail.sql
@@views/dmt_v_grant_certs_detail.sql
@@views/dmt_v_grant_cfdas_detail.sql
@@views/dmt_v_grant_funding_detail.sql
@@views/dmt_v_grant_fund_alloc_detail.sql
@@views/dmt_v_grant_fund_src_detail.sql
@@views/dmt_v_grant_headers_detail.sql
@@views/dmt_v_grant_keywords_detail.sql
@@views/dmt_v_grant_org_credits_detail.sql
@@views/dmt_v_grant_personnel_detail.sql
@@views/dmt_v_grant_prj_fund_src_detail.sql
@@views/dmt_v_grant_prj_tsk_brd_detail.sql
@@views/dmt_v_grant_projects_detail.sql
@@views/dmt_v_grant_references_detail.sql
@@views/dmt_v_grant_terms_detail.sql
@@views/dmt_v_pay_rel_detail.sql
@@views/dmt_v_perf_eval_detail.sql
@@views/dmt_v_perf_eval_rating_detail.sql
@@views/dmt_v_person_addr_detail.sql
@@views/dmt_v_person_email_detail.sql
@@views/dmt_v_person_legisl_detail.sql
@@views/dmt_v_person_name_detail.sql
@@views/dmt_v_person_nid_detail.sql
@@views/dmt_v_person_phone_detail.sql
@@views/dmt_v_plan_budget_detail.sql
@@views/dmt_v_po_dists_detail.sql
@@views/dmt_v_po_headers_detail.sql
@@views/dmt_v_po_lines_detail.sql
@@views/dmt_v_po_line_locs_detail.sql
@@views/dmt_v_prj_budget_detail.sql
@@views/dmt_v_projects_detail.sql
@@views/dmt_v_project_tasks_detail.sql
@@views/dmt_v_project_team_detail.sql
@@views/dmt_v_rcv_headers_detail.sql
@@views/dmt_v_rcv_transactions_detail.sql
@@views/dmt_v_req_dists_detail.sql
@@views/dmt_v_req_headers_detail.sql
@@views/dmt_v_req_lines_detail.sql
@@views/dmt_v_salary_detail.sql
@@views/dmt_v_sal_basis_detail.sql
@@views/dmt_v_suppliers_detail.sql
@@views/dmt_v_sup_addr_detail.sql
@@views/dmt_v_sup_contacts_detail.sql
@@views/dmt_v_sup_site_assn_detail.sql
@@views/dmt_v_sup_site_detail.sql
@@views/dmt_v_talent_prof_detail.sql
@@views/dmt_v_talent_prof_item_detail.sql
@@views/dmt_v_tax_card_comp_detail.sql
@@views/dmt_v_tax_card_detail.sql
@@views/dmt_v_txn_controls_detail.sql
@@views/dmt_v_w2_bal_detail.sql
@@views/dmt_v_w2_bal_dtl_detail.sql
@@views/dmt_v_worker_detail.sql
@@views/dmt_v_work_rel_detail.sql
@@views/dmt_v_work_sched_detail.sql
@@views/dmt_v_work_sched_dtl_detail.sql

prompt == Package specs (dependency order) ==
@@packages/dmt_1099_fbdi_gen_pkg.pks.sql
@@packages/dmt_1099_results_pkg.pks.sql
@@packages/dmt_absence_hdl_gen_pkg.pks.sql
@@packages/dmt_absence_results_pkg.pks.sql
@@packages/dmt_absence_transform_pkg.pks.sql
@@packages/dmt_absence_validator_pkg.pks.sql
@@packages/dmt_apex_page_pkg.pks.sql
@@packages/dmt_ap_fbdi_gen_pkg.pks.sql
@@packages/dmt_ap_pay_term_fbl_gen_pkg.pks.sql
@@packages/dmt_ap_pay_term_results_pkg.pks.sql
@@packages/dmt_ap_pay_term_runner_pkg.pks.sql
@@packages/dmt_ap_pay_term_transform_pkg.pks.sql
@@packages/dmt_ap_pay_term_validator_pkg.pks.sql
@@packages/dmt_ap_results_pkg.pks.sql
@@packages/dmt_ap_transform_pkg.pks.sql
@@packages/dmt_ap_validator_pkg.pks.sql
@@packages/dmt_ar_fbdi_gen_pkg.pks.sql
@@packages/dmt_ar_results_pkg.pks.sql
@@packages/dmt_ar_transform_pkg.pks.sql
@@packages/dmt_ar_validator_pkg.pks.sql
@@packages/dmt_assignment_hdl_gen_pkg.pks.sql
@@packages/dmt_assignment_results_pkg.pks.sql
@@packages/dmt_assignment_transform_pkg.pks.sql
@@packages/dmt_assignment_validator_pkg.pks.sql
@@packages/dmt_ben_benfy_hdl_gen_pkg.pks.sql
@@packages/dmt_ben_benfy_results_pkg.pks.sql
@@packages/dmt_ben_benfy_transform_pkg.pks.sql
@@packages/dmt_ben_benfy_validator_pkg.pks.sql
@@packages/dmt_ben_depend_hdl_gen_pkg.pks.sql
@@packages/dmt_ben_depend_results_pkg.pks.sql
@@packages/dmt_ben_depend_transform_pkg.pks.sql
@@packages/dmt_ben_depend_validator_pkg.pks.sql
@@packages/dmt_ben_partic_hdl_gen_pkg.pks.sql
@@packages/dmt_ben_partic_results_pkg.pks.sql
@@packages/dmt_ben_partic_transform_pkg.pks.sql
@@packages/dmt_ben_partic_validator_pkg.pks.sql
@@packages/dmt_billing_event_fbdi_gen_pkg.pks.sql
@@packages/dmt_billing_event_results_pkg.pks.sql
@@packages/dmt_billing_event_transform_pkg.pks.sql
@@packages/dmt_billing_event_validator_pkg.pks.sql
@@packages/dmt_bip_deploy_pkg.pks.sql
@@packages/dmt_bip_setup_pkg.pks.sql
@@packages/dmt_blanket_po_fbdi_gen_pkg.pks.sql
@@packages/dmt_blanket_po_results_pkg.pks.sql
@@packages/dmt_ce_bank_fbl_gen_pkg.pks.sql
@@packages/dmt_ce_bank_results_pkg.pks.sql
@@packages/dmt_ce_bank_runner_pkg.pks.sql
@@packages/dmt_ce_bank_transform_pkg.pks.sql
@@packages/dmt_ce_bank_validator_pkg.pks.sql
@@packages/dmt_contract_fbdi_gen_pkg.pks.sql
@@packages/dmt_contract_results_pkg.pks.sql
@@packages/dmt_csv_loader_pkg.pks.sql
@@packages/dmt_csv_upload_pkg.pks.sql
@@packages/dmt_cust_fbdi_gen_pkg.pks.sql
@@packages/dmt_cust_results_pkg.pks.sql
@@packages/dmt_cust_transform_pkg.pks.sql
@@packages/dmt_cust_validator_pkg.pks.sql
@@packages/dmt_ebs_adaptor_pkg.pks.sql
@@packages/dmt_egp_item_cat_fbdi_gen_pkg.pks.sql
@@packages/dmt_egp_item_cat_results_pkg.pks.sql
@@packages/dmt_egp_item_cat_runner_pkg.pks.sql
@@packages/dmt_egp_item_cat_transform_pkg.pks.sql
@@packages/dmt_egp_item_cat_validator_pkg.pks.sql
@@packages/dmt_egp_item_fbdi_gen_pkg.pks.sql
@@packages/dmt_egp_item_results_pkg.pks.sql
@@packages/dmt_egp_item_runner_pkg.pks.sql
@@packages/dmt_egp_item_transform_pkg.pks.sql
@@packages/dmt_egp_item_validator_pkg.pks.sql
@@packages/dmt_ess_util_pkg.pks.sql
@@packages/dmt_expenditure_fbdi_gen_pkg.pks.sql
@@packages/dmt_expenditure_results_pkg.pks.sql
@@packages/dmt_expenditure_transform_pkg.pks.sql
@@packages/dmt_expenditure_validator_pkg.pks.sql
@@packages/dmt_fa_asset_fbdi_gen_pkg.pks.sql
@@packages/dmt_fa_asset_results_pkg.pks.sql
@@packages/dmt_fa_asset_transform_pkg.pks.sql
@@packages/dmt_fa_asset_validator_pkg.pks.sql
@@packages/dmt_fnd_lookup_fbl_gen_pkg.pks.sql
@@packages/dmt_fnd_lookup_results_pkg.pks.sql
@@packages/dmt_fnd_lookup_runner_pkg.pks.sql
@@packages/dmt_fnd_lookup_transform_pkg.pks.sql
@@packages/dmt_fnd_lookup_validator_pkg.pks.sql
@@packages/dmt_fnd_vs_fbl_gen_pkg.pks.sql
@@packages/dmt_fnd_vs_results_pkg.pks.sql
@@packages/dmt_fnd_vs_runner_pkg.pks.sql
@@packages/dmt_fnd_vs_transform_pkg.pks.sql
@@packages/dmt_fnd_vs_validator_pkg.pks.sql
@@packages/dmt_generic_adaptor_pkg.pks.sql
@@packages/dmt_gl_budget_fbdi_gen_pkg.pks.sql
@@packages/dmt_gl_budget_results_pkg.pks.sql
@@packages/dmt_gl_budget_transform_pkg.pks.sql
@@packages/dmt_gl_budget_validator_pkg.pks.sql
@@packages/dmt_gl_calendar_fbl_gen_pkg.pks.sql
@@packages/dmt_gl_calendar_results_pkg.pks.sql
@@packages/dmt_gl_calendar_runner_pkg.pks.sql
@@packages/dmt_gl_calendar_transform_pkg.pks.sql
@@packages/dmt_gl_calendar_validator_pkg.pks.sql
@@packages/dmt_gl_fbdi_gen_pkg.pks.sql
@@packages/dmt_gl_results_pkg.pks.sql
@@packages/dmt_gl_transform_pkg.pks.sql
@@packages/dmt_gl_validator_pkg.pks.sql
@@packages/dmt_grants_fbdi_gen_pkg.pks.sql
@@packages/dmt_grants_results_pkg.pks.sql
@@packages/dmt_grants_transform_pkg.pks.sql
@@packages/dmt_grants_validator_pkg.pks.sql
@@packages/dmt_hdl_util_pkg.pks.sql
@@packages/dmt_import_report_pkg.pks.sql
@@packages/dmt_inv_uom_fbl_gen_pkg.pks.sql
@@packages/dmt_inv_uom_results_pkg.pks.sql
@@packages/dmt_inv_uom_runner_pkg.pks.sql
@@packages/dmt_inv_uom_transform_pkg.pks.sql
@@packages/dmt_inv_uom_validator_pkg.pks.sql
@@packages/dmt_loader_pkg.pks.sql
@@packages/dmt_misc_receipt_fbdi_gen_pkg.pks.sql
@@packages/dmt_misc_receipt_results_pkg.pks.sql
@@packages/dmt_misc_receipt_transform_pkg.pks.sql
@@packages/dmt_misc_receipt_validator_pkg.pks.sql
@@packages/dmt_mock_pkg.pks.sql
@@packages/dmt_pay_rel_hdl_gen_pkg.pks.sql
@@packages/dmt_pay_rel_results_pkg.pks.sql
@@packages/dmt_pay_rel_transform_pkg.pks.sql
@@packages/dmt_pay_rel_validator_pkg.pks.sql
@@packages/dmt_perf_eval_hdl_gen_pkg.pks.sql
@@packages/dmt_perf_eval_results_pkg.pks.sql
@@packages/dmt_perf_eval_transform_pkg.pks.sql
@@packages/dmt_perf_eval_validator_pkg.pks.sql
@@packages/dmt_pipeline_init_pkg.pks.sql
@@packages/dmt_plan_budget_fbdi_gen_pkg.pks.sql
@@packages/dmt_plan_budget_results_pkg.pks.sql
@@packages/dmt_plan_budget_transform_pkg.pks.sql
@@packages/dmt_plan_budget_validator_pkg.pks.sql
@@packages/dmt_poz_sup_addr_fbdi_gen_pkg.pks.sql
@@packages/dmt_poz_sup_addr_validator_pkg.pks.sql
@@packages/dmt_poz_sup_cont_fbdi_gen_pkg.pks.sql
@@packages/dmt_poz_sup_cont_validator_pkg.pks.sql
@@packages/dmt_poz_sup_fbdi_gen_pkg.pks.sql
@@packages/dmt_poz_sup_results_pkg.pks.sql
@@packages/dmt_poz_sup_site_assn_fbdi_gen_pkg.pks.sql
@@packages/dmt_poz_sup_site_assn_validator_pkg.pks.sql
@@packages/dmt_poz_sup_site_fbdi_gen_pkg.pks.sql
@@packages/dmt_poz_sup_site_validator_pkg.pks.sql
@@packages/dmt_poz_sup_transform_pkg.pks.sql
@@packages/dmt_poz_sup_validator_pkg.pks.sql
@@packages/dmt_po_fbdi_gen_pkg.pks.sql
@@packages/dmt_po_results_pkg.pks.sql
@@packages/dmt_po_transform_pkg.pks.sql
@@packages/dmt_po_validator_pkg.pks.sql
@@packages/dmt_prj_budget_fbdi_gen_pkg.pks.sql
@@packages/dmt_prj_budget_results_pkg.pks.sql
@@packages/dmt_prj_budget_transform_pkg.pks.sql
@@packages/dmt_prj_budget_validator_pkg.pks.sql
@@packages/dmt_project_fbdi_gen_pkg.pks.sql
@@packages/dmt_project_results_pkg.pks.sql
@@packages/dmt_project_transform_pkg.pks.sql
@@packages/dmt_project_validator_pkg.pks.sql
@@packages/dmt_queue_pkg.pks.sql
@@packages/dmt_queue_worker_pkg.pks.sql
@@packages/dmt_regression_pkg.pks.sql
@@packages/dmt_report_pkg.pks.sql
@@packages/dmt_req_fbdi_gen_pkg.pks.sql
@@packages/dmt_req_results_pkg.pks.sql
@@packages/dmt_req_transform_pkg.pks.sql
@@packages/dmt_req_validator_pkg.pks.sql
@@packages/dmt_rest_loader_pkg.pks.sql
@@packages/dmt_rest_lookup_pkg.pks.sql
@@packages/dmt_rest_query_pkg.pks.sql
@@packages/dmt_salary_hdl_gen_pkg.pks.sql
@@packages/dmt_salary_results_pkg.pks.sql
@@packages/dmt_salary_transform_pkg.pks.sql
@@packages/dmt_salary_validator_pkg.pks.sql
@@packages/dmt_sal_basis_hdl_gen_pkg.pks.sql
@@packages/dmt_sal_basis_results_pkg.pks.sql
@@packages/dmt_sal_basis_transform_pkg.pks.sql
@@packages/dmt_sal_basis_validator_pkg.pks.sql
@@packages/dmt_scheduler_pkg.pks.sql
@@packages/dmt_talent_prof_hdl_gen_pkg.pks.sql
@@packages/dmt_talent_prof_results_pkg.pks.sql
@@packages/dmt_talent_prof_transform_pkg.pks.sql
@@packages/dmt_talent_prof_validator_pkg.pks.sql
@@packages/dmt_tax_card_hdl_gen_pkg.pks.sql
@@packages/dmt_tax_card_results_pkg.pks.sql
@@packages/dmt_tax_card_transform_pkg.pks.sql
@@packages/dmt_tax_card_validator_pkg.pks.sql
@@packages/dmt_upload_dict_pkg.pks.sql
@@packages/dmt_util_pkg.pks.sql
@@packages/dmt_w2_bal_hdl_gen_pkg.pks.sql
@@packages/dmt_w2_bal_results_pkg.pks.sql
@@packages/dmt_w2_bal_transform_pkg.pks.sql
@@packages/dmt_w2_bal_validator_pkg.pks.sql
@@packages/dmt_worker_hdl_gen_pkg.pks.sql
@@packages/dmt_worker_results_pkg.pks.sql
@@packages/dmt_worker_transform_pkg.pks.sql
@@packages/dmt_worker_validator_pkg.pks.sql
@@packages/dmt_work_sched_hdl_gen_pkg.pks.sql
@@packages/dmt_work_sched_results_pkg.pks.sql
@@packages/dmt_work_sched_transform_pkg.pks.sql
@@packages/dmt_work_sched_validator_pkg.pks.sql
@@packages/dmt_zx_fbl_gen_pkg.pks.sql
@@packages/dmt_zx_results_pkg.pks.sql
@@packages/dmt_zx_runner_pkg.pks.sql
@@packages/dmt_zx_transform_pkg.pks.sql
@@packages/dmt_zx_validator_pkg.pks.sql
@@packages/fbt_bip_pkg.pks.sql
@@packages/utl_zip.pks.sql

prompt == Procedures ==
@@procedures/dmt_ess_job_detail.sql
@@procedures/dmt_fbdi_file_chain.sql
@@procedures/dmt_object_detail_breadcrumb.sql
@@procedures/dmt_plan_preview_html.sql
@@procedures/dmt_plan_run_gtt.sql
@@procedures/dmt_render_view.sql
@@procedures/dmt_run_detail_header.sql
@@procedures/dmt_run_detail_tiles.sql
@@procedures/dmt_submit_run_v2.sql

prompt == Package bodies ==
@@packages/dmt_1099_fbdi_gen_pkg.pkb.sql
@@packages/dmt_1099_results_pkg.pkb.sql
@@packages/dmt_absence_hdl_gen_pkg.pkb.sql
@@packages/dmt_absence_results_pkg.pkb.sql
@@packages/dmt_absence_transform_pkg.pkb.sql
@@packages/dmt_absence_validator_pkg.pkb.sql
@@packages/dmt_apex_page_pkg.pkb.sql
@@packages/dmt_ap_fbdi_gen_pkg.pkb.sql
@@packages/dmt_ap_pay_term_fbl_gen_pkg.pkb.sql
@@packages/dmt_ap_pay_term_results_pkg.pkb.sql
@@packages/dmt_ap_pay_term_runner_pkg.pkb.sql
@@packages/dmt_ap_pay_term_transform_pkg.pkb.sql
@@packages/dmt_ap_pay_term_validator_pkg.pkb.sql
@@packages/dmt_ap_results_pkg.pkb.sql
@@packages/dmt_ap_transform_pkg.pkb.sql
@@packages/dmt_ap_validator_pkg.pkb.sql
@@packages/dmt_ar_fbdi_gen_pkg.pkb.sql
@@packages/dmt_ar_results_pkg.pkb.sql
@@packages/dmt_ar_transform_pkg.pkb.sql
@@packages/dmt_ar_validator_pkg.pkb.sql
@@packages/dmt_assignment_hdl_gen_pkg.pkb.sql
@@packages/dmt_assignment_results_pkg.pkb.sql
@@packages/dmt_assignment_transform_pkg.pkb.sql
@@packages/dmt_assignment_validator_pkg.pkb.sql
@@packages/dmt_ben_benfy_hdl_gen_pkg.pkb.sql
@@packages/dmt_ben_benfy_results_pkg.pkb.sql
@@packages/dmt_ben_benfy_transform_pkg.pkb.sql
@@packages/dmt_ben_benfy_validator_pkg.pkb.sql
@@packages/dmt_ben_depend_hdl_gen_pkg.pkb.sql
@@packages/dmt_ben_depend_results_pkg.pkb.sql
@@packages/dmt_ben_depend_transform_pkg.pkb.sql
@@packages/dmt_ben_depend_validator_pkg.pkb.sql
@@packages/dmt_ben_partic_hdl_gen_pkg.pkb.sql
@@packages/dmt_ben_partic_results_pkg.pkb.sql
@@packages/dmt_ben_partic_transform_pkg.pkb.sql
@@packages/dmt_ben_partic_validator_pkg.pkb.sql
@@packages/dmt_billing_event_fbdi_gen_pkg.pkb.sql
@@packages/dmt_billing_event_results_pkg.pkb.sql
@@packages/dmt_billing_event_transform_pkg.pkb.sql
@@packages/dmt_billing_event_validator_pkg.pkb.sql
@@packages/dmt_bip_deploy_pkg.pkb.sql
@@packages/dmt_bip_setup_pkg.pkb.sql
@@packages/dmt_blanket_po_fbdi_gen_pkg.pkb.sql
@@packages/dmt_blanket_po_results_pkg.pkb.sql
@@packages/dmt_ce_bank_fbl_gen_pkg.pkb.sql
@@packages/dmt_ce_bank_results_pkg.pkb.sql
@@packages/dmt_ce_bank_runner_pkg.pkb.sql
@@packages/dmt_ce_bank_transform_pkg.pkb.sql
@@packages/dmt_ce_bank_validator_pkg.pkb.sql
@@packages/dmt_contract_fbdi_gen_pkg.pkb.sql
@@packages/dmt_contract_results_pkg.pkb.sql
@@packages/dmt_csv_loader_pkg.pkb.sql
@@packages/dmt_csv_upload_pkg.pkb.sql
@@packages/dmt_cust_fbdi_gen_pkg.pkb.sql
@@packages/dmt_cust_results_pkg.pkb.sql
@@packages/dmt_cust_transform_pkg.pkb.sql
@@packages/dmt_cust_validator_pkg.pkb.sql
@@packages/dmt_ebs_adaptor_pkg.pkb.sql
@@packages/dmt_egp_item_cat_fbdi_gen_pkg.pkb.sql
@@packages/dmt_egp_item_cat_results_pkg.pkb.sql
@@packages/dmt_egp_item_cat_runner_pkg.pkb.sql
@@packages/dmt_egp_item_cat_transform_pkg.pkb.sql
@@packages/dmt_egp_item_cat_validator_pkg.pkb.sql
@@packages/dmt_egp_item_fbdi_gen_pkg.pkb.sql
@@packages/dmt_egp_item_results_pkg.pkb.sql
@@packages/dmt_egp_item_runner_pkg.pkb.sql
@@packages/dmt_egp_item_transform_pkg.pkb.sql
@@packages/dmt_egp_item_validator_pkg.pkb.sql
@@packages/dmt_ess_util_pkg.pkb.sql
@@packages/dmt_expenditure_fbdi_gen_pkg.pkb.sql
@@packages/dmt_expenditure_results_pkg.pkb.sql
@@packages/dmt_expenditure_transform_pkg.pkb.sql
@@packages/dmt_expenditure_validator_pkg.pkb.sql
@@packages/dmt_fa_asset_fbdi_gen_pkg.pkb.sql
@@packages/dmt_fa_asset_results_pkg.pkb.sql
@@packages/dmt_fa_asset_transform_pkg.pkb.sql
@@packages/dmt_fa_asset_validator_pkg.pkb.sql
@@packages/dmt_fnd_lookup_fbl_gen_pkg.pkb.sql
@@packages/dmt_fnd_lookup_results_pkg.pkb.sql
@@packages/dmt_fnd_lookup_runner_pkg.pkb.sql
@@packages/dmt_fnd_lookup_transform_pkg.pkb.sql
@@packages/dmt_fnd_lookup_validator_pkg.pkb.sql
@@packages/dmt_fnd_vs_fbl_gen_pkg.pkb.sql
@@packages/dmt_fnd_vs_results_pkg.pkb.sql
@@packages/dmt_fnd_vs_runner_pkg.pkb.sql
@@packages/dmt_fnd_vs_transform_pkg.pkb.sql
@@packages/dmt_fnd_vs_validator_pkg.pkb.sql
@@packages/dmt_generic_adaptor_pkg.pkb.sql
@@packages/dmt_gl_budget_fbdi_gen_pkg.pkb.sql
@@packages/dmt_gl_budget_results_pkg.pkb.sql
@@packages/dmt_gl_budget_transform_pkg.pkb.sql
@@packages/dmt_gl_budget_validator_pkg.pkb.sql
@@packages/dmt_gl_calendar_fbl_gen_pkg.pkb.sql
@@packages/dmt_gl_calendar_results_pkg.pkb.sql
@@packages/dmt_gl_calendar_runner_pkg.pkb.sql
@@packages/dmt_gl_calendar_transform_pkg.pkb.sql
@@packages/dmt_gl_calendar_validator_pkg.pkb.sql
@@packages/dmt_gl_fbdi_gen_pkg.pkb.sql
@@packages/dmt_gl_results_pkg.pkb.sql
@@packages/dmt_gl_transform_pkg.pkb.sql
@@packages/dmt_gl_validator_pkg.pkb.sql
@@packages/dmt_grants_fbdi_gen_pkg.pkb.sql
@@packages/dmt_grants_results_pkg.pkb.sql
@@packages/dmt_grants_transform_pkg.pkb.sql
@@packages/dmt_grants_validator_pkg.pkb.sql
@@packages/dmt_hdl_util_pkg.pkb.sql
@@packages/dmt_import_report_pkg.pkb.sql
@@packages/dmt_inv_uom_fbl_gen_pkg.pkb.sql
@@packages/dmt_inv_uom_results_pkg.pkb.sql
@@packages/dmt_inv_uom_runner_pkg.pkb.sql
@@packages/dmt_inv_uom_transform_pkg.pkb.sql
@@packages/dmt_inv_uom_validator_pkg.pkb.sql
@@packages/dmt_loader_pkg.pkb.sql
@@packages/dmt_misc_receipt_fbdi_gen_pkg.pkb.sql
@@packages/dmt_misc_receipt_results_pkg.pkb.sql
@@packages/dmt_misc_receipt_transform_pkg.pkb.sql
@@packages/dmt_misc_receipt_validator_pkg.pkb.sql
@@packages/dmt_mock_pkg.pkb.sql
@@packages/dmt_pay_rel_hdl_gen_pkg.pkb.sql
@@packages/dmt_pay_rel_results_pkg.pkb.sql
@@packages/dmt_pay_rel_transform_pkg.pkb.sql
@@packages/dmt_pay_rel_validator_pkg.pkb.sql
@@packages/dmt_perf_eval_hdl_gen_pkg.pkb.sql
@@packages/dmt_perf_eval_results_pkg.pkb.sql
@@packages/dmt_perf_eval_transform_pkg.pkb.sql
@@packages/dmt_perf_eval_validator_pkg.pkb.sql
@@packages/dmt_pipeline_init_pkg.pkb.sql
@@packages/dmt_plan_budget_fbdi_gen_pkg.pkb.sql
@@packages/dmt_plan_budget_results_pkg.pkb.sql
@@packages/dmt_plan_budget_transform_pkg.pkb.sql
@@packages/dmt_plan_budget_validator_pkg.pkb.sql
@@packages/dmt_poz_sup_addr_fbdi_gen_pkg.pkb.sql
@@packages/dmt_poz_sup_addr_validator_pkg.pkb.sql
@@packages/dmt_poz_sup_cont_fbdi_gen_pkg.pkb.sql
@@packages/dmt_poz_sup_cont_validator_pkg.pkb.sql
@@packages/dmt_poz_sup_fbdi_gen_pkg.pkb.sql
@@packages/dmt_poz_sup_results_pkg.pkb.sql
@@packages/dmt_poz_sup_site_assn_fbdi_gen_pkg.pkb.sql
@@packages/dmt_poz_sup_site_assn_validator_pkg.pkb.sql
@@packages/dmt_poz_sup_site_fbdi_gen_pkg.pkb.sql
@@packages/dmt_poz_sup_site_validator_pkg.pkb.sql
@@packages/dmt_poz_sup_transform_pkg.pkb.sql
@@packages/dmt_poz_sup_validator_pkg.pkb.sql
@@packages/dmt_po_fbdi_gen_pkg.pkb.sql
@@packages/dmt_po_results_pkg.pkb.sql
@@packages/dmt_po_transform_pkg.pkb.sql
@@packages/dmt_po_validator_pkg.pkb.sql
@@packages/dmt_prj_budget_fbdi_gen_pkg.pkb.sql
@@packages/dmt_prj_budget_results_pkg.pkb.sql
@@packages/dmt_prj_budget_transform_pkg.pkb.sql
@@packages/dmt_prj_budget_validator_pkg.pkb.sql
@@packages/dmt_project_fbdi_gen_pkg.pkb.sql
@@packages/dmt_project_results_pkg.pkb.sql
@@packages/dmt_project_transform_pkg.pkb.sql
@@packages/dmt_project_validator_pkg.pkb.sql
@@packages/dmt_queue_pkg.pkb.sql
@@packages/dmt_queue_worker_pkg.pkb.sql
@@packages/dmt_report_pkg.pkb.sql
@@packages/dmt_req_fbdi_gen_pkg.pkb.sql
@@packages/dmt_req_results_pkg.pkb.sql
@@packages/dmt_req_transform_pkg.pkb.sql
@@packages/dmt_req_validator_pkg.pkb.sql
@@packages/dmt_rest_loader_pkg.pkb.sql
@@packages/dmt_rest_lookup_pkg.pkb.sql
@@packages/dmt_rest_query_pkg.pkb.sql
@@packages/dmt_salary_hdl_gen_pkg.pkb.sql
@@packages/dmt_salary_results_pkg.pkb.sql
@@packages/dmt_salary_transform_pkg.pkb.sql
@@packages/dmt_salary_validator_pkg.pkb.sql
@@packages/dmt_sal_basis_hdl_gen_pkg.pkb.sql
@@packages/dmt_sal_basis_results_pkg.pkb.sql
@@packages/dmt_sal_basis_transform_pkg.pkb.sql
@@packages/dmt_sal_basis_validator_pkg.pkb.sql
@@packages/dmt_scheduler_pkg.pkb.sql
@@packages/dmt_talent_prof_hdl_gen_pkg.pkb.sql
@@packages/dmt_talent_prof_results_pkg.pkb.sql
@@packages/dmt_talent_prof_transform_pkg.pkb.sql
@@packages/dmt_talent_prof_validator_pkg.pkb.sql
@@packages/dmt_tax_card_hdl_gen_pkg.pkb.sql
@@packages/dmt_tax_card_results_pkg.pkb.sql
@@packages/dmt_tax_card_transform_pkg.pkb.sql
@@packages/dmt_tax_card_validator_pkg.pkb.sql
@@packages/dmt_upload_dict_pkg.pkb.sql
@@packages/dmt_util_pkg.pkb.sql
@@packages/dmt_w2_bal_hdl_gen_pkg.pkb.sql
@@packages/dmt_w2_bal_results_pkg.pkb.sql
@@packages/dmt_w2_bal_transform_pkg.pkb.sql
@@packages/dmt_w2_bal_validator_pkg.pkb.sql
@@packages/dmt_worker_hdl_gen_pkg.pkb.sql
@@packages/dmt_worker_results_pkg.pkb.sql
@@packages/dmt_worker_transform_pkg.pkb.sql
@@packages/dmt_worker_validator_pkg.pkb.sql
@@packages/dmt_work_sched_hdl_gen_pkg.pkb.sql
@@packages/dmt_work_sched_results_pkg.pkb.sql
@@packages/dmt_work_sched_transform_pkg.pkb.sql
@@packages/dmt_work_sched_validator_pkg.pkb.sql
@@packages/dmt_zx_fbl_gen_pkg.pkb.sql
@@packages/dmt_zx_results_pkg.pkb.sql
@@packages/dmt_zx_runner_pkg.pkb.sql
@@packages/dmt_zx_transform_pkg.pkb.sql
@@packages/dmt_zx_validator_pkg.pkb.sql
@@packages/fbt_bip_pkg.pkb.sql
@@packages/utl_zip.pkb.sql

prompt == Grants made ==
@@grants/grants_made.sql

prompt == Seed data ==
@@seed/dmt_cemli_split_cfg.sql
@@seed/dmt_bip_report_tbl.sql
@@seed/dmt_erp_interface_options_tbl.sql
@@seed/dmt_rest_lookup_tbl.sql
@@seed/dmt_bu_lookup_tbl.sql
@@seed/dmt_config_tbl.sql
@@seed/dmt_pipeline_def_tbl.sql
@@seed/dmt_cemli_catalog_tbl.sql
-- E1 (2026-07-08): the Mock engine-test registrations are TEST-SETUP only —
-- test/unit/setup_mock_objects.sql, run by test/unit/test_queue_engine.sql.
-- A production install carries no dispatchable mock objects and no MOCK_*
-- config keys.

prompt == Recompile schema ==
exec dbms_utility.compile_schema(schema => user, compile_all => false)

prompt == Scheduler jobs (created disabled, enabled last — after seeds + recompile) ==
@@jobs/dmt_queue_poller.sql
begin
  dbms_scheduler.enable('"DMT_QUEUE_POLLER"');
end;
/

prompt == Invalid objects remaining (expected: DB-link/Fusion-dependent) ==
select object_type, object_name from user_objects where status='INVALID' order by 1,2;

prompt == db_full/install.sql complete ==
