-- =============================================================================
-- 01_create_dmt_lookup.sql
-- Run as ADMIN
-- Creates the DMT_LOOKUP schema for EBS-to-Fusion value mapping management.
-- =============================================================================

begin
  execute immediate q'[
CREATE USER DMT_LOOKUP IDENTIFIED BY "<SET_PASSWORD_HERE>"
    DEFAULT TABLESPACE DATA
    TEMPORARY TABLESPACE TEMP]';
exception when others then
  if sqlcode not in (-1920) then raise; end if;  -- ORA-01920: user exists
end;
/

-- Basic privileges
GRANT CREATE SESSION TO DMT_LOOKUP;
GRANT CREATE TABLE TO DMT_LOOKUP;
GRANT CREATE SEQUENCE TO DMT_LOOKUP;
GRANT CREATE PROCEDURE TO DMT_LOOKUP;
GRANT CREATE VIEW TO DMT_LOOKUP;
GRANT CREATE SYNONYM TO DMT_LOOKUP;
GRANT UNLIMITED TABLESPACE TO DMT_LOOKUP;

-- Required for BIP SOAP calls
GRANT EXECUTE ON SYS.UTL_HTTP TO DMT_LOOKUP;
GRANT EXECUTE ON SYS.UTL_RAW TO DMT_LOOKUP;
GRANT EXECUTE ON SYS.DBMS_LOB TO DMT_LOOKUP;

-- Cross-schema access to DMT_OWNER (credentials + logging)
GRANT SELECT ON DMT_OWNER.DMT_CONFIG_TBL TO DMT_LOOKUP;
GRANT SELECT ON DMT_OWNER.DMT_LOG_TBL TO DMT_LOOKUP;
GRANT INSERT ON DMT_OWNER.DMT_LOG_TBL TO DMT_LOOKUP;

-- DMT_OWNER access to DMT_LOOKUP tables (for EBS DB link pass-through)
GRANT SELECT, INSERT, UPDATE, DELETE ON DMT_LOOKUP.DMT_LKP_EBS_VALUES TO DMT_OWNER;
GRANT SELECT ON DMT_LOOKUP.DMT_LKP_MAPPING TO DMT_OWNER;
GRANT SELECT ON DMT_LOOKUP.DMT_LKP_FUSION_VALUES TO DMT_OWNER;
GRANT SELECT ON DMT_LOOKUP.DMT_LKP_TYPE_CONFIG TO DMT_OWNER;
