-- =============================================================================
-- 06_seed_type_config.sql
-- Run as DMT_LOOKUP
-- Seeds DMT_LKP_TYPE_CONFIG with all 17 supported lookup types.
-- =============================================================================

INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('BUSINESS_UNIT_NAME', 'Business Unit / Operating Unit name', '/Custom/DMT/Lookups/BU_NAME_DM.xdm', '/Custom/DMT/Lookups/BU_NAME_RPT.xdo', 'FINANCE');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('LEGAL_ENTITY_NAME', 'Legal Entity name', '/Custom/DMT/Lookups/LEGAL_ENTITY_DM.xdm', '/Custom/DMT/Lookups/LEGAL_ENTITY_RPT.xdo', 'FINANCE');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('PAY_TERMS', 'Payment Terms (supplier/PO usage)', '/Custom/DMT/Lookups/PAY_TERMS_DM.xdm', '/Custom/DMT/Lookups/PAY_TERMS_RPT.xdo', 'PROCUREMENT');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('PAYMENT_TERMS', 'Payment Terms (AP invoice usage)', '/Custom/DMT/Lookups/PAY_TERMS_DM.xdm', '/Custom/DMT/Lookups/PAY_TERMS_RPT.xdo', 'FINANCE');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('HZ_LOCATIONS', 'Ship-to / Bill-to Location codes', '/Custom/DMT/Lookups/HZ_LOCATIONS_DM.xdm', '/Custom/DMT/Lookups/HZ_LOCATIONS_RPT.xdo', 'PROCUREMENT');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('LEDGER_NAME', 'General Ledger name', '/Custom/DMT/Lookups/LEDGER_DM.xdm', '/Custom/DMT/Lookups/LEDGER_RPT.xdo', 'FINANCE');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('FA_BOOK', 'Fixed Assets Book Type Code', '/Custom/DMT/Lookups/FA_BOOK_DM.xdm', '/Custom/DMT/Lookups/FA_BOOK_RPT.xdo', 'FINANCE');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('FA_PRORATE_CONVENTION', 'Fixed Assets Prorate Convention', '/Custom/DMT/Lookups/FA_PRORATE_DM.xdm', '/Custom/DMT/Lookups/FA_PRORATE_RPT.xdo', 'FINANCE');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('FA_METHOD_CODE', 'Fixed Assets Depreciation Method', '/Custom/DMT/Lookups/FA_METHOD_DM.xdm', '/Custom/DMT/Lookups/FA_METHOD_RPT.xdo', 'FINANCE');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('TAXPAYER_COUNTRY', 'ISO Country/Territory codes', '/Custom/DMT/Lookups/TERRITORY_DM.xdm', '/Custom/DMT/Lookups/TERRITORY_RPT.xdo', 'COMMON');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('DEPARTMENT', 'HR Department name', '/Custom/DMT/Lookups/DEPARTMENT_DM.xdm', '/Custom/DMT/Lookups/DEPARTMENT_RPT.xdo', 'HCM');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('LOCATION', 'Work Location code', '/Custom/DMT/Lookups/LOCATION_DM.xdm', '/Custom/DMT/Lookups/LOCATION_RPT.xdo', 'HCM');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('JOB', 'Job name', '/Custom/DMT/Lookups/JOB_DM.xdm', '/Custom/DMT/Lookups/JOB_RPT.xdo', 'HCM');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('GRADE', 'Grade name', '/Custom/DMT/Lookups/GRADE_DM.xdm', '/Custom/DMT/Lookups/GRADE_RPT.xdo', 'HCM');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('PAYROLL', 'Payroll name', '/Custom/DMT/Lookups/PAYROLL_DM.xdm', '/Custom/DMT/Lookups/PAYROLL_RPT.xdo', 'HCM');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('SALARY_BASIS', 'Salary Basis name', '/Custom/DMT/Lookups/SALARY_BASIS_DM.xdm', '/Custom/DMT/Lookups/SALARY_BASIS_RPT.xdo', 'HCM');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE) VALUES
('LEGAL_EMPLOYER', 'Legal Employer organization name', '/Custom/DMT/Lookups/LEGAL_EMPLOYER_DM.xdm', '/Custom/DMT/Lookups/LEGAL_EMPLOYER_RPT.xdo', 'HCM');

COMMIT;
