-- =============================================================================
-- 06_seed_type_config.sql
-- Run as DMT_LOOKUP
-- Seeds DMT_LKP_TYPE_CONFIG with all 17 supported lookup types.
-- Re-run-safe: each row is inserted only if its LOOKUP_TYPE is not present.
-- =============================================================================

INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'BUSINESS_UNIT_NAME', 'Business Unit / Operating Unit name', '/Custom/DMT/Lookups/BU_NAME_DM.xdm', '/Custom/DMT/Lookups/BU_NAME_RPT.xdo', 'FINANCE' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'BUSINESS_UNIT_NAME');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'LEGAL_ENTITY_NAME', 'Legal Entity name', '/Custom/DMT/Lookups/LEGAL_ENTITY_DM.xdm', '/Custom/DMT/Lookups/LEGAL_ENTITY_RPT.xdo', 'FINANCE' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'LEGAL_ENTITY_NAME');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'PAY_TERMS', 'Payment Terms (supplier/PO usage)', '/Custom/DMT/Lookups/PAY_TERMS_DM.xdm', '/Custom/DMT/Lookups/PAY_TERMS_RPT.xdo', 'PROCUREMENT' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'PAY_TERMS');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'PAYMENT_TERMS', 'Payment Terms (AP invoice usage)', '/Custom/DMT/Lookups/PAY_TERMS_DM.xdm', '/Custom/DMT/Lookups/PAY_TERMS_RPT.xdo', 'FINANCE' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'PAYMENT_TERMS');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'HZ_LOCATIONS', 'Ship-to / Bill-to Location codes', '/Custom/DMT/Lookups/HZ_LOCATIONS_DM.xdm', '/Custom/DMT/Lookups/HZ_LOCATIONS_RPT.xdo', 'PROCUREMENT' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'HZ_LOCATIONS');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'LEDGER_NAME', 'General Ledger name', '/Custom/DMT/Lookups/LEDGER_DM.xdm', '/Custom/DMT/Lookups/LEDGER_RPT.xdo', 'FINANCE' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'LEDGER_NAME');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'FA_BOOK', 'Fixed Assets Book Type Code', '/Custom/DMT/Lookups/FA_BOOK_DM.xdm', '/Custom/DMT/Lookups/FA_BOOK_RPT.xdo', 'FINANCE' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'FA_BOOK');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'FA_PRORATE_CONVENTION', 'Fixed Assets Prorate Convention', '/Custom/DMT/Lookups/FA_PRORATE_DM.xdm', '/Custom/DMT/Lookups/FA_PRORATE_RPT.xdo', 'FINANCE' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'FA_PRORATE_CONVENTION');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'FA_METHOD_CODE', 'Fixed Assets Depreciation Method', '/Custom/DMT/Lookups/FA_METHOD_DM.xdm', '/Custom/DMT/Lookups/FA_METHOD_RPT.xdo', 'FINANCE' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'FA_METHOD_CODE');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'TAXPAYER_COUNTRY', 'ISO Country/Territory codes', '/Custom/DMT/Lookups/TERRITORY_DM.xdm', '/Custom/DMT/Lookups/TERRITORY_RPT.xdo', 'COMMON' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'TAXPAYER_COUNTRY');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'DEPARTMENT', 'HR Department name', '/Custom/DMT/Lookups/DEPARTMENT_DM.xdm', '/Custom/DMT/Lookups/DEPARTMENT_RPT.xdo', 'HCM' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'DEPARTMENT');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'LOCATION', 'Work Location code', '/Custom/DMT/Lookups/LOCATION_DM.xdm', '/Custom/DMT/Lookups/LOCATION_RPT.xdo', 'HCM' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'LOCATION');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'JOB', 'Job name', '/Custom/DMT/Lookups/JOB_DM.xdm', '/Custom/DMT/Lookups/JOB_RPT.xdo', 'HCM' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'JOB');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'GRADE', 'Grade name', '/Custom/DMT/Lookups/GRADE_DM.xdm', '/Custom/DMT/Lookups/GRADE_RPT.xdo', 'HCM' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'GRADE');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'PAYROLL', 'Payroll name', '/Custom/DMT/Lookups/PAYROLL_DM.xdm', '/Custom/DMT/Lookups/PAYROLL_RPT.xdo', 'HCM' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'PAYROLL');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'SALARY_BASIS', 'Salary Basis name', '/Custom/DMT/Lookups/SALARY_BASIS_DM.xdm', '/Custom/DMT/Lookups/SALARY_BASIS_RPT.xdo', 'HCM' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'SALARY_BASIS');
INSERT INTO DMT_LKP_TYPE_CONFIG (LOOKUP_TYPE, DESCRIPTION, BIP_CATALOG_PATH, BIP_REPORT_PATH, MODULE)
SELECT 'LEGAL_EMPLOYER', 'Legal Employer organization name', '/Custom/DMT/Lookups/LEGAL_EMPLOYER_DM.xdm', '/Custom/DMT/Lookups/LEGAL_EMPLOYER_RPT.xdo', 'HCM' FROM dual
WHERE NOT EXISTS (SELECT 1 FROM DMT_LKP_TYPE_CONFIG WHERE LOOKUP_TYPE = 'LEGAL_EMPLOYER');

COMMIT;
