-- =============================================================================
-- 11_fix_mapping_identity_and_audit.sql
-- Run as DMT_LOOKUP
-- Two fixes that resolve user-reported defects on the Value Mapping IG:
--   1. ORA-32795 "cannot insert into a generated always identity column"
--      MAPPING_ID was GENERATED ALWAYS AS IDENTITY. APEX IG submits MAPPING_ID
--      (even as NULL) on every row save which Oracle rejects on GENERATED ALWAYS.
--      Switch to GENERATED BY DEFAULT ON NULL AS IDENTITY so APEX-supplied NULLs
--      fall through and the sequence still auto-fills.
--   2. CREATED_BY / CREATED_DATE / LAST_UPDATE_BY / LAST_UPDATE_DATE
--      should be auto-populated server-side, never editable. Add a single
--      BEFORE INSERT OR UPDATE trigger that stamps these on every row.
-- Idempotent — run as many times as needed.
-- =============================================================================

-- 1. Identity column fix
ALTER TABLE DMT_LKP_MAPPING
   MODIFY MAPPING_ID GENERATED BY DEFAULT ON NULL AS IDENTITY;

-- 2. Audit-column trigger
-- Static SQL only: SYS_CONTEXT('APEX$SESSION','APP_USER') returns the APEX
-- user when the session runs under APEX and NULL otherwise, so non-APEX
-- sessions (SQL*Plus, SQLcl, plain JDBC) fall back to USER. No dependency
-- on the APEX API, no dynamic SQL.
CREATE OR REPLACE TRIGGER DMT_LKP_MAPPING_BIU
BEFORE INSERT OR UPDATE ON DMT_LKP_MAPPING
FOR EACH ROW
DECLARE
   l_user VARCHAR2(100);
BEGIN
   l_user := COALESCE(
                SYS_CONTEXT('APEX$SESSION','APP_USER'),
                USER
             );

   IF INSERTING THEN
      :NEW.CREATED_BY   := l_user;
      :NEW.CREATED_DATE := SYSDATE;
   END IF;

   :NEW.LAST_UPDATE_BY   := l_user;
   :NEW.LAST_UPDATE_DATE := SYSDATE;
END;
/

SHOW ERRORS TRIGGER DMT_LKP_MAPPING_BIU;
